### ISSUE TITLE
Allow users other than the owner of a collaborative playlists to modify it

### ISSUE THREAD

**Issue by jtabone16** [spotify/web-api#100]
Please :D

**Comment by thelinmichael** [comment]
Thanks for adding this feature request @jtabone16. This isn't a feature that's planned in the short-term, but it'd be a nice addition to the API for sure. I'd like to add that it's not necessarily as simple as it may seem, depending on which users should be allowed to modify the collaborative playlist.

From the top of my head, I can see several options. 
- Only followers, as you've suggested
- Anyone (similar to any Spotify client)
- Anyone that the owner of the playlist has granted (for a limited amount of time)

I'm going to modify the title of this feature request to make it more open to different types of access control applied to editing collaborative playlists using the API. 

As always, any use-case that you could share is always helpful to spark a discussion either here or internally at Spotify.

**Comment by jtabone16** [comment]
Awesome, thanks @thelinmichael!

**Comment by cantoniazzi** [comment]
Hi.
How was this feature? Answer me, please! :+1: 
Thanks, guys!

**Comment by jtabone16** [comment]
@cantoniazzi I don't think it was ever implemented lol

**Comment by Waiski** [comment]
I'd appreciate this feature very much. Here's a use case, as @thelinmichael requested:

Within my group of friends, we have created collaborative playlists to listen to on various occasions. However, sometimes someone adds a track that I don't like, but I dare not remove it in case everyone else likes it. To solve this (without discussing each track individually), I'd like a system where each person invited to a playlist could somehow rate and vote on the tracks, and the playlist would only include the best-rated or most-voted tracks or something. This would require all users to be able to modify the same playlist.

For now, I think I'm going to solve this by creating the same playlist for everyone individually, but this is not ideal, since then everyone needs to visit my app to update their copy of the playlist, in case other user's votes have altered it.

**Comment by chrisde1997** [comment]
Any news on this feature? It's possible in the Spotify application so why not make it available in the API as well ;)

**Comment by Nessworthy** [comment]
Bumping this request as a one that's still desired. Trying to build a jukebox to control a work playlist!

**Comment by cantoniazzi** [comment]
Actually it's possible to create a collaborative playlist using the apps, but this feature not is present in the API yet. Right? @thelinmichael

**Comment by nostrame** [comment]
+1

**Comment by arirawr** [comment]
Hey all,

As per our [new developer support process](https://github.com/spotify/web-api#creating-an-issue), any feature requests that have no plans to be considered in the next 6 months will be closed as wontfix.

We do not have any plans to implement this in the next 6 months and thus will close as wontfix.

We encourage you and other members of the community to continue to share use cases and your support for this feature, as it helps us prioritize features going forward. You will be able to comment on this issue even after it is closed. We will also post any updates here relating to this suggestion when they happen.

**Comment by MPaalanen** [comment]
While I do understand the possible problems regarding allowing collaborative playlist control over api as well, I do have a situation where it would give one solution to existing problem.

If you happen to have a popular collaborative playlist with lots of followers it tends to get a lot of spamming from indie artists who think it is a good tactic to just search for collab lists and inject their portfolio systematically, no matter what the genre / context of the playlist in question is.

Of course one solution would be to just make the list non collaborative, but that often is really something you do not want. 

Hence the idea that came to my mind is that one could create a simple program using the web api where you could help the owner of the list to have some control over what the playlist will contain and prevent abuse. One could just tag certain artists as "blacklisted" and the script would then systematically check that if it finds those artists included in the playlist in question, it would remove them.

This way one could more easy make sure that even collaborative playlists wouldn't be easy targets for trolls and spammers.

**Comment by BloodShura** [comment]
Sad that it's been 3 years and this hasn't been implemented... If it was, it would definitely open up a great variety of possibilities for music collaboration between users.

**Comment by selaromdotnet** [comment]
I'll bump this up, why not? One thing I'm curious about is, if the app can do this, exactly why can't the API? Can the same implementation or restrictions that allow that to happen not be used to restrict the API from doing it as well?

Not sure if this will be seen or be helpful in any way, would making a new thread revive this discussion?

**Comment by Nyzl** [comment]
+1 from me

I'd love to be able to use the API to add a song. The use case is that every Friday we have a team playlist in Slack, i have a bot that helps in the playlist creation and sharing but it would be awesome if we could add songs to this collaborative playlist too.

For example during playlist creation could their be an option for authorising specific app ids to add songs. Just a thought.

**Comment by jtabone16** [comment]
Can't believe this is still an issue 😢
