### ISSUE TITLE
Your app keeps crashing quen trying to share music...

### ISSUE THREAD

**Issue by mismaiel1988** [spotify/web-api#1000]
Issue found on February 19th 2015.

#### Endpoint(s):
* `GET /v1/users/{user_id}`

#### Scope(s):
* None (application is not using authentication)

#### Steps to reproduce:
1. Open the API Console
2. Call the `get-users-profile` endpoint with `user_id` `%5E`

#### Expected behaviour:
A public user object as described on `https://developer.spotify.com/web-api/object-model/#user-object-public`.

#### Actual behaviour:
500 Server Error (consistently)

**Comment by 0xNF** [comment]
You might have better luck with your issue at the support or community sections of the Spotify website

https://support.spotify.com/us/

https://community.spotify.com/

**Comment by arirawr** [comment]
Hi there! This issue tracker is only for bugs and suggestions for the [Spotify Web API](https://developer.spotify.com/documentation/web-api/). For issues with the official Spotify app, please contact [Spotify customer support](https://support.spotify.com/us/).
