### ISSUE TITLE
Productionalising the app

### ISSUE THREAD

**Issue by DeluFernando** [spotify/web-api#1005]
We've developed an app using the Spotify APIs. 
1.What's process to be followed for the app to be moved from developer environment to production?
2.What's the maximum number of load (users) your system could handle concurrently from the app?

**Comment by arirawr** [comment]
Hi @DeluFernando - you can apply for commercial approval from Spotify by going to your Dashboard, selecting "Create a Client ID", then clicking "Yes" when asked about commercial use. You will then be asked to fill out some information about your app, which will be forwarded to the partnerships team for approval. Please note that this process can take some time.

I can't provide exact numbers for rate limits, as they're subject to change. Rate limiting is applied per application based on Client ID, and regardless of the number of users who use the application simultaneously. You can read more about rate limiting [here](https://developer.spotify.com/documentation/web-api/#rate-limiting).

**Comment by DeluFernando** [comment]
Hi Arielle,

Thanks for your update.

I've submitted the app per your instructions. Would I be able to get an
update on the current status please? The login email is delu.lorex@gmail.com

Kind regards,
Delu

**Comment by DeluFernando** [comment]
Hi Arielle,

Could you please share with me contact details of the representative at
Spotify who could assist with approvals for integration.

Kind regards,
Delu
