### ISSUE TITLE
Add web API endpoint to add a new device

### ISSUE THREAD

**Issue by ashleyvaccaro** [spotify/web-api#1007]
I think this guy needs to be opened again. Just relating back to this guy https://github.com/spotify/web-api/issues/540

I think it's definitely worth adding something like this. Makes it easier to add a device to a user.

**Comment by bih** [comment]
Hello @ashleyvaccaro,

Thanks for reaching out! I posted a comment on #540 so others can see. As this is a duplicate, I'll close this as such 👍
