### ISSUE TITLE
Playlist error on playing song "Not Found" response

### ISSUE THREAD

**Issue by flakronkadriu** [spotify/web-api#1018]
On the https://open.spotify.com/browse/featured page when playing a playlist from this page the songs start playing but if i go to the playlist page(https://open.spotify.com/user/spotify/playlist/37i9dQZF1DX10zKzsJ2jva) and i click the same song it says that the song is not found and the api return 404. 

Issue found on September 7th 2018.

#### Endpoint(s):
https://api.spotify.com/v1/episodes/5MFptOt9ONEiku7glFTTl3

#### Expected behaviour:
Play songs from the playlist page also.

#### Actual behaviour:
404 Not Found Error (consistently)

**Comment by bih** [comment]
Hello @flakronkadriu,

I can't seem to reproduce this error. It works fine for me with the playlist you provided (Viva Latino) and with numerous tracks in the playlist:

Here is the cURL request I ran:
```curl
curl -X "PUT" "https://api.spotify.com/v1/me/player/play?device_id=[DEVICE ID HERE]" --data "{\"context_uri\":\"spotify:playlist:37i9dQZF1DX10zKzsJ2jva\",\"offset\":{\"uri\":\"spotify:track:0s5DNDV6LAKn2u2Ufa3VjQ\"}}" -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: Bearer [ACCESS TOKEN]"
```

As this hasn't had any activity and we haven't received any other reports of this issue, I'm going to close it as inactive. If you're continuing to have issues, feel free to open a new ticket with detailed reproducible steps so we can help.

Hope this helps! 👍
