### ISSUE TITLE
Wildcard (*) not functional when query contains a field filter

### ISSUE THREAD

**Issue by Dyphen** [spotify/web-api#1021]
Issue found on September 7th 2018, was working on September 6th 2018. 

#### Endpoint(s):
* `GET /v1/search`

#### Scope(s):
* None (application is not using authentication)

#### Steps to reproduce:
1. Open the API Console
2. Search for an album respondent to tag:new or tag:hipster, for instance, tag:new and Paul McCartney's Egypt Station (released 09/07/18) with a wildcard, e.g.,
`q=paul+mccartne*+tag:new&type=album`

#### Expected behaviour:
Wildcard matches "mccartney" and returns Egypt Station, it's intended functionality as denoted in the API, in responses to previous issues here, and in practice for several years. 

#### Actual behaviour:
Search query returns nothing.

1. Query without wildcard, e.g.,
`q=paul+mccartney+tag:new&type=album`
Works and returns Egypt Station.
2. Wildcard query without tag:new, e.g., 
`q=paul+mccartne*&type=album` 
Works and returns Egypt Station (among other Paul McCartney albums). 

This was working 3 days ago, so it must be something new. 

Please advise.

**Comment by J0nKn1ght** [comment]
Any news on this issue?  We're also having problems with it.  It seems that wildcards only work at word boundaries, for example:

`https://api.spotify.com/v1/search?q=track%3Asmell*%20artist%3Anirvana&type=track`

doesn't work, but:

`https://api.spotify.com/v1/search?q=track%3Asmells*%20artist%3Anirvana&type=track`

does (i.e. the only difference is the 'smell*' vs 'smells*').

To all intents and purposes, this makes our website look like it's broken.

**Comment by J0nKn1ght** [comment]
An update on this is that we found that switching the order of the parameters from:

`q=track:smell* artist:nirvana&type=track`

to

`q=artist:nirvana track:smell*&type=track`

works fine, so I'm not sure if it's an issue with the position of the wildcard within a sequence of tags?

**Comment by bih** [comment]
Hello @Dyphen,

I can't seem to reproduce the errors you're facing. Both `paul mccartney tag:new` and `paul mccartne*` both return the expected results. It might have been a temporary issue that seems resolved, plus we haven't received more reports regarding this.

As this seems inactive, I will assume this is resolved. If you continue to have issues, feel free to open a new ticket and reference this issue.

**Comment by shillshocked** [comment]
In the Spotify app, I can get non-ascii titles by searching NOT a* NOT b* NOT c* NOT d* NOT e* NOT f* NOT g* NOT h* NOT i* NOT j* NOT k* NOT l* NOT m* NOT n* NOT o* NOT p* NOT q* NOT r* NOT s* NOT t* NOT u* NOT v* NOT w* NOT x* NOT y* NOT z* NOT 0* NOT 1* NOT 2* NOT 3* NOT 4* NOT 5* NOT 6* NOT 7* NOT 8* NOT 9*

But in the api, the results total randomly changes with each request. What gives?
