### ISSUE TITLE
Cannot play song according playlist context: "Non supported context uri"

### ISSUE THREAD

**Issue by andrewcdoh** [spotify/web-api#1024]
Issue found on September 11, 2018.

#### Endpoint(s):
* `PUT /v1/me/player/play`

#### Scope(s):
* 'user-read-private user-read-email user-read-playback-state user-read-currently-playing user-modify-playback-state user-read-recently-played user-library-read'

#### Steps to reproduce:
1. Play any song and while adding the new playlist context_uri to the body of request

![image](https://user-images.githubusercontent.com/20361028/45370871-cb077280-b5ae-11e8-9c32-8c0663309022.png)

#### Expected behaviour:
To play the song according the playlist context and offset

#### Actual behaviour:
status: 400, message: "Non supported context uri"

![image](https://user-images.githubusercontent.com/20361028/45371023-1883df80-b5af-11e8-8264-0ce9e800aaac.png)

**Comment by arirawr** [comment]
I've been able to reproduce this and we're looking into it. Thanks for the report!

**Comment by arirawr** [comment]
@andrewcdoh This should now be fixed. Thank you for the report!

**Comment by jeremenichelli** [comment]
Hey @arirawr, I just ended up here with the same error but for songs, then eld me to this one: https://github.com/spotify/web-api/issues/675 which kinda solve the issue I was having with the player API.

Maybe your team could update the docs and specify when is suitable to use `context_uri` (artists, playlist, albums) and when to use the `uris` array (songs) 😊
