### ISSUE TITLE
The available_markets returned empty for tracks restricted to Japan

### ISSUE THREAD

**Issue by AngyNoT** [spotify/web-api#1025]
Issue found during August 2018 but was already found 1 or 2 years ago.

#### Endpoint(s):
* `GET /v1/tracks/{id}`

#### Scope(s):
* None

#### Steps to reproduce:
1. Open the API Console
2. Call the `Get a Track` endpoint with `id` : `6dmRLLkwPKFvAHRgM6cBY6` or  `25KUPF5gNRASy9jLpw7g8H`

#### Expected behaviour:
A track object with a list of countries in `available_markets`

#### Actual behaviour:
`available_markets` is empty for many tracks I found. All of these tracks are from Japan and probably restricted to its market. 
I don't understand why `available_markets` does not simply return `['JP']`.

I know that there is already an issue about that but it was closed 2 years ago while the bug still remains.

**Comment by 0xNF** [comment]
I too have noticed this behavior, specifically with Japanese songs, and would love to get it fixed.

**Comment by loisaidasam** [comment]
Are you explicitly passing `market` to your API call?

I noticed a similar issue: #1048

**Comment by AngyNoT** [comment]
No I'm not passing market to my API calls.
But I don't think it's similar to your issue, in my case the available_markets is there, but empty.

**Comment by bih** [comment]
Hello @AngyNoT,

Thanks for the bug report! I can confirm that I'm still seeing the issue here. We're investigating this issue and will post here with updates.

**Comment by AngyNoT** [comment]
Looks like it's now fixed! Thank you :)
