### ISSUE TITLE
Update order of playlists

### ISSUE THREAD

**Issue by harryt04** [spotify/web-api#1031]
This is not a bug, merely a suggestion or request for the API. 

For years, I've wanted the ability to sort my playlists and playlists within a playlist folder alphabetically. For those of us who have 50-70+ playlists, finding them is quite the chore, and sorting them is even worse. As a web developer, I had the idea to make a simple app that could sort your playlists for you and tracks for you (since you can't sort on mobile, you have to go with whatever order you added the tracks in), and I can do the latter, but as far as I can tell, you can only get a list of a person's playlists, not update them.  So, I'd love for a "PUT" endpoint to be added for playlists in addition to the existing "GET". If you'd like to implement some sort of security stipulation that playlists can't be deleted within that PUT request, I'm fine with that. I simply want to reorder them so they are easier to find, especially on mobile.

I think this would be a very useful feature and likely very easy to implement.

**Comment by arirawr** [comment]
Hey @harryt04 ! Does this endpoint cover your use case? https://developer.spotify.com/documentation/web-api/reference/playlists/change-playlist-details/

**Comment by harryt04** [comment]
@arirawr No, that does not cover my use case. That end point is great if you want to change or update a single playlist. I want to change the order of my playlists as they appear in my spotify client, both desktop and mobile, without having to hand sort them myself (say, the most recently edited playlist being on top, or sort them alphabetically).  What other information do you need from me..?

**Comment by arirawr** [comment]
That's it - just wanted to clarify what you were looking for. Thanks for the suggestion! We'll post here if there are any updates.

**Comment by arirawr** [comment]
Hey @harryt04 - we've looked into this and this isn't something that's technically possible, as the ordering of playlists is set on the client. I'm going to close this issue as wontfix, and will update here if anything changes.
