### ISSUE TITLE
Start/Resume a user's playback endpoint not working properly from jQuery.ajax()

### ISSUE THREAD

**Issue by turnipjs** [spotify/web-api#1032]
Issue found on September 13th 2018.

#### Endpoint(s):
* `https://api.spotify.com/v1/me/player/play`

#### Scope(s):
* `user-modify-playback-state`

#### Steps to reproduce:
1. Use jQuery to send a request with the following code, replacing ${userToken} (or just set the `userToken` var) with the user token and `uri` in the data object with the uri of the song you want to play:
```javascript
$.ajax({
    method: "PUT",
    url: 'https://api.spotify.com/v1/me/player/play',
    headers: {
        'Authorization': `Bearer ${userToken}`,
    },
    data: {
         "uris": [uri]
    },
    success: function(response) {
        console.log("response:");
        console.log(response);
    }
});
```

#### Expected behaviour:
Play the song specified by the Spotify URI like it does when using the online console or when using curl.

#### Actual behaviour:
`400: Malformed JSON`

#### Additional:
- Sending this request without any data in the data object works like it should, starting playback as if you hit the play button on the Spotify client as long as there is nothing playing.
- Curling or using the console with the same JSON results in expected behavior.
- Using the same formatting for the `$.ajax()` call works for other endpoints such as:
```javascript
$.ajax({
    url: 'https://api.spotify.com/v1/search',
    headers: {
        'Authorization': "Bearer ${userToken}"
    },
    data: {
        'q': 'space oddity',
        'type': 'track',
        'market': 'US'
    },
    success: function(response) {
        console.log("response:");
        console.log(response);
    }
});
```

**Comment by jscholes** [comment]
You're setting the data parameter to a plain JavaScript object, and JQuery isn't converting it to JSON because this isn't the default behaviour.  Try:

        data: JSON.stringify({
             "uris": [uri]
        }),
        contentType: 'application/json',
        processData: false,
