### ISSUE TITLE
FR: retrieve another user's currently playing track

### ISSUE THREAD

**Issue by dandv** [spotify/web-api#1034]
Use case: co-play the same track with my friend (as long as their session isn't private).

This information *is* accessible (I see it in my Linux client for example):

![image](https://user-images.githubusercontent.com/33569/45739662-5765f680-bba8-11e8-89d5-e20df41486d4.png)

In other words, https://developer.spotify.com/documentation/web-api/reference/player/get-the-users-currently-playing-track/ could take a userId parameter, and return the track last played by that user.

**Comment by arirawr** [comment]
Hey @dandv - thanks for the suggestion. As mentioned in #83, we have no plans to implement this functionality. We will update on that issue and on our developer blog if that changes.
