### ISSUE TITLE
Add city-related data

### ISSUE THREAD

**Issue by wolnicat** [spotify/web-api#1037]
Is there a possibly to open up the API to include city-related data for artists?

- Number of followers of artist in a city
- Number of active listeners of artist in a city

Tracking the popularity of an artist given a city can be used to:
- Identify rising artists in a city
- Identify most popular artists in a city
- Allow cafes, restaurants, shops, and bars to curate playlists based on artist popularity in their city
- Allow music stores to stock records and merchandise based on artist popularity in their city
- Predict the likelihood an artist's future tour passes through a city
- Predict future concert venues for artists
- Predict time period of concert ticket availability for a venue before it sells out

**Comment by arirawr** [comment]
As raised in #188, we do not currently have any plans to implement this functionality in the API. We will update that issue and our developer blog if anything changes.
