### ISSUE TITLE
How to access "Monthly Listeners" ?

### ISSUE THREAD

**Issue by jonathonpitman** [spotify/web-api#1043]
How can I access the Monthly Listeners value? I'd be ok to access it only for the account / artist logged in... but don't see why you wouldn't be able to look this up for any artist as its publicly available.  
I noticed there is a site Chartmetric.io that shows this value. So surely there is a way to access this.

Any guidance is appreciated.

**Comment by arirawr** [comment]
Hey @jonathonpitman - as mentioned on issue #130, we don't have any plans to implement this in the near future. We will post on that issue with any updates.
