### ISSUE TITLE
Search returns no results when track title includes a colon

### ISSUE THREAD

**Issue by SHxKM** [spotify/web-api#1044]
Issue found on September 27th 2018.

#### Endpoint(s):
* `GET /v1/search`

#### Scope(s):
* None (application is not using authentication)

#### Steps to reproduce:
1. Open the API Console
2. Call the [`search`](https://developer.spotify.com/console/get-search-item/) endpoint with `q` `The Best of Pantera: Far Beyond the Great Southern Cowboys' Vulgar Hits! ` ([spotify link](https://open.spotify.com/album/2pEiQl69yF4PZDXIBoZjaH))

#### Expected behaviour:
The above release appears in the JSON response.

#### Actual behaviour:
The response is:

```
{
  "albums": {
    "href": "https://api.spotify.com/v1/search?query=The+Best+of+Pantera%3A+Far+Beyond+the+Great+Southern+Cowboys%27+Vulgar+Hits%21+&type=album&market=US&offset=0&limit=50",
    "items": [],
    "limit": 50,
    "next": null,
    "offset": 0,
    "previous": null,
    "total": 0
  }
}
```

Even if the title is truncated further, the release doesn't show up. It doesn't even show up in search on the website..it seems that the colon is culprit:

> (The Best of Pantera**:** Far Beyond the Great Southern Cowboys' Vulgar Hits! )

**Comment by arirawr** [comment]
This issue should now be resolved. Thanks for your report!

Please feel free to reopen if you continue to see this issue occur.

**Comment by lrholmes** [comment]
Hey @arirawr! I've just encountered this issue with another track: [re:stacks by Bon Iver](https://open.spotify.com/track/6EhAIEtuOABhRJ17NjDVjL?si=ytjqUPPmQliyYAD4erYSoA). I'm not sure if it's the same exact thing as this issue, but I just can't create a search that will return this track at all (other tracks are returned, but only covers and remixes that are all named differently: "Re: Stacks"). 

I've been trying it here: https://developer.spotify.com/console/get-search-item/?q=re%3Astacks&type=track&market=&limit=&offset=

Let me know if I should create a new issue for this 🙂thanks!
