### ISSUE TITLE
Productionalising the app

### ISSUE THREAD

**Issue by DeluFernando** [spotify/web-api#1045]
Hi
I've submitted an application requesting permission to use Spotify API in my mobile app for commercial purposes. This was done more than 2 weeks back. How can I track the progress of this application & is there a phone number to contact the relevant department/ personnel?
Thanks,
Delu 

Issue found on February 19th 2015.

#### Endpoint(s):
* `GET /v1/users/{user_id}`

#### Scope(s):
* None (application is not using authentication)

#### Steps to reproduce:
1. Open the API Console
2. Call the `get-users-profile` endpoint with `user_id` `%5E`

#### Expected behaviour:
A public user object as described on `https://developer.spotify.com/web-api/object-model/#user-object-public`.

#### Actual behaviour:
500 Server Error (consistently)

**Comment by jscholes** [comment]
If you are only using the Spotify Web API to develop a non-streaming SDA, you may not need approval from Spotify to distribute it.  Please consider seeking legal advice if your interpretation of how the [Developer Terms of Service](https://developer.spotify.com/terms/) apply to your application is unclear - you might be delaying the release of your application unnecessarily.

**Comment by arirawr** [comment]
Hey @DeluFernando - I'm not a lawyer and I can't interpret the terms of service for you. I recommend consulting a lawyer if you are unclear on the terms.

The commercial approval process can take some time, up to several months. If your application is successful, our partners team will reach out to you directly.
