### ISSUE TITLE
Add ability to see all playlists where an artist exists in

### ISSUE THREAD

**Issue by Hugs70** [spotify/web-api#1046]
Is it possible to use the Spotify API in order to get all playlists where a single artist in involved?

**Comment by 0xNF** [comment]
Nope. There are no APIs at present that involve querying for playlist information, except for whatever you can wrangle from the generic [search endpoint](https://developer.spotify.com/documentation/web-api/reference/search/search/).

**Comment by Hugs70** [comment]
Any idea how services like https://www.spotontrack.com or https://spektrol.io are able to track playlists filtered by artists?

**Comment by 0xNF** [comment]
Well according to Spot On Track, "The data shown on this website are retrieved directly from the Spotify API." Without being able to see some of what their actual output is the best I can wager is that they are creatively monitoring top artists, category playlists, and search endpoint results.

**Comment by Hugs70** [comment]
I've used Spot On Track for a while and technically I was able to get full info about every playlist related to "any" artist I needed (not only top artists).

**Comment by bih** [comment]
Hello @Hugs70,

Thanks for reaching out! We don't have this as a feature today, and I'm not sure how others are doing. There isn't an official API for it, and for this reason I'll mark this as a suggestion.

As we don't have plans to add this in the next 6 months and it isn't a popular suggestion, I'm going to close this as <kbd>wontfix</kbd> for now. If this changes in the future, we'll comment here. In the meantime, I suggest you and others add your +1 and comment with your use cases for what you'd use this for. It'll help us evaluate suggestions to prioritize in the future.
