### ISSUE TITLE
Null track in Release Radar

### ISSUE THREAD

**Issue by mjwsteenbergen** [spotify/web-api#1049]
Issue found on October 5th 2018. I have some automation running every week to get the songs from my release radar. This week it crashed, as it contained a track with the value null. This is unexpected behaviour, right?

#### Endpoint(s):
* `GET /v1/users/{ownerId}/playlists/{playlistId}/tracks`

#### Scope(s):
* Whatever is needed for it

#### Steps to reproduce:
1. Call the endpoint as my user

#### Expected behaviour:
Get all songs in my release radar

#### Actual behaviour:
```
{
  "href": "https://api.spotify.com/v1/playlists/37i9dQZEVXbfI1OlPEmIm5/tracks?offset=0&limit=100",
  "items": [
    {
        17 valid songs (songs that contain a track)
    },
    {
      "added_at": "2018-10-04T22:00:00Z",
      "added_by": {
        "external_urls": {
          "spotify": "https://open.spotify.com/user/"
        },
        "href": "https://api.spotify.com/v1/users/",
        "id": "",
        "type": "user",
        "uri": "spotify:user:"
      },
      "is_local": false,
      "primary_color": null,
      "track": null,
      "video_thumbnail": {
        "url": null
      }
    },
    {
        more valid songs
    }
  ],
  "limit": 100,
  "next": null,
  "offset": 0,
  "previous": null,
  "total": 30
}
```

**Comment by arirawr** [comment]
Hey @mjwsteenbergen - there are many reasons why a track may return null (availability in a specific market, ID change, removal from catalogue, etc). Your application should be able to check for and handle this possibility.

PS. you've got some great tracks on that Release Radar 💪
