### ISSUE TITLE
URGENT: Production API returns empty list of categories

### ISSUE THREAD

**Issue by iosdev-republicofapps** [spotify/web-api#105]
Last night this code worked perfectly.  Now this morning, without any changes on my end, your API is returning an empty list of categories.

This is a showstopping bug for us!  Do you have an ETA for a fix?  Was this a bad deploy?  Did something change in this API in an undocumented fashion or was this a bad push?

PLEASE HELP.

Now we get:
```
curl -X GET "https://api.spotify.com/v1/browse/categories?locale=en_US&country=US&limit=10&offset=0" -H "Accept: application/json" -H "Authorization: Bearer __VALID_BUT_REDACTED_OAUTH_TOKEN__"

HTTP/1.1 200 OK
Access-Control-Allow-Headers: Accept, Authorization, Origin, Content-Type
Access-Control-Max-Age: 604800
X-Content-Type-Options: nosniff
Content-Encoding: gzip
Transfer-Encoding: chunked
Access-Control-Allow-Credentials: true
Strict-Transport-Security: max-age=31536000;
Keep-Alive: timeout=600
Server: nginx
Connection: keep-alive
Cache-Control: public, max-age=600
Date: Tue, 25 Aug 2015 18:59:08 GMT
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, POST, OPTIONS, PUT, DELETE
Content-Type: application/json; charset=utf-8
{
  "categories" : {
    "href" : "https://api.spotify.com/v1/browse/categories?country=US&locale=en_US&offset=0&limit=10",
    "items" : [ ],
    "limit" : 10,
    "next" : null,
    "offset" : 0,
    "previous" : null,
    "total" : 0
  }
}
```

**Comment by thelinmichael** [comment]
We're looking into this right now @iosdev-republicofapps.

**Comment by iosdev-republicofapps** [comment]
Thanks!

**Comment by iosdev-republicofapps** [comment]
Hi @thelinmichael  ,

Any updates or ETA for a fix?  :-)  This is still an issue for us.

Thanks!

**Comment by thelinmichael** [comment]
We've got a high priority on solving this as quickly as possible @iosdev-republicofapps. That said, I'd like to avoid giving an ETA, but definitely ASAP. Will let you know when there are any updates.

**Comment by iosdev-republicofapps** [comment]
Thanks @thelinmichael !

**Comment by drojas** [comment]
It seems fixed... @iosdev-republicofapps

**Comment by thelinmichael** [comment]
This bug was just patched. Apologies for the inconvenience, we'll of course try to make sure this doesn't occur again. Thanks for the report @iosdev-republicofapps, we appreciate it!

**Comment by iosdev-republicofapps** [comment]
@thelinmichael @drojas thanks so much for fixing this and quickly!  Much appreciated!  :-)

I just verified - this API call now succeeds again in both your Web API Console and in our unit tests.

Thanks again and best wishes!

Joel

**Comment by drojas** [comment]
oh no.. @iosdev-republicofapps I don't work at spotify... I was just as eager as you waiting for this to be fixed so I wanted to share the good news..

cheers..

**Comment by thelinmichael** [comment]
Thanks for being quicker than us @drojas! :-) And kudos to you for having proper testing @iosdev-republicofapps!

**Comment by drojas** [comment]
;) thanks to you @thelinmichael for making our lifes easier

**Comment by iosdev-republicofapps** [comment]
Ah OK, understood @drojas .

And much thanks to @thelinmichael !
