### ISSUE TITLE
Refused to display [playlist_link] in a frame because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'none'".

### ISSUE THREAD

**Issue by MrAmericanMike** [spotify/web-api#1052]
I am getting this error on console once I login when trying to embed a playlist using the iframe code provided on the examples pages.

It was discussed also here, but I was requested to report in here.
https://community.spotify.com/t5/Other-Partners-Web-Player-etc/Web-Site-play-button-problem/m-p/4581637#M57610

This happens on Google Chrome: Versión 69.0.3497.100 (Build oficial) (64 bits)

Any help would be appreciated.

**Comment by gorkacrisiscreativa** [comment]
I have the exact same problem. Dis you solve it @MrAmericanMike ?

Thanks!

**Comment by jamespearn** [comment]
I also have the exact same problem. It seems to be something that Spotify must fix.

**Comment by bih** [comment]
Hello,

I'm using Chrome 71.0.3578.98 (Official Build) (64-bit) and I don't seem to have the same issue. I imagine either Chrome or the respective team at Spotify has fixed the issue.

Can you confirm if you're still having this issue?

**Comment by MrAmericanMike** [comment]
Can confirm the embed is working on Chrome 71 0 3578 98
Thanks.

**Comment by gorkacrisiscreativa** [comment]
Yes, It's working for me too! Thanks!

**Comment by bih** [comment]
No worries, glad to hear it! I'll close this issue as resolved. Feel free to open a new ticket if you're continuing to have issues 🙂

**Comment by jamespearn** [comment]
Still broken for me. Same error message.

Chrome version: 71.0.3578.98

![screenshot](https://user-images.githubusercontent.com/6469010/51109581-eea92680-17f5-11e9-95ee-06d9128e4d4b.png)

**Comment by garrettjoecox** [comment]
For anyone that runs into this again and finds this thread, ensure your URL has the `/embed/` prefix in the pathname. For example 
```
https://open.spotify.com/embed/album/0ODLCdHBFVvKwJGeSfd1jy
```
vs 
```
https://open.spotify.com/album/0ODLCdHBFVvKwJGeSfd1jy
```

This solved the issue for me, hope it helps someone else.

**Comment by hknguyenvu** [comment]
It's broken for me now on normal Chrome but can show in incognito mod :(

Test with https://developer.spotify.com/documentation/widgets/generate/play-button/ on Version 80.0.3987.122 (Official Build) (64-bit) (Max OS)
