### ISSUE TITLE
Information Request: Spotify Web API Preview Audio Clips Licensing

### ISSUE THREAD

**Issue by Minneth** [spotify/web-api#1054]
Question logged on October 10th 2018.

#### Endpoint(s):
* `GET /v1/artists/{artist-id}`

#### Question Overview:
Hi,

First of all, apologies if this is logged in the wrong place but I was directed here by the Spotify Support Team.

I work for a software development business and we've recently finished a new Alexa app that allows users to find live music events in their area and preview short clips of each band so they can decide whether they want to check out the show. In order to play short previews, we currently look up each artist using the Spotify Web API and stream the Preview Audio Clip back to the user.

The app is completed however we're struggling to get it over the finish line and approved by Amazon's approvals team as they have raised a question over my rights to use these previews within the Alexa app.

According to their feedback, we must:

"Please provide documentation demonstrating that you have the right to use the music content within your skill. The documentation must be either a confirmation letter from the intellectual property rights holder or a copy of the applicable license."

Can someone please direct me to the right team so I can ascertain what needs to be done, and how we can get this over the finish line?

Thanks very much.

**Comment by jscholes** [comment]
Here are Spotify's [Developer Terms of Service](https://developer.spotify.com/terms/).  Nobody here will be able to interpret them for you and provide legal advice.  If you are in doubt as to whether those terms of service permit you to develop the application you have described, please consult with a legal professional.

**Comment by arirawr** [comment]
Hey @Minneth - I'm not a lawyer and can't interpret our Terms of Service for you. If you are unsure about our terms, I recommend you consult legal counsel.

If you would like to apply for commercial approval, you can do so by creating a client ID on the [Spotify for Developers Dashboard](https://developer.spotify.com/dashboard) and selecting "Yes" when asked about commercial approval. This will prompt you to answer some more detailed questions about your integration, which will be sent to our partnerships team.

**Comment by dmoerman** [comment]
@arirawr is there a way to contact the partnerships team? At my company we applied for a commercial license and would like to know the status of it.
