### ISSUE TITLE
Search command returning 404 Error Not Found when there should be a LOT more results...

### ISSUE THREAD

**Issue by maxiedaniels** [spotify/web-api#1055]
#### Endpoint(s):
* `GET /v1/search?q=piano&type=playlist&limit=50&offset=9951

Take the above API command. If you search an offset of 9950, you'll see at the bottom that there should be a total of roughly 147,000 playlists to go through. But if I increase the offset by 1, I get '404 Error Not Found'.

This wasn't happening a year ago so I'm not sure what's changed.. any ideas?

**Comment by jscholes** [comment]
You can only fetch up to 10000 search results when using the Web API.  With an offset of 9951 and a limit of 50, you're asking for results 9951-10001, and getting a 404 because results 10001 and over aren't available.

**Comment by bih** [comment]
Echoing what @jscholes said, we only permit up to 10,000 results when using search. For all legal use cases of our Developer Platform, it should be sufficient for your use case. If you have any specific use cases where you'd need more, I'd recommend that sharing with us so we can investigate.

As this hasn't had much activity, I'm going to close this issue. Cheers!
