### ISSUE TITLE
[Question] Spotify auth with scope

### ISSUE THREAD

**Issue by guilhermefcs** [spotify/web-api#1056]
hi guys, I need some help with Spotify authentication.
I’m creating a shortcut on Apple Siri Shortcuts that I can search on 
Google/Genius a lyric based on the song that I’m listening. Spotify has a endpoint for that -> Currently Playing Track (https://developer.spotify.com/console/get-users-currently-playing-track/)
Even I don’t know how to code, I was able to make it works with a test oauth token from the link above (sadly it last just 1 hour) 
I started reading Spotify docs (https://developer.spotify.com/documentation/general/guides/scopes/) and found out that I need a scope auth with user-read-currently-playing to make it works, but I don’t have a website to register my “app” and create a redirect URI. 
Do I really need this scope to access my own account info? I already registered as developer so I have ClientID and ClientSecret.

Any ideas to make it work?
I can share the siri shortcut if anyone is interested.

thanks in advance

**Comment by guilhermefcs** [comment]
@0xnf thx :) gonna check those links.I confess its hard being a no-coder haha but I’m curious and apple made shortcuts/workflow easy to understand. Spotify docs helps a lot too. I’m happy that I almost got it done (at least worked with a test oath token)

thx again for your time!

**Comment by bih** [comment]
Hello,

Sounds like an awesome shortcut. Seems like others have gotten it working on the Shortcuts app and being able to find the relevant page once you have the current playing track should be fairly straightforward. I'll close this as this isn't a bug and it seems resolved! 😄
