### ISSUE TITLE
Alarm/Timer Playback Mode

### ISSUE THREAD

**Issue by reavishk** [spotify/web-api#106]
Can you develop an alarm/timer playback mode? It would be so useful for timed activities - like workouts or getting ready in the morning. If you do an hour workout, you could have 5 hours worth of songs in one playlist, but set the timer to 10 minutes to let you know when to switch activities, or to an hour to let you know when your workout is over.

I could see this being useful in virtually any situation where people would generally need an alarm or reminder of some kind. It would be a cool and unique feature to have, and could even promote more frequent use of Spotify simply due to its functionality. If I'm cooking dinner and need to remember to take food out of the oven in 30 minutes, rather than setting the alarm on my phone, I might be more inclined to put some music on and set my Spotify timer.

**Comment by thelinmichael** [comment]
@reavishk, could you please forward this to https://community.spotify.com/t5/New-Ideas/ct-p/newideas? This Github repository is used as an issue tracker for developers using the Spotify's Web API. Also, posting on the Community site will give your idea a lot more attention from both Spotify and regular users. Thank you!
