### ISSUE TITLE
oEmbed Deep Linking API doesn't support Playlists

### ISSUE THREAD

**Issue by KokkieH** [spotify/web-api#1060]
Not sure if this is the correct place, but I can't find any documentation on developer.spotify.com regarding your oEmbed support.

It seems playlist embeds if the playlist URL is copied from the web player does not work on the WordPress CMS. However, it works perfectly if the playlist URL is copied from the desktop and mobile apps (tested with MacOS and Android apps).

Example web app URL: `https://open.spotify.com/playlist/37i9dQZF1DWZeKCadgRdKQ`

Example desktop app URL: `https://open.spotify.com/user/spotify/playlist/37i9dQZF1DWZeKCadgRdKQ?si=2CukGXk1RtSjIf6DVmNpXg`

Trying to embed the web app URL leads to the URL being displayed, rather than the embedded player which appears if the desktop app URL is used.

The only "announcement" I'm aware of of oEmbed support being added to Spotify is this [Twitter thread](https://twitter.com/nicklas2k/status/330112083964342273).

As per the instructions there and the Spotify section on https://oembed.com/, the [WordPress code](https://core.trac.wordpress.org/browser/trunk/src/wp-includes/class-oembed.php#L79) contains the following to implement oEmbed support on that software:

`'#https?://(open|play)\.spotify\.com/.*#i'     => array( 'https://embed.spotify.com/oembed/', true ),`

The regex used there should cover both the web and desktop versions of the Playlist URL as far as I can tell, and there has been no recent changes on WordPress's end in this regard, so has there been a change in the URL structure or in oEmbed implementation itself on Spotify's end that would cause the one URL not to work?

If there has been a change on Spotify's end, but a change needs to be made on WordPress's end to compensate for that, can you please provide details on what needs to be done? Then I can open a ticket with WordPress instead to have this fixed there.

**Comment by james4388** [comment]
look like they not support playlist yet

**Comment by bih** [comment]
Hello,

This seems like an old API that we don't officially support. I will still however raise this with the appropriate team at Spotify and see if I can get this resolved for you after the festive period.

**Comment by KokkieH** [comment]
Thank you :)

**Comment by KokkieH** [comment]
It appears since I reported this the desktop app's playlist URL structure has been changed to be the same as the web player's, `https://open.spotify.com/playlist/*`, and that URL is now working properly when embedding on WordPress. So it looks like whatever was causing this issue has since been resolved.

**Comment by mdrovdahl** [comment]
Hi @bih pinging you since you previously commented here and might have some relevant knowledge...it looks like playlist support in oembeds has gone away again? Can you comment on that or redirect me to someone who can?

FWIW, I'm happy to help bridge communication between Spotify and Automattic if it's helpful...

Ref: 
* https://github.com/WordPress/gutenberg/issues/22302
* https://core.trac.wordpress.org/ticket/50116

**Comment by mdrovdahl** [comment]
Noting I emailed Bilawal @bih directly today asking if he can prioritize this. We have an increasing number of WordPress users submitting issue reports for this =(
