### ISSUE TITLE
Devices empty array if player in pause

### ISSUE THREAD

**Issue by Gabs496** [spotify/web-api#1062]
Issue found on February 18th October 2018

#### Endpoint(s):
* https://api.spotify.com/v1/me/player/devices

#### Scope(s):
* user-read-playback-state

#### Steps to reproduce:
1. Open a Spotify player
2. Play a song
3. Open the API Console
4. Call the `get-users-available-devices
5. Stop playing song
6. Call the `get-users-available-devices

#### Expected behaviour:
Player info would be get from API also if it is in pause.

#### Actual behaviour:
Empty array

**Comment by arirawr** [comment]
Hey @Gabs496 - is the device you're using a mobile device? It's possible that the device is disconnecting from Spotify on pause, which can be the case on some mobile devices.

You can read about devices not appearing in the device list [here](https://developer.spotify.com/documentation/web-api/guides/using-connect-web-api/).

**Comment by bih** [comment]
Closing this as inactive.

Feel free to open a new ticket if your issue persists and it doesn't fit inside of the [Devices not Appearing on Device List in the Spotify Connect Web API](https://developer.spotify.com/documentation/web-api/guides/using-connect-web-api/#devices-not-appearing-on-device-list) explanations.

**Comment by maurotrentini** [comment]
I am experiencing a similar problem. I currently have my Spotify desktop app open and I am logged in with my account. When I retrieve the available devices via the API, it returns an empty list. If I start playback on Spotify desktop and call the same API endpoint, it returns my device successfully. 

Shouldn't it return my device even when playback is paused?
