### ISSUE TITLE
Last played playlists

### ISSUE THREAD

**Issue by Isetnt2** [spotify/web-api#1069]
Is there any way to only fetch the 20 last played playlists much like the `https://api.spotify.com/v1/me/player/recently-played` endpoint for last played tracks.

**Comment by jscholes** [comment]
> Is there any way to only fetch the 20 last played playlists

Not currently, no.  Your only option is to fetch the list of recently played tracks (maximum of 50) and then filter for ones with a playlist context.

**Comment by Isetnt2** [comment]
Could this at some point be added to the API?

**Comment by Isetnt2** [comment]
> > Is there any way to only fetch the 20 last played playlists
> 
> Not currently, no. Your only option is to fetch the list of recently played tracks (maximum of 50) and then filter for ones with a playlist context.

Do you know the best way to do so and filter out tracks from the same playlist?

**Comment by arirawr** [comment]
Hey @Isetnt2 - I'm closing this issue in favour of the suggestion you made at #1084.
