### ISSUE TITLE
How to get recently played songs.

### ISSUE THREAD

**Issue by atakangktepe** [spotify/web-api#107]
Hello,
I want get recently played songs with javascript. Please help :sos: :)

**Comment by petermakowski** [comment]
This feature is not yet available.

https://github.com/spotify/web-api/issues/12

**Comment by atakangktepe** [comment]
But facebook is can this. This is not impossible.

**Comment by thelinmichael** [comment]
Nothing is imposible @atakangktepe, but it's unfortunately a question of priorities. The issues @petermakowski is linking to in his response cover the features you're requesting, so any changes will be posted there.

**Comment by atakangktepe** [comment]
@thelinmichael thanks for help!

**Comment by dandv** [comment]
https://developer.spotify.com/documentation/web-api/reference/player/get-recently-played/
