### ISSUE TITLE
I can't seem to fill out the captcha for the Accounts API?

### ISSUE THREAD

**Issue by jkroes** [spotify/web-api#1070]
All of my old scripts based on the Spotify API have become unusable since Spotify implemented this captcha requirement for logging in. I've tried four times, and I have yet to clear the captcha. Each round it's made me attempt a dozen captcha attempts that are overly vague (Do I include the post when selecting squares with traffic lights, or just the lights themselves?) or too small to see (Is that a car in the distance?). This isn't a traditional issue in the sense of a bug. I just wanted to be on the record as opposing this system.

**Comment by bih** [comment]
Hello @jkroes,

Thanks for reaching out. You shouldn't be seeing a CAPTCHA if you are using our official APIs, and you shouldn't be trying to login logging users in by trying to "simulate" a form interaction on <https://accounts.spotify.com/en/login>.

Can you confirm? Cheers! 👍

**Comment by jscholes** [comment]
Even though this isn't web API related, just to point out that there is an audio option, so you can listen to a short collection of words and then type them in if that's easier.  If you have UX issues with the CAPTCHA, maybe take them up with Google/ReCAPTCHA.  Hope it helps.

**Comment by bih** [comment]
As this isn't an issue with the Web API, I'm going to mark this as offtopic and close it. If you continue to have issues with this, let me know and we can forward the feedback back to the Google reCAPTCHA team. Cheers 👍
