### ISSUE TITLE
Donations

### ISSUE THREAD

**Issue by Isetnt2** [spotify/web-api#1071]
Do donations count as commercial use? Giving a donation would not grant any extra features. It would only warm the heart of the person who did for the support he's giving.

**Comment by arirawr** [comment]
Hey @Isetnt2 - I'm not a lawyer and can't interpret our Terms of Service for you. If you are unsure about our terms, I recommend you consult legal counsel.

If you would like to apply for commercial approval, you can do so by creating a client ID on the [Spotify for Developers Dashboard](https://developer.spotify.com/dashboard) and selecting "Yes" when asked about commercial approval. This will prompt you to answer some more detailed questions about your integration, which will be sent to our partnerships team.
