### ISSUE TITLE
Offset issue for searching artist

### ISSUE THREAD

**Issue by gigaByte404** [spotify/web-api#1076]
**My Search Query is:**
[https://api.spotify.com/v1/search?query=artist%3A+%22*%22+year%3A1992&type=artist&market=US&offset=0&limit=50](url)

I'm trying to find all artists of 1992 and there total count are almost 27K. But I'm having issue that i cannot increase offset above than 10K. Can someone suggest me the solution please, if there's any?

**Comment by jscholes** [comment]
As per the [documentation for the search endpoint](https://developer.spotify.com/documentation/web-api/reference/search/search/), the maximum offset (including limit) is 10,000 items.

**Comment by gigaByte404** [comment]
so can't we increase it?

**Comment by gigaByte404** [comment]
can you please change my API query which will search by name alphabet of an artist 
for 1992 year?

**Comment by arirawr** [comment]
Hey @gigaByte404 - as @jscholes has correctly pointed out, the limit for search results is 10000 and we don't have any plans on changing that right now.
