### ISSUE TITLE
/v1/me/player/play with offset uri gives 500 back

### ISSUE THREAD

**Issue by malfurion** [spotify/web-api#1079]
Issue found on November 5th 2018.

#### Endpoint(s):
* `PUT /v1/me/player/play`

#### Scope(s):
* user-modify-playback-state

#### Steps to reproduce:
1. Open the API Console
2. Call the `put-player-play` endpoint with Request Body `{
  "context_uri": "spotify:user:spotify:playlist:37i9dQZF1DXcXBWjiVEM8R",
  "offset": {
    "uri": "spotify:track:5UqCQaDshqbIk3pkhy4Pjg"
  },
  "position_ms": 0
}`

#### Expected behaviour:
Playback of the give track in given playlist on active device like described on `https://developer.spotify.com/documentation/web-api/reference/player/start-a-users-playback/`.

#### Actual behaviour:
500 Server Error (consistently)

**Comment by malfurion** [comment]
figured out that it works with all my other playlists just with that one from user spotify not

**Comment by arirawr** [comment]
Hey @malfurion - it seems that that is not a valid track ID. You can test this out the console [here](https://developer.spotify.com/console/get-track/?id=spotify%3Atrack%3A5UqCQaDshqbIk3pkhy4Pjg&market=).

If you change the track ID to another in that playlist, you can verify that it works (see console example [here](https://developer.spotify.com/console/put-play/?device_id=&body=%7B%22context_uri%22%3A%22spotify%3Auser%3Aspotify%3Aplaylist%3A37i9dQZF1DXcXBWjiVEM8R%22%2C%22offset%22%3A%7B%22uri%22%3A%22spotify%3Atrack%3A6vQ0VbsRRFOYVmjAMM8c2a%22%7D%2C%22position_ms%22%3A0%7D).)
