### ISSUE TITLE
Do the user must be primiuem to use the Spotify Connect Web API

### ISSUE THREAD

**Issue by alon1902** [spotify/web-api#1089]
I read the doc about  the Spotify Connect Web API
And I didn't understand if the userush be primiuem to use the the Spotify Connect Web API for all the command and if not what command can I use without primiuem 
Thanks ahead for all the helper

**Comment by arirawr** [comment]
Hey @alon1902,

Any user (free or premium) can use the following endpoints:
GET `/v1/me/player/devices` (Get a User's Available Devices)
GET `/v1/me/player` (Get Information About The User's Current Playback)
GET `/v1/me/player/recently-played` (Get Current User's Recently Played Tracks)
GET `/v1/me/player/currently-playing` (Get the User's Currently Playing Track)

All other /player/ endpoints are Premium only (play, pause, seek, etc)

Hope that helps! Let me know if you have any further questions.
