### ISSUE TITLE
[SOLVED] I'm having trouble reordering songs

### ISSUE THREAD

**Issue by t-MURO** [spotify/web-api#1091]
Ok, so I don't know if I'm using this endpoint correctly. If this is not how you use the snapshot_id then sorry...

#### Endpoint:
* `PUT /v1/playlists/{playlistId}/tracks`

What I want to do is completely reorder my playlist. What I do right now is using the same snapshot_id for every request. I do this since I don't want to keep track of the song's positions whenever I reorder a song.

This is a variation of what I tried (this time synchronous)

    reorder(pos){
       const index= pos || 0;
       const originalIndex = originalTracks.findIndex(track => track === sortedTracks[index]);
       axios.put(`https://api.spotify.com/v1/playlists/${this.playlist.id}/tracks`,
         {
           range_start: originalIndex,
           insert_before: index,
           snapshot_id: this.playlist.snapshot_id 
         },
         authHeader)
           .then(res => {
                  if(index  < sortedTracks.length) this.reorder(index+1);
                })
           .catch(err => this.handleError(err, () => this.reorder(index)));
        }

code might not be perfect since I changed a bit, renamed variables, etc. I put it here so you can see what the logic behind my approach is :)

#### Expected behaviour:
Playlist is sorted like it would be in sortedTracks

#### Actual behaviour:
some songs are sorted some aren't, If I run this many times, eventuelly the playlist will be sorted.

Hope someone can help me!

**Comment by arirawr** [comment]
@t-MURO great to hear you got a solution! I'm going to go ahead and close this issue - please reopen if you encounter this issue again.
