### ISSUE TITLE
API-Get a List of a User's Playlists does not return all the users playlists

### ISSUE THREAD

**Issue by adonnelly** [spotify/web-api#1096]
Issue found on 30/11/2018.

#### Endpoint(s):
* `GET https://api.spotify.com/v1/users/{user_id}/playlists`
* `GET https://api.spotify.com/v1/users/spotify/playlists`

#### Scope(s):
* All

#### Steps to reproduce:
1. Open the API Console
2. Repeatedly call the Get a List of a User's Playlists endpoint with `user_id` `spotify` from offset 0 to the end which is 350 to get all the playlists. 
3. Examine results for presence of playlist massive dance hits or new metal tracks

#### Expected behaviour:
Expected to find multiple spotify owned playlists such as
* Massive dance hits uri `https://api.spotify.com/v1/playlists/37i9dQZF1DX5uokaTN4FTR`
* New Metal Tracks uri `https://open.spotify.com/playlist/37i9dQZF1DX5J7FIl4q56G`

#### Actual behaviour:
These playlists and others are not returned.

These playlist can be found via the search api example

`https://api.spotify.com/v1/search?query=New+Metal+Tracks&type=playlist&market=GB&offset=0&limit=20`

**Comment by tebbutp** [comment]
Why doesn't api return all playlists for some users??

**Comment by falolaf** [comment]
I have also recently realized that not all the playlists I follow shows up through the web api. Actually non of the most recent playlists shows up. At least one playlist that has been working is missing. In desktop client, Win10, and Android app they show up.
Neither Spotify web player nor Spotty, via Logitech Media Server, shows the playlists.

Examples of two playlists that does not show up:
`spotify:user:spotify:playlist:37i9dQZF1DWZwtERXCS82H`
`spotify:user:spotify: playlist:37i9dQZF1DX4xuWVBs4FgJ`
The first one I have recently started to follow. The second one I have followed for a long time and it just recently stopped to show up. Both of these playlists are visible to at least one other user though.

Playlists I create myself seem to work. Haven't checked all of them though as I have a few hundred.

**Comment by falolaf** [comment]
FYI: It seems that the playlists that were missing for me are back again. Noticed that yesterday.

**Comment by bih** [comment]
This could have been a temporary issue from our end, and I cannot seem to reproduce the issues that you all were having with playlists. I'll close this as it seems resolved, but feel free to open a new ticket if you're continuing to have issues 👍
