### ISSUE TITLE
Developer console not loading for some endpoints - returning status code 900

### ISSUE THREAD

**Issue by adonnelly** [spotify/web-api#1097]
Issue found on November 23rd 2015.

#### Endpoint(s):
* `https://developer.spotify.com/console/get-playlist/`
* `https://developer.spotify.com/console/get-playlist-tracks/`

#### Steps to reproduce:
1. Open the API Console
2. Select the get-playlist endpoint

#### Expected behaviour:
The webform to try out the get-playlist api is returned. 

#### Actual behaviour:
Error 900 Fastly Internal
Fastly Internal

Guru Mediation:
Details: cache-ord1722-ORD 1543598619 1338683508

Varnish cache server

**Comment by arirawr** [comment]
Hey, I'm fixing this now. Will post when it's live.

**Comment by arirawr** [comment]
@adonnelly This should now be resolved. Thanks for the report and sorry for any inconvenience!
