### ISSUE TITLE
{'error': 'invalid_client'} Authorization Code Flow [400]

### ISSUE THREAD

**Issue by charlotteprevost** [spotify/web-api#1098]
This is one of my many attempts at  making a POST request to "https://accounts.spotify.com/api/token"
Scope was set to 'playlist-modify-public, playlist-modify-private'
I'm using Python 3.7, Django 2.1.3.
No matter what I do, response_data returns {'error': 'invalid_client'}
I've tried many things, including passing the client_id/client_secret inside the body of the request, to no avail. Please help!

```
def callback(request):

	auth_token = request.GET.get('code')     # from the URL after user has clicked accept
	code_payload = {
		'grant_type': 'authorization_code',
		'code': str(auth_token),
		'redirect_uri': REDIRECT_URI,
	}

	auth_str = '{}:{}'.format(CLIENT_ID, CLIENT_SECRET)
	b64_auth_str = base64.b64encode(auth_str.encode()).decode()

	headers = {
		'Content-Type': 'application/x-www-form-urlencoded',
		'Authorization': 'Basic {}'.format(b64_auth_str)
	}

	post_request = requests.post(SPOTIFY_TOKEN_URL, data=code_payload, headers=headers)

	response_data = json.loads(post_request.text)
        # ==> {'error': 'invalid_client'}
```

**Comment by jscholes** [comment]
The Content-Type header isn't strictly necessary here; Requests will take care of that for you.  It's also better practice to explicitly specify an encoding when encoding/decoding strings.  Something like:

    	auth_str = bytes('{}:{}'.format(CLIENT_ID, CLIENT_SECRET), 'utf-8')
    	b64_auth_str = base64.b64encode(auth_str).decode('utf-8')

Other than that, your code here looks fine.  If making those minor changes doesn't fix things, then the error is elsewhere, either on Spotify's end or in the code referenced outside of your callback (i.e. the CLIENT_ID, CLIENT_SECRET, REDIRECT_URI and SPOTIFY_TOKEN_URL constants).  If the client ID or secret were wrong, though, I wouldn't expect the initial authorization URL to work.

Some things to try:

1. Can you store a sample code and then try to make this request work with curl?
2. Does it work using a library like [Spotipy](https://spotipy.readthedocs.io/)?

**Comment by charlotteprevost** [comment]
James I owe you my firstborn child. It wasn't the encoding/decoding, it was my CLIENT_SECRET.
I'd completely forgotten I had reset it and forgot to modify my secrets file accordingly. I spent a day and a half on this, I was getting so desperate I rummaged through Russian and Chinese websites. Thank you so much. QwQ

**Comment by bih** [comment]
Hello @charlotteprevost,

Seems like this issue is resolved, thanks to @jscholes :) I'll close this, but if you have any further issues feel free to open a new ticket!
