### ISSUE TITLE
Include Artist's name in Album search results and New Releases results

### ISSUE THREAD

**Issue by digitaldesaster** [spotify/web-api#11]
https://api.spotify.com/v1/browse/new-releases?country=DE

this api call should include the name of the artist in the results. 

at the moment only the name of the album is available. to get the artist name i would have to make a second api call (https://api.spotify.com/v1/albums/{id}) to fetch the album.

regards
Alex

``` json
{
   "album_type" : "album",
   "available_markets" : [ "AD", "AR", "AT", "AU", "BG", "BO", "BR", "CH", "CL", "CO", "CR", "CY", "CZ", "DE", "DK", "DO", "EC", "EE", "ES", "FI", "GR", "GT", "HK", "HN", "HU", "IS", "IT", "LI", "LT", "LV", "MC", "MT", "MY", "NI", "NO", "NZ", "PA", "PE", "PH", "PL", "PT", "PY", "RO", "SE", "SG", "SI", "SK", "SV", "TR", "TW", "UY" ],
   "external_urls" : {
      "spotify" : "https://open.spotify.com/album/2pCUV3X3UHbtglDR0hpH5g"
   },
    "href" : "https://api.spotify.com/v1/albums/2pCUV3X3UHbtglDR0hpH5g",
    "id" : "2pCUV3X3UHbtglDR0hpH5g",
    "images" : [ {
       "height" : 640,
       "url" : "https://i.scdn.co/image/a03fb56633f1ed05fb54493412876406177bcd5f",
       "width" : 640
     }, {
       "height" : 300,
       "url" : "https://i.scdn.co/image/f8dd45072b5f6bef18d8772671ff4eeb8c1898d1",
       "width" : 300
     }, {
       "height" : 64,
       "url" : "https://i.scdn.co/image/0277723cbda5951bc35a99663f9379687967e5b7",
       "width" : 64
   }],
   "name" : "Chambers",
   "type" : "album",
   "uri" : "spotify:album:2pCUV3X3UHbtglDR0hpH5g"
}
```

**Comment by thelinmichael** [comment]
Thanks for the feedback @digitaldesaster. 

[Get a List of New Releases](https://developer.spotify.com/web-api/get-list-new-releases/) returns [Simple Album objects](https://developer.spotify.com/web-api/object-model/#album-object-simplified) which as you've pointed out doesn't include artist information. There are both drawbacks and benefits by returning Simple objects. One benefit is that it decreases the size of the response so that the client doesn't need to get more data than necessary. Another benefit is that the work in Spotify's backend will be less which decreases the response time. 

I do understand that the use cases for retrieving newly released album very often requires artist metadata as well, so I will bring this up with the team.

**Comment by sagotsky** [comment]
+1 for artist name on album search.  Apparently there are 33 albums with 2112 in the title so I need a second api call to find Rush's (assuming get v1/albums gives me an artist name).

**Comment by jsimonsson** [comment]
Hi @sagotsky 

What thelinmichael said, but you can also improve your search (not guaranteed to always work) by doing something like this:

https://api.spotify.com/v1/search?q=2112%20artist:rush&type=album&market=US

That will reduce it down to 2 results where one is the remastered album.

**Comment by mradzinski** [comment]
+1 on returning artist name when searching for albums. While searching you cannot guarantee the user will always provide an artist name, so to obtain it we'll have to make a second request to the /Albums endpoint using the obtained album ID and only then we get the artist name. Having to make a second request to obtain the artists name makes no sense to me. At the very least an artist ID should be provided in the search response to make a request to the proper endpoint and not to the /Albums one.

**Comment by rserra90** [comment]
+1 for artist name on album search.

**Comment by RafaelYousuf** [comment]
+1 for artist info, now i am making an extra call to find the artist name of the albums. I don't think one more property in the json response is a huge deal when it comes to bandwidth.

**Comment by hughrawlinson** [comment]
Hi - Artist info is now included in our [simplified album object](https://developer.spotify.com/web-api/object-model/#album-object-simplified). Thanks!
