### ISSUE TITLE
Network Exchange - Error in execution

### ISSUE THREAD

**Issue by fagnercandido** [spotify/web-api#110]
Hello,
When I am on a network 3 / 4G and automatically go into a Wi-Fi network, the Spotify stops playing music . For the implementation of the songs back to normal, only closing the application ( Ios, Iphone 5S ) and opening again.

hugs,

**Comment by thelinmichael** [comment]
HI @fagnercandido. This repository is geared towards issues related to the [Web API](https://developer.spotify.com/web-api), and I'll have to forward you to the [Community forums](https://community.spotify.com) where they'll know a lot more about bugs related to connectivity.
