### ISSUE TITLE
spotify error status 401 message "No token provided"

### ISSUE THREAD

**Issue by loicquirion** [spotify/web-api#1103]
Hey guys, i'm constantly getting this error message when I click on the link (https://api.spotify.com/v1/search?query=Frank+Sinatra&type=artist&market=CA&offset=0&limit=1) that I'm getting from my the console. 

I've added my access token inside of the following code line in my app.jsx file but nothing works either: 

import React, { Component } from 'react';
import './app.css'
import { FormGroup, FormControl, InputGroup, Glyphicon} from 'react-bootstrap';

class App extends Component {
  constructor(props) {
    super(props);
    this.state = {
      query: ''
    }
  }

search() {
    console.log('this.state', this.state);
    const BASE_URL = 'https://api.spotify.com/v1/search?';
    const FETCH_URL = BASE_URL + 'q=' + this.state.query
        + '&type=artist&limit=1';
    var accessToken = 'MY ACCESS TOKEN'
    // eslint-disable-next-line
    var myHeaders = new Headers();
    var myOptions = {
      method: 'GET',
      headers:  {
        'Authorization': 'Bearer ' + accessToken
    },
    mode: 'cors',
    cache: 'default'
  };
  fetch(FETCH_URL, myOptions )
    .then(response => response.json())
    .then(json => console.log(json))
}

  render() {
    return (
      <div className="App">
        <div className="App-title">Music Master</div>
        <FormGroup>
          <InputGroup>
           <FormControl
            type="text"
            placeholder="Search for an artist..."
            value={this.state.query}
            onChange={event => {this.setState({query: event.target.value})}}
            onKeyPress={event => {
              if (event.key === 'Enter') {
                this.search()
              }
            }}
           />
           <InputGroup.Addon onClick={() => this.search()}>
             <Glyphicon glyph="search"></Glyphicon>
           </InputGroup.Addon>
          </InputGroup>
        </FormGroup>
        <div className="Profile">
         <div>Artist Picture</div>
         <div>Artist Name</div>
        </div>
        <div className="Gallery">
          Gallery
        </div>
      </div>
    )
  }
}

export default App;

**Comment by bih** [comment]
Hello,

As mentioned by @kevinguebert, you'll need to obtain an `access_token` before you can make that request. The error message mentions that you aren't passing any access token. You can learn more about how to obtain a user's access token through the [Authorization Guide](https://developer.spotify.com/documentation/general/guides/authorization-guide/).

I'll close this, but feel free to open a new GitHub issue ticket if you're having other issues.
