### ISSUE TITLE
Compute audio features for music not on Spotify

### ISSUE THREAD

**Issue by mabrehm** [spotify/web-api#1104]
I'm looking into creating a program which would classify automatically composed music. I'd like to train this classifier on some of the proprietary features offered by the Spotify API (e.g. danceability and valence). This would require me to compute these features for the newly created music, which obviously isn't available on Spotify. So I was wondering if there is any way to compute these features for music not on Spotify. Thanks!

**Comment by bih** [comment]
Our classifiers are not available for general consumption. This isn't something I expect to change in the near future, so unfortunately I'll have to close this as <kbd>wontfix</kbd>.

I'll be sure to update the thread if this changes in the future.
