### ISSUE TITLE
What time is the New Music Friday playlist updated?

### ISSUE THREAD

**Issue by abeo** [spotify/web-api#1107]
Hello,

I am developing an app that makes use of the New Music Friday playlist which is updated every Friday. 

What time is the New Music Friday playlist updated? In what time zone? Is the update time consistent? 

Do all users globally have access to the updated playlist at the same time?

TIA,

~eric

<!--

Thanks for your interest in the Spotify Web API!

**Comment by bih** [comment]
This is what is mentioned on [our community forums](https://community.spotify.com/t5/Content-Questions/When-do-new-releases-go-up/td-p/98811):
> This uploading is done on US time, so when it appears on Spotify very much depends on which country you're in.

It also mentions they're uploaded in bulk, so this means it'll likely be on the same timezone.

**Comment by abeo** [comment]
Thanks bih for checking on this.

The community article you reference is from 2012 and refers to new music in general.  As of 2015 new music is coordinated to be released on Fridays (by most of the labels). 

My question is specifically about the Spotify New Music Friday playlist which appears to be available to all Spotify users. 

It appears that new music is available at 00:00 UTC (Greenwich) while the New Music Friday playlist is updated at 00:00 ET on Fridays, therefore some users get the updated playlist earlier than midnight ET as per their time zone. For instance, Pacific time users get the playlist at 2100 PT. 

Possibly someone at Spotify can confirm this?

Thanks again,
~eric

**Comment by bih** [comment]
@abeo Ah understood, it's slightly outside of the scope of the Web API technical support itself. In this case, I would recommend asking the Community forums as they'd be able to better support you for general questions about New Music Friday.
