### ISSUE TITLE
Can I have access to the user's play queue?

### ISSUE THREAD

**Issue by psmeireles** [spotify/web-api#1110]
Issue found on December 16th 2018.

I would like to suggest an endpoint to change the next song(s) in the user's playback. I struggle everyday with spotify's not random at all shuffle, so I would like to build my own shuffler. However, there's no endpoint in the api that provides the functionality to change the next song in playback.

Endpoint(s):
POST /v1/me/player/next-song?id={songId}
Expected behaviour:
Add the song with id = songId in the playback queue.

**Comment by syeo66** [comment]
You'll probably have to wait... as we all are at #462
