### ISSUE TITLE
How to get a list of downloaded songs on a device?

### ISSUE THREAD

**Issue by HansKre** [spotify/web-api#1111]
Is there a way to get a list of downloaded songs (available to be played offline) on a particular device (e.g. the user's currently used iPhone) through the Spotify API?

I've been going through the Spotify API and found only endpoints for retrieving user's Playlists and Library Content regardless whether they are downloaded or not.

Thanks!

**Comment by jscholes** [comment]
> Is there a way to get a list of downloaded songs (available to be played offline) on a particular device (e.g. the user's currently used iPhone) through the Spotify API?

No.

**Comment by bih** [comment]
Hello @HansKre,

We don't have any plans to add this to the Web API right now. However, it is possible to play offline content through the iOS and Android SDKs though, so it would technically possible to know this if you were to use either of those SDKs.

I have decided to close this, but if you have any compelling use cases for this feature request, feel free to open a new ticket and we'll take a look. Cheers!
