### ISSUE TITLE
Authorization 

### ISSUE THREAD

**Issue by imminna** [spotify/web-api#1114]
Issue found on Dec. 19th 2018.

#### Endpoint(s):
* `https://accounts.spotify.com/authorize/?client_id=XXX&response_type=code&redirect_uri=OOO&scope=ZZZ`

when I put the LINK in my own  browser, then something went wrong. 

![spotify_authorize](https://user-images.githubusercontent.com/36121949/50197349-a70fb600-0381-11e9-8c43-7023f431b313.png)

**Comment by bih** [comment]
Hey @imminna,

Thanks for reaching out. The URL and query parameters looks correct, so in this case it looks like that you either have:
- An invalid `client_id`
- A `redirect_uri` that isn't registered. Remember this needs to _exactly_ match including the trailing slash.
- A temporary issue with our backend. Services have been over the past 24 hours, but maybe an unexpected error occurred.

If that doesn't work, feel free to create a new ticket. We'll be able to better help you debug if you share your client ID, redirect URI and scopes - feel free to DM them to us at @SpotifyPlatform on Twitter if you'd prefer not to have them public.

Cheers!
