### ISSUE TITLE
Is there a way to access playlist tracks with only the URI via Python?

### ISSUE THREAD

**Issue by SeyiAgboola** [spotify/web-api#1115]
The main python api "spotipy"(https://spotipy.readthedocs.io/en/latest/) only allows you to get playlists when provided the username and playlist id.

I want to extract tracklist with just the playlist ID or URI or URL. No username required.

I think it's possible looking at the "Get A Playlist"[ reference page](https://developer.spotify.com/documentation/web-api/reference/playlists/get-playlist/) but I can't decipher it.

Could you steer me in the right direction at least please?

**Comment by bih** [comment]
Hi @SeyiAgboola,

The `spotipy` library is not officially maintained by Spotify, so I cannot speak about what abstractions they provide for the Web API. In terms of retrieving a tracklist using only a playlist ID (and without a username), it is actually possible [as of these changes announced a few months ago](https://developer.spotify.com/community/news/2018/06/12/changes-to-playlist-uris/).

For example, this cURL request should solve your particular issue (and replace `{access token}` and `{playlist id}`):

```curl
$ curl -X GET -H "Authorization: Bearer {access token}" https://api.spotify.com/v1/playlists/{playlist id}/tracks | jq '.'
```
