### ISSUE TITLE
Modification of Playlist Image and Description

### ISSUE THREAD

**Issue by jolantz** [spotify/web-api#112]
This is a feature that obviously Spotify can do and have used in several campaigns. It would be nice if you, providing you have a playlist-modify-xxx scope, could POST an image and a text.

**Comment by thelinmichael** [comment]
@jolantz, this feature is something that we've looked at and plan on adding to the API, but most likely not both at the same time.

**Comment by jelko** [comment]
I am working for/with a Spotify partner account. Is it possible to add the image and description through the API for those? I see that the function is available inside the Spotify application itself.
This would be a great API feature for radio stations and similar that update playlists often.

**Comment by thelinmichael** [comment]
@jelko, there's currently no separation between partner accounts and regular accounts. So as far as the API is concerned, it doesn't matter if the request is made on behalf of a Spotify partner or a regular user.

**Comment by mattvivier** [comment]
+1 on this, any status updates @thelinmichael?

**Comment by thelinmichael** [comment]
No, not right now @mattvivier. Please stay tuned though.

**Comment by scgough** [comment]
+ 1 on this - would REALLY like to see these features added. Description as the priority I think

**Comment by khamaileon** [comment]
+1

**Comment by nathancoleman** [comment]
+1 for this - needed for my project [here](https://github.com/nathancoleman/musicleague). I can quickly add support to [Spotipy](https://github.com/plamere/spotipy) once this endpoint is implemented.

**Comment by lrholmes** [comment]
Any updates or an ETA for this feature?

**Comment by Remco75** [comment]
Cool, so description works now. now move on to the image as well @spotify! 

thnx so far

**Comment by maartenrein** [comment]
Waiting for the image.... would be great guys! Thanks in advance!  - keep rocking -

**Comment by arirawr** [comment]
I have some exciting news for you 🎉 🎉 

[Upload a Custom Playlist Cover Image](https://developer.spotify.com/news-stories/2017/07/26/new-endpoint-custom-playlist-cover-image/) is now live!

Thank you for the feature request - we're excited to see what you build with it!

**Comment by lrholmes** [comment]
I've got this working on one of my projects, [Setify](https://setify.co/). Seems to work great! And wasn't too difficult to integrate either. Happy to help if anyone runs into trouble. Thanks for the great work @arirawr and the team!

**Comment by jeiemgi** [comment]
Hi @lrholmes or @arirawr, sorry if I'm missing something but ... What would be the name of the field for changing the image at the REQUEST BODY?, the docs only says: 

> Base64 encoded JPEG image data, maximum payload size is 256 KB

**Comment by lrholmes** [comment]
@jeiemgi there is no field, the request body contains only the image data as described in the docs. Here's how I'm doing it using `fetch` from my node.js server:
```
      fetch(`https://api.spotify.com/v1/users/${userId}/playlists/${playlistId}/images`, {
        method: 'PUT',
        headers: {
          'Authorization': 'Bearer [access_token]',
          'Content-Type': 'image/jpeg'
        },
        body: '/9j/4AAQSkZJRgABAQAAAQ...' // this string is 1000s characters long
      })
```
The image data that I'm using comes from an HTML canvas element that is converted to this string using the [toDataURL](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toDataURL) method.

**Comment by jeiemgi** [comment]
@lrholmes, @arirawr  Sorry, but after many attempts, **it didn't work**, I tried with Python, Postman and a Node Server, here is my code of node:


```
const http = require('http');
const fetch = require('fetch');

const hostname = '127.0.0.1';
const port = 3000;

const server = http.createServer((req, res) => {
    res.statusCode = 200;
    res.setHeader('Content-Type', 'text/plain');
    res.end('Hello World\n');
});

server.listen(port, hostname, () => {
    var request = fetch.fetchUrl('https://api.spotify.com/v1/users/jmgtz1995/playlists/3EngLubxu9iVEYKvXmKJK8/images', {
        method: "PUT",
        headers: {
            "Authorization": "Bearer {token}",
            "Content-Type": "image/jpeg"
        },
        body: "/9j/4AAQSkZJRgABAQAAAQABAAD...."
    }, function(error, meta, body) {
        console.log(body.toString());
    })
});
```
![captura de pantalla 2017-07-26 a la s 19 01 28](https://user-images.githubusercontent.com/16458560/28648646-dd0556dc-7234-11e7-8ede-a72195fce54f.png)

**Comment by lrholmes** [comment]
@jeiemgi okay I think I figured it out. You're using the [fetch](https://www.npmjs.com/package/fetch) package, which instead of the `body` field accepts `payload`. Either try changing `body` to `payload`, or (recommended) switch to using [node-fetch](https://www.npmjs.com/package/node-fetch).

**Comment by scgough** [comment]
Hello! Great news about this new feature. 
I've got some C# code to push my image but it's giving me the following error:

```
{
  "error" : {
    "status" : 401,
    "message" : "Unauthorized."
  }
}
```
I know my token is good and has the required scopes. Anyone else seen this?

**Comment by arirawr** [comment]
@scgough This endpoint uses a new scope, `ugc-image-upload`, in addition to the `playlist-modify-public` and/or `playlist-modify-private`. The user who is authenticated must also be the playlist owner.

**Comment by scgough** [comment]
@arirawr ah ok thank you. I will look at that. 
I think I'm just missing the `ugc-image-upload` scope. 

Is there a way of adding scope without having to force the user through a full 'login' again?

**Comment by arirawr** [comment]
@scgough If the user has not already granted permission for a scope, they will be prompted again with a description of the new scope(s).

**Comment by scgough** [comment]
@arirawr ok thanks for the confirmation 👍

**Comment by scgough** [comment]
@arirawr got it all working now - thanks again. 🚀

**Comment by scgough** [comment]
OK, I have another question - is it possible to delete an uploaded custom image?

**Comment by paulofabiano** [comment]
Hi, guys!

Anyone using this new endpoint for updating the playlist's cover with ruby?

I am struggling with this several ours and it is not working, I keep receiving 404 Bad Request.

When I started implementing login with Spotify (ominiauth-spotify) I was not setting the scopes but now I do. How can I revoke authorization to restart the process? I don't remember seeing the scopes list shown when I asked for authorization.

My request is like this:

```ruby
  base64 = Base64.encode64(
      open(picture.url) { |io| io.read }
    )

    HTTParty.put(
      "https://api.spotify.com/v1/users/.../playlists/.../images",
      headers: {
        'Content-Type' => 'image/jpeg',
        'Authorization' => "Bearer ..."
      },
      body: base64)
```

Any thoughts? I need this read in two days for a big event and this is driving me crazy.
Thanks, guys!

**Comment by arirawr** [comment]
Hey @paulofabiano - double check to make sure you're not including the image headers (something along the lines of `data:image/jpeg;base64`) at the start of the image data. You will need to strip out that data before sending the request.

**Comment by paulofabiano** [comment]
Thanks @arirawr! I am off the office right now but I'll double check it asap. Thanks for you help

**Comment by paulofabiano** [comment]
Hey, @arirawr! You were right. There was a '\n' in the end of the base64 string that I forgot to remove. I changed the encode64 method to the strict_encode64 and it worked. Thanks :)
