### ISSUE TITLE
Getting an 401 "invalid client" error when exchanging authorization code

### ISSUE THREAD

**Issue by jafioti** [spotify/web-api#1120]
#### Endpoint(s):
* `POST https://accounts.spotify.com/api/token`

#### My Code:
```
async void ExchangeCodes(string authorizationCode)
{
            HttpClient client = new HttpClient();
            String command = "{\"client_id\":\"" + clientId + "\", \"client_secret\":\"" + clientSecret + "\", \"grant_type\":\"authorization_code\", \"code\":\"" + authorizationCode + "\", \"redirect_uri\":\"http://httpbin.org/get\"}";
            Console.WriteLine(command);
            var content = new StringContent(command, Encoding.UTF8, "application/x-www-form-urlencoded");
            HttpResponseMessage responseMessage = await client.PostAsync("https://accounts.spotify.com/api/token", content);
            string result = await responseMessage.Content.ReadAsStringAsync();
            Console.WriteLine(result);
}
```

#### Expected behaviour:
Something like this:
```
{
   "access_token": "NgCXRK...MzYjw",
   "token_type": "Bearer",
   "scope": "user-read-private user-read-email",
   "expires_in": 3600,
   "refresh_token": "NgAagA...Um_SHo"
}
```

#### Actual behaviour:
`{"error":"invalid_client"}`

I've been stuck on this for a day or so, not sure if there's a problem in the way my body is formated or if I need any headers or anything, but I'm 100% sure my client id and client secret are correct, and I'm pretty  sure the authorization code is correct as well. (Also I'm pretty sure a different error is thrown if the authorization code is wrong but idk)

**Comment by bih** [comment]
It looks like you're sending the right information, and you're sending it as a `application/x-www-form-urlencoded` which should work from our end. One thing to note is that you'll receive an `{"error":"invalid_client"}` even if you send an empty body. For example:
```curl
curl -X POST --data "" https://accounts.spotify.com/api/token
```

It could be that your `client.PostAsync` method in your C# code isn't sending the right information. It should translate to something like this in cURL:

```curl
curl -X POST -H "Accept: application/json" \
             -H "Content-Type: application/json" \
             --data "client_id=[client id here]" \
             --data "client_secret=[client secret here]" \
             --data "grant_type=authorization_code" \
             --data "code=[authorization code here]" \
             https://accounts.spotify.com/api/token
```

Could you double check the parameters for `client.PostAsync` and let me know if that solves your problem?

**Comment by jafioti** [comment]
@bih  Thanks for the response, I went through my code and it turns out I had the body written the wrong way. Instead of the technique I used before, I went with this:

```
HttpClient client = new HttpClient();
            var commandDict = new Dictionary<string, string>
            {
                {"client_id", clientId },
                {"client_secret", clientSecret },
                {"grant_type", "authorization_code" },
                {"code", authorizationCode },
                {"redirect_uri", "http://httpbin.org/get" }
            };
            var content = new FormUrlEncodedContent(commandDict);
            HttpResponseMessage responseMessage = await client.PostAsync("https://accounts.spotify.com/api/token", content);
            string result = await responseMessage.Content.ReadAsStringAsync();
```
This worked fine for me, and I got the proper JSON response. For everyone using C# I would recommend using this method.
