### ISSUE TITLE
Can't view more than 50 saved tracks

### ISSUE THREAD

**Issue by usmansohail** [spotify/web-api#1121]
Using the web-api, I cannot get more than 50 tracks when getting the user's saved tracks. The documentation makes it clear that the limit is 50, so I was wondering if there is any alternative way to access this information?

**Comment by 0xNF** [comment]
Use the `offset` field to start past 50.

If you don't specify an offset, it defaults to zero, so repeated calls will always return the same first 50.
The request format you're looking for is `https://api.spotify.com/v1/me/tracks?offset=X` where X is the next batch of songs you want. For example, `https://api.spotify.com/v1/me/tracks?offset=50`, followed by `https://api.spotify.com/v1/me/tracks?offset=100`, etc

**Comment by bih** [comment]
To echo what @0xNF said, you'll need to specify the `offset` parameter as mentioned. This should be your issue, and as a result I'll mark this as closed given it is a question and not a bug report.

Feel free to open a new ticket if you're having issues (or have any other questions)! 👍
