### ISSUE TITLE
login issue on ps4 (country issue)

### ISSUE THREAD

**Issue by Vamyr** [spotify/web-api#1123]
update the spotify app.

![download 4](https://user-images.githubusercontent.com/46259740/50546434-d4414b80-0c40-11e9-9ec3-403a6a8ded0e.jpg)

i can use it normally on pc also on ps4 but the problem is : i can't login to my account in ps4

where i live?
UAE

**Comment by bih** [comment]
Hello @Vamyr,

Sorry to hear you're having issues. This issue tracker only deals with issues and questions related to the Spotify Web API, and not our official clients or integrations such as the Playstation integration.

The best place to go for support with that would be our [official Community forums](https://community.spotify.com). Hope this helps!
