### ISSUE TITLE
Windows Forms Application Authorization Login Screen

### ISSUE THREAD

**Issue by jafioti** [spotify/web-api#1124]
I'm trying to login to the spotify api, and I have the user login using a certain url, which displays a login screen. Once they login, they are redirected to a url that currently displays the JSON response: http://httpbin.org/get. I want to be able to get the info the login screen returns in my windows forms app, and I was told to use a URI scheme for my app, and to set the redirect uri to that scheme so that my app could receive the data.

This is where I get confused, how do I setup a URI scheme for my app and get the parameters to come through it.

I am extremely confused, any information will help!

**Comment by jscholes** [comment]
Once the user has logged into Spotify and authorized your app, as you're aware they are redirected back to the URI set for your application.  Currently, you're using an httpbin URL, which will show the authorization code in JSON in the user's browser.

This code needs to be exchanged for access and refresh tokens, which should happen inside your application.  But you shouldn't expect your users to paste or type in the code manually once the JSON has been displayed.  Instead, the user should be redirected back to a URI which represents a part of your application.  There are four fairly common ways to accomplish this:

Firstly, a URI scheme, which has already been recommended to you.  This way, your application will be invoked using a specific URI format, e.g.:

    yourapp://<auth_code>

A couple of disadvantages of this approach are:

1. Your app will need to gracefully handle being launched multiple times, as the URI handling in Windows will not communicate with an existing process.  It will start a new instance of your app every time the URI is invoked, meaning that you'll need to set up a method to communicate from new instances to the existing one.
2. Some browsers, e.g. Firefox, will prompt the user to confirm that they want to open a URI type which they haven't opened before, which could be potentially confusing for users.

For more info, see:
[Registering an Application to a URI Scheme (Windows)](https://msdn.microsoft.com/en-us/windows/desktop/aa767914)

The second method involves setting up a temporary web server inside your application.  This web server will listen on a specific port number, say, 49000 as an example, and thus can be accessed using:

    http://localhost:49000

You would then set that URL, or a variation on it, as the callback URI for your Spotify application.  The user's browser would be redirected back to that URL, performing an HTTP request to the server running inside your application's local web server.  Your application would then extract the authorization code from the request parameters, exchange them for tokens, and shut down the internal web server.

Thirdly, a server-side application, e.g. a page on your website, which acts as the redirect URL and then communicates the authorization back to your locally-running app.  The locally-running app could listen for the code e.g. via a websocket, and the page on your website would then send the code down the same websocket.

And finally, embed a web browser control inside your winforms application, allowing the user to authorize without opening the user's browser at all.  For more on this method, see:
[3-legged OAuth on desktop apps (C# & WinForm)](https://adndevblog.typepad.com/cloud_and_mobile/2016/10/3-legged-oauth-on-desktop-apps-c-winform.html)

As an aside, there is an existing .Net package for accessing the Spotify Web API, which includes code for simplifying authorization.  You can find it at:
https://github.com/JohnnyCrazy/SpotifyAPI-NET

**Comment by jafioti** [comment]
Thanks for the thorough response, will use the second option because it seems the most user friendly without requiring an actual server
