### ISSUE TITLE
Searching for items across types

### ISSUE THREAD

**Issue by jafioti** [spotify/web-api#1125]
Is there a way to search spotify across all types (artists, playlists, tracks) at once and have them sorted in the way they appear in the spotify app? I know a search across all types is possible, but it always comes up in the same order, with artists first, no matter how much more relevant the top track is. When you search in spotify, the types come up in order of relevance. How would this be done using the web api?

**Comment by bih** [comment]
Hello @jafioti,

This is indeed possible. Here's an example in cURL for a search with `hello`:

```curl
curl -X GET -H "Authorization: Bearer [access token]" -H "Accept: application/json" https://api.spotify.com/v1/search?type=album,artist,playlist,track&q=hello*&market=from_token
```

That will return you all the albums, artists, playlists, and tracks that match `hello`. Although it isn't guaranteed that the results are in the same as they would be in the official Spotify clients, it should be the same or at least very similar.

Hope this helps!

**Comment by shillshocked** [comment]
Doesn't work for me. Get:

`  "error" : {
    "status" : 400,
    "message" : "No search query"`

**Comment by fdietze** [comment]
I think the question was how to get a sorting order across different types.

Currently, the types `track` and `artist` have a field `popularity`, which you can use to sort yourself. For type `album`, the simplified album is returned, which does not have the `popularity` field.

It would be very helpful if the simplified album included a `popularity` field.
