### ISSUE TITLE
How do I make it possible for external website visitors to add tracks to a Spotify playlist via my website?

### ISSUE THREAD

**Issue by Wedvites** [spotify/web-api#1128]
Hi,

I'm wondering whether there's an app or integration that allows website visitors to add to a playlist from the website?

E.g. a wedding website where people can request a song, they pick an artist and a song (linked with Spotify's entire library) and this song is then automatically added to a playlist.

Is this already available/possible?

Thanks, 
Rob.

**Comment by bih** [comment]
Hello @Wedvites,

There isn't a "copy-paste" widget that allows visitors of your website to add tracks to a playlist, if that's what you mean. Of course, this is possible with the Web API - users could authenticate with their accounts and add to your playlist, assuming it was marked as collaborative.

The two endpoints you'd need to use are:
- [`GET /v1/search`](https://developer.spotify.com/documentation/web-api/reference-beta/#category-search)
- [`PUT /v1/playlists/{playlist_id}/tracks`](https://developer.spotify.com/documentation/web-api/reference-beta/#endpoint-add-tracks-to-playlist)

I'll close this as this is neither a bug report or a suggestion for the Web API, but feel free to ask these questions on Twitter too, we're [@SpotifyPlatform](https://twitter.com/SpotifyPlatform) :)
