### ISSUE TITLE
Spotify iOS app device menu contains unexpected device

### ISSUE THREAD

**Issue by Mideam** [spotify/web-api#1132]
Issue observed in November 2018.

It has been reported to me that a device is unexpectedly appearing in the Spotify iOS app devices menu.
The issue may relate to the Web API.
I am interested in finding out about any known circumstance under which this may occur.

#### Endpoint(s):
* None (issue observed on the Spotify iOS app)

#### Scope(s):
* None (issue observed on the Spotify iOS app)

#### Steps that may reproduce:
1. On one network, switch on and connect a [Marantz SR5009 AV Receiver](https://www.marantz.co.uk/uk/products/pages/productdetails.aspx?catid=hometheatre&subcatid=avreceiver&productid=sr5009) (via WiFi) and a non-Marantz client (via ethernet).
2. On another network, open the Spotify iOS app and access the devices menu.

#### Expected behaviour:
The Marantz SR5009 AV Receiver and the non-Marantz client are not in the devices menu.

#### Reported actual behaviour:
The non-Marantz client is in the devices menu.

**Comment by bih** [comment]
Hello @Mideam,

Thank you for reporting a bug. This repository only deals with issues and suggestions relating to the Web API, and this seems more like a potential bug with the main Spotify client. The Web API doesn't have any ability to create Spotify Connect devices, see #540.

My recommendation would be to report this in the Spotify Community. You'll be able to create a bug report [by clicking here](https://community.spotify.com/t5/forums/postpage/board-id/spotifyiOS).

As this is offtopic, I will close it. If I have misunderstood, feel free to create a new ticket and it'd be helpful if you could explain in more detail specifically how the Web API might be involved - which endpoints, reproducible steps with code, etc.

**Comment by Mideam** [comment]
Thank you.
I have created a [post](https://community.spotify.com/t5/iOS-iPhone-iPad/Unexpected-device-in-Spotify-iOS-app-devices-menu/m-p/4649672#M108198) for this at the Spotify Community.
