### ISSUE TITLE
[QUESTION] Is there a way to access "Appears On" section in the API?

### ISSUE THREAD

**Issue by arjn137** [spotify/web-api#1141]
Hi,

I am currently building an application with the Spotify API and was browsing through the documentation to find the elements I need for my app, but realized there was no way of accessing the "Appears On" section for each artist that you see toward the bottom of each profile page. Is there something I'm missing, or is there an easier way to find all songs an artist is featured on?

Thank you

**Comment by 0xNF** [comment]
There is currently no way to get this information from the Web API.

**Comment by arjn137** [comment]
Thanks you!
