### ISSUE TITLE
Linux Spotify Client doesn't start (redirected by support)

### ISSUE THREAD

**Issue by deftkHD** [spotify/web-api#1155]
Issue found on February 7th 2019.

I was redirected by your support to this site. If this issue doesn't match with the topic of this repo (I think it doesn't), it would nice if you could redirect me to a site that you think is best for this issue.

#### Steps to reproduce:
Open Spotify Client (from Startmenu, Console, etc)

#### Expected behaviour:
Spotify Client starts and I can listen to my music

#### Actual behaviour:
Dark window appears, but closes before any components are visible.
In console I can see some errors. I created two dumps:
"spotify > spotify-error 2>&1": https://www.dropbox.com/s/om7useejo1lrrfg/spotify-error?dl=0
"strace spotify > spotify-error-dump 2>&1":  https://www.dropbox.com/s/jp5uqng53lu77rp/spotify-error-dump?dl=0

#### Already tried (without any results):
- Deleted ~/.cache/spotify/Storage
- Deleted ~/.cache/spotify
- Reinstalled Spotify via apt-get (apt-get remove spotify-client, apt-get install spotify-client)

#### More information:
- Kubnutu 18.04.1 LTS (bionic)
- Kernel 4.15.0-45-generic
- Spotify Premium
- Newest Client from Spotify Repo (no Dev Build), new update was available today
- Error occurs since this update

**Comment by Grosser100** [comment]
Hillebrandb.110@gmail.com

**Comment by deftkHD** [comment]
I updated my Kernel to 4.20 and now it's working ^^
