### ISSUE TITLE
image links

### ISSUE THREAD

**Issue by anaqim** [spotify/web-api#1161]
An important question for developers that I havent found an answer to anywhere. 

Are image links permanent? 

When an artist update artist or coverart, does that generate a new link or will the old one work with the updated image?

**Comment by 0xNF** [comment]
I could have sworn I read on one of the old docs pages way back when that image links and preview url links couldn't be trusted to to be permanent and that you shouldn't cache them, but I can't find it anymore. Additionally, I went back and tested with some image links I kept from at least a year ago and they still work.

Cache at your own discretion, I guess.

**Comment by anaqim** [comment]
Thanks for the feedback. Just wish spotify staff would take the time to give a proper reply. I have noticed that playlists retain the same link even if the image keep changing, which is the background for me asking.

Dont want to make unneccesary maintainance API calls if I dont have to.

**Comment by anaqim** [comment]
Update, got reply from spotify that confirms what you said. There is no guarantee that cached links are permanent.
