### ISSUE TITLE
Cannot add tracks to playlist, 400 error due to invalid URI

### ISSUE THREAD

**Issue by EthanStraub** [spotify/web-api#1168]
Issue found on February 19th 2015.

#### Endpoint(s):
* POST https://api.spotify.com/v1/playlists/{playlist_id}/tracks 

#### Scope(s):
* All scopes

#### Steps to reproduce:
1. Open the API Console
2. Call the https://api.spotify.com/v1/playlists/{playlist_id}/tracks endpoint with playlist URI '5T5TP1CtWYKwOiH9zpJH9D' and track URI '2VVI3s5cAGh2YMDmmmEV44'

#### Expected behaviour:
Track 'Kinski Assassin' is added to playlist 'Mature Themes'

#### Actual behaviour:
400 error (consistently), with error message 'Invalid track URI: 2VVI3s5cAGh2YMDmmmEV44'

**Comment by kevinguebert** [comment]
Hm so I was successfully able to add that track to a personal playlist without any problems. I couldn't add it to your playlist as I don't own it but it seems to work. Do you mind sharing a bit more about the request?

Also I forgot to do this the first time but make sure you're passing `spotify:track:2VVI3s5cAGh2YMDmmmEV44` to the endpoint and not just `2VVI3s5cAGh2YMDmmmEV44`. See the docs ["A comma-separated list of Spotify track URIs to add"](https://developer.spotify.com/documentation/web-api/reference/playlists/add-tracks-to-playlist/) for that note that I missed the first time

**Comment by EthanStraub** [comment]
AH! How foolish I am! I clearly was passing in the tracks ID instead of the uri, which would be 'spotify:track:2VVI3s5cAGh2YMDmmmEV44'. Issue solved, I will now close it.

As I'm typing this, I just now saw kevinguebert give his reply with the same solution. Thank you for your patronage.
