### ISSUE TITLE
Play endpoint won't play the selected URI

### ISSUE THREAD

**Issue by g4w3l** [spotify/web-api#1169]
Issue found on February 21th 2019.

#### Endpoint(s):
* `PUT /v1/me/player/play`

#### Scope(s):
* None (application is not using authentication)

#### Steps to reproduce:
1. Open the API Console
2. Call the `play` endpoint with some `context_uri` or tracks via `uri`, also populate `device_id` with an active device

#### Expected behaviour:
The device should start the playback with the selected URI on the selected device.

#### Actual behaviour:
The player won't do anything. Neither load the playlist, nor resuming the playback. If a different device is selected, it won't transfer the current playback neither. The endpoint used to work well before today.

Tried within my own app, and also via Restlet and the Web API Console.
No error in response from the API (204 NO CONTENT)

**Comment by 0xNF** [comment]
Not sure if yours is the same issue, but I _always_ have to issue hit the /play endpoint twice for each desired play request.

**Comment by yoomy3** [comment]
+1 

I am writing an app using Spotify APIs, but I cannot start the playback by calling the endpoint with a song URI, even with the proper authentication.

**Comment by g4w3l** [comment]
Ok, just found out that the problem was with the `librespot` library that I use, as seen in [this issue](https://github.com/librespot-org/librespot/issues/288), just had to upgrade the app. I close this case.
