### ISSUE TITLE
Get playlists not consistent

### ISSUE THREAD

**Issue by scotty914** [spotify/web-api#117]
When making the following call

https://api.spotify.com/v1/users/scottwalstead/playlists?offset=0&limit=50

I sometimes get 3 playlists back and sometimes I get all 7 playlists back.

**Comment by thelinmichael** [comment]
Thanks for the report @scotty914. Are you making these requests with the same access token? The response will be different depending on the scopes "included" in the access token, as well as which user authorized it, if any.

**Comment by scotty914** [comment]
Yes. I'm using the same access token and it's the same user making the request. Could it be a caching issue?

Date: Mon, 5 Oct 2015 01:33:12 -0700

**Comment by thelinmichael** [comment]
@scotty914, interesting. Could you possibly post the different responses here? I'd assume that if you've cached the response it'd return the exact same content.

**Comment by scotty914** [comment]
It seems to have resolved it. Sorry for the confusion. I meant if you guys were doing the caching. On my end, I'm not caching it. If it happens again, I'll open up another issue sending the different responses.

**Comment by thelinmichael** [comment]
Thanks @scotty914! Reopen this issue and let us know.
