### ISSUE TITLE
Spotify user ID is sometimes the numeric user id instead of the username.

### ISSUE THREAD

**Issue by daannijkamp** [spotify/web-api#119]
The returned value for the "Spotify user ID" is sometimes the numeric user id instead of the username.
(Difficult to reproduce this bug)

```
GET https://api.spotify.com/v1/me
```

Expected behavior: return the username as Spotify user ID (in my case "daannijkamp")

Actual behavior: Most of the times the username. Sometimes the numeric user id (in my case "1192160446")

**Comment by JohnnyCrazy** [comment]
This is the case when the user registered via Facebook.
For example, my spotify-uri is `spotify:user:1122095781`.
