### ISSUE TITLE
GET https://api.spotify.com/v1/me/top/{type} not working - returns 400

### ISSUE THREAD

**Issue by AndreiLucaci** [spotify/web-api#1191]
Issue found on February 19th 2015.

#### Endpoint(s):
* `  GET https://api.spotify.com/v1/me/top/{type} `

#### Scope(s):
* user-top-read

#### Steps to reproduce:
1. Have a configuration / application which requests information about a user
2. Call the service with valid ACCESS_TOKEN and I get either
- an empty object (no information)
- 400
`{
  "error": {
    "status": 400,
    "message": "Only valid bearer authentication supported"
  }
}`
![](https://i.imgur.com/NbpPRKr.png)

#### Expected behaviour:
A public user object as described on `https://developer.spotify.com/documentation/web-api/reference/object-model/#artist-object-full` or `https://developer.spotify.com/documentation/web-api/reference/object-model/#track-object-full`.

The service should be working fine.

#### Actual behaviour:
400 or empty object

**Comment by kingosticks** [comment]
I get that error if I *do not* correctly set the `Authorization` header. i.e.

* This works:
```
curl -X "GET" "https://api.spotify.com/v1/me/top/artists" -H "Authorization: Bearer <MY_TOKEN>"
```
* This does not work:
```
curl -X "GET" "https://api.spotify.com/v1/me/top/artists" -H "Authorization: foobar <MY_TOKEN>"
```

**Comment by AndreiLucaci** [comment]
This wasn't the case... it was something related to Spotify's servers. All requests were denied for some endpoints, such as the login / authorization one.

The issue has been resolved since. I received news from the Spotify team:
![](https://i.imgur.com/uqr9pCb.png)
