### ISSUE TITLE
Next on Search Results Null All of the Sudden

### ISSUE THREAD

**Issue by davejhahn** [spotify/web-api#1200]
Searching seems to be broke.  

Example: https://api.spotify.com/v1/search?q=year:2019-2019+album:A*&type=album&limit=50

Returns all of the 50 objects as expected, but NEXT is null. 

Has been working without issue for last 3 1/2 months for me until today.

**Comment by FranzAjM** [comment]
Exactly! All of a sudden since yesterday afternoon, Spotify dev tem, help!!

**Comment by dave-u** [comment]
Same here. Help please Spotify!

**Comment by FranzAjM** [comment]
I tweeted to @SpotifyCares - they answered that they were going to look, but the issue is still there...

**Comment by davejhahn** [comment]
I also tweeted to @SpotifyPlaytform on Friday and haven't seen any responses.

**Comment by dave-u** [comment]
Hmm, ok, thanks both for the update

**Comment by adrianosbr** [comment]
Same here, no next. But offset seems to be working. I've patched my app to make it iterate without knowing if there are more results, which is really bad for the API.

**Comment by davejhahn** [comment]
The offset max is 10,000 though, so for my purpose and a lot of others, it is not good enough.

**Comment by adrianosbr** [comment]
Wow, how come? My app relies quite heavily on the search API but the maximum offset it ever reached was 2,000 or so (40 pages with 50 results each).

**Comment by davejhahn** [comment]
For me, it's to identify daily new releases to be considered for a playlist.  Not a UI based app.  There is a new releases filter, but it won't give you everything.  So you need to narrow it down to the year, then search in chunks that are 10K or less, and identify if it is within the day you are looking for.  Extremely inefficient.    So to do the same given this missing pagination issue, the same thing needs to be done with chunks of 50.  Imagine how many API calls and how long that takes.

**Comment by adrianosbr** [comment]
I see. My app is metadata-oriented as well (it automatically creates multitrack “sub-albums” of classical music works, used by a specialized player) but to be compliant with the API license, I managed to keep it more or less on the interface level. (The license is quite restrictive: no storing, no crunching, no derivative metadata etc.)

**Comment by FranzAjM** [comment]
@SpotifyCares has replied to me that they also replicated a similar issue with Search using the desktop client, so they've reported both issues to the "right folks".

**Comment by davejhahn** [comment]
@FranzAjM thanks for the update, sounds like it's moving now.

**Comment by adrianosbr** [comment]
@FranzAjM, thanks! (The open.spotify.com client relies on the same APIs and was indeed broken.)

**Comment by FranzAjM** [comment]
Yay! It's working again! 👍  @adrianosbr, @davejhahn, @dave-u

**Comment by adrianosbr** [comment]
I can confirm that. Great!

**Comment by davejhahn** [comment]
Excellent!

**Comment by dave-u** [comment]
Great news! Thanks Spotify and to all here for the updates.
