### ISSUE TITLE
Cannot set context_uri for play

### ISSUE THREAD

**Issue by wackazong** [spotify/web-api#1207]
Issue found on February 19th 2015.

#### Endpoint(s):
* `GET /v1/me/player/play`

#### Scope(s):
* user-modify-playback-state

#### Steps to reproduce:
1. Open the API Console
2. Call the `play` endpoint with a spotify connect device and a context_uri
3. Call the `play` endpoint with a context_uri 

#### Expected behaviour:
Spotify starts playing the music specified by the context_uri

#### Actual behaviour:
Play just restarts the currently playing track. It is not possible to get a new song to play.

#### Remark
Context_uri works when not using a spotify connect device.

**Comment by brandonferrer** [comment]
Any feedback on your resolution? I tried both context_uri and uris in my request. I'm able to continue playing on my device, but uris aren't respected. 

```
export const transferPlaybackWithTrackHere = (deviceId, token) => {
  fetch("https://api.spotify.com/v1/me/player", {
    method: "PUT",
    headers: {
      authorization: `Bearer ${token}`,
      "Content-Type": "application/json"
    },
    body: JSON.stringify({
      device_ids: [deviceId],
      play: true,
      uris: ["spotify:track:2rPE9A1vEgShuZxxzR2tZH"]
    })
  });
};
```

**Comment by wackazong** [comment]
I use https://github.com/Spotifyd/spotifyd and had to update it. That solved the problem.
