### ISSUE TITLE
Authorization page will not load when App Transport Security enabled

### ISSUE THREAD

**Issue by Doraemoe** [spotify/web-api#121]
System: OS X 10.11, Xcode 7.

Apple introduced the ATS (App Transport Security) in their latest system, now Spotify's authorization webpage will not load under WebView. It will return "NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9802)" error. The solution -- edit info.plist -- is not available to me since I'm developing a plugin in for another software and I cannot edit that software's info.plist. Will Spotify update their server setting in the near future?

This problem was also mentioned in spotify/ios-sdk#417

**Comment by iKenndac** [comment]
This is an issue with iOS ATS, not the Web API. Please discuss this in the iOS issue you mentioned.

**Comment by thelinmichael** [comment]
:+1: Closing this issue.

**Comment by Doraemoe** [comment]
I'm using WebAPI on OS X 10.11, has nothing to do with iOS. Actually the most proper place to discuss this issue would be something related to Spotify's server security, but since there is no such place...
