### ISSUE TITLE
`GET` on Discover Weekly playlist throws 404

### ISSUE THREAD

**Issue by avinassh** [spotify/web-api#122]
I first went [here](https://developer.spotify.com/web-api/console/get-playlists/#complete) to get ID of my discover weekly playlist. 

    curl -X GET "https://api.spotify.com/v1/users/sajjanshetty/playlists?limit=50" -H "Accept: application/json" -H "Authorization: Bearer my_auth"

In the response JSON, I got details of Discover Weekly Playlist:

    {
        "collaborative" : false,
        "external_urls" : {
          "spotify" : "http://open.spotify.com/user/spotifydiscover/playlist/0i80...9I5UP"
        },
        "href" : "https://api.spotify.com/v1/users/spotifydiscover/playlists/0i80...9I5UP",
        "id" : "0i80...9I5UP",
        "images" : [ {
          "height" : 300,
          "url" : "https://i.scdn.co/image/d4957f2e34bde422c89d6e0cbdcff9dc591e5ee9",
          "width" : 300
        } ],
        "name" : "Discover Weekly",
        "owner" : {
          "external_urls" : {
            "spotify" : "http://open.spotify.com/user/spotifydiscover"
          },
          "href" : "https://api.spotify.com/v1/users/spotifydiscover",
          "id" : "spotifydiscover",
          "type" : "user",
          "uri" : "spotify:user:spotifydiscover"
        },
        "public" : false,
        "snapshot_id" : "av3yBuNWlV0...ru903JqH1LOs",
        "tracks" : {
          "href" : "https://api.spotify.com/v1/users/spotifydiscover/playlists/0i80...9I5UP/tracks",
          "total" : 30
        },
        "type" : "playlist",
        "uri" : "spotify:user:spotifydiscover:playlist:0i80...9I5UP"
    } 

So I guess `0i80...9I5UP` is my playlist `id`. Now when I do `GET` on it, I get `404`:

    $ curl -X GET "https://api.spotify.com/v1/users/sajjanshetty/playlists/0i...5UP" -H "Accept: application/json" -H "Authorization: Bearer my_auth"

    {
      "error": {
        "status": 404,
        "message": "Not found."
      }
    }

**Comment by jsimonsson** [comment]
As you may notice the owner of that playlist is spotifydiscover, not you. The playlist has two unique keys, the owners name and the ID.

**Comment by avinassh** [comment]
Worked, thanks! 

    curl -X GET "https://api.spotify.com/v1/users/spotifydiscover/playlists/0i80p...5UP" -H "Accept: application/json" -H "Authorization: Bearer my_auth"
