### ISSUE TITLE
Automatic change in widget - no documentation.

### ISSUE THREAD

**Issue by alexrwilson94** [spotify/web-api#1220]
The widgets on my website have changed from the old playlist style shown on the widget generator page to a new one-track play button. (the old style still shows on the spotify dev page!

1. Can i get it back?
2. Is there a new way of displaying all tracks from a playlist without linking them individually?
3. Is there any documentation regarding these new widgets?

#### Steps to reproduce:
Embed a playlist using the widget generator, see a new one track play button generated.

#### Expected behaviour:
Playlist with all tracks displayed.

#### Actual behaviour:
One song displayed despite linking of playlist URL.

**Comment by mklaunzer** [comment]
@alexrwilson94 this issue tracker is connected to the Spotify Web API and does not cover widgets or other products.
