### ISSUE TITLE
Authorisation

### ISSUE THREAD

**Issue by achambers1997** [spotify/web-api#1224]
Hello,

I am having troubling getting the access key for the client credentials flow. 

I am new to coding, so am unsure how to format the request based on the examples here:

https://developer.spotify.com/documentation/general/guides/authorization-guide/

![94d85b05cb90857412a2b223a05be235](https://user-images.githubusercontent.com/49419026/55763553-51116c00-5a5f-11e9-9974-d2a31344dd34.png)

Thanks.

**Comment by Splixz00** [comment]
Here is an working example: https://apitester.com/shared/checks/8785e581a54b4f248b49c80863c357f0
Replace the placeholder in the `Authorization` header with your base64 encoded `client_id:client_secret` (don't encode id & secret by itself, but with the `:` between; so `base64(client_id:client_id)`)

Your mistake is that you need to set the `Content-Type` header to `application/x-www-form-urlencoded` and send the `grant_type` inside the body.

But be careful: When accessing the endpoints not used for authorization like `https://api.spotify.com/v1/me/player/` you will have to set the `Content-Type` header to the value `application/json` and also properly create your body in JSON format.
