### ISSUE TITLE
Cannot create Playlists (using new URI)

### ISSUE THREAD

**Issue by SimonMazzucca** [spotify/web-api#1228]
Issue found on February 19th 2015.

#### Endpoint(s):
* `POST /v1/me/playlists`

#### Scope(s):
* playlist-read-private playlist-modify-private

#### Steps to reproduce:
1. Open the API Console: https://developer.spotify.com/console/post-playlists/
2. Get token
3. Try It

#### Expected behaviour:
A playlist is created

#### Actual behaviour:
_POST https://api.spotify.com/v1/playlists 404
Uncaught (in promise) SyntaxError: Unexpected end of JSON input at console.bundle.js:25529_

I think that documentation is obsolete, because [this June 2018 post](https://developer.spotify.com/community/news/2018/06/12/changes-to-playlist-uris/) indicates the URI has changed to /v1/me/playlists.

I tried that too in Postman but I get a 400:

```
{
    "error": {
        "status": 400,
        "message": "Error parsing JSON."
    }
}
```

Can you please update this [page](https://developer.spotify.com/console/post-playlists/) to something that works 100%? So I can rule out issues on my end!

Thanks so much,
SM

**Comment by Pebaugh** [comment]
I'm also having a similar issue.  When I try the web console, I don't get any response at all.  The "try it" button seems unresponsive to me.

**Comment by zhammer** [comment]
the web console documentation is outdated. see: https://developer.spotify.com/documentation/web-api/reference-beta/#category-playlists

endpoint is `/users/{user_id}/playlists/{playlist_id}`

**Comment by geekarist** [comment]
> the web console documentation is outdated. see: https://developer.spotify.com/documentation/web-api/reference-beta/#category-playlists
> 
> endpoint is `/users/{user_id}/playlists/{playlist_id}`

The 'try it' link in the new documentation redirects to the old doc

**Comment by joshubrown** [comment]
Thanks for flagging this, @SimonMazzucca. The console now points to the correct endpoint, `POST /v1/users/{user_id}/playlists`
