### ISSUE TITLE
"/v1/browse/categories/inspirational" throwing an error

### ISSUE THREAD

**Issue by MattLowden** [spotify/web-api#123]
Hello,

I'm trying to use the `https://api.spotify.com/v1/browse/categories/{category_id}` API endpoint, but for certain `category_id` values an error is thrown: `Specified id doesn't exist`.

The two IDs I have experienced this error with are `kpop` & `inspirational`, however, all other IDs appear to work fine.

I've tried this method both with and without the `country` parameter & get the same results each time.

I'm also pulling the list of category IDs using the `https://api.spotify.com/v1/browse/categories` endpoint, so the IDs I'm passing on to the `https://api.spotify.com/v1/browse/categories/{category_id}` endpoint are definitely correct.

It's also worth mentioning that when sending the `kpop` & `inspirational` IDs to the `https://api.spotify.com/v1/browse/categories/{category_id}/playlists` endpoint, there is no error & the requested playlists return correctly.

Thanks in advance,
Matt

**Comment by asmitter** [comment]
Hi Matt,
Sorry for the delay. When trying to replicate I don't see those two categories in the list returned by `https://api.spotify.com/v1/browse/categories`- are you specifying a particular region or locale when requesting the list of IDs?
