### ISSUE TITLE
Search API prioritizing Indian songs 

### ISSUE THREAD

**Issue by coffeebite** [spotify/web-api#1231]
Issue found on April 26th 2019.

#### Endpoint(s):
* `GET /v1/search`

#### Scope(s):
* None (application is not using authentication)

#### Steps to reproduce:
1. Open the API Console
2. Call the `search` endpoint with `type=track&q=hello&market=US`

#### Expected behaviour:
I'd expect the API to return Adele's Hello, which is the first result in the player.

#### Actual behaviour:
Returns a dozen or so Indian tracks before Adele's Hello.

Issue isn't that I don't like Indian music. It's just that it's almost impossible that the returned song is the most relevant song for the word "Hello" in the US market.

This is not the only keyword though that prioritizes Indian music. Many other common english words seem to prioritize Indian tracks over American.

Attached is an example of the query I am making and the returned response:

<img width="2304" alt="Screen Shot 2019-04-26 at 5 23 43 PM" src="https://user-images.githubusercontent.com/763616/56842346-0a868480-6849-11e9-8186-7a301f126444.png">

**Comment by 0xNF** [comment]
I can confirm this with the developer test console. Weird.

**Comment by kevinguebert** [comment]
I have been experiencing this for a while so I've been following this thread, but it looks like they have updated something. I did this same search and it now returns Adele's Hello first for me. I wonder what they updated 🤷‍♂️

**Comment by coffeebite** [comment]
I can confirm that the issue is fixed for me. Will close the issue now. (Thanks @kevinguebert.)
