### ISSUE TITLE
/v1/me/following?type=artist returns incorrect next and href

### ISSUE THREAD

**Issue by NovaFocus** [spotify/web-api#124]
The API method /v1/me/following?type=artist returns a next and href url with /users/### instead of /me, e.g. https://api.spotify.com/v1/users/####/following?type=artist&after=0yNLKJebCb8Aueb54LYya3&limit=50 (results in error) instead of https://api.spotify.com/v1/me/following?type=artist&after=0yNLKJebCb8Aueb54LYya3&limit=50 (results in correct response).

**Comment by thelinmichael** [comment]
Thanks a lot for the report @NovaFocus! Confirmed bug.

**Comment by thelinmichael** [comment]
Just deployed a fix for this. Thanks again!

**Comment by NovaFocus** [comment]
@thelinmichael thanks for the fix.
