### ISSUE TITLE
Get Playlist Follower Count

### ISSUE THREAD

**Issue by juanhotencoding** [spotify/web-api#1247]
Is there a way to get the amount of followers a playlist has using the playlist endpoint with a playlist_id?

**Comment by 0xNF** [comment]
The playlist object returned by the [/v1/playlists/{playlist_id}](https://developer.spotify.com/console/get-playlist/) endpoint contains a `followers` object that looks like this:
```json
  "followers": {
    "href": null,
    "total": 127
  },
```
