### ISSUE TITLE
Does Spotify API/ spotipy support time-frequency analysis and spectrograms?

### ISSUE THREAD

**Issue by samlupton** [spotify/web-api#1248]
I'm using the Spotify API (in Python with spotipy) in a machine learning project to try and predict the era in which a track was released based off auditory features, to study changing trends in music and mastering.

I would like to use frequency analysis (especially bassiness) and/or spectrograms in my modelling, but I can't find support for anything that specific in the API reference. The closest option would be the 'timbre' section in Spotify audio analysis, but the docs don't describe what each of the 12 coefficients actually represent. Is there any way of getting more clarification on their meaning, or another way of viewing the amplitude in different frequency bands?

https://developer.spotify.com/documentation/web-api/reference/tracks/get-audio-analysis/

**Comment by 0xNF** [comment]
> the docs don't describe what each of the 12 coefficients actually represent.   

Welcome to a problem many of us have been complaining about for years. The audio analysis endpoint is famously underdocumented.   

If it makes your work any easier, there is no annotated meaning to the timbre and pitch values. They come from the arbitrarily selected first 12 rows of the audio data being run through PCA. The only people who have assigned any meaning to them are Spotify engineers, and they've kept that information strictly internal.  

Other than the audio analysis endpoint, there is no other data available for what you'd like to do.

**Comment by samlupton** [comment]
I see. Thanks for giving me an answer, even if it's not exactly the one I was hoping for! Hopefully I can at least run my own PCA and see if I come up with similar components
