### ISSUE TITLE
/v1/me/following?type=artist returns redundant top level "artists" property

### ISSUE THREAD

**Issue by NovaFocus** [spotify/web-api#125]
The paged result for /v1/me/following?type=artist is inconsistent with other API methods. It returns a redundant top level "artists" property which is not necessary (and inefficient for users of the API due to inconsistency) where other page results don't have this extra top level property. For instance /v1/users/{user_id}/playlists correclty does not return a "playlists" top level property.

**Comment by thelinmichael** [comment]
Hey @NovaFocus. I'll do my best to explain the rationale behind what the responses look like.

The main reason we're wrapping results in an `artists` object is that the endpoint could potentially return `users` as well. Another endpoints that also allow a `type` parameter is [Search](https://developer.spotify.com/web-api/search-item/), which also wraps items in `artists`, `tracks`, etc. 

Another reason to wrap responses in an object is either that we want to include other top-level data alongside the returned items, e.g. `message` in [Get a List of Featured Playlists](https://developer.spotify.com/web-api/get-list-featured-playlists/), or that we expect the need to do so in the future.

Hope this made sense! Keep the feedback coming.
