### ISSUE TITLE
Revoking access to an OAuth app

### ISSUE THREAD

**Issue by danott** [spotify/web-api#126]
As a Spotify user I have granted OAuth access to 3rd party applications. These applications are able to read/write information in my Spotify account.

I no longer want these applications to have access to read/write information my Spotify account. How can I revoke access to these applications?

**Comment by thelinmichael** [comment]
Hi @danott! We're working on enabling users to revoke access tokens. I've sent you an email in case you'd like to discuss an access token that's connected to your account. 

Any update regarding the state of this feature will be posted to this issue ticket.

**Comment by danott** [comment]
Thanks @thelinmichael! I replied to your email about the specifics of my use case.

**Comment by phpfunk** [comment]
@thelinmichael - Same issue here, sort of crazy this wasn't baked in from the beginning. It's sort of a basic security feature. How does one go about revoking access?

**Comment by jdhartley** [comment]
This is an extremely important missing feature. Any work arounds for now?

**Comment by volksport** [comment]
+1 Would really like to be able to revoke an apps permissions!

**Comment by RichardSimko** [comment]
@thelinmichael Having the same problem, how do I go about getting my token revoked? Can your support do it perhaps? Massive oversight that this wasn't included from the start.

**Comment by roggithub** [comment]
is it not possible revoke application token access?

**Comment by phpfunk** [comment]
Not possible AFAIK. Maybe contacting support, but I left Spotify some time ago now.

**Comment by phof** [comment]
@thelinmichael Any updates on this? I'd like to get a token revoked.

**Comment by thelinmichael** [comment]
@phof: No update as of yet, but we're working actively on rolling this out and will update this thread when it's done. Meanwhile, please tweet at @SpotifyPlatform or mail me at thelinmichael@spotify.com if you want tokens revoked.

**Comment by rayning0** [comment]
@thelinmichael, I also must revoke Spotify OAuth access but must do it through my code, for our customers. Is this feature done yet? If not, how do Spotify's engineers expect us to do it?

**Comment by Viper007Bond** [comment]
Still no updates on this? I can't revoke a third party's access to my account? Seems like a pretty big oversight.

**Comment by calebhskim** [comment]
Having this issue fixed would greatly help the development of my project. Would it be possible to get an approximate time as to when this will get fixed?

**Comment by hallelujah** [comment]
@thelinmichael Guys wake up!!!!!! How can you implement an OAuth 2.0 without the ability to revoke access? I mean HOW **DARE** YOU?

Fix this ASAP

**Comment by JohnnyCrazy** [comment]
The weird thing is, the web api exists for nearly over 2 years now. Wonder why there were so many changes but this still isn't implemented

**Comment by rapala61** [comment]
To whom it may concern,

I just taught a class of future developers about the advantages of OAuth and it will be immediately invalidated by your implementation. Now I have to point them to this ticket and remind them that in the Wild  Wild West of Web development even the big boys get it wrong from time to time.

**Comment by akatrevorjay** [comment]
Guys, this isn't OAUTH. Come on now.

**Comment by sevos** [comment]
![Shame](https://m.popkey.co/6bee24/6GJWk.gif)

**Comment by michaeljwilliams** [comment]
Spotify! What are you doing?! Fix this! How have years gone by without this being fixed?! You need to tell your bosses that this is an important security issue that annoys a lot of people, and it has a relatively easy fix.

**Comment by daenney** [comment]
We're aware of the issue and as noted we're working on it. However, flooding this thread with additional +1's and outraged reactions won't help us move forward. Please keep this in mind going forward and join us in having a constructive discussion around the issue instead.

With this in mind I'd like to point out that Spotify's FOSS presence, under which our GitHub repositories fall, is governed by our [Code of Conduct to which we expect participants to adhere](https://github.com/spotify/code-of-conduct/blob/master/code-of-conduct.md).

I've pinged a few teams to get some additional eyes on this, stay tuned.

**Comment by danott** [comment]
@daenney Are you a member of the team at Spotify? I don't see you in the organization when [querying by your username](https://github.com/orgs/spotify/people?utf8=✓&query=dae)? I ask because seeing the `Spotify member` badge on your comments might be informative to others and facilitate the constructive discussion that is desired on both sides?

As the originator of this request, I want to say that members of the Spotify team (namely @thelinmichael) have been super helpful when corresponding over email. I can't imagine that there are any quick/easy fixes when operating at the scale that Spotify does. The fact that this issue isn't closed, but is still open for consideration and discussion is encouraging that the desired behavior will be implemented in time.

❤️ 🎧 📗 

(The `:green_book:` emoji is the closest thing I can find as far as green-and-black logos go 😄 )

**Comment by daenney** [comment]
@danott Oh yes I am. I just noticed that my membership was set to private, hence why it didn't show up. Thanks for pointing that out. I'm a member though not specifically involved with the web API.

**Comment by thelinmichael** [comment]
Hi all! Users will be able to revoke access tokens from August 9th. If you're an application developer, please read about how this may affect your application and what you need to think about [here](https://developer.spotify.com/news-stories/2016/07/25/app-ready-token-revoke/). Meanwhile, please contact us at [@SpotifyPlatform](https://twitter.com/SpotifyPlatform) if you want access tokens revoked. 

Thanks everyone who has engaged with us regarding this important feature, and thanks a lot for your patience while we've been working on it.

**Comment by thelinmichael** [comment]
As of last night users are able to revoke account access for applications from their [accounts page](https://www.spotify.com/se/account/apps/). I encourage you all to try it out and to let us know if you run into any unexpected behaviour.

Extremely happy that we're finally bringing this to a close. And as mentioned in the previous post, we really appreciate that you've engaged with us on this.

**Comment by Viper007Bond** [comment]
Here's a link that won't change your language to Swedish: https://www.spotify.com/account/apps/

**Comment by thelinmichael** [comment]
Doh! Thanks for the correction @Viper007Bond. Updated the link in my last post.
