### ISSUE TITLE
New releases of artists you follow

### ISSUE THREAD

**Issue by Colucas** [spotify/web-api#127]
Currently, as I understood, New Releases endpoint just provides albuns that are, for example, featured on Spotify's Browser tab. I think it would be nicer to have a simple way to get the latest releases of the artists you're following.

Currently, if I want to retrieve such list, I would need to iterate my following list, then over each artist's albuns, then filter them by date (year).. Or is there any other way to do it? :)

**Comment by thelinmichael** [comment]
Hi @Colucas! Your assumption about the [Get New Releases endpoint](https://developer.spotify.com/web-api/get-list-new-releases/) is correct, and the workaround you've provided sounds to me like the best way to currently retrieve new releases for an authenticated user.

I'll set this issue as an API feature request.

**Comment by rsefer** [comment]
I have recently come across this issue and am doing the following:
- Get the full list of artists I follow
- Get the full list of new releases in my country (/v1/browse/new-releases)
- Iterate through the new releases list and pluck releases that share artist(s) in my follow list
- Display the overlap albums/singles/etc. in a reverse chronological order

This works fine 95%+ percent of the time. However, when the new releases list *omits* a new release from an artist I follow, this doesn't work. For example, The Weeks released a new album on April 7th, 2017 (spotify:album:64ZAYYzStXUT8QFfRwufh0), which is well within the current New Releases calendar (there are albums released prior to it from similarly-popular artists on the list), but it doesn't appear in the New Releases list.

Is this a bug? Is that New Releases list not comprehensive?

As a workaround, I tried going through every artist I follow, reverse sorting their releases by date, and then only displaying the most recent X # of releases - this is terribly slow.

Any info would be much appreciated - or even better, an endpoint that grabs the most recent releases from only artists followed would be awesome. Thanks!

**Comment by nickwgiannini** [comment]
@rsefer How did this work out for you?  I just graduated school and am doing something like this very similar as a solo project

**Comment by rsefer** [comment]
@nickwgiannini I've been using the former method (the one that works most of the time) for a while and haven't noticed any major issues. Would still love to see an API call that return new releases from all artists a user follows. Maybe one day!

**Comment by hughrawlinson** [comment]
Hi! The best way to get the new releases of all the artists your user follows is to:

1. Get the user's [followed artists](https://beta.developer.spotify.com/documentation/web-api/reference/follow/get-followed/)
2. Get the [first page of albums from each artist](https://beta.developer.spotify.com/documentation/web-api/reference/artists/get-artists-albums/)
3. Filter that list down with a date threshold.

That way, you have finer control on how recent you consider a "new" release to be :) Hope that helps!

**Comment by shaunhughston** [comment]
@hughrawlinson to get the albums for each artist, is it necessary to interate the function to get the albums for each artist, or is it possible to get multiple artists albums from a single call?

**Comment by uzomao** [comment]
@shaunhughston at the time of writing this you'd have to iterate.
