### ISSUE TITLE
Able to access user despite revoking app

### ISSUE THREAD

**Issue by Shpigford** [spotify/web-api#1277]
Issue found on June 19th 2019.

#### Endpoint(s):
* `GET /v1/me/player/recently-played`

#### Scope(s):
* user-read-recently-played

#### Steps to reproduce:
1. Authorize app with the `user-read-recently-played` scope
2. Revoke access to app on [Apps page](https://www.spotify.com/us/account/apps/)
3. Call `recently-played` endpoint

#### Expected behaviour:
I should receive a 401 Unauthorized message as authorization was revoked.

#### Actual behaviour:
Despite having revoked access to the app (see step 2 in steps to reproduce), I'm still able to access the endpoint and the data (recently played songs).

**Comment by 0xNF** [comment]
Does this behavior continue for more than an hour? To be more specific, are you able to continue to receive new Refresh Tokens?

A revocation only invalidates the Refresh Token you have for that user, and any remaining Access Tokens will remain valid until they expire.

**Comment by Shpigford** [comment]
Ah, it did indeed resolve itself within an hour. Didn't realize it only invalidated future tokens. 

So, no bug here, assuming this is the intended behavior.

**Comment by jscholes** [comment]
I don't think this ticket should be closed, regardless of whether the behaviour is intended or not.

If I revoke an app's authorization, my expectation is that it will no longer have access to any aspect of my account.  If Spotify are not honouring that by accident, it is a serious security bug.  If they are making this decision on purpose, it's plain stupid.

If a bad actor gains access to my account, and is using it for nefarious purposes, there is no way they should be given up to a free hour between when I revoke the app and when the system actually kicks them out.  that is ridiculous.

Equally insane is the fact that RFC 7009 implies that this behaviour is acceptable, by recommending that access tokens be revoked along with refresh tokens but not requiring it.

**Comment by 0xNF** [comment]
Not to recommend one particular side or another on this issue, the common justification that I've come across has been one of reducing database round-trips checking revocation status per request given that access tokens are typically high traffic items. Whether that's a good reason or not is subject to debate.

Some frameworks for working with OAuth2 recommend this same approach.

**Comment by jscholes** [comment]
While that justification does make some sense, it doesn't entirely hold up.  There are APIs which don't enforce regular access token refreshes, and they still manage to correctly revoke tokens without imposing an unacceptable performance overhead.  A company like Spotify has the resources to ensure user security, while not relying on some internal performance DBMS metrics to excuse not doing so.
