### ISSUE TITLE
Get the user currently playing track always returns 404

### ISSUE THREAD

**Issue by MRmlik12** [spotify/web-api#1286]
Issue found on July 1st 2019.

#### Endpoint(s):
* `GET https://api.spotify.com/v1/me/player/currently-playing`

#### Scope(s):
* user-read-currently-playing

#### Steps to reproduce:
None at the moment

#### Expected behaviour:
This url returns user's currently playing track info

#### Actual behaviour:
404 Page Not Found

**Comment by kevinguebert** [comment]
Checking this out today, it seems to be working fine with postman. I tested when no song was playing and with a song playing.

Can you provide any more info on steps to reproduce?
