### ISSUE TITLE
Cumulative User Activity

### ISSUE THREAD

**Issue by danielgroves** [spotify/web-api#129]
I'd like to be able to pull further data around my own personal listening metrics. This provides endless possibilities around comparing to friends, as well pulling information for personal websites. 

The data I'd personally like to pull is:
- Cumulative number tracks listened to
- Cumulative hours spent listening
- Average number of tracks per day
- Average time spent listening per day
- Cumulative number of tracks this year so far
- Cumulative hours spent listening so far

**Comment by mehmettaskiner** [comment]
I'd like to develop an spotify statistics application. This information is very useful that kind of applications. So +1.

**Comment by Wingman4l7** [comment]
The data is definitely there -- see Spotify's [Year in Music](https://yearinmusic.spotify.com/).

**Comment by jasongilmour** [comment]
I'd love to be able to access all my listening data, I think there's real potential to make something great if users can control and share their listening data.

I'll also use this opportunity to shamelessly plug my concept for an app using said data: http://jasongilmour.co.uk/projects/polyphonic/

**Comment by breachofmind** [comment]
+1, I would also like to see this.

**Comment by mattvivier** [comment]
+1

**Comment by Hayderhj** [comment]
+1, any update on this?

**Comment by slandersson** [comment]
My guess is they don't want to give too much of their own data away.

Would be cool features to have though.

**Comment by bih** [comment]
Hello all!

As per our [new developer support process](https://github.com/spotify/web-api), any feature requests that have no plans to be considered in the next 6 months will be closed as <kbd>wontfix</kbd>.

In this particular case, we have decided against implementing additional user activity through the Web API for now. If you want to see your own personal listening history, Spotify is regularly running campaigns to let users see their own listening history which you can look out for.

We encourage you and other members of the community to continue to share use cases and your support for this feature, as it helps us prioritize features going forward. You should be able to comment on this issue even after it is closed. We will also post updates here relating to this suggestion as and when they happen.

Cheers 👍
