### ISSUE TITLE
ugc-image-upload is not listed as a scope but seems to be required to upload cover image

### ISSUE THREAD

**Issue by GregWoodring** [spotify/web-api#1293]
Issue found on July 8, 2019

When attempting to put to https://api.spotify.com/v1/playlists/${playlist_id}/images I get 401 unauthorized despite having a valid access token for the scopes below. Looking in the documentation it indicates that I require: 'ugc-image-upload granted' however this is not listed as a scope at https://developer.spotify.com/documentation/general/guides/scopes/. When I try to request the scope regardless it does not prompt me to authorize for that scope. 

I'm suspicious that 'ugc-image-upload granted' is not a real scope due to it having a space, when I try to do simply ''ugc-image-upload' or ''ugc-image-upload-granted' it also does not work. 

Is there a scope I should be requesting for this functionality, or am I doing something else wrong? 

This is the structure of my request object: 

            let requestObj = {
                url: `https://api.spotify.com/v1/playlists/${playlist_spotify_id}/images`
                method: 'PUT',
                headers: {
                    'Authorization' : `Bearer ${user.access_token}`,
                    'Content-Type' : 'image/jpeg'
                },
                data: image
            }

and I make the request with axios as so: 

let response = await axios(requestObj);

#### Endpoint(s):
* `PUT https://api.spotify.com/v1/playlists/${playlist_spotify_id}/images'

#### Scope(s):
'user-read-email',
        'user-read-recently-played', 
        'user-library-modify',
        'playlist-modify-public',
        'playlist-read-private',
        'playlist-modify-public',
        'playlist-modify-private',
        'user-library-read',
        'playlist-read-collaborative',
        'user-read-birthdate',
        'user-read-playback-state',
        'user-read-private',
        'app-remote-control',
        'user-modify-playback-state',
        'user-follow-read',
        'user-top-read',
        'user-read-currently-playing',
        'user-follow-modify',
        'streaming',

#### Expected behaviour:
Update playlist image for playlist.

#### Actual behaviour:
401 unauthorized (consistently)

**Comment by vaibhavhrt** [comment]
Same.

**Comment by vaibhavhrt** [comment]
After a bit of investigation the actual scope name is `ugc-image-upload`. Its mistake in their docs highlighting the whole `ugc-image-upload granted`. Also it requires Client Credentials Flow

**Comment by joshubrown** [comment]
Thanks for giving feedback on this, folks. We have updated the documentation now to make the required scopes clearer.
