### ISSUE TITLE
Question: Is it possible to modify private user data at all?

### ISSUE THREAD

**Issue by ssalcedo00** [spotify/web-api#1296]
Hi, I am new to developing using the Spotify Web API and I have already submitted my application for commercial integration. I'm planning on building a subscription management service and I was wondering if it was even possible to allow users, once authorized through your API, to change their private information, say email, through my service. If possible, what steps would I have to go through to do so?

If this is not the right place to ask this question then I ask you to redirect me to who can answer my question. 

Thank you.

**Comment by mklaunzer** [comment]
@ssalcedo00 changing account information is not supported through the Web API and there are currently no plans to do so in the future.
