### ISSUE TITLE
Using Axios POST to retreive token from Spotify API using client_credentials - node.js

### ISSUE THREAD

**Issue by mrbjjackson** [spotify/web-api#1301]
This issue more me asking for an explaination than a technical issue. I hope I'm posting it in the right place.

I've been trying everything to get my node.js script to request an API token from Spotify using 'client_credentials'. I've searched all over and tried a tonne of different combinations and I finally found this this small snippet from @Agnostic (quoted below) buried in a related thread. It's the only one that's worked for me.

As far as I can see the only thing that is different here is that instead of using:
```Authorisation: Basic CLIENT_ID : CLIENT_SECRET```
or a variation e.g.
```'Authorization': 'Basic ' + Buffer.from(`${client_id}:${client_secret}`).toString('base64') ```
this code uses
```       
auth: {
          username: 'YOUR-CLIENT-ID',
          password: 'YOUR-CLIENT-SECRET'
        }
```
My question is why does this work, while none of the code that I have lifted from the Spotify docs has worked. As far as I can see, this is the first time I have seen the "auth" parameter mentioned. Am I missing something or is the documentation misleading / yet to be changed after an update?

I'm not trying to be passive aggressive here. :) I'm genuinely interested in finding out how I could have come to this solution earlier.

Many thanks,
Ben

```javascript
     axios({
        url: 'https://accounts.spotify.com/api/token',
        method: 'post',
        params: {
          grant_type: 'client_credentials'
        },
        headers: {
          'Accept':'application/json',
          'Content-Type': 'application/x-www-form-urlencoded'
        },
        auth: {
          username: 'YOUR-CLIENT-ID',
          password: 'YOUR-CLIENT-SECRET'
        }
      }).then(function(response) {
          console.log(response);
      }).catch(function(error) {
      });
```

_Originally posted by @Agnostic in https://github.com/spotify/web-api/issues/321#issuecomment-321134744_

**Comment by 0xNF** [comment]
Are  you sure that the `auth` field isn't just an alias that is used to construct an Authorization header at request time?

Try inspecting the actual request object that gets sent out, might find some interesting things in it.

**Comment by mrbjjackson** [comment]
Thanks for getting back to me @0xNF. I've just seen on the Axios documentation that `auth:` is used to send Basic authentication. So that explains that.

What I can't understand though is why none of the things I tried passing `Authorisation: Basic CLIENT_ID : CLIENT_SECRET` as a `header` or as a `param` or as `data` as is advised in the Spotify documentation.

**Comment by 0xNF** [comment]
This is a minor thing, and your original post looked like it had it correct, but are you sending `Authorisation` or `Authorization`. Notice the 'z' in the second one.

**Comment by mrbjjackson** [comment]
Thanks very much for your help. You may well be right about this. TBH In a way I hope you are not right because it meant I struggled for hours over something as simple as a one letter British / US spelling discrepancy :) 
Thanks though.

**Comment by 0xNF** [comment]
Don't forget about the spaces either. `{ClientId}:{ClientSecret}`, no space between the colon. Let us know how it goes.  And if it is? We've all been there man. Typos are the ultimate bughunt.

**Comment by donstefani** [comment]
I'm late to the party, but it took me a while to get success, [I used this code >>](https://gist.github.com/donstefani/70ef1069d4eab7f2339359526563aab2)
