### ISSUE TITLE
Discover Weekly Endpoint Access

### ISSUE THREAD

**Issue by grantbrewster** [spotify/web-api#1320]
Is it possible to get the Discover Weekly playlist of a user that gives read access but does not have the playlist saved to their own library? For example, every usr  has a Discover weekly in the "made for you" section, but I do not follow my own Discover Weekly so it is not in my library. Is this possible to access, if so what is the endpoint I am looking for? Sorry, just have not found any clear documentation for it online! Appreciate the help.

**Comment by 0xNF** [comment]
Nope. Technically the automated playlists are owned by user "Spotify", so won't show up in the API unless you follow them.
