### ISSUE TITLE
Error: Illegal Scope 

### ISSUE THREAD

**Issue by alexsdesign** [spotify/web-api#1322]
I'm having an issue using the WEB API.
I'm currently using the PHP API library recommended by Spotify
(jwilsson/spotify-web-api-php)

I've written a multi user playlist creator software, which allows users to import their private and public playlists, along with playlist and track management

I have a few users that keep getting an error message "Illegal Scope"... however not all users are getting this. 

Here is the list of scopes being requested. Can anyone shed any light on this? 
I know a couple of months ago there was an illegal scope issue, I'm wondering if it's connected?
`		$options = [
			'scope' => [
				'user-read-recently-played',
				'user-library-modify',
				'user-library-read',
				'playlist-read-private',
				'playlist-modify-public',
				'playlist-modify-private',
				'playlist-read-collaborative',
				'user-read-email',
				'user-read-birthdate',
				'user-read-private',
				'user-read-playback-state',
				'user-modify-playback-state',
				'user-read-currently-playing',
				'user-follow-read',
				'user-follow-modify',
			],
		];
`

**Comment by mklaunzer** [comment]
@alexsdesign this might be related to recent changes around the user-read-birthdate scope. Not requesting that scope from your app should resolve the problem.

Thanks for the hint! We'll have a closer look at this library.

**Comment by alexsdesign** [comment]
Thanks for the heads up.... I'll make the changes and see what happens :)
