### ISSUE TITLE
oEmbed endpoint responds with 500

### ISSUE THREAD

**Issue by artzag** [spotify/web-api#1329]
Issue found on August 22nd 2019.

#### Endpoint(s):
* `https://embed.spotify.com/oembed?url={url}`

#### Scope(s):
* None (application is not using authentication)

#### Steps to reproduce:
1. Open the browser
2. Call the `https://embed.spotify.com/oembed?url=http%3A%2F%2Fopen.spotify.com%2Ftrack%2F298gs9ATwr2rD9tGYJKlQR` 

#### Expected behaviour:
JSON oEmbed response describing requested track.

#### Actual behaviour:
500 Server Error (consistently)

<img width="1090" alt="Skjermbilde 2019-08-22 kl  15 32 44" src="https://user-images.githubusercontent.com/1443097/63531915-dcb90000-c509-11e9-97e8-6121f4b66385.png">

<img width="1168" alt="Skjermbilde 2019-08-22 kl  15 33 12" src="https://user-images.githubusercontent.com/1443097/63531952-f0646680-c509-11e9-88bc-fd3455589e84.png">

**Comment by alexplumb** [comment]
Seems to be working now

**Comment by artzag** [comment]
Yes - it is. Anybody knows what was wrong - and where to knock if it happens again?
