### ISSUE TITLE
Share Spotify content with Current User's Followers

### ISSUE THREAD

**Issue by tim-thimmaiah** [spotify/web-api#134]
Are there any plans on adding an endpoint to share a track or album to your followers inside of Spotify?

**Comment by thelinmichael** [comment]
Hi @tim-thimmaiah! If this is an endpoint that you'd like to see I think we should consider this a feature request. I'm assuming that you're referring to the Activity part of the app.

**Comment by tim-thimmaiah** [comment]
@thelinmichael Yes exactly. I think a put request that takes a URI/URL for a track, album, or playlist and a general message parameter that posts to all of your followers would be perfect. I believe this would greatly improve the discovery of content right in a user's activity panel.

**Comment by arirawr** [comment]
Hi from the future! I'm going to close this issue, as the in-app messaging feature no longer exists, making this unfeasible.
