### ISSUE TITLE
Get playlist returning 400 Error Bad Request with no error details

### ISSUE THREAD

**Issue by ziadamir** [spotify/web-api#1342]
Issue found on September 6th 2019.

#### Endpoint(s):
* `GET https://api.spotify.com/v1/playlists/{playlist_id}`

#### Steps to reproduce:
1. Generate token
2. Call the `get a playlist` endpoint with the following playlist ids `1qilUb2lCepRhM0IKd4tki`, `13VeS4Ykz5IH7rC2ZOTICi`, `2zTLZozGdmOkoxVhCVfDKJ`, `1HDx5aeJzKSzXfOYEIdb1b`, `131TlI4rnDzmtV6xaXarUr`, `0EvcUQstq5wCK9KFtR9CJV`, `1BvMeRpVmBlT3sF7Zp2SQn`, `3R2VIZgOdc6IsmNM1T9TNZ`, `5nGSALO01eK1J90Gh1A8vq`

#### Expected behaviour:
A playlist object (full) as described on `https://developer.spotify.com/documentation/web-api/reference/object-model/`.

#### Actual behaviour:
400 Bad Request (consistently getting this error for the above playlist ids, works fine for other playlist ids)
I manually checked to make sure the playlists still exist on Spotify and they do.

Please advise or provide insight into the cause of these errors. Thanks.

**Comment by kevinguebert** [comment]
This is interesting. If you put those playlist ids in the web console it also fails so the API is working the same as the console...which is good.

But, if you go to one of the playlists like this one (https://open.spotify.com/playlist/2zTLZozGdmOkoxVhCVfDKJ) then it does end up showing the playlist like you said.

Looking next at the network tab, it looks like they actually have problems with the original request and then up changing the request to `https://api.spotify.com/v1/playlists/2zTLZozGdmOkoxVhCVfDKJ?type=track%2Cepisode&market=from_token`

I tried that request out in Postman and it actually also works there. If you remove the `market=from_token`, it still works. But, if you remove the `type=track%2Cepisode`, then it fails/

🤷‍♂

So my theory is there is something special with those playlists that maybe we don't know about? I can't find any documentation on adding the `type` query parameter onto the playlist either. Maybe if one always passes `type=track%2Cepisode` the GET request will always work?  

---
Note I don't work at Spotify, just doing some debugging.

**Comment by ziadamir** [comment]
@kevinguebert thank you for investigating my issue. I added  ```?type=track%2Cepisode``` to the end of all of my GET requests and it is now returning data 🎉
