### ISSUE TITLE
Referencing incorrect endpoint on 'Create a Playlist' console page

### ISSUE THREAD

**Issue by fmxy** [spotify/web-api#1344]
As mentioned by user @fclement-yseop the Spotify Web API Console still references the wrong endpoint for creating playlists. It renders the console useless as the request is sent to the wrong endpoint. 

The `console`  is still with the bad form of url `POST /v1/playlists` and not `POST /v1/me/playlists`
https://developer.spotify.com/console/post-playlists/

_Originally posted by @fclement-yseop in https://github.com/spotify/web-api/issues/936#issuecomment-418342572_

**Comment by joshubrown** [comment]
The console endpoint has been corrected now. Thanks for filing an issue, @fmxy!
