### ISSUE TITLE
Bot for private and educational purposes only

### ISSUE THREAD

**Issue by Paul2708** [spotify/web-api#1349]
Hey guys!
I didn't find any information about creating a bot that streams the music to another service like Teamspeak or Discord.
It should be for private and educational purposes only.

Am I allowed to do so or is it against any ToS?

Thanks for any help provided.
Greetings, Paul

**Comment by NoNamePro0** [comment]
Hey Paul, I think you can ask the question again in the [Forum](https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer)!
