### ISSUE TITLE
Spotify: how to get the preset "blob" (the key to play a playlist as a preset) when it's not already playing? 

### ISSUE THREAD

**Issue by Prabahara** [spotify/web-api#137]
Spotify: how does a preset blob get mapped to a playlist?

**Comment by thelinmichael** [comment]
Hey @Prabahara! This doesn't sound like it's related to Spotify's Web API, which this Github repository is meant for. 

If you're using proprietary software from Spotify that's meant for hardware integration, I advise you to contact Spotify directly through the support channel that you've been given.

**Comment by Prabahara** [comment]
ok i am trying to find out the WebAPI to get preset "blob" for the particular playlists. Please let me know is there any API to find out the WebAPI to get preset "blob" for the particular playlists?

**Comment by thelinmichael** [comment]
@Prabahara, I don't know what you mean by _"preset blob"_  and I'm fairly sure it's unrelated to the Web API? Again, if you already have a contact person at Spotify you should use that support channel. If you believe this is actually related to the Web API please reopen the issue and elaborate.

**Comment by Prabahara** [comment]
my question is related to WebAPI.  blob is the key used to initiate particular playlist plyback. actually this is for preset.

Normally with libspotify library we can use  SP_EMB_PUBLIC SpError SpGetPreset(uint8_t *buffer, size_t *buff_size); to get the blob or key for currently playing playlist.

same as like this is there any webapi to get the  preset for the currently playing song preset?

**Comment by thelinmichael** [comment]
@Prabahara, the simple answer is no.
