### ISSUE TITLE
Impossible to have the Client Credentials Flow working !

### ISSUE THREAD

**Issue by Totoremix** [spotify/web-api#1372]
Issue found on October 25th 2019.

#### Endpoint(s):
* `POST https://accounts.spotify.com/api/token`

#### Scope(s):
* None (application is not using authentication)

#### Steps to reproduce:
1. Encode the following string : "user_id:user_secret" in base64 using base64encode.org/
2. Execute curl command on Windows cmd : curl -X "POST" -H "Authorization: Basic the_base64_previously_encoded_string" -d grant_type=client_credentials  https://accounts.spotify.com/api/token

#### Expected behaviour:
Gives an access token.

#### Actual behaviour:
400 Server Error : "Invalid Client"

(I've tested my credentials a several billion times already :-/, I can use them to connect to Spotify)

PS: Please help me, I will soon run out of hair to tear out

**Comment by kevinguebert** [comment]
Hey @Totoremix!

Just want to clarify something - for your base64 encoded string, you are registering an application in the developer portal, getting the client_id and client_secret from there, and then putting both of those into the base64encode.org website as `client_id:client_secret`?


![image_blur_Screen Shot 2019-10-25 at 11 03 33 AM](https://user-images.githubusercontent.com/2111847/67582185-44144b80-f717-11e9-93e2-8a8bfb942050.png)

**Comment by Totoremix** [comment]
Hello, Thanks for your quick answer! Looks like I completely misunderstood what was meant by user_id and user_secret...I wasn't aware I needed to register an app in the dashboard to achieve what I was trying to. Again thanks a lot, and sorry for the dumb issue (-:

**Comment by Totoremix** [comment]
Hello @kevinguebert,

Thanks for your quick answer! Looks like I completely misunderstood what was meant by user_id and user_secret...
I wasn't aware I needed to register an app in the dashboard to achieve what I was trying to. Again thanks a lot, and sorry for the dumb issue (-:

**Comment by kevinguebert** [comment]
Glad you were able to figure it out!
