### ISSUE TITLE
Exactly match search query

### ISSUE THREAD

**Issue by Andreas75** [spotify/web-api#138]
Is there a way to match a search exactly?

If i seach for album:25 artist:adele (/v1/search?q=album%3A25+artist%3Aadele&type=album) i get a artist called Adele Cara with a album called "19 21 25"

I want to get a zero result from the search because the Adele record isn't on Spotify.

**Comment by thelinmichael** [comment]
Extremely late response, but I'll add a response just for future reference. 

It isn't possible to restrict results to exactly match a query string, but I'm slapping a feature request label to this issue to keep track of it if there's an update.

On a positive note, [25 by Adele](https://api.spotify.com/v1/albums/7uwTHXmFa1Ebi5flqBosig) is now available on Spotify!

**Comment by arirawr** [comment]
I realize that this is a 2-years-later response, but you can search for exact matches by using double quotes in your query (ie. album:"25"artist:"Adele"). Here's a link to this specific query using double quotes, and you can see that there is only one result: [https://developer.spotify.com/web-api/console/get-search-item/?q=album%3A%2225%22artist%3A%22Adele%22&type=album](https://developer.spotify.com/web-api/console/get-search-item/?q=album%3A%2225%22artist%3A%22Adele%22&type=album)

**Comment by eikowagenknecht** [comment]
@arirawr I guess this is because only one "Adele" has an album called "25". If you try https://developer.spotify.com/console/get-search-item/?q=artist:%22Adele%22&type=artist%2Cartist for example, multiple artists are returned, depite the quotation marks (e.g. Adele, Robyn Adele Anderson, ...).
