### ISSUE TITLE
"create playlist" api -"try" example doesnt work

### ISSUE THREAD

**Issue by dcinick78** [spotify/web-api#1383]
Issue found on November 4th 2019.

#### Scope(s):
* playlist-modify-public, playlist-modify-private

#### Steps to reproduce:
1. Open https://developer.spotify.com/console/post-playlists/
2. Get your token and test the try button.

2.1 https://developer.spotify.com/documentation/web-api/reference/playlists/create-playlist/
2.2 the ENDPOINT here differs from the try example, which is confusing too.

#### Expected behaviour:

a new playlist object 

#### Actual behaviour:

POST https://api.spotify.com/v1/playlists 404
console.bundle.js:25529 Uncaught (in promise) SyntaxError: Unexpected end of JSON input
    at console.bundle.js:25529

**Comment by galesberdurin** [comment]
Hello friend,

They have an error, change the url to https://api.spotify.com/v1/me/playlists and it should work fine!

Best,

**Comment by joshubrown** [comment]
Thanks for bringing this up, @dcinick78. We've deployed a fix and the console should now allow you to create playlists.
