### ISSUE TITLE
Wish: New search function for related artists  

### ISSUE THREAD

**Issue by UtotheLtotheF** [spotify/web-api#139]
I would like search related artists using 2 or more artists in the search bar. The search function would then find the related artist most "in-between" the mentioned artists. With the spotify related artists library this search function should be easy to create. For example: I want somthing a bit like Abba and a bit like Daft punk, the seach function would find the inbetween related artist (perhaps.. Erasue??). I would appreciate this search function alot, the related artist suggestions now popping up are only within the same genre and its hard finding something new.

**Comment by jsimonsson** [comment]
Hi!

This github repository is for the Spotify Web API. If you have ideas and suggestions for the Spotify clients  you can suggest and discuss them here: https://community.spotify.com/t5/Idea-Submissions/idb-p/ideas_submissions
