### ISSUE TITLE
I'm getting a 401 "Invalid access token" when trying to perform a fetch from my react app.

### ISSUE THREAD

**Issue by doseofmazen** [spotify/web-api#1397]
Cannot retrieve profile for user with user Data

Issue found on Nov 25th 2019.

#### Endpoint(s):
* `GET /v1/me`

#### Scope(s):
* My app is using authentication. To what level I don't know... I new to this so  please bare with me. I do have an access token that's provided to me though. Which is this.

http://localhost:3000/?access_token=BQAfv6LAi0s9Is_ghh8H96ZqdGwRzeP6K6Rmw_4tgaRrjTMje_tF2pWOiPYE9ZvpSitX5Ggg1CkF5gsm_Vg2r6d2GmmIvggM19KC03duVdnMoPI00Lw6WQTAlcrVB7nnFZd1C9SWY_C42lgkJT2f-tyuK3wTIk1p0ZMq8GaZa8NkILf7tA

I'm trying to fetch data from a non premium user so maybe that has something do to with it?? 
I don't know... I'm following a tutorial on youtube(https://www.youtube.com/watch?v=rzk8n-4gMWs) 

#### Steps to reproduce:
 fetch('https://api.spotify.com/v1/me', {
     headers: {
       'Authorization': 'Bearer ' + accessToken
     }
   }).then(response => response.json()).then(data => console.log(data))

#### Expected behaviour:
An object with country and display_name keys and values.

#### Actual behaviour:
error:
status: 401
message: "Invalid access token"

Please help and Thanks!

**Comment by kevinguebert** [comment]
Hm hard to tell without seeing more of the code. I would recommend double-checking to make sure your `client_id`, `client_secret`, and `redirect_uri` are all set correctly. 

Secondly, I would recommend requesting a new access token. They do expire after 60 minutes so it could be that this one has just expired and you need a new one.

**Comment by doseofmazen** [comment]
This is what I had before was >
let accessToken = querystring.parse(window.location.search).access_Token

And this is how to fix it
 let accessToken = querystring.parse(window.location.search).access_token

And there was nothing wrong with my fetch. Just a capital letter in the key.

fetch('https://api.spotify.com/v1/me', {
    headers: {
      'Authorization': 'Bearer ' + accessToken
     }
   }).then(response => response.json()).then(data => console.log(data))
  }
