### ISSUE TITLE
DOCS: Minor styling bug in the docs

### ISSUE THREAD

**Issue by AllanOcelot** [spotify/web-api#1398]
Issue found on February 19th 2015.

#### Scope(s):
* None (application is not using authentication)

#### Steps to reproduce:
1. Visit https://developer.spotify.com/documentation/web-api/reference/playlists/upload-custom-playlist-cover/
2. In header fields, Auth, the styling for the scope tag "ugc-image-upload" contains "granted". 

#### Expected behaviour:
1. The word granted should not be styled within the scope tag. 

#### Actual behaviour:
1. The word "granted" is styled within the scope tag. Can be confusing for some newer API users whom will simply copy and paste the tag into their code.

I understand this is a minor minor bug, and maybe not the right place to post.

**Comment by stephanebruckert** [comment]
Duplicate https://github.com/spotify/web-api/issues/1293

**Comment by joshubrown** [comment]
Thanks for bringing this up, @AllanOcelot. We have corrected that part of the documentation.
