### ISSUE TITLE
Negative value of Followers for certain users

### ISSUE THREAD

**Issue by VirUZI** [spotify/web-api#14]
For certain users we get a negative value of followers instead of the the value displayed in the Spotify Client which we expect.

Some examples of requests that give negative followers are:
https://api.spotify.com/v1/users/justinbieber which has -4419 instead of the expected 2478621.
https://api.spotify.com/v1/users/1121769402 which has -710 followers.

**Comment by jsimonsson** [comment]
Thanks for the report!

**Comment by thelinmichael** [comment]
This has been fixed. Thanks again for the report @VirUZI, and please do let us know if you stumble upon this again.
