### ISSUE TITLE
App Not Setup: This app is still in development mode

### ISSUE THREAD

**Issue by reinisk22** [spotify/web-api#1401]
Hey,

Learning how to build simple apps, bet I'm stuck at logging in with Facebook. 
Basically, I'm trying to set up the authorization flow, I get to the point, where a pop up appears and offers me to log in. If I try to insert my credentials, when I press on sing in button, nothing happens, if I try to login with facebook, I get: App Not Setup: This app is still in development mode

Looked all over the internet, found nothing that helps. 
Any help will be appreciated.

**Comment by kevinguebert** [comment]
@reinisk22 Do you also have a facebook app alongside this current one? The message "App Not Setup: This app is still in development mode" is usually tied to developing with facebook apps:
https://developers.facebook.com/docs/apps/managing-development-cycle/
https://stackoverflow.com/questions/30085246/app-not-setup-this-app-is-still-in-development-mode

**Comment by reinisk22** [comment]
@kevinguebert No, I just try to login with Facebook into my Spotify app. Today I got past this issue by rewriting my code. Thanks tho, will close this thread.
