### ISSUE TITLE
Bug (typo) on Official WebPage (Swiss-German ch-de)

### ISSUE THREAD

**Issue by 3raymon** [spotify/web-api#1411]
Bug on WebPage Swiss-German ch-de Translation

Issue found on February 19th 2015.

#### Endpoint(s):
* https://www.spotify.com/ch-de/

#### Scope(s):
* Official Webpage

#### Steps to reproduce:
1. open page :https://www.spotify.com/ch-de/
2. login to your account
3. go to startpage again: https://www.spotify.com/ch-de/

#### Expected behaviour:
HTML code visible `"Dein Jahresrückblick<br />2019"`

#### Actual behaviour:
![grafik](https://user-images.githubusercontent.com/23735902/70441711-2e739f00-1a95-11ea-8661-67e95683b138.png)

**Comment by joshubrown** [comment]
Thank you for letting us know about this, @3raymon! We've made a correction to that page.
