### ISSUE TITLE
CREATE A PLAYLIST

### ISSUE THREAD

**Issue by SiddharthS018** [spotify/web-api#1415]
Issue found on February 20th Dec 2019.

#### Endpoint(s):
* `  POST https://api.spotify.com/v1/playlists`

#### Scope(s):
* None (application is not using authentication)

#### Steps to reproduce:
1. Open the API Console
2. Call the `get-users-profile` endpoint with `user_id` `%5E`

#### Expected behaviour:
A public user object as described on `https://developer.spotify.com/web-api/object-model/#user-object-public`.

#### Actual behaviour:
500 Server Error (consistently)

**Comment by kevinguebert** [comment]
@SiddharthS018 can you provide more information about what is happening? Are you running into an issue? Most of the information above is the same as in the [issue template](https://github.com/spotify/web-api/issues/new) except your endpoint.

**Comment by SiddharthS018** [comment]
Hello,
Thanks for the reply,

I tried to create a new playlist using the Endpoints, When I trigger the
Try it, there's no change in My Playlists, can you help find the issue?

**Comment by SiddharthS018** [comment]
Hello,
Thanks for the reply, 

I tried to create a new playlist using the Endpoints, When I trigger the Try it, there's no change in My Playlists, can you help find the issue?

I have mailed you regarding the issue.

**Comment by kevinguebert** [comment]
It looks like the endpoint for creating a playlist is a bit different now than the web console says.

Instead of:
`https://api.spotify.com/v1/playlists`
it should be:
`https://api.spotify.com/v1/users/{user_id}/playlists`

See:
- https://developer.spotify.com/documentation/web-api/reference/playlists/create-playlist/
- https://github.com/JMPerez/spotify-web-api-js/issues/124

**Comment by SiddharthS018** [comment]
Hi,
Can you please support me with this issue also,
https://github.com/spotify/web-api/issues/1420

**Comment by SiddharthS018** [comment]
Hi,
Can you please support me regarding the issue #1420 (30s  Preview).

https://github.com/spotify/web-api/issues/1420#issuecomment-572433887

**Comment by joshubrown** [comment]
Thanks for bringing this up, @SiddharthS018. As @kevinguebert points out, the endpoint was incorrect in the console. We have deployed a fix.
