### ISSUE TITLE
/v1/users/{user}/playlists/{list}/tracks only returns a single artist in "artists" array

### ISSUE THREAD

**Issue by admattingly** [spotify/web-api#142]
When retrieving the tracks for a playlist, the items[].track.artists[] array only has one element when the Spotify UI shows multiple artists for that track.  

The following track has 3 artists (J Deamer, Ariana Grande, Iggy Azalea) per the Spotify UI:
![problem](https://cloud.githubusercontent.com/assets/16056043/11450766/702aec64-9600-11e5-8002-e76cef130b47.png)

However, the "items" element returned by /v1/users/{user}/playlists/{list}/tracks shows:
  {
    "added_at" : "2015-11-28T05:05:43Z",
    "added_by" : {
      "external_urls" : {
        "spotify" : "http://open.spotify.com/user/xxx"
      },
      "href" : "https://api.spotify.com/v1/users/xxx",
      "id" : "xxx",
      "type" : "user",
      "uri" : "spotify:user:xxx"
    },
    "is_local" : true,
    "track" : {
      "album" : {
        "album_type" : null,
        "available_markets" : [ ],
        "external_urls" : { },
        "href" : null,
        "id" : null,
        "images" : [ ],
        "name" : "Problem (feat. Iggy Azalea) - Single",
        "type" : "album",
        "uri" : null
      },
      **"artists" : [ {
        "external_urls" : { },
        "href" : null,
        "id" : null,
        "name" : "Ariana Grande",
        "type" : "artist",
        "uri" : null
      } ],**
      "available_markets" : [ ],
      "disc_number" : 0,
      "duration_ms" : 193000,
      "explicit" : false,
      "external_ids" : { },
      "external_urls" : { },
      "href" : null,
      "id" : null,
      "name" : "Problem (feat. Iggy Azalea)",
      "popularity" : 0,
      "preview_url" : null,
      "track_number" : 0,
      "type" : "track",
      "uri" : "spotify:local:Ariana+Grande:Problem+%28feat.+Iggy+Azalea%29+-+Single:Problem+%28feat.+Iggy+Azalea%29:193"
    }
  }

**Comment by jsimonsson** [comment]
Hi!

This is a case of local tracks. If you are viewing a song that is a local track but belongs to someone else and you do not have it then the Spotify client will try to find the closest match and may have more metadata about the track than the local track entry. You can see that it is a local track because of the lack of a lot of the information and the uri that starts with spotify:local.
