### ISSUE TITLE
New client library for Python: Tekore

### ISSUE THREAD

**Issue by felix-hilden** [spotify/web-api#1429]
Hello, I'd like to inform you about a new client for the Web API for Python: Tekore ([GitHub](https://github.com/felix-hilden/tekore)). Would you be so kind as to add it to your list of client libraries on [this page](https://developer.spotify.com/documentation/web-api/libraries/)?

I don't know if you have any requirements for those libraries, but let me try to sell my package anyway.
- Complete client with every endpoint - stable and beta - and authentication
- 100 % test coverage, and tested against the live server
- In development since August 2019, version 1.0.0 released on PyPI just now

It seems that all libraries you've put up are in the form "author/library" and many of them point to GitHub. If it's possible I'd like for the link to point to [PyPI](https://pypi.org/project/tekore/) instead. But I have no problem with my name in the front.

Cheers!

**Comment by felix-hilden** [comment]
If I may ping you guys, since you've been helpful in getting previous similar requests closed (@hughrawlinson @JMPerez).

It seems that you have wanted to check out what kinds of applications could be built and what the code looks like. We do have an examples section in our documentation. [Here](https://tekore.readthedocs.io/en/stable/examples/recommended_playlist.html)'s one to create a playlist filled with recommendations from a user's top tracks.

I would much appreciate any response, just to know that you are listening, as the most recent issues here are somewhat quiet. And do let me know if you want to know anything!

**Comment by joshubrown** [comment]
Thanks for letting us know about the new library, @felix-hilden! We will take a look shortly and consider including in the list of third-party libraries.

**Comment by felix-hilden** [comment]
Thank you very much for the quick reply, can't wait!

**Comment by felix-hilden** [comment]
Our newest release brought response caching and support for asynchronous programming. We can now finally boast that there are no features that the web api documentation mentions that we don't directly support.

What's the status on your taking a look, @joshubrown? Can I do anything to help you further? I realise I'm being a bit inquisitive about this, but I care for this library and would like to see it benefit as wide an audience as possible.

**Comment by felix-hilden** [comment]
As previously, I'd appreciate any form of response, @joshubrown! Whether you are simply too busy to evaluate a new library to the extent you'd like, or you'd like to reject my proposal, or would accept it sometime, I'd like to know about that decision and what's going on. Alternatively, when can I expect a decision to be made? I'd hate for this discussion to be just me crying out to Spotify just to be ignored.

You are doing important work at Spotify, but this issue tracker is a mess. But I can't really blame it on you when browsing around some of the issues 😄 I hope you have some time from your other duties to respond.

**Comment by joshubrown** [comment]
Congratulations on the new features, @felix-hilden! This is still on our radar and I am looking forward to reviewing the project. I'll share an update here as soon as I can; hopefully in the next two or three weeks.

**Comment by felix-hilden** [comment]
Thanks for the quick response again, and for your kind words. I'm glad that it's still in consideration. Looking forward to it!

**Comment by felix-hilden** [comment]
Hello @joshubrown! I'm glad to announce that thanks to your update we've also implemented podcast support and published it!

And right when I was about to ask again, I decided to have a look at the page. Thank you for adding us in! No doubt the current global situation affects you too, so many thanks for taking the time. Hope you are well and healthy.
