### ISSUE TITLE
Embed widget has invalid meta viewport

### ISSUE THREAD

**Issue by Swatinem** [spotify/web-api#143]
Apparently the spotify embed widget does some server-side UA sniffing and when it detects a mobile device, it injects an invalid meta viewport:

```html
<meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;" />
```

This in invalid because the fields should be separated by comma instead of semicolon. Chrome logs a few warnings in the console about this:

```
?uri=spotify%3A…:5 The value "device-width;" for key "width" is invalid, and has been ignored.
?uri=spotify%3A…:5 The value "1.0;" for key "initial-scale" was truncated to its numeric prefix.
?uri=spotify%3A…:5 The value "1.0;" for key "maximum-scale" was truncated to its numeric prefix.
?uri=spotify%3A…:5 The value "0;" for key "user-scalable" was truncated to its numeric prefix.
?uri=spotify%3A…:5 Error parsing a meta element's content: ';' is not a valid key-value pair separator. Please use ',' instead.
```

While these are just warnings, we suspect that this causes some serious problems on ios when we embed the widget. Initial load is fine, but when rotating the device back and forth, safari does not apply the correct viewport anymore and our fixed positioned content has the wrong width.

**Comment by JMPerez** [comment]
Thanks @Swatinem. This repo keeps track of the issues related with the Web API. The Spotify Play Button is not part of it, and we try to track its issues on https://developer.spotify.com/technologies/widgets/spotify-play-button/.

In any case, thanks for letting us know. We are going to work on a fix soon.

**Comment by JMPerez** [comment]
And this should be fixed now!
I'm going to close the ticket. Feel free to reopen it if you still see the issue.

**Comment by Swatinem** [comment]
Yes, I was coming from that page, but there is no contact info on it, so I used the next best link on "support".

And thanks for the quick fix, the response time on this was really amazing :-)
