### ISSUE TITLE
Start/Resume a User's Playback route does not play song specified in "uris" field.  

### ISSUE THREAD

**Issue by liamtrampota** [spotify/web-api#1436]
Issue found on January 19th 2020.

#### Endpoint(s):
* `PUT player/play`

#### Scope(s):
* user-modify-playback-state

#### Steps to reproduce:
1. Open the API Console
2. Call the `player/play` endpoint with request body field `uris` set to some spotify:track:[track-id]

#### Expected behaviour:
Playback should play the track specified in uris.

#### Actual behaviour:
Playback plays next song in user's "Play Queue".

**Comment by hubgit** [comment]
I think this is the same as #1434 and #1439, with the best description of the issue, which is that the API endpoint at https://api.spotify.com/v1/me/player/play isn't reading the `uris` field from the request body.

**Comment by hubgit** [comment]
This is also reported in https://github.com/spotify/web-playback-sdk/issues/99

**Comment by hubgit** [comment]
@joshubrown This seems to be fixed by the recent update.

**Comment by joshubrown** [comment]
Great! @liamtrampota, please feel free to reopen this issue if you're still having trouble.
