### ISSUE TITLE
Incorrect track is played on webplayer device while sending single track uri via PUT v1/me/player/play

### ISSUE THREAD

**Issue by nocach** [spotify/web-api#1445]
Issue found on January 24th 2020.

#### Endpoint(s):
* `PUT v1/me/player/play`

#### Scope(s):
* user-modify-playback-state

#### Steps to reproduce:
1. Open web player (I used chrome browser)
2. record device id of the web player
3. call PUT v1/me/player/play?device_id=device_id_of_web_player with web player device id and track uri e.g.
```
{
"uris":["spotify:track:1jHgugWZailHKpPdDk57QU"]
}
```
4. While track is still playing execute previous command again but with another track, e.g.
```
{
"uris":["spotify:track:6uPVRZB9GYljJ52fmlIlUC"]
}
```

#### Expected behaviour:
Second track (spotify:track:6uPVRZB9GYljJ52fmlIlUC) is played.

#### Actual behaviour:
First track (spotify:track:1jHgugWZailHKpPdDk57QU) is played again instead of second (spotify:track:6uPVRZB9GYljJ52fmlIlUC)

#### Notes:
Desktop player plays second track as expected.

**Comment by joshubrown** [comment]
Hi @nocach, thank you for the report. We've made some changes to our Player API, can you still reproduce this issue?

**Comment by nocach** [comment]
Hi @joshubrown, thanks for quick reply! I've tested my code and tracks are now played as expected in web player. 

As a curious side note incorrect behavior is still present when I try to repreduce issue using web console (using https://developer.spotify.com/console/put-play/)... I'll close the issue
