### ISSUE TITLE
search for "song2" should be expanded to "song 2"

### ISSUE THREAD

**Issue by arska** [spotify/web-api#146]
Hello,

I search for https://developer.spotify.com/web-api/console/get-search-item/?q=blur+song2&type=track

I get an empty result.

I should get a reference to https://api.spotify.com/v1/tracks/3GfOAdcoc3X5GPiiXmpBjK, the lexer should split the "song2" to "song 2".

Cheers,
Aarno

**Comment by arska** [comment]
Similarly a search for https://developer.spotify.com/web-api/console/get-search-item/?q=Kuolemankurviin&type=track shoud also find https://developer.spotify.com/web-api/console/get-search-item/?q=Kuoleman+kurviin&type=track

**Comment by arirawr** [comment]
I'm going to close this issue in favour of the broader #244. You can follow for updates there.
