### ISSUE TITLE
How can I get recently played tracks by user id?

### ISSUE THREAD

**Issue by ygygbb** [spotify/web-api#1464]
Hi,  I am currently researching about Spotify user musical tastes and behaviors. I got some user id and I can get user profile from them.
From Spotify web API, I want to get recently played tracks by user id but I can get only current user recently played tracks.

I tried to change the endpoint  from
https://api.spotify.com/v1/me/player/recently-played
to
https://api.spotify.com/v1/users/{user_id}/recently-played
but It didn't work

Can I get them via API?

Thanks

**Comment by joshubrown** [comment]
Hi @ygygbb, `/v1/me/player/recently-played` is the correct endpoint. You will need the user's authorization before you can access their recently played tracks.

**Comment by ygygbb** [comment]
> Hi @ygygbb, `/v1/me/player/recently-played` is the correct endpoint. You will need the user's authorization before you can access their recently played tracks.

But I want to get recently played tracks from other user by using their user id can I do it?

**Comment by kevinguebert** [comment]
@ygygbb the Spotify API does not allow you to get a different user's recently played tracks. You can only get the current user's recently played tracks by using the `/me/player/recently-played` endpoint.
