### ISSUE TITLE
Player pause gives 401 Error: No token provided

### ISSUE THREAD

**Issue by JPilawka** [spotify/web-api#1467]
Player pause gives 401 Error: No token provided

Issue found on February 6th, 7th 2020.

#### Endpoint(s):
* `PUT /v1/me/player/pause`

#### Scope(s):
'streaming 
user-modify-playback-state 
user-read-email 
user-read-private'

#### Steps to reproduce:
I'm using spotify-web-playback-sdk
for other actions (authenticate, play) it's working fine (in fact after checking - seek also gives the same error), when console.log(headers object):
headers = {
              'Content-Type': 'application/json',
              'Authorization': 'Bearer ' + this.token
            };
the token is provided and this header is put into HTTP as below, and when the value of token (for other actions it's valid) copied and used in https://developer.spotify.com/console/put-pause/ - it's working.
url = 'https://api.spotify.com/v1/me/player/pause?device_id=',
http.put(url, {headers: headers}).   => Error 401

#### Expected behaviour:
returning 200, pausing background playback

#### Actual behaviour:
401 Error - "No token provided", playback still plays music

**Comment by Jensssen** [comment]
Did you solve the issue? Have the same problem, creating a new playlist :(

**Comment by JPilawka** [comment]
Yes. Mine was silly assumption that I use some Spotify function to put data to db. But I was using angular standard http.
I simply solved it by putting empty object like this:
http.put(url,**{}**, headers)
instead of just:
http.put(url, headers).
I didn't start making playlist and I don't know the API for making them but I assume you should send playlist object instead of empty one as I did but with POST.
I hope it helps.
