### ISSUE TITLE
Search for "Steven 'n' Seagulls" should find "Steve ´n´ Seagulls"

### ISSUE THREAD

**Issue by arska** [spotify/web-api#147]
Hello,

Opening separate issues here, feel free to merge/handle in one.

searching for artist "Steven 'n' Seagulls" https://developer.spotify.com/web-api/console/get-search-item/?q=Steven+%27n%27+Seagulls&type=artist

Gives empty response

Should find "Steve ´n´ Seagulls" (spotify:artist:77A9XsX4SDJlhB23yyUwQt)

Interestingly "Steve 'n' Seagulls" works: https://developer.spotify.com/web-api/console/get-search-item/?q=Steve+%27n%27+Seagulls&type=artist

**Comment by holmberd** [comment]
Works: https://play.spotify.com/search/Steven%20'n'%20Seagulls

**Comment by jsimonsson** [comment]
This: https://developer.spotify.com/web-api/console/get-search-item/?q=Steven+%27n%27+Seagulls&type=artist should work now. Sorry for late response.
