### ISSUE TITLE
Allow for the user's library to be played

### ISSUE THREAD

**Issue by Twometer** [spotify/web-api#1478]
Issue found on February 20th 2020.

#### Endpoint(s):
* `PUT /v1/me/player/play?device_id={id}`

#### Scope(s):
* user-modify-playback-state

#### Steps to reproduce:
1. Open the API Console
2. Call the `play` endpoint with `context_uri` set to `spotify:user:{user_id}:collection`

#### Expected behaviour:
The selected device starts playing the user's song collection just like any other playlist

#### Actual behaviour:
400 Bad Request: Non supported context uri

**Comment by felix-hilden** [comment]
To start playback, you should use `PUT`. Furthermore, `user` is not a valid context, as documented [here](https://developer.spotify.com/documentation/web-api/reference/player/start-a-users-playback/).

Am I missing something? I've never seen that `spotify:user:id:collection` URI before.

**Comment by Twometer** [comment]
Yes, I used PUT, sorry that is a typo.

This URI is sent to my web player by the API when I play my collection on a different device and then transfer Playback to it. That's why I thought that it would also work the other way around.

**Comment by felix-hilden** [comment]
Oh, I see. That would certainly be a good addition to the API. Maybe you could see if there exists such a feature request. If so, give it a thumbs up and close this issue. If not, edit this issue a bit to be more to that point.

**Comment by Twometer** [comment]
Seems like this feature request (#1297) already exists since 2019, oh well.
