### ISSUE TITLE
Preview URL Field is null

### ISSUE THREAD

**Issue by svarlamov** [spotify/web-api#148]
A lot of tracks that can be looked up through the web API return `"preview_url" : null`. Some example tracks include, `spotify:track:2ThslNnPGmK82KFcCF2Lxm`, `spotify:track:3Helw8TVmKNzP17d06PdWZ`, and `spotify:track:1B5TuVIIB1KixueZ0CHSJS`. Also an example playlist that seems to contain a lot of these null preview tracks is `spotify:user:timmay7:playlist:12PKzv33n3hTDNTpL6isTj`. The first page of results for this playlist contains 100 tracks from the get playlist's tracks endpoint, and 34 of those 100 tracks have the preview url set to `null`. None of these tracks are local tracks either. Is there any way to get the preview url field for these tracks?

**Comment by thelinmichael** [comment]
Hey @svarlamov!

This isn't a bug - some tracks do not have 30 second previews. This is most common when they're not available in any market. A good example of this is the first track you've mentioned - `spotify:track:2ThslNnPGmK82KFcCF2Lxm`.

Retrieving the metadata for this track shows that it's not available in any market,
```json
available_markets: [ ],
```
This is also the case for the tracks in the playlist you mentioned.

**I advise you to to use the `market` parameter when looking up track metadata or playlist tracks.** Using this parameter, the response will include different tracks if there's an alternative track (an identical track, also called _linked track_) that _is_ available in the given market. If there is such a track, it's more likely to have a `preview_url`.

For example, the first track mentioned has as we've concluded no `preview_url` and isn't available in any market. Let's say that your user is located in Sweden, country code `SE`. Looking up the track's metadata using the `market` parameter, returns

`GET` https://api.spotify.com/v1/tracks/2ThslNnPGmK82KFcCF2Lxm?market=SE

```json
preview_url: "https://p.scdn.co/mp3-preview/b51d0ed637d2e5cb3eb27565cce9a06f95599077",
```

Read more about relinking tracks in our [Track Relinking Guide](https://developer.spotify.com/web-api/track-relinking-guide/).

**Comment by svarlamov** [comment]
Thank you so much for your detailed explanation!

**Comment by verlinden** [comment]
Hi @thelinmichael

You said "some tracks do not have 30 second previews. This is most common when they're not available in any market"

Her is an example of track with available markets but no preview

`https://api.spotify.com/v1/tracks/28WYIQb2URGli0st5Ua1At`

Adding the `?market=XX` param for one of the available markets isn't working.
Can you tell me the reason why some albums with available markets haven't track previews ? On 3 albums I already checked for test purposes, 2 albums have no previews.

Thanks

**Comment by shi11** [comment]
Here's another example: https://api.spotify.com/v1/tracks/3ZpQiJ78LKINrW9SQTgbXd?market=US

**Comment by rickvdl** [comment]
I just noticed my app not working due to the preview URL being `null`. This is not specified in the API Documentation, so maybe it would helpful to add it?

Thanks!

**Comment by jscholes** [comment]
> This is not specified in the API Documentation, so maybe it would helpful to add it?

The [Web API Object Model](https://developer.spotify.com/web-api/object-model/) does describe this behaviour, but doesn't go into detail about when it is and isn't expected.  The preview_url key for both [full](https://developer.spotify.com/web-api/object-model/#track-object-full) and [simplified](https://developer.spotify.com/web-api/object-model/#track-object-simplified) track objects has the following description:

> A link to a 30 second preview (MP3 format) of the track. null if not available.

**Comment by rickvdl** [comment]
@jscholes Ah right now I see it, my bad :) Thanks for clarifying!

**Comment by Tzikas** [comment]
@verlinden did you ever figure out how to only query songs with a preview_url?  I see many examples with markets but null preview_urls.

**Comment by verlinden** [comment]
@Tzikas no, I didn't get the logic behind null preview_urls, if there is any...
Only Spotify guys can explain this but it seems they don't care about this official repository :/

**Comment by arirawr** [comment]
As documented, the preview URL can be null. This can happen for a variety of reasons related to licensing restrictions or technology. Your app should handle the possibility that a clip is not available.

**Comment by tetreault** [comment]
Just faced this problem too. What a bummer, but will have to work around.

**Comment by feedm3** [comment]
Also having this issue with some artists. 

When I'm trying to get the `preview_url` within my code (getting credentials server side via `clientCredentialsGrant()`) the field is null but when I'm using the official [api console](https://developer.spotify.com/web-api/console/get-artist-top-tracks/) the field is available.

I did some samples and the problem occurs for example for "The Rolling Stones" (ID: 22bE4uQ6baNwSHPVcDxLCe) but works for "Boys Noize" (ID: 62k5LKMhymqlDNo2DWOvvv)

**Comment by sgalizia** [comment]
@feedm3 I was able to do an Auth code flow and execute the call server side. On your client you have them go through the OAuth flow and when the code is returned to your client, send it to your server. With that one time code, your server can make a request for an auth token and refresh token. That flow should give you access to the `preview_url` if it exists.

**Comment by Xetera** [comment]
In case anyone is still struggling with this issue years after it was opened, you can scrape spotify embeds using the track id like https://open.spotify.com/embed/track/5lwWpQ71GKN3sWmk8zZr9g and select the `#resource` element for full song details which consistently includes the `preview_url` field. 

Not a fan of these kinds of workarounds but I genuinely have no idea why spotify would make an otherwise-public information available through `Authorization Code` but not `Client Credentials` when the data you're trying to get has nothing to do with a user and is even present without authentication. You should still try to work with `Authorization Code` if you can of course (which fixes this issue) but in my case that wasn't possible.

**Comment by ChildishForces** [comment]
Staggering, I can't think of a single good reason for this.
