### ISSUE TITLE
Getting a 404 error when querying the currently-playing API with an access_token generated from https://accounts.spotify.com/api/token

### ISSUE THREAD

**Issue by AlejandroLuperon** [spotify/web-api#1489]
Hello!

I am attempting to query the `https://api.spotify.com/v1/me/player/currently-playing` endpoint with an access token generated from `https://accounts.spotify.com/api/token`. 

The API call to the `api/token` endpoint will successfully return an `access_token`. However, when I query the `/v1/me/player/currently-playing` endpoint, I get the following response:

`{
  "error" : {
    "status" : 404,
    "message" : "Invalid username"
  }
}`

I used documentation around the [client credentials flow](https://developer.spotify.com/documentation/general/guides/authorization-guide/#client-credentials-flow) and documentation around the [currently-playing](https://developer.spotify.com/documentation/web-api/reference/player/get-the-users-currently-playing-track/) endpoint.

Expected Behavior:

Receiving the information for the users currently playing track.

Actual Behavior:

Getting a 404 response.

Thank you for any help in advance 😃

**Comment by felix-hilden** [comment]
Knowing the username might help, in case it has special characters or something. You could use the [user](https://developer.spotify.com/documentation/web-api/reference/users-profile/get-current-users-profile/) call to get this information.

**Comment by AlejandroLuperon** [comment]
@felix-hilden Thank you for responding!

My `display_name` is Alejandro Luperon, which I pulled from the "Try It" feature on the [doc](https://developer.spotify.com/documentation/web-api/reference/users-profile/get-current-users-profile/) for the `https://api.spotify.com/v1/me` endpoint. 

I tried to hit that endpoint with the `access_token` I generated from the `"https://accounts.spotify.com/api/token` end point, and received:

`{
  "error" : {
    "status" : 401,
    "message" : "Unauthorized."
  }
}`

However, when using the token I generated from `"https://accounts.spotify.com/api/token` and pass it to `https://api.spotify.com/v1/tracks/2TpxZ7JUBn3uw46aR7qd6V` to get track info, it returns `200 OK` with the payload.

I will look at the [client credentials flow](https://developer.spotify.com/documentation/general/guides/authorization-guide/) documentation again since I wouldn't expect a successful response from the `track` endpoint but not the `currently-playing` endpoint.

**Comment by felix-hilden** [comment]
Ah, but you are using the Authorisation Code Flow for your user token, right? Otherwise, the application token isn't enough to request user-authenticated endpoints.

**Comment by AlejandroLuperon** [comment]
@felix-hilden Ahhh, okay, that makes sense! I was intending to show what is currently playing at a venue on the venue's homepage. 

I'll close the ticket. Thank you for your time!
