### ISSUE TITLE
API limit requets

### ISSUE THREAD

**Issue by blackarcanis** [spotify/web-api#150]
Hi,
With our app we have reach the limit of requests we can do (429 error). 
But all our requests are identified (authorization bearer), and we do retry after as possible (some times we get 404 not found in place for same requests)...

What can we do for increase this limit ?

Thanks !

**Comment by holmberd** [comment]
https://developer.spotify.com/web-api/user-guide/#rate-limiting

**Comment by thelinmichael** [comment]
@blackarcanis, it's great that you're sending authenticated requests and that you're waiting to retry. It does sound very strange that you're getting 404 for the same URL, and I'd be very grateful if you could provide us with some example request. I'm curious about what type of request you're making the most and why you're making it so often - perhaps there's a way to reduce the amount of requests. I'm also interested in what you're doing to reduce the number of requests right now in terms of caching responses, avoiding to poll more than necessary.

**Comment by thelinmichael** [comment]
Closing this issue for now, please open it up if this is still relevant @blackarcanis.

**Comment by blackarcanis** [comment]
Hi Michael,
About why we doing some much requests is a question of traffic and by our system of App.
Can we contact your personnaly for explain that ? Or have a contact at Spotify parternship ?

Thanks a lot !

**Comment by thelinmichael** [comment]
Unless your application has thousands of users daily, I suspect this to be more of an engineering question in how you can reduce the amount of requests and still have a fully functioning app.

**Comment by blackarcanis** [comment]
Thanks for this fast reply !
Yes we are an app with thousands users daily utilisation and lot of more during some periods. 
The main endpoint we request is **search**, lot of time by hours. But we can't optimize this point, it's the main feature of our app :/

**Comment by thelinmichael** [comment]
Alright, feel free to contact me at thelinmichael@spotify.com and we can continue the conversation there.

**Comment by blackarcanis** [comment]
Thanks for that, an email was sent. 
We can continue the conversation on it now.
