### ISSUE TITLE
Requesting details about some of some users' public playlists should not return 404s

### ISSUE THREAD

**Issue by leonoverweel** [spotify/web-api#151]
Hi,

I'm using the Web API to get a list of a user's public playlists using this URL:
`https://api.spotify.com/v1/users/{userId}/playlists?limit=50`

Then, I'm looping through the returned playlist IDs and requesting them using this URL: `https://api.spotify.com/v1/users/{userId}/playlists/{playlistId}`

For some users, this works exactly as expected and gets me the data about all of their playlists. For other users, though, this only works for some a subset of their playlists, and returns 404s for the rest.

If a playlist ID is returned by the request for all public playlists, shouldn't its details always be requestable and not return 404s?

**Comment by jsimonsson** [comment]
Hi

Could you provide some example URLs?

One where you fetch the public playlists that then contains uris that return 404.

Some people have mistakenly filled in the userId to be the same (the user you were fetching) and only appending the playlistId when in fact the owner of a public playlist that user is managed by another user.
That is a common cause to get 404s.

**Comment by holmberd** [comment]
As said above. Check the 'owner' of each playlist before you request it.

**Comment by leonoverweel** [comment]
Ah, that's it. Thanks.
