### ISSUE TITLE
 Insufficient client scope when trying to get "current_user_recently_played"

### ISSUE THREAD

**Issue by yahyaest** [spotify/web-api#1518]
Issue found on February 19th 2015.

#### Endpoint:
PUT  https://api.spotify.com/v1/me/player/recently-played

#### Scope(s):
user-read-currently-playing

#### Steps to reproduce:
1-Authenticate user and store access token
2-Make call to get "current_user_recently_played" (see attached file)

#### Expected behaviour:
should get "current_user_recently_played"

#### Actual behaviour:
 File "C:\Users\Aymen\AppData\Local\Programs\Python\Python38\lib\site-packages\spotipy\client.py", line 170, in _internal_call
    raise SpotifyException(
spotipy.client.SpotifyException: http status: 403, code:-1 - https://api.spotify.com/v1/me/player/recently-played?limit=50:
 Insufficient client scope

**Comment by yahyaest** [comment]
[get_recent_played.txt](https://github.com/spotify/web-api/files/4405883/get_recent_played.txt)

**Comment by felix-hilden** [comment]
The [call](https://developer.spotify.com/documentation/web-api/reference/player/get-recently-played/) needs the `user-read-recently-played` scope. Can you try with that?

**Comment by yahyaest** [comment]
It works.
Thanks.
