### ISSUE TITLE
Access to previous playlist snapshots

### ISSUE THREAD

**Issue by thomasleese** [spotify/web-api#153]
I wanted to make a tool which could show how a user's music tastes change over time, so I was interested in being able to look at the history of playlists via snapshots. However, it seems that is is not possible with the current API. I think it would be a good addition if this was possible.

**Comment by hughrawlinson** [comment]
Hey @thomasleese - this isn't likely to be possible any time soon. I'd recommend that you look at the [top music](https://developer.spotify.com/web-api/get-users-top-artists-and-tracks/) endpoint to see how a users taste changes over time.
