### ISSUE TITLE
playlist cover image is lower resolution than what i uploaded

### ISSUE THREAD

**Issue by bradgarropy** [spotify/web-api#1530]
Issue found on April 10th 2020.

#### Endpoint(s):
* `GET /v1/playlists/0AbnxNMZqSCVog82luj1Ir/images`

#### Scope(s):
* playlist-read-collaborative

#### Steps to reproduce:
1. Open the API Console
2. Hit the following endpoint: [`https://api.spotify.com/v1/playlists/0AbnxNMZqSCVog82luj1Ir/images`](https://api.spotify.com/v1/playlists/0AbnxNMZqSCVog82luj1Ir/images)
3. Navigate to the returned image url: [`https://i.scdn.co/image/ab67706c0000da84ccc7975ca6bcb24dd4d49a37`](https://i.scdn.co/image/ab67706c0000da84ccc7975ca6bcb24dd4d49a37)
4. Note that the image size is `300x300`.

#### Expected behaviour:
I would expect that Spotify would return a URL to the playlist cover image that I uploaded at the original resolution (`1920x1920`).

#### Actual behaviour:
Spotify returns a low resolution (`300x300`) version of the playlist cover image I uploaded (`1920x1920`).

**Comment by nickthemichalek** [comment]
Spotify most likely does that to save storage space. They appear to store it at the largest size that will ever be displayed, that is your 300x300 px.

**Comment by bradgarropy** [comment]
I figured as much.

To get higher quality images, I hosted them myself at full resolution.
