### ISSUE TITLE
Add availability to track object

### ISSUE THREAD

**Issue by donb1991** [spotify/web-api#154]
I looking for a way to tell if a track is playable as a free member though the Spotify app. When creating a playlist some of the songs are greyed out and not playable. Would be helpful if track object had some indication if it was available on the Spotify app.

**Comment by jsimonsson** [comment]
Hi,

you can read this article on the developer site: https://developer.spotify.com/web-api/track-relinking-guide/

I would use the from_token functionality. Track relinking works on most endpoints that return tracks (playlists, track lookup etc).
