### ISSUE TITLE
CORS No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by kimanikelly** [spotify/web-api#1553]
**THE ERROR THAT PRINTS IN THE GOOGLE DEVELOPER TOOLS CONSOLE**

 (redirected from 'http://localhost:3000/auth/spotify') from origin 'http://localhost:3001' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

M.E.R.N Stack Oauth Login Issue: CORS No 'Access-Control-Allow-Origin' header is present on the requested resource that occurs during onClick. The app is fully functional when I added the Google Chrome CORS disable plugin and properly routes me to the Spotify login page and upon successful login, I'm routed back to my apps home page. The problem is if I'm not using the CORS plugin I'll be blocked from the Spotify login page. I tried using CORS middleware through NPM and tried to manually configure the server proxy but the error still occurs. I would be very appreciative If this issue can be fixed I'm trying to make the transition as a Web Developer and want to use this project for my portfolio. 

**SERVER SIDE API ROUTING USING NODE.JS, EXPRESS.JS, AND THE  PASSPORT SPOTIFY OAUTH STRATEGY**

// Requiring the passport module as a dependency
var passport = require('passport');

var SpotifyUserModel = require('../models/User');

module.exports = function (app) {

    // Initiates Oauth transaction and redirects the user to Spotify
    app.get('/auth/spotify', passport.authenticate('spotify', {

        // Scopes provide Spotify users using third-party apps the confidence that only the
        // information they choose to share will be shared, and nothing more

        // The user-read-private scope reads access to user’s subscription details (type of user account).
        // The user-read-email scope reads access to user’s email address.
        scope: ['user-read-email', 'user-read-private', 'user-read-playback-state', 'streaming', 'user-modify-playback-state', 'user-library-read',
            'user-library-modify']
        , showDialog: true
    }), function (req, res, next) {

    });

    // Redirects the user back to the app on successful authorization
    app.get(
        '/auth/spotify/callback',
        passport.authenticate('spotify', { failureRedirect: '/' }),
        function (req, res, next) {
            // Successful authentication, redirect home.
            res.redirect('http://localhost:3001/home');
        }
    );

    app.get('/users', function (req, res) {

        SpotifyUserModel.find(function (err, spotifyUsers) {
            if (err) {
                console.log(err)
            };

            // SpotifyUsers returns an array of objects storing all users and their credentials
            // The recentUser variable stores the recent user logged in of the SpotifyUsers array
            var recentUser = spotifyUsers.slice(-1);

            // The recentUserToken variable stores the recent users access token
            var recentUserToken = recentUser[0]['token'];

            // The recentUserDisplayName variable stores the recent users display name
            var recentUserDisplayName = recentUser[0]['spotifyProfileId'];

            // The recentUserEmail variabke stores the recent users email
            var recentUserEmail = recentUser[0]['email'];

            // The response returns a JSON object storing the following credentials
            res.send({
                Token: recentUserToken,
                DisplayName: recentUserDisplayName,
                Email: recentUserEmail
            });

        });
    });

};

**REACT LOGIN PAGE COMPONENT**
// Allows for React JSX to be used
// JSX is the React extension for HTML
import React from 'react';

// The react-helmet is a react component to add meta information into react components
// Will be used to set the page title
import { Helmet } from 'react-helmet';

// Allows for HTTP requests on the client side to retrieve/communicate
// With server side data(api-routes and database) and return responses
// Promised based HTTP client
import axios from 'axios';

// Loads the CSS stylesheet into login.js
import './style.css';

// Stores the value fo the page title 
var pageTitle = 'The-Aux | Login'

// ES6 class to define the Login component
class Login extends React.Component {
    constructor(props) {
        super(props);

        // This binding is necessary to make `this` work in the callback
        this.handleClick = this.handleClick.bind(this)
    };

    // The Event handler responsible for sending the user to the Spotify authorization page
    handleClick(event) {

        // HTTP GET route path
        axios.get('http://localhost:3000/auth/spotify')

            // Callback returns the response object(Spotify authorization data)
            .then(function (res) {

                // Redirects the browser to the Spotify authorization page
                window.location = 'http://localhost:3000/auth/spotify'

            })
            // If there’s a problem with the request, the promise will be rejected with an error object
            .catch(function (err) {
                console.log(err);
            });
    };

    render() {
        return (
            <React.Fragment>

                <Helmet>
                    <title>{pageTitle}</title>
                </Helmet>

                <nav className="navbar navbar-light bg-light">
                    <h1 className='the-aux'>The-Aux</h1>
                </nav>

                <button type="button" className="btn btn-secondary btn-lg" id='log-in-button'
                    // When this button is clicked the handleClick function is performed
                    // Redirecting to the Spotify authorization page is done by clicking the button
                    onClick={this.handleClick}>
                    <span>Login With Spotify</span>
                </button>

                <nav className="navbar fixed-bottom navbar-light bg-light">
                    <h3 className='copyright'>Copyright &copy; 2020</h3>
                </nav>

            </React.Fragment>
        )
    };
};

// Exports the Login component
export default Login;

**Comment by ardaorkin** [comment]
Same issue is here.
Is there any progress?

**Comment by ardaorkin** [comment]
Hey! Finally I find a solution!
I was making an api call with fetch() triggred by an onclick event and got an error that says 
<pre>Access to fetch at 'https://accounts.spotify.com/authorize?client_id=...&response_type=token&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fcallback&scope=user-read-private%20user-read-email&show_dialog=true' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.</pre>

My api call was like that:
<pre><code class="javascript">fetch("https://accounts.spotify.com/authorize?client_id=" + client_id + "&response_type=token" + "&redirect_uri=" + encodeURIComponent(redirect_uri) + "&scope=" + encodeURIComponent(scopes) + "&show_dialog=true", {
          method: "GET",
          
        })
          .then((res) => {
            window.location = res.url
          })</code></pre>
I remove the api call code and write just a little redirect line:
<pre>
        window.location = "https://accounts.spotify.com/authorize?client_id=" + client_id + "&response_type=token" + "&redirect_uri=" + encodeURIComponent(redirect_uri) + "&scope=" + encodeURIComponent(scopes) + "&show_dialog=true"</pre>
It's solve my problem.

**Comment by kimanikelly** [comment]
Thank you @ardaorkin I will go back and try your solution and verify with you if it corrected the issue.

**Comment by kimanikelly** [comment]
@ardaorkin I was able to bypass CORS by using <a href='/auth/spotify'></a> in my Login component and using express middleware app.use(cors()) for my routes on the server side thank you.
