### ISSUE TITLE
Get Audio Analysis for a Track returning NA or missing values for random features

### ISSUE THREAD

**Issue by AndrewFNJIT** [spotify/web-api#1555]
Issue found on April 25th 2020.

#### Endpoint(s):
* GET https://api.spotify.com/v1/audio-analysis/{id}

#### Scope(s):
* None (application is not using authentication)

#### Steps to reproduce:
1. Open the API Console
2. Call the audio-analysis with a track id

#### Expected behaviour:
A object holding low level audio features for the track (with no NA or missing values) 

#### Actual behaviour:
Certain values are missing for tracks. For example for the songID: "4lIxdJw6W3Fg4vUIYCB0S5" key_confidence is no longer present.

Also for some song ID's certain values for segments, beats, and tatums have been replaced with NA values that were not present a few days ago. The above mentioned songId is a good example.

**Comment by asabatba** [comment]
There's something weird going on.

I've fetched ~800 track analyses and there are no zeroes for the "key" and "mode" features.
For example, for "mode", 623 tracks have a 1 (major) and 194 tracks are not informed.
So I'm guessing missing values stand for zero?

**Comment by AndrewFNJIT** [comment]
Yes that could be it--I just wish Spotify updated its API docs to inform which values will now be "optional" for being returned across songs, as different songs contain different missing values. 

Certain columns are also just pure "NA" values (take a look at the loudness_end column under segments)

**Comment by asabatba** [comment]
In my sample I've counted the following values for loudness_end of segments:

```
706926 are missing 
817 existing, valid 
```

It definitely looks like a mistake on their part but it's weird they would leave this up for almost two weeks now. We'll see.

**Comment by joshubrown** [comment]
Hey all, thank you for reporting this issue to us. We've made some updates to the API and the problem should be resolved now. Join us over in the [Spotify for Developers forum](https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer) if you continue to see a problem with this endpoint.

**Comment by AndrewFNJIT** [comment]
Thanks so much! This fixed my problem :)
