### ISSUE TITLE
Get Followed Artists returning Null in incorrect cases

### ISSUE THREAD

**Issue by pkiv** [spotify/web-api#156]
Hi there, 

I have been encountering an error where I will call https://api.spotify.com/v1/me/following. For some users, it returns null even though if are following artists. When I test it in the Web API console (https://developer.spotify.com/web-api/console/get-following/) it returns the correct information. But when I call the API via Javascript or using CURL, it returns null. 

I'm not sure how to differentiate users where it doesn't work with users where it works. A userid where I can recreate this is "totalwannabe", and I have confirmed by logging into the account that he follows artists. 

I love the API, thank you so much for all the help!
- Paul

**Comment by thelinmichael** [comment]
Thanks for reporting @pkiv. Could you please provide us with the response from the API Console, as well as the exact cURL request you're making including the response? (access token not needed.)

**Comment by pkiv** [comment]
Hi @thelinmichael. 

Here is the request from the API Console:
`GET /v1/me/following?type=artist HTTP/1.1
Host: api.spotify.com
Accept: application/json
Content-Type: application/json
Accept-Encoding: gzip, deflate, compress
Authorization: Bearer *REMOVED*
User-Agent: Spotify API Console v0.1`

Here is the response from the API Console:
`HTTP/1.1 200 OK
Access-Control-Allow-Headers: Accept, Authorization, Origin, Content-Type
Access-Control-Max-Age: 604800
X-Content-Type-Options: nosniff
Content-Encoding: gzip
Transfer-Encoding: chunked
Access-Control-Allow-Credentials: true
Strict-Transport-Security: max-age=31536000;
Vary: Authorization
Keep-Alive: timeout=600
Server: nginx
Connection: keep-alive
Etag: "5b5a3d3bf333a1fca61a8a4502372cb9"
Cache-Control: private, max-age=0
Date: Thu, 07 Jan 2016 18:28:21 GMT
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, POST, OPTIONS, PUT, DELETE
Content-Type: application/json; charset=utf-8
{
  "artists" : {
    "items" : [ {
      "external_urls" : {
        "spotify" : "https://open.spotify.com/artist/2qxJFvFYMEDqd7ui6kSAcq"
      },
      "followers" : {
        "href" : null,
        "total" : 796116
      },
      "genres" : [ "complextro", "edm", "electro house" ],
      "href" : "https://api.spotify.com/v1/artists/2qxJFvFYMEDqd7ui6kSAcq",
      "id" : "2qxJFvFYMEDqd7ui6kSAcq",
      "images" : [ {
        "height" : 1000,
        "url" : "https://i.scdn.co/image/a706ba87cf368d76b3c9a7188d90cff1cac3aff5",
        "width" : 1000
      }, {
        "height" : 640,
        "url" : "https://i.scdn.co/image/9c131394fccee4a0c858e15a269e38cace1a1ea3",
        "width" : 640
      }, {
        "height" : 200,
        "url" : "https://i.scdn.co/image/63f056e65cf785939aa1d58a12d45df94a71b1ef",
        "width" : 200
      }, {
        "height" : 64,
        "url" : "https://i.scdn.co/image/9b53dc248342b449e135668ec2bb20c52a042095",
        "width" : 64
      } ],
      "name" : "Zedd",
      "popularity" : 77,
      "type" : "artist",
      "uri" : "spotify:artist:2qxJFvFYMEDqd7ui6kSAcq"
    }, {
      "external_urls" : {
        "spotify" : "https://open.spotify.com/artist/4MXUO7sVCaFgFjoTI5ox5c"
      },
      "followers" : {
        "href" : null,
        "total" : 312555
      },
      "genres" : [ "chamber pop", "indie christmas", "indie folk", "indie pop" ],
      "href" : "https://api.spotify.com/v1/artists/4MXUO7sVCaFgFjoTI5ox5c",
      "id" : "4MXUO7sVCaFgFjoTI5ox5c",
      "images" : [ {
        "height" : 942,
        "url" : "https://i.scdn.co/image/c9475278ed947f3b8241b5504ef8c7830897892b",
        "width" : 942
      }, {
        "height" : 640,
        "url" : "https://i.scdn.co/image/6184313919833a69dae627df26ef6aee29f00fed",
        "width" : 640
      }, {
        "height" : 200,
        "url" : "https://i.scdn.co/image/d1088fd4edf525a579242b6ffb768528acfe17c6",
        "width" : 200
      }, {
        "height" : 64,
        "url" : "https://i.scdn.co/image/a7a2606b415209c803b0651c4fe452f51697a2f0",
        "width" : 64
      } ],
      "name" : "Sufjan Stevens",
      "popularity" : 73,
      "type" : "artist",
      "uri" : "spotify:artist:4MXUO7sVCaFgFjoTI5ox5c"
    } ],
    "next" : null,
    "total" : 2,
    "cursors" : {
      "after" : null
    },
    "limit" : 20,
    "href" : "https://api.spotify.com/v1/me/following?type=artist&limit=20"
  }
}`

Here is the cURL request:
`curl -X GET "https://api.spotify.com/v1/me/following?type=artist" -H "Accept: application/json" -H "Authorization: Bearer *REMOVED*"`

Here is the response:
`{
  "artists" : {
    "items" : [ ],
    "next" : null,
    "total" : 0,
    "cursors" : {
      "after" : null
    },
    "limit" : 20,
    "href" : "https://api.spotify.com/v1/me/following?type=artist&limit=20"
  }
}`

**Comment by pkiv** [comment]
Just an update to this, I am now seeing the responses coming in correctly for my test user. Was something changed on the back end?

**Comment by jsimonsson** [comment]
Hey

Just to be able to see if there was something wrong, would you mind telling me where you made these requests from? Region/country that is.

**Comment by pkiv** [comment]
Hi @jsimonsson, sorry for the delay.

The requests were coming from Los Angeles/US.

**Comment by jsimonsson** [comment]
Hey

As I suspected. The machines in US had a hiccup, it should be alright now. Thanks for the report!

**Comment by chasenyc** [comment]
I am experiencing this issue currently.
