### ISSUE TITLE
Podcast API not working properly

### ISSUE THREAD

**Issue by antiabed** [spotify/web-api#1569]
Hi there,

When I try to pull info from a podcast or episode, using the correct GET request and authorization (it works for tracks, albums and artists) I get an error. It’s the same for shows and episodes, both claiming that the ID doesn’t exist. But I tried the link and it works so the ID must be correct.

Here’s an example I tried it with:

https://api.spotify.com/v1/shows/0lcm41E37AFqyOBXBf1Asv

**Comment by joshubrown** [comment]
Hi @antiabed! Some shows are only available in certain places. You may see a 404 response when the user account associated with the authorisation token is registered to a country where the content is not available. Hope this helps.

**Comment by antiabed** [comment]
I’m sorry, that doesn’t seem to be the problem.

I logged into Spotify with that same user account and all the shows and episodes that get the error are available there.
