### ISSUE TITLE
Audio Analysis: HTTP 404 Not Found

### ISSUE THREAD

**Issue by nicolasanjoran** [spotify/web-api#1570]
Issue found on May 5th 2020.

#### Endpoint(s):
* `GET /v1/audio-analysis/{track_id}`

#### Scope(s):
* None (application is not using authentication)

#### Steps to reproduce:
1. Open the API Console
2. Call the `audio-analysis` endpoint.
3. Try with the default track ID.

#### Expected behaviour:
The audio analysis should show up.

#### Actual behaviour:
404 Not found

```json
{
  "error": {
    "status": 404,
    "message": "analysis not found"
  }
}
```

**Comment by nicolasanjoran** [comment]
After some more trials, it sees that it doesn't work for most of the songs. However, for some of them, the analysis is retrieved. I tried using a VPN to see if its a local issue, but it doesn't impact the results, the API returns the same results for all VPN locations.

Example of a working ID:
https://api.spotify.com/v1/audio-analysis/1wjzFQodRWrPcQ0AnYnvQ9

Example of an ID that doesn't work:
https://api.spotify.com/v1/audio-analysis/06AKEBrKUckW0KREUWRnvT

**Comment by Tinouga** [comment]
Same as you, I receive the audio analysis for maybe 1 in 20 songs (getting 404 for the rest).

**Comment by njm222** [comment]
I am also having the same issue with the endpoint.
Looks like a duplicate issue #1555

**Comment by nicolasanjoran** [comment]
@njm222 no it's not a duplicate.

10 days ago, the audio-analysis endpoint started to send json files with missing attributes, this is what the issue #1555 is about. The new issue I opened is about the analysis not being retrieved using the endpoint, which results in a HTTP 404.

**Comment by Tinouga** [comment]
> @njm222 no it's not a duplicate.
> 
> 10 days ago, the audio-analysis endpoint started to send json files with missing attributes, this is what the issue #1555 is about. The new issue I opened is about the analysis not being retrieved using the endpoint, which results in a HTTP 404.

Yeah and the #1555 can be solved using default values, this one is another matter :|

**Comment by nicolasanjoran** [comment]
For information, I started to get 404 errors ~10h ago if that's helpful (at 3am GMT+2).

**Comment by MadalenaSousa** [comment]
Just leaving a comment because I'm having the same issue

**Comment by Tinouga** [comment]
It seems to be working now, I'm not getting any 404 anymore (tested with a few tracks that were giving me this error).

**Comment by nicolasanjoran** [comment]
> It seems to be working now, I'm not getting any 404 anymore (tested with a few tracks that were giving me this error).

Same here, I was just waiting for a few minutes before closing the issue, just in case.
