### ISSUE TITLE
EchoNest "audio-features" API

### ISSUE THREAD

**Issue by robhardwick** [spotify/web-api#158]
In the [Sort Your Music](https://github.com/plamere/SortYourMusic) project there is a call to a [/v1/audio-features](https://api.spotify.com/v1/audio-features) endpoint which was added in commit [9688e9c](https://github.com/plamere/SortYourMusic/commit/9688e9cb2508f4f8e1b89964e413d5fadf7ccf51) and I would like to use it in my app. However, I can't find any documentation for the endpoint and when I try to use it I get a "403 Forbidden" response (all my other requests to the Spotify Web API are working correctly).

Can you let me know what the status of the "audio-features" endpoint is? Can it be used by 3rd-party developers? If not, do you know if it'll be made available in the future?

Thanks,

Rob

**Comment by holmberd** [comment]
Also used [here](https://github.com/plamere/spotipy/tree/365d3714bfff9b64de9302d24f2f3ff01cfdfa9b)

**Comment by plamere** [comment]
the audio-features api is in beta. No official announced date, but it is pretty far along. If you are interested in being a beta tester, let me know. (email paul at spotify )
