### ISSUE TITLE
Search for type=episodes, returning null values for all results

### ISSUE THREAD

**Issue by mikerhyssmith** [spotify/web-api#1589]
Issue found on May 30th 2020.

#### Endpoint(s):
* `GET /v1/search`

#### Scope(s):
* None (client_credentials)

#### Steps to reproduce:
1. Make a request to the search api with type=episode or type=show

#### Expected behaviour:
Each item is an episode or show.

#### Actual behaviour:
Pagination information is correct showing the total results, but all the individual results are null

```js
{
  "episodes": {
    "href": "https://api.spotify.com/v1/search?query=Fish&type=episode&offset=20&limit=20",
    "items": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
    ],
    "limit": 20,
    "next": "https://api.spotify.com/v1/search?query=Fish&type=episode&offset=40&limit=20",
    "offset": 20,
    "previous": "https://api.spotify.com/v1/search?query=Fish&type=episode&offset=0&limit=20",
    "total": 46297
  }
}
```

**Comment by mikerhyssmith** [comment]
Ahh it looks like adding the market returns valid results

**Comment by joshubrown** [comment]
That is right @mikerhyssmith - glad you were able to resolve this. If you have any further questions then let us know in Spotify's new [developer community forum](https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer) 🙂
