### ISSUE TITLE
Retry-After response header not accessible in my JavaScript application

### ISSUE THREAD

**Issue by Roaders** [spotify/web-api#159]
As noted in this stackoverflow post:
http://stackoverflow.com/questions/34963169/accessing-headers-in-spotify-api-call-response
I am unable to access the Retry-After header in javascript despite being able to see it in the browser debug console. I suspect that this is a problem with the Access-Control-Expose-Headers header being incorrectly setup on the server (I could well be wrong but based on my reading that seems to be the case).
I realise that there are much better ways to request this information by requesting multiple tracks at once but I was trying to get this example working first before I move on to a better implementation.

**Comment by hughrawlinson** [comment]
Thanks for this report @Roaders! I've passed it on to the relevant team. 🐈

**Comment by Roaders** [comment]
well thanks for that. A shame that it took 8 months and I've moved onto other projects now...

**Comment by eivhyl** [comment]
Any updates on this?

**Comment by bih** [comment]
Hey folks!

Great news - I can definitely confirm we have `Retry-After` in the `Access-Control-Allow-Headers` header. It has been added in there already for a while, so I'll go ahead and formally close this issue. Let us know if you have any other questions!
