### ISSUE TITLE
502 Bad gateway

### ISSUE THREAD

**Issue by Jensssen** [spotify/web-api#1590]
I am getting a 502 Bad gateway since Yesterday for the user device endpoin

Issue found on June 02th 2020.

#### Endpoint(s):
* `v1/me/player/devices`

#### Steps to reproduce:
1. Just try it out here? https://developer.spotify.com/console/get-users-available-devices/

#### Expected behaviour:
Get response code 200

#### Actual behaviour:
502 Bad gateway

**Comment by Jensssen** [comment]
Now it works again. What could be a reason for such a temporary error? Is there any chance that such an error is cased by the client?

**Comment by joshubrown** [comment]
Glad to hear that this is working again for you, @Jensssen. 500 series errors usually indicate a problem on Spotify's side. If you have any other questions, feel free to drop by our [new developer community forum.](https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer)
