### ISSUE TITLE
Temporary 504 Bad Gateway Error

### ISSUE THREAD

**Issue by blackarcanis** [spotify/web-api#1591]
Hi !
Since couple of days now the Spotify API is returning more and more (often by group of 5 minutes) a 504 Bad Gateway Error to all our requests (whatever they are on https://api.spotify.com/v1/.......).

Did you got some servers issues recently and are you working on that ? 

Thank you for your help !

**Comment by joshubrown** [comment]
Hi @blackarcanis. Thank you for reporting this. We were having some temporary server issues a few days ago. If you continue to see problems then please do drop by our [developer community forums](https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer) and let us know.

**Comment by blackarcanis** [comment]
@joshubrown Thank you for your reply. Yes unfortunately still experiencing the 504 Error time to time... A topic has been opened on the developper comunity forums => https://community.spotify.com/t5/Spotify-for-Developers/Temporary-504-Bad-Gateway-Error/m-p/4974053#M448
