### ISSUE TITLE
Cannot get more above offset 50 for a user's favorite tracks

### ISSUE THREAD

**Issue by Maninhell** [spotify/web-api#1592]
#### Endpoint(s):
* `GET /v1/me/top/{type}`

#### Scope(s):
* User-top-read

#### Steps to reproduce:
1. Open the API Console
2. Call the `Get User's Top Artists and Tracks` endpoint with `offset` `50` or above

#### Expected behaviour:
A List of X top songs of a user, beginning with the offset of 50

#### Actual behaviour:
Empty list of top songs, href resets to offset 50 if offset is set to above 50 as well as limit resets to 0

**Comment by joshubrown** [comment]
Hi! This endpoint returns a maximum of 50 tracks. If you have any other questions, feel free to join us in the Spotify [developer community forum](https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer).
