### ISSUE TITLE
Can I like a song from my Discover Weekly playlist?

### ISSUE THREAD

**Issue by Beinish** [spotify/web-api#1593]
Hello,
I've searched through all of the playlist or track related commands but either I'm missing it or it doesn't exist.

I would like to be able to play songs from my Discover Weekly or Release Radar/Daily Mix playlists and like or remove a song. I see no command to perform either of those 2 actions. If I like a song it adds it automatically to my liked songs, if I remove it, it just removes it from the playlist and plays the next song.

It might be my inexperience with Spotify, but is [this](https://developer.spotify.com/documentation/web-api/reference/library/save-tracks-user/) what I'm looking for?

Any help on this be great :)

**Comment by joshubrown** [comment]
Hi @Beinish! Using the API you can [add songs to your library](https://developer.spotify.com/documentation/web-api/reference/library/save-tracks-user/) and [skip tracks](https://developer.spotify.com/documentation/web-api/reference/player/skip-users-playback-to-next-track/). There is no dislike function, I'm afraid. If you have any other questions then feel free to drop by the [Spotify for Developers forum.](https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer)
