### ISSUE TITLE
New client library for Rust: rspotify

### ISSUE THREAD

**Issue by marioortizmanero** [spotify/web-api#1595]
Hello,

I'd like to notify the Spotify devs of [rspotify](https://github.com/ramsayleung/rspotify), a client library for Rust that isn't listed in [the official page of Web API Libraries](https://developer.spotify.com/documentation/web-api/libraries/). I saw something similar done for tekore at https://github.com/spotify/web-api/issues/1429, so I figured I'd mention this one, too.

It's already quite used in the Rust community, with a total of [65K+ downloads, 15 versions released](https://crates.io/crates/rspotify) and almost 200 stars on GitHub. It's based on [spotipy](https://github.com/plamere/spotipy), a library for Python.

Pinging @joshubrown, who attended the issue I mentioned for Tekore.

Thanks in advance :)

**Comment by ramsayleung** [comment]
Author of [rspotify](https://github.com/ramsayleung/rspotify) there, thanks @marioortizmanero for submitting an issue there. I think it'll be great if rspotify could be listed in the official page of Web API Libraries, which could help more people want to create some creative stuff with Spotify in Rust, and [rspotify](https://github.com/ramsayleung/rspotify) is the first Rust API Libraries for Spotify(as far as I know). Thus, it will be awesome to see more people using Spotify and Rust :)

**Comment by joshubrown** [comment]
Thank you for letting us know about the library, @ramsayleung @marioortizmanero. We'll take a look at it the next time we update that list. This issue tracker is no longer used, join us in the [Spotify for Developers](https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer) forum if you have any further questions.

**Comment by marioortizmanero** [comment]
Thanks! Have you thought about archiving this repository? That'll avoid devs creating more issues here by mistake like me.

**Comment by joshubrown** [comment]
Good suggestion @marioortizmanero, we will do that :)
