### ISSUE TITLE
Support for Top and Viral Charts

### ISSUE THREAD

**Issue by HSkogmo** [spotify/web-api#16]
I would like for Charts - Country specific Top and Viral - to be available through the API.

With this the chart for each country could be mined and then eliminate reoccurring songs over the multiple charts to find the "most unique songs" for each country. A "Sound of {Sweden,Norway,United Kingdom}" if you will.

Think it would be a nice way of discovering new music :smile:

**Comment by thelinmichael** [comment]
Hi @HSkogmo! Charts are actually available over a HTTP API, it's just not currently part of the official Spotify Web API as documented on the [Developer Site](https://developer.spotify.com) which means that we can't offer any support on it. You can read more about the Charts API [here](http://charts.spotify.com/docs).

Example request: http://charts.spotify.com/api/tracks/most_streamed/global/daily/latest

**Comment by RachelScodes** [comment]
@thelinmichael is charts access via api officially dead?

**Comment by thelinmichael** [comment]
Let's track the progress of Charts related endpoints in #33. (https://charts.spotify.com is dead.)
