### ISSUE TITLE
Remove User’s Saved Tracks doesn't work

### ISSUE THREAD

**Issue by Foldalake** [spotify/web-api#160]
It is not possible to remove user's saved tracks with, for example:
DELETE https://api.spotify.com/v1/me/tracks?ids=5obZZO4ZyrWeLoHDWEUNEI

Issue found on January 27th 2016.

Steps to reproduce: Use the [Spotify API console](https://developer.spotify.com/web-api/console/delete-current-user-saved-tracks/?ids=5obZZO4ZyrWeLoHDWEUNEI)

Expected behaviour: The song is removed from my songs.

Actual behaviour: The song is not removed. Response is 200 OK

**Comment by JohnnyCrazy** [comment]
Did you check the result via the spotify client? If so, try restarting it after you removed the track. Last time I checked, my music library also didn't update itself after a album /track removal.

**Comment by Foldalake** [comment]
Yes, I have the Spotify client running on my 2nd screen :) I tried restarting the client after the web api delete call, but the song is still there.

Adding a song via the web api works fine, and updates immediately in the client. But removing the song via the web api has no effect.

**Comment by asmitter** [comment]
I believe what you see is due to caching in the client.
You can check that the remove has worked by using the "Check Current User's Saved Tracks" endpoint: https://developer.spotify.com/web-api/console/get-current-user-contains-saved-tracks/
If the remove is successful, the call will return "false".

**Comment by Foldalake** [comment]
Ah, I see. You are absolutely correct!

But still, strange that the behaviours differ for adding and deleting...
