### ISSUE TITLE
Search api returns zero results when putting wildcards around a query containing special characters

### ISSUE THREAD

**Issue by maxh-** [spotify/web-api#161]
Issue found on January 28, 2016.

Endpoint(s): /search/ 

Scope(s): None (application is not using authentication)

Steps to reproduce: Use the API Console. Compare https://developer.spotify.com/web-api/console/get-search-item/?q=jävlaranamma&type=track to the same query with wildcards added: https://developer.spotify.com/web-api/console/get-search-item/?q=*jävlaranamma*&type=track 

Expected behaviour: Should return at least the same results as the query without wildcards, as is the case for queries which don't contain special (URL-encoded) characters e.g. åäö.

Actual behaviour: Doesn't return any tracks.

**Comment by jsimonsson** [comment]
Hey!

This should be fixed now!

**Comment by renchuqiao** [comment]
Adding to this issue: if the artist name has special character like $,#,@, the wildcard will return no tracks. 

Steps to reproduce: Use the API Console. Compare https://developer.spotify.com/web-api/console/get-search-item/?q=ke$h*&type=artist to the same query with wildcards added: https://developer.spotify.com/web-api/console/get-search-item/?q=kesh*&type=artist
