### ISSUE TITLE
getUserPlaylists doesn't return the correct number of playlists every time

### ISSUE THREAD

**Issue by jacobgreen25** [spotify/web-api#162]
I filed an issue with JMPerez (https://github.com/JMPerez/spotify-web-api-js) who suggested that I refile the issue here. We determined that the calls were the same except for the etag and Auth token. He thought it may have been an issue of scope but since I'm only giving users ['user-read-private', 'playlist-read', 'playlist-read-private', 'playlist-read-collaborative'] I can't see that being an issue (using https://github.com/thelinmichael/spotify-web-api-node to assign scope and do authorization). So personally I have 11 playlists and sometimes it returns 6 of them and sometimes it returns all 11. Seems like updating the auth token sometimes resolves the issue.

Here is the original ticket I filed with pictures of the request/response headers.
https://github.com/JMPerez/spotify-web-api-js/issues/29

**Comment by thelinmichael** [comment]
@jacobgreen25, by looking at the user `spotify:user:scottwalstead` I can see that he's got 6 public playlists, so the remaining 5 are private and potentially collaborative. The reason you'd only retrieve the public playlists using the API would be that your application 

- is making the request on behalf of the user `scottwalstead`, but without the `user-read-private` and `user-read-collaborative` scope.
- is making the request on behalf of a user that isn't `scottwalstead`. (The scopes wouldn't matter in that case.)

Could you please double-check that any of the above isn't what's causing this?

**Comment by thelinmichael** [comment]
Closing this issue, please re-open it if you have more information @jacobgreen25.

**Comment by jacobgreen25** [comment]
I have the user-read-private and user-read-collaborative scope when I make the request so it should always work and I'm the one making the request, as scottwalstead. Whenever I logout and log back in, it seems to resolve the issue. Simply fetching the list of playlist only resolves the issue sometimes.
