### ISSUE TITLE
You can't' play music when the playlist is sorted by USER

### ISSUE THREAD

**Issue by Epok1976** [spotify/web-api#163]
Hello,

Issue found on February the 1st 2016

Device : desktop release 1.0.20.101.ge6957e14

I have created a playlist and shared it with my friends. They added some tracks but when I sort the playlist by "USER" (from the top of the column) I can't play the music. The CTA "PLAY" ,on the left of the track, doesn't respond correctly.

![sortbyuser](https://cloud.githubusercontent.com/assets/17006077/12718716/ab346452-c8f0-11e5-8770-f85b59bfee9d.JPG)

Regards,
Antoine

**Comment by thelinmichael** [comment]
Great bug report, but unfortunately this is the wrong forum for it as it only handles Spotify's Web API. Please head over to the [Spotify Community](https://community.spotify.com) for issues in Spotify's apps.
