### ISSUE TITLE
Get track popularity without full album object

### ISSUE THREAD

**Issue by psarnowski76** [spotify/web-api#164]
I have an issue, mostly dealing with trying to be as efficient as possible.

I have a page that shows all of the albums tracks, and I need to get the Popularity number.

The API can return me the album's tracks but it returns a simplified version of the Tracks of object, which lacks the one thing I also need, the Popularity score.

Now I'm forced to iterate the albums collection and recall the API for each track, to get the full track object so I can get the popularity score.

This is wasting a lot of bandwidth, as I already have everything else I need in the simple Track object and am just downloading repeated data.

Is there any way we can either get the Popularity added to the simple Track object, or add an API call to just get the Popularity score for a Track without having to get all the other information?

**Comment by jamesfairhurst** [comment]
Use the **Get Several Tracks** call so it's only one more request:
https://developer.spotify.com/web-api/get-several-tracks/
