### ISSUE TITLE
Can't modify user private data with Client Credential Flow

### ISSUE THREAD

**Issue by mastier** [spotify/web-api#165]
The current API as far as I know makes it impossible to modify private user data like playlist
https://developer.spotify.com/web-api/authorization-guide/#client-credentials-flow

Can it be added option for specifying scopes ?

**Comment by jsimonsson** [comment]
The client credentials flow is for backend to backend calls, identifying a application and is not ment to be used as a way to do things on behalf of an user. To do things on behalf of an user you need to obtain an access token through either https://developer.spotify.com/web-api/authorization-guide/#authorization-code-flow or https://developer.spotify.com/web-api/authorization-guide/#implicit-grant-flow

The access token can then be used from either a client or a backend to do things on behalf of an user through the Web API.

**Comment by mastier** [comment]
This is very inconvenient to create user's own application to handle only his own data. To achieve what you say I need to have publicly accessible HTTP(S) server link to it can respond with authorization code, then it can get access token.

What discourages you from enabling that for users ?

**Comment by jsimonsson** [comment]
If you only need to handle ONE user (your own I presume) you can do the first part of client credential flow, obtain the refresh token, save the refresh token and use that to negotiate for an access token when you want to do something for that user.

I'll repeat, client credential flow is not a way to identify a specific user. It is to identify a specific application. It is done by using a clientID and a secret. These has nothing to do with a specific user. You will always have to go through accounts.spotify.com in some way if you want to be identified as a specific user. There are currently two flows, one fit for short sessions in a web app (implicit grant flow) and one for longer sessions where the user doesn't need to be active for a service to do things (authorization code flow + the use of refresh token).

**Comment by mastier** [comment]
Alright! So, according to your words, I shall first send
POST https://accounts.spotify.com/api/token
and in the request body I sent "grant_type=refresh_token".
but here I still need previously obtained refresh_token

So either way I need to got through either _implicit grant flow_ or  _authorization code flow + the use of refresh token_ , to get the token with the proper scopes access.

To sum, I see there's now way so I can simple specify scopes authorize user with credential so my app get the access to playlist modification without being authorized by web callback rather that simply received as response json from api directly.

**Comment by jsimonsson** [comment]
That is correct, you cannot do things on behalf of an user without going through the oauth2 processes we provide through accounts.spotify.com.

**Comment by mastier** [comment]
So I assume you are not leaning to enable the user authorization process without redirect-uri callback ? Actually I would like put that in the wishlist, therefore this "issue" here occured. Any change for that at all ? Are you leaning toward implementing that or rather not ? If not, I think this issue might be easily closed, as nothing more is pending.

**Comment by mastier** [comment]
Hello ? :-)

Additional question is there anyway there allowing authorize user other than web-api ? I see there is libspotify, but will not be developed anymore according to this (https://developer.spotify.com/technologies/libspotify/).

I want to have access to modification of playlist and other like the regular Desktop or Mobile application without need of having deployed webapp, to which redirect-uri points to.

Any plans for that ?

**Comment by jsimonsson** [comment]
Hello,
no, no plans for that at the moment. To be able to go through the authentication flow you'll have to have  a deployed webapp for the authentication part.

**Comment by mastier** [comment]
(sighs deeply) I see. Anyway, thanks for explanation.

**Comment by asmitter** [comment]
Playlist creation/updates etc must always be tied to a user, so there is no way to do that without going through the oAuth flow.

Assuming you want to do all playlist manipulation as a single user: Why not temporarily deploy an app to do the flow and get your first access_token and refresh_token?
The token can be refreshed without a callback_url, so you do not need to maintain the app once you have authenticated the user that first time.

**Comment by mastier** [comment]
I could it, but if I want share the application to someone else, like posting on github, the one must have access to that webapp to use my app. I also considering building webapp publicly accessible, but I don't have time resources for that now. I see that there was some solution on the net, but the guy used the old API and now the project retired until he create a new one.

Does desktop application (I use Linux Beta) uses the webapi to authorize itself ? Does it make some dirty trick, that in between the process let's itself to be authenticated by getting authorization code from some special spotify temporary url after I put my credentials in place authorizing the desktop app ?

**Comment by asmitter** [comment]
You could include the code for the temporary auth solution. Just make sure you wipe any client_id and client_secrets before pushing.

Anyway, there is no other way to go about editing playlists via the Web API.
