### ISSUE TITLE
500 Server Error consistently for /playlists

### ISSUE THREAD

**Issue by richyjay** [spotify/web-api#167]
Cannot retrieve playlists for user ID: kingwig

Issue found on February 11th 2016.

Endpoint(s): /users/kingwig/playlists 
Scope(s): playlist-read-private, playlist-read-collaborative

Steps to reproduce: Use the API Console, https://developer.spotify.com/web-api/console/get-playlists/

Expected behaviour: A list of playlists returned

Actual behaviour: 500 Server Error (consistently)

Note: I run www.britify.com and have been instructed by Spotify Support to migrate from libspotify to the Web API, but it doesn't work with my account. The website has been featured in Time, The Guardian, BBC Click etc.

**Comment by holmberd** [comment]
I can confirm a 500 server error for that user ID with 'Get a List of a User's Playlists' API.

**Comment by jsimonsson** [comment]
Hi!

Thanks for the report, will look into it.

**Comment by asmitter** [comment]
I revisited this and it appears to work fine. Do you still see a problem, @richyjay?

**Comment by richyjay** [comment]
All fixed, not sure if changes were made to my account or server side but everything's working now, thanks!
