### ISSUE TITLE
No notifications of new playlist followers

### ISSUE THREAD

**Issue by juanlanus83** [spotify/web-api#169]
Hi, 
I use to receive a notification when some new user follow a playlist. But now I don´t. I receive only some. 
For example, I receive a notification that a user followed me on one playlist, but he followed me on 3 playlists (but I wasnt notified of those other two).
Also it is not possible to see which are the users that follow each playlist (this was possible at the begining of Spotify). 
Thanks! 
Juan

**Comment by thelinmichael** [comment]
@juanlanus83, this Github repository covers [Spotify's Web API](https://developer.spotify.com/web-api) and not how the Spotify apps work. I recommend that you head over to the [Spotify Community](https://community.spotify.com), as that's more suitable place to report bugs and ideas for the Spotify app.
