### ISSUE TITLE
Save and Remove Track from User's Library - returns 200 OK with Content-Type application/json

### ISSUE THREAD

**Issue by jayenashar** [spotify/web-api#17]
https://developer.spotify.com/web-api/save-tracks-user/ seems to return a 200 OK with no content whereas https://developer.spotify.com/web-api/follow-artists-users/ seems to return a 204 No Content.  Personally, I prefer the latter, because 204 works better with jQuery.ajax(), but at least make it consistent between the different endpoints.

**Comment by thelinmichael** [comment]
Thanks for the feedback @jayenashar, I agree that this is an inconsistent part of the API.

**Comment by thelinmichael** [comment]
This has been fixed. The API still responds with status code 200, but the Content-Type has been set to `text/plain` which should work with jQuery.ajax(). Changing the status code to 204 would arguably improve consistency, but it could break existing implementations so changing the Content-Type is a friendlier fix.

Ping @jayenashar.
