### ISSUE TITLE
Ability to add songs to the listener's queue

### ISSUE THREAD

**Issue by Twister1002** [spotify/web-api#170]
I would like to request a way to use the Play Queue. I am trying to develop an application where I could make a music jukebox and add people's songs to the Play Queue. This would be a great thing for streamers and such.

**Comment by thelinmichael** [comment]
Closing this as it's covered in #15.

**Comment by jhass** [comment]
Looks like #15 was closed with only playback control added or am I missing something? If not I guess this should be reopened.

**Comment by MichaelMallett** [comment]
@thelinmichael P;ease reopen this, as #15 does not cover this functionality, there is no add to queue functionality listed there.

**Comment by martlind** [comment]
+1 to reopen

**Comment by ryantrappy** [comment]
+1 to reopen

**Comment by tikotus** [comment]
I was really looking forward for #15 to add this but it didn't.
I need this functionality so bad!

**Comment by ski7777** [comment]
Wats the state? When to expect a queue API?

**Comment by tegillis** [comment]
+1

**Comment by deb42** [comment]
+1

**Comment by daniel-centore** [comment]
This looks like a duplicate of #462

**Comment by arirawr** [comment]
I'm going to close this issue as a duplicate of #462, which appears to have more discussion. We will post any updates to this issue over there!
