### ISSUE TITLE
[request] Additional info about a track

### ISSUE THREAD

**Issue by Zhigalin** [spotify/web-api#175]
Hi!
I think it's nice to add some more data in this endpoint: https://api.spotify.com/v1/tracks/{id}
Like total listeners, monthly listeners, total/monthly listens, popularity among different markets...
What do you think of it?

**Comment by Zhigalin** [comment]
@JMPerez @thelinmichael Anyone?

**Comment by thelinmichael** [comment]
@Zhigalin, thanks for opening the issue. It's an interesting idea and I can imagine that it'd enable a lot of interesting use cases. It's however not likely to be delivered in the near future.

**Comment by hughrawlinson** [comment]
I'm going to close this issue as it's very similar to #111, which is older, and it hasn't had much engagement in over a year since it's been opened. Please follow that issue for any announcements related to listener data of a track.
