### ISSUE TITLE
Searching Album by UPC

### ISSUE THREAD

**Issue by d-a-v-e** [spotify/web-api#176]
I am unable to get a result set when searching for an album by UPC. The web api console has an example call for this which also returns an empty set (OAuth is used).

https://developer.spotify.com/web-api/console/get-search-item/?q=upc%3A5099908217059&type=album

**Comment by thelinmichael** [comment]
Appreciate the report @d-a-v-e. It was easy to recreate the issue, and it appears the example UPC was invalid. I've updated the documentation and the [link in the console](https://developer.spotify.com/web-api/console/get-search-item/?q=upc%3A00602537817016&type=album) to an album that's in Spotify's catalogue.

**Comment by d-a-v-e** [comment]
Current example on the site (and the one linked) still actually return an empty set. Are there any stats on how many albums have UPC stored against them?

**Comment by escamoteur** [comment]
still not fixed, I actually wonder if it can work like this at all as it's not a simple field but an external id object

**Comment by shillshocked** [comment]
Works now. Is it possible to search for albums that don't have a upc?
