### ISSUE TITLE
How can I play full tracks from my playlist from a website

### ISSUE THREAD

**Issue by ctutu** [spotify/web-api#177]
Hello,
I would like to be able with javascript play/stop to listen to full track from my playlist.
Is there a way ?
Regards

**Comment by thelinmichael** [comment]
Hey @ctutu! It's not possible unfortunately and has been added as a feature request in #57. It's an amazing feature but I want to use this opportunity to lower the expectations of this being rolled out in the near future. Hopefully using 30 second preview clips, which are available for most tracks, will satisfy your use case.
