### ISSUE TITLE
Add support for control via OS media playback events (i.e., KDE media controls)

### ISSUE THREAD

**Issue by GuiltyPixel** [spotify/web-api#178]
Currently media keys, and events triggered by KDE Connect, as well as the media player system tray application cannot interact with Spotify. This breaks my media control scheme in my home and makes Spotify an unlikely choice for my primary media player currently.

**Comment by JMPerez** [comment]
@GuiltyPixel Thanks for the report, but this doesn't seem to be related with Spotify's Web API in Any way. I believe the [Community Forum](https://community.spotify.com/) is the best place to report this and get help from other users and developers of the desktop client.

I'm closing this issue.
