### ISSUE TITLE
All routes returning 502

### ISSUE THREAD

**Issue by GabeJacobs** [spotify/web-api#180]
All routes seem to be down

https://api.spotify.com/v1/tracks/3z3bcIS2CBJ5pqWQjKPiIo

**Comment by ahallora** [comment]
Yup, I get the same error when trying to connect to Spotify from my app. 

https://developer.spotify.com/web-api/user-guide/

> 502 Bad Gateway - The server was acting as a gateway or proxy and received an invalid response from the upstream server.

What's going on? Halp!

**Comment by JohnnyCrazy** [comment]
Seems like some requests return successfully though. (2/10 tries)

Any infos @thelinmichael  @jsimonsson ?

**Comment by GabeJacobs** [comment]
Yep every once in a while it is successful

**Comment by GabeJacobs** [comment]
Actually, looks like search is down within the Spotify app as well #theydefinitelyknow

**Comment by thelinmichael** [comment]
@GabeJacobs, @ahallora, @JohnnyCrazy, thanks a lot for reporting in so quickly. As you've noticed we've had a fairly major disruption in the service, but it should be resolved now. Let us know if you're still seeing issues by opening the ticket and posting what endpoints aren't working. Thanks again!
