### ISSUE TITLE
Consistant 500 server error with Oauth/passport

### ISSUE THREAD

**Issue by hannahtwiggsmith** [spotify/web-api#181]
Issue found 3/7/16

endpoints: https://accounts.spotify.com/en/authorize/accept, https://accounts.spotify.com/en/authorize/cancel

Steps to reproduce: First encountered when implementing oauth in my own app, now it is also found in the example app here: https://github.com/JMPerez/passport-spotify

Expected behavior: oauth success

Actual behavior: 500 internal server error

**Comment by jsimonsson** [comment]
Hi!

Can you supply me with the username you are trying to login with? 
**Note** Do NOT provide me with a password

**Comment by hannahtwiggsmith** [comment]
Hi, the username I used was mqlkome

**Comment by eshrubs** [comment]
Hey @hannahtwiggsmith, are you still experiencing this issue? Would it be possible to send the request HTTP headers and the response details?

Thanks!

**Comment by thelinmichael** [comment]
@hannahtwiggsmith, it's been a while. Please let us know if you're able to provide us with the information requested by @eshrubs. I'll close this issue until then.

**Comment by ThiagoMarra** [comment]
Hello, i have a similar issue, with this response:

<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 500 </title>
</head>
<body>
<h2>HTTP ERROR: 500</h2>
<p>Problem accessing /en/authorize/accept. Reason:
<pre>    Internal Server Error</pre></p>
<hr /><a href="http://eclipse.org/jetty">Powered by Jetty:// 9.3.5.v20151012</a><hr/>
</body>
</html>

 Can help me?

**Comment by juliancc** [comment]
having the same error
