### ISSUE TITLE
Web view renders User Last Name without un-escaping escaped characters.

### ISSUE THREAD

**Issue by oliverodaa** [spotify/web-api#183]
For example, `O'Donnell` renders on the website as `O@#039;Donnell`

<img width="999" alt="screen shot 2016-03-15 at 12 03 50 pm" src="https://cloud.githubusercontent.com/assets/5886107/13790631/a3b24802-eaa6-11e5-82bc-4c691434f338.png">

**Comment by thelinmichael** [comment]
@oliverodaa, this GitHub repository works as an issue tracker for Spotify's [Web API](https://developer.spotify.com/web-api) which is separate from the Spotify's website. Therefore I'll close this ticket, but will forward your information to the appropriate team. This is also a good opportunity to let you know that you can file general Spotify issues such as this one in Spotify's [Community forums](https://community.spotify.com). Thanks!
