### ISSUE TITLE
Web API Remove User’s Saved Tracks

### ISSUE THREAD

**Issue by eduardolima93** [spotify/web-api#184]
Hi,

The remove user's saved tracks call (https://developer.spotify.com/web-api/remove-tracks-user/) doesn't seem to be working, I receive the success response but the track isn't removed from my library.

**Comment by jsimonsson** [comment]
Hey

If you re looking in the Spotify client if it is gone or not then that may show wrong since it caches for a while. If you look now or use the Web API to see if the track is there and it is, then please provide what track you tried to remove and for what user :)

**Comment by eduardolima93** [comment]
Yeah I was checking with the client, it did remove it.

Thanks!
