### ISSUE TITLE
Spotify web player refuses to play selected song

### ISSUE THREAD

**Issue by wesselvanderlinden** [spotify/web-api#185]
Since a week or so I encountered an issue that when I select a song (by clicking the play button or double clicking on the song title) in the Spotify web player, then it refuses to play the song. The play button changes to the 'song playing' icon, but no music is being played.

I encountered this issue in Chrome and Firefox on 2 different pc's (Linux Mint and Ubuntu OS).

The javascipt console gives me the following error which maybe related:

> Uncaught TypeError: Cannot read property 'length' of undefined   spotify.sdk.5.9.1-dc2b83d.min.js

**Comment by thelinmichael** [comment]
Thanks for reporting this to us @wesselvanderlinden! I've forwarded this to the people working on the Spotify Play Button. Since this is a repository dedicated to Spotify's Web API I'm going to close this issue.
