### ISSUE TITLE
Artist "banner" endpoint?

### ISSUE THREAD

**Issue by indiecore-fm** [spotify/web-api#186]
Could we please add an endpoint to retrieve the artist's banner? Would make it easier for us to developer nicer looking artist pages for our sites!

**Comment by hughrawlinson** [comment]
Hey @indiecore-fm - due to licensing restrictions we're not able to provide that data. Sorry! You could perhaps use a [search engine](https://search.creativecommons.org/) to try to find an appropriately licensed image based on the artist name, but this isn't something we can provide.
