### ISSUE TITLE
Include 'Where People Listen' data for Artists (currently in Artist Page > About)

### ISSUE THREAD

**Issue by trevorpburke** [spotify/web-api#188]
I'd like to see access to the 'About' section of an artist for the API

**Comment by thelinmichael** [comment]
For future reference, this is to include the Where People Listen data in the Artist profile's About section described in [this article](http://www.tunecore.com/blog/2015/09/spotify-rolls-out-new-about-pages.html). The data includes the five cities where artist is the most popular.

**Comment by hardikr** [comment]
This would be awesome to have. I'd love to build a reverse lookup (most popular artists by city)

**Comment by funkeymikey** [comment]
This would be useful.  I wouldn't mind getting more than the top 5 as well.

**Comment by themartinsjoseph** [comment]
This would be awesome to have. It would be the first way to tie Spotify behavior to geography without relying on an additional API.

**Comment by br-smith** [comment]
This would be great. Location info would be super useful, even if it was just the top 5

**Comment by usrbowe** [comment]
Any update on this? 🙏

**Comment by juanfurattini** [comment]
I did that for a web site, is pretty simple

**Comment by santoshJAVA** [comment]
Any updates on this ?

**Comment by arirawr** [comment]
Hey all,

As per our [new developer support process](https://github.com/spotify/web-api#creating-an-issue), any feature requests that have no plans to be considered in the next 6 months will be closed as wontfix.

We do not have any plans to implement this in the next 6 months and thus will close as wontfix.

We encourage you and other members of the community to continue to share use cases and your support for this feature, as it helps us prioritize features going forward. You will be able to comment on this issue even after it is closed. We will also post any updates here relating to this suggestion when they happen.

**Comment by gavrieltal** [comment]
this data would have been useful for helping users make judgments about where to vacation or move on the basis of their musical interests.

**Comment by fmxy** [comment]
would love to see this and would be happy with bio, followers and where people listen. should be low effort compared to other requests as the information is already available in the desktop client.

**Comment by faustocarva** [comment]
I encourage spotify to do this functionality, it will be very useful.

**Comment by iksena** [comment]
I'd love to see a list of cities that would be my best crowd based on my favourite tracks

**Comment by kuranalove** [comment]
Would love to see this as well. Will be helpful for artists looking to find their best markets.
