### ISSUE TITLE
Add new tracks to the TOP of playlists, NOT bottom

### ISSUE THREAD

**Issue by AxoSal** [spotify/web-api#189]
[Link to the suggestion on the community forum](https://community.spotify.com/t5/Live-Ideas/Option-to-Add-Fresh-Tracks-to-the-Top-of-Playlists/idi-p/176876#comments). This feature request has been made 2012. Isn't it time to implement it?

**Comment by thelinmichael** [comment]
Hi @AxoSal! This Github repository works as an issue tracker for [Spotify's Web API](https://developer.spotify.com/web-api), and not any particular Spotify app. (The Web API actually supports adding tracks to any position in a playlist.)

**Comment by AxoSal** [comment]
I know. I just wanted someone from Spotify to pay attention to the feature request. Could you let the people responsible for changes in the Spotify app itself know about the feature request?
