### ISSUE TITLE
404 if field (track / artist etc.) has "/" in it's name

### ISSUE THREAD

**Issue by nachmore** [spotify/web-api#191]
I'm trying to grab data for "Numb/Encore" by "JAY Z" and the following return 404s:

https://api.spotify.com/v1/search?q=track:%22Numb%2FEncore%22+artist:%22JAY%20Z%22&type=track
https://api.spotify.com/v1/search?q=track:%22Numb/Encore%22+artist:%22JAY%20Z%22&type=track

Interestingly if I replace the '/' with a space (' ') I get the correct results.

Thanks!

**Comment by nachmore** [comment]
Looking through my logs I see more instances of this, for example searching for songs by AC/DC etc:

https://api.spotify.com/v1/search?q=track:%22Thunderstruck%22+artist:%22AC/DC%22&type=track
https://api.spotify.com/v1/search?q=track:"0 To 100 / The Catch Up"+artist:"Drake"&type=track
https://api.spotify.com/v1/search?q=track:"Prayers/Triangles"+artist:"Deftones"&type=track

(there are a bunch more...)

**Comment by thelinmichael** [comment]
Thanks @nachmore! Closing since it's the same issue as #187.
