### ISSUE TITLE
Apparently random failures when removing tracks from a playlist

### ISSUE THREAD

**Issue by relevitt** [spotify/web-api#192]
This request succeeded:
endpoint: DELETE https://api.spotify.com/v1/users/bigclot/playlists/4eWp8fPuzI9HoH7CMRjibZ/tracks
tracks: [{"uri":"spotify:track:4JLhdNpCpb1KA5SM76zGtz","positions":[161]}]

However, this request keeps failing:
endpoint: DELETE https://api.spotify.com/v1/users/bigclot/playlists/4eWp8fPuzI9HoH7CMRjibZ/tracks
tracks: [{"uri":"spotify:track:2iTz17Fo23cvEydIaQD7BR","positions":[161]}]

This request also keeps failing:
endpoint: DELETE https://api.spotify.com/v1/users/bigclot/playlists/4eWp8fPuzI9HoH7CMRjibZ/tracks
tracks: [{"uri":"spotify:track:0CnkmQrs39VVL0yXKz8dzT","positions":[160]}]

I've left these two tracks (where the deletion request keeps failing) in place in the playlist, so you can see if there is anything about them which is problematic.  I created the playlist for testing purposes, so you can test trying to delete the tracks through the web-api, if you can give yourself permission.

Other delete requests on this test playlist have succeeded (including requests deleting 50 tracks at once), so I don't think there is any problem with my headers or authorisation.

**Comment by jsimonsson** [comment]
When it fails do you get a 201/200 response-code back? Or is the track just not removed?

**Comment by relevitt** [comment]
Hi Johan, 
I get a 400 response for the failed deletions. 
As far as I can tell, there are specific spotify tracks that trigger the error. In addition to the two tracks I mentioned on the bug report, I've just found another track that won't get deleted:
endpoint: DELETE https://api.spotify.com/v1/users/bigclot/playlists/59KWhLQjo3oK41c8PQJYdF/tracks
"tracks":[{"uri":"spotify:track:15QIdOtJ9kdZQLRCKr7rQt","positions":[181]}]

Any attempt to delete that particular track fails, even though I've successfully deleted 100s of tracks from the same playlist.

I've been deleting tracks from the end of the playlist (not the beginning), so the issue seems to have nothing to do with repositioning of tracks as a result of earlier deletions. 
I wondered if there could be specific characters in the uri of the problematic tracks, but I can't see anything.
Regards,Richard

**Comment by jsimonsson** [comment]
Hello again

Had a look at this. My initial thought is on how you get those track IDs.
This is what I think may be happening:
You get the playlist with a market parameter, this will trigger relinking behaviour.
You can read about it here: [Track Relinking Guide](https://developer.spotify.com/web-api/track-relinking-guide/)

In short, you are operating on a relinked track ID when you should use the relinked_from items track ID.

**Comment by relevitt** [comment]
That was the problem. Thanks v much for your help.
Richard
