### ISSUE TITLE
Reordering tracks in a playlist doesn't work as expected if the latest snapshot_id is provided

### ISSUE THREAD

**Issue by relevitt** [spotify/web-api#193]
endpoint: PUT https://api.spotify.com/v1/users/{user_id}/playlists/{playlist_id}/tracks

I've been performing multiple reordering requests, each subsequent request using the snapshot_id returned by the previous successful reordering request. 

However, whenever I provide the snapshot_id in this way, the wrong item gets moved in each subsequent request. In other words, the item that gets moved in each subsequent request is from the first snapshot, and not from the latest snapshot, even though the latest snapshot_id (as returned by the previous reordering request) was provided. 

However, if no snapshot_id is provided, everything seems to work correctly. In other words, a subsequent reordering request will reflect the changed order resulting from previous requests only if no snapshot_id is provided.

**Comment by jsimonsson** [comment]
Hey, will def take a look, will label it as a bug for now.

**Comment by arirawr** [comment]
Hey there, we haven't been able to replicate this and we haven't had any other reports. I'm going to close this as inactive, but feel free to reopen with reproduction steps if you continue seeing the error.
