### ISSUE TITLE
Implement other Echo Nest API endpoints

### ISSUE THREAD

**Issue by mcrawford-dayspring** [spotify/web-api#196]
With yesterday's announcement of the ending of the Echo Nest API, we'll have to rely on Spotify's web API to provide the information. But Spotify's web API is missing many of the features of the Echo Nest API.

I'm not sure exactly how to create this issue -- the one feature in particular that I use is the call to get Artist "terms." I haven't looked at all the other Echo Nest API calls to see if they can be replicated by the Spotify API, but that "terms" one cannot be.

Are there plans to re-create these missing features in the Spotify web API?

**Comment by bih** [comment]
Hello @mcrawford-dayspring and @holmberd,

As per our [new developer support process](https://github.com/spotify/web-api), any feature requests that have no plans to be considered in the next 6 months will be closed as <kbd>wontfix</kbd>.

In this particular case, we have introduced some parts of the Echo Nest API such as [Audio Analysis](https://developer.spotify.com/documentation/web-api/reference/tracks/get-audio-analysis) and [Audio Features](https://developer.spotify.com/documentation/web-api/reference/tracks/get-several-audio-features/). Implementing other Echo Nest API endpoints isn't something that we are planning on considering in the next 6 months, and so for clarity we will mark this as <kbd>wontfix</kbd>.

We encourage you and other members of the community to continue to share use cases and your support for this feature, as it helps us prioritize features going forward. You should be able to comment on this issue even after it is closed. We will also post updates here relating to this suggestion as and when they happen.

Let us know if you have any questions about this 👍
