### ISSUE TITLE
Get Recommendations - Wrong type in the docs

### ISSUE THREAD

**Issue by JohnnyCrazy** [spotify/web-api#197]
In the [Get Recommendations](https://developer.spotify.com/web-api/get-recommendations/) docs, the tunable attribute `duration_ms` is marked as `float`, although only `int`-values are valid.

You can't enter a `float`-value in the Web-API Console at least, so I guess it should be a `int`.

**Comment by JMPerez** [comment]
@JohnnyCrazy Thanks for letting us know! We have just changed the type in the docs, since the supported value in the API is of type `int`, as in the console.
