### ISSUE TITLE
Invalid analysis_urls returned by API

### ISSUE THREAD

**Issue by mcrawford-dayspring** [spotify/web-api#198]
When getting the audio features for a track, it often seems to return an invalid analysis URL.
 
Issue found on March 31st, 2016

Endpoint: /audio-features
Scope: no specific scope needed, but am authenticated

Steps to reproduce: 

1. Use the API console to get the audio features: https://developer.spotify.com/web-api/console/get-audio-features-track/?id=06AKEBrKUckW0KREUWRnvT#complete
2. Use the returned `analysis_url` to request the analysis

Expected behavior: The analysis_url would return the Echo Nest audio analysis

Actual behavior: It returns an error message:

`<Error>
    <Code>NoSuchKey</Code>
    <Message>The specified key does not exist.</Message>...`

**Comment by jsimonsson** [comment]
Hi

I'm unable to reproduce this using the above link.

It exists an expiry time on those URLs fyi, incase you are trying to look them up later.

**Comment by mcrawford-dayspring** [comment]
It seems like *that particular* one now works. Can you try with some others? My guess is that the analysis_url is not yet ready for new releases.

Here are the first tracks from the 3 new releases for today. They all return the NoSuchKey error when I request the analysis_url.
https://api.spotify.com/v1/audio-features/4uXDWsoGZXd39QP47NkGm5
https://api.spotify.com/v1/audio-features/6YplmxTwJ2XgkOw59xAYJO
https://api.spotify.com/v1/audio-features/6Yzh272O4hwZHjrnXYhL8a

If those work for you by the time you try them out, then try some other tracks from new releases.




My guess is
