### ISSUE TITLE
Get Recommendations - Return uniform error-object?

### ISSUE THREAD

**Issue by JohnnyCrazy** [spotify/web-api#199]
Another thing I would like to address:

Currently, the [Get Recommendations](https://developer.spotify.com/web-api/get-recommendations/)-Endpoint returns a very specific error-response (e.g by setting no track/genre/artist seed):

````json
{
  "status" : 400,
  "message" : "invalid request"
}
````

Would it be possible to change that to behave like all other endpoints? It's described [here](https://developer.spotify.com/web-api/user-guide/#error-details). It would be really odd to implement another rare error-model into wrappers.

What I would expect:
````json
{
  "error": {
  	"status" : 400,
  	"message" : "invalid request"
  }
}
````

**Comment by JohnnyCrazy** [comment]
It seems like the `GetUsersTop`-endpoint returns the same rare error-model.

**Comment by JohnnyCrazy** [comment]
Any ETA @thelinmichael ?

**Comment by joegester** [comment]
Hi Johnny,

We've deployed changes to both end points to make the error formatting consistent.  Thanks for catching this for us!

**Comment by JohnnyCrazy** [comment]
Thanks @joegester , can confirm it's working fine :)
