### ISSUE TITLE
A significant number of errors in ISRC data

### ISSUE THREAD

**Issue by MosNicholas** [spotify/web-api#2]
There are a significant number of incorrectly labelled ISRC data fields. See for instance the following Spotify track:

https://developer.spotify.com/web-api/console/get-track/?id=7FBUSWeAxm4zvHLBka9EzQ

Or compare these two tracks which are different, but have the same ISRC:

https://developer.spotify.com/web-api/console/get-several-tracks/?ids=6DQ9b9uEysKDdKs1qcLaB2,5a2O2iA2jtHlLtTgCs6zQH#complete

These errors seem to be pretty significant, although I don't know how to measure the breadth of the issue.

**Comment by possan** [comment]
Oh, that's interesting! i'll check with our content team

**Comment by MosNicholas** [comment]
Thank you you for replying quickly and your help! Please let me know what you resolve to do.

**Comment by possan** [comment]
It seems that this actually happens on occasion when multiple labels for some reason (by mistake or not) report the same values

Good catch, but it's not really a bug in that sense so i'll close this.

**Comment by MosNicholas** [comment]
So this is a problem from labels reporting data to you? There's nothing Spotify can do to remedy this?

**Comment by possan** [comment]
I'm sure we report that back to labels if this happens, but right now we're basically in the hands of them reporting correct values

**Comment by MosNicholas** [comment]
Ok, thank you for looking into this!
