### ISSUE TITLE
Retrieve Current User's play History

### ISSUE THREAD

**Issue by sean1rose** [spotify/web-api#20]
Provide information on a user's recently played tracks, or in the alternative - provide info on recent/current listeners of a song.

**Comment by thelinmichael** [comment]
Thanks for your feature request @sean1rose. There's an existing issue (#12) covering what track a user is currently listening to, so I think it'd be good to limit the scope of this issue to retrieving a user's recently played tracks.

**Comment by sean1rose** [comment]
Ok Michael - I'm excited to see the feature implemented

On Wed, Apr 1, 2015 at 12:46 AM, Michael Thelin <notifications@github.com>
wrote:

> Thanks for your feature request @sean1rose <https://github.com/sean1rose>.
> There's an existing issue (#12
> <https://github.com/spotify/web-api/issues/12>) covering what track a
> user is currently listening to, so I think it'd be good to limit the scope
> of this issue to retrieving a user's recently played tracks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spotify/web-api/issues/20#issuecomment-88382814>.
>



-- 
Sean Rose
714.469.1796
sean1rose@gmail.com

**Comment by omasseau** [comment]
Supporting this.
It would be nice to be able to get play history of current user or followed users (would be a workaround to the useless friend feed of the 1.0.1 version of the desktop app).

**Comment by DefV** [comment]
+1

**Comment by rjrahul** [comment]
+1

**Comment by ptlola** [comment]
+1

**Comment by ardixiv** [comment]
+1

**Comment by nporter19** [comment]
+1

**Comment by Foorack** [comment]
+1

**Comment by thelinmichael** [comment]
I'm merging the scope of #68 with this issue with the aim of facilitating a discussion around what entity types (e.g. tracks, albums, artists, playlists.) are the most important for you.

**Comment by dinoparavandis** [comment]
Great,

from a priority point of view imho its
- artists
- albums
- tracks
- playlists

thanks!

**Comment by sean1rose** [comment]
All of them! But if you do need an order:
1. Tracks
2. Artists
3. Playlists
4. Albums

**Comment by ardixiv** [comment]
1. track (artist + title)
2. album
2. playlist

**Comment by omasseau** [comment]
Same as the above:
1.Track (artist - title)
2.Album
3.Playlist

**Comment by marianolatorre** [comment]
+1

**Comment by jmilloy** [comment]
Also very interested in history or stats. I would like to be able to specify some sort of date range when request play counts.

Track stats is the most important/general, because we could figure out artist and album stats on our own if track stats were available.

**Comment by sregg** [comment]
+1

**Comment by johnthillaye** [comment]
+1

**Comment by mwpastore** [comment]
+1

**Comment by sreid8** [comment]
+1

**Comment by sevy11** [comment]
+1

**Comment by rakauchuk** [comment]
+1

**Comment by serafettin** [comment]
+1

**Comment by mmounirou** [comment]
+1

**Comment by 12preschph** [comment]
+1

**Comment by danyay** [comment]
+1

**Comment by ElderSignStudio** [comment]
+1

**Comment by naelmusleh** [comment]
+1

**Comment by mbavio** [comment]
+1

**Comment by Patrick-Fieger** [comment]
+1

**Comment by brycemcd** [comment]
+1

**Comment by Timmaeh** [comment]
+1

I want to display the artists I recently listened to on my website, like it's on my spotify profile.

**Comment by mjhasbach** [comment]
+1

**Comment by AndreasMaier** [comment]
+1

**Comment by syntiux** [comment]
+1

**Comment by brunoksato** [comment]
+1

**Comment by gxferreira** [comment]
+1

**Comment by gravitypersists** [comment]
rdio refugee here. I used my listening history to keep up with stuff I've been listening to recently. I feel a bit lost without it.

+1

**Comment by seanemmer** [comment]
+1

**Comment by parkan** [comment]
+1

**Comment by joselitojunior** [comment]
+1

**Comment by tomeriksen** [comment]
+1

**Comment by theguaz** [comment]
+1

**Comment by endowzoner** [comment]
+1

**Comment by pkiv** [comment]
+1

**Comment by adamsinger** [comment]
+1

**Comment by wohlfea** [comment]
+1

**Comment by yuhan210** [comment]
+1

**Comment by rene-springmann** [comment]
+1

**Comment by tomsheedy** [comment]
+1

Any news on this?

**Comment by kianlavi** [comment]
+1

**Comment by wcauchois** [comment]
+1

Would be very interested in this data.

**Comment by pika11** [comment]
+1

**Comment by ssx** [comment]
@thelinmichael has there been any movement on this? I run tweekly.fm, which collects play data and posts to social media, the number one thing I get asked for is the same for Spotify.

**Comment by llewy** [comment]
+1

**Comment by outspaced** [comment]
+1.  This is a really important feature.

**Comment by GLosch** [comment]
:+1: Tried to add a Discover Weekly song to a private playlist in December, but it errored, and I lost the song after my Discover Weekly updated the next day. Would love to have the ability to set a date range for viewing play history.

**Comment by Senpos** [comment]
+1

**Comment by HumanDisaster** [comment]
+1

**Comment by plailleur** [comment]
+1

**Comment by dzuendorf** [comment]
+1

**Comment by sleverbor** [comment]
+1

**Comment by joejknowles** [comment]
@thelinmichael is this ever going to happen?

**Comment by tom12e** [comment]
+1

**Comment by newsum** [comment]
+1

**Comment by hooverlunch** [comment]
+1

**Comment by franrios** [comment]
+1

**Comment by th1988** [comment]
+1

**Comment by blaster151** [comment]
+1

**Comment by BlakeGuilloud** [comment]
+1

**Comment by jas0njames** [comment]
+1

**Comment by California20025** [comment]
+ 1

**Comment by jakegibson** [comment]
+1

**Comment by rodreego** [comment]
I'm not sure if I just leave another +1 or ask "if somebody has any way around".

**Comment by rakauchuk** [comment]
@rodrigocnascimento I use for this an export tracks from Spotify to LastFM and then I'm checking it.

**Comment by rodrigocnascimento** [comment]
@rakauchuk yeah, I found out something like; thx =P

**Comment by tedmiston** [comment]
+1 for track and playlist listening history

**Comment by einfalles** [comment]
what's the status on this? +1!

**Comment by PENDOnl** [comment]
+1

**Comment by maggie-lagos** [comment]
+1

**Comment by xzys** [comment]
+1

**Comment by CNG** [comment]
Storing a track ID number plus timestamp for all tracks ever played can't be that difficult or resource intensive, can it?

**Comment by adam-arold** [comment]
+1
So what is the state of this?

**Comment by sergiotomasello** [comment]
any news?

**Comment by vjm** [comment]
+1

**Comment by glockenstein** [comment]
+1

**Comment by denisigo** [comment]
+1

**Comment by guney** [comment]
+1

**Comment by krizo** [comment]
+1

**Comment by bonsaicc** [comment]
+1

**Comment by iancampbell33** [comment]
+1

**Comment by tke578** [comment]
+1

**Comment by mjonik** [comment]
+1

**Comment by thelinmichael** [comment]
Conversation locked to avoid spamming everyone subscribing this issue with further "+1"s. To clarify, this doesn't mean that the feature request is closed.

**Comment by hughrawlinson** [comment]
*Very* happy to report that we've just launched an endpoint to address this issue! [Get Current Users Recently Played Tracks](https://developer.spotify.com/web-api/web-api-personalization-endpoints/get-recently-played/).

**Comment by ColmHally** [comment]
Great to hear it @hughrawlinson !
It looks like the link to the API docs is not up yet though!
https://developer.spotify.com/web-api/get-current-users-recently-played-tracks

**Comment by davidski** [comment]
Super glad to see this! Would a request to get the full play history warrant a separate issue? Trying to get my full played history without resorting to last.fm connectivity.

**Comment by steveculverwell** [comment]
Fifty? Not great.

**Comment by aidos** [comment]
This is great! But 50 isn't really many tracks. Are there plans to increase the limit at all?

**Comment by seahorsepip** [comment]
50 is kind of a low amount indeed, That's in most cases only one or two playlist when looking at the context :/

**Comment by Behoston** [comment]
+1

**Comment by netoolii** [comment]
i want my all history music

**Comment by airstrike** [comment]
+1 on the "all of my history" train. please let us resurrect [LastGraph](http://lastgraph3.aeracode.org/)

**Comment by AlexSilR** [comment]
All history +1!

**Comment by newpatriks** [comment]
+1 on "all my history". Or at least an increase to 1k or 2k possible results on the recently played end point. 50 It's less than the music someone might listen in one or two days.

**Comment by sr-ix** [comment]
give us the full history

**Comment by jscholes** [comment]
> (Though it looks like it's created by spotify) How come that has access to everything?

You've just answered your own question there.  The site uses a custom backend which returns the data that it needs, rather than accessing the Web API directly.  It has access to everything because that's the access Spotify have given it.

**Comment by seahorsepip** [comment]
@adios 
Spotify applications use closed source APIs them self that are not open to the public. Those APIs might even be RMI, SOAP, Socket etc instead of REST and not created for public use because of technical and legal privacy reasons.

**Comment by aidos** [comment]
Looking at the API docs there are now next / cursors returned — do they still not allow you to go beyond the 50 tracks?

```
"next": "https://api.spotify.com/v1/me/player/recently-played?before=1481661737016&limit=2",
  "cursors": {
    "after": "1481661844589",
    "before": "1481661737016"
  },
  "limit": 2,
```

**Comment by seahorsepip** [comment]
@adios
Last time I checked (~2months ago) those cursors where already there and didn't allow me to go beyond 50 tracks.

**Comment by aidos** [comment]
@seahorsepip Looking a bit closer, it still looks limited.

It's so depressing that there are tracks I want to rediscover from the past year (and I've even noted down the rough dates I listened to them), but I'll never find again without Spotify lifting this pointless restriction.

**Comment by jscholes** [comment]
> It's so depressing that there are tracks I want to rediscover from the past year (and I've even noted down the rough dates I listened to them), but I'll never find again without Spotify lifting this pointless restriction.

It doesn't help you rediscover those tracks from 2017 and earlier, but this is one of the usecases that Last.fm is perfect for.  I have detailed day-by-day listening history going back to 2008, across all applications which scrobble.  Maybe set that up going into 2018?

**Comment by ndelnano** [comment]
+1

**Comment by steveculverwell** [comment]
I can just keep scrolling and scrolling on my youtube history and I dont pay a premium for that.

**Comment by seahorsepip** [comment]
@steveculverwell
As end user you can also see more history then 50 tracks in the official apps, that doesn't mean that the developer API should offer the same data since the developer API is not just about your own account but also the accounts that use your app/service/etc and thus there are more privacy concerns to keep in mind.

**Comment by DalerAsrorov** [comment]
"all of my history" please

**Comment by heharkon** [comment]
Per EU GDPR, as a data subject I want to have access to my complete play history.

And while we are at it, the API should also include the possibility to clear the history (consumer right for data erasure), thus it is necessary to be able to retrieve complete history also for verification purposes.

**Comment by seahorsepip** [comment]
@heharkon 
Might sound like a good argument but this is **not** the correct place to make the argument.
The Web API gives access as developer to not just your account information but also **everyone's account who's using your application**. 

So giving developers so much access to this privacy sensitive information which might be years of listening information with time stamps and everything would be actually a problem in the eye of EU privacy laws and the exact thing that it the law should be protecting users from.

If you want full access to **your own history** in some exportable format (like Google search offers) then you should contact Spotify customers relations directly instead of it's developers and request them to add it to the user portal.

Increasing the limit a bit makes sense since 50 is just too low but full history access for 3rd party apps is just a big privacy issue for end users and might not even be feasible considering the different privacy regulations in countries the Spotify service is offered

**Comment by heharkon** [comment]
@seahorsepip 
So basically you are saying that if the app developer would maliciously misuse the access token while the user has it active? But then I'd be more concerned about the much more immediate privacy related information that the third party could attain. Like email address, birth date, connections etc.

Of course it's all about trust between the client and the third party, and I think the Spotify authorization page doesn't do that good of a job informing the client about which scopes the app is applying the grant for.

**Comment by Osherz5** [comment]
+1 To all of my history

**Comment by jayachithra** [comment]
+1 for all history !

**Comment by grillinmuffins** [comment]
If you can't give us all playback history, can't we get some analytics? 

- Total Number of tracks listened to all time
- Total Number of Tracks Listened for given date range
- Number of tracks per category for given date range
- Number of tracks listened by artist for given range
etc. etc. etc.

Seems pretty ridiculous to not even have access to this high level information.

**Comment by NijsTom** [comment]
+1 for all history

**Comment by dandv** [comment]
The [GDPR issue](https://github.com/spotify/web-api/issues/20#issuecomment-370687041) is quite serious. What needs to happen for Spotify to offer complete access to a user's play history? Hopefully not a lawsuit.

**Comment by seahorsepip** [comment]
> The [GDPR issue](https://github.com/spotify/web-api/issues/20#issuecomment-370687041) is quite serious. What needs to happen for Spotify to offer complete access to a user's play history? Hopefully not a lawsuit.

The Web API is primarily meant to be used to fetch data from other users.
Giving full access to the all data and history of Spotify users to 3rd party developers is not what the GDPR stands for. 

As for the actual GDPR compliance in my experience:

- Users can already access all their own data from the official Spotify apps which include a very long history list in recently played. Full history is indeed not available as far I've seen and a topic of discussion but **has nothing to do with a 3rd party developer api.**

- As for deleting history, this is already possible by simply deleting your Spotify account.

I can understand 3rd party developers want more endpoints and more data but commething on every issue with +1 or even mentioning unrelated laws does not really help. 

GDPR gives users the rights to control all their **own data**, it does **not** give 3rd party developers the right to control all the **data of their users**.

GDPR discussions should be held at the Spotify community forums or with Spotify Support, not on Github issues of an unrelated Web API for 3rd party developers.

Ideally there should be a history management page on the Spotify website to manage your own history similiar to what Facebook and Google offer in compliance with GDPR. But this is unrelated to this web API.

Feel free to correct me if I'm wrong, I'm just tired of getting unrelated email notifications while following this issue and wanted to clear up some confusion.

**Comment by seahorsepip** [comment]
Update:

After some looking around I found that Spotify already offers a data export option at [https://www.spotify.com/account/privacy/](https://www.spotify.com/account/privacy/) in comliance with GDPR.

So that means that Spotify is already GDPR compliant.

**Comment by pelmered** [comment]
@seahorsepip I've tried that, but you don't get the data in a good format that allows you gather your own analytics from that, at least not in an easy way.

**Comment by seahorsepip** [comment]
@pelmered 
I haven't made an export yet using the tool, I'll make an export and (hopefully) receive the data soon so I can look into it, maybe I'll write a script that transforms the data into an easier format similar to the format returned by the endpoint related to this issue.

**Comment by brichardCVS** [comment]
> @pelmered
> I haven't made an export yet using the tool, I'll make an export and (hopefully) receive the data soon so I can look into it, maybe I'll write a script that transforms the data into an easier format similar to the format returned by the endpoint related to this issue.

Would love to hear if there was anything useful in this file. I just requested my own and am considering building a tool as well.

The API is useless for history :(
