### ISSUE TITLE
New user's top artists / tracks endpoint issue ?

### ISSUE THREAD

**Issue by mickaeloak** [spotify/web-api#200]
Hi,

I noticed by testing the new endpoint for getting the user's top artists or tracks that you can only get the top 50 of these. Even though I have over 100 artists on my account, setting an offset of 10 would get me 40 artists (10 to 50 from the top) and I noticed the 'next' value is always null. When I compare to the endpoint to get the user's followed artists, this one gives us a 'next' url to get the rest of the artists, which would make sense in the top artists endpoint too. Is this an issue or you wanted to give a top 50 artists / track only ?

Top artists / tracks endpoint testing URL : https://developer.spotify.com/web-api/console/get-current-user-top-artists-and-tracks/?type=artists

User's followed artists endpoint testing URL : https://developer.spotify.com/web-api/console/get-following/

**Comment by joegester** [comment]
Hi mickaeloak,

Currently data pipeline limitations mean we only have 50 tracks and 50 artists for each user.  We expect to scale that up in the future.  I'll add a note in the API docs explaining this.  

Thanks for pointing this out.

**Comment by mickaeloak** [comment]
Hi Joe,

Thanks for your answer.
Alright, yes it would be great for some cases. 
We wanted to use this for a music recommender but not getting all the user's artists would not really work for this case.

**Comment by jsimonsson** [comment]
Closing this as an answer has been given.
