### ISSUE TITLE
Pagination results (value for total) on artist search a little peculiar

### ISSUE THREAD

**Issue by dnblankedelman** [spotify/web-api#201]
Let me demonstrate using curl:

First, with an offset of 0:
```$ curl -s -X GET "https://api.spotify.com/v1/search?q=chloe&type=artist&limit=10&offset=0" -H "Accept: application/json"|jq '.artists|[.total]'```

    [
      341
    ]

Then with an offset of 10:
```$ curl -s -X GET "https://api.spotify.com/v1/search?q=chloe&type=artist&limit=10&offset=10" -H "Accept: application/json"|jq '.artists|[.total]'```

    [
      328
    ]

Now let's try 20:
```$ curl -s -X GET "https://api.spotify.com/v1/search?q=chloe&type=artist&limit=10&offset=20" -H "Accept: application/json"|jq '.artists|[.total]'```

    [
      331
    ]

And just for fun, an offset of 330:
```$ curl -s -X GET "https://api.spotify.com/v1/search?q=chloe&type=artist&limit=10&offset=330" -H "Accept: application/json"|jq '.artists|[.total]'````

    [
      331
    ]

So I'm having a hard time understanding the behavior. Is this a bug, or do I not quite get how this value is supposed to work? Thanks!

**Comment by cosinekitty** [comment]
I'm glad someone already reported this.  I found the same issue with searching for Tracks.  Here is an example:

`https://api.spotify.com/v1/search?query=Yael+Naim&offset=0&limit=10&type=track&market=US&locale=en-US`
This yields Tracks.Total = 78.

`https://api.spotify.com/v1/search?query=Yael+Naim&offset=10&limit=10&type=track&market=US&locale=en-US`
Now Tracks.Total = 71.

`https://api.spotify.com/v1/search?query=Yael+Naim&offset=20&limit=10&type=track&market=US&locale=en-US`
Tracks.Total = 74.

`https://api.spotify.com/v1/search?query=Yael+Naim&offset=30&limit=10&type=track&market=US&locale=en-US`
Tracks.Total = 73.

The following three pages of 10 tracks each yield the same value, Tracks.Total = 74.
What's really bad is that the last page (offset=70), says Tracks.Total=0 and **does not return any tracks** (it should have provided the last 4 tracks).

**Comment by restfulmt** [comment]
Hi,

I found the same problem searching for albums. It can be reproduced as follows:

1. Make the following request:
    https://api.spotify.com/v1/search?query=redhouse&offset=0&limit=20&type=album

    The response returns albums.total=27 and 20 items.

2. Make another request using the albums.next URI:
     https://api.spotify.com/v1/search?query=redhouse&offset=20&limit=20&type=album

     The response returns albums.total=21 and 1 item. (6 missing items!)

3.  Make the same request with offset=0 and limit=30
     https://api.spotify.com/v1/search?query=redhouse&offset=0&limit=30&type=album

     The response returns albums.total=27 and 27 items, which is correct.

**Comment by restfulmt** [comment]
Hi again,

This seems a serious bug. Suppose the following request:

https://api.spotify.com/v1/search?query=redhouse&offset=0&limit=50&type=album

Iterating over results using limit=50 I get albums.total=140 and 90 actual items.

Iterating over results with limit=20 in the first call and then 50 in the successive requests I get albums.total=156 and 76 actual items.

Is there any reliable way to iterate over the search results?

**Comment by asmitter** [comment]
Thanks for the detailed reports. We've now rolled out a fix so the count and paging should be stable.
Let us know if you see any other unusual behaviour.
