### ISSUE TITLE
Dynamic Playlists

### ISSUE THREAD

**Issue by alexhulbert** [spotify/web-api#202]
Hi! I was wondering if, since you'll be moving TheEchonest over to Spotify, whether or not the the steering functionality (including like, dislike, etc.) is going to be moved over to the Spotify API at some point. Myself, along with a large number of other developers, used these in applications, and I'd love to see them added to the new and improved Spotify API.

If they are going to be implemented, do you have even a rough roadmap of the features or at least a preliminary list of things you'd like to add?

Sorry for the inconvenience and thanks.

**Comment by thelinmichael** [comment]
Thanks for opening this issue @Taconut - dynamic playlists are awesome. I'm treating this issue as a feature request for adding dynamic playlists to Spotify's Web API. (Not as adding like/dislike functionality to endpoints where it might make sense.)

**Comment by bih** [comment]
Hello @alexhulbert,

We're in the process of revisiting all our Web API issues, and as this particular request has no plans to be prioritised in the next 6 months (as per our [updated support process](https://github.com/spotify/web-api)), I'll close this issue.

Of course, should there be updates related to this feature, we'll post them here! Cheers 👍
