### ISSUE TITLE
Recommendations API

### ISSUE THREAD

**Issue by woniesong92** [spotify/web-api#203]
I saw that Spotify just released recommendations endpoint!
Please tell me if it will be useful in the following situation.
Suppose that I have a query that looks like `John Lennon Imagine`.
How do I generate a seed with the above query so I can find similar songs?

**Comment by JMPerez** [comment]
@woniesong92 In your case you will want to send a track id to the recommendations endpoint. You first need to find the id for `Imagine`, for which you can use the [search endpoint](https://developer.spotify.com/web-api/console/get-search-item/?q=John+Lennon+Imagine&type=track).

Suppose we use the track id `7pKfPomDEeI4TPT6EOYjn9` that corresponds to `Imagine - 2010 - Remaster`. Now you can pass it to the [recommendations endpoint](https://developer.spotify.com/web-api/console/get-recommendations/?limit=10&seed_tracks=7pKfPomDEeI4TPT6EOYjn9) as a seed.
