### ISSUE TITLE
500 Error Attempting To Authenticate User

### ISSUE THREAD

**Issue by tastepwalle** [spotify/web-api#204]
Using Python Spotipy API..according to this set of instructions here: http://spotipy.readthedocs.org/en/latest/#authorized-requests

I am able to get the library to redirect me to Spotify's web portal (it tries links like this):

https://accounts.spotify.com/authorize?redirect_uri=<redirect_url>&response_type=code&client_id=<client_id>

Credentials are correct.

I am getting a 500 Internal Server Error response from that above url. Message is like:

Oops! Something went wrong, please try again or check out our help area.

I am trying this from South Korea which I am aware does not have Spotify service yet. However I am unable to do this via VPN or otherwise. Please advise.

**Comment by thelinmichael** [comment]
Thanks for reporting @tastepwalle! First off, the fact that you're in South Korea and/or on VPN shouldn't matter. This isn't an issue I'm aware of, and we should never be returning server errors. Does the URL return 500 constantly, or only the first time? Could you also please paste the entire URL except the code?

**Comment by tastepwalle** [comment]
Hey thanks for the reply, Michael.

I get the error every time. It has never worked for me. I have tried
specifying a redirect url as well and still nothing.

Url is as i pasted before:

https://accounts.spotify.com/authorize?redirect_uri=<redirect uri or
empty>&response_type=code&client_id=<client id>

Where <var> is placeholder

**Comment by thelinmichael** [comment]
@tastepwalle, could you please paste the URL including the `redirect_uri` and `client_id` values as well?

**Comment by tastepwalle** [comment]
Sure.

https://accounts.spotify.com/authorize?redirect_uri=www.mymusictaste.com&response_type=code&client_id=6ae65c930ea741fa9b8996c55e2af73e

On Mon, Apr 11, 2016 at 3:44 AM, Michael Thelin <notifications@github.com>
wrote:

> @tastepwalle <https://github.com/tastepwalle>, could you please paste the
> URL including the redirect_uri and client_id values as well?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/spotify/web-api/issues/204#issuecomment-208042374>
>



-- 

*Paul Elliott | 엘리엇폴*
Developer / Platform Dev. team
paul@mymusictaste.com
+82-10-2990-8642

**Comment by thelinmichael** [comment]
Thanks, confirmed that it consistently returns 500. We'll take a look!

**Comment by spkrka** [comment]
The bug has been fixed so now you will get a friendly error message instead - the `redirect_uri` needs to begin with a schema (I guess in your case that would be `https://`).

**Comment by tastepwalle** [comment]
Great thanks!
