### ISSUE TITLE
Search API 'market' parameter does not work with newly launched market Indonesia

### ISSUE THREAD

**Issue by kalleprymne** [spotify/web-api#205]
Search API 'market' parameter does not work with newly launched market Indonesia.

Issue found on April 5th 2016.

When addressing the Search API Endpoint with the newly launched 'market' Indonesia, the API responds with 404/Not found. Example:

https://api.spotify.com/v1/search?q=euphoria&type=track&market=ID

...results in:

````
{
  "error": {
    "status": 404,
    "message": "Not found."
  }
}
````

Since 'ID' now is supported, a full reply as for e.g. 'SE' would be expected:

````
{
  "tracks" : {
    "href" : "https://api.spotify.com/v1/search?query=euphoria&offset=0&limit=20&type=track&market=SE",
    "items" : [ {
      "album" : {
        "album_type" : "compilation",
        "available_markets" : [ "AR", "AU", "AT", "BE", "BO", "BR", "BG", "CA", "CL", "CO", "CR", "CY", "CZ", "DK", "DO", "DE", "EC", "EE", "SV", "FI", "FR", "GR", "GT", "HN", "HK", "HU", "IS", "IE", "IT", "LV", "LT", "LU", "MY", "MT", "MX", "NL", "NZ", "NI", "NO", "PA", "PY", "PE", "PH", "PL", "PT", "SG", "SK", "ES", "SE", "CH", "TW", "TR", "UY", "US", "GB", "AD", "LI", "MC", "ID" ],
        ...
````

(Also note, that for not supported countries we get a 400/Bad request with payload indicating "Unlaunched market".)

Best regards,

**Comment by thelinmichael** [comment]
Thanks @kalleprymne, we're on it.

**Comment by thelinmichael** [comment]
@kalleprymne, this has now been fixed. Thanks again for reporting.

**Comment by kalleprymne** [comment]
Thank you, @thelinmichael, for your fast action on this. Impressing! It works fine now. :-)
