### ISSUE TITLE
UPC issues

### ISSUE THREAD

**Issue by mradzinski** [spotify/web-api#208]
Hi guys, no matter how hard I try searching for UPC codes I cannot seem to succeed. For example, 685738598625 should match "Enya - A Day Without Rain" CD. If you Google that code you'll find plenty of search results (It's even registered under upcindex.com), however, if I search that UPC using the Spotify Web API I get 0 results. I thought UPC was an universal code, right? My main questions is: From where is Spotify obtaining their UPC codes?

Thanks!

**Comment by thelinmichael** [comment]
Hi @mradzinski! Looks like this particular album has been released twice (2000 and 2005) and that Spotify's catalogue only include one of them - the [one with UPC 825646292660](https://api.spotify.com/v1/albums/2ioso1tqQ5zABQDVYyiUi5). [All metadata for tracks, albums and artists are given by the record labels](https://www.spotify.com/us/about-us/labels/), and I believe this is true for the UPC as well.

**Comment by mradzinski** [comment]
Hi @thelinmichael! Well, it's not the only scenario where that happens to happen. Another two examples: 731454031424 should match Fields of Gold-Best of by Sting, 075992733625 should match James Taylor - Greatest hits. I'm pretty sure at least the Sting one has been only released by A&M Records only once...

**Comment by thelinmichael** [comment]
Looks like the same issue here @mradzinski - Fields of Gold was released 1994 by UMG Recordings as [UPC 00731454028622](https://api.spotify.com/v1/albums/1rZTn68Lgr5J4F4vIpgpWf), and James Taylor's Greatest hits was also released as [UPC 075992733663](https://api.spotify.com/v1/albums/2L4U4JjEADYaVltkvDrkCC).

**Comment by mradzinski** [comment]
@thelinmichael Simply unbelievable! hahaha. I have my Sting copy over here with me and it says 1994 A&M not UMG :smile:. Let me close this, there are so many disk releases available that matching UPC's looks like quite impossible. Let me know If at some point you guys happen to include all available UPC's (joking, I know that will never happen xD). Cheers mate!

**Comment by thelinmichael** [comment]
@mradzinski, that's what our metadata says, which of course is invalid in some cases. If you don't get a match on UPC, consider falling back to searching for the name of the album instead so that you'll find alternative releases.

**Comment by mradzinski** [comment]
@thelinmichael, Yeah, thing is that by the point I hit the search endpoint I truly don't have the names of the artist nor the album (app requirements, d'oh!), so I guess I will have to have some other API which provides me artist and album based on UPC and then hit the Spotify search endpoint using that metadata.
