### ISSUE TITLE
Extracting audio features from a custom track 

### ISSUE THREAD

**Issue by ludwikbukowski** [spotify/web-api#209]
Due to The Echo Nest's `Important API Announcement, March 29th 2016`[1] their platform will no longer serve requests and developers will have to move over to the Spotify API. However, The Echo Nest has been providing a quite important feature which was the extraction **audio features from a custom uploaded track.**
Will it be also posible to obtain those features (like danceability, energy etc) from audio file after the migration?

[1] http://developer.echonest.com/

**Comment by thelinmichael** [comment]
Hey @ludwikbukowski! You can retrieve `danceability`, `energy`, and other attributes using the [Get Audio Features for Track](https://developer.spotify.com/web-api/get-audio-features/) endpoint. This endpoint as well as two others were released as part of The Echo Nest's [API announcement](https://developer.spotify.com/news-stories/2016/03/29/api-improvements-update/).

**Comment by ludwikbukowski** [comment]
Thank you @thelinmichael but the point is that the audio features for a track can only be obtained by its Spotify ID. I would like to upload an audio file from my PC and get its audio features as a response. The Echo Nest API allowed that - http://developer.echonest.com/docs/v4/track.html#upload Will this functionality also be a part of the Spotify API?

**Comment by pskiden** [comment]
Hi @ludwikbukowski,
Unfortunately, uploading songs for analysis through the API will not be supported going forward. All music content that gets released on Spotify will have it’s audio analysis available through the API though.

**Comment by ludwikbukowski** [comment]
@pskiden Thanks!

**Comment by mrbfrank** [comment]
@pskiden This is sad news, the [EchoNext Remix](https://echonest.github.io/remix/) project is so cool & relies on this custom track upload/analysis feature. Please, is there anything you guys can do to support it? If you can't serve upload analysis requests, Is it possible to release some code to provide offline analysis and keep that project alive? So many [interesting things](https://echonest.github.io/remix/examples.html) have been made with it, would be a dark day in the history of API acquisitions to see that project die.

**Comment by polyrhythmatic** [comment]
I'd like to second this feature continue to be supported. @pskiden if this is not supported can you recommend alternatives?

**Comment by taambr** [comment]
I want to write and say that I love the remix.js api as well and am having trouble accessing the same information that I did with the echonest api. Is the pitch information from segments still available through the Spotify Web api?

**Comment by hughrawlinson** [comment]
Hey @ludwikbukowski,

We have no plans to implement custom uploaded track feature extraction, sorry! There are some alternatives though, I'd encourage you to look at [Amen](https://github.com/algorithmic-music-exploration/amen) a tool for algorithmic remixing which has some contributions from Spotifiers. There are also a variety of lower level feature extractors available, such as [librosa](https://github.com/librosa/librosa), [essentia](http://essentia.upf.edu/) and [meyda](https://github.com/hughrawlinson/meyda) which cover python, c, and javascript.

We have an API endpoint for [audio features](https://developer.spotify.com/web-api/get-audio-features/), as well as [deeply detailed analysis](https://developer.spotify.com/web-api/get-audio-analysis/) of tracks that are already on Spotify, maybe that could help?

**Comment by jpdohner** [comment]
All Audio Features can be calculated without uploading to Spotify using a program called [Traktomizer](https://traktomizer.com).
