### ISSUE TITLE
Retrieve Current User's Notifications

### ISSUE THREAD

**Issue by omasseau** [spotify/web-api#21]
It would be great to add a new endpoint to be able to get the notifications for the user.

**Comment by vjandrea** [comment]
+1, i would like to create a little service that adds to a playlist every suggestion i get through notifications.

**Comment by thelinmichael** [comment]
Treating this issue ticket as a feature request for retrieving _notifications when an entity that the user is following is updated_, e.g. a track is added to a playlist, or an artist releases a new album.

**Comment by asmitter** [comment]
(Cleaning up old issues)
Notifications no longer exist in the client as they did when this was opened. Closing.
