### ISSUE TITLE
Migration of Artist coordinates from EchoNest

### ISSUE THREAD

**Issue by matthieugrieger** [spotify/web-api#210]
Hi there,

Today I learned of the news that Echo Nest is being deprecated in favor for a unified Spotify Web API. Are there any plans for migrating the data related to Artist locations (latitude, longitude) to the Spotify Web API? It doesn't seem that it is supported right now.

As a reference, this data can be used in the Echo Nest API to search for songs in a particular region: http://developer.echonest.com/docs/v4/song.html#search

I have been working on an application for a school project that makes use of this coordinate data, so a "yes/no" answer on the availability of this data would be much appreciated. :)

Thanks!

**Comment by pskiden** [comment]
Hi!
Adding artist location to the API is something we want to do in the future. It’s in the roadmap but there is no timeline for it yet.

**Comment by matthieugrieger** [comment]
Alright, thanks for the quick response!

**Comment by jch254** [comment]
Definitely keen for this!

**Comment by dannymy** [comment]
Any news on this one? I guess it's a rather desirable feature, as it also gets mentioned on the [docs page](https://developer.spotify.com/web-api/get-artist/). 
It's been a while and one of my old projects is still not functioning as it relied on the EchoNest API. Alternative music metadata providers can not provide adequate coverage of the geo data. So, may we expect something?

**Comment by robostheimer** [comment]
Totally agree.  I have an app (musicwhereyour) that has a broken experience now that the location data is not surfaced.  Any chance that it will be added in 2018?

**Comment by Benjaki2** [comment]
👍

**Comment by ATChustz** [comment]
Also would love to see the location data come back to the Spotify API. Any updates on timeline would be much appreciated, thanks!

**Comment by sdl60660** [comment]
This would be really helpful for an app I'm working on too. Any update would be appreciated!

**Comment by arirawr** [comment]
Hey all,

As per our [new developer support process](https://github.com/spotify/web-api#creating-an-issue), any feature requests that have no plans to be considered in the next 6 months will be closed as wontfix.

We do not have any plans to implement artist coordinates in the next 6 months and thus will close as wontfix.

We encourage you and other members of the community to continue to share use cases and your support for this feature, as it helps us prioritize features going forward. You will be able to comment on this issue even after it is closed. We will also post any updates here relating to this suggestion when they happen.

**Comment by joeprabawa** [comment]
Hello all, currently i'm working with the spotify API, and really need the artist origin data. are there any alternatives to get the data ? Thanks 🙏🏼

**Comment by huulbaek** [comment]
I too would like to see this feature implemented. I am trying to estimate if a festival concert will be crowded or not (should we get there early?) and right now I use the popularity score and number of follows. But if an artist is locally based these metrics fail.

**Comment by joshbDev** [comment]
I'd also love to see this feature. I was thinking about making a roadtripping app that would add artists along the route that you're driving, this information would be amazing for that.

**Comment by ardaorkin** [comment]
Hi! It'd have been very useful to see this feature for my project as well.
