### ISSUE TITLE
get-current-user-playlists does not return images any more

### ISSUE THREAD

**Issue by ahallora** [spotify/web-api#211]
The endpoint **get-current-user-playlists** currently returns empty images objects for each playlist. Verified today in the [Spotify Web Console](https://developer.spotify.com/web-api/console/get-current-user-playlists/). Images object is expected to hold the image url (and optionally height and width) as usual. Was working about a week ago or so. :smile: 

Changing the OAuth scope has no effect.

Extract of my response data below:

```json
{
  "href" : "https://api.spotify.com/v1/users/**************/playlists?offset=0&limit=20",
  "items" : [ {
    "collaborative" : false,
    "external_urls" : {
      "spotify" : "http://open.spotify.com/user/spotifydiscover/playlist/4UiL6MirIHuwH0A1tCen8A"
    },
    "href" : "https://api.spotify.com/v1/users/spotifydiscover/playlists/4UiL6MirIHuwH0A1tCen8A",
    "id" : "4UiL6MirIHuwH0A1tCen8A",
    "images" : [ ],
    "name" : "Discover Weekly",
    "owner" : {
      "external_urls" : {
        "spotify" : "http://open.spotify.com/user/spotifydiscover"
      },
      "href" : "https://api.spotify.com/v1/users/spotifydiscover",
      "id" : "spotifydiscover",
      "type" : "user",
      "uri" : "spotify:user:spotifydiscover"
    },
    "public" : false,
    "snapshot_id" : "87WpOU/VEOL/WtWQLUX+N1nUU55XoD7vtzx4tQCRqyw/yj0d2A1dTNhRWZq+ssbZ",
    "tracks" : {
      "href" : "https://api.spotify.com/v1/users/spotifydiscover/playlists/4UiL6MirIHuwH0A1tCen8A/tracks",
      "total" : 30
    },
    "type" : "playlist",
    "uri" : "spotify:user:spotifydiscover:playlist:4UiL6MirIHuwH0A1tCen8A"
  } ],
  "limit" : 20,
  "next" : null,
  "offset" : 0,
  "previous" : null,
  "total" : 1
}
```

**Comment by holmberd** [comment]
I can't verify a problem with this endpoint.

**Comment by holmberd** [comment]
I've noticed that when I follow a new playlists they return one single image json object containing one image url on a different domain than the usual: **url: "https://mosaic.scdn.co"**, right now they are on **url: "https://u.scdn.co/"**.

**Comment by thelinmichael** [comment]
@holmberd, images from Spotify can be hosted on different CDNs, usually depending on what type of cover art it is, e.g. a mosaic of album art or if it's a custom image. So that's unrelated from the issue raised here by @ahallora.

**Comment by thelinmichael** [comment]
@ahallora, thanks for reporting. Are you seeing this consistently? If so, where are you based?

**Comment by ahallora** [comment]
@thelinmichael Yes, I haven't been able to get images from this endpoint in the last week or two. Just tried again now from the web console and still empty images-objects on all playlist items. 

I'm located in Denmark, and using Spotify Premium (with Family enabled).

**Comment by mattiamaestrini** [comment]
We encounter the same issue, I just noted another strange behaviour. If you request the playlists without any parameter:

    https://api.spotify.com/v1/users/{user_id}/playlists

you receive the playlist from 1 to 20, each one with an empty images object. But if you instead add an offset greater or equals to 6, for example:

    https://api.spotify.com/v1/users/{user_id}/playlists?offset=6

you receive the playlists from 6 to 25, each one with the correct image object even those that before had an empty image (the ones from 6 to 20).

**Comment by thelinmichael** [comment]
Thanks fellows, we're investigating.

**Comment by BertsIdleHands** [comment]
Hey @thelinmichael, any progress on this?
Images still seem to be missing.

Thanks!

**Comment by neonal** [comment]
@BertsIdleHands Could you give us an example user_id?

**Comment by ahallora** [comment]
@neonal try my username...

**Comment by onalzengin** [comment]
@BertsIdleHands If you still having the problem could you share your user_id?

**Comment by BertsIdleHands** [comment]
It's resolved now for me as well. Thanks guys!
