### ISSUE TITLE
get user saved tracks missing tracks

### ISSUE THREAD

**Issue by aligature** [spotify/web-api#212]
I'm using the get current users saved tracks endpoint in the spotify web api.

username: aligature
endpoint: https://api.spotify.com/v1/me/tracks
example url: https://api.spotify.com/v1/me/tracks?market=US&limit=50&offset=100
expected behavior: All the tracks shown in the spotify client should be returned
current behavior: Two tracks are missing for some reason. All other tracks seem to be returned.

missing tracks:
spotify:track:20sjpxvx9l3k314vX0onIv added on 2015-12-23
spotify:track:2q5qg2aBy76G3EcJavDSuZ added on 2015-12-22

**Comment by aligature** [comment]
This behavior only started recently on 2016-04-05.

**Comment by holmberd** [comment]
Are they local tracks?

```
{
  "error": {
    "status": 404,
    "message": "non existing id"
  }
}
```

**Comment by aligature** [comment]
No, they're not local tracks, but it looks like the album may have been moved or replaced.

The original tracks (These still play successfully from my music, but clicking on the album link sends you to the "Something went wrong" error page.):
https://open.spotify.com/track/20sjpxvx9l3k314vX0onIv
https://open.spotify.com/track/2q5qg2aBy76G3EcJavDSuZ

The links found by going to the artist / album:
https://open.spotify.com/track/5tVCYMIYm1d8jbJc5fCuHr
https://open.spotify.com/track/2qZeXyR5LgXWSGLHwod8sx

**Comment by thelinmichael** [comment]
@aligature, apologies for the delay in following up. Are you still seeing this issue in your collection?

**Comment by thelinmichael** [comment]
My suspicion is that the tracks that were part of your collection has been removed from Spotify for some reason. If so, they should consequentially not be shown in the desktop client for your user, or at least be shown as unplayable. I'd be interested in knowing more if you're seeing this issue though, so please re-open the ticket if so @aligature.
