### ISSUE TITLE
Migration of Artist Bio features from Echonest?

### ISSUE THREAD

**Issue by Toddzio** [spotify/web-api#213]
I am trying to build a webapp that provides information about various kinds of artists.  I was hoping to use Echonest's bio feature for musicians, but this is not available in the Spotify API.
Will this feature be implemented?

**Comment by JohnnyCrazy** [comment]
I think this is already covered in #207 @Toddzio

**Comment by thelinmichael** [comment]
Closing since it's a duplicate.
