### ISSUE TITLE
Return unexisting track URI when using `fields` param

### ISSUE THREAD

**Issue by vjo** [spotify/web-api#214]
Using "Get a Playlist's Tracks" endpoint like this: 
`curl -X GET "https://api.spotify.com/v1/users/spotifydiscover/playlists/0V6gREqJmbXLmi5lA555Zz/tracks?limit=50"`

It seems that one track is not available anymore:

``` JSON
...
{
  "added_at" : "2016-04-11T05:41:32Z",
  "added_by" : {
    "external_urls" : {
      "spotify" : "http://open.spotify.com/user/spotifydiscover"
    },
    "href" : "https://api.spotify.com/v1/users/spotifydiscover",
    "id" : "spotifydiscover",
    "type" : "user",
    "uri" : "spotify:user:spotifydiscover"
  },
  "is_local" : false,
  "track" : null
}
...
```

but, when using the `fields` parameter to only get track URI, the API return a track ID for this track anyway:
`curl -X GET "https://api.spotify.com/v1/users/spotifydiscover/playlists/0V6gREqJmbXLmi5lA555Zz/tracks?fields=items(track(uri))&limit=50" -H "Accept: application/json"`

In this case:

``` JSON
...
{
  "track" : {
    "uri" : "spotify:track:6Ijb2xCO37OOFQra6gzYGl"
  }
}
...
```

Which lead to a `Payload contains a non-existing ID` error when trying to use this track URI to add it to a playlist for example.

**Comment by hughrawlinson** [comment]
Hi @vjo. If I'm not mistaken, that playlist seems to be a Discover Weekly. Have you tried adding a `market` parameter equal to the country of the relevant user? That may resolve your issue, however this is still an interesting issue, and I will pass it on to the relevant teams. Thanks! 🎉

**Comment by vjo** [comment]
Hi @hughrawlinson, yes this is a Discover Weekly playlist.

I created an issue because these the endpoint seems inconsistent, I would expect the `uri` to not be available filtering with the `fields` parameter if it wasn't available without filtering in a first time.

Using the `market` parameter doesn't seems to change anything.

**Comment by hughrawlinson** [comment]
Thanks so much for the further explanation @vjo, I will let the team know that changing the market parameter doesn't have any effect.

**Comment by arirawr** [comment]
Hey @vjo - this issue should now be resolved! Thanks for the report 😄

**Comment by shillshocked** [comment]
I got this error again the other day:

0JFsuCdcEeqOPNwIB2Ao5i
Traceback (most recent call last):
  File "/home/destiny/Scripts/addtr2pl.py", line 53, in <module>
    sp.user_playlist_add_tracks(username, playlist_id, tracks)
  File "/usr/lib/python2.7/site-packages/spotipy/client.py", line 465, in user_playlist_add_tracks
    payload=ftracks, position=position)
  File "/usr/lib/python2.7/site-packages/spotipy/client.py", line 180, in _post
    return self._internal_call('POST', url, payload, kwargs)
  File "/usr/lib/python2.7/site-packages/spotipy/client.py", line 126, in _internal_call
    headers=r.headers)
spotipy.client.SpotifyException: http status: 400, code:-1 - https://api.spotify.com/v1/users/musicreleases/playlists/2c5GMM17UWrjYDxPkojPWy/tracks:
 Payload contains a non-existing ID
