### ISSUE TITLE
Wrong results for field filter year

### ISSUE THREAD

**Issue by amorimdecoelho** [spotify/web-api#215]
When searching for type artist and query "year:1910-1920" I get names such as Elvis Presley, who was only born in 1935. But at least all names I'm getting seem to be from old artists. However when querying for "year:1900-1920" I get results like "Eminem" , "Sam Smith" and "Chris Brown".

I get the same weird results when specifying a single year. I'm using the web api console*

"The field filter year can be used with album, artist and track searches to limit the results to a particular year (for example, q=bob%20year:2014) or date range (for example, q=bob%20year:1980-2020)."

**Comment by asmitter** [comment]
Sorry for the delayed response. I had a look into this and this can happen when there is some bad metadata in the catalogue - if an album (particularly a compilation album) has an incorrect date then it can flag the artist as active in that year. 
Errors in metadata are an ongoing process of identification and manual remediation, so I'll close this issue for now. We do strive to always have good metadata, so this should become less of a problem over time.
