### ISSUE TITLE
Get a random song

### ISSUE THREAD

**Issue by JanoschVG** [spotify/web-api#216]
Hi there! :headphones: 

Is it possible to get a random track out of the whole Spotify library?

Obviously, requesting all track ID's and picking one at random is not gonna work. However, I tried generating my own 22-character base-62 ID's which didn't really work all that great as well since they mostly don't exist in the API. Also, the API states that the "Spotify ID does not clearly identify the type of resource".

Any ideas how go about this? Did I miss something really obvious?
Thank you for your help :)

**Comment by heymega** [comment]
You could potentially use the Search-Item method

**Comment by JanoschVG** [comment]
The best solution I found is to use the [search item](https://developer.spotify.com/web-api/search-item/) with a random offset.

**Comment by ftlc** [comment]
Hi!

I'm looking to get information about a list of random songs for statistical learning using the `audio-features` endpoint. Is there any way to get something like that, or would I have to generate search items and get random offsets?

Thanks!

**Comment by hughrawlinson** [comment]
@ftlc yep, you can get songs based on audio feature queries using the "Get Recommendations" endpoint - https://beta.developer.spotify.com/documentation/web-api/reference/browse/get-recommendations/

Make sure you're complying with the developer terms of use! https://beta.developer.spotify.com/terms/
