### ISSUE TITLE
Some songs available in EchoNest not available in Spotify Web API (eg "Style" by Taylor Swift)

### ISSUE THREAD

**Issue by pviolette3** [spotify/web-api#217]
Some songs that have data available in the soon-to-be shutdown EchoNest API are not available in the Spotify Web API, perhaps because Spotify can't play them. I was wondering if there is a plan to migrate these songs from EchoNest, or if we are out of luck for resolving information about them from the Spotify API. Even though some songs are not playable in Spotify, it would be nice if the API knows they exist :)

Here's a specific example:

I can search for the song "Style" by Taylor Swift through EchoNest with the example API key: http://developer.echonest.com/api/v4/song/search?api_key=FILDTEOIK2HBORODV&format=json&results=1&artist=Taylor%20Swift&title=Style

```
{
  "response": {
    "status": {
      "version": "4.2",
      "code": 0,
      "message": "Success"
    },
    "songs": [
      {
        "artist_id": "ARS54I31187FB46721",
        "id": "SOSWRLB1498972BECD",
        "artist_name": "Taylor Swift",
        "title": "Style"
      }
    ]
  }
}
```

But, the equivelent query to the Spotify web api for "Style" by Taylor Swift returns no results: https://api.spotify.com/v1/search?query=Style+artist%3ATaylor+Swift&offset=0&limit=20&type=track

```
{
  "tracks" : {
    "href" : "https://api.spotify.com/v1/search?query=Style+artist%3ATaylor+Swift&offset=0&limit=20&type=track",
    "items" : [ ],
    "limit" : 20,
    "next" : null,
    "offset" : 0,
    "previous" : null,
    "total" : 0
  }
}
```

**Comment by hughrawlinson** [comment]
Hey @pviolette3 - we cannot expose data that we don't have licenses for. It is the *Spotify* API after all. Depending on your use case, it may be possible to use the [Musicbrainz API](https://wiki.musicbrainz.org/Development/JSON_Web_Service) developed by our good friends in Barcelona. Happy hacking! 💻

**Comment by pviolette3** [comment]
Thanks, also nice work guys getting Taylor Swift back (y)
