### ISSUE TITLE
Multiple URI's for the same album (and songs)

### ISSUE THREAD

**Issue by codytodonnell** [spotify/web-api#219]
I came across two different Spotify URI's for the same album as well as the songs that are contained in this album (specifically the album is Hail to the Thief by Radiohead).

Several days ago I was using the Spotify "Search for an Item" endpoint to find the tracks from an album that matched my query and then I used the track URI's to search Echo Nest using for the track:

`https://api.spotify.com/v1/search?q=album:hail+to+the+thief%20artist:radiohead&type=track&limit=50&offset=0`

Using the same query today, I am getting all the same data from Spotify, except the URI's are different for the album as well as the tracks within the album. The track URI's that I am now retrieving are returning empty audio_summary results from Echo Nest. The URI's that were used previously still work with Echo Nest and are returning complete audio_summary results. I will include all the endpoints I am testing this with below.

Multiple URI's for the same album:
`https://api.spotify.com/v1/albums/1oW3v5Har9mvXnGk0x4fHm`
`https://api.spotify.com/v1/albums/1OAMyQGaooBR0qjxDEjG4t`

Multiple URI's for the same track:
`https://api.spotify.com/v1/tracks/37kUGdEJJ7NaMl5LFW4EA4`
`https://api.spotify.com/v1/tracks/0yeJZaM09venrf1bkQB70R`

Empty Echo Nest audio_summary:
`http://developer.echonest.com/api/v4/track/profile?api_key=******************&format=json&id=spotify:track:37kUGdEJJ7NaMl5LFW4EA4&bucket=audio_summary`

Complete Echo Nest audio_summary:
`http://developer.echonest.com/api/v4/track/profile?api_key=******************&format=json&id=spotify:track:0yeJZaM09venrf1bkQB70R&bucket=audio_summary`

**Comment by asmitter** [comment]
This is likely related to the face that Radiohead have just changed label, so their catalogue will have been re-ingested, generating new URIs.
For the audio features you should use the migrated endpoint: https://developer.spotify.com/web-api/get-audio-features/ which contains data for both of those track URIs you posted above.

**Comment by codytodonnell** [comment]
Thanks for the link to the Spotify audio-features method. That seems to be updated and work better.
