### ISSUE TITLE
Get User's Playlists: Not returning all public playlists

### ISSUE THREAD

**Issue by FranciscoAlexis** [spotify/web-api#22]
Hi guys,

I've been using this api call with my own account and turns out it doesn't return all my playlists... i'm using limit = 50 and offset = 0, but some playlists just don't get returned on the items array.

BTW i own less than 50 playlists

Any hints on what may be the problem?

**Comment by thelinmichael** [comment]
Hi @FranciscoAlexis. Are the missing playlists possibly collaborative? Collaborative playlists are currently not returned from the Web API.

**Comment by FranciscoAlexis** [comment]
Hi @thelinmichael,

Only one of them, in fact i changed ir to non-collaborative but still is not being returned. The others have been always non-collaborative but still i'm not getting them.

If it helps, i'm using  the following scopes playlist-read-private, playlist-modify-public, playlist-modify-private

**Comment by thelinmichael** [comment]
Thanks, knowing your scopes does help. Is it always the same playlists that are not returned? If so, are the playlists that are not returned private? I'm assuming that the used access token is authorized by the same user as the one in {user_id}.

**Comment by FranciscoAlexis** [comment]
Yes, they are always the same playlists no being returned. Most of them are private, but the ones that are being returned are private as well.

And finally yes, the user access token is the same authorized by the user on user_id.

**Comment by thelinmichael** [comment]
@FranciscoAlexis, what's your user_id? I'd be helpful to have it so I can make more detailed checks from here.

**Comment by FranciscoAlexis** [comment]
No problem, my id is 1211666386

**Comment by thelinmichael** [comment]
Thanks, could you also provide the Spotify URI to one of the playlists that you expect to be returned?

**Comment by FranciscoAlexis** [comment]
Sure,
Here are two of the ones that are not being returned

spotify:user:1211666386:playlist:72UwpKRSizH5nvK2AsrnPd
spotify:user:1211666386:playlist:22VeCcTIK3MPbT36pYAF1Z

**Comment by thelinmichael** [comment]
Thanks a lot @FranciscoAlexis, I've confirmed that this is a bug and we'll hopefully have it sorted shortly.

**Comment by thelinmichael** [comment]
@FranciscoAlexis, I tried making a request to this endpoint with an access token that was authorized by your user, with the `playlist-read-private` scope, and it did return these playlists. However, making the same request without the  `playlist-read-private` scope, or making the request as a different user, will not return these playlists - which it should.

**Comment by thelinmichael** [comment]
Ok, I think there's a pretty simple solution to this issue. 

Both of these playlists are private. (Both [72UwpKRSizH5nvK2AsrnPd](https://developer.spotify.com/web-api/console/get-playlist/?playlist_id=72UwpKRSizH5nvK2AsrnPd&user_id=1211666386) and [22VeCcTIK3MPbT36pYAF1Z](https://developer.spotify.com/web-api/console/get-playlist/?playlist_id=22VeCcTIK3MPbT36pYAF1Z&user_id=1211666386) have `public: false`).

I believe that your original request either

- Used an access token that was authorized by a user that wasn't the owner of the playlist, `1211666386`. Making a request with the `playlist-read-private` will not return private playlists unless the request is made on behalf of the playlists' owner.
- Used an access token that didn't have the `playlist-read-private` scope.

I'm going to close this issue. If you believe that I'm mistaken, feel free to add some reason to why and reopen it.

**Comment by FranciscoAlexis** [comment]
@thelinmichael i believe i'm using the playlist-read-private scope, and these playlists are mine. But, i will have to confirm it when i get home. Thanks.

**Comment by FranciscoAlexis** [comment]
I've just confirmed that the issue is fixed. Thank you very much!
