### ISSUE TITLE
Many seed_genres not Working For Get Recommendations Call

### ISSUE THREAD

**Issue by rfarmaha** [spotify/web-api#220]
I'm unable to pull tracks for popular genres such as `hip-hop`, `trip-hop`

e.g. `https://api.spotify.com/v1/recommendations?seed_genres=hip-hop` returns no recommendations

**Comment by asmitter** [comment]
I tried it just now and get recommendations for both genres:
https://developer.spotify.com/web-api/console/get-recommendations/?seed_genres=hip-hop
https://developer.spotify.com/web-api/console/get-recommendations/?seed_genres=trip-hop
Might have been a temporary condition. Does it work for you now?

**Comment by asmitter** [comment]
Closing for now, assuming it was a temporary issue. Please reopen if you have more problems.
