### ISSUE TITLE
Intermittent errors: 504 Gateway Timeout, 500 Internal Server Error, 502 Bad Gateway.

### ISSUE THREAD

**Issue by cosinekitty** [spotify/web-api#221]
Most of the time the Spotify Web API has been working very well in my application. Every 2 or 3 days however, there are multiple-minute outages where a request to api.spotify.com stalls for 30 to 45 seconds, followed by one of the following errors.  I list them in order of decreasing frequency:

- (504) Gateway Timeout
- (500) Internal Server Error
- (502) Bad Gateway

In every case, if I wait a few minutes and try again with an identical request, it will start working again with no changes on my end.  When a request fails, others start failing afterward also. When a request succeeds after that, they all start working again. 

There is no obvious pattern regarding what types of requests I am sending when the outages occur.  I have seen this happen fetching albums, playlists, and tracks.  Here are the most recent 3 examples that have failed in this way.  All times are in USA Eastern Daylight Time (UTC-04:00).

- 2016-04-19 09:29:24 (500) Internal Server Error; https://api.spotify.com/v1/users/earthygirl123/playlists/2JhABMR78FpkbXrk3IadNy?fields=name%2cimages%2ctracks.total&locale=en_US&country=US

- 2016-04-13 21:59:32 (502) Bad Gateway; https://api.spotify.com/v1/users/spotify/playlists/5wDvHZhgPBlWyDEZ3jSMF4?fields=name%2cimages%2ctracks.total&locale=en_US&country=US

- 2016-04-07 13:48:40 (504) Gateway Timeout; https://api.spotify.com/v1/tracks/1tsWNtWxi7SVydMm2G1W6Z?market=US&locale=en_US&country=US

Are such outages to be expected by clients normally, or is this something that can be addressed by Spotify?  It is especially painful when the client has to wait 30 to 45 seconds for the error to occur, and retrying would fail also.  I could time out on my client side sooner.  I have seen normal requests take 6 or 8 seconds, so I don't know what a safe timeout would be.  I'm guessing 15 seconds, but that is still a long time to wait only to fail.

I do notice DNS lookup for api.spotify.com does return different IP addresses; I suppose this is for load balancing.  Is it possible that a particular server (IP address) might be out of commission for a while but other servers would work?  In other words, would it make sense to retry to a different IP address if I can obtain one?

When this happens my client becomes unresponsive for several minutes because each request is taking so long and requests keep failing during that time.  Any help would be most appreciated!  Thank you.

**Comment by asmitter** [comment]
Sorry for the late reply. These issues should be very rare. Are you still having problems?

**Comment by cosinekitty** [comment]
I have not seen this happen in the last couple of days. I will keep an eye on it.

**Comment by hughrawlinson** [comment]
Hey @cosinekitty - haven't heard about this in a while, so I'll close this issue. Please do reopen it if you are still encountering this issue! Happy hacking. 🐈
