### ISSUE TITLE
Add web api wrapper for R language

### ISSUE THREAD

**Issue by taddallas** [spotify/web-api#223]
I've been working on a small project that allows `R` access to aspects of the Spotify api in order to create [networks of related artists](http://taddallas.github.io/music/), as well as control a Spotify instance from an R session (skip tracks, get track info, etc.; relying heavily on [this script](https://gist.github.com/wandernauta/6800547)).  If you think it's worth it, would you consider adding it to your [developer page](https://developer.spotify.com/web-api/code-examples/)?

**Comment by thelinmichael** [comment]
Very cool @taddallas, thanks for doing this and providing the code for others to reuse. The issue I'm having with https://github.com/taddallas/rSpotify is that it's also using an interface to control the client that isn't publicly supported and may stop working without notice. This is something that we've recommended against for some time, so my personal take is that it would be inconsistent with our messaging to include it on the page. Again, appreciate your effort and would be happy to add it if it wasn't for the parts controlling the client.
