### ISSUE TITLE
Retrieve Personalized list of Upcoming Concerts

### ISSUE THREAD

**Issue by lyrixx** [spotify/web-api#224]
Hello.

In the application, I have the concert tab:
![screenshot4](https://cloud.githubusercontent.com/assets/408368/14783750/0d128544-0af2-11e6-8a57-56c2963df1f7.png)

But it not very easy to share this list to friends. So I wanted to export a simple list via the API. But this endpoint does not exist yet.

It would be awesome to open this API :heart:

**Comment by thelinmichael** [comment]
Hey @lyrixx! While this isn't provided in the Web API, you could get similar functionality by combining the [Get User's Followed Artists endpoint](https://developer.spotify.com/web-api/get-followed-artists/) with [Songkick's API](http://www.songkick.com/developer). Keeping this as a feature request though.

**Comment by jhmacdon** [comment]
Just out of curiosity does Songkicks API provide this data to Spotify? Would love some way to work backwards if Spotify has that data (for example, getting a list of artists at a festival rather than a list of concerts for an artist). 

I see that Spotify has pages with lineups: https://open.spotify.com/concert/1UhGiOYfZSMTJSeB2elcLJ

But it also says "Available on Songkick" on the concert page. 

Either way, would love to just get be able to get a list of Spotify artist URIs/ids for a festival.

**Comment by igm5007** [comment]
I would really like to have this exposed in the api as well given that songkick specifically requests not to combine it with other services 

"4.3 You may not use the Songkick Data in a product or service that competes with products or services offered by Songkick."

**Comment by lohriialo** [comment]
Kindly expose the concert endpoint in the api, it would make the api much more robust

**Comment by kapesacharana** [comment]
Would love to see this api exposed, please consider given many requested, being a year or more now

**Comment by asmitter** [comment]
Hi - thanks for the comments. We won't be able to bring concert data to the Spotify web APIs.
However, as you've noticed data is [included from Songkick](http://support.songkick.com/customer/portal/articles/2091034-tour-dates-on-my-spotify-artist-page), and they have a [pretty nice API of their own](http://www.songkick.com/developer) which I highly recommend checking out.

**Comment by jeff-stclair** [comment]
Sorry to revive this thread, but @asmitter would combining Songkick and Spotify API data not violate Spotify's clause that "You should not use the Spotify brand together with any other brand or in any co-branded communications. Pairing of brands is not permitted under our Developer Terms."?

**Comment by LorenaSabou** [comment]
Hello, is there any update on this topic?

**Comment by brian-bk** [comment]
+1 to feature, looking to sync my personalized concerts with a 3rd party calendar.

**Comment by shalins** [comment]
+1 to this feature as well. I would love for this endpoint to available for developers to use.

**Comment by mabergerx** [comment]
+1, I am waiting for my Songkick API key for a while now and as far as I understood, Songkick doesn't want us to combine it with the Spotify data.
