### ISSUE TITLE
Unable to iterate over search results

### ISSUE THREAD

**Issue by restfulmt** [spotify/web-api#225]
Hi,

The number of total results of searches differs depending on the value of offset and limit. For instance:

Make the following request:
https://api.spotify.com/v1/search?query=redhouse&offset=0&limit=20&type=album

The response returns albums.total=27 and 20 items.

Make another request using the albums.next URI:
https://api.spotify.com/v1/search?query=redhouse&offset=20&limit=20&type=album

The response returns albums.total=21 and 1 item. (6 missing items!)

Make the same request with offset=0 and limit=30
https://api.spotify.com/v1/search?query=redhouse&offset=0&limit=30&type=album

The response returns albums.total=27 and 27 items, which is correct.

I reported this as a bug (#201) but I can't sill find a reliable way to iterate over the results of a search. I would apprecitate any support on this. 

Thanks for looking into this.

**Comment by asmitter** [comment]
We've rolled out a fix which should stabilise this, and I ran your examples successfully.
Thanks for the detailed report.
