### ISSUE TITLE
New release endpoint missing releases?

### ISSUE THREAD

**Issue by andrew-kennedy** [spotify/web-api#226]
There are artists that have new releases that don't show up under the new release endpoint, is there a better to look for new releases for all artists for a region? It seems like if I want to get, say, all of the new releases for a user's followed artists, I have to get every artist they follow, then get all of the music of those artists, and look at the release dates of all the albums.

**Comment by thelinmichael** [comment]
@andrew-kennedy, the [New Releases endpoint](https://developer.spotify.com/web-api/get-list-new-releases/) does indeed return a subset of all newly released albums. 

You could use the [Search endpoint](https://developer.spotify.com/web-api/search-item/) to retrieve new releases in a region by utilising the `new` tag, e.g. https://api.spotify.com/v1/search?q=tag:new&type=album&market=SE. I'm however not sure what constitutes as a `new` album. 

The solution you're using right now, to iterate over the user's followed artists, would be an inefficient but working way to determine if there are any new releases.
