### ISSUE TITLE
Search returns partial matches of the keywords

### ISSUE THREAD

**Issue by restfulmt** [spotify/web-api#227]
Hi,

Searches return partial matches of the keywords instead of exact matches. For instance, a search for “chichos” return albums containing the word “**chic**os” (which are completely unrelated to the target albums).  I tried using double quotation marks but the results are the same. This behaviour seems inconsistent with the documentation. I would expect matches to include the keyword  as a substring (ex. "cachichos") but definitely not matches including only a part of the keyword. Is this a bug? Is there any way of searching for an exact keyword?

As an example, the following request (q=chichos) returns the album shown below (name=Chicos de la Luz):

https://api.spotify.com/v1/search?query=chichos&offset=0&limit=50&type=album
`{
album_type: "album",
available_markets: [
"CA",
"US"
],
external_urls: {
spotify: "https://open.spotify.com/album/1JAJem5IxeIq8Rwo6EhIWe"
},
href: "https://api.spotify.com/v1/albums/1JAJem5IxeIq8Rwo6EhIWe",
id: "1JAJem5IxeIq8Rwo6EhIWe",
images: [
{
height: 640,
url: "https://i.scdn.co/image/e09b51d079900164a6663c1b6cb9073163a01324",
width: 640
},
{
height: 300,
url: "https://i.scdn.co/image/a33f8d7cfbd707e1027da1f11743189afa1d695b",
width: 300
},
{
height: 64,
url: "https://i.scdn.co/image/09e9f091b65dd1be58f7a02f1ad82ddfb03e603c",
width: 64
}
],
name: "Chicos de la Luz",
type: "album",
uri: "spotify:album:1JAJem5IxeIq8Rwo6EhIWe"
}`

Thanks for looking into this.

**Comment by restfulmt** [comment]
A further comment in case it helps: note that the search is done by the exact keyword if a filter is used (as expected). This leads to some counterintuitive results, for instance:

q=chichos
albums.total=32
`https://api.spotify.com/v1/search?query=chichos&offset=0&limit=50&type=album`

q=chichos year:1900-2016 (This time range covers all albums)
albums.total=16
`https://api.spotify.com/v1/search?query=chichos%20year:1900-2016&offset=0&limit=50&type=album`

**Comment by hughrawlinson** [comment]
Hey, sorry for the super late response on this, but if I understand your issue correctly, it's now resolved - but please do double check and reopen this issue if I've misunderstood!
