### ISSUE TITLE
Spotify Web API: Premium usage rates and limits

### ISSUE THREAD

**Issue by calebhskim** [spotify/web-api#228]
It would be helpful if in the near future I could increase the usage rates/limits for my project. Is this possible?

**Comment by thelinmichael** [comment]
@calebhskim, rate limits can be increased but only in special cases. Such special cases could be that your application has a significant user base and that you've done what you can to reduce the amount of requests to the API by for example caching. We've compiled a brief guide to rate limits in the [User Guide](https://developer.spotify.com/web-api/user-guide/#rate-limiting).
