### ISSUE TITLE
Spotify Embed Code Problem

### ISSUE THREAD

**Issue by dagrawal-systango** [spotify/web-api#229]
I have integrated Spotify in blog but it is not working properly as needed from API side. The problem is that it either plays song after n number of requests or redirect to Spotify desktop app. It's embed code is not doing what expected.

**On Firefox**: It makes n number of AJAX requests and after making all requests, I have to press play and then plays track.

**On Chrome**: It redirects to desktop app

Please help me out.

**Comment by thelinmichael** [comment]
Hi @dagrawal-systango! The scope of this Github repository is limited to the Web API, which is separate from the Spotify Play Button and other HTML widgets. I suggest that you report this on Spotify's [Community site](https://community.spotify.com/).
