### ISSUE TITLE
Spotify Charts API Access

### ISSUE THREAD

**Issue by pa12** [spotify/web-api#23]
I am simply looking for an API solution to pull the songs that appear in each country's Viral 50 charts, and noticed that these links are no longer being updated: http://charts.spotify.com/embed?object=tracks&rank=most_viral&country=global&windowtype=weekly&date=latest. 

Is there an alternate API solution for these charts?

**Comment by thelinmichael** [comment]
Hey @pa12. Without getting into details, I'd just like to add that we can't offer the same level of support of the Charts API as we do for the API presented on [Spotify's Developer site](https://developer.spotify.com/web-api). To my knowledge there's no reason as to why the Charts API isn't updated so I'm labeling this as a bug. 

If you're interested, you can retrieve playlists containing the most viral and most tracks for the current week using the [Get a Category's Playlists](https://developer.spotify.com/web-api/get-categorys-playlists/) endpoint - category name 'toplists'. [Try it out using the Web API Console](https://developer.spotify.com/web-api/console/get-category-playlists/?country=US&category_id=toplists).

**Comment by thelinmichael** [comment]
The Charts API will start updating again shortly. 

Since this isn't part of the API covered on the Developer site, I'm going to close this issue as it isn't part of the supported APIs. Still, please don't hesitate to comment here if you're in need of more information. Thanks again for reporting.

**Comment by serhanbakir** [comment]
Hi there,
any developement on charts.spotify.com ? If charts api won't be updating anymore is there any equivalent method to fetch those charts from api.spotify.com ?

**Comment by thelinmichael** [comment]
@serhanbakir, this is still in development. I'll open this ticket and update it when there are changes.

**Comment by kovv** [comment]
Any updates on this issue?

**Comment by thelinmichael** [comment]
Let's track the progress of Charts related endpoints in #33. (https://charts.spotify.com is dead.)
