### ISSUE TITLE
Market parameter does not filter search results as expected

### ISSUE THREAD

**Issue by restfulmt** [spotify/web-api#230]
Whenever I use the market parameter in a search the result set is expanded rather than filtered. Suppose the following example:

https://api.spotify.com/v1/search?query=miguel+bose&type=album
`{
albums: {
href: "https://api.spotify.com/v1/search?query=miguel+bose&offset=0&limit=20&type=album",
items: [],
limit: 20,
next: "https://api.spotify.com/v1/search?query=miguel+bose&offset=20&limit=20&type=album",
offset: 0,
previous: null,
total: 58
}
}`

https://api.spotify.com/v1/search?query=miguel+bose&type=album&market=ES
`{
albums: {
href: "https://api.spotify.com/v1/search?query=miguel+bose&offset=0&limit=20&type=album&market=ES",
items: [],
limit: 20,
next: "https://api.spotify.com/v1/search?query=miguel+bose&offset=20&limit=20&type=album&market=ES",
offset: 0,
previous: null,
total: 92
}
}`

According to the documentation, the first request should return all results while the second should returns only those albums with content playable in Spain (from where I I am invoking the services). That is, the results of the second request should be a subset of the results retrieved in the first request.  Am I missing something? Is this a bug?

Thanks a lot in advance.

**Comment by hughrawlinson** [comment]
They @restfulmt - this is because the search market defaults to US. It's not a matter of searching everything vs filtering that result to Spain, it's more like searching the US vs searching Spain. There's an existing bug report in #194 for adding that feature, so I'll close this issue.
