### ISSUE TITLE
Can't get to Developer account

### ISSUE THREAD

**Issue by sajsanghvi** [spotify/web-api#231]
Really random but don't know where else to leave this comment. I had an app and am still using the developer keys - but somehow I changed my account (logged in via fb unlogged it changed username etc.) and now the app won't show up under 'My Apps' section. 

Any ideas on how to retrieve it?

**Comment by hughrawlinson** [comment]
Hey @sajsanghvi - [Spotify Support](https://support.spotify.com/uk/). They should be able to recover/consolidate your accounts.

Please let us know if you have any more issues!
