### ISSUE TITLE
Documentation typo: Get Several Artists.

### ISSUE THREAD

**Issue by tom12e** [spotify/web-api#233]
The example in [Get Several Artists Docs](https://developer.spotify.com/web-api/get-several-artists/) shows `https://api.spotify.com/v1/artists/?ids={ids},` but in the [Web API Endpoint Reference List ](https://developer.spotify.com/web-api/endpoint-reference) it shows `/v1/artists?ids={ids} `. It took me about 30 mins. to figure out that the last one, was the working one :P

**Comment by hughrawlinson** [comment]
Fixed! Thanks so much for pointing this out @tom12e 😄
