### ISSUE TITLE
analysis_url error 

### ISSUE THREAD

**Issue by Snippern** [spotify/web-api#235]
Are anyone else having troubles with opening analysis_url? I keep getting this error:

  "error":
    "status": 401,
    "message": "No token provided"

The reason I ask is because I had no problems opening analysis_url until recently. It worked just fine before. I'm using the Spotipy library to access the data.

**Comment by thelinmichael** [comment]
@Snippern, an access token is required when retrieving this data and we'll have a look at the documentation to clarify this. It's possible that the Spotipy library needs updating if it's not already sending an access token along with that request.
