### ISSUE TITLE
Feature Request - Current Playing Track to Specified Playlist through IFTTT

### ISSUE THREAD

**Issue by jlindqvist** [spotify/web-api#236]
Hi, is there a search query through the IFTTT service that would enable adding the currently playing track in a specified playlist?

This would enable a Flic button to sort out favourite songs while listening on a nice bike ride or run.

**Comment by hughrawlinson** [comment]
Hey @jlindqvist, this isn't currently possible, and would require a feature request both on Spotify's side, and on IFTTT's side. I'll mention it as a feature request to the relevant teams, thanks for getting in touch!

**Comment by gabrielizaias** [comment]
Related to #12. This would be great to have in the API.

**Comment by hughrawlinson** [comment]
*Very* happy to report that at we've just launched an endpoint to address this issue! [Get Current Users Recently Played Tracks](https://developer.spotify.com/news-stories/2017/03/01/new-endpoint-recently-played-tracks/). This endpoint should enable developers to implement this using IFTTT, so I'll consider this issue closed. If you build it, we'd love it if you could share it with us.

**Comment by JulioFig** [comment]
@hughrawlinson This does not solve this issue please reopen this ticket. I am looking for a Play Playlist action
<img width="920" alt="screen shot 2017-11-27 at 8 51 46 pm" src="https://user-images.githubusercontent.com/12346871/33298497-af43da0c-d3b4-11e7-8e84-67530ce3c682.png">

**Comment by hughrawlinson** [comment]
Hi @JulioFig - IFTTT actions are not in scope for this issue tracker, as the underlying APIs are available. You can file the feature request with IFTTT, or on community.spotify.com.
