### ISSUE TITLE
RAML API specification not up-to-date

### ISSUE THREAD

**Issue by jscholes** [spotify/web-api#238]
The RAML API spec included in this repository hasn't been updated for seven months, which means it's missing the new endpoints that were added in December 2015 and March 2016, as well as any parameter changes that may've been implemented since then.  Is an update planned, or is there an alternative source to get an up-to-date spec?

According to [this post](https://labs.spotify.com/2015/04/21/ramlfications/), the API console uses an RAML specification to create its forms.  Presumably that specification is kept updated but is also presumably private.

**Comment by thelinmichael** [comment]
Thanks for bringing it to our attention @jscholes. We're going to make an update to this repository to reflect the recent changes to the Web API.

**Comment by scottflute** [comment]
Any updates on this?  It appears that the RAML spec still hasn't been updated yet.

**Comment by mirh** [comment]
And that v1.0 pull request has been there open for 8 months.

**Comment by thelinmichael** [comment]
@jscholes, @scottflute - the latest RAML has now been added to the repository. Anyone who wants to get involved in migrating it to RAML 1.0 are very welcome to collaborate with us!
