### ISSUE TITLE
Add /me alias for /users/{user_id}/ endpoints

### ISSUE THREAD

**Issue by jayenashar** [spotify/web-api#24]
There's no way to get the current user's playlists without first getting the current user's profile.  Please consider making all /users/{user_id}/ endpoints available as /me/ endpoints as well.

Thanks,
Jayen

**Comment by CrisMT** [comment]
As you well suggested, we created an alias endpoint: */me/playlists* for */users/{user_id}/playlists* that returns a list of the current user's playlists, provided that you input a valid authentication token tied to your user.

Here you can find the documentation:
[Get List of Current User's Playlist](https://developer.spotify.com/web-api/get-a-list-of-current-users-playlists/)

With the current addition, you no longer have to to make a request to /me to get the user's *user_id* and then, make a request to /users/{user_id}/playlists to get the user's playlists. 

:musical_score: Good luck with your future cool apps!
