### ISSUE TITLE
Date of latest version of tracks or albums

### ISSUE THREAD

**Issue by gerhardberger** [spotify/web-api#240]
Is there a way to retrieve a track's or album's latest upload date?
Unfortunately I don't see it in the API endpoint specification.

**Comment by thelinmichael** [comment]
@gerhardberger, do you mean the time when an album was added to Spotify's catalogue and not its release date? If you're looking for the release date, it's available in the [Get Album](https://developer.spotify.com/web-api/get-album/) endpoint under `release_date` and `release_date_precision`. The API doesn't however expose the date when an album was added to the catalogue. If this is what you need, could you please elaborate on why it'd be useful for your application?

**Comment by gerhardberger** [comment]
@thelinmichael, I want to notify the user, when a new version of a track or album has been uploaded, similar to how app updates work.

**Comment by thelinmichael** [comment]
@gerhardberger, could you please provide an example of what you mean by new version of a track?

**Comment by gerhardberger** [comment]
@thelinmichael, sure, for example [Kanye's The Life Of Pablo](https://open.spotify.com/album/0S3BCTCKEJAfIWM1DYrvFJ) and its tracks are over many iterations.

**Comment by hughrawlinson** [comment]
Thanks @gerhardberger, I will pass this on as a feature request to the appropriate teams.

**Comment by stolendog** [comment]
It looks that its not the right way to relay on release_date field if I need to get latest albums added from the artist?
@hughrawlinson any ETA for this feature request?

**Comment by bih** [comment]
Hello @gerhardberger,

Thanks for your feature request! We're in the process of cleaning up our GitHub issue tracker (as per our [new developer support process](https://github.com/spotify/web-api)) to better serve you and other developers.

In this particular case, we discussed this and decided that whilst it is useful there isn't sufficient demand for this to justify building this out right now. For that reason I'm going to close this as <kbd>wontfix</kbd>.

Though I encourage you and other developers to continue to share use cases and support for this feature - it helps us prioritize features in the future. You should still be able to comment on this issue. We will post updates here if there are any updates relating to this ticket 🙂

Thank you for taking the time to share your feedback, and please continue to do so! We highly appreciate it and of course reach out if you have any other questions!

Cheers 👍
