### ISSUE TITLE
Get Artists by Location ordered by Popularity

### ISSUE THREAD

**Issue by patrickhofer** [spotify/web-api#242]
Is it possible to get information about the most listened tracks based on a city? Like on the about tab in the spotify app. My goal enter a city and find the most listened track. That would be awesome! 

Thank you very much

**Comment by thelinmichael** [comment]
@patrickhofer, this isn't possible to retrieve from Spotify's Web API.

**Comment by patrickhofer** [comment]
@thelinmichael thanks, please let me know if this becomes aviable :)

**Comment by arirawr** [comment]
Hey all,

As per our [new developer support process](https://github.com/spotify/web-api#creating-an-issue), any feature requests that have no plans to be considered in the next 6 months will be closed as wontfix.

We do not have any plans to implement this in the next 6 months and thus will close as wontfix.

We encourage you and other members of the community to continue to share use cases and your support for this feature, as it helps us prioritize features going forward. You will be able to comment on this issue even after it is closed. We will also post any updates here relating to this suggestion when they happen.
