### ISSUE TITLE
Return a list of the most popular artists in a genre

### ISSUE THREAD

**Issue by realworld666** [spotify/web-api#243]
I'd like to get a list of genres and then for each genre return the most popular 100 artists in that genre. Looks like this was possible in echonest but I cant find this feature in Spotify 
http://developer.echonest.com/docs/v4/genre.html#artists

**Comment by hughrawlinson** [comment]
Hi @realworld666 - you can do this using the recommendations endpoint. [Here](https://developer.spotify.com/web-api/console/get-recommendations/?seed_genres=rock&target_popularity=100) is a link to our web console with an example request. Hope that helps!
