### ISSUE TITLE
Add Tracks to a Playlist - Should accept Position as Body parameter

### ISSUE THREAD

**Issue by jayenashar** [spotify/web-api#25]
`position` is documented as a query parameter, but not a body parameter.  Not sure if this is a documentation omission or implementation inconsistency.

**Comment by thelinmichael** [comment]
The Add Tracks to Playlist endpoint doesn't accept `position` in its JSON body, which it should for consistency. (Compare #13)

**Comment by jstlnd** [comment]
This has now been fixed. Position is accepted either as parameter or in the body.
Thanks for reporting.
