### ISSUE TITLE
missing albums in library requests

### ISSUE THREAD

**Issue by bigmittens** [spotify/web-api#250]
when making a request for the albums in my library, only albums that I have added on my phone show up. when viewing the albums on my phone, all albums are returned. the albums not shown were added using the deprecated libspotify library.

occured june 13, 2016 using https://developer.spotify.com/web-api/console/get-current-user-saved-albums/?limit=50

**Comment by asmitter** [comment]
The ability to add albums to a user's collection is not supported in libSpotify.
To add albums to a collection you can use the "Save Albums for Current User" web api endpoint: https://developer.spotify.com/web-api/save-albums-user/

**Comment by bigmittens** [comment]
Ah, I'm mistaken then. The albums were added using https://github.com/dirkgroenen/mopidy-mopify, which must use the web api. However albums added through this client will only show up on the mobile app.

**Comment by asmitter** [comment]
I suggest reporting it to the maintainers of that project. It may be that they are adding all the tracks as separate items instead of the album.
