### ISSUE TITLE
Get audio features - valid access token

### ISSUE THREAD

**Issue by knagle** [spotify/web-api#251]
When performing a normal search, authorization is optional so long as "market=from token" is not supplied in the query string. However, A valid access token from the Spotify Accounts service is required when you perform an audio-features request. 
In my app I do not wish to force the user to login to Spotify in order to retrieve audio-features such as key or mode. Is there a way of performing this request using the developer credentials rather than forcing a user log in?

**Comment by thelinmichael** [comment]
@knagle, you could solve this by using an access token that's retrieved using the [Client Credentials](https://developer.spotify.com/web-api/authorization-guide/#client-credentials-flow) flow - it doesn't require any user interaction.
