### ISSUE TITLE
Get user playlist behavior

### ISSUE THREAD

**Issue by theoscat** [spotify/web-api#252]
Hi,

Doing https://api.spotify.com/v1/user/12176879045/playlists/2sTesWI64zHp7x5aBxYdKw in the spotify console API will return a result, doing the exact same request on postman will return 404.

The playlist isnt public, the user cant see the playlist at all but i have a node app adding track in it !
In the API console i can see that the tracks are added.

Can someone explain me what could possibly happen ? 

Cordialy,

Théo

**Comment by asmitter** [comment]
You're missing an 's' on /users/ Try:
https://api.spotify.com/v1/users/12176879045/playlists/2sTesWI64zHp7x5aBxYdKw
