### ISSUE TITLE
(Spotify Web API) Create New Playlist - POST request returning 'Error 403 (Forbidden)'

### ISSUE THREAD

**Issue by playingwithbandits** [spotify/web-api#253]
Here is the link to the Web API notes on how to create a new playlist. [https://developer.spotify.com/web-api/create-playlist/](https://developer.spotify.com/web-api/create-playlist/)

As far as I understand, the POST requests the url `https://api.spotify.com/v1/users/{user_id}/playlists`. This is requested while passing the access token and data. The content type of the data being 'application/json'.

For some reason this is failing and returning a Error **403 (Forbidden)** in the console.

Anything I'm missing?

I have tried the Spotify Create New Playlist API console example which is online at: [https://developer.spotify.com/web-api/console/post-playlists/](https://developer.spotify.com/web-api/console/post-playlists/ ) using the same details (as well as the same oAuth Token). This online example using cURL works fine! Just not the ajax request...

---------
`//(playlistName, userId, accessToken) are passed to this.

var urlString = 'https://api.spotify.com/v1/users/' + userId + '/playlists';

var jsonData = {
    "name": playlistName,
    "public": false
};

$.ajax({
  type: 'POST',
  url: urlString,
  data: jsonData,
  dataType: 'json',
  headers: {
      'Authorization': 'Bearer ' + accessToken
  },
  contentType: 'application/json',
  success: function(result) {
      console.log('Woo! :)');
  },
  error: function() {
      console.log('Error! :(');
  }
})`

**Comment by asmitter** [comment]
I've tried it out in the console and it works as expected.
Some things to check:
- Does the token have the correct scope (playlist-modify-private)?
- Does the userid you are sending match the user for which the token was provided?

**Comment by playingwithbandits** [comment]
The weird thing about it is that I'm testing the exact same oAuth Token and UserId I'm posting in the Ajax call, using their example console. 

Any GET Ajax calls seem to work fine with the oAuth Token and UserId, It's just the POST request that fails. This would make it seem likely that it's due to 'playlist-modify-private' being somehow different between the Ajax call and their console. :S

**Comment by asmitter** [comment]
Does it work in the console? If so I suspect there's something up with the way your code is doing the POST request, especially if the request also works via cURL.

**Comment by playingwithbandits** [comment]
I think I've spotted the error. (playlist-modify-private not being included) I'll have a look at it tonight and get back to you. Thanks for the help!

**Comment by playingwithbandits** [comment]
Works now! I messed up when generating the oAuth Token and 'playlist-modify-private' was not being included correctly. Now that it has been added it's working as expected! Thanks for the help!

**Comment by josephwilliam11** [comment]
I am using the spoifyApi on numerous different occasions, but getting an error for createPlaylist() the error is below as well as my api call

POST https://api.spotify.com/v1/users/1223418399/playlists 403 ()

savePlaylist = () => {
  const id = this.state.userId;
  const playlist = this.state.filteredArray;
  spotifyApi.createPlaylist(id, playlist, function(res) {
    console.log(res) 
})
}

**Comment by ewerton-azevedo** [comment]
I am having the same problem even though the scope is set with all the permissions.

    schlotify.createPlaylist(user.id, playlist_name, JSON.stringify({"public":true, "collaborative":true})).then(function(playlistCreated){
        console.log("passed",playlistCreated)
        return(playlistCreated)
    })

If I use json stringify I get a forbidden response, without it I get a bad request.

This is how I have my scope:

var scopes = ['user-read-private', 'user-read-email', 'user-read-currently-playing', 'user-read-playback-state',
'user-modify-playback-state','streaming', 'playlist-modify-public', 'playlist-modify-private', 'playlist-read-collaborative',
'playlist-read-private'];

The token is correctly set as well. Does anyone have an idea what could I be missing?

**Comment by sb2059** [comment]
Did you figure this out @ewerton-azevedo ?  I'm experiencing a similar issue.
