### ISSUE TITLE
Audio-features accessToken

### ISSUE THREAD

**Issue by knagle** [spotify/web-api#256]
Our iOS app used to perform searches for songs not streamed from Spotify, but stored on the user's device, with Echonest requests for "audio_summary", which would return features such as song key and mode.

Now our app has to perform searches for "audio-features" using a two stage process. First, the search string is created:
`NSString *songSearch = [NSString stringWithFormat:@"artist:%@ title:%@", self.artistNameString, self.songTitle];`
And then we search for a Spotify id using:
`[SPTSearch performSearchWithQuery:songSearch queryType:SPTQueryTypeTrack accessToken:nil callback:^(NSError *error, id object) {...}`
Finally, we request the "audio-features":
`SPTAuth *auth = [SPTAuth defaultInstance];`
`NSURLRequest *audioFeaturesRequest = [SPTRequest createRequestForURL:spotifyScriptUrl withAccessToken:auth.session.accessToken httpMethod:@"GET" values:nil valueBodyIsJSON:YES sendDataAsQueryString:NO error:nil];`

In the above example the user is required to be logged in to Spotify, where previously the Echonest request was performed using the developer credentials. SPTSearch does not require an access token. Why does SPTRequest one? And is it possible to use the developer credentials to perform the request, or does the user absolutely have to be logged in?

**Comment by asmitter** [comment]
The audio features endpoint can be accessed with any valid access token, including those obtained using the "[Client Credentials flow](https://developer.spotify.com/web-api/authorization-guide/#client-credentials-flow)" which don't require a specific user to be tied to them.
The search endpoint currently doesn't require an access token for historical reasons, but it is encouraged that you provide one for more generous rate limits.
All new endpoints require some form of token depending on what operation you want to perform.
