### ISSUE TITLE
Getting Other Users' Top Artists/Top Tracks/ "Top List"

### ISSUE THREAD

**Issue by malsf21** [spotify/web-api#257]
Hello,

I was reading [this article on getting the current user's Top Artists/Tracks](https://developer.spotify.com/web-api/get-users-top-artists-and-tracks/), and I was wondering if there was a way that we could request the Top Artists/Tracks of a *specific user*, such as a tastemaker, artist, or blog writer, instead of the *current user's* top artists/tracks. 

I'm not entirely sure if there's a better way to do this, but I haven't found anything online (other than the now inactive [Spotify Apps API](https://www.quora.com/Does-the-spotify-API-let-you-display-a-users-most-listened-to-track-during-a-period-of-time).

**Comment by thelinmichael** [comment]
Hey @malsf21! No, there's no way to do this. 

The reason why is privacy. We treat this information as something that users may want to keep for themselves, similarly to their private playlists, followed artists, and their birthday. If a user however wants to share this information publicly, they can do so by giving an application access to it.

**Comment by malsf21** [comment]
Hi @thelinmichael , thanks for the response.

Is there a way for a user to give their information, so everybody can see it? Let's say I want to share my top 50 on my blog; would that be possible?

**Comment by thelinmichael** [comment]
> Is there a way for a user to give their information, so everybody can see it?

It isn't possible for a user to make their top tracks public for _anyone_ to retrieve. The user has to give permission to individual applications. (Compare this with for example private playlists, which can be toggled to become public. If that's done, the public playlists will start appearing in the user's [List of Playlists](https://developer.spotify.com/web-api/get-list-users-playlists/) for any application that asks for them.)

> Let's say I want to share my top 50 on my blog; would that be possible?

Sure, that's possible. If there's [an application using Spotify's Web API](https://developer.spotify.com/my-applications/) that [you have given permission to access to read your top 50](https://developer.spotify.com/web-api/using-scopes/), the application could use the access token connected to your user to retrieve your data. When the access token expires, the application could simply refresh the access token provided that the oAuth 2.0 flow used to retrieve the access token was the [Authorization Code Flow](https://developer.spotify.com/web-api/authorization-guide/#authorization-code-flow).

**Comment by malsf21** [comment]
Thanks for the response @thelinmichael, I think I understand how to work on this now. Just want to give you kudos for interacting with the community so much and helping us out 😄 

Have a good day!
