### ISSUE TITLE
Upcoming releases endpoint

### ISSUE THREAD

**Issue by danwani** [spotify/web-api#259]
Hey there,
Is it possible to get pre-release data from the releases API endpoint?
If not, is it or will ever be a separate endpoint?
As a third party website developer, there is a lot more anticipation (and therefore engagement), from users about an upcoming release rather than one that's already out.  No doubt Spotify will have the same reaction from their users, and therefore also have a use for this functionality within their site.
Thanks,
Dan.

**Comment by hughrawlinson** [comment]
Hi @danwani - unfortunately this isn't feasible, as Spotify just doesn't have complete data on upcoming releases. I'll close this issue.
