### ISSUE TITLE
Follow Artists or Users - url with required query parameter

### ISSUE THREAD

**Issue by jayenashar** [spotify/web-api#26]
https://developer.spotify.com/web-api/follow-artists-users/ shows just one URL without query parameters, while https://developer.spotify.com/web-api/add-tracks-to-playlist/ shows two URLs, one with a query parameter.  I think the former should show the required parameter in the URL.  I think the latter should show only one URL with no parameters (as none are required).

**Comment by thelinmichael** [comment]
This was just an inconsistency in the documentation, thanks for pointing it out. Query parameters in the URL have been removed from all endpoint docs.
