### ISSUE TITLE
Current Playing Track

### ISSUE THREAD

**Issue by hongkongkiwi** [spotify/web-api#260]
Hi, I would love to be able to get the currently playing track for an authorized user.

I'm building a plugin to a home automation where it simply shows the currently playing track & artist on an LCD screen, but so far it seems I have no way to get this information in the web-api.

Is there a call I'm missing or is this feature not available? If so can I suggest a simple enhancement.

**Comment by thelinmichael** [comment]
Hey @hongkongkiwi! This feature request is available as #12, so I'm closing this one to avoid duplicates. Your project sounds like a good one, and I hope that we'll be able to enable it in the future.
