### ISSUE TITLE
Get similar tracks by audio features of a single track

### ISSUE THREAD

**Issue by LATAEVIA** [spotify/web-api#262]
Can currently get audio features for multiple tracks based on their Spotify IDs. Is it possible to get tracks by audio features as query arguments?

**Comment by jscholes** [comment]
See the [Get Recommendations Based on Seeds endpoint](https://developer.spotify.com/web-api/get-recommendations/) to accomplish this.

**Comment by LATAEVIA** [comment]
Never mind I came across "Get Recommendations Based on Seeds" and realized it was what I needed. https://developer.spotify.com/web-api/get-recommendations/

**Comment by LATAEVIA** [comment]
Thanks so much!
