### ISSUE TITLE
Genres are not returned for artists

### ISSUE THREAD

**Issue by prullenbak** [spotify/web-api#263]
Hi,

It seems like the https://api.spotify.com/v1/artists/{id} endpoint (almost) never returns any genres? Maybe I'm doing something wrong, but for example a band like muse (/v1/artists/12Chz98pHFMPJEknJQMWvI) should have some genres?

Thanks!

**Comment by hughrawlinson** [comment]
Hey @prullenbak, thanks for getting in touch. This issue is a duplicate of #157, please see that issue for any updates. Thanks!

**Comment by buckmaxwell** [comment]
This issue is not a duplicate of #157, they are different endpoints right?
