### ISSUE TITLE
Wrong artist in recommendations 

### ISSUE THREAD

**Issue by longbeardmen** [spotify/web-api#264]
Hi guys!
There is a bug I found in recommendations.

![selection_007](https://cloud.githubusercontent.com/assets/11632855/16768718/2492a5ca-484e-11e6-9776-60b001030c85.png)

There is two different artists with the same name and by clicking on the name of this artist
https://open.spotify.com/artist/5TQqMJgiBxOcXzvMB0Msby
you'll get wrong discography list.
Owner of this album https://open.spotify.com/album/0igcmMLSJOWqnGlyvSuCg1
has no those albums
https://open.spotify.com/album/2pLNPvl0GFCTnYOt2g9NVZ
https://open.spotify.com/album/3SCOIYGFfFBau9pSpkrMNl
https://open.spotify.com/album/1ATVq9LUryHOT8sPp7s2nG

Fix it, please

**Comment by hughrawlinson** [comment]
Hi @longbeardmen, thanks for pointing this out to us! I've forwarded it to our curation team.

**Comment by longbeardmen** [comment]
Many thanks for operative work, guys!
