### ISSUE TITLE
Getting recommendations doesn't work

### ISSUE THREAD

**Issue by Murad-Bummos** [spotify/web-api#265]
Getting a recommendation based on seeds does not work.

**Comment by asmitter** [comment]
Tried it in the console and works OK: https://developer.spotify.com/web-api/console/get-recommendations/?seed_tracks=0c6xIDDpzE81m2q797ordA

Can you paste the call you are making here, and the error you are receiving?

**Comment by Murad-Bummos** [comment]
It seems to only work on that console. If I try it on postmaster I get 
```javascript
{
  "error": {
    "status": 401,
    "message": "No token provided"
  }
}
```
Despite the fact that I generated a new token using OAuth2.0 after logging in within postmaster. 

If I try it within the app I use this command:
```javascript
 var getNewTracks = function (a,d,e,i,k,li,lo,m,s,te,ti,v,gs) {
                  $.ajax({
                      url: 'https://api.spotify.com/v1/recommendations',
                      async: false,
                      headers: {
                          'Authorization': 'Bearer ' + access_token
                      },
                      data: {
                          seed_artists: artistDataID,
                          seed_tracks: songID,
                          seed_genres: gs,
                          target_acousticness: a,	
                          target_danceability: d,
                          target_energy: e,
                          target_instrumentalness: i,
                          target_key: k,
                          target_liveness: li,
                          target_loudness: lo,
                          target_mode: m,
                          target_speechiness: s,
                          target_tempo: te,
                          target_time_signature:ti,
                          target_valence: v
                      },
                      success: function (response) {
                          document.write(JSON.stringify(response));
                          alert("NICE");
                          resultsPlaceholder3.innerHTML = template(response);
                      },
                      error: function (xhr, response, textStatus, thrownError) {
                          alert(JSON.stringify(xhr));
                      }
                  });

```
and my statustext returns "BadRequest" and error:400. Thank you for such a quick response by the way.

**Comment by asmitter** [comment]
Postman works fine for me. Make sure that after generating the token you select it and click "Use Token". You can see that it is included by switching to the "Headers" tab.

400 Bad Request is returned when there is some mismatch between what you are sending with what the API is expecting. Output the complete request to a string and have a look at what it is sending. If it all looks OK to you but still doesn't work then post it here (but don't post your access token 😄 )

**Comment by asmitter** [comment]
The response from the API should also contain a message in the body giving you a clue as to what the mismatch was. Have a look at that message too.

**Comment by Murad-Bummos** [comment]
It seems to work thank you for the help. However, do you know if there is anyway to require the results to be of a specific seed? For example I want the results to be of a particular genre-seed.

**Comment by asmitter** [comment]
Take a look at the docs: https://developer.spotify.com/web-api/get-recommendations/
You can specify a genre seed, for example: https://api.spotify.com/v1/recommendations?seed_genres=pop

The genre_seeds available can be retrieved by calling https://api.spotify.com/v1/recommendations/available-genre-seeds with a valid token. Details nhere: https://developer.spotify.com/web-api/get-recommendations/#available-genre-seeds

**Comment by Murad-Bummos** [comment]
Yes. I figured out that if you put both genre seed and artist or track seed the search automatically prefers the latter two. I figured out how to accomplish what I wanted. Thank you so much for the help.
