### ISSUE TITLE
Playlist Creation - Add ability to specify position

### ISSUE THREAD

**Issue by JohnnyCrazy** [spotify/web-api#266]
Hi,

The following feature would be nice to have:
**Specify the position of the playlist in the user's list when creating it.**

Use-Case:
When adding songs to a playlist on mobile devices, the whole list of playlists appears with the latest on top of it. The latest aren't always the important ones though, so the user has to scroll till he reaches their favorite playlists. Several services (e.g [discover-backup.com](https://discover-backup.com)) create playlists without user-action. It would be nice if we could add them at the bottom so the user still has his favorites one at the top.

Thinking even further: Maybe another endpoint for reordering playlists would be good to have

**Comment by hughrawlinson** [comment]
Hey @JohnnyCrazy - the order of the playlists is determined by user interaction in the Spotify client, we don't have plans to expose reordering as an endpoint at the moment.

**Comment by JohnnyCrazy** [comment]
Aw, thanks for the heads up tho! :+1:
