### ISSUE TITLE
400 Bad Request (Invalid authorization code)

### ISSUE THREAD

**Issue by steve-quikkly** [spotify/web-api#267]
Hi,

I have retrieved an authorization code from then _https://accounts.spotify.com/authorize_ endpoint perfectly fine. I then forward the code onto the _https://accounts.spotify.com/api/token_ endpoint to try to exchange for an access token.

The response I get is: _{"error":"invalid_grant","error_description":"Invalid authorization code"}_

I am not base64 encoding the _client_id_ and _client_secret_ parameters, but I am adding them as body parameters (as per the documentation). The _grant_type_ parameter value is _authorization_code_ and the _redirect_uri_ is correct.

I have also tried adding a debug fingerprint to my application registration but no joy. If it makes a difference, I am making the requests from Android.

Can anybody help me out?
Many thanks!

**Edit:**
It turns out I was passing _access_token_ instead of _code_ as the _response_type_ parameter to the _https://accounts.spotify.com/authorize_ endpoint. This was clearly an error due to the documentation. However, the error message has now changed to: _{"error":"invalid_grant","error_description":"Invalid redirect URI"}_

**Comment by hughrawlinson** [comment]
The `redirect_uri` has to match with a Redirect URI you have specified in your application settings page. You can find that page at [https://developer.spotify.com/my-applications](https://developer.spotify.com/my-applications). Hopefully that solves your issue. I'm going to close this ticket now, but please feel free to reopen it if you still have a problem, and I'll happily help! Happy hacking! 😄

**Comment by hughrawlinson** [comment]
P.S.: Since you're working with Android, you may like to try out our [Android SDK](https://developer.spotify.com/technologies/spotify-android-sdk/).
