### ISSUE TITLE
Create a Playlist - optional paramater for conflict resolution

### ISSUE THREAD

**Issue by jayenashar** [spotify/web-api#27]
Could you add a parameter to the "Create a Playlist" endpoint so that the client can specify what to do if a playlist of the same name (and visibility) exists?  I can see options like creating the list, setting the visibility on the existing list, emptying the existing list, or doing nothing.  If not creating a new list, the existing playlist object should be returned.

**Comment by fsahin** [comment]
Playlist names are not intended to be unique. It is possible to have multiple playlists with same name. If you want to manage a playlist long term, you should have the id of the playlist as a reference, not the name. If you want to do something other than creating the playlist when a playlist with the same name exists, you can get a list of users playlists and check if the name exists first. But again, the system doesn't ensure the uniqueness of the playlist names, so don't count on it to be unique forever.
