### ISSUE TITLE
Enhancement: Ability to control playback and position/time

### ISSUE THREAD

**Issue by Neo-Desktop** [spotify/web-api#272]
Note this enhancement is very similar to (and dependent on) #15 

I am requesting the ability to control the user's playback and **seek time** pragmatically (via javascript)

This is needed for an awesome social app idea I've got based on ye olde Spotify extension: Sounddrop

Hopefully, this won't be too difficult to build out while #15 is in development :)

Many thanks for building such an amazing platform!

**Comment by hughrawlinson** [comment]
Hey Neo - Thanks for the suggestion! We'll make sure we consider it.

**Comment by thelinmichael** [comment]
I believe this issue could be merged with #15 since that one could contain control of playback seek position as well. 

The JavaScript layer is a nice addition, but isn't related to the Web API.

Feel free to re-open if you disagree @Neo-Desktop.
