### ISSUE TITLE
Album returning with empty available_markets

### ISSUE THREAD

**Issue by 0xNF** [spotify/web-api#274]
Requesting an album, specifically `5M4KhrTlZEpNKVm73XX4Av` will return an empty available markets field, and accordingly, each of its tracks have a ` "preview_url" : null`. Adding almost any `market` to the request will also return `"is_playable" : false`

However, having knowledge of the origin, Japan, adding `market=JP` to the query will return with filled `preview_url`, while still returning `"is_playable" : false`.

Is it expected that this album has no available markets, yet returns a more complete listing when appending what it's actual market probably is?

Request with empty available_markets:
`curl -X GET "https://api.spotify.com/v1/albums/5M4KhrTlZEpNKVm73XX4Av" -H "Accept: application/json" -H "Authorization: Bearer <edited>"`

Request with filled preview_urls:
`curl -X GET "https://api.spotify.com/v1/albums/5M4KhrTlZEpNKVm73XX4Av?market=JP" -H "Accept: application/json" -H "Authorization: Bearer <edited>"`

**Comment by brki** [comment]
Sounds like it's related to #194 (reported 5 months ago).

**Comment by thelinmichael** [comment]
Thanks for the report @0xNF! I believe this issue has been resolved. A request for the album's metadata now returns `JP` in the `available_market` array, and the `preview_url` attributes are populated. Please reopen this issue if you still see issues.

**Comment by wilsonpage** [comment]
The issue is still apparent with this album:

https://open.spotify.com/album/096HVI3iSCGbC8WJFRK0Zc?si=rApV2ZWy

**Comment by hajdbo** [comment]
and this album: 
spotify:album:0oaw93oslOSxqhP4MlEFWq

**Comment by wilsonpage** [comment]
Can this issue be re-opened?

**Comment by stolendog** [comment]
sometimes it returns some available_markets, but another time (later) I get an empty list of available_markets, is it some data inconsistency?

https://api.spotify.com/v1/albums/0Hwc1IF2pmvQCj961KSfz1
https://api.spotify.com/v1/albums/59XmOOWGNhybRV8B0PsFlH

**Comment by stolendog** [comment]
It looks that it returns different data to separate tokens. 

If I use web-api console token (https://developer.spotify.com/web-api/console/get-album) I get empty available_markets, If I use my own application token it returns some available markets for the album. Why it's so?
