### ISSUE TITLE
New Elixir web api wrapper 

### ISSUE THREAD

**Issue by jsncmgs1** [spotify/web-api#276]
I saw your compilation of wrappers libraries in the docs, and I wasn't sure where to let you guys know, but I just released 1.0 of an Elixir web api wrapper, so here you go :)

https://github.com/jsncmgs1/spotify_ex

**Comment by hughrawlinson** [comment]
As [mentioned on twitter](https://twitter.com/SpotifyPlatform/status/760732758641610753) we've added your elixir wrapper to our page. Thanks so much!
