### ISSUE TITLE
Retrieve Current User's Consumption time

### ISSUE THREAD

**Issue by cursorial** [spotify/web-api#277]
Each year we get a 'Your year in music' from Spotify.

This aggregation of data shows us our listening times and the number of new tracks we've listened to over the year.

I think it'd be cool if we could access this data, I've taken a brief look at the documentation and it doesn't seem to be available, if there is a way to see it, how, and if not, then this is a feature request.

**Comment by hughrawlinson** [comment]
Hey @cursorial - that would be awesome, we'll consider it! Thanks for the feedback.

**Comment by cursorial** [comment]
Any updates on this?

**Comment by dgollahon** [comment]
I'd also be really interested in this feature, especially since I couldn't find any listening time information for 2016 like I could the previous year with Year In Music.

Is this still under consideration?

**Comment by cursorial** [comment]
@hughrawlinson any news on this? Would be such a cool feature, seems a shame it's being missed out on.

**Comment by arirawr** [comment]
Hey all,

As per our [new developer support process](https://github.com/spotify/web-api#creating-an-issue), any feature requests that have no plans to be considered in the next 6 months will be closed as wontfix.

We do not have any plans to implement this in the next 6 months and thus will close as wontfix.

We encourage you and other members of the community to continue to share use cases and your support for this feature, as it helps us prioritize features going forward. You will be able to comment on this issue even after it is closed. We will also post any updates here relating to this suggestion when they happen.
