### ISSUE TITLE
Recently get status 500 when call api get playlist of user

### ISSUE THREAD

**Issue by thevuuranusls** [spotify/web-api#278]
I'm recently get status 500 error at: https://api.spotify.com/v1/users/.../playlists or next page (next offset). I have > 800 playlist.
example: 
`curl -X GET "https://api.spotify.com/v1/users/videofly/playlists?offset=0&limit=50" -H "Authorization: Bearer BQDpEnEdtA_yLMhY9aAYNA3SpZttrB7fsmS1yHXZmAdsq32kYLUbs3DrXvxBlUloPKOlo60HYVDBhIRGq5SiHg"` and get return:
_{
"error": {
"status": 500,
"message": "Internal server error. Please try again later."
}_

**Comment by thelinmichael** [comment]
Thanks a lot @thevuuranusls! It's easy to reproduce this error. We'll have a look at it.

**Comment by MikeNGarrett** [comment]
This bug was fixed in 2017, but recently cropped back up. Making this request with an offset of 0 triggers a 500 error. 

https://developer.spotify.com/web-api/console/get-current-user-playlists/?offset=0

**Comment by arirawr** [comment]
This was resolved and is no longer reproducible. Closing the issue 🙂
