### ISSUE TITLE
Get User's Playlists - ETag doesn't change when response changes

### ISSUE THREAD

**Issue by jayenashar** [spotify/web-api#28]
Steps:

1. Request user's playlists: https://api.spotify.com/v1/users/getsoundninja/playlists?limit=50&offset=0
2. Add a track to a playlist: https://api.spotify.com/v1/users/getsoundninja/playlists/1Jp15JlbHgdGCRjEgcaswl/tracks?uris=spotify:track:4rr67zXmEYf9ykLigeEsbv
3. Request user's playlists: https://api.spotify.com/v1/users/getsoundninja/playlists?limit=50&offset=0 using `If-None-Match` Etag retrieved in step 1

Expected outcome:

1. Same playlists with tracks.total updated

Actual outcome:

1. HTTP 304 Not Modified

**Comment by thelinmichael** [comment]
Hi @jayenashar! Again, thanks for your feedback. This isn't a bug, which I can understand is somewhat confusing. The Etag received from the Get User's Playlists request changes if a playlist has been added or removed - not when a specific playlist has changed. The Etag you receive from the Get Playlist endpoint changes when you add a track to the same playlist.

**Comment by thelinmichael** [comment]
A fix for this has been deployed. The `ETag`'s value is now changed if the response is changed. Note that this change is only for the Get User's Playlists endpoint, and not the Get Playlist or Get Playlist's Tracks endpoints.
