### ISSUE TITLE
Intelligent shuffle  

### ISSUE THREAD

**Issue by Farmdoggydog** [spotify/web-api#280]
Users have huge playlists that they have amassed over the years and turned into a minefield of generas. Intelligent shuffle would let you set perimeters within the shuffle mode only playing music of a certain genera, year ect. within that playlist.

**Comment by jscholes** [comment]
This is not the job of the Spotify API, and would probably result in a lot of unnecessary API calls.  If you want to implement smart shuffle in your app, that's up to you.

**Comment by thelinmichael** [comment]
@Farmdoggydog, this seems to be a feature request for Spotify's application for desktop or mobile. If so, the best place to post it is at [Spotify's community site](https://community.spotify.com). This Github repository is dedicated to [Spotify's web API](https://developer.spotify.com/web-api).
