### ISSUE TITLE
Image timeout when using mobile data on iPhone

### ISSUE THREAD

**Issue by alexduckmanton** [spotify/web-api#281]
Hi guys! I have a super weird one for you. 

I'm using the Spotify search API to link my users out to artist/album Spotify pages. As part of the link, I display an image returned from the Search API, e.g. https://i.scdn.co/image/0b3c04473aa6a2db8235e5092ec3413f35752b8d

The issue I'm having is that when viewed on an iPhone with mobile data, the image tries to load for about 30 seconds before timing out completely. It works just fine with WiFi turned on.

I'm on an iPhone 6S with iOS 9.3.4

Thanks!

**Comment by asmitter** [comment]
Is this every time? How's the signal strength?

**Comment by alexduckmanton** [comment]
Yeah every time - signal strength is fine. Everything else works perfectly. 

If you load the image with wifi, then switch back to mobile data it'll work, but I assume that's because the image has been cached.

**Comment by asmitter** [comment]
That is super weird. Could something be blocking access to the CDN?

**Comment by alexduckmanton** [comment]
Not sure. It's definitely not something specific to my phone. I've done a bit more testing on a few friends' phones and had mixed results (all on iPhones in Australia):

Image loaded:
- iOS 9.3.2, Telstra
- iOS 9.3.2, Amaysim (Optus reseller)
- iOS 9.3.2, Amaysim

Image timed out:
- iOS 9.3.1, Optus
- iOS 9.3.4, Optus
- iOS 9.3.4, Optus

Optus seems to be the common theme, but it's curious that the image loads fine for people on Amaysim, who (as far as I know) just resell Optus' network. 

Do you think the issue is more likely to be with the CDN or with this ISP? Optus recently stopped metering Spotify data, so perhaps something's gone wrong there?

**Comment by asmitter** [comment]
It's likely to be an ISP issue. If they are not metering Spotify data some traffic interception is maybe happening? Afraid I'm no expert on in inner workings of Australian ISPs! 😖

**Comment by alexduckmanton** [comment]
I think so too. I've raised a ticket with Optus and they're "investigating".

Thanks for your help!
