### ISSUE TITLE
New Releases not Updating in API endpoint

### ISSUE THREAD

**Issue by jessicaraepetersen** [spotify/web-api#286]
Is there a lag time between when the New Release page is updated with new albums and when the API get requests includes those new albums? For example, today (Friday, August 12th) Rae Sremmurd's new album SremmLife2 was released, but when I get the new release list with the API endpoint, that album is not included. Thank you in advance for your time!

**Comment by thelinmichael** [comment]
Hi @jessicaraepetersen! The [New Releases endpoint](https://developer.spotify.com/web-api/get-list-new-releases/) includes a subset of all new albums. This could be the reason that the album you're expecting to be in the response isn't part of it.

**Comment by jessicaraepetersen** [comment]
@thelinmichael thank you so much for taking the time to help! Have a lovely day!
