### ISSUE TITLE
Authentication fails with invalid_client

### ISSUE THREAD

**Issue by TheAtomicGoose** [spotify/web-api#289]
The authentication for my app suddenly stopped working, without my making any changes (that I know of). I'm using the Node port of the Web API, and I get `WebapiError: Bad Request` every time I try to authenticate. Just to check if the issue lay in the Node version of the API, I tried using the following curl request to get an access code: 
```curl -H "Authorization: Basic clientId:clientSecret" -d grant_type=client_credentials https://accounts.spotify.com/api/token```
 When I do that, the response is `{"error": "invalid_client"}`.

I've tried regenerating my client secret, and making a new app altogether, but have still met with the same issue after doing both of those things. Any help would be much appreciated.

Thanks!

**Comment by jsimonsson** [comment]
Hey I'm not sure how it has worked before, but that Basic clientId:clientSecret should be Basic <base64encoded clientId:clientSecret> can you verify that you are doing so? Have a look here: https://developer.spotify.com/web-api/authorization-guide/#client-credentials-flow

**Comment by TheAtomicGoose** [comment]
Ah, my bad. The curl request does work once I base64 encode the clientId:clientSecret string. However, on line 22 in [`server-methods.js`](https://github.com/thelinmichael/spotify-web-api-node/blob/master/src/server-methods.js) in the [Node API](https://github.com/thelinmichael/spotify-web-api-node/) repo, it appears that the clientId+clientSecret string is being base64 encoded, so that shouldn't be the issue. Any other ideas? Thanks!

**Comment by TheAtomicGoose** [comment]
After doing some more messing around with my code, I've noticed something very strange. When I get the authorization URL, I click on it, and then the web page acts like it's loading the authorization URL, but never actually loads it. However, I do receive the JSON object with the `access_token`, `refresh_token`, etc. But then after I print out the JSON object to make sure it exists, I sometimes receive a `Bad Request` error. It confuses me that the request could be bad if I'm receiving the access_token.

**Comment by TheAtomicGoose** [comment]
Nevermind, the error was not related to the authorization flow. I got it figured out...sorry for the false alarm. Thank you for your help.
