### ISSUE TITLE
Get My Saved Tracks - Add "fields" filtering

### ISSUE THREAD

**Issue by Thalhammer** [spotify/web-api#29]
Please provide the posibility to filter the returned fields,known from normal playlists also for mySongs.

**Comment by vdesabou** [comment]
I believe the current API does not allow this:

The `fields` parameter is not available for User’s Saved Tracks (https://developer.spotify.com/web-api/get-users-saved-tracks/) whereas it is for Get playlists tracks (https://developer.spotify.com/web-api/get-playlists-tracks/)

So there is no way to filter right now I'm afraid, confirmed by Spotify here: https://developer.spotify.com/web-api/get-users-saved-tracks/#comment-1952284473

**Comment by hughrawlinson** [comment]
Thanks for the issue @Thalhammer. Field filtering is not a particularly common REST API feature, and we don't think we'll address it in the near term. Between that and the lack of engagement this issue has received, I'll close this issue.
