### ISSUE TITLE
Retry-After response header not available in response

### ISSUE THREAD

**Issue by ashishbaltech** [spotify/web-api#293]
Hi,
I am woking at a project where i am creating spotify followers widgets as describe in below link https://developer.spotify.com/technologies/widgets/spotify-follow-button/.

I have two artist 
1. Madonna : spotify:artist:6tbjWDEIzxoDsBA1FuhfPW
2. Jedi :  spotify:artist:4gWKo9ZFjRHmrxGKUDOLJ1

I tried to create widgets for both but getting error in console for artist Jedi 

**?uri=spotify:artist:4gWKo9ZFjRHmrxGKUDOLJ1&size=detail&theme=light:13 The widget was not rendered due to an error 429(anonymous function) @ ?uri=spotify:artist:4gWKo9ZFjRHmrxGKUDOLJ1&size=detail&theme=light:13**

it is working for Madonna without Error code 429.

I read 429 in docs and know about retry-after count for it but 

I am not getting Retry-After response in header response. 

![a](https://cloud.githubusercontent.com/assets/20041297/17960728/732331a2-6ac5-11e6-99f3-de1f5688f5a6.jpg)

**Comment by JMPerez** [comment]
@ashishbaltech This issue is not related with the Web API, but we'd love to help you out. Could you provide the whole URL for the Spotify Play Button or the embed code for `Jedi`? It seems to be working for us.

**Comment by JMPerez** [comment]
I'm closing this issue for now. Feel free to reopen it if you can provide some additional information.
