### ISSUE TITLE
API seems to be returning inaccurate songs

### ISSUE THREAD

**Issue by patrickml** [spotify/web-api#294]
We have been using this api for about a week now for users to search for songs to be played. We haven't updated our Webapp since then. Now when we search for songs (including ones we have before) songs that don't really match the query are showing up. Any idea?

**Comment by GabeJacobs** [comment]
Also seeing this. Something with search is off

**Comment by thelinmichael** [comment]
Thanks for reporting @patrickml and @GabeJacobs. Could you please provide us with an example query?

**Comment by GabeJacobs** [comment]
@thelinmichael Try searching "A 1000 Times" which is this song https://open.spotify.com/track/1MFqL5S1fnIM68v80otDwl. Before the downtime yesterday this song would show up in search. Now I can't get it.

**Comment by patrickml** [comment]
@thelinmichael If you search for `https://api.spotify.com/v1/search?q=all+the+small+things&offset=0&type=track` this song used to come up 
`https://open.spotify.com/track/12qZHAeOyTf93YAWvGDTat`

Now this is what is coming up https://cl.ly/0q302X1x3L0A

**Comment by thelinmichael** [comment]
@GabeJacobs, @patrickml, we've just deployed a patch and expect this to be resolved now. Please let us know if you're still seeing unexpected behaviour.

**Comment by thelinmichael** [comment]
Thanks again! 

![nod](https://media.giphy.com/media/vgUFOWBwBkziE/giphy.gif)

**Comment by GabeJacobs** [comment]
@thelinmichael Haha. Is it still propagating though? Seeing that if I search "A 1000 Times" that song still doesn't show up. It shows up if I search "A 1000 Time" though

**Comment by patrickml** [comment]
It seems to be fixed for me thank you!

**Comment by patrickml** [comment]
I'm curious what was the issue?

**Comment by GabeJacobs** [comment]
@thelinmichael looks good now
