### ISSUE TITLE
Previews for newly uploaded songs are corrupt

### ISSUE THREAD

**Issue by GabeJacobs** [spotify/web-api#295]
Im noticing that for new Spotify tracks, the previews aren’t playable.

For example, this is a track that was uploaded to Spotify a day ago and preview url is https://p.scdn.co/mp3-preview/adb683e820cd7dcdfb5adfb8f8a3855ec89de961. Trying to play this file fails since I think it’s corrupted. Older previews work fine, such as this one https://p.scdn.co/mp3-preview/e88485b9d7b6fc426931c9f4355cc1a9998be99c.

Any idea what is going on?

**Comment by thelinmichael** [comment]
@GabeJacobs, we'll investigate further - thanks a lot for reporting this. If you've got more examples that'd be very helpful.

**Comment by GabeJacobs** [comment]
@thelinmichael I think they are just missing the .mp3 extension

**Comment by GabeJacobs** [comment]
@thelinmichael If I rename the file and give it an .mp3 extension, it is the right file. But since our app doesn't do the renaming, it fails. We noticed it happens to only new songs. So this album too is corrupted: https://open.spotify.com/album/2haR5qnQopCdVASZ92YTGn

**Comment by GabeJacobs** [comment]
@thelinmichael Just wondering if you saw anything while investigating?

**Comment by GabeJacobs** [comment]
You'll notice that if you open this up using the twitter app on the iPhone, playing it will make the app crash: https://twitter.com/alftirado/status/769037228303650816

**Comment by thelinmichael** [comment]
@GabeJacobs, retested this now and it works. Are you able to recreate the issue? Thanks!

**Comment by GabeJacobs** [comment]
@thelinmichael I ended up manually adding in a .mp3 extension if it didn't have one. That did the trick.

**Comment by thelinmichael** [comment]
@GabeJacobs, alright! Thanks for responding, appreciate your help troubleshooting this issue. This should ideally work without having to change the filename extension, so we'll keep a look out for this problem in the future.
