### ISSUE TITLE
Ability to query with explicit: false

### ISSUE THREAD

**Issue by patrickml** [spotify/web-api#296]
Is there currently a way to search for only non-explicit songs?

**Comment by thelinmichael** [comment]
Hey @patrickml! It's not possible, no. You'd have to filter out those results. Note that `explicit: false` means that the content is either explicit _or unknown_. 

Reference: [Search endpoint](https://developer.spotify.com/web-api/search-item/)

**Comment by patrickml** [comment]
@thelinmichael I had tried this, but nothing shows up when you added `explicit` filter

https://api.spotify.com/v1/search?q=all+the+small+things%20explicit:false&offset=0&type=track

When you search for this song nothing is `explicit` so all the songs should show, but nothing does. Are there only certain keys you can filter by?

**Comment by jscholes** [comment]
> @thelinmichael I had tried this, but nothing shows up when you added  explicit  filter

That's because there is no explicit filter.  As @thelinmichael noted, this isn't possible.  You'll need to do a regular search, and then filter out any explicit results from the data you get back yourself.

**Comment by sameerjj** [comment]
results can sometimes be quite slim after filtering explicit manaully, so I +1 this. At the same token the Spotify app doesn't have much functionality around this so maybe it's too much to ask.

**Comment by bih** [comment]
Hello @patrickml,

As per our [new developer support process], any feature requests that have no plans to be considered in the next 6 months will be closed as <kbd>wontfix</kbd>.

In this particular case, filtering out search results based on the `explicit` key returned is possible. There is still a case for having a dedicated `explicit` parameter for performance reasons, but won't be considered in the next 6 months.

We encourage you and other members of the community to continue to share use cases and your support for this feature, as it helps us prioritize features going forward. You should be able to comment on this issue even after it is closed. We will also post updates here relating to this suggestion as and when they happen.

Cheers 👍

**Comment by Gelevation** [comment]
So...has anyone been able to search by typing in explicit:false? It doesn't seem to be accurate.
