### ISSUE TITLE
Cannot add non-facebook friends

### ISSUE THREAD

**Issue by novabum** [spotify/web-api#297]
I have a friend who does not have a facebook account, however I use Spotify with my facebook reg. I tried many ways to add him but did not succeed.
Tried to add his username and spotify:user:username too. How the hack can I add him? Any help is appreciated.

**Comment by asmitter** [comment]
This tracker is for issues with the Web API.
For general Spotify help you can visit https://support.spotify.com/ or ask in our community forums. I had a quick look and there are some suggestions posted here: https://community.spotify.com/t5/Accounts-and-Subscriptions/Add-people-friends-without-facebook-accounts/m-p/2213
