### ISSUE TITLE
Japanese characters are returned when using Accept-Language header (with en before ja)

### ISSUE THREAD

**Issue by matijse** [spotify/web-api#299]
I am using the web API in my iOS app, with the framework AFNetworking (https://github.com/AFNetworking/AFNetworking).

By default, this framework adds an `Accept-Language` header, presumably based on the users Locale. 

In my case this header is added: `Accept-Language: nl;q=1, en;q=0.9, fr;q=0.8, de;q=0.7, ja;q=0.6, it;q=0.5` (I am from NL / The Netherlands).

With this header, I get some artists names returned in Japanese, even though `ja` is listed 5th... For example `https://api.spotify.com/v1/search?q=perry&type=track&market=NL&limit=50` returns `ケイティ・ペリー` as the artist name of the second result. When I remove that header I get `Katy Perry`. 

Also, on another phone, which is set to English, the default header is `Accept-Language: en-NL;q=1`, which also produces English results (ie. `Katy Perry`)

**Comment by asmitter** [comment]
Thanks for the report - we can reproduce the issue and will investigate.

**Comment by GabeJacobs** [comment]
@asmitter Hey we are seeing this too from some of our users: 

![crxkq30w8aa9rmr](https://cloud.githubusercontent.com/assets/953195/18325819/17d6330c-7511-11e6-8f0e-6a29be771624.jpg)

**Comment by asmitter** [comment]
@matijse @GabeJacobs We've pushed out an update that addresses the issue you were seeing. English should now be properly prioritised over japanese when both are specified in descending weight order via the Accept-Language header.
