### ISSUE TITLE
getrecommendations call keeps returning 500 error

### ISSUE THREAD

**Issue by snoek09** [spotify/web-api#300]
I keep getting a 500 error when calling `getrecommendations`;

```
HTTP/1.1 500 Internal Server Error
Content-Length: 0
Access-Control-Allow-Headers: Accept, Authorization, Origin, Content-Type
Access-Control-Max-Age: 604800
Access-Control-Allow-Credentials: true
Keep-Alive: timeout=600
Server: nginx
Connection: keep-alive
Cache-Control: private, max-age=0
Date: Sun, 04 Sep 2016 18:11:35 GMT
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, POST, OPTIONS, PUT, DELETE
```

**Comment by bosr** [comment]
👍

**Comment by bosr** [comment]
Hmm, it looks that some Spotify IP addresses always return the 500 status code. 

I have accumulated all the api.spotify.com IP addresses returned by google's dns 8.8.8.8, and some of them always return the appropriate answer, others always return the 500 status code. Here is the list :

errors on 194.132.198.149, 194.132.198.198, 194.132.197.198, 194.132.196.227, and 104.199.64.0

correct answers on 194.132.162.152, 194.132.162.201, 194.132.162.236

**Comment by asmitter** [comment]
We identified an issue in one of the datacentres which has now been resolved.
Do you still see the errors?

**Comment by snoek09** [comment]
All fine now. Thanks a lot! :+1:

**Comment by bosr** [comment]
Great thanks, i'll come back to you within an hour.  

Cheers

**Comment by bosr** [comment]
Works fine now, thank you!
