### ISSUE TITLE
Playback Control 

### ISSUE THREAD

**Issue by RenegadeTech** [spotify/web-api#302]
First of all, the issue I am having is related to all platform versions.

Given the use case of an Android Wear Device, Android Device and Desktop application; the android wear device shows the currently playing song on the Desktop application as if it was being played on the Android Device. 

The Android wear device shows all the interfaces as intended but as the Android device is not currently playing the controls do nothing for volume up or down. 

That being said, I can go backwards, forward and pause the song and it stops playing on the Desktop which is neat. However the bug is the following, if I press play again, the Android device will start playback instead of the desktop application.

I would gather this to be an issue with the model part of the application that does not store which application is running playback of music. I would assume that the pause button on the Android Wear device causes the application playback variable to be reset and then default back to the Android device.

**Comment by asmitter** [comment]
This tracker is for issues with our Web API.
It sounds like your issues are related to the Android client, for which you can find help on the Spotify support page https://support.spotify.com/ or in the community https://community.spotify.com/t5/Android/bd-p/spotifyandroid
