### ISSUE TITLE
TrackError: Account subscription status not Spotify Premium

### ISSUE THREAD

**Issue by mR12KL** [spotify/web-api#304]
I've seen a lot of people have this problem: Regardless of whether you have free or premium (tried on both types of accounts, I get an error. We think it's a server-side issue that has to be addressed by developers. As you can see, free and premium both are true, yet the TrackError persists.

`parseRestrictions() account: {"catalogue":"free","country":"DE"}
        parseRestrictions() catalogues: {"free":true,"premium":true,"shuffle":true,"commercial":true}
        sp/track_uri args: ["a28416f2c2a44b95a6ed08aa4c6e4384","f233d182b44626acf857391e74cfcb16d319972f"]
        sendCommand("sp/track_uri2", ["a28416f2c2a44b95a6ed08aa4c6e4384","f233d182b44626acf857391e74cfcb16d319972f"])
        storing callback function for message id 6
        sending command: {"name":"sp/track_uri2","id":"6","args":["a28416f2c2a44b95a6ed08aa4c6e4384","f233d182b44626acf857391e74cfcb16d319972f"]}
        WebSocket "message" event: {"error":[12,0,""],"id":6}
           - Error received: TrackError: Account subscription status not Spotify Premium`

**Comment by asmitter** [comment]
I don't recognise these messages or structure as part of our Web API or SDKs.
Are you using a wrapper? Or what library are you building against?

**Comment by thelinmichael** [comment]
Closing this due to lack of engagement. @mR12KL, please reopen it with the information asked for by @asmitter.
