### ISSUE TITLE
Search: Results not consistently ordered when using different limit arguments

### ISSUE THREAD

**Issue by sajsanghvi** [spotify/web-api#305]
When I GET this endpoint (limit=15)- 
https://api.spotify.com/v1/search?q=chill%20dinner&type=playlist&limit=15 
"Mellow Dinner" is the last result

When I GET this endpoint (limit=1)-
https://api.spotify.com/v1/search?q=chill%20dinner&type=playlist&limit=1
"Mellow Dinner" is the first and only result

Pretty confused

**Comment by JackRyder** [comment]
I think this is because it uses first in last out, so your first song will be the last song. I'd suggest if you need it to be at the front add all into a list of some sort and then use Array.reverse ;)

**Comment by asmitter** [comment]
A fix has now been rolled out for this bug. Thanks for the report, and let us know if you see any further strange behaviour.
