### ISSUE TITLE
api.spotify.com/v1/me/top/tracks does not work anymore

### ISSUE THREAD

**Issue by beacharoni** [spotify/web-api#307]
The spotify API 
**api.spotify.com/v1/me/top/tracks** 
… delivers constant old results with "short_term".

It delivers exactly the same results since at least 2016-08-10 (I know, because I saved the results of that day).

**Comment by beacharoni** [comment]
Yeah! Today it is working again. Thanks!

**Comment by beacharoni** [comment]
**api.spotify.com/v1/me/top/tracks**
"medium_term" and "long_term" should be fixed also, they still deliver old results...
THANKS!

**Comment by thelinmichael** [comment]
Closing this issue since it's been fixed. Thanks a lot for reporting and following up when it started working again @beacharoni!
