### ISSUE TITLE
Recommendations API not finding any tracks for most artist seeds

### ISSUE THREAD

**Issue by steinitzu** [spotify/web-api#308]
I noticed today that recommendations seem to have mostly stopped working. I have an app which iterates over a list of artists and fetches recommendations one by one and it seems that almost all the requests return empty result sets/   

To see the problem:  
Using the API console, trying to get recommendations based on Bob Dylan (with no other parameters) yields no results:
https://developer.spotify.com/web-api/console/get-recommendations/?limit=50&seed_artists=74ASZWbe4lXaubB36ztrGX

John Lennon seems to be working fine though
https://developer.spotify.com/web-api/console/get-recommendations/?limit=50&seed_artists=4x1nvY2FN8jxqAFA0DA02H

**Comment by joegester** [comment]
Hi steinitzu,

Thanks so much for reporting this.  I'm impressed by how quickly you noticed!  This problem is fallout from a poorly coordinated deploy.  Things should be fixed now.  Please let us know if you continue to see errors.

**Comment by steinitzu** [comment]
@joegester 
Great! Thanks for the quick response. I just happened to be tinkering with recommendations at the right time I guess :)  
Looks like everything is working now!

**Comment by omadume** [comment]
I just tried to use recommendations to get tracks using Ariana Grande's id in seed artists and it returned nothing
