### ISSUE TITLE
Frank Ocean songs not streaming

### ISSUE THREAD

**Issue by GabeJacobs** [spotify/web-api#309]
Hi guys,

Frank Oceans new album got removed from spotify last night http://pitchfork.com/news/68261-frank-oceans-blonde-no-longer-on-spotify/

It's back now, but none of the tracks stream from the iOS or Android SDK.

**Comment by asmitter** [comment]
I see you opened it in the [SDK tracker](https://github.com/spotify/ios-sdk/issues/753), so I'll close here.
