### ISSUE TITLE
Feature request: genre of track

### ISSUE THREAD

**Issue by davidescurria** [spotify/web-api#31]
I'm looking about the web-api and i didn't find, inside the "track" object, the genre of specified tracks. Is there a way to get it ? 
For example: track X from artist Y genre pop, track XX from artist YY genre rock and so on.

Thanks

**Comment by thelinmichael** [comment]
Hi @davidescurria. While Spotify doesn't expose genres for tracks, the closest you can get is to check the genre of the album the track is on. Genre is however only part of the full album object, and not the simple album object. To get the album's genre, first requesting the [Track metadata](https://developer.spotify.com/web-api/get-track/) to get the album URI, and continue to request [Album metadata](https://developer.spotify.com/web-api/get-album/). You can also get an artist's genres by calling the [Artist metadata](https://developer.spotify.com/web-api/get-artist/) endpoint. I hope this satisfies your use case!

**Comment by davidescurria** [comment]
Hi @thelinmichael Thanks for the quick response. I'm sure I will not find other problems. Good job

**Comment by gilesbutler** [comment]
Hey @thelinmichael is this because Spotify doesn't keep track of genres for individual tracks?

It seems strange not to expose this through the API. We're looking at migrating over from the iTunes API and they expose genres on a per track basis and it's key bit of info for us.

**Comment by thelinmichael** [comment]
@gilesbutler, I'm curious to know how you're using track genres, could you please elaborate a bit on that?

**Comment by gilesbutler** [comment]
@thelinmichael sure thing, it's because we have a music player and we won't to keep track of the most popular genres

**Comment by yozhik-man** [comment]
I'm also interested in this feature request. One album may include several genres of track.

**Comment by BloodShura** [comment]
A bit late to the party... but is there any hope for something like this in the future?

Currently, I not only need to retrieve the genre for a track (which I get through the artist's info endpoint), but also the year of the album... so, for a given track, I have to call another 2 Spotify API endpoints for getting the data I need. I really think this is bad for both sides!

As @gilesbutler also mentioned, these informations are delivered per track on iTunes API...

**Comment by jpmurray** [comment]
@BloodShura I'm not sure about the iTunes API's track level information on genre. I have access to the itunes EPF here (which is a database dump of the whole iTunes Store) and there is only genre information to the album level. Indeed, when you search the itunes API, the track object gives you "PrimaryGenre", which correspond to the album genre in the EPF data :(

Now, all of that being said, if I remember correctly, The Echo Nest did have information of a track level, and since Spotify bought The Echo Nest, I'd think it would not be that hard to expose. (As mentioned earlier in the conversation, Spotify do not _expose_ the information, it doesn't mean it doesn't have it).

I too am search for track genres, and I've searched high and low of accurate and reliable information, but not other API will give it. I'd hope that Spotify would see the competitive edge in exposing this data :(

**Comment by ohnosharks** [comment]
Also late to this party, but I've been looking for something similar, and found that the Last.fm API offers the top tags for tracks, but not genres. Not always reliable, not always specifically a genre, but it might work for some cases.

**Comment by shillshocked** [comment]
Would love to have easier access to genres for albums, artists and tracks!

**Comment by shillshocked** [comment]
I see the genre information is always empty on albums

**Comment by ShimmyMySherbet** [comment]
Yea, I'm also noticing that the genres property on the FullTrack is always empty. Any possible reason as to why?

**Comment by stephanebruckert** [comment]
@shillshocked It can be empty but it's not always empty. Same for artists. Basically need to be lucky.

My question is, if unavailable, can artist and album genres get added later in the future? @thelinmichael do you have any idea maybe? Thanks

**Comment by XandeGasperini** [comment]
Hello, i also am interested in track genre information, especially on "v1/tracks". Why it doesn't return an array of strings, containing the track genres?
Also, i figured out how to filter the "v1/tracks" search for just tracks in a specific genre, so Spotify should have this information easy to get and expose through "v1/tracks" API.
