### ISSUE TITLE
'Get Artists' -> all GENRES are empty arrays.

### ISSUE THREAD

**Issue by robertnabbe** [spotify/web-api#312]
Regardless of the artist, all artists consistently return an empty **genres** array (obj.artists[i].genres), whether calling for 1 single artist (https://api.spotify.com/v1/artists/{id}) or multiple (https://api.spotify.com/v1/artists?ids={ids}).

**Comment by thelinmichael** [comment]
Thanks @robertnabbe, we're investigating.

**Comment by asmitter** [comment]
@robertnabbe this should now be fixed.

**Comment by matthias-D** [comment]
I'm getting this issue again.

**Comment by vgalaktionov** [comment]
Same here

**Comment by schledererj** [comment]
Same here. Please fix.

**Comment by schledererj** [comment]
Looks like the Spotify team will be posting updates on this issue to #823.

**Comment by ryanfreemanio** [comment]
I am also getting this issue, artist object returns empty genres array
