### ISSUE TITLE
Token swap service - HTTP 400 invalid_grant from time to time

### ISSUE THREAD

**Issue by greencoppercompany** [spotify/web-api#313]
Hi!

We're using the iOS and Android SDK since a while (at least 2 years) and we've implemented token swap service as describe in Spotify documentation.
We're receiving from time to time an HTTP 400 when trying to swap the user token with the following json response:

`{"error":"invalid_grant","error_description":"Invalid authorization code"}`

We would like to minimize our log error report and we're looking for a way to better understand why this is happening for a small percentage of our calls. Is there any way to have a better overview or more info regarding this error code?

Thanks a lot.
Loïc

**Comment by matijse** [comment]
My guess: https://developer.spotify.com/news-stories/2016/07/25/app-ready-token-revoke/

**Comment by asmitter** [comment]
If this in when refreshing tokens then yes, it is likely that the user has revoked their token and you should remove any data you have associated with their session and allow them to re-auth as a new user to your service.

**Comment by asmitter** [comment]
Closing as >1 month without comment. Please reopen or create a new issue if you have further problems not related to users revoking their token.
