### ISSUE TITLE
Get a time expired HTTPS stream for a track

### ISSUE THREAD

**Issue by paultag** [spotify/web-api#315]
I can't figure out how to get some sort of HTTP(hopefully S!) stream of the audio for a track from the Spotify API. What's the endpoint?

Could the docs on that endpoint be added in a  noticeable place on the docs? I'm having a hard time finding it.

Thanks!

**Comment by jscholes** [comment]
This isn't possible with the web API.  You can only stream tracks using the iOS, Android and Libspotify SDKs (see #57).

**Comment by paultag** [comment]
Wait, seriously? How does the HTML Web player do it?

**Comment by paultag** [comment]
Also isn't `libspotify` super EOL?

**Comment by thelinmichael** [comment]
Hey @paultag! As @jscholes, this is covered by #57. Libspotify is considered deprecated, and Spotify's Web Player is using a solution based on Flash.

**Comment by paultag** [comment]
Wait, so there's seriously no way to stream music, @thelinmichael?

**Comment by thelinmichael** [comment]
@paultag, that's correct. You could still use the [mobile SDKs](https://developer.spotify.com/technologies/) to stream full tracks, or use the 30 second previews available through the [Get a Track endpoint](https://developer.spotify.com/web-api/get-track/).
