### ISSUE TITLE
Error returned when accessing oauth with urn:ietf:wg:oauth:2.0:oob return url

### ISSUE THREAD

**Issue by lukaszg84** [spotify/web-api#316]
When using oauth2client python library (https://github.com/google/oauth2client) and redirect url set to:
urn:ietf:wg:oauth:2.0:oob
(this is to be used when script is started remotely and user should copy and paste authorization key)

https://accounts.spotify.com/authorize?client_id=d76c4c94809e48d3bcaf194b7a32b787&response_type=code&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&access_type=offline&scope=playlist-modify-public

spotify web page returns following error:

Error
Oops! Something went wrong, please try again or check out our help area.

urn:ietf:wg:oauth:2.0:oob is added to the whitelisted redirect uris list.

oauth2client works, when redirect url is set to some other whitelisted domain, but then key has to be copied from the url part instead from a browser.

**Comment by hughrawlinson** [comment]
Hey @lukaszg84 - I can't reproduce this issue. Is it still occurring for you?

**Comment by lukaszg84** [comment]
Yes it is still occuring. When using:
urn:ietf:wg:oauth:2.0:oob
as redirect url

it returns:
INVALID_CLIENT: Invalid redirect URI
when url is not added to thedeveloper console

and
Error
Oops! Something went wrong, please try again or check out our help area.
when it is added

**Comment by lukaszg84** [comment]
@hughrawlinson in order to test that, you would need to create a regular oauth client and use that urn... string as redirect_url parameter.
When it is used with google.com, the code is displayed on a special page (hosted by google) - see screenshot:

![screenshot](https://user-images.githubusercontent.com/22541451/33765653-2ea24546-dc1a-11e7-8eba-846d165af2cb.png).

**Comment by hughrawlinson** [comment]
Ah @lukaszg84 - I misunderstood before, I thought the redirect uri was your own uri scheme. We don't currently support the oob oauth flow. We're aware of the feature request though, and tracking it in #168. We'll post any updates we have there.
