### ISSUE TITLE
Object model for Track Audio Analysis

### ISSUE THREAD

**Issue by daturkel** [spotify/web-api#317]
The documentation for `audio_features` notes that one return value is:

> `analysis_url`    - `string` - An HTTP URL to access the full audio analysis of this track. An access token is required to access this data.

Sure enough, the `audio_features` API works as described and gives us an analysis url, in the format `https://api.spotify.com/v1/audio-analysis/{SOME_ID}`, and that URL is indeed a valid API call that returns a big json file. 

However, there appears to be no current documentation about the output of this API call. Indeed, `audio-analysis` does not appear in the [web api endpoint list](https://developer.spotify.com/web-api/endpoint-reference/), and the return object is not listed in the [object model docs](https://developer.spotify.com/web-api/object-model/). The `audio-analysis` API does not appear in any of the RAML files in these repo either. (In fact, even `audio-features` is missing from the [schema directory](https://github.com/spotify/web-api/tree/master/specifications/raml/schemas).)

I searched for documentation on the schema and interpretation of the `audio-analysis` API call results, and the best thing that I could find was a PDF on the Echo Nest website (not linked to here as I'm not sure if the document is meant to be public-facing; it was Google-able though) that appears to document the equivalent method for the (now deprecated) Echo Nest API. 

This issue is a request for up-to-date documentation of the `audio-analysis` API and return object, ideally located on the Spotify dev site.

**Comment by thelinmichael** [comment]
Thanks a lot for raising this @daturkel. 

We've added the endpoint to the RAML specification, the [API Console](https://developer.spotify.com/web-api/console/get-audio-analysis-track/?id=06AKEBrKUckW0KREUWRnvT), and the [Developer site](https://developer.spotify.com/web-api/get-audio-analysis/). We may add an object model for it as well, stay tuned for that. Hopefully the audio features endpoint is enough for your use case.

**Comment by daturkel** [comment]
Thank you for starting work on this! Even just the pretty-printed output in the documentation example is a decent start for my parsing out exactly what this call returns. Based on how big/complex the returned object is, I can understand how it would be a big undertaking to document it—though I'd still love to see it!

**Comment by AgentCid** [comment]
I had the same question about seeing the object model for this endpoint, and I was able to track down an old copy of the [Echo Nest API reference](https://web.archive.org/web/20160528174915/http://developer.echonest.com/docs/v4/_static/AnalyzeDocumentation.pdf) for their version of the endpoint, which looks to be very similar, if not identical. It looks usable on its own, but it would be more useful if the info here made its way to the developer site. Hope this helps.

**Comment by reidpd** [comment]
What exactly do all the properties mean in parameters? I would really love to expose this capability more, but have no idea what a value of '5' means for `track.key`, or what to get from array of floats represented by `segments[x].pitches`, or what any other property values actually signify in real-life terms.

**Comment by awoehrmann** [comment]
I am trying to filter audio features by item, getting back an array of Spotify IDs. 
E.g. getting an array of Spotify IDs of all songs with a danceability between 0.735 and 0.740. I think that this was possible in the old Echo Nest API. Is there still a way of doing this in the new Web-Api?

**Comment by c-schuhmann** [comment]
The PDF containing the documentation for the Echo Nest version of the Analyzer contains a great part of all information, but not everything. Any updates on this?

**Comment by arirawr** [comment]
I'm going to close this issue in favour of #947, which covers documentation of audio features and analysis. Please follow that issue for updates!

**Comment by arirawr** [comment]
As mentioned on #947 - this has now been updated! Check out the new documentation here: https://developer.spotify.com/documentation/web-api/reference/tracks/get-audio-analysis/

**Comment by daturkel** [comment]
Thanks so much @arirawr ! Can't wait to play around with this again.
