### ISSUE TITLE
400 Bad Request when requesting access token

### ISSUE THREAD

**Issue by franrios** [spotify/web-api#318]
Hello, I'm trying to develop an app to access user's playlist in react native. According to the following diagram, I complete successfully steps 1,2 and 3. 

![image](https://cloud.githubusercontent.com/assets/7302131/19020164/9628a120-88a0-11e6-91fa-4e7c6cc9207c.png)

The problem come in step 4 when I POST the code, redirectUri, grant_type, client_id and client_secret to https://accounts.spotify.com/api/token. This snippet returns 

`<html><body><h1>400 Bad request</h1>↵Your browser sent an invalid request.↵</body></html>↵`

```
const newBody = {
        code: query.code,
        redirect_uri: redirectUri,
        grant_type: 'authorization_code',
        client_id: clientId,
        client_secret: clientSecret
      }

      fetch('https://accounts.spotify.com/api/token', {
        method: 'POST',
        body: JSON.stringify(newBody),
        headers: JSON.stringify({
          'Authorization': 'Basic ' + base64.encode(clientId + ':' + clientSecret)
        })
      }).then((response) => {
        console.log({response})
        return response.text()
      }).then((response) => {
        console.log({response})
      })
```

**Comment by jsimonsson** [comment]
Hey, first off you do not need client_id and client_secret in the "newBody", ie the POST data.

Second, when you set the body you are posting a json by the looks of it, you are supposed to use the regular POST way of sending it; ie in the form of application/x-www-form-urlencoded.

Also, not being familiar with your xhr setup but I would expect headers to actually accept a regular JS object and not a stringified version (ie it should do the proper conversion itself and iterate over own properties and insert into xhr request). If you are running this in an environment where you can debug the actual request that would be helpful, to see that you actually get a proper header set. 

But my guess is that you are posting a JSON blob where it expects it as application/x-www-form-urlencoded parameters.

**Comment by asmitter** [comment]
Closing as 1 month with no comments. If you follow the instructions but still have an issue, please reopen.
