### ISSUE TITLE
Support Resource Owner Password Credentials OAuth flow

### ISSUE THREAD

**Issue by gopi1989** [spotify/web-api#319]
Hi all,

I am creating an android app,In that app uisng the spotify music library features.My intension is by using the client credential(UserName and Password) generate the access_token from that android app to access the available Spotify web API.
In spotify web API,there is three kind of authorization,but no one authorization methods are using client credential(UserName and Password)
It is posssible to generate the access_token without client_credentials.client_id?

Thanks in Advance for the Valuable help !!

Regards,
Gopi Krishnan.R

**Comment by jscholes** [comment]
> It is posssible to generate the access_token without
client_credentials.client_id?

No.  This would completely defeat the point of using OAuth in the first
place.

**Comment by gopi1989** [comment]
Hi jscoles,

               Thanks for your reply.
Regards,
Gopi Krishnan

**Comment by gopi1989** [comment]
Hi jscoles,

In case if i generate the access token for the user using the Spotify Android SDK, It is possible to use the Available Web API .I read out the document ,it says it is possible to use the Web API ,I am just asking for the confirmation

Regards,
Gopi Krishnan

**Comment by thelinmichael** [comment]
Yes, that's possible to do @gopi1989. 

I'd be happy to change this feature request to instead be about the [Resource Owner Password Credentials](https://tools.ietf.org/html/rfc6749#section-1.3.3) flow, which Spotify doesn't support.

> The resource owner password credentials (i.e., username and password)
   can be used directly as an authorization grant to obtain an access
   token.  The credentials should only be used when there is a high
   degree of trust between the resource owner and the client (e.g., the
   client is part of the device operating system or a highly privileged
   application), and when other authorization grant types are not
   available (such as an authorization code).

**Comment by thelinmichael** [comment]
Given that this OAuth flow is only considered appropriate in cases where the client is highly trusted by the resource owner it isn't useful to keep this enhancement request open. Applications developed by third parties will have to continue to use one of the [three different OAuth flows](https://developer.spotify.com/web-api/authorization-guide/) available.
