### ISSUE TITLE
There is no sound when play the preview url in iPad

### ISSUE THREAD

**Issue by alanchen1988** [spotify/web-api#32]
We team use the iOS SDK to get the track preview url. Then play the 30s song, but, there is no sound. However, the progress is moving.

Issue found on April 14th 2015.

Steps to reproduce: 
***** We use the API to get the preview url from the track.
[SPTRequest requestItemAtURI:[NSURL URLWithString:@"spotify:track:0CKxrnF9KplS21LTjkkqsW" withSession:nil callback:^(NSError *error, SPTTrack *track) {
            /// Now you have a track
            if (error != nil) {
                NSLog(@"*** Album lookup got error %@", error);
                return;
            }
            NSLog(@"previewURL=%@", track.previewURL);
        }];

***** Then play the preview url (https://p.scdn.co/mp3-preview/1f74e8c41c7e1d1823382ab78aece316c24f3bad), there is no sound.

Expected behaviour: The progress is moving, but can not hear the sound.

Actual behaviour: The progress is moving and can hear the sound.

**Comment by JMPerez** [comment]
Hi @alanchen1988. Since this is not an issue with the Web API itself  but the iOS SDK (the preview url is playable and it has sound), I suggest you report the issue in that repo.

For the moment I will close this issue.
