### ISSUE TITLE
Getting 200 ok when trying to save more than 9995 songs but the save fails

### ISSUE THREAD

**Issue by Foldalake** [spotify/web-api#320]
I wanted to verify that my app behaves correctly if the user tries to save more than 10000 tracks, but ran into some trouble with the web api.

The [documentation for Save Tracks for Current User](https://developer.spotify.com/web-api/save-tracks-user/) says that there is a max limit of 10.000 saved songs and after that, you will receive 403 Forbidden if you try to save more tracks. However, when I have saved 9995 songs, I cannot save more tracks, but I get a 200 Ok response as if the save request worked.

**Steps to reproduce:**
1. Save 9995 songs in the Spotify desktop client.
2. Save one or more songs, using either the web api or the desktop client.

**Expected:** The song is saved.

**Actual behaviour:** The song is not saved, but I get 200 ok when using the web api.

(Just thought I'd mention that if i save more songs in the desktop client, they will appear as saved in Your Music, but will not show up if I get the list of saved tracks using the web api. The songs exceeding 9995 will disappear if i restart the desktop client)

**Comment by hughrawlinson** [comment]
Hey @Foldalake. Sorry for the delay in getting back to you on this! Can you still reproduce the issue?

**Comment by hughrawlinson** [comment]
Haven't heard from you so I'll close this. Feel free to reopen if it's still an issue for you.

**Comment by Foldalake** [comment]
Hi @hughrawlinson, sorry I haven't checked in for a while. Yes, I still get 200 OK when I try to add more than 10000 songs - but now the limit is actually 10000 instead of 9995, so at least that bit is fixed :)
