### ISSUE TITLE
PLAYLIST SORT BY DATE ADDED - REAL TIME CONNECT TO FRIENDS

### ISSUE THREAD

**Issue by joshbhill123** [spotify/web-api#325]
I am writing to propose new features for Spotify on a mobile device either IOS or Android.

Firstly, you should have the ability to sort songs within playlists by date added as it is frustrating constantly scrolling down to listen to my latest songs on a playlist on a mobile device. I acknowledge this feature is available on desktop version of Spotify.

Secondly, there should be a feature that enables your profile to connect to friends and visa versa so others can "piggyback" each other live streaming music.

Good musiking!!!

**Comment by asmitter** [comment]
Hi. These ideas relate to Spotify generally, and this issue tracker is for the Web API only.
Ideas for the Spotify product can be posted in our community here: https://community.spotify.com/t5/Ideas/ct-p/newideas
