### ISSUE TITLE
Rate limits for client id authenticated calls

### ISSUE THREAD

**Issue by julianostarek** [spotify/web-api#326]
The documentation states that, in comparison to unauthenticated requests, the rate limits are improved when the api call is somehow authenticated, e.g. with client id. In my case I only want to use the api to retrieve music metadata, so there's no authentication necessary for that use case. The request's sender will always vary, as the use case is an android app, and therefore I wonder whether client id authenticated calls are still calculated on ip basis or on client id basis. In other words, will I have more or less available calls per device in a specific timeframe using the client id authentication?

**Comment by thelinmichael** [comment]
Hey @julianostarek! 

> I wonder whether client id authenticated calls are still calculated on ip basis or on client id basis

Great question. The answer is that we're looking at both the requester's IP and the `client_id` used in the request. We strongly recommend that you use an access token when making requests.

Not only is the default rate limit higher when making authenticated requests, but this way you avoid being rate limited in case there are a temporary peak in unauthenticated requests. If you _do_ get rate limited, it's in your application's control to solve the issue. On top of that, you don't miss out on the new [application stats](https://developer.spotify.com/news-stories/2016/09/26/statistics-insights-web-api-apps/) we've added recently. Finally, it's great for us maintaining the platform as we get a better understanding of how the APIs are being used. 

Unless you've read it already - Our [User Guide](https://developer.spotify.com/web-api/user-guide/#rate-limiting) contains some information about how to decrease the number of requests, and how to handle being rate limited.
