### ISSUE TITLE
Control playback on a device from another device

### ISSUE THREAD

**Issue by Avinodh** [spotify/web-api#327]
Trying to create a web abstraction for playback which users could use to control playback on a single host's device.

For example:
- Host A has a track playing on his/her Spotify on an iPhone
- User B authenticates through a new web interface, and then wants to say, pause, the track playing on Host A's device.

Is there any way of currently doing this (assuming User B can potentially even authenticate as Host A through a web UI)

**Comment by hughrawlinson** [comment]
Hi @Avinodh - we've got a feature request ticket for the APIs this would depend on already - #15. Thanks for getting in touch!
