### ISSUE TITLE
2 songs will play simultaneously. WEB CLIENT

### ISSUE THREAD

**Issue by rsweis62** [spotify/web-api#328]
Any time i skip a song or the song play the next track the next 2 songs will play simultaneously. Only happens on the web client. Looks like when the next song is queued and the get request fails it will play the next song in the list. Which is fine but i think there is retry logic that will try to play the failed song resulting in 2 songs playing at the same time.

**Comment by hughrawlinson** [comment]
Hey @rsweis62, this issue tracker is actually for the Web API rather than any Spotify players. I'll pass this bug report on to the team responsible, thanks!
