### ISSUE TITLE
Inbox message retrieval endpoint

### ISSUE THREAD

**Issue by juanuicich** [spotify/web-api#329]
Are there any plans to implement any inbox endpoints? Specifically, I am interested in retrieving the incoming messages for a user, to pick the recommendations sent by friends.

**Comment by hughrawlinson** [comment]
Hey @juanuicich,

No current plans, but we'll take this issue as a feature request! Thanks 😄

**Comment by juanuicich** [comment]
Thanks @hughrawlinson. I contacted the platform team through Twitter and they recommended I added the feature request here. Any way to retrieve incoming messages or the user activity (for the logged in account) would enable me to build some interesting apps I have planned.

**Comment by arirawr** [comment]
Sorry to ping on an old issue, but I'm going to close this, as the in-app inbox no longer exists.
