### ISSUE TITLE
github pull-request like feature in playlists

### ISSUE THREAD

**Issue by juanlarrambebere** [spotify/web-api#330]
Hi guys how are you?

Im a developer from MercadoLibre in Uruguay and i really like Spotify. I thought I would be nice to have a concept similar to github pull-requests when talking of playlists. 

The idea is to be able to suggest a friend to add a song to a playlist. Supose I have a friend Bob and he has a really cool playlist i'm following. Bob's playlist has three songs A,B and C but i would love it if includes a 4th one D, so i would simple suggest him to add D to the playlist and he could "merge" it or not.

Thanks!!

**Comment by jscholes** [comment]
This is already somewhat implemented within the Spotify ecosystem.  A
user can choose to make a playlist public, private or collaborative.  In
collaborative mode, a playlist can be modified by any user who's
following the playlist.  That's where the good news ends, however.  As
is quickly establishing itself as the norm, Spotify have decided not to
allow this functionality through the web API and only the owner of a
collaborative playlist can make changes to it.

**Comment by thelinmichael** [comment]
Thanks for jumping in @jscholes, and for linking to the related issue ticket regarding collaborative playlists.

@juanlarrambebere, if you're referring to a feature that you want implemented in Spotify's apps, the best place to do so is at [Spotify's community forums](https://community.spotify.com). The scope of this repository is limited to [Spotify's web API](https://developer.spotify.com/web-api). 

If you're however using the web API already - I'd challenge you to build this feature yourself. All your application needs is an access token signed by the playlist's owner to read and modify playlist, and your application can take care of the rest. It's an interesting idea, and I'd love to see it implemented!
