### ISSUE TITLE
Get gender information

### ISSUE THREAD

**Issue by Gdewilde** [spotify/web-api#332]
It would be handy to include gender information in the /me endpoint.

**Comment by hughrawlinson** [comment]
Thanks for the enhancement request, we'll consider it! 😄

**Comment by chriswong929** [comment]
+1 for this feature!

**Comment by davellaj** [comment]
This feature would be helpful. I would like to select female related artists

**Comment by thelinmichael** [comment]
@davellaj, to clarify - this feature request is for allowing a user to give an application permission to read their gender information, not for applications to read artists' gender information.

**Comment by Gdewilde** [comment]
@thelinmichael @hughrawlinson Any update on this? Thanks.

**Comment by davellaj** [comment]
@thelinmichael thanks for the clarification!

**Comment by arirawr** [comment]
Hey all,

As per our [new developer support process](https://github.com/spotify/web-api#creating-an-issue), any feature requests that have no plans to be considered in the next 6 months will be closed as wontfix.

We do not have any plans to implement this in the next 6 months and thus will close as wontfix.

We encourage you and other members of the community to continue to share use cases and your support for this feature, as it helps us prioritize features going forward. You will be able to comment on this issue even after it is closed. We will also post any updates here relating to this suggestion when they happen.
