### ISSUE TITLE
Specifying a particular image in the field filter

### ISSUE THREAD

**Issue by jasonhcarr** [spotify/web-api#333]
I'm having trouble finding the appropriate format for specifying the url of a particular image size in the "fields=" filter.  Everything else seems to be a relatively simple nested parentheses structure for specifying fields, however the images are within an array and i can't seem to target the particular object within that array that I want to receive. Tips?

**Comment by thelinmichael** [comment]
@jasonhcarr, filtering can only be done on attribute names as not on objects within an array. You'd have to loop through the image array to check for the image size you need.
