### ISSUE TITLE
Playlist widget does not trigger other tracks besides track #1

### ISSUE THREAD

**Issue by richsancho** [spotify/web-api#336]
If you have a look at the playlist widget on this page, it only triggers the first song:

https://developer.spotify.com/technologies/widgets/examples/

This used to function as intended - when a user selects track two, track two plays. Please advise asap, thanks.

also, I am on Chrome, osX El Capitan.

**Comment by asmitter** [comment]
Thanks for the report. This would be an issue with the Spotify Play Button so I've passed it on to the relevant team and they'll investigate.
This issue tracker is specifically for issues on the Web API, so I'll close this issue.

**Comment by richsancho** [comment]
Hello asmitter,

I work with Viacom, and I am trying to integrate the widget into experiences on our site. I appreciate you passing along the bug info.

Is there a way for me to a) track the progress of the bug and b) get in contact with someone on the tech team at Spotify working specifically on the embeddable widget?
