### ISSUE TITLE
Track search unexpected 404 when "year:" range is greater than 2 years

### ISSUE THREAD

**Issue by ruslanskorb** [spotify/web-api#337]
Hi, guys!

Thank you for your work on the Spotify API.

Unfortunately, we are faced with a problem in the Web API, which looks like a bug. If you try to specify `year:` range that is greater than 2 years, you will get the error 'Not found'.

https://api.spotify.com/v1/search?limit=20&offset=0&q=year%3A2013-2016&type=track

```
{
  "error": {
    "status": 404,
    "message": "Not found."
  }
}
```

If the years range is equal or less than 2 years it works without any errors.

https://api.spotify.com/v1/search?limit=20&offset=0&q=year%3A2014-2016&type=track

```
{
  "tracks": {
    "href": "https://api.spotify.com/v1/search?query=year%3A2014-2016&offset=0&limit=20&type=track",
    "items": [
      ...
    ],
    "limit": 20,
    "next": "https://api.spotify.com/v1/search?query=year%3A2014-2016&offset=20&limit=20&type=track",
    "offset": 0,
    "previous": null,
    "total": 16034626
  }
}
```

Some time ago it worked without any problems in both cases.

**Comment by asmitter** [comment]
Hi @ruslanskorb - thanks for the report. We're looking into it.

**Comment by asmitter** [comment]
Hi @ruslanskorb,
We made some improvements under the hood which should address this issue. Let us know if you see any further problems.

**Comment by ruslanskorb** [comment]
Thanks @asmitter!
