### ISSUE TITLE
May I use the Spotify API to write an program to tag my local music files

### ISSUE THREAD

**Issue by ElCap1tan** [spotify/web-api#339]
I know that is not really a issue but it don't know where else to ask so I hope I'll get an answer here.
So here's my question: Does Spotify permit to use there DB/API for my own program so I can tag my music files with some of the metadata from Spotify?

Thanks in advance

**Comment by hughrawlinson** [comment]
Hey @ElCap1tan 😄  For a non-commercial application, this seems fine, but there are some restrictions about using metadata. If you want to be on the safe side, please see our [Developer Terms of Use](https://developer.spotify.com/developer-terms-of-use/), which all users of the Spotify Web API must comply with. Happy hacking!
