### ISSUE TITLE
Error getting playlists for category in browse

### ISSUE THREAD

**Issue by ronniehillgren** [spotify/web-api#34]
One specific request to one of the browse endpoints always seems to return an error lately (for the past 20 days or so). We get a "502: Bad gateway" error, even though the category (latin) is listed when getting all categories for that country (US) from the API.

Here is the specific request that returns an error:
https://api.spotify.com/v1/browse/categories/latin/playlists?country=US

**Comment by thelinmichael** [comment]
Thanks @ronniehillgren, we're looking into it.

**Comment by thelinmichael** [comment]
A fix has been deployed, thanks again for reporting.
