### ISSUE TITLE
502 Bad Gateway error?

### ISSUE THREAD

**Issue by maxiedaniels** [spotify/web-api#340]
I'm still trying to figure out what exactly is triggering a 502 Bad Gateway error, but it seems to be when I pull the display_name of a user. If I retry the same call, it will sometimes work, and sometimes return 502 again.

This wasn't happening yesterday, and I can't figure out if this is some issue with what I'm doing or if it's on Spotify's end... any ideas?

**Comment by asmitter** [comment]
If the error code coming back starts with a 5, it's probably us.
Which endpoint are you hitting, and roughly how often are you seeing the error?

**Comment by asmitter** [comment]
@maxiedaniels Good news: We found a misbehaving machine and fixed it up. Our graphs look good so I'll close the ticket, but please reopen if symptoms persist.

**Comment by janyksteenbeek** [comment]
Getting loads of 502's here as well while using the search endpoint

**Comment by bhargav3** [comment]
@happy-machine thanks for that. I think we can't get past 10k offset. Spotify team - is there a fix?

**Comment by moritzlauper** [comment]
getting 502 gateway with the reorder playlist tracks endpoint.

**Comment by sethpoly** [comment]
getting 502 bad gateway with getAlbum endpoint
