### ISSUE TITLE
Track search returns no result for existing track.

### ISSUE THREAD

**Issue by sgloutnikov** [spotify/web-api#341]
Search API returns bad results for following track: Desiigner - Timmy Turner. This is also true for the Spotify MacOS client. The real track exists here: spotify:track:3NJG6vMH1ZsectZkocMEm0

- Searching for "artist:Desiigner track:Timmy Turner" returns an empty result.
https://api.spotify.com/v1/search?query=artist%3ADesiigner+track%3ATimmy+Turner&offset=0&limit=20&type=track

- Searching for "Desiigner Timmy Turner" returns the wrong tracks.
https://api.spotify.com/v1/search?query=Desiigner+Timmy+Turner&offset=0&limit=20&type=track

One more track with bad results: Darwin - Dessert. Real track: spotify:track:0mxoXsr14ILAYcXZBMJcOs

- https://api.spotify.com/v1/search?query=artist%3ADarwin+track%3ADessert&offset=0&limit=20&type=track
- https://api.spotify.com/v1/search?query=Darwin+Dessert&offset=0&limit=20&type=track

**Comment by asmitter** [comment]
Hi @sgloutnikov 
You are making some typos in your requests.

The track by Desiigner is called "Tiimmy Turner" (with two "i"s), and can be found here:
https://api.spotify.com/v1/search?query=artist%3ADesiigner+track%3ATiimmy+Turner&offset=0&limit=20&type=track

In your second example, the artist is "Dawin" without the "r". The track Dessert can be found here:
https://api.spotify.com/v1/search?query=artist%3ADawin+track%3ADessert&offset=0&limit=20&type=track

**Comment by sgloutnikov** [comment]
Yikes, that's embarrassing. Will make sure to get my sleep before posting again. Thanks!

**Comment by asmitter** [comment]
No problem 😄
