### ISSUE TITLE
401 Unauthorized when trying to grab playlists..

### ISSUE THREAD

**Issue by maxiedaniels** [spotify/web-api#342]
I've pulled a client_credentials token and while I can access other parts of the API, I can't seem to pull playlist information. It's definitely a public playlist, yet I'm getting 401 Unauthorized. Am I just misunderstanding something? I apologize, this may not be a bug, but I don't know where else to post.

*Edit*
I've been checking and the rspotify gem uses client_credentials, so I don't think that's my issue.

For example, this works:
    `curl -I -s -X GET "https://api.spotify.com/v1/users/#{testUser}" -H "Authorization: Bearer {#{@accessToken}}"`

This does not:
    `curl -I -s -X GET "https://api.spotify.com/v1/users/#{testUser}/playlists/#{testPlaylist}?fields=href,name,owner(!href,external_urls),tracks.items(added_by.id,track(name,href,album(name,href)))" -H "Authorization: Bearer {#{@accessToken}}"`

**Comment by asmitter** [comment]
Hi @maxiedaniels 
Does it work when doing the same call but without specifying the fields parameter? i.e.
 `curl -I -s -X GET "https://api.spotify.com/v1/users/#{testUser}/playlists/#{testPlaylist}" -H "Authorization: Bearer {#{@accessToken}}"`

**Comment by thelinmichael** [comment]
@maxiedaniels, please reopen if you're still experiencing this issue.
