### ISSUE TITLE
Ordering of new-releases is unknown

### ISSUE THREAD

**Issue by nguyenchr** [spotify/web-api#344]
for the endpoint `https://developer.spotify.com/web-api/get-list-new-releases/`

I seem to be getting a weird ordering of releases

e.g. First item (Drake - Fake Love) has a release date of 24Oct
Then there are a few pages of releases for the 4th Nov
Then it moves on to older releases

Is there any reason why that Drake release is returned out of order of release date, is it featured or something? or is the new releases list not ordered by release date, I could find any documentation on the ordering so I assumed release date as that's what made sense to me

**Comment by asmitter** [comment]
Hi @nguyenchr 
The ordering follows the ordering used in our clients, so some releases may be brought closer to the start of the list to make them more discoverable.
I've added a note to the documentation for future developers. Thanks for flagging!
