### ISSUE TITLE
authorisation on a headless embedded system - how?

### ISSUE THREAD

**Issue by Bharji** [spotify/web-api#345]
I'm developing a headless embedded platform and want to be able to access Spotify. Initial setup (probably using a mobile app) will embed the username and password in the platform. Given this, what is the preferred way to obtain an authorisation token? Note - the system is headless (no display of any kind) and can't serve a webpage.

Thanks

**Comment by hughrawlinson** [comment]
Hey @Bharji,

Ideally you shouldn't store users usernames and passwords. You should get the user to log in with oauth, and use the oauth token to authorize. You can use the [Authorization Code Flow](https://developer.spotify.com/web-api/authorization-guide/#authorization-code-flow) to authenticate your user and get the access token and refresh token, and have your headless system refresh your access token using the refresh token. I wrote [a bash script](https://gist.github.com/hughrawlinson/1d24595d3648d53440552436dc215d90) that you can use to easily get access tokens and refresh tokens (uncomment line 50). Make sure to read the script comments to understand how to provide it with your client_id and client_secret (available on [developer.spotify.com](https://developer.spotify.com/my-applications/#!/applications)), and to make sure that you authorize the correct scopes!

Hope that helps! Feel free to keep in touch and ask for help, I'm happy to answer any questions!
