### ISSUE TITLE
Request creator's display name in playlists request

### ISSUE THREAD

**Issue by jtvd78** [spotify/web-api#346]
I am displaying a list of a user's playlist, which I get from /users/{user_id}/playlists. The response only seems to have the user's id within the returned owner object, and but it doesn't provide the display name of the user. Currently, I simply display the user id of the playlists's creator, but now I would like to display their actual name. 

Without having to individually request the display names of each user after downloading the playlist, is there a way to request the user's display_name along with the rest of the data when requesting playlists?

Thank you

**Comment by hughrawlinson** [comment]
I'll pass this on as a feature request to the responsible team. Thanks for getting in touch!

**Comment by jtvd78** [comment]
Is there any update on this issue? The documentation page for this resource states that the response format contains simplified playlist objects. The documentation for simplified playlist object states that it contains a [user object](https://developer.spotify.com/web-api/object-model/#user-object-public). This user object is supposed to contain a display_name field, but that field is never returned with the request. 

Is the display_name field intentionally left out, because by reading the documentation it seems that the field should be sent.

**Comment by mmontag** [comment]
Seems to me this should be considered a bug. Thanks for reporting.

**Comment by hughrawlinson** [comment]
@mmontag you're right, this is a bug.

**Comment by jtvd78** [comment]
Any update with this bug?

Thanks

**Comment by jtvd78** [comment]
Is there any progress on this issue? I hate to keep asking, but I would really appreciate any kind of update on the bug.

Thank you

**Comment by arirawr** [comment]
This issue should now be resolved. Thanks for your report!

Please feel free to reopen if you continue to see this issue occur.
