### ISSUE TITLE
Cover art

### ISSUE THREAD

**Issue by mangeboyen** [spotify/web-api#348]
Why doesn´t the Cover art work at this page and many other pages..? Anyone got an idea..?

https://developer.spotify.com/technologies/widgets/examples/two/

**Comment by hughrawlinson** [comment]
Hey @mangeboyen - we're aware of the issue and we're working on it. Thanks for reporting!

**Comment by hughrawlinson** [comment]
@mangeboyen a fix will be rolled out soon!

**Comment by JMPerez** [comment]
@mangeboyen That playlists seems to have an issue and doesn't return a valid playlist image. It's a corner case we are investigating. In the meantime, we have replaced the playlist used in [the example page for the Spotify Play Button widget](https://developer.spotify.com/technologies/widgets/examples/two/).
