### ISSUE TITLE
Retrieve "friend activity" feed 

### ISSUE THREAD

**Issue by fgblanch** [spotify/web-api#349]
I see the feature in the app but it would be great to have access to it via API. It would be great for example to implement "Listen to a friend activity" feature. So a user can DJ to his friends. Thanks

**Comment by hughrawlinson** [comment]
Thanks for the feature request @fgblanch. I've passed it on to the relevant team.

**Comment by jayceecam** [comment]
+1!

**Comment by hughrawlinson** [comment]
I've realised this is a duplicate of #83, so I'll close this issue and make any updates on the other issue.
