### ISSUE TITLE
Content Security Policy Error while login via OAuth

### ISSUE THREAD

**Issue by turbulem** [spotify/web-api#350]
Today I faced an error with your API:
After user login on decision page "Okay" button doesn't fire redirect to app-specific url-scheme URL.

In Chrome console I can see error after each click on "Okay" button:
Refused to connect to '{my-app-id}://#access_token={token_value}&token_type=Bearer&expires_in=3600' because it violates the following Content Security Policy directive: "default-src 'self'". Note that 'connect-src' was not explicitly set, so 'default-src' is used as a fallback.

p.s. {my-app-id} and {token_value} are values

**Comment by hughrawlinson** [comment]
Hey @turbulem - we think we've fixed this issue. Could you check if it's working again? If not, I'll chase it up.

**Comment by turbulem** [comment]
Yes, thank you, now it works as expected for all values of redirect_uri except the ones with capital letters.

**Comment by eito** [comment]
What is the solution to this? We are running into a similar situation. Is there a best-practice or does the redirect URI need to be added explicitly to the CSP?
