### ISSUE TITLE
Registration from Countires unsuported by spotify

### ISSUE THREAD

**Issue by GeorgeHosuAdswizz** [spotify/web-api#351]
Is there currently a way to register you application from a country which isn't offered Spotify user services ?

**Comment by hughrawlinson** [comment]
Hey @GeorgeHosuAdswizz - it's a requirement at the moment that a Spotify developer must be a Spotify user (free or premium). This has the effect that people in countries that Spotify hasn't launched in can't register Spotify apps. I'll bring this up with my colleagues and see if there's possibility to change this, but at the moment it looks unlikely. I'll be sure to update you here if anything changes!
