### ISSUE TITLE
User switch interface within family premium

### ISSUE THREAD

**Issue by haan-z** [spotify/web-api#353]
Since using family premium, our home devices are used by all family members to play Spotify on. Now we constantly are logging out the previous user and loggin in ourselves. An interface at startup (and after logout) with "who's listening" and the 5 user names next to each other would help. Compare loggin in to Netflix with multiple users within one account. #

**Comment by hughrawlinson** [comment]
Hey @haan-z - this issue tracker is for issues with the Spotify Web API. To request features for the Spotify service, please contact customer support.
