### ISSUE TITLE
Advanced search option

### ISSUE THREAD

**Issue by haan-z** [spotify/web-api#354]
Currently I have made a number of playlists (a.o. a monthly new music list shared with friends), containing about 3000 songs. Sometimes I know an album is already in one of the lists, but don't know in which. To find out, I have to open them one by one and scroll. Would be great to have an "advanced search" option available with boxes to tick like: "search within playlists" or "search within friends' playlists".

**Comment by hughrawlinson** [comment]
This issue tracker is for issues with the Spotify Web API. For feature requests for the Spotify service, please contact customer support.
