### ISSUE TITLE
Attribute "public" of a playlist at null

### ISSUE THREAD

**Issue by blackarcanis** [spotify/web-api#356]
Hi,
I would like to display in my interface if the playlist is "public" or "private".
But it seems there's a "null" value instead of "true" or "false"... 
That's a first issue and the second is playlist i follow doesn't have public at true, but at null... strange thing for a playlist i can follow ? ;)

Can you please take a look at this ?
Thanks

**Comment by hughrawlinson** [comment]
Hey @blackarcanis, thanks for the report! We'll need a bit more info in order to figure out the problem. Could you give us an example of the query that yields you this result? If you could give us a curl syntax request we'd likely be able to diagnose the issue.

**Comment by blackarcanis** [comment]
For example this playlist wich i can follow on Spotify main page : 
https://play.spotify.com/user/spotify_france/playlist/3Mg9gqLBLtzlGYti43mlDO

```
stdClass Object
(
    [collaborative] => 
    [external_urls] => stdClass Object
        (
            [spotify] => http://open.spotify.com/user/spotify_france/playlist/3Mg9gqLBLtzlGYti43mlDO
        )

    [href] => https://api.spotify.com/v1/users/spotify_france/playlists/3Mg9gqLBLtzlGYti43mlDO
    [id] => 3Mg9gqLBLtzlGYti43mlDO
    [images] => Array
        (
            [0] => stdClass Object
                (
                    [height] => 
                    [url] => https://u.scdn.co/images/pl/default/729397a27e0f0dcca1e7526b432fb69e3a543412
                    [width] => 
                )

        )

    [name] => Fin de journée
    [owner] => stdClass Object
        (
            [external_urls] => stdClass Object
                (
                    [spotify] => http://open.spotify.com/user/spotify_france
                )

            [href] => https://api.spotify.com/v1/users/spotify_france
            [id] => spotify_france
            [type] => user
            [uri] => spotify:user:spotify_france
        )

    [public] => 
    [snapshot_id] => 2Sjt4qxkJenVhOnRioS8hMvTYghBAN1awzXMv9mF+ouBecHok0Ym2rBgSwxmh96N
    [tracks] => stdClass Object
        (
            [href] => https://api.spotify.com/v1/users/spotify_france/playlists/3Mg9gqLBLtzlGYti43mlDO/tracks
            [total] => 50
        )

    [type] => playlist
    [uri] => spotify:user:spotify_france:playlist:3Mg9gqLBLtzlGYti43mlDO
)
```

As you can see "public" property is empty.

Now i get this playlist for example wich i can found on Spotify : 
http://play.spotify.com/user/nikerunclub/playlist/4RpqiyPxEHFdpdDuRkgrS5

```
stdClass Object
(
    [collaborative] => 
    [external_urls] => stdClass Object
        (
            [spotify] => http://open.spotify.com/user/nikerunclub/playlist/4RpqiyPxEHFdpdDuRkgrS5
        )

    [href] => https://api.spotify.com/v1/users/nikerunclub/playlists/4RpqiyPxEHFdpdDuRkgrS5
    [id] => 4RpqiyPxEHFdpdDuRkgrS5
    [images] => Array
        (
            [0] => stdClass Object
                (
                    [height] => 
                    [url] => https://u.scdn.co/images/pl/default/4c1df49214436621a63508c8e3210c568800b986
                    [width] => 
                )

        )

    [name] => NIKE RUNNING SPEED RUN
    [owner] => stdClass Object
        (
            [external_urls] => stdClass Object
                (
                    [spotify] => http://open.spotify.com/user/nikerunclub
                )

            [href] => https://api.spotify.com/v1/users/nikerunclub
            [id] => nikerunclub
            [type] => user
            [uri] => spotify:user:nikerunclub
        )

    [public] => 1
    [snapshot_id] => 19Jw5EhkYkM0GKoyYgkBRTyj4L8LSu0EFS289SMbzoJrCxmbMA+8r9o3eLamOf/A
    [tracks] => stdClass Object
        (
            [href] => https://api.spotify.com/v1/users/nikerunclub/playlists/4RpqiyPxEHFdpdDuRkgrS5/tracks
            [total] => 68
        )

    [type] => playlist
    [uri] => spotify:user:nikerunclub:playlist:4RpqiyPxEHFdpdDuRkgrS5
)
```
Here the "public" property is set at 1.
Why this difference for both public playlist i can follow ?

**Comment by asmitter** [comment]
I tried both examples in the Web API console, and both returned "public: true"
https://developer.spotify.com/web-api/console/get-playlist/?playlist_id=3Mg9gqLBLtzlGYti43mlDO&user_id=spotify_france
https://developer.spotify.com/web-api/console/get-playlist/?playlist_id=4RpqiyPxEHFdpdDuRkgrS5&user_id=nikerunclub
Can you reproduce?

**Comment by blackarcanis** [comment]
Hi,
Thanks for your reply.
I see the issue... When you get a playlist directly thanks the endpoint "get-playlist" is can see the "public: true".
But this value is not the same thanks the endpoint "get-current-user-playlists" for me i get "public: false".

For reproduce, follow the playlist (playlist_id=3Mg9gqLBLtzlGYti43mlDO&user_id=spotify_france) and look at the playlist endpoint "get-current-user-playlists".

**Comment by asmitter** [comment]
I see the confusion:
The "public" flag on a playlist is related to whether the playlist is shown in the "Public Playlists" tab for that user.
Now, when you follow a playlist, you are also adding it to your list of playlists. You may not want playlists that you follow to automatically end up in the list people see in your profile, so you can choose to have any playlist you follow automatically set to private _in your list_. (This may be the default. I forget.)

In your example, those playlists are both public in the list for the users who created them, so getting them in isolation you will see `public:true`. If you get the list of playlists for the owning users, you will also see them in there with `public:true`.
If you see them as `public:false` for your user, you are following them privately. You can test this out by going to the Spotify desktop client, right-clicking the playlist and selecting "Make Public". That playlist will then be shown in your profile under "Public Playlists" and if you do another request via the web api for your list of playlists you will see it with `public:true`.

Hope that helps clarify. I can see how it can be misleading, but it does give everyone more flexibility with what gets shown in their profile page.

**Comment by blackarcanis** [comment]
@asmitter thanks for those details, it was a little confuse yes ;)
But I understand the choice for flexibility. I will work with it.
