### ISSUE TITLE
Value for playlist name is null when retrieving user's playlists

### ISSUE THREAD

**Issue by VirUZI** [spotify/web-api#358]
When making a request to https://api.spotify.com/v1/users/sonymusichk/playlists I recieve the playlist name for spotify:user:spotify:playlist:37i9dQZF1DZ06evO3DbIU8 in the list as null.

The issue can currently be reproduced in the API console. If I follow the playlist with another account and make an API request to get the playlists for that account I get the name "This Is: The Chainsmokers" as expected.

**Comment by jstlnd** [comment]
@VirUZI Hi, this indeed looks weird. We'll investigate and get back to you.
Thanks for your report!

**Comment by jstlnd** [comment]
@VirUZI We have deployed a fix for this issue now.
Please get back to us if you have issues.
Thanks again for your report!
