### ISSUE TITLE
Explicit Key for Albums

### ISSUE THREAD

**Issue by ryandt** [spotify/web-api#36]
Currently, it looks like the only way to weed out explicit or non-explicit album versions is by iterating through each track in each album to check if an explicit track exists. It would be great if there could be an "explicit" key at the album level to better manage returning a single version of an album in search results (e.g. how the Spotify app operates).

**Comment by TylerFisher** [comment]
+1

**Comment by thelinmichael** [comment]
Let's track this issue in #296.
