### ISSUE TITLE
POST request new playlist 400 error parsing JSON

### ISSUE THREAD

**Issue by Pau1fitz** [spotify/web-api#360]
I am trying to create a playlist using the Spotify API and am receiving the following error:

```
    {
      "error" : {
        "status" : 400,
        "message" : "Error parsing JSON."
      }
    }
```

I am following the https://developer.spotify.com/web-api/create-playlist/ that says to use the following curl request

`    curl -X POST "https://api.spotify.com/v1/users/thelinmichael/playlists" -H "Authorization: Bearer {your access token}" -H "Content-Type: application/json" --data "{\"name\":\"A New Playlist\", \"public\":false}"   `

My code looks like this

```
    $.ajax({
       url: 'https://api.spotify.com/v1/users/{id}/playlists',
       method: "POST",
       data: {
         name: "test",
         public: "false"
       },
       headers: {
         'Authorization': 'Bearer ' + access_token,
         'Content-Type': 'application/json'
       },
       success: function(response) {
         console.log(response);
       }
     });

```
Can anyone advise what I am doing wrong?

**Comment by jsimonsson** [comment]
Can you try to not quote "false" ie write false instead as the basic type in javascript? Try that first and tell us if it worked or not :)

**Comment by jsimonsson** [comment]
Nevermind, tried with quoted "false" and it did work.

**Comment by jsimonsson** [comment]
ok, actually you are not posting json I think :) try assigning data: with data: JSON.stringify({name: "test", public: false}) instead

**Comment by Pau1fitz** [comment]
nice man, that worked! thanks!

**Comment by Pau1fitz** [comment]
@jsimonsson thanks for that. I am trying to make the same post request in Node but am getting the Error 400 message again, saying error parsing json.

My code looks like this. Is there a different approach when using `request`?

```
        var playlistOptions = {
            url: 'https://api.spotify.com/v1/users/1114819007/playlists',
            headers: {
                'Authorization': 'Bearer ' + access_token,
                'Content-Type': 'application/json'
            },
            data: JSON.stringify({name: "test", public: false})
        }

        request.post(playlistOptions, function(err, resp, body){
            console.log(body)
        });
```

I also tried setting `json: true`
```

        var playlistOptions = {
            url: 'https://api.spotify.com/v1/users/1114819007/playlists',
            headers: {
                'Authorization': 'Bearer ' + access_token
            },
            json: true,
            data: JSON.stringify({name: "test", public: false})
        }

        request.post(playlistOptions, function(err, resp, body){
            console.log(body)
        });
```
