### ISSUE TITLE
Adding playlist into playlist

### ISSUE THREAD

**Issue by italocuzziol** [spotify/web-api#361]
It would be nice if we have the possibility of adding playlist into another playlist. This would be useful on the following cases:

1.) You can't shuffle the songs of two or more playlists. If you, for example, are in a party and two or more friends decide to put together their playlists and shuffle the songs contained in then, it's not possible, unless you create a new playlist and add song by song to it. The more songs contained in playlists, the harder.

2.) It is not possible to listen to the songs contained in two or more different playlists. If you, for example, want to listen to the songs of Pearl Jam's playlist and Queen's playlist, you need to add, song by song, all of them of both playlists into a new one.

These cases would be easily attended, since you'd be able to put all together two or more playlists into a single new one.

Also, it would be nice if we had the possibility of choosing if updates on child playlists would automatically reflect on the parent playlists.

**Comment by hughrawlinson** [comment]
Hey @italocuzziol - this change would require a change in behavior to the spotify client, which we don't handle, so I'll close this ticket. If the functionality ever gets added to the client, we'll consider this again. Thanks!

**Comment by laurencemooney** [comment]
can I suggest in the desktop app selecting all songs from one playlist and dragging them into the second one.
