### ISSUE TITLE
Retrieve list of followed users

### ISSUE THREAD

**Issue by jakob-haider** [spotify/web-api#362]
one can delete a followed user by id
* `DELETE "https://api.spotify.com/v1/me/following?type=user&ids=exampleuser01"`

but one can not retrieve a list of followed users
* `GET "https://api.spotify.com/v1/me/following?type=user"`

**Comment by hughrawlinson** [comment]
Hey Jakob - this issue has already been reported (see #4), so I'll close this as a duplicate and you can follow discussion on that ticket. Thanks!
