### ISSUE TITLE
Original release year on Track object instead of Album only

### ISSUE THREAD

**Issue by mjonik** [spotify/web-api#363]
A similar issue has already been reported here: https://github.com/spotify/web-api/issues/359

Problem: 
I would like to play all my saved pop songs of the 80's.

There query, using the spotify client would look like this: `year:1980-1989 genre:pop`

I won't find Eddy Grants' Electric Avenue, released in 1982, because I have saved the song from the Album "100 Essential Hits, Vol. 2", released in 2010.

The original album "Killer on the Rampage" is not available for my market.

(For the advanced music listener) the orignal release year of a song is one of the most important attributes for selecting the music (right after the genre). If the same song is on more than one album or has been remastered, it still has to hold the orignal release year and preferably the original released album.

**[EDIT]**
This problem does not appear to be a Web Api problem but a general one.
Thats why I additionally created an "idea" here: https://community.spotify.com/t5/Idea-Submissions/Metadata-Make-release-year-of-tracks-available/idi-p/1507654

**Comment by hughrawlinson** [comment]
Hey @mjonik, thanks for the issue. As it's being tracked as a Spotify feature request I'll close this issue so that we can re-evaluate once that request had been resolved. Thanks!
