### ISSUE TITLE
Add NPM Package 'spotify-graphql' to the librairies page ?

### ISSUE THREAD

**Issue by wittydeveloper** [spotify/web-api#364]
Hi Spotify team,

I just wrote a graphQL client for the Spotify Web API in Node.js

It allow the following request type : 

```js
import SpotifyGraphQLClient from '../src/spotify-graphql';
// config is an object like :
//   {
//     "clientId" : "",
//     "clientSecret" : "",
//     "redirectUri" : "",
//     "accessToken" : ""
//   }
import config from './config';

SpotifyGraphQLClient.create(config).query(`
  {
    track(id: "3W2ZcrRsInZbjWylOi6KhZ") {
      name
      artists {
        name
      }
    }
  }
`).then(result => {
  console.log(JSON.stringify(result));
});

// Print : 
// {
//   "data": {
//     "track": {
//       "name": "You & Me - Flume Remix",
//       "artists": [
//         {
//           "name": "Disclosure"
//         },
//         {
//           "name": "Eliza Doolittle"
//         },
//         {
//           "name": "Flume"
//         }
//       ]
//     }
//   }
// }

```

Is there any requirements to have the library on the following page ? ⬇️ 
https://developer.spotify.com/web-api/code-examples/#wrappers

Here is the repo URL : https://github.com/thefrenchhouse/spotify-graphql

Cheers,

**Comment by hughrawlinson** [comment]
Hey @wittydeveloper! Awesome work on this library. It looks great. To get on that page, we usually do a code review and look for a project using the package to see how it works in a practical setting. I'll plan to review it soon :) Thanks!

**Comment by wittydeveloper** [comment]
Hi @hughrawlinson,

I'm currently working on a music-based project that will use this library (http://github.com/thefrenchhouse/expander/)

I'll keep you updated when i'll have refactored the “expander" project to use this library so you can see a usage case ;) 

Thanks !

**Comment by wittydeveloper** [comment]
Hi @hughrawlinson ,

I've  done a repo with examples of using the library ! 
https://github.com/thefrenchhouse/spotify-graphql-examples

I would love to have a feedback :)

**Comment by hughrawlinson** [comment]
Added! Thanks for the awesome work 😄

**Comment by wittydeveloper** [comment]
Thanks a lot @hughrawlinson ! 😸
