### ISSUE TITLE
Mark audiobook-title when already played

### ISSUE THREAD

**Issue by nhaug** [spotify/web-api#365]
#### Expected behaviour:
All tracks from audiobooks should be marked as "already heard" ... If i switch listening audiobook and normal music, i always get sad, because i have to find the last played track. 

#### Actual behaviour:
no special marking

**Comment by asmitter** [comment]
Hi @nhaug - this sounds like a feature request for Spotify generally rather than the Web API. Please contact customer support or post your idea in the community forums.
