### ISSUE TITLE
Get Many Track Audio Analysis Endpoint?

### ISSUE THREAD

**Issue by 0xNF** [spotify/web-api#366]
It would be really useful if we could get multiple track analyses in a single request. 
Given the size of the data transferred I'm not optimistic about it being implemented, but it would be neat.

**Comment by hughrawlinson** [comment]
Thanks for the feature request!

**Comment by bih** [comment]
Hello @0xNF,

Great news! Looks like we now have an API for this - see [Get Audio Features for Several Tracks](https://developer.spotify.com/documentation/web-api/reference/tracks/get-several-audio-features/) 🎉
