### ISSUE TITLE
How to presave an album using Spotify web api

### ISSUE THREAD

**Issue by Pau1fitz** [spotify/web-api#367]
I have just seen on the Laura Marling website there is an ability to pre-save an album once it is released - https://live.lauramarling.com/. When you click on pre-save you are redirected to this link where it is then possible to get notified when the tracks/album are added to your playlist - http://presave.kls.io/albums/f216f5f0-0a83-4fbd-b8e6-eb15d86937f3/eb15d86937f3/

I know how to access a user's playlists through the API, create playlists etc. but what I am unsure of is how you know when an album will be released and to add to the user's playlists and notify them when it is released.

Does anyone have any idea? Is there an endpoint for non-released music?

**Comment by asmitter** [comment]
Hi @Pau1fitz 
We don't have an endpoint for yet-to-be-released music and it's unlikely that we will anytime soon.
Nice campaign though, and I quite like Laura Marling *<clicks "pre-save">* :)

**Comment by Pau1fitz** [comment]
@asmitter based on this article it would suggest there is some way to do this?

http://musically.com/2016/11/29/laura-marling-fans-can-pre-save-her-new-album-on-spotify/

**Comment by asmitter** [comment]
I saw that too. I guess as they are the label they already have all the data needed to implement this. We don't have - or currently aim to provide - a generic way to get information on unreleased albums via the public Web API.

You solution sounds like it would work, with the added advantage that you could do the check specifically to the individual user's market.

**Comment by Pau1fitz** [comment]
@asmitter  ok, cool! that's all good to know.

Final question --- so a user comes to the page and authenticates the 'app'. They then sign up to 'save the new album'. To write to a user playlist I will need an access token. so if I store the current access token in a database alongside the user, and 6 months later when the album is released and I want to update the user's playlist, can I just refresh the old access token?

Does this question make sense?

**Comment by asmitter** [comment]
Correct - you can use the refresh token to gain a new access token (providing that within those 6 months or however long it is the user doesn't actively revoke access).
It's important to do any storage of access/refresh tokens securely so that they cannot be intercepted or otherwise obtained by others. I recommend spending some extra time and effort when building your app to ensure no-one can steal the tokens.

**Comment by Pau1fitz** [comment]
@asmitter I am having some issues exchanging the `refresh_tokens` for `access_tokens`. I have seen in the docs that:

> Authorization	Required. A valid access token from the Spotify Accounts service: see the Web API Authorization Guide for details. The access token must have been issued on behalf of the user.  

In my example this is what I am doing. A user signs up that they want to presave an album. I then save their `playlistId`, `userId` and `refresh_token` in a database. Following this I loop through the database and get all the users and add these to an array with objects that look like this `{userId: xxxxxx, playlistId: xxxxxxx, access_token}`

See code below. Firstly I hit the /get-users endpoint, and then the add-tracks endpoint. The `request` in `add-tracks` returns an error saying 

```
{ error:
   { status: 401,
     message: 'This request requires authentication.' } 
}
```

It looks as if my access_token is being created as this is what my `users` array looks like (with one user) when I hit the `get-users` endpoint.

```
[ { userId: '1xxxxxxxx7',
    playlistId: '4xxxxxxxxxxxxxxxxDkuX0',
    accesstoken: 'xxxxxxxxxx-xxxxxxxxx-xx-xxxxxx-xxxxxxxx-xxxxxxxxxx-xxxxx-xxxxxxx' } ]
```

The `access_token` is 247 characters long so it appears that it is correct.

Here is my code below:

```
app.get('/get-users', function (req, res) {
	connection.query('SELECT * from users', function(err, rows, fields) {
	    if(err) console.log(err);
	    users = [];
	    for(var i = 0; i < rows.length; i++) {
	    	refresh_token = rows[i].refreshToken;
	    	userId = rows[i].userId;
	    	playlistId = rows[i].playlistId;
	    	var authOptions = {
		        url: 'https://accounts.spotify.com/api/token',
		        headers: {
		            'Authorization': 'Basic ' + (new Buffer(client_id + ':' + client_secret).toString('base64'))
		        },
		        form: {
		            grant_type: 'refresh_token',
		            refresh_token: refresh_token
		        },
		        json: true
		    };

    	    request.post(authOptions, function(error, response, body) {
		        if (!error && response.statusCode === 200) {
		            var access_token = body.access_token;
		            users.push({userId: userId, playlistId: playlistId, accesstoken: access_token});
		            console.log(users)
		        }
		    });    
	    }
	    res.send('users obtained');
	    connection.end();
	});
})

app.get('/add-tracks', function (req, res) {
    for(var i = 0; i < users.length; i++) {
        request.post({
	        url: 'https://api.spotify.com/v1/users/' + users[i].userId + '/playlists/' + users[i].playlistId + '/tracks?uris=spotify%3Atrack%3A4iV5W9uYEdYUVa79Axb7Rh,spotify%3Atrack%3A1301WleyT98MSxVHPZCA6M',
	        headers: {
	            'Authorization': 'Bearer ' + users[i].accessToken
	        },
	        method: 'POST',
	        json: true
        }, function(err, resp, body){
        	console.log(body)
        })	
    }
    res.send('tracks added');
})
```

**Comment by asmitter** [comment]
`users.push({userId: userId, playlistId: playlistId, accesstoken: access_token});`

`users[i].accessToken`

Check your camel-casing on accessToken :)

**Comment by Pau1fitz** [comment]
BOOM! @asmitter  That second set of eyes is invaluable! Thanks very much!

**Comment by asmitter** [comment]
@Pau1fitz no problem.

![Tips Hat](http://i.imgur.com/5ajbeWB.gif)

**Comment by then2s** [comment]
do you have the final version of this that I can download in a quick zip file? thank you

**Comment by thalesblite** [comment]
Hey @asmitter the pre-save function on spotify WebApi still not available?

**Comment by jscholes** [comment]
Presaving isn't a Spotify feature.  It's a feature implemented by an artist, record label, etc. which simply saves an album to your library once it's been released.  Before the album has been released, the website like the one mentioned here won't touch your Spotify account.  In other words it's a glorified cronjob.

Thus, you can easily implement this using either the suggestions discussed above, or by using an alternative API to obtain album release dates and then setting up a scheduled task to save them once they're available.

**Comment by thalesblite** [comment]
Thanks @jscholes ! So I just add the music on the user's playlist and when the music is released spotify automatically display in the user's playlist?

**Comment by Pau1fitz** [comment]
@thalesblite I implemented this a couple of years ago. What I did was create a form where a user signed up to presave the album and stores their Spotify username and refresh token. Then when the album was released I ran a job that used the refresh token to get an access token which then allowed me to add the presaved songs to the user’s Spotify account.

**Comment by jscholes** [comment]
@thalesblite no.  You run an application on your server which saves the album to the user's Spotify library on the release date of the album.
