### ISSUE TITLE
Can't use logical terms in query string. 

### ISSUE THREAD

**Issue by nadavoosh** [spotify/web-api#368]
Issue found on November 29, 2016.

#### Endpoint(s):
* `GET /v1/search`

#### Scope(s):
* None (application is not using authentication)

#### Steps to reproduce:
1. Open the API Console
2. Call the `search` endpoint with a `query` that includes any of the words `AND` `NOT` `OR`. For example https://developer.spotify.com/web-api/console/get-search-item/?q=ONE+AND&type=track

#### Expected behavior:
Search results are returned. 

#### Actual behaviour:
404 Not Fond

**Comment by hughrawlinson** [comment]
Thanks for letting us know, we'll take a look

**Comment by asmitter** [comment]
I can only replicate this when you have the operator as the last word in the search, which makes no sense as a search term anyway. What would you expect it to return?

As you linked to, "q=ONE+AND" return 404 but
"q=ONE+AND+TWO" returns results 
"q=ONE+NOT+TWO" returns results 
"q=ONE+OR+TWO" returns results 

Putting the logical term at the end of the query string cannot be parsed, which is to be expected.
Closing for now but please reopen if it occurs for queries which should be parseable.

**Comment by nadavoosh** [comment]
I would expect to be able to search for songs with the word "and" in them? I'm not trying to use these as operators, but as search terms.

**Comment by nadavoosh** [comment]
It actually seems like a capitalization issue. For instance, searching for The Beatles' _And I Love Her_ fails if you search for `AND+I+LOVE+HER`, but succeeds if you use `and+I+love+her`. Pretty unexpected IMO, but it's your API.

**Comment by asmitter** [comment]
Uppercase is used to enable operators without removing the ability to use "and", "not" etc. as search terms. As stated in the [Search documentation](https://developer.spotify.com/web-api/search-item/):

> Note that operators must be specified in uppercase otherwise they will be treated as normal keywords to be matched.

So in summary, make sure your search term is lowercase and any operators are uppercase.
Hope that clarifies.
