### ISSUE TITLE
Return preview_url start time

### ISSUE THREAD

**Issue by DustinJSilk** [spotify/web-api#370]
Would like to be able to know exactly when the preview of tracks start so that we can sync it to the audio analysis data.
This means we can show audio visualisations with the preview mp3 playing without having to manually analyse the sample live.

If this is possible in any other way already, im yet to find it, would appreciate any advice.

**Comment by hughrawlinson** [comment]
Hey @DustinJSilk, I'll pass this on as a feature request to the relevant team. Thanks!

**Comment by DustinJSilk** [comment]
That would be great, thanks! @hughrawlinson

**Comment by arirawr** [comment]
Hey @DustinJSilk,

As per our [new developer support process](https://github.com/spotify/web-api#creating-an-issue), any feature requests that have no plans to be considered in the next 6 months will be closed as wontfix.

We do not have any plans to implement this in the next 6 months and thus will close as wontfix.

We encourage you and other members of the community to continue to share use cases and your support for this feature, as it helps us prioritize features going forward. You will be able to comment on this issue even after it is closed. We will also post any updates here relating to this suggestion when they happen.
