### ISSUE TITLE
Old Style Button

### ISSUE THREAD

**Issue by SilverNightstone** [spotify/web-api#372]
If possible please create a button that allows users to switch back and forth between the old style of Spotify and the newer. As I find the new and recent version is rather sudden and difficult to maneuver throughout as playlists pause and restart the buttons of shuffle and loop when the user chooses a song. Even if it the button is only for a short period of time, I rather liked the old version as it seemed in no need of a huge update to change the whole platform.

Kind Regards and Thanks

**Comment by thelinmichael** [comment]
@SilverNightstone, this question is better suited for the [Spotify Community website](https://community.spotify.com) since it doesn't relate to Spotify's web API, which this Github repository is meant for. Thanks!
