### ISSUE TITLE
Retrieve Playlists' Folders

### ISSUE THREAD

**Issue by mklschreiber** [spotify/web-api#38]
Currently there is no information published about the folder in which the playlist is located. So the third party can just show all playlists in a flat list. It would be a great improvement if we could show the same structure like the official spotify application does. 

For example:

Playlist Folder A
....Playlist Folder A-a
........Playlist Test
....Playlist Folder A-b
........Playlist Test2
Playlist Folder B
....Playlist Test3

**Comment by jmilloy** [comment]
I just wanted to second this enhancement request. The task I am most interested in is reordering playlists in a folder, and neither the folder structure nor (I believe) playlist order are accessible through the web api.

**Comment by thelinmichael** [comment]
@jmilloy, the order of the playlists is maintained and should be the same as in the Spotify applications.

**Comment by jmilloy** [comment]
@thelinmichael Okay. How can I change the order of the playlists? Right now the best I can do is delete the playlists and create them again (from last to first).

Note that I'm not talking about the track order in a particular playlist.

**Comment by thelinmichael** [comment]
@jmilloy, the Web API unfortunately doesn't support changing the orders of the playlists, so the only workaround would be to do what you're doing.

**Comment by triplef** [comment]
+1

A lot of our users are using folders to organize their (extensive) Spotify libraries/playlists, and not having folder support in our app makes for an inferior and confusing experience as compared to the official Spotify apps.

For us it would be sufficient to have a "parent playlist" property that we can use to build the tree of playlists.

**Comment by whyhellothere** [comment]
I completely agree with @triplef 

We need folders. This includes use of the API in the Sonos app. Currently my 800+ folders are a long list and it lags.

**Comment by whyhellothere** [comment]
I should also add @thelinmichael I've created 2 open forum posts on @spotify and @sonos 

https://en.community.sonos.com/music-services-and-sources-228994/spotify-folders-gone-ios-v54-and-v55-6732153

https://community.spotify.com/t5/Help-Other-Partners-Windows/Sonos-Controller-v5-5-no-more-folders/m-p/1219871

**Comment by whyhellothere** [comment]
@mkl87 @thelinmichael @jmilloy @triplef I feel strongly about not having folders anymore. So I created this: http://bringbackfolders.com/

Share if you agree please!

**Comment by thelinmichael** [comment]
Hey @whyhellothere! There's an Idea post on the Spotify Community site that'll serve as a better place to discuss folders in the Sonos app. Go to it [here](https://community.spotify.com/t5/Live-Ideas/Sonos-Playlists-Restore-the-folder-structure-in-the-web-API-so/idi-p/1223003).

**Comment by rawdlite** [comment]
+1 for folders support in the API.

Are there any plans on supporting this?

**Comment by whyhellothere** [comment]
@rawdlite - nope! great, huh? also, the Spotify forums are complete shit. I DM'd them directly and they said they do not reply on their forums until it hits a certain number of "kudos". There are about 3 threads already, one of which has about 1600. 

Bottom line: if you want an answer, the best bet is by asking Sonos (they reply in their forums) or by DM'ing either company. 

As far as I know both know its an issue, but haven't many any public statements with plans for change.

**Comment by fredriklaason** [comment]
Folders please :+1:

**Comment by willdunning** [comment]
:+1: Folder support please.

**Comment by varazir** [comment]
+1 on folders

**Comment by bmoers** [comment]
+1 please extend the folder API

**Comment by bart-eijk** [comment]
+1. I would love to see the Spotify Web API support folders.

**Comment by mattbroussard** [comment]
+1

**Comment by Gregg8** [comment]
Seriously, no folders? I have tons of them. It's the only way to make any sense of them all. What a mess they become as a single list! This is a crucial feature as far as I (and many others) am concerned. It's such a nice API, but so brain dead in this area. Why oh why oh why?

**Comment by jayhubau** [comment]
+1 for folders support in the API.

**Comment by willhutch** [comment]
+1 for folders support as well - why is this missing??

**Comment by hbraasch** [comment]
Its been more than a year since the start of this problem. What the heck! Again... Why is this still missing?

**Comment by hbraasch** [comment]
A bit more...

I’ve been following this issue (Retrieve Playlists' Folders) on the GitHub issue tracker for a while and seriously need some assistance.

Anyone, please provide me with an email address or phone number of the developers on Spotify side (in some country) so I can get BEHIND the reason why this feature cannot be implemented in due time. The whole SONOS community (I'm just a user) have been screaming for it, but I do not think SONOS is going about it the right way (or not reporting sufficiently).

Spotify... please give us a some proper feedback. I’m a programmer myself and would like to explain to my peers in a language they can understand. Otherwise… I cannot see any reason why the API still lacks this interface, other than that Spotify INTENTIONALLY wants to cripple all other developers of client apps.

And please do NOT refer me to your other support webpages, these are useless and are easily ignored.

**Comment by jayce-leathers** [comment]
I want to second this. I'm interested in developing an app to organize playlists intelligently by genre and need folders to do so. Right now it looks like I'll be stuck using libspotify to do this. Hopefully whatever api replaces libspotify (spotify api help pages say they're replacing it in 2017) keeps the folder management.

**Comment by MusicPartner** [comment]
I second this also. We are a professional background Music provider and are creating new services using Spotify (and more business for Spotify) so this really needs to get sorted!

**Comment by klihelp** [comment]
Folders in API 
please :-)

**Comment by pafodie** [comment]
+1 Spotify, I beg you!

**Comment by avinassh** [comment]
Spotify, please add folders support?

**Comment by kgowru** [comment]
+1 spotify, need this!

**Comment by jayce-leathers** [comment]
@hbraasch Did you ever get a hold of the spotify devs?

**Comment by seahorsepip** [comment]
Another +1 for the month May.

**Comment by xavierhb** [comment]
+1

**Comment by klihelp** [comment]
+1 for June

**Comment by fosron** [comment]
+1

**Comment by klihelp** [comment]
Museum of +1s

**Comment by akej74** [comment]
Could we please get an official comment from Spotify on this topic?

**Comment by hughrawlinson** [comment]
Hi @akej74 and everyone - we've been aware of this feature request for some time, and we're keeping it open so that developers can continue to express their interest. We've chosen to focus on some more heavily requested features, like #12, #15, and #20, and have addressed them with [our new Spotify Connect APIs](https://developer.spotify.com/news-stories/2017/04/10/new-endpoints-beta-web-api-connect/), and [recently played tracks](https://developer.spotify.com/news-stories/2017/03/01/new-endpoint-recently-played-tracks/) endpoint. We understand that a playlist folder API would be very useful _to a rather small group of users and developers that use Spotify's playlist folder feature_, but we don't have any related announcements to make in the near future.

**Comment by eyanson** [comment]
+1

**Comment by gabriel-roth** [comment]
Strongly urge you to implement folder support in the web API. The kind of serious users most likely to use third-party apps are also most likely to want to organize their music. 

I'm not surprised that only a few users make use of Spotify's playlist folder feature. Maybe that's because it's not very well implemented in the official apps?

**Comment by moritzsternemann** [comment]
I still need this for a great app I‘m working on...

Oh and btw, I‘d love to work on this as an intern at Spotify ;)

**Comment by arirawr** [comment]
@moritzsternemann - https://www.spotifyjobs.com/students/ 🙊

**Comment by OliverPearmain** [comment]
I'm desperate for this also.

1+

**Comment by cacothi** [comment]
Hi guys, any review on this item?

This feature was raised in 2015 and nothing has happened till now? I couldn't find anything on Spotify API and also on Playlist Object that would say the parent folder for that playlist:

https://developer.spotify.com/web-api/object-model/#playlist-object-full

**Comment by arirawr** [comment]
Hi @cacothi!

This issue, as with all of our long open issues, is an open feature request.  An issue being open is not an indication that we're working on the feature, only that we're interested in seeing the demand, and compelling example use cases that we could enable. The current state is that we're aware that it's a feature that has a lot of demand, but for a variety of reasons have no immediate plans to release it.

We keep feature requests open so that we can continue to gauge demand for a feature over time, and regularly prioritize highly demanded features - see #302 #57 #260, and many others for examples of this.

**Comment by Jovaage** [comment]
+1

Full folder api support is something I need for my app and would like to see implemented.

**Comment by cacothi** [comment]
Thanks for the return @arirawr

**Comment by rvf148** [comment]
+1 folders please

**Comment by mjh421** [comment]
Another request for folder support please

**Comment by soheilpro** [comment]
+1

**Comment by arirawr** [comment]
Hi developers! We know you want to show support for this issue, but please refrain from writing comments containing only +1, as this sends unnecessary notifications to everyone on the thread. Instead, use a [GitHub Reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to plus-one comments or issues and click the "Subscribe" button in the right-hand menu to receive updates. Thanks 😄

**Comment by klihelp** [comment]
+2

**Comment by tomverhoeff** [comment]
As a heavy Spotify user, I spend literally hours to organize playlists into the right folders to keep a bit of organization in my library. I understand this is only relevant for a small subset of users and therefore doesn't get a lot of attention in the native applications. However, exposing basic folder management APIs should be doable right?

As soon as this is possible I'd be happy to build a simple web-app that just enables quick reordering of playlists (in bulk). Is that too much to ask?

**Comment by fbegue** [comment]
I would seem also that the web player - in no form that I can see - recognizes playlist folders either, which seems like a major issue for users who use the folder function regularly. 

As a developer who is new to the Spotify web API, this is really the first time I've been disappointed by all the awesome work you guys have put into letting us play around with this beautiful platform! PLEASE at least give us a hint if this is something that will be coming in the future, or SOME kind of workaround?! Really any way to extract the folder'd state of my playlists on the mobile or desktop application - not even a live report - would be acceptable, since as of Janurary it would seem this is not happening.

Much love

**Comment by klihelp** [comment]
Workaround I was thinking is to combine Spotify API with an external playlist organizer API, eg Google Sheets, where playlist IDs listed into folder categories.

**Comment by willdunning** [comment]
Wow. Three years the only official word from Spotify is "...don't add +1 comments to this thread..." It would be great to hear anything from a Spotify dev / advocate about the issue. A definitive "won't do" would be preferable to the the ocean of silence.

**Comment by 0xNF** [comment]
Any updates to the potential for adding folder apis? For an service that bills itself as playlist focused, there's a lot of playlist-peripheral features that are missing.

**Comment by cacothi** [comment]
It’s a shame that they open this channel to the community, and once they
got big they forget about them

**Comment by arirawr** [comment]
Hi again all,

We have looked into this feature request. The implementation of folders you see in the Desktop client is not one that lends itself to a resource-based API (for example, there are no folder IDs). Unfortunately this is something we are not technically able to implement. As a result, we are not able to support playlist folders in the Web API.

Thank you for your patience. We will try to be more clear about things like this in the future.

**Comment by klihelp** [comment]
Alternative idea can be to add a new folder attribute/value for each playlist, but adding to the folder ID reason, somehow Spotify apps able to list folders with it's very own sub-folders and playlists, then without folder IDs, maybe Spotify uses a NO_SQL, NO-DB setup..

Ideas for API users/programmers to test, anyone have other ideas?
- have full folder management outside Spotify API, organizing playlist IDs with eg. Google Sheets or other DB.
- have additional folder management within Spotify, eg: filter for folders by analyzing data structure in playlists' title and description.

**Comment by fbegue** [comment]
@klihelp Following the idea of doing the folder management outside of the Spotify API - what was your thinking here? And what is your use case? For me, I want my Node.js applications that use the Spotify API to be able to 'see' the current state of folders in the desktop/mobile application. Do you know of any application outside of the official ones that can see playlist folders? I don't even know where to start looking

**Comment by 0xNF** [comment]
If the main issue is that folders don't have IDs, then you could just interpret any `/` inside a playlist name as belonging to a folder. Bit ghetto, though.

I'm kind of curious how Spotify is doing it, if they don't a concrete folder object.

**Comment by tomledger** [comment]
@arirawr  could you just add a 'folders' attribute to the playlist object containing a string showing the full path (e.g. 'genres/reggae'), and let the end user use that to construct a folder list if necessary?

**Comment by mikez** [comment]
If you want a short-term workaround, this seems to work on my machine:

https://github.com/mikez/spotify-folders

**Comment by fbegue** [comment]
@mikez Hey thats not to bad.  Have you tried doing this on a Windows machine? At a quick glance, if I were to appropriate this for myself, I would need to do what? adjust file paths and change  get_all_persistent_cache_files to do something Windows-ish? Thanks

**Comment by mikez** [comment]
> @mikez Hey thats not to bad. Have you tried doing this on a Windows machine? At a quick glance, if I were to appropriate this for myself, I would need to do what? adjust file paths and change get_all_persistent_cache_files to do something Windows-ish? Thanks

Yep, that could work! Set `PERSISTENT_CACHE_PATH` to the windows-equivalent-path, maybe `os.path.join(os.getenv('LOCALAPPDATA'), 'Spotify', 'Storage')`. Test with some other Windows people too, to make sure it works.

**Comment by mikez** [comment]
@fbegue Feel free to message me on twitter: twitter.com/mikez

**Comment by villeodell** [comment]
**Adding additional context to consider for issue:**

I just discovered this issue/thread as a Spotify user who was forced into using playlists when, to my surprise, I was informed by Spotify that I couldn't add any more music to my library 
(wtf? -- of course there are reasons, but from a user experience perspective it's like saying -- Whoah there, you've liked too much music, Spotify is no longer for you).

Such is life and I started using playlists to save albums; pleased to find that I could group them under folders for easier access / listening (e.g. doing: 'genre-folder/sub-genre-folder/album-playlist' or 'label-folder/album-playlist' is really great!). Not so easy to manage though once you have more than a few -- and discovering that there is zero support for playlist folders via the web api is a bummer.

Users can have folders so it would be great if developers could support those for users everywhere users can access Spotify (e.g. Google Home Actions, Sonos, playlist managers, etc.. ) -- users expect this by default (e.g. search for spotify folders on the Sonos community forums).

_Couldn't issue be kept open but labeled 'blocked' (e.g. by "no folder IDs" which could be tracked internally?)_

**Comment by xuezhma** [comment]
> Unfortunately this is something we are not technically able to implement

There are so many ways to implement this. Looking into workaround provided by mikez, there seems to be IDs for folders already. https://github.com/mikez/spotify-folders

```
{
  "name": "Seasons",
  "type": "folder",
  "uri": "spotify:user:example:folder:f0dcb1c2b1a98521",
  "children": [{
    "name": "Summer",
    "type": "folder",
    "uri": "spotify:user:example:folder:8212237ac7347bfe",
    "children": [{
        "type": "playlist",
        "uri": "spotify:user:spotify:playlist:37i9dQZF1DXdCsscAsbRNz"
     }, {
        "type": "playlist",
        "uri": "spotify:user:spotify:playlist:37i9dQZF1DWZd79rJ6a7lp"
     }]
  }, {
    "name": "Winter",
    "type": "folder",
    "uri": "spotify:user:example:folder:4b254ce1b7f5e23d"
    "children": [{
      "type": "playlist",
      "uri": "spotify:user:spotify:playlist:37i9dQZF1DWSiZVO2J6WeI"
    }]
  }
}
```


> "uri": "spotify:user:example:folder:f0dcb1c2b1a98521",

`f0dcb1c2b1a98521` looks like an folder id to me.

Spotify prob simply wants to focus on stuff like promoting ads passively and grab cash than actually making the product better.

**Comment by kayvanbree** [comment]
Damn. You guys don't want to remove the 10k song limit, you don't want us to use folders to let us organize albums into folders. We can't do anything here if you are [part of the 1%](https://community.spotify.com/t5/Live-Ideas/All-Platforms-Your-Library-Increase-maximum-Songs-allowed-in/idi-p/733759)...

If you implement a folder API where we can organize playlists into folders, I can continue on my Spotify playlist organizer app and I won't complain about the 10k song limit anymore. Spotify is an awesome music player, but the way you treat your paying customers is ridiculous. One percent of the current user base amounts to 22 million annoyed customers.

**Comment by gralpli** [comment]
That `wontfix` tag there is hilarious. This is such a basic thing and of course it's technically possible to implement this. They probably just want to make it harder to write tools that help switching from Spotify to an alternative provider.

@arirawr

**Comment by arirawr** [comment]
@gralpli , I'm no longer at Spotify and can't help you with this issue. Please refrain from tagging me.

**Comment by Twometer** [comment]
The open.spotify.com web player requests `https://spclient.wg.spotify.com/playlist/v2/user/{username}/rootlist?decorate=revision%2Clength%2Cattributes%2Ctimestamp%2Cowner&market=from_token` to get a list of playlists *with* folders. So much for "not technically possible"

**Comment by technomorph** [comment]
For my app, I use mikez parser:

https://github.com/mikez/spotify-folders

Create a JSON out of the output.
In Objective-C I create a new Root Folder dictionary.
I walk thru the JSON. 

If the item is a folder I add relevant info such as the name, ID and URI. 
If the folder has children I then reload thru my folder parsing function.  

If the item is a playlist. I add the ID and URI
(Mikes Parsing doesn’t include the name)

After recreating my own version of the folder parsing. 
 I use the Web API to get all current users playlists.

I think walk thru my  Folder/playlists dictionary.
For any playlists I get the playlist ID.
Filter / Find it in all user playlists.
Get the name, and the Tracks Link Ref URL.
I the. Update my Folder/playlists dictionary.

In my user interface I have two table views.  One on the left
To display the Folders / playlists names and their items (children) count.   
One on the right that shows the tracks of a playlist is selected on the left.

Once a playlist is selected on the left.
I use the playlist tracks ref URL and the web API to quickly fetch the tracks, I parse
Them and then add them to the items of the playlist in my Folder/playlist dictionary .

Then update the table views.

It works great but don’t have the functionally or being able to:
1) create / delete folders
2) move playlists within folders
