### ISSUE TITLE
Edit playlist image

### ISSUE THREAD

**Issue by sebbenla** [spotify/web-api#380]
It would be fantastic to edit image for user's own playlists. 

#### Use-case:
A user login to a playlist "generator" service with their Spotify account. Through this service the user creates a list with tracks and creates or choose a customized artwork. User save the list as a new playlist in their own Spotify library, and the artwork is used as playlist image through the API.

**Comment by thelinmichael** [comment]
Hey @sebbenla! Thanks for bringing this up - it's a great feature. It's covered in #112, so in order to track every request in the same place I'm going to close this issue.
