### ISSUE TITLE
Multi-fetch for User's and Category's

### ISSUE THREAD

**Issue by mhuusko5** [spotify/web-api#381]
It would be optimal to have a multi-fetch endpoint for User's and Category's, similar to Artist/Album/Playlist/Track's.

**Comment by hughrawlinson** [comment]
Hey @mhuusko5 - could you tell me more about your use case for this kind of an endpoint? It's a lot of data to request at one time.

**Comment by mhuusko5** [comment]
If a resource type is exposed, at some point multiple of them are going to be fetched. Better to do that via a batch endpoint instead of lots of single requests.

Besides, theres batch requests for Albums already and those are significantly bigger responses than Category or User.

**Comment by mhuusko5** [comment]
@hughrawlinson thoughts?

**Comment by bih** [comment]
Hello @mhuusko5,

Thanks for your feature request! We're in the process of cleaning up our GitHub issue tracker (as per our [new developer support process](https://github.com/spotify/web-api)) to better serve you and other developers.

In this particular case, we discussed this and decided that whilst your points are valid, there simply aren't enough use cases or demand to justify building this out. For that reason I'm going to close this as <kbd>wontfix</kbd> for now.

Though I encourage you and other developers to continue to share use cases and support for this feature - it helps us prioritize features in the future. You should still be able to comment on this issue. We will post updates here if there are any updates relating to this ticket 🙂

Thank you for taking the time to share your feedback, and please continue to do so! We highly appreciate it. Let me know if you have any other questions!

Cheers 👍
