### ISSUE TITLE
Empty playlist list when calling https://api.spotify.com/v1/me/playlists

### ISSUE THREAD

**Issue by gyosko** [spotify/web-api#382]
Issue found on December 20th 2016

#### Endpoint(s):
* `GET https://api.spotify.com/v1/me/playlists

#### Scope(s):
* playlist-read-private

#### Steps to reproduce:
1. Open the API Console
2. Call the `/me/playlists` 

#### Expected behaviour:
A list with my current playlists.

#### Actual behaviour:
Response 200 with following content (even though I have some playlists)

    {
      "href" : "https://api.spotify.com/v1/users/gyosko/playlists?offset=0&limit=20",
       "items" : [ ],
      "limit" : 20,
      "next" : null,
      "offset" : 0,
      "previous" : null,
      "total" : 0
    }

**Comment by hughrawlinson** [comment]
Hey @gyosko. Is this still happening? I'm not able to reproduce the issue. Please reopen this ticket if you're still experiencing the problem.

**Comment by gyosko** [comment]
@hughrawlinson It looks like it's working now, thank you :)

**Comment by MarinaTaran** [comment]
@gyosko Hi!Could you tell  me,please,how did you solve this problem?!
