### ISSUE TITLE
track gender

### ISSUE THREAD

**Issue by kthouz** [spotify/web-api#385]
Does anybody know how to return the gender (r&b, hip hop, jazz, rock, electronic, ...) of a song?

**Comment by thelinmichael** [comment]
@kthouz, you're looking for the _genre_, and you'll find it on the [Full Album object](https://developer.spotify.com/web-api/object-model/#artist-object-full), and not on the track itself. You can use the [Get an Album endpoint](https://developer.spotify.com/web-api/get-album/) to retrieve it. 

Note that genre information isn't always available, in which case the `genres` array will be empty.
