### ISSUE TITLE
Not able to add a track in a playlist

### ISSUE THREAD

**Issue by delaflota** [spotify/web-api#387]
Issue found on February 19th 2015.

#### Endpoint(s):
* `https://api.spotify.com/v1/users/{user_id}/playlists/{playlist_id}/tracks`

#### Scope(s):
* 'playlist-modify playlist-modify-public user-library-read playlist-modify-private'

#### Steps to reproduce:
1. Open the API Console
2. Call the `Add Tracks to a Playlist` endpoint with all required information delivered 
as requested on the form.

#### Expected behaviour:
Tracks added to the playlist.

#### Actual behaviour:
{
  "error" : {
    "status" : 403,
    "message" : "Insufficient client scope"
  }
}

**Comment by delaflota** [comment]
Solved!!!
Sorry, didn't check the necessary scopes boxes...

Delaflota

**Comment by thelinmichael** [comment]
Thanks for getting back to us @delaflota - Happy hacking! 👍

**Comment by delaflota** [comment]
Thanks Michael,
and sorry for being too fast :-)

**Comment by raffjones** [comment]
Hi guys,

I have a strange situation where only one user is causing an issue with an SDA. Every action they take is reporting `Insufficient client scope` but they authorized the same app as everyone else, and nothing has changed in the scope request. We have always had `['playlist-modify', 'user-read-private']`

We are trying to add a track to a public playlist, so this scope should cover it, right?

Is there any way, using the API, to check the scope granted to a user against an API token?
