### ISSUE TITLE
Open Feature Requests link is incorrect.

### ISSUE THREAD

**Issue by crewupco** [spotify/web-api#388]
The readme for this repo has three links:

Open bug tickets | Open feature requests | Open enhancement requests

"Open enhancement requests" goes to https://github.com/spotify/web-api/issues?q=enhancement+is:open
"Open feature requests" goes to https://github.com/spotify/web-api/labels/enhancement

**Comment by thelinmichael** [comment]
Thanks for the report @crewupco! It's been fixed.
