### ISSUE TITLE
/v1/me/top/* date filter

### ISSUE THREAD

**Issue by pwatsonwailes** [spotify/web-api#389]
#### Endpoint:
* `GET /v1/me/top/{item}`

It'd be nice if this supported specific date ranges, in addition to the slightly arbitrary [long|medium|short]_term values currently specifiable.

**Comment by hughrawlinson** [comment]
Thanks for the feature request @petewailes

**Comment by arirawr** [comment]
Hey @pwatsonwailes,

As per our [new developer support process](https://github.com/spotify/web-api#creating-an-issue), any feature requests that have no plans to be considered in the next 6 months will be closed as wontfix.

We do not have any plans to implement this in the next 6 months and thus will close as wontfix.

We encourage you and other members of the community to continue to share use cases and your support for this feature, as it helps us prioritize features going forward. You will be able to comment on this issue even after it is closed. We will also post any updates here relating to this suggestion when they happen.
