### ISSUE TITLE
Search endpoint 500 error when using a certain string

### ISSUE THREAD

**Issue by fan1200** [spotify/web-api#391]
Issue found on February 19th 2015.

#### Endpoint(s):
* `GET /v1/search`

#### Scope(s):
* None (OAuth Token used)

#### Steps to reproduce:
1. Open the API Console
2. Call the `search` endpoint with `query` `chainsmokers closer` and `item type` `track`

#### Expected behaviour:
A public track object as described on `https://developer.spotify.com/web-api/object-model/#track-object-full`.

#### Actual behaviour:
500 Server Error (consistently)

**Comment by hughrawlinson** [comment]
Hey @fan1200 - I'm not able to reproduce this issue. Is it still happening for you? Please reopen this ticket if it is.

**Comment by fan1200** [comment]
It fixed itself I guess. Thanks anyway.
