### ISSUE TITLE
Full-length playback on Windows

### ISSUE THREAD

**Issue by gillesbergerp** [spotify/web-api#392]
Dear Spotify team,

I know that similar questions have been asked quite often in the past, but I haven't found a precise answer yet. Thus, I will ask it again: Will there ever be the possibility of full-length track playback on the Windows platform (might it be via a standalone SDK, as it is available for iOS and Android, or  as part of the Web API) in the near or far future?

I'm looking forward to your reply and I'm really hoping to get a positive answer.

**Comment by hughrawlinson** [comment]
Hey @gillesbergerp. As we've mentioned before we'd love to provide full length playback across as many platforms as possible, but it's a big task involving legal and licensing issues, as well as significant technical challenges. At the moment we have nothing to announce.
