### ISSUE TITLE
Results are found in search only when market is specified

### ISSUE THREAD

**Issue by ChrisHeinemeyer** [spotify/web-api#393]
Issue found on January 9th 2017.

#### Endpoint(s):
* `GET  /v1/search`

#### Scope(s):
* None (application is not using authentication)

#### Steps to reproduce:
1. Open the API Console
2. Search for Query : 'artist:Denzal Sinclaire album:I Found Love' and type: 'album'
3. Observe no results are returned.
4. Search with the same query, but add 'CA' to markets
5. Observe that a result is returned.

#### Expected behaviour:
For the results of searches to return correctly all the time when markets are not specified.

#### Actual behaviour:
No results being returned when a market is not specified.

**Comment by hughrawlinson** [comment]
Currently the market defaults to US (as marketless search isn't available). If an album is available in Canada but not in the US, it won't appear in a search for the US. You'll have to do multiple queries to search multiple markets.
