### ISSUE TITLE
Nulls in playlist names

### ISSUE THREAD

**Issue by rongi** [spotify/web-api#394]
Nulls in playlist names

Issue found on January 10th 2017.

#### Endpoint(s):
* `GET /v1/users/11130084896/playlists`

#### Scope(s):
* playlist-read-private, playlist-read-collaborative

#### Steps to reproduce:
1. Open the API Console
2. Call the `Get a List of a User's Playlists` endpoint with `user_id` `11130084896`

#### Expected behaviour:
Playlists should have names

#### Actual behaviour:
Playlists have nulls instead of names

**Comment by jstlnd** [comment]
@rongi Thanks for your report! We have deployed a fix.
Please let us know if you have any more issues.

**Comment by rongi** [comment]
It's happening again
