### ISSUE TITLE
GetPlaylists is returning null for playlist name

### ISSUE THREAD

**Issue by michaelfoster9** [spotify/web-api#395]
Hello, I am retrieving a users playlists with either of the endpoint below. 

https://api.spotify.com/v1/users/" + userId + "/playlists?limit=50"
https://api.spotify.com/v1/me/playlists

This has been working fine for over a year but as of this morning, the API started returning NULL for the playlist name for all playists not owned by spotify (ie. Discovery Weekly and Release Radar work, but my own playlists that I own do not).  I have reproduced this error using the developers console.

I'm hoping this is a defect that can be fixed quickly and not a security change where i have to make additional calls to get more data because of it's the latter, then 1) all existing software breaks and 2) The software would not perform well having to make additional round trips just to get a display name.

Please let me know if you need additional information.  I have received a lot of support questions on my own product this morning because of this so i'm hoping to resolve this as soon as possible.

**Comment by jstlnd** [comment]
@michaelfoster9 Thanks for your report! We are aware of the issue, and we're working on fixing it.

**Comment by jstlnd** [comment]
@michaelfoster9 We have deployed a fix.
Please let us know if you have more issues.
