### ISSUE TITLE
CURL error Unknown SSL protocol

### ISSUE THREAD

**Issue by blackarcanis** [spotify/web-api#396]
Hi,

Sometimes in my production environnement i got this error : 
`Unknown SSL protocol error in connection to api.spotify.com:443 `

or this one 
`SSL read: error:00000000:lib(0):func(0):reason(0), errno 104`

About my CURL request I don't define any SSLVERSION or params about SSL, because it works most of the time. But 1 request / 1000 maybe doing this error or the followed one : 
`Operation timed out after 0 milliseconds with 0 out of 0 bytes received`

Do you have some recommendations for improve my CURL requests and don't met this error definitively ?

Thanks a lot,
Thomas

**Comment by hughrawlinson** [comment]
Hi @blackarcanis - could you paste your curl request here so that we can reproduce the issue? (make sure to strip out any tokens that may be in there)

**Comment by blackarcanis** [comment]
@hughrawlinson That could happen on all requests I made, but it's something rare so I don't know how you can reproduce the issue. 
That's why I just wanted to know if you have recommendations about CURL option ?

**Comment by hughrawlinson** [comment]
Hey @blackarcanis - Perhaps try making your queries from the [Web Console](https://developer.spotify.com/web-api/console/) and copying the CURL commands generated there? If you can reliably reproduce the issue I'd be happy to look at it!
