### ISSUE TITLE
Misleading documentation in API Console about OAUTH token requirement for obtaining a user's profile

### ISSUE THREAD

**Issue by anamud** [spotify/web-api#397]
Hi,

While trying out the API console for the endpoint [Get a User's Profile](https://developer.spotify.com/web-api/console/get-users-profile/), I found that the information about OATH token requirement is not consistent with the table in [API Endpoint Reference](https://developer.spotify.com/web-api/endpoint-reference/).

The table correctly notes that OATH token is not required for the endpoint. However, the console API documentation notes that OATH is required. Making these consistent will reduce confusion and improve the experience of new-comers trying out the console.

I also noted that both the asterisk **(*)** character and the string _"Required"_ are used to denote OATH requirement. For a further reduction in confusion, I suggest using just only one of them, and removing the form and button for getting an OATH token for endpoint cases that do not require it.

For your reference, I am attaching a screenshot that points out the problem.

![screenshot-developer spotify com-2017-01-14-16-52-17](https://cloud.githubusercontent.com/assets/6641896/21956157/8f1e01d2-da7a-11e6-838f-5e6d0139338a.png)

**Comment by hughrawlinson** [comment]
Thanks @anamud, we'll address this soon :)

**Comment by hughrawlinson** [comment]
Hi @anamud - we've just announced that [all endpoints will require an auth token from any of our supported oauth flows](https://developer.spotify.com/news-stories/2017/01/27/removing-unauthenticated-calls-to-the-web-api/) from May 29th. We'll update the endpoint reference during this changeover time, and we'll make sure to update this ticket once it's done. I wanted to make sure you got the news, as it's clear from your issue that unauthenticated requests affect you.

**Comment by anamud** [comment]
Thanks for the timely update, Hugh Rawlinson.

**Comment by asmitter** [comment]
Should all match now!
