### ISSUE TITLE
Unable to authenticate with a Go client

### ISSUE THREAD

**Issue by zmb3** [spotify/web-api#398]
Issue found on January 14, 2017.

I received a report of users unable to authenticate using my Go implementation of the web API: https://github.com/zmb3/spotify/issues/20

A related HTTP2 [Go issue](https://github.com/golang/go/issues/17066) seems to indicate this is due to a [bug in nginx](https://trac.nginx.org/nginx/ticket/959) where the stream is refused if headers or data are sent before acking the settings from the server.

The nginx bug tracker indicates that the issue was fixed in v1.11.  Could it be that Spotify is running an unpatched nginx server? 

#### Endpoint(s):
* `POST accounts.spotify.com/api/token`

#### Scope(s):
* User read private

#### Steps to reproduce:
Run the authenticate example at https://github.com/zmb3/spotify/blob/master/examples/authenticate/authenticate.go

#### Expected behaviour:
Succesful authentication.

#### Actual behaviour:
`2017/01/14 11:29:56 Post https://accounts.spotify.com/api/token: stream error: stream ID 1; REFUSED_STREAM`

**Comment by hughrawlinson** [comment]
Thanks so much for reporting this! I'll pass it on to the team and get back to you.

**Comment by hughrawlinson** [comment]
Hey @zmb3 - the answer is that we currently don't support HTTP 2.0. Is there a way to configure your client to use the previous version?
