### ISSUE TITLE
Recommendation API - Compare results to Playlist recommended songs

### ISSUE THREAD

**Issue by ulizellbeck** [spotify/web-api#399]
Hey, I was looking to find recommendations for a track (Parov Stelar - All night). I was comparing my results of the API with the results from the playlist recommended songs. Unfortunately, they differ. 
I have two questions:

- How can I compare my results to the desktop App?
- Is there a way to get the same results as the playlist recommender?

#### Endpoint(s):
* `GET https://api.spotify.com/v1/recommendations`

#### Scope(s):
* None (application is not using authentication)

#### Steps to reproduce:
1. Open the API Console
2. Call https://api.spotify.com/v1/recommendations?market=DE&seed_tracks=2TBL24r897ewBYvf2hItYc&limit=10

#### Expected behaviour:
I will get the recommendations when I create a new playlist and add the track (Parov Stelar - All night):
Nekta - Listen, Skeewiff - Don't rock the boat, Parov Stelar  - The sun, ...

#### Actual behaviour:
I get the following recommendations:
Claptone - Ghost
Worakls - Good night my love
Fritz Kalkbrenner - willing
...

**Comment by hughrawlinson** [comment]
Hey @ulizellbeck - the recommendations are different because they're powered by two different recommendation systems. We don't expect to provide access to both over our web API.
