### ISSUE TITLE
500 error when trying to sign up for the API

### ISSUE THREAD

**Issue by egonSchiele** [spotify/web-api#40]
Hi there,
This page: https://developer.spotify.com/my-applications/#!/tos-accept

Gives me this error in the js console:

    https://api.spotify.com/webapi-provisioning/user-developer-info Failed to load resource: the server responded with a status of 500 (Internal Server Error)

**Comment by thelinmichael** [comment]
Thanks for this report @egonSchiele, we'll have a look at this immediately.

**Comment by thelinmichael** [comment]
@egonSchiele, please try again, the error should be intermittent. We'll try to make sure that it doesn't happen in the future, but you should be good to continue the signup process now, or at least shortly. Thanks again for reporting.

**Comment by egonSchiele** [comment]
Still not working: http://i.imgur.com/L6evOFo.png

I'll try again in a bit.

**Comment by Hobstweedl** [comment]
Also having the same issue trying to sign up for the API

**Comment by thelinmichael** [comment]
We've made a couple of changes to fix this, please let us know if you're still experiencing this issue.
