### ISSUE TITLE
Add description in list of a User playlist

### ISSUE THREAD

**Issue by blackarcanis** [spotify/web-api#400]
Hi,

I see the field "description" is not returned in user playlist list get by this endpoint : 
`https://api.spotify.com/v1/users/{user_id}/playlists`

That could be great ! Without it we need to make an other request for each playlist to get this field...

Thanks

**Comment by hughrawlinson** [comment]
Hey @blackarcanis - the `users/{id}/playlists` endpoint returns a list of [simplified playlist objects](https://developer.spotify.com/web-api/object-model/#playlist-object-simplified). This is to reduce payload size, which is useful when there are lots of playlists in a query. As you noted, you can query `users/{id}/playlists/{playlist_id}` to get the [full playlist object](https://developer.spotify.com/web-api/object-model/#playlist-object-full). We're unlikely to change this in the future, so I'm going to close this issue.
