### ISSUE TITLE
Web api with business account

### ISSUE THREAD

**Issue by sergiotomasello** [spotify/web-api#401]
Hi everybody,
I was wondering if I could use the web-api with a [Spotify Business account (or even Soundtrack)](https://www.soundtrackyourbrand.com/spotify-business) ?
Thank you all
Sergio

**Comment by hughrawlinson** [comment]
Hi @sergiotomasello - It should work, and I've asked them for confirmation of this. It will likely be faster for you to ask them directly [on their support website](https://www.soundtrackyourbrand.com/help).

**Comment by sergiotomasello** [comment]
hi @hughrawlinson thank you for the quick reply, I just open a support ticket, but if you'll get a response from they please let me know. Thank you very much!
Sergio

**Comment by sergiotomasello** [comment]
hei @hughrawlinson, did you get a confirmation from them? let me know, because their support isn't really fast :/
thank you!
Sergio

**Comment by hughrawlinson** [comment]
@sergiotomasello I haven't heard from them yet. I'll chase them up.

**Comment by sergiotomasello** [comment]
Finally i've got a reply from _Soundtrack your brand_ support team. Generally I can use most of the api, but I cannot stream music and then cannot build a music player. sadness, really sadness 😞
