### ISSUE TITLE
Playlist names appearing as null in `Get a List of a User's Playlists`

### ISSUE THREAD

**Issue by jdpopkin** [spotify/web-api#402]
Issue found on January 17th 2017.

#### Endpoint(s):
* `GET /v1/users/{user_id}/playlists`

#### Scope(s):
* None (application is not using authentication)

#### Steps to reproduce:
1. Open the API Console
2. Call the `Get a List of a User's Playlists` endpoint with `user_id` `iam3`

#### Expected behaviour:
Playlists' names will match those fetched using `Get a Playlist`. In particular, since /v1/users/iam3/playlists/7hi3CO5QkC8qg0XnYJulDQ has the `name` `ALT RnB`, I would expect the playlist with the `id` `7hi3CO5QkC8qg0XnYJulDQ` to have the `name` `ALT RnB`.

#### Actual behaviour:
Most playlists' names are null, including `7hi3CO5QkC8qg0XnYJulDQ`. The correct playlist name occasionally appears, but only rarely. A more popular playlist by the same user, `17HYiAIcwlDEg5RgVkm4L7`, always has its correct name in `Get a List of a User's Playlists` results.

**Comment by hughrawlinson** [comment]
Hi @jdpopkin - we've deployed a fix for this. Please let us know if it happens again!
