### ISSUE TITLE
Care about personal data modifications not advised to laymen users of API Console

### ISSUE THREAD

**Issue by anamud** [spotify/web-api#405]
While testing several endpoints the API Console, laymen users can inadvertently modify their personal data. They may not even realize that till its too late since the API Console returns technical data and is showcased as a playground which has the connotations of a safe sandbox. My suggestion is to warn users that their interactions with the API Console can modify personal data, and briefly explain OAuth scope terms such playlist-modify-private in the token-request pop-up.

**Comment by hughrawlinson** [comment]
Hey @anamud - thanks for the feedback. We'll consider putting in a warning.

**Comment by hughrawlinson** [comment]
Hi @anamud - we now have a warning that displays inside the console if the OAuth token field is filled, saying that running the command will affect the users account. Thanks!
