### ISSUE TITLE
Server responding with 500 internal server error on step 1 of Authorization Code Flow

### ISSUE THREAD

**Issue by antoinfive** [spotify/web-api#406]
Issue found on Jan 19th 2017.

#### Endpoint(s):
* `GET https://accounts.spotify.com/en/authorize?`

#### Scope(s):
* None

#### Steps to reproduce:
1. Make the initial client side request to the authorize endpoint and click accept or cancel

#### Expected behaviour:
When the user clicks accept or cancel, instead of redirecting to my applications callback with authorization code, or an error, the server responds with a 500 internal server error consistently.

#### Actual behaviour:
500 Server Error (consistently)

I can get to this page consistently, where the user will accept or deny access:

![screen shot 2017-01-22 at 2 35 52 pm](https://cloud.githubusercontent.com/assets/11672791/22185269/69542d8c-e0b0-11e6-953d-186956ff2969.png)

But upon selection, I receive this error in the console: 

![screen shot 2017-01-22 at 2 37 42 pm](https://cloud.githubusercontent.com/assets/11672791/22185271/773ab1b4-e0b0-11e6-8bdf-a67ed9299588.png)

**Comment by hughrawlinson** [comment]
Hi @antoinfive - I haven't been able to reproduce this issue. Is it still occurring for you?

**Comment by antoinfive** [comment]
Hi @hughrawlinson - thanks for getting back to me. Yes, I am still getting this error in the same scenarios. I am utilizing Ruby on Rails that will eventually serve as an API but i'm testing the auth flow before building the front-end. 

A user will visit `localhost:3000/auth` and this will redirect them to the authorization page.

Here is the controller action that redirects the user to the authorization page:
`def new 
      redirect_to "#{BASE_URL}?client_id=#{ENV['spotify_client_id']}&response_type=code&redirect_uri=localhost:3000/auth/callback" 
    end
`
My callback route:
`get '/auth/callback'` 

I have tried using multiple accounts, private browsers, and also have tried accessing the authorization route directly rather and a redirect with no success. 

What other information would be valuable to aid in solving this issue?

**Comment by hughrawlinson** [comment]
Could you send me your client-id? Also, redirect uris must start with the protocol ('http://' or 'https://'). Could you try including the full uri? In this case `http://localhost:3000/auth/callback`? Make sure to whitelist the uri in the developer dashboard too!

**Comment by antoinfive** [comment]
😓  wow, thanks @hughrawlinson .. forgot the protocol in the callback. Everything is working now.

**Comment by hughrawlinson** [comment]
No worries! Glad it's working. We should be giving a better error message though, so I'll try and get that to happen. Thanks!

**Comment by avoinicu** [comment]
I'm getting the same error while using the web-api-authorization example. I made sure to add in my client id and have the redirect uri including the protocol.
