### ISSUE TITLE
album_type for appears_on is not set correctly

### ISSUE THREAD

**Issue by emilguareno** [spotify/web-api#407]
Issue found on February 19th 2015.

#### Endpoint(s):
* `GET /v1/artists/{id}/albums`

#### Scope(s):
* None (application is not using authentication)

#### Steps to reproduce:
1. Open the API Console
2. Call the `get-artist-albums` endpoint with `artist-id` `3jK9MiCrA42lLAdMGUZpwa` and `album_type` `appears_on`

#### Expected behaviour:
The `album_type` for the returned objects should be `appears_on` when querying the artist albums endpoint

#### Actual behaviour:
The `album_type` for the returned objects are all `album`. 

I understand why it might not return `appears_on`, as it is not an official `album_type`. But when querying for all types at once, there should be a way to differentiate between a regular album and appears_on. Also, the documentation allows for the value `appears_on` as an `album_type`, therefore it is kind of misleading.

**Comment by hughrawlinson** [comment]
Thanks for the report @emilguareno!

**Comment by arirawr** [comment]
Hey @emilguareno - I'm happy to let you know that this is now supported in the API. Thanks for your suggestion!

Returned albums now have an "album_group" field, which will be "appears_on" for albums the artist appears on.

You can check out the updated docs here: https://developer.spotify.com/documentation/web-api/reference/artists/get-artists-albums/
