### ISSUE TITLE
Getting a 502 bad gateway when trying to read /tracks

### ISSUE THREAD

**Issue by TobiasBales** [spotify/web-api#408]
Issue found on January 23th 2017.

#### Endpoint(s):
* `GET /v1/me/tracks`

#### Scope(s):
* `user-library-read`
* `user-library-read`

#### Steps to reproduce:
1. Open the API Console
2. Call the Get Current User's Saved Tracks endpoint `/me/tracks` with `user_id` `tobiasbales`

#### Expected behaviour:
Some data

#### Actual behaviour:
502 Bad Gateway Error (consistently)

The same is true for `/me/albums` `/me/playlists` works though.

**Comment by JackRyder** [comment]
I have a similar problem at the moment, seems like their API is down on certain areas.

**Comment by TobiasBales** [comment]
After going below my library song limit of 10k the api response is fine again.

My guess is that it is related ;)

**Comment by hughrawlinson** [comment]
Hey @TobiasBales - we were having an issue with the service, but it should all be good now. Feel free to reopen this issue if you're still having problems!
