### ISSUE TITLE
404 when searching for `-)`

### ISSUE THREAD

**Issue by stephanebruckert** [spotify/web-api#409]
One of the tracks I was searching for on Spotify had `-)` in it. I can easily clean it from the search terms or even catch the 404 I get in return, but I thought this could prevent finding a track in some cases.

#### Endpoint(s):
* `GET /v1/search`

#### Scope(s):
* None (application is not using authentication)

#### Steps to reproduce:
1. Just visit https://api.spotify.com/v1/search?q=-%29&type=track&limit=1&offset=0

#### Expected behaviour:

```
{
  "tracks": {
    "href": "https://api.spotify.com/v1/search?query=-%29&type=track&offset=0&limit=1",
    "items": [],
    "limit": 1,
    "next": null,
    "offset": 0,
    "previous": null,
    "total": 0
  }
}
```
#### Actual behaviour:

```
{
  "error":  
    "status": 404,
    "message": "Not found."
  }
}
```

**Comment by hughrawlinson** [comment]
Thanks for letting us know @stephanebruckert! I've filed a bug with the team responsible.

**Comment by asmitter** [comment]
Hi @stephanebruckert - what was the track which contained -) ?

**Comment by stephanebruckert** [comment]
Hi @asmitter, I was searching for [`Creative Swing Alliance - Mother Water (Medlar remix -)`](https://www.residentadvisor.net/tracks/468818).

**Comment by zeeshanayaz** [comment]
I am also facing the same issue. Is there any possible **solution**?

**Comment by stephanebruckert** [comment]
This seems to work now, no more 404! Thanks.
