### ISSUE TITLE
Facebook login bug

### ISSUE THREAD

**Issue by akgargo** [spotify/web-api#41]
Using facebook to create a new account works, but when I'm trying to login with Facebook, the server responses that I already have an account created with that email address

**Comment by rschildmeijer** [comment]
@akgargo could you tell us what email and facebook uid (http://findmyfacebookid.com/) you are using?

**Comment by akgargo** [comment]
I wasn't wrote any email address or any password I'm just using "Login with Facebook" button, and that button does the same function that do "create an account with Facebook" button... If I wasn't sufficient clearly at all, just let me know. Thanks

**Comment by rschildmeijer** [comment]
@akgargo That means that you already have an account.
I would recommend you to do a password reset (https://www.spotify.com/se/password-reset/) if you don't remember your password.

**Comment by akgargo** [comment]
Thanks, I did when this happened to me, but I mentioned it because that's not supposed to be the proper functioning of the system. I think that if I click on a button that says "Login" and this sent me to a window that gives me the option to sign in with my Facebook data, you should do that. not create a new account, just login with those data

**Comment by thelinmichael** [comment]
This repository is only meant for Web API issues. If you have ideas or having further issues, please see [the Spotify Community](https://community.spotify.com/) or contact [@SpotifyCares](https://www.twitter.com/spotifycares) on Twitter.
