### ISSUE TITLE
Token expires after 1 hour - refresh token gives one more hour.

### ISSUE THREAD

**Issue by denysvitali** [spotify/web-api#414]
Hi everyone,

I'm filing this bug report because I cannot find the answer elsewhere.
I am currently developing an application that acts as a brdige from the BBC Radio 1 "current song" endpoint and the Spotify API.
Basically my applocation just search for the entries in current song, and adds it to a specific playlist on spotify.
Everything works great, but the Access Token expires after an hour: by following the documentation I can "refresh" it for another hour, but when I do it I don't get a new refresh token, thus the total Access Token validity is 1+1 hour. Since my apps basically needs "offline access" it would be great to have a way to do it, such like a scope, or simply by returning a new Access Token, as well as a new Refresh Token when it's needed to refresh the expired token.
Additionally, it would be nice to have an endpoint to validate a token: at the moment I use `/me` as an endpoint, but this could give you problems with resources on your side.

**Comment by hughrawlinson** [comment]
Hey @denysvitali. It looks like the title of this issue doesn't match the body. Could you double check? To answer both questions:

> Token expires after 1 hour - refresh token gives one more hour.

That's exactly the correct behaviour. Once an access token expires, you can refresh using the refresh token and grab a new one for queries in the next hour.

> Cannot retrieve profile for user with user ID ^

I can't reproduce the issue, the web console queries for that user properly for me. Which browser are you using? Perhaps it's failing to encode the character.

**Comment by denysvitali** [comment]
I'm sorry @hughrawlinson , it was the default message. I accidentally sent the issue without editing the body (I am on mobile, sorry about that).
I fixed the text now.

Basically my problem is that an AT expires after 1+1 hour, and there is no way to refresh the already refreshed token

**Comment by hughrawlinson** [comment]
No problem!

Are you encountering an issue generating new auth tokens with the refresh token? You should be able to use the refresh token to generate a new auth token an unlimited number of times.

**Comment by denysvitali** [comment]
I may have misunderstood the documentation then. I'll try right now and report back. Thanks!

**Comment by hughrawlinson** [comment]
Cool! Feel free to suggest ways in which the documentation could be made more clear. Please reopen this issue if you aren't able to indefinitely refresh your token.

**Comment by denysvitali** [comment]
It works indeed. Sorry about that!
The documentation is right: "Access tokens are deliberately set to expire after a short time, after which new token**s** may be granted by supplying the refresh token originally obtained during the authorization code exchange."

**Comment by sahandnayebaziz** [comment]
Hey @hughrawlinson, any word on extending the one hour expiration? My client, using the Client credentials flow, every hour does the dance of receiving a 401, refreshing the token, and retrying that request.

I am sure you know this isn't the most graceful situation, and I understand there must be reasons behind it, but wanted to ask anyway.

**Comment by jpiepkow** [comment]
@sahandnayebaziz the standard is to have your client send the token to a server you wrote that will see if the token is still valid/refresh if needed and then make the request. No need for a client to see 401

**Comment by sahandnayebaziz** [comment]
@jpiepkow Right, by my client I am referring to my server, per the [oauth 2.0 specification](https://tools.ietf.org/html/rfc6749#section-1.1).

**Comment by sahandnayebaziz** [comment]
@jpiepkow that is also what I am currently doing, check the token validity each time (until it ultimately isn't accepted and I re-auth), but I can't imagine this is how we all want this to work forever

**Comment by jpiepkow** [comment]
@sahandnayebaziz it is actually pretty standard as far as oauth flow goes.

**Comment by sahandnayebaziz** [comment]
Why though? Why not refresh every 4 weeks? Or 4 months? In this use case with the Client credentials flow, there is no sensitive user data being accessed. I'm only searching Spotify for track IDs to surface Spotify songs for users! Worth mentioning, by the way, that Apple Music search requires no auth for search, but I know that's a separate topic.

So everybody using the Client credentials flow is refreshing their token every hour? Even though they may be using the app every hour for sure anyway?

**Comment by sahandnayebaziz** [comment]
I understand if nothing changes, the API is working fine, but in terms of what makes sense and what feels like extra work over here, just want to make sure I get in being a squeaky wheel here to complain about this.

**Comment by denysvitali** [comment]
IMHO refreshing tokens every hour isn't a big deal - it is an additional request every hour  
  
It may be more load-intensive on Spotify's part though

**Comment by hughrawlinson** [comment]
Hey, no updates at the moment. Refreshing once your previous token expires can be done automatically, it's best practice from a client perspective for now.
