### ISSUE TITLE
Retrieve all relinking information with single API call

### ISSUE THREAD

**Issue by rorygilchrist** [spotify/web-api#415]
When trying to get track IDs for each market via relinking, multiple API calls are required. While there are ways to reduce the number, the current method puts strain on the application, the Spotify Web API and impacts rate-limits. This seems to be against the design principles of the API, as quoted from the documentation: 

> A way to reduce the amount of requests is to use endpoints that fetch multiple entities. 

 
It would be useful to have an endpoint such as ` /tracks/:trackId/markets`, which lists out each market and the track ID associated - this could also be grouped by track ID. A sample return response could be something like this: 

```
{
    id : "requested_id"
    markets : [
        {"id" : "XXXXXXXXXXXXXXXXX", "markets" : [ "US", "GB", "ES", ... ] },
        {"id" : "XXXXXXXXXXXXXXXXX", "markets" : [ "DE", "NL", "BE", ... ] },
        ...
    ]
}
```

or 

```
{
    id : "requested_id"
    markets : [
        {"id" : "XXXXXXXXXXXXXXXXX", "market" :  "US" },
        {"id" : "XXXXXXXXXXXXXXXXX", "market" :  "GB" },
        ...
    ]
}
```

**Comment by hughrawlinson** [comment]
Thanks for the feature request! I'll pass it on to the relevant team.

**Comment by arirawr** [comment]
Hey @rorygilchrist,

As per our [new developer support process](https://github.com/spotify/web-api#creating-an-issue), any feature requests that have no plans to be considered in the next 6 months will be closed as wontfix.

We do not have any plans to implement this in the next 6 months and thus will close as wontfix.

We encourage you and other members of the community to continue to share use cases and your support for this feature, as it helps us prioritize features going forward. You will be able to comment on this issue even after it is closed. We will also post any updates here relating to this suggestion when they happen.
