### ISSUE TITLE
Public playlist visibility

### ISSUE THREAD

**Issue by bvhertz** [spotify/web-api#417]
Issue found on January 31th 2017.

#### Endpoint(s):
* `GET /v1/users/{user_id}/playlists/`
* `GET /v1/users/{user_id}/playlists/{playlist_id}`

#### Scope(s):
* None (application is not using specific authentication right)

#### Informations to reproduce:
Using following values:
* "spotify" as user_id
* "1yHZ5C3penaxRdWR7LRIOb" and "37i9dQZF1DX4JAvHpjipBk" as playlist_id

#### Expected behaviour:
Both playlists should be listed through endpoint /v1/users/{user_id}/playlists/.

#### Actual behaviour:
1yHZ5C3penaxRdWR7LRIOb is mentioned in the endpoint /v1/users/{user_id}/playlists/, but 37i9dQZF1DX4JAvHpjipBk isn't.
Sales report mention the playlist 37i9dQZF1DX4JAvHpjipBk, but not 1yHZ5C3penaxRdWR7LRIOb

**Comment by hughrawlinson** [comment]
Hey @bvhertz - which sales report are you referring to?

**Comment by bvhertz** [comment]
Hello @hughrawlinson, it's about daily reports we can retrieve with API v.2
I try to merge data from web api (playlist data) and daily reports, but in some case we have divergent ids like here.

**Comment by hughrawlinson** [comment]
@bvhertz could you contact me through developer-support@spotify.com please?
