### ISSUE TITLE
Adding tracks to users library (put-current-user-saved-tracks) sometimes fails with HTTP 400 - BadRequest

### ISSUE THREAD

**Issue by ClemensSchneider** [spotify/web-api#42]
Sometimes, when trying to add tracks to the users library, we get an HTTP 400 - BadRequest as response from the server. This is even reproducible using the Web-API console.
My guess is that this is somehow related to the existing tracks in the users library, but we did observe, that it does work sometimes when changing the amount of track-ids passed in the API-call.

Now it event fails for one single track-id (this is for my test-account 'Falchor_01'):

https://developer.spotify.com/web-api/console/put-current-user-saved-tracks/?ids=4cQIbDqCZrHknxlDUjRHZ0

The response-body is not very informative:

```
HTTP/1.1 400 Bad Request
Access-Control-Allow-Methods: GET, POST, OPTIONS, PUT, DELETE
Content-Encoding: gzip
Transfer-Encoding: chunked
Access-Control-Allow-Credentials: true
Access-Control-Max-Age: 604800
Keep-Alive: timeout=600
Server: nginx
Connection: keep-alive
Cache-Control: private, max-age=0
Date: Tue, 05 May 2015 08:36:37 GMT
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: Accept, Authorization, Origin, Content-Type
Content-Type: application/json; charset=utf-8
```

```
{
  "error": {
    "status": 400,
    "message": "Bad request"
  }
}
```

**Comment by thelinmichael** [comment]
Hi @ClemensSchneider! I had a look at your account and your test account has hit the limit on how many tracks you can have in your Your Music collection - 10'000 tracks.

We'll fix the error message and update our documentation to include this limit.

**Comment by thelinmichael** [comment]
The error message and documentation has been updated. I'm closing this issue now but please let us know if you're getting more ambiguous error messages.
