### ISSUE TITLE
"Your Library" playlist URI

### ISSUE THREAD

**Issue by xzzz9097** [spotify/web-api#420]
It seems that "spotify:user:[user_name]:starred" as a URI for context is no longer working.
Is there another way to get a valid URI for "Your Library" tracks playlist? I'd pass it as a context to Spotify AppleScript API to let the user jump between tracks he saved.

**Comment by hughrawlinson** [comment]
Hey @xzzz9097 - we don't have a URI for this at the moment. I've sent a feature request to the team that's responsible, but please don't expect this in the short term.

**Comment by hughrawlinson** [comment]
As playlist URIs aren't part of the Web API, I'll close this issue. URIs are a feature of the Spotify Clients, and feature requests for those should be on [Spotify's Community Site](https://community.spotify.com/)
