### ISSUE TITLE
Using web-api as a remote control to play a song

### ISSUE THREAD

**Issue by kellogsgit** [spotify/web-api#421]
Dear all,

First, thanks for the hard work.

If machine A is running Spotify with a premium account.

Can I use machine B with Web API to:
* modify playllst (add, remove a song in playlist)
* trigger audio play
* modify volume

In short, I would like to use web-api as a remote control for a stock Spotify accound with premium account.

Is that possible?

**Comment by jscholes** [comment]
The web API will allow you to modify playlists, and changes made in this
way will be noticed by the Spotify desktop apps in realtime.  However,
neither of the other things you mentioned are currently possible.

**Comment by kellogsgit** [comment]
Okay, I getting back to buying CDs and I will soon close my Spotify account. CDs are only 1 to 3 EUR on Internet. I can buy 200 CDs for 20 EUR in batch. SO I wron't put more money into a streaming service which does not offer a real API stable over time.

**Comment by hughrawlinson** [comment]
Hey @kellogsgit!

You can use our [playlist web api endpoints](https://developer.spotify.com/web-api/console/playlists/) to modify playlists. 😄 

We'd love to provide volume and playback control functionality, but we don't have any endpoints for those at the moment. There's already an open feature request for it #15, so I'll close this duplicate. Thanks!
