### ISSUE TITLE
Docs: incorrect top tracks example

### ISSUE THREAD

**Issue by kabirvirji** [spotify/web-api#422]
Issue found on February 13th 2017.

#### Endpoint(s):
* `GET v1/artists/{id}/top-tracks`

#### Scope(s):
* None (application is not using authentication)

#### Steps to reproduce:
1. Visit https://developer.spotify.com/web-api/get-artists-top-tracks/

#### Expected behaviour:
Example should be (notice correct placement of quotation): <br>
`curl -X GET "https://api.spotify.com/v1/artists/43ZHCT0cAZBISjO8DG9PnE/top-tracks?country=SE"`

#### Actual behaviour:
Wrong quotation mark resulting in `curl: no URL specified!` <br>
This is what is in the documentation:
`curl -X "GET https://api.spotify.com/v1/artists/43ZHCT0cAZBISjO8DG9PnE/top-tracks?country=SE"`

**Comment by hughrawlinson** [comment]
Thanks for the report! I've passed it on to the team.

**Comment by hughrawlinson** [comment]
That's fixed now, thanks! 😄
