### ISSUE TITLE
Request timed out from Workflow app when requesting for token

### ISSUE THREAD

**Issue by Behinder** [spotify/web-api#423]
#### Endpoint(s):
* POST https://accounts.spotify.com/api/token
#### Scope(s):
* None (application is not using authentication)

Whenever I use this from PAW it works. However when using POST request from Workflow app on iOS I got request timed out. The same code worked last year. Workflow developers said that it had to be problem on Spotify side.

Example for this workflow is [here](https://workflow.is/workflows/0bdd1a827d904f4ebf617aac7a06d4e8)

**Comment by AriX** [comment]
Workflow developer here. It seems that this is the same-ish issue as https://github.com/spotify/web-api/issues/398. Workflow uses Apple's `NSURLSession` to connect to the Spotify server, which for some reason decides to go over HTTP/2 and fails.

We aren't sure why iOS chooses to use HTTP/2 here, and we haven't been able to find a way to affect this behavior. Is it possible to disable HTTP/2 on the server so as to prevent this?

**Comment by AriX** [comment]
I found a workaround, which is to add an HTTP header to the request such as "Upgrade: TLS/1.2", which prevents the connection from upgrading to HTTP/2 (which causes the request to fail).

**Comment by hughrawlinson** [comment]
Looks like this issue is resolved, I'll close it. As previously mentioned on this issue tracker, we don't currently have any announcements to make around HTTP/2.
