### ISSUE TITLE
Cannot create a Spotify Developer account for API access

### ISSUE THREAD

**Issue by mrosscoe** [spotify/web-api#424]
I am having an extremely hard time creating a Spotify Developer account for access to the API. I'm not sure if this is the correct place to ask - but I am unable to find proper contact information and this was the only lead I found.

Whenever I click on "My Applications" and try to "Login" at this page: https://developer.spotify.com/my-applications/login

I get an error that it is forbidden and it does not load. This also happened on my phone. I also tried clicking on the "About" link for more contact information and it doesn't load either. 

How can I go about creating a Spotify Developer account? I would like to use the API to work on a Recommender System using the Echo Nest music data. I was under the impression that Echo Nest's API functionality was rolled into the Spotify API. However, I am unable to login or even find a link to register for a Spotify Developer account. Can somebody please direct me to the proper resources?

Thank you!

**Comment by hughrawlinson** [comment]
Hey @mrosscoe - is it still broken for you? It seems to be working for me.

Some of the Echo Nest API was rolled into the Spotify API. For more specific info about what the Spotify Web API provides, please consult our [endpoint reference](https://developer.spotify.com/web-api/endpoint-reference/)

**Comment by mrosscoe** [comment]
Seems to work now - website must have been fixed. Thanks for the update.
