### ISSUE TITLE
Analysis Object Endpoint 504 Gateway Time-out

### ISSUE THREAD

**Issue by ianmcfarlane** [spotify/web-api#427]
Issue found on February 21st 2017.

#### Endpoint(s):
* `GET /v1/audio-analysis/{id}`

#### Scope(s):
* Authorized w/ implicit grant flow and no scopes, just publicly available information. Although optional, I tried with different scopes, but as expected, had no effect on the behavior.

#### Steps to reproduce:
1. Request outside of Web API Console, the endpoint performs as expect when using the API Console.
2. Call the 'audio-analysis' endpoint with any track id

#### Expected behaviour:
Analysis object w/ status 200 or any response status listed here https://developer.spotify.com/web-api/user-guide/#response-status-codes

#### Actual behaviour:
504 Gateway Time-out (very consistent today, intermittent in the past).

Any thoughts as to what could be going on here would be much appreciated. Example below.

`$ curl -X GET "https://api.spotify.com/v1/audio-analysis/1cG0umU5TKStygKsPFZ9pY" -H "Accept: application/json" -H "Authorization: Bearer BQCoMROxl40M_Sff1DBc_-zWX0ChF47eKBR2-cqegIUHBBp99Bop9RWv5T6oY9gs4Fr5QUa2dpu7Xq_OzQObA-IUB0-ifUSLyuAMK09aBYppO7BAgRHTljOjRbumZVPFpfSa9kdxxC3iA6w"`
`<html>`
`<head><title>504 Gateway Time-out</title></head>`
`<body bgcolor="white">`
`<center><h1>504 Gateway Time-out</h1></center>`
`<hr><center>nginx</center>`
`</body>`
`</html>`

**Comment by hughrawlinson** [comment]
Hey @ianmcfarlane - I've just double checked that the analysis endpoint is working. This sounds to me like there was an issue at the time with the service that is now resolved. Please feel free to reopen this ticket if you're still having the issue.

**Comment by ianmcfarlane** [comment]
@hughrawlinson Thanks for the followup.
