### ISSUE TITLE
Is it possible to implement play button but avoid this login  restriction?

### ISSUE THREAD

**Issue by tlss94** [spotify/web-api#428]
Hi,

I would like to add a play button on my blog so that any visitors can listen to the music  but I read that it request people login??
Is there any way to circumvent that?

Thanks!

Also where can I find a complete code lines for python other than github which I find it is not very easy for beginner to understand which files correspond to what and how to assemble that.

**Comment by tlss94** [comment]
Ok thank you!
btw I wondered what is the difference between getting informqtion without providing secret ID through
import spotipy
sp = spotipy.Spotify()

results = sp.search(q='weezer', limit=20)
for i, t in enumerate(results['tracks']['items']):
    print ' ', i, t['name']

and the method that require secret ID ...?

thank you !

**Comment by hughrawlinson** [comment]
Hi @tlss94

To use the play button to play full tracks, the user must be logged in.

With the python examples, what exactly are you looking to do with the python code? You can always search for examples on StackOverflow.

As for your final question, there's currently no difference between authenticated and unauthenticated search results, but as of May 29th unauthenticated API calls will be removed, and an access token will be required. Please see [our blog post](https://developer.spotify.com/news-stories/2017/01/27/removing-unauthenticated-calls-to-the-web-api/) for more information. Once authentication is required, you can use an auth token from any of our three oauth flows to make the request. The `client credentials` flow will yield a token that doesn't correspond to a user, but the other two flows (`authorization code` and `explicit grant`) yield tokens that correspond to the logged in user, and search will return personalised results for that user. For more information on authorization, please see our [Authorization Guide](https://developer.spotify.com/news-stories/2017/01/27/removing-unauthenticated-calls-to-the-web-api/). Hope that helps!

**Comment by tlss94** [comment]
Ok thanks for your answer ! I will look into it !
I was looking for some example code that show you how to log in and request data with authentification
such as in the yelp API:

 *import requests
app_id = 
app_secret = 
data = {'grant_type': 'client_credentials',
        'client_id': app_id,
        'client_secret': app_secret}
token = requests.post('https://api.yelp.com/oauth2/token', data=data)
access_token = token.json()['access_token']
url = 'https://api.yelp.com/v3/businesses/search'
headers = {'Authorization': 'bearer %s' % access_token}

    params = {'location': '',
              #'categories': '',
              'limit':'1',
              'offset':0,
              'term':''           
             }  
   resp = requests.get(url=url, params=params, headers=headers)
    l=resp.json()*
   


btw is it possible to get social tags for artist/ album or tags??  even tags provided by users??
