### ISSUE TITLE
Get Followed Artists returning Null in incorrect cases

### ISSUE THREAD

**Issue by chasenyc** [spotify/web-api#429]
Issue found on February 19th 2015.

Intermittent user followed artists not returning correctly. In all cases if done through the web api no matter the account we receive the proper list. With multiple different accounts, one of these accounts when curling the same command provided by web-console we receive null for artists, other spotify accounts return the appropriate artists when curled. This seems to possibly be a [recurring issue.](https://github.com/spotify/web-api/issues/156)

#### Endpoint(s):
* `GET https://api.spotify.com/v1/me/following `

#### Scope(s):
* user-follow-read

#### Steps to reproduce:
1. Open the API Console
2. Call the `Get Followed Artists` endpoint and everything works (populated with artists.
3. Copy curl command and paste in terminal or hit endpoint through postman / native client and receive null.

#### Expected behaviour:
Return a list of followed artists.

#### Actual behaviour:
Returned:

```
{
  "artists" : {
    "items" : [ ],
    "next" : null,
    "total" : 0,
    "cursors" : {
      "after" : null
    },
    "limit" : 20,
    "href" : "https://api.spotify.com/v1/me/following?type=artist&limit=20"
  }
}
```

**Comment by hughrawlinson** [comment]
Hi! Could you give me your client id (not your access token) and the ID of the user so I can debug?

**Comment by chasenyc** [comment]
This issue seemed to resolve itself. if it helps at all the artist follows were relatively new(that same day). Not sure why the web console would have results while curling wouldn't. It seems as if you wont be able to see any problem now, regardless, the user ID is 22qlvdyfcizivxbnczb5dic7a. I don't believe the client ID was being used as we were just copying and pasting the web console's curl url. The client ID is f7015c33dc97458ba1f79e3a3323c7a9.

**Comment by hughrawlinson** [comment]
> this issue seemed to resolve itself

In that case, I'll close the issue. Feel free to reopen it if you encounter this issue again.

> I don't believe the client ID was being used as we were just copying and pasting the web console's curl url

The client ID is tied to the auth token that is part of the curl command if you authenticate. If you didn't copy the auth token, that would cause this issue as it's a `me` endpoint and therefore requires an auth token tied to a user login.
