### ISSUE TITLE
Search for Playlists crashing/returning 500 with specific limit and offset

### ISSUE THREAD

**Issue by rolandjohann** [spotify/web-api#432]
#### Endpoint(s):
* `GET https://api.spotify.com/v1/search`

#### Scope(s):
* None (application is not using authentication)

#### Steps to reproduce:
call `https://api.spotify.com/v1/search?type=playlist&query=name:*&offset=2850&limit=50`

#### Expected behaviour:
Response with 200 status code and proper response body

#### Actual behaviour:
```
{
    error: {
        status: 500,
        message: "Server error."
    }
}
```

**Comment by rmmjohann** [comment]
I'm sorry to have to push that issue. The git spam detector flagged my account so this issues had been invisible until now.
