### ISSUE TITLE
Playlist cover removed after an update of the title and/or the description

### ISSUE THREAD

**Issue by davidbillamboz** [spotify/web-api#433]
#### Endpoint(s):
* `PUT https://api.spotify.com/v1/users/{user_id}/playlists/{playlist_id}`

#### Scope(s):
* playlist-modify-public

#### Steps to reproduce:
1. Create a playlist
2. Set a cover for the playlist
3. [Go to the API console](https://developer.spotify.com/web-api/console/put-playlist/)
4. Set new title + new description
4. Reboot Spotify to refresh the cache

#### Expected behaviour:
The title and the description are updated and the cover is still there.

#### Actual behaviour:
The title and the description are updated and the cover is removed.

**Comment by asmitter** [comment]
Thanks for the report - we'll take a look.

**Comment by asmitter** [comment]
We found the issue and deployed a fix. Let us know if you have any more problems.

**Comment by davidbillamboz** [comment]
It seems to be fixed from our side as well.
Thank you Andy!
