### ISSUE TITLE
Get playlist returning 404 not found when trying to retrieve Discover Weekly Playlist

### ISSUE THREAD

**Issue by timdiacon** [spotify/web-api#434]
Get playlist returning 404 not found when trying to retrieve Discover Weekly Playlist

#### Endpoint(s):
* `GET v1/users/spotifydiscover/playlists/{playlistID}/tracks`

#### Scope(s):
* User (requesting playlist using access token)

#### Steps to reproduce:
* make an authenticated call to the above endpoint for your Discover Weekly Playlist ID

#### Expected behaviour:
The playlist should be returned

#### Actual behaviour:
Returns 404 JSON package
`{
  "error": {
    "status": 404,
    "message": "Not found."
  }
}`

**Comment by hughrawlinson** [comment]
Hey @timdiacon - could you give me the playlist ID so I can debug?

**Comment by hughrawlinson** [comment]
Also worth mentioning - if you've cached that URI for a while, it's possible that the ID has changed. Consider double checking the URI of the discover weekly playlist you're trying to find.

**Comment by timdiacon** [comment]
37i9dQZEVXcJEB08dKtQV4

**Comment by martimgalvao** [comment]
I am also having the same issue. Checked the ID to make sure it is current. All other playlists work fine.

**Comment by hughrawlinson** [comment]
Looks like that playlist is owned by the `spotify` user rather than the `spotifydiscover` user. I made the request to that playlist using the 'spotify' user and it worked 😄 

Let me know if I can help further!

**Comment by martimgalvao** [comment]
Thanks. Looks like my problem was that I was trying to get the Discover Weekly playlist with the user's owner ID. Changing the owner ID to 'spotify' fixed it.

**Comment by hughrawlinson** [comment]
@martimgalvao in the example that @timdiacon gave, the owner of the playlist was 'spotify'. Is your playlist listed as being owned by 'spotifydiscover' somewhere?

**Comment by martimgalvao** [comment]
Not as far as I can tell. I was just using the user's ID for the {user_id} portion instead of grabbing it from the playlist owner.

**Comment by hughrawlinson** [comment]
@martimgalvao ah yes, that'd do it. Cool! 😄

**Comment by nikolasleblanc** [comment]
Hey everyone, new here. Has code been contributed for conditionally setting the playlist owner based on playlist name?
