### ISSUE TITLE
Add support for user type in me/following endpoint

### ISSUE THREAD

**Issue by mbc1990** [spotify/web-api#439]
I would like to build a tool that generates playlists based on what a user's friends have been listening to, however per the api documentation of the `type` parameter: `Required. The ID type: currently only artist is supported.` 

Thanks folks, keep up the good work!

**Comment by hughrawlinson** [comment]
Hey @mbc1990 - we've already got a feature request for this #4, so I'll close this as a duplicate. Updates will appear on our Twitter account (@SpotifyPlatform)[twitter.com/spotifyplatform], and on that issue if anything changes.

**Comment by goodwordalchemy** [comment]
This issue shouldn't be closed.  You have a circular reference in your closed issues.

**Comment by goodwordalchemy** [comment]
This would be an awesome feature.  Is there any reason it hasn't been implemented yet?
