### ISSUE TITLE
Playlists

### ISSUE THREAD

**Issue by santim21** [spotify/web-api#44]
Hello, i had this idea the other day. I'm currently working on a playlist for a party, and i came up with a project whose difficulty to integrate i don't know, but would be awesome if you could put it in the next spotify update. My idea is having playlists where songs can be added from two different accounts. I look forward to seeing it in the next version update

**Comment by thelinmichael** [comment]
Hi @santim21, thanks for contacting us. Ideas for the desktop and mobile applications are best handled by the [Spotify's Community forum](https://community.spotify.com/). (This Github repository is dedicated to [Spotify's Web API](https://developer.spotify.com/web-api).) Although it does seem like what you're really looking for is to simply create a playlist and make it `collaborative`.
