### ISSUE TITLE
Use `type` consistently as a path or query parameter

### ISSUE THREAD

**Issue by mbc1990** [spotify/web-api#440]
`type` is a query parameter in this call
https://developer.spotify.com/web-api/get-followed-artists/

`type` is a path parameter in this call
https://developer.spotify.com/web-api/get-users-top-artists-and-tracks/

The inconsistency is confusing. Thanks!

**Comment by hughrawlinson** [comment]
Thanks for the feedback! I'll pass it on to the team and see what they think.

**Comment by bih** [comment]
Hey @mbc1990,

Thanks for your patience. Given that we haven't received any other feedback about it being confusing (both on this thread and through other channels), we decided to keep it as is. Of course, if you have more evidence to help support that more users are confused by this documentation, feel free to open a new ticket and we'll consider revisiting this feature request! Hope this helps 🙂

Best,
Bil
