### ISSUE TITLE
some field filters deprecated ?

### ISSUE THREAD

**Issue by hycday** [spotify/web-api#441]
As per Spotify documentation (https://developer.spotify.com/web-api/search-item/), we can use Field filters in the query.

I never get any result when adding the `tag:new` filter. Is it deprecated ?

Any updated list of available field filters ?

**Comment by hughrawlinson** [comment]
Thanks for letting us know about this! I'll chase this up and get back to you. Thanks!

**Comment by hughrawlinson** [comment]
@hycday - the `tag:new` filter works on the album search type. I'll make sure to update the documentation to indicate that it's specific to it. Thanks!
