### ISSUE TITLE
Get a list of all available Spotify markets

### ISSUE THREAD

**Issue by hycday** [spotify/web-api#442]
Where can we get the list of all available_markets ? or all markets in which Spotify is launched (guess that's the same).

**Comment by hughrawlinson** [comment]
Thanks for the request @hycday - I'll chase this up with the team.

**Comment by wilsonpage** [comment]
I made [this gist](https://gist.github.com/wilsonpage/503092f6cd87f9152d5a523bb82ce730) based off of [this list](https://www.spotify.com/us/select-your-country/) referenced on Wikipedia. Would be good if someone at Spotify could keep it up-to-date :)

**Comment by bih** [comment]
Hello @,

Thanks for your feature request! We're in the process of cleaning up our GitHub issue tracker (as per our [new developer support process](https://github.com/spotify/web-api)) to better serve you and other developers.

In this particular case, we discussed this and there isn't enough use cases or demand for creating this endpoint. Any specific use cases are still able to create a manual list of Spotify markets. For that reason I'm going to close this as <kbd>wontfix</kbd>.

Though I encourage you and other developers to continue to share use cases and support for this feature - it helps us prioritize features in the future. You should still be able to comment on this issue. We will post updates here if there are any updates relating to this ticket 🙂

Thank you for taking the time to share your feedback, and please continue to do so! We highly appreciate it and of course reach out if you have any other questions!

Cheers 👍
