### ISSUE TITLE
Right click on a playlist and export the Track Artist and Album info into a text file or Excel worksheet.

### ISSUE THREAD

**Issue by Sludgeguts** [spotify/web-api#443]
A feature where I can Right click a playlist and export the contents of the playlist into a text file.  I would like to choose what to export   Ie Track title, artist ect  .
Would help alot.

Thanks for your interest in the Spotify Web API!
If you're submitting a bug, please use the following template.
If your issue is a feature request, please include your use-case so that we have all the necessary info.

-->

Issue found on February 19th 2015.

#### Endpoint(s):
* `GET /v1/users/{user_id}`

#### Scope(s):
* None (application is not using authentication)

#### Steps to reproduce:
1. Open the API Console
2. Call the `get-users-profile` endpoint with `user_id` `%5E`

#### Expected behaviour:
A public user object as described on `https://developer.spotify.com/web-api/object-model/#user-object-public`.

#### Actual behaviour:
500 Server Error (consistently)

**Comment by kvanzuijlen** [comment]
> A feature where I can Right click a playlist and export the contents of the playlist into a text file. I would like to choose what to export Ie Track title, artist ect .
Would help alot.

What does this have to do with the Web API? This is a feature you should build yourself using the JSON data returned by the correct endpoint (which isn't `/v1/users/{user_id}`).

If you want this feature to be implemented in the Spotify App then you should do a feature request on the Spotify forums and you should not create a new issue in the Spotify Web API repo.

**Comment by hughrawlinson** [comment]
Hey - looks like this is a feature request for the Spotify Client. You can make those kinds of feature requests on our [Community](community.spotify.com) website, but this issue tracker is for our Web API. Thanks!
