### ISSUE TITLE
Payment for premium in app

### ISSUE THREAD

**Issue by arvindd87** [spotify/web-api#448]
Product vision: A one stop hub to purchase digital products using alternative currency (emoney used to pay for Spotify codes/direct subscription)

Objective: 
1. To make digital products more accessible to the users who are vary of putting in credit card details in multiple services by offering them a one stop shop to manage all their digital subscriptions.
2. To also remove the hassle for service providers to manage payments and are better off concentrating on content and user experience in their app.

The guidance needed is for my users to pay for Spotify premium in my app using either:
1. Code
2. Direct payment via emoney stored in my vault
*has to work via API calls*

For good user experience, in the Get Current User's Profile API call to also add in info for:
1. subscription details: expiry date (if used code to pay)
2. subscription details: renew date (if used emoney to pay)

**Comment by hughrawlinson** [comment]
Hey @arvindd87 - we're not intending to publish any public APIs related to paying for premium at the moment. Thanks!
