### ISSUE TITLE
Unexpected status: 400 when /api/token

### ISSUE THREAD

**Issue by rakemous** [spotify/web-api#449]
I have created a Java app that calls the Spotify endpoint: https://accounts.spotify.com/api/token
that gives me a 400 error: "{"error":"server_error","error_description":"Unexpected status: 400"}" with the following request:

> bash-3.2$ nc -l 127.0.0.1 1234
> POST /api/token HTTP/1.1
> Authorization: Basic Z...=
> Accept: */*
> Connection: keep-alive
> Cache-Control: no-cache
> Accept-Language: en-GB,en-US;q=0.8,en;q=0.6
> Accept-Encoding: gzip, deflate, br
> Origin: chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop
> Content-Type: application/x-www-form-urlencoded
> Content-Length: 460
> Host: localhost:1234
> User-Agent: Apache-HttpClient/4.3.5 (java 1.5)
> 
> code=a_code...&grant_type=authorization_code&redirect_uri=my_redirect_url

This request is right before I change the config to point to `https://accounts.spotify.com` instead 
`http://localhost` (I switched to http and localhost before to see the request with nc)

#### Expected behaviour:
A JSON response retrieving a refresh and access token for that a_code.

#### Actual behaviour:
400 Bad Request (consistently) saying "Unexpected status: 400"

Any help would be much appreciated.
Thanks!

**Comment by hughrawlinson** [comment]
Hey @rakemous - this issue usually comes up when the Basic authorization value hasn't been created correctly. Could you paste your Java code for constructing that string?

**Comment by rakemous** [comment]
Hi @hughrawlinson - this is how I build that header: 
`    public static final String AUTH_HEADER = "Basic " + DatatypeConverter.printBase64Binary((CLIENT_ID + ":" + CLIENT_SECRET).getBytes());
`

**Comment by hughrawlinson** [comment]
Hey @rakemous - [here's](https://github.com/thelinmichael/spotify-web-api-java/blob/master/src/main/java/com/wrapper/spotify/methods/authentication/AuthorizationCodeGrantRequest.java#L68) an example implementation of that flow in Java. It's in a repo containing an API wrapper library for Java that you may find useful!

Please let me know if that helps.

**Comment by wokalski** [comment]
In my case it was missing `Content-Type` header. It should be `"Content-Type": "application/x-www-form-urlencoded"`.

**Comment by atorstling** [comment]
I would argue that this is a bug, the content-type is not 'applicaiton/x-www-form-urlencoded'. But this value is the only value which works. If you set 'Content-Type' to 'application/json' you get a even more obscure error:

```
<!DOCTYPE html>\n<html ng-app="accounts" ng-csp>\n  <head>\n    <meta charset="utf-8">\n    <title>Error - Spotify</title>\n    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">\n    <base href="/">\n    <link href="https://d2d1dxiu3v1f2i.cloudfront.net/496c5b7/css/index.css" media="screen" rel="stylesheet">\n  </head>\n  <body>\n  <div class="head">\n    <a class="spotify-logo" href="/" tabindex="-1" title="Spotify"></a>\n  </div>\n\n    <div class="container-fluid error">\n      <div class="content">\n        <h1 class="h1">Error</h1>\n        <p>\n          Oops! Something went wrong, please try again or check out our <a href="https://www.spotify.com/help">help area</a>.\n        </p>\n      </div>\n    </div>\n    <script async defer src="https://d2d1dxiu3v1f2i.cloudfront.net/496c5b7/js/error.js" sp-error=\'\'></script>\n  </body>\n</html>\n
```
