### ISSUE TITLE
Searches fail if using asterisk on words with diacritics

### ISSUE THREAD

**Issue by Foldalake** [spotify/web-api#451]
Issue found on March 15th, 2017.

Asterisks don't work with words that contain non-A-Z latin letters (letters with umlauts, accents etc). Search words that contain ä, ö, æ, ü, ñ, Č, Ł, ß, ĳ etc and end with an asterisk will always return 0 results.

I tried using asterisks with the Greek, Russian and Japanese alphabets and it seems to work fine, but I'm not familiar with how they work with diacritics so you may want to test that on your end too...

We have added an asterisk to the end of our search query in our free text search field because we feel that it generally improves the quality of results from the search endpoint. For instance, "ramm" does not find Rammstein, whereas "ramm*" does.

#### Endpoint(s):
* `GET v1/search`

#### Scope(s):
* Not relevant (but we use playlist-read-private, playlist-read-collaborative, user-follow-modify, user-library-read, user-library-modify, user-read-private, user-follow-read)

#### Steps to reproduce:
1. Open the API Console
2. Call the search endpoint with "track" as item type and a query with a word containing a diacritic followed by an asterisk (e.g. bättr*, så mycket bä*, så mycket bättre*)

#### Expected behaviour:
Returns a list of tracks that matches the query.

#### Actual behaviour:
Returns a response with zero track items in it.

#### Additional notes:
The following track searches will return tracks related to Swedish TV show "Så mycket bättre" (because the asterisk is appended to words that don't contain diacritics):
så mycket batt*
bättre så mycket*

Fun fact: This track search unexpectedly returns a song called "Ba Ba Ba":
så mycket bä
(I get that this is some kind of simplification treating ä as a, but it's kind of weird...)

**Comment by hughrawlinson** [comment]
@Foldalake I've reported this issue to the team, thanks for submitting it!

**Comment by hughrawlinson** [comment]
Hey @Foldalake - the teams are investigating a fix for this, but in the mean time you can get around this issue by ascii-folding your search queries. I'll update this issue once we have addressed it. Thanks!

**Comment by Foldalake** [comment]
Looks like this issue is fixed now!
