### ISSUE TITLE
Return context for currently playing song in Applescript api

### ISSUE THREAD

**Issue by tal** [spotify/web-api#452]
Apologies, this isn't directly related to the web api, but i couldn't find where to request this.

I'd love if the applescript api for interacting with the client and returning the currently playing song could include the context that it's playing in (current playlist/album/etc). Optionally this could be a property of the application rather than the track. Whatever makes the most sense.

Thanks!

**Comment by kvanzuijlen** [comment]
Hi @tal,

See https://developer.spotify.com/applescript-api/#support where you should report bugs for the Applescript API.

Report bugs at the [Community site](https://community.spotify.com/t5/Help-Desktop-Linux-Mac-and/bd-p/001)

**Comment by hughrawlinson** [comment]
👍 , support for the Applescript API is handled on the [Community Site](https://community.spotify.com/t5/Help-Desktop-Linux-Mac-and/bd-p/001)
