### ISSUE TITLE
Add to queue

### ISSUE THREAD

**Issue by M4sterZer0** [spotify/web-api#453]
Issue found on February 19th 2015.

#### Endpoint(s):
* `GET remote/play.json?uri={url}?action=queue`

#### Scope(s):
* All

#### Actual behaviour:
The song is played directly. Was the parameter changed or completely removed?

**Comment by jscholes** [comment]
> GET remote/play.json?uri={url}?action=queue

This is a part of the unofficial Web Helper protocol and not the Web API.  As such, it isn't supported in any way by Spotify and is unlikely to be fixed unless one of their official partners (Last.fm etc) requires the functionality.

**Comment by M4sterZer0** [comment]
Thanks for your answer @jscholes. Exist a other way to add song to the queue?

**Comment by hughrawlinson** [comment]
Hey @M4sterZer0 - as @jscholes mentioned this isn't part of any public Spotify API, and we don't support it. There is a feature request for this #170, so I'll close this issue and you can follow that one for any updates.
