### ISSUE TITLE
New Releases not aligned with Release Radar

### ISSUE THREAD

**Issue by danwani** [spotify/web-api#454]
Hi,
I've noticed quite a disconnect between the data provided through the New Releases endpoint versus what is presented in the Release Radar, with a lot of items present in Release Radar not appearing in the New Releases endpoint.  Our users have also noticed the difference.  I would have expected the same content to be present in both.  I've verified this isn't related to the region filters in play.  Should we expect the same content, or is this a limited subset of all releases?  If so, how is the selection made?

Issue found on March 18th 2017.
GET /v1/browse/new-releases

Thanks,
Dan.

**Comment by hughrawlinson** [comment]
Hey @danwani - Release Radar and New Releases are different things. [Release Radar](https://news.spotify.com/se/2016/08/05/release-radar-your-personalized-playlist-of-the-newest-releases/) is a personalised playlist for the specific logged in user, like Discover Weekly. New Releases on the other hand is the selection of chosen new releases that appear in the 'new releases' tab of the 'browse' page in the Spotify client.

Hope that helps!

**Comment by danwani** [comment]
Hi @hughrawlinson,
Thanks for getting back to me so quick.  Your feedback makes sense and is inline with what we've observed.  So just to clarify - the New Releases endpoint is a cut down list of the releases available on the platform?  Is there any way to gain access to all releases?  
The issue is that with Release Radar it's very obvious what new releases have come out, but these are not present on the new releases feed.
Thanks,
Dan.

**Comment by hughrawlinson** [comment]
That's right - the new releases endpoint returns a subset of the new releases on the platform. There's no endpoint to access all new releases.
