### ISSUE TITLE
Create field filter for musicbrainz ID in the search endpoint

### ISSUE THREAD

**Issue by bibliotechy** [spotify/web-api#455]
In the search endpoint, it would be great to have an field filter for external url identifiers, like MusicBrainz ID, to identify bands and albums. Would help to integrate spotify resources with data from other sites.

**Comment by hughrawlinson** [comment]
Hi @bibliotechy - thanks for the feature request! This issue is already being tracked as part of #241, so I'll close this one and post any updates there for you to subscribe to. If you feel that this is an error, please let me know!
