### ISSUE TITLE
500 Error when Playlist Name is greater than 200 characters long

### ISSUE THREAD

**Issue by phealy1982** [spotify/web-api#456]
Issue found on March 21 2017.

#### Endpoint(s):
* `PUT /users/{user_id}/playlists/{playlist_id}`

#### Scope(s):
* playlist-modify-public, playlist-modify-private

#### Steps to reproduce:
1. Open the API Console
2. Call the `Change a Playlist's Details` endpoint with `name` greater than 200 characters long

#### Expected behaviour:
400  (Bad Request) for "name" attribute length.

#### Actual behaviour:
500 Server Error (consistently)

**Comment by hughrawlinson** [comment]
Thanks for the report @phealy1982, the team is looking into it.

**Comment by asmitter** [comment]
This has now been fixed - thanks for reporting!

**Comment by blackarcanis** [comment]
@asmitter To be more precise, could you tell us the length max for a "title" and "description" field ?
