### ISSUE TITLE
Outdated Documentation for Artist's Top Tracks Endpoint

### ISSUE THREAD

**Issue by jscholes** [spotify/web-api#457]
The documentation for the [Get an Artist's Top Tracks](https://developer.spotify.com/web-api/get-artists-top-tracks/) endpoint says the following:

> If you want to fetch more artist’s top tracks, an alternative way is to use Echo Nest song/search to accomplish this. It will accept a Spotify artist id for input and give you Spotify id’s in the output.

This is obviously no longer relevant (and as an aside, leaves no alternative method to accomplish it).

**Comment by asmitter** [comment]
Thanks for flagging that -  I've fixed the doc.

**Comment by jscholes** [comment]
> Thanks for flagging that - I've fixed the doc.

Great fast response, but now the page is throwing a 404 :)
-- 
James Scholes
http://twitter.com/JamesScholes

**Comment by hughrawlinson** [comment]
@jscholes just double checked it, it should be fine now. Thanks for reporting!
