### ISSUE TITLE
Outdated documentation for Create a Playlist

### ISSUE THREAD

**Issue by lrholmes** [spotify/web-api#459]
I've noticed that we are now able to post a `description` when creating a playlist. This is really cool! (Any progress on posting a playlist cover too? 🙏)

While it works perfectly, it is not described in the documentation at https://developer.spotify.com/web-api/create-playlist/ so lots of developers are probably missing out on this. I only noticed it was available when browsing another issue here. It may also be worth updating those who watch issue #112 that description modification is now working.

**Comment by hughrawlinson** [comment]
Thanks for letting us know @lrholmes, we've updated the documentation and the API console.
