### ISSUE TITLE
A way to access older snapshot_ids in retrospect?

### ISSUE THREAD

**Issue by modkaffes** [spotify/web-api#460]
I initally asked this question in [thelinmichael/spotify-web-api-node](https://github.com/thelinmichael/spotify-web-api-node/issues/92#issuecomment-289690817) and I was pointed here.

I was wondering if the ability to access older states of a playlist (eg. Discover Weekly) is implemented. 

I'm aware of this [IFTTT applet](https://ifttt.com/applets/313481p-save-your-discover-weekly-tracks-to-a-playlist), but if I understand this correctly, it works from the point you enable it forward.

So, can I access older snapshot_ids?

**Comment by hughrawlinson** [comment]
There's no currently available API to access old snapshot_ids. I'll take this as a feature request, but I can say that we don't have any current plans to implement an endpoint like this.

**Comment by hughrawlinson** [comment]
The team has got back to me - for technical reasons, we're not going to be able to build this feature. Thanks for getting in touch though!

**Comment by modkaffes** [comment]
Thanks for letting me know!
