### ISSUE TITLE
Audio Analysis API output is sometimes truncated

### ISSUE THREAD

**Issue by fascinated** [spotify/web-api#461]
Issue found on March 30th 2017.

#### Endpoint(s):
* `GET /v1/audio-analysis/{id}`

#### Scope(s):
* None (application is not using authentication)

#### Steps to reproduce:
1. Open the API Console
2. Call the `audio-analysis` endpoint with `id` `2aGdUcIFCB8vjxqibN3JhZ`

Or alternatively via curl
curl -X GET "https://api.spotify.com/v1/audio-analysis/2aGdUcIFCB8vjxqibN3JhZ" -H "Accept: application/json" -H "Authorization: Bearer TOKEN_HERE"

#### Expected behaviour:
Valid JSON output.

#### Actual behaviour:
Partial JSON output that appears to be abruptly truncated. Perhaps this track has too many features and exceeds some sort of buffer.

**Comment by kvanzuijlen** [comment]
Just tested this, with that exact ID. It's working absolutely fine for me. For me, it returns an audio features object that matches the audio features object as found in the docs.

**Comment by fascinated** [comment]
Hmm, strange, I am still seeing the partial JSON issue. It is easier to see if you look at the final 300 bytes of the output:

```
curl -s -X GET "https://api.spotify.com/v1/audio-analysis/2aGdUcIFCB8vjxqibN3JhZ" -H "Accept: application/json" -H "Authorization: Bearer TOKEN_HERE" | tail -c 300
:-21.864, "pitches":[0.060, 0.086, 0.097, 0.064, 0.084, 0.036, 0.049, 0.286, 1.000, 0.763, 0.171, 0.169], "timbre":[34.824, -57.375, 21.980, -41.177, 8.720, -34.382, 63.914, 20.276, -0.483, 6.544, -0.538, 21.625]}, {"start":269.50789, "duration":0.61592, "confidence":0.747, "loudness_start":-27.781,
```

**Comment by hughrawlinson** [comment]
Thanks for letting us know about this - it appears that this is a bug. I will pass it on to the relevant team and update you on this ticket when I hear anything.

**Comment by hughrawlinson** [comment]
Hi - the response for that ID is now fixed. Please let us know if you encounter any more IDs with a truncated response.

**Comment by fascinated** [comment]
Thanks @hughrawlinson! I can confirm that this is working and will keep an eye out for other issues.
