### ISSUE TITLE
Show performance data for a touring artist

### ISSUE THREAD

**Issue by jshakes** [spotify/web-api#465]
I noticed that in the Spotify desktop application, an artist's page is populated with information on upcoming tour dates (as listed in Songkick). Would it be possible to expose this same data in the artist endpoint? Even if it weren't fully populated, an array of Songkick event IDs would be really helpful. 

I'm making an application that helps people find artists playing in their area based on tracks in their Discover Weekly playlist, so this would be really helpful.

**Comment by hughrawlinson** [comment]
Hey,

We have no current plans to expose this data, but have you considered using the [SongKick API](http://www.songkick.com/developer)?

**Comment by jshakes** [comment]
Yeah I have been using that and most of the time it's great, but because I have to look up the artist by string search it doesn't give me reliable results 100% of the time, eg if two artists have the same name or if it's a band that's awkward to search for like [!!!](https://en.wikipedia.org/wiki/!!!). If the IDs of Songkick events were exposed then it would be a sure thing to map Spotify artists to Songkick events.

**Comment by hughrawlinson** [comment]
Hey @jshakes - so it sounds to me like this feature request is really a request for a mapping between Spotify's ID space and that of Songkick - that's already covered by issue #241. Please feel free to add your voice to that ticket!
