### ISSUE TITLE
Add ability to add query parameter with TITLE,ALBUM,ARTIST,DATE_ADDED

### ISSUE THREAD

**Issue by jai-zeng** [spotify/web-api#466]
#### Endpoint(s):
* `GET	/v1/me/playlists`

I want the response data sorted by TITLE,ALBUM,ARTIST,DATE_ADDED when using this endpoint. Any idea?

If the playlist has 500 tracks, and the user selects "sort by ALBUM", my app get 50 tracks one time, so it can append these tracks without re-sorting.

**Comment by hughrawlinson** [comment]
Hey @jai-zeng - if I understand your request correctly, this feature request is already being tracked at #75. Please feel free to add feedback there. If you feel that I've misunderstood, please reopen this ticket and let me know!
