### ISSUE TITLE
Authentication Flow

### ISSUE THREAD

**Issue by mikeread1967** [spotify/web-api#468]
We have an audio app and want to integrate Spotify api functionality into this.  It makes sense to us to offer Spotify authentication for the app (as we do for Facebook and Google users).  Do you have any plans to offer an authentication flow?

**Comment by jscholes** [comment]
You can already authenticate users with the web API - see the [Authorization Guide here](https://developer.spotify.com/web-api/authorization-guide/).

**Comment by mikeread1967** [comment]
Thanks @jscholes. I'm looking to Authenticate a user through Spotify, not get authorization to access their account.  I can't see how to do that through the Authorization guide without leaving ourselves open to a man in the middle attack (unless i'm not understanding the flow correctly?)

**Comment by jscholes** [comment]
> I'm looking to Authenticate a user through Spotify, not get 
authorization to access their account.

I could be wrong, as I haven't worked much with OAuth, but I don't quite 
understand the difference.

1. The user authorizes your app, redirecting back to a URI within it.
2. Your app exchanges the received authorization code for an access 
token (probably server-side).
3. You can then fetch the user's profile from Spotify's API to confirm 
they are who they say they are.  If the profile comes back, everything 
has worked as expected and you can then use the information within the 
profile (e.g. user ID/email) to display and store login status.
4. If you get an error when requesting the profile using the token, 
something has gone wrong.

As far as I'm aware, this is exactly the same flow you would follow if 
you were to implement a manual Facebook login flow, as described 
[here](https://developers.facebook.com/docs/facebook-login/manually-build-a-login-flow). 
  If you're exchanging an authorization code for an access token 
server-side, and also fetching the user's profile from code running on 
your server, then I'm unclear how a man-in-the-middle attack could be 
used to comprimise your application or users.

**Comment by mikeread1967** [comment]
Thanks James, you put me on the right track.  I just needed to do the token
exchange think on the server so that the clients don't need to hold the
client_secret.
