### ISSUE TITLE
/v1/me show Full Name.

### ISSUE THREAD

**Issue by slandersson** [spotify/web-api#469]
Full names are publicly visible on profiles so why not through the API as well as the username etc?

**Comment by hughrawlinson** [comment]
Hi @slandersson - the users full name is visible on the `/v1/me` endpoint under the field `display_name`. Hope that helps!

**Comment by slandersson** [comment]
Interestingly for me it returns 
"display_name" : null,
Even though my full name is definitely on spotify as it's linked to facebook.
