### ISSUE TITLE
Get "following" count

### ISSUE THREAD

**Issue by vemv** [spotify/web-api#47]
I wrote a utility for following artists.

I want it to have a confirmation, e.g. "You are following N artists now, and you would follow M artists if you confirm the action. Proceed?"

Problem is, there's no way to know N.

I don't see the issue with adding an endpoint with following count to https://developer.spotify.com/web-api/web-api-follow-endpoints/ ?

**Comment by thelinmichael** [comment]
Not the same but related to #4. (List of Artists & Users a user follows)

**Comment by thelinmichael** [comment]
@vemv, this use case should now be satisfied with the [Get Followed Artists endpoint](https://developer.spotify.com/web-api/get-followed-artists/)'s `total` property.

**Comment by vemv-kantox** [comment]
@thelinmichael thanks much! Appreciated.
