### ISSUE TITLE
/v1/me/top/Artists - more than 50 artists, exact playcounts or weightings

### ISSUE THREAD

**Issue by slandersson** [spotify/web-api#470]
As the title.

More detailed listening history in any way would be fantastic.

**Comment by hughrawlinson** [comment]
Thanks for the request. It'd be great if you could split it up into individual, specific requests, that way we can investigate each of them independently. I'll keep this around in the mean time.

**Comment by slandersson** [comment]
https://github.com/spotify/web-api/issues/477
https://github.com/spotify/web-api/issues/478

done!

**Comment by arirawr** [comment]
This has been split into #477 and #478 so I'm going to close this issue :)
