### ISSUE TITLE
Offset in `player/play` isn't zero-based, but docs say so

### ISSUE THREAD

**Issue by tjhorner** [spotify/web-api#471]
Issue found on 10 April 2017.

#### Endpoint(s):
* `PUT /v1/me/player/play`

#### Scope(s):
* Authorized user via Connect API

#### Steps to reproduce:
1. Create a playlist with 5 tracks.
2. Copy the URI of that playlist.
3. Put the URI into the `context_uri` of the request.
4. Set `offset` to `{ "position": 0 }`.
5. Send the request and notice how nothing plays. But if you set `position` to 1, it will play the first song.

#### Expected behavior:
The first song in the playlist should play, since the docs [here](https://developer.spotify.com/web-api/start-a-users-playback/) say that `position` is zero-based, so the first song should be `0` and not `1`.

#### Actual behaviour:
The user's current Spotify client doesn't play anything.

**Comment by hughrawlinson** [comment]
Thanks @tjhorner - I'll forward this to the team.

**Comment by hughrawlinson** [comment]
Hey, could you give us your username and the exact URI to the context? We need it for debugging.

**Comment by tjhorner** [comment]
Sure thing.

Context URI: `spotify:user:nottjhorner:playlist:5ZAX1gMT3oH3AYnzXsISrB`

Username: `nottjhorner`

**Comment by hughrawlinson** [comment]
@tjhorner take a look at the playlist in [the developer console](https://developer.spotify.com/web-api/console/get-playlist/?playlist_id=5ZAX1gMT3oH3AYnzXsISrB&user_id=nottjhorner). The indices that the play endpoint refers to are what appear in the API response - it looks like you have an unplayable local track in position 0 of the playlist. There's a setting in the Spotify desktop client that hides unplayable tracks, if you have that turned on you won't see the unplayable 0th track in this playlist. You can solve this by using [track relinking](https://developer.spotify.com/web-api/track-relinking-guide/), making sure not to issue a play command for an unplayable track. Hope that helps!

**Comment by tjhorner** [comment]
Well I'll be damned, sorry about that haha.
