### ISSUE TITLE
player/seek?position_ms does not update player laps time

### ISSUE THREAD

**Issue by rolpal** [spotify/web-api#472]
Issue found on April 10 2017

#### Endpoint(s):
`PUT "https://api.spotify.com/v1/me/player/seek?position_ms`

#### Scope(s):
'user-modify-playback-state'

#### Steps to reproduce:
1. Call the endpoint with an access token and seek to a point back in time of current playing song.

#### Expected behaviour:
The song should continue play at the time specified and the player laps time and bar should be set accordingly.

#### Actual behaviour:
The song continue to play at the time specified but the laps time and bar continue where it is.
Eventually the laps timer and bar reach end of song while song still play and they stop while song continue to play.

#### Mobile player used:
Android on Samsung S6 Spotify player version 8.2.0.788 armV7

**Comment by rolpal** [comment]
Similar behavior for this endpoint as well:

`POST "https://api.spotify.com/v1/me/player/next"`

It do skip to next song but the player continue to show previous song and laps timer and bar just continue to progresses.

**When phone is left to "sleep" during play and then "woken" the player UI gets updated.**

**Comment by rolpal** [comment]
Wakening the phone from sleep refreshes the UI and laps time and bar gets updated.
Seems to be a UI refresh issue and not an API issue, though I think the player UI should reflect current state even if changed from API...
Missing an event to player client to update UI or player clients do not listen for such events?

Any how, awesome to have this API, will be a killer!

**Comment by hughrawlinson** [comment]
Hey @rolpal - by 'player laps time' you're referring to the playback scrubber of the official Spotify Android client? If so, that may be considered an issue with the Spotify Android client, and issues for that are taken by customer service - check out community.spotify.com.

If I've misunderstood, please feel free to reopen this ticket!
