### ISSUE TITLE
Ability to add albums to playlists through the web API

### ISSUE THREAD

**Issue by alexwlchan** [spotify/web-api#473]
Use case: I have a chatroom where people are posting Spotify links. I’d like to write a script that scoops up all the links from this chatroom, and puts them in a shared Spotify playlist.

People tend to post links to tracks, albums, and artists.

* I can add track links with the existing [Add Tracks to a Playlist](https://developer.spotify.com/web-api/add-tracks-to-playlist/) API
* I can add album links to a playlist through the GUI app, but I can’t find a way to do it through the API
* I don’t think it’s possible to add artists to a playlist, and I’m not even sure what that would look like

Would be lovely if albums could be exposed in the API, so I can cut out the manual work of adding them by hand (or more usually, forgetting to do so and making people think my script is broken).

**Comment by rolpal** [comment]
Perhaps you could get the tracks from the album and add the tracks to the playlist?
Same method wold work for an artist but it might be a bit to many tracks to add to a list to be useful.

**Comment by alexwlchan** [comment]
> Perhaps you could get the tracks from the album and add the tracks to the playlist?

That seems obvious now you say it, I’ll try that. Thanks!

**Comment by hughrawlinson** [comment]
Hey @alexwlchan - I'd recommend getting tracks from the album and adding them to a playlist. As the Add Tracks to a Playlist endpoint accepts multiple tracks, it is unlikely to take many more API calls (the default number of tracks retrieved in the 'Get an Album's Tracks' endpoint is 20, but can be set to 50 - way more than most albums). It's the best solution for nearly all albums (perhaps excluding this one: `spotify:album:0vdy6DtGYEFyW0yjHjdUv5`).
