### ISSUE TITLE
User device endpoint question

### ISSUE THREAD

**Issue by kabirvirji** [spotify/web-api#474]
I'm trying to make a Spotify desktop app clone (with simple functionality)

There are API endpoints for music manipulation (pause, play, next, etc)
ie) https://developer.spotify.com/web-api/pause-a-users-playback/

Looking at the optional parameters, I can obtain a device using this endpoint:
https://developer.spotify.com/web-api/get-a-users-available-devices/

1. What is considered to be a device? Is it something I can set, or does it only identify official spotify apps? When would I need to include the *optional* device parameter?
2. Is something like a Spotify desktop app clone possible with the given endpoints available? (is there any way I'm misinterpreting what is possible with these endpoints)
3. How can I get devices in the playground? (the wrong scope might be suggested here) https://developer.spotify.com/web-api/console/get-users-available-devices/

I'm getting a 401 error when I try to request available devices:
```
{
  "error" : {
    "status" : 401,
    "message" : "Permissions missing"
  }
}
```
And when I try to pause https://developer.spotify.com/web-api/console/put-pause/#complete (using the correct scope) I get the following result:
![image](https://cloud.githubusercontent.com/assets/11722981/24941007/fd09966e-1f14-11e7-8183-7303a24d3a03.png)

Do I need to provide a device id to pause? How can I get the device id?

Thanks! Let me know if any clarification is needed on my questions.

**Comment by rlingineni** [comment]
+1 , is this only available for iOS and Android? Is it a certain scope?

**Comment by rlingineni** [comment]
Hey, check your scopes. I had to use `user-read-recently-played`

The play and pause work when I provide a device ID. There is an endpoint to list devices.

**Comment by jscholes** [comment]
> 1. What is considered to be a device? Is it something I can set, or does it only identify official spotify apps? When would I need to include the optional device parameter?

Only official Spotify apps (and possibly hardware devices with official SpotifyConnect support) count as devices.  You can't register your own unless you're a Spotify partner, but you can specify one of the user's registered devices to control playback on a specific one e.g. the desktop app on one of their computers, or their iPad.

You can set the user's current playback device for all API calls via the [Transfer a User’s Playback endpoint](https://developer.spotify.com/web-api/transfer-a-users-playback/).

> 2. Is something like a Spotify desktop app clone possible with the given endpoints available? (is there any way I'm misinterpreting what is possible with these endpoints)

It depends what you mean by a "desktop clone".  If you want to provide an alternative user interface which supports search, playlist management, playback actions etc., then the standard and Connect endpoints that the web API currently provides will allow you to do so.  However, there will be some functionality you won't be able to implement, such as realtime notifications of track changes in your GUI, a playback queue, and most importantly, actual playback of full tracks.

> 3. How can I get devices in the playground? (the wrong scope might be suggested here) https://developer.spotify.com/web-api/console/get-users-available-devices/

You'll need to have an access token which was issued with the user-read-playback-state scope, and that token must belong to a Spotify Premium account.

Hope that helps.

**Comment by kabirvirji** [comment]
@rlingineni how can I get my device id? I'm on the playground here: https://developer.spotify.com/web-api/console/get-users-available-devices/

I'm using the token with scope `user-read-recently-played` clicking *Try it*, and I'm getting a 401:
```
  "error" : {
    "status" : 401,
    "message" : "Permissions missing"
  }
}
```

@jscholes By "clone" I mean that I want to make a separate desktop application with no affiliation to the official Spotify Desktop application. This could be used in place of the desktop application and would have similar but very limited functionality. 

However, I'm confused to why I wouldn't have full playback of tracks? If I have a user login, I have access to all their saved tracks, and I'm able to play a track correct? With something like this: https://developer.spotify.com/web-api/console/put-play/

**Comment by jscholes** [comment]
> However, I'm confused to why I wouldn't have full playback of tracks? If I have a user login, I have access to all their saved tracks, and I'm able to play a track correct? With something like this: https://developer.spotify.com/web-api/console/put-play/

That endpoint can be used to start playback of Spotify content on an officially-supported device or application, so you could allow users of your clone to play tracks, albums etc. on one of their registered devices.  But your app itself won't be able to get access to the audio data to play it.  In other words, a user could log in, choose their iPhone as the playback device, choose one of their saved tracks from your UI, click it and have playback start on their iPhone, but not inside your own app.  If you wanted users to be able to play content on the same computer running your clone, they would need the official Spotify desktop app installed and running, and would need to select that device as the playback endpoint.  Hopefully that clears things up a bit.

**Comment by rlingineni** [comment]
@kabirvirji ,

These were all of the scopes I used to get the player endpoints working, it didn't work initially and then it did:

- user-read-private 
- user-read-email 
- streaming 
- user-modify-playback-state 
- user-read-playback-state
- user-read-recently-played

**Comment by kabirvirji** [comment]
@jscholes Thanks, that does clarify. Is the web player considered a device? For example, could the clone select the web player? So the user could select the web player as the playback device, choose a saved track in the clone and have it play out of that tab?

@rlingineni I'm still having trouble getting a successful response. How/where are you generating a token with all those scopes? 

I'm trying it here: https://developer.spotify.com/web-api/console/get-users-available-devices/
There are the scopes its giving me:

![image](https://cloud.githubusercontent.com/assets/11722981/24977267/7436f256-1f9a-11e7-8cbb-acee898747ee.png)

**Comment by jscholes** [comment]
> Is the web player considered a device? For example, could the clone select the web player? So the user could select the web player as the playback device, choose a saved track in the clone and have it play out of that tab?

With the web player logged in and open in Firefox, I do see an entry for it when querying the "Get a User's Available Devices" endpoint.  The entry looks like this:

    {
        "id" : "[redacted]",
        "is_active" : false,
        "is_restricted" : false,
        "name" : "Spotify Web Player",
        "type" : "Computer",
        "volume_percent" : 100
    }

I haven't tested whether the device ID for a Web Player tab stays the same if you close and reopen it, although I would tend to think it would be recreated each time.

**Comment by hughrawlinson** [comment]
Hey @kabirvirji  - @jscholes's answers are all right!

Device ID is optional because the default is the one that's active in the current user session. If there's no user session, none will be started as the user would have to open the device (any spotify connect device or client, including the webplayer).

As for the issues you're having on the web console - the scopes are wrong on the console. I've now fixed them! Thanks for bringing this to my attention.
