### ISSUE TITLE
/v1/me/player/devices issue together with Transfer

### ISSUE THREAD

**Issue by roflcoopter** [spotify/web-api#475]
I am trying to build an app that will transfer the playback from my iPhone to a Chromecast Audio i have on my local network when i arrive home.

The problem is, if i start the Spotify app on my iPhone when I'm on the local network, the Chromecast shows up together with a few other Spotify Connect devices.
If i now get all the available devices via 
`https://api.spotify.com/v1/me/player/devices`
It only returns the iPhone, not the other devices such as the Chromecast.

If I manually select the Chromecast as the playback device and get all the devices again, it shows up. 
Not having all the available devices showing up without them being manually activated makes it hard to automate playback transferring. 

Is there a way to fix this that I am missing?

**Comment by hughrawlinson** [comment]
Hey @roflcoopter - there has to be an active connection from a phone to a chromecast device for it to show up on Spotify connect. This is due to how the underlying cast protocol works.
