### ISSUE TITLE
Bearer token question

### ISSUE THREAD

**Issue by kabirvirji** [spotify/web-api#476]
If I'm having the user supply the bearer token (with the scopes I need), is there a way that they don't have to supply a new one every hour?

**Comment by jscholes** [comment]
> If I'm having the user supply the bearer token (with the scopes I need), is there a way that they don't have to supply a new one every hour?

Not from an access token alone, no.  It means writing more code upfront, but you should provide a mechanism for them to authorize through the Spotify Accounts service, that way you can store a refresh token as well.  Once the access token expires, renew it using the refresh token.  More info in the [Authorization Guide](https://developer.spotify.com/web-api/authorization-guide/).

It depends on the audience of your app, of course, but generally speaking your users shouldn't have to concern themselves with the implementation details behind OAuth.  I'm writing my own app at the moment, though, so I know that to start with, it's often easier to just let the user put a token in a config file and have done with it.

**Comment by kabirvirji** [comment]
Thanks for the help @jscholes
