### ISSUE TITLE
/v1/me/top/Artists - Provide exact play count or weightings per artist

### ISSUE THREAD

**Issue by slandersson** [spotify/web-api#478]

**Comment by Jens-vd** [comment]
+1

In order to retrieve detailed statistics, connecting to last.fm is still needed.

**Comment by arirawr** [comment]
Hey @slandersson,

As per our [new developer support process](https://github.com/spotify/web-api#creating-an-issue), any feature requests that have no plans to be considered in the next 6 months will be closed as wontfix.

We do not have any plans to implement this in the next 6 months and thus will close as wontfix.

We encourage you and other members of the community to continue to share use cases and your support for this feature, as it helps us prioritize features going forward. You will be able to comment on this issue even after it is closed. We will also post any updates here relating to this suggestion when they happen.
