### ISSUE TITLE
Add description to playlists returned by Get a Category’s Playlists endpoint

### ISSUE THREAD

**Issue by soundspectrum** [spotify/web-api#48]
When querying for the playlists in a given category:

```
   api.spotify.com/v1/browse/categories/{category_id}/playlists  
```

It makes a LOT of sense to _also_ include the playlist description in each playlist JSON object.  Otherwise, in a browsing app (such as ours), there's no way to offer a playlist description for each playlist without initiating a _separate_ query for _each_ playlist.

So in our UI when we show a table view of 30+ playlists, we can't include a description string without doing 30+ queries, which is rather ridiculous.

**Comment by hughrawlinson** [comment]
Hey @soundspectrum - we've left this issue open for a while and it doesn't look like it's received much traction. For now we'll leave the simple playlist object model as is. Thanks for the report though!
