### ISSUE TITLE
currently-playing doesn't always return track currently playing

### ISSUE THREAD

**Issue by cheshire137** [spotify/web-api#481]
Issue found on April 16, 2017.

#### Endpoint(s):
* `GET /v1/me/player/currently-playing`

#### Scope(s):
* user-read-currently-playing
* user-read-email

#### Steps to reproduce:
1. Listen to Spotify across multiple clients, such as in the iOS app, macOS app, and web player.
1. currently-playing endpoint does not always return the track that is actively being played in one of the clients.

#### Expected behaviour:
Whatever song is streaming via any client for the authenticated user, at that moment, should be returned by the endpoint.

#### Actual behaviour:
While playing Portishead in macOS, the endpoint reported I was listening to Northern League, FS. I opened the web player and started playing Chrome Sparks, paused the song and closed the web player, resumed Portishead in the macOS app, and the endpoint reported I was currently playing Chrome Sparks.

**Comment by asmitter** [comment]
Hi Sarah,
This may be related to a known issue affecting some users - can you let us know your username (either here or [DM to @spotifyplatform on twitter](https://twitter.com/SpotifyPlatform)) so we can take a look? Thanks!

**Comment by cheshire137** [comment]
Sure! I'm cheshire137 on Spotify.

**Comment by asmitter** [comment]
Thanks Sarah. I've applied a fix for your user - can you please give it another try and see if it behaves itself now?

**Comment by cheshire137** [comment]
That seems to have worked! I may direct a few friends to this issue that were experiencing the same thing.

**Comment by jpiepkow** [comment]
@asmitter do you have any news on when there might be a more widespread fix then a per user basis. I understand  it is still in beta but any news would be super helpful for my application. Thanks!!

**Comment by asmitter** [comment]
Hey @jpiepkow - we're still investigating the best way to fix this across the board (and won't leave Beta without it). We've got enough data now to see it's only a minority of users that are affected, so a vast majority of your application's users won't see any problems.

I've [opened a "Known Issue"](https://github.com/spotify/web-api/issues/499) to which you could link (like @cheshire137 did here) for people to report their usernames while we continue to work on a blanket fix.

**Comment by baslu93** [comment]
Hey @asmitter, I've got the same issue, can you apply the fix also to **11181288000** ? 
Many thanks, 
Luca
