### ISSUE TITLE
https://api.spotify.com/v1/me/top/artists returns 400 - invalid request

### ISSUE THREAD

**Issue by gilsonmandalogo** [spotify/web-api#483]
Issue found on April 16th 2017.

#### Endpoint(s):
* `GET /v1/me/top/artists`

#### Scope(s):
* `user-read-private read-birthdate user-read-email user-top-read`

#### Steps to reproduce:
Call this http request: `https://api.spotify.com/v1/me/top/artists?access_token={valid token}`

#### Expected behaviour:
A paging object as described on [https://developer.spotify.com/web-api/get-users-top-artists-and-tracks/](https://developer.spotify.com/web-api/get-users-top-artists-and-tracks/).

#### Actual behaviour:
`{
  "error" : {
    "status" : 400,
    "message" : "invalid request"
  }
}`

#### PS:
If i only change the endpoint to `https://api.spotify.com/v1/me?access_token={valid token}` with same token, the result is 200 - OK

**Comment by jscholes** [comment]
> Call this http request:  https://api.spotify.com/v1/me/top/artists?access_token={valid token}

Passing your access token in this way, i.e. as a query parameter in the URL, is not supported.  You'll need to provide an "Authorization" header with the value set to a valid Bearer-based authorization string.  It looks like:

    Bearer <your_token_here>

There are more details in the [Authorization Guide](https://developer.spotify.com/web-api/authorization-guide/).

> If i only change the endpoint to  https://api.spotify.com/v1/me?access_token={valid token}  with same token, the result is 200 - OK

This works for me too, oddly enough.  But this isn't documented, is most likely a bug and basically shouldn't be used.  You should always pass your access token in the way described by the Authorization Guide and the individual documentation for the endpoint you're attempting to use.  The [docs for the /me endpoint](https://developer.spotify.com/web-api/get-current-users-profile/), for instance, state that your token should be provided in the Authorization header.

**Comment by gilsonmandalogo** [comment]
Very thanks @jscholes, i changed my authorization to bearer-based and now works fine =D
