### ISSUE TITLE
Wildcard for redirect URI

### ISSUE THREAD

**Issue by dreszczyk** [spotify/web-api#487]
My application includes local server and localtunnel.me integration - user gets random localtunnel domain (to share with others). I cannot add wildcard in Redirect URI on the [my applications](https://developer.spotify.com/my-applications/) page. Is this possible? Or can it be added?

**Comment by jscholes** [comment]
The web API Authorization Guide is explicit about the requirement that redirect URIs must exactly match what is stored in your developer account.  However, if you're authorizing the user via a browser, you can just redirect them back to your app by using 127.0.0.1.  Is there a reason this wouldn't work for you?

**Comment by dreszczyk** [comment]
Well, my app needs to share a local server over the internet, so that's a must 💯

**Comment by jscholes** [comment]
The redirection during the authorization flow happens client-side, so the redirect URI doesn't need to be Internet-accessible.  If your app is running on a user's local machine, and that is also the machine on which they're going to operate the app, then redirecting back to 127.0.0.1 will work.

If your app has a more complicated infrastructure then you may have to implement the authorization server-side or use some other option depending on how exactly your app works.  I don't work for Spotify, so I can't categorically say that they won't implement wildcard support for OAuth redirect URIs.  But it sounds like a security nightmare waiting to happen.  Feel free to share more details of how exactly your app works and why redirecting to localhost won't suffice and we can try to help further.

**Comment by JMPerez** [comment]
As @jscholes, if you are shipping a local browser in your project you can just use `localhost` as the redirect uri. This is what the [beginner's tutorial](https://developer.spotify.com/web-api/tutorial/) does and works pretty well.

If you are working on a website, you are hosting the server and want other users to get tokens from an unknown url, there is another approach hat has worked for me in the past. You can open the `login` page in a popup and send a post message from the `redirect_uri` to `*`, or the hosts you decide. This is useful to create [JSFiddle snippets](http://jsfiddle.net/JMPerez/62wafrm7/) or [CodePen pens](https://codepen.io/jmperez/pen/YVXEaz) where you get a different url with every snippet and don't want to whitelist each of them.

**Comment by dreszczyk** [comment]
I'm using [this](https://github.com/kauffecup/spotify-react-router-auth) as a boilerplate. I want to create an app which will give you random localtunnel.me adress to share with your friends. Everyone will login (with Spotify account) using this random link and the application will sync the playback for everyone.

_... is there such an app already (and its working on windows/linux/macos)? ;)_

**Comment by jscholes** [comment]
You'll need to perform the authorization in some other way, then.  This is a limitation of your app's infrastructure, not of OAuth or the Spotify Web API.  Wildcards in redirect URIs would open up too many attack vectors (see [this post](http://technotes.iangreenleaf.com/posts/closing-another-nasty-security-hole-in-oauth.html) for more details.

**Comment by frafra** [comment]
What about wildcards just for the domain instead of the full URI? For example, same path but different subdomain:
`https://spotify-*.testing.domain.com/callback`

That would allow to do use CI/CD systems with Spotify easily, as each commit/pull request triggers a new deployment under a different subdomain usually.
