### ISSUE TITLE
Get a User’s Top Tracks - Track Object

### ISSUE THREAD

**Issue by kvanzuijlen** [spotify/web-api#489]
Issue found on April 19th 2017.

#### Endpoint(s):
* `GET /v1/me/top/tracks`

#### Scope(s):
* user-top-read

#### Steps to reproduce:
1. Open the API Console
2. Call the `get-users-top-artists-and-tracks` endpoint with `type` `tracks`

#### Expected behaviour:
A list with full track objects including available markets as described on `https://developer.spotify.com/web-api/get-users-top-artists-and-tracks/#tablepress-58` (`https://developer.spotify.com/web-api/object-model/#track-object-full`).

#### Actual behaviour:
What looks like a list of simple track objects (`https://developer.spotify.com/web-api/object-model/#track-object-simplified`). It's (at least) missing the available_markets field.

**Comment by arirawr** [comment]
We're looking into this - thanks for the report.

**Comment by arirawr** [comment]
This issue should now be resolved. Thanks for your report!

Please feel free to reopen if you continue to see this issue occur.
