### ISSUE TITLE
Spotify OS X client doesn't update currently playing on the API

### ISSUE THREAD

**Issue by ruigomeseu** [spotify/web-api#490]
Issue found on April 19th 2017.

#### Endpoint(s):
* `GET /v1/me/player/currently-playing`

#### Scope(s):
- 'user-read-currently-playing'
- 'user-read-email'
- user-read-private'

#### Steps to reproduce:
1. Authenticate a user through the regular authorization flow.
2. Play a song using the Spotify OS X client.
3. Access the endpoint for the currently playing song.
4. Notice that "is_playing": false.

#### Expected behaviour:
Listening to a song on the OS X client would update the currently playing song retrieved via the web API.

#### Actual behaviour:
No update occurs on the Web API, even if waiting for longer than a minute.

Note: If I listen to a song on my iPhone it updates instantly, so I'm pretty sure the code is correct. The account is obviously the same.

**Comment by agilesteel** [comment]
Accidentally stumbled on the same thing.

Can confirm that it does NOT update from Spotify Windows 10 client, but DOES update from the Android App.

**Comment by ruigomeseu** [comment]
Eventually I tried from the web player and it updated.

From then on the OS X player started updating. Suddenly it stopped updating, playing a song from the web player fixed it again. Not sure if this was just a big coincidence.

**Comment by asmitter** [comment]
This may be related to a known issue, which is user specific.
Can you both provide your Spotify usernames? Either as a reply here or in a [DM to the @SpotifyPlatform twitter account](https://twitter.com/SpotifyPlatform).

**Comment by ruigomeseu** [comment]
@asmitter thanks for the reply. My Spotify username is rmsgomes

**Comment by agilesteel** [comment]
Mine is the same as on github: agilesteel, thx.

**Comment by jpiepkow** [comment]
Yep have ran into this issue since starting to convert my app to using these new endpoints. For now the workaround I use is. 1. Get user device(the osx application most of the time) 2. call play via the new endpoint 3. Now call get current song and calling play in the previous step should 'update' the current song endpoint to the current song in the OSX application. Not exactly the best thing..but until this is fixed it at least works in my use case.

**Comment by jstlnd** [comment]
@ruigomeseu and @agilesteel Please try now and let us know if things work better.

**Comment by ruigomeseu** [comment]
@jstlnd seems to be updating consistently now. I'll report back in 24 hours after some more throughout testing. Thanks!

**Comment by agilesteel** [comment]
@jstlnd same here. All good now. Thx for the quick fix. Cheers

**Comment by cassiohub** [comment]
Hello

I'm facing the same issue. Current Playback Info is not updated when it start from the osx client. My user name is 12129631691 (facebook linked account).
