### ISSUE TITLE
endpoint v1/me/player/pause error----"Not available for the current user"

### ISSUE THREAD

**Issue by orchestor** [spotify/web-api#491]
Issue found on April 20th 2017.

#### Endpoint(s):
* https://api.spotify.com/v1/me/player/pause

#### Scope(s):
* user-modify-playback-state

#### Steps to reproduce:
1. Open https://developer.spotify.com/web-api/console/put-pause/

2. input device id and get token with "user-modify-playback-state" scope

#### Expected behaviour:
Pause playback

#### Actual behaviour:
{
  "error" : {
    "status" : 403,
    "message" : "Not available for the current user"
  }
}

**Comment by asmitter** [comment]
Are you a premium user? [Controlling devices is only available for premium users](https://developer.spotify.com/web-api/working-with-connect/#premium-only).

**Comment by orchestor** [comment]
Thanks for this info. I might got this one. -Lin
