### ISSUE TITLE
Start/Resume a User's Playback ends up on 403 Forbidden

### ISSUE THREAD

**Issue by dreszczyk** [spotify/web-api#496]
Issue found on April 23 2017.

#### Endpoint(s):
* `PUT https://api.spotify.com/v1/me/player/play`

#### Scope(s):
* user-modify-playback-state

#### Steps to reproduce:
1. Open the API Console
2. Call the `me/player/play` endpoint

#### Expected behaviour:
A song would start or resume.

#### Actual behaviour:
```
{
  "error" : {
    "status" : 403,
    "message" : "Forbidden."
  }
}
```

**Comment by jscholes** [comment]
What is your account type?  This (and many of the other Connect endpoints) will only work for premium users.

**Comment by dreszczyk** [comment]
It's premium and it's working now.
