### ISSUE TITLE
Shuffle album playback, first track playback issues (wasn't sure where to report this)

### ISSUE THREAD

**Issue by bab4m** [spotify/web-api#497]
Issue found on February 19th 2015.

With shuffle on, the play button on the very first track of an album won't play that song, but functions like the green play button beside the follow button.

#### Steps to reproduce:
1. turn on shuffle
2. pick album
3. press play on very first song

#### Expected behaviour:
Play that song first, then shuffle the rest.

#### Actual behaviour:
500 Server Error (consistently)

**Comment by asmitter** [comment]
Hi @bab4m 
This doesn't sound like an issue with Spotify's Web API, which is the purpose of this tracker.
For general Spotify help and feedback you can reach out to SpotifyCares on Twitter, or post to the [Spotify Community](https://community.spotify.com/).
