### ISSUE TITLE
Duplicate Song panel hidden behind list of playlists

### ISSUE THREAD

**Issue by ashmc** [spotify/web-api#498]
Issue found on April 23rd 2017.

* This is a bug found in the desktop application 

#### Steps to reproduce:
1. Right click on a song, click on "Add to Playlist" and add to playlist X
2. Now repeat step 1 with the same song

#### Expected behaviour:
* The panels from step 1 + list of playlists panel should be hidden, or maybe if upon canceling show the list of playlists again (?)

#### Actual behaviour:
* Duplicate Song panel is hidden behind the list of playlists

#### Extra info:
* In the online version (play.spotify.com) it always successfully adds the same song to the same playlist, no duplicate error message
<img width="759" alt="screen shot 2017-04-23 at 13 20 18" src="https://cloud.githubusercontent.com/assets/1707137/25317217/4ff22b1c-2829-11e7-8b86-580d18b529c2.png">
 shown.

**Comment by arirawr** [comment]
Hello, I've reported this issue to the team that works on the desktop app, but, as this isn't a Web API issue, I'll close it here. Thank you for reporting!
