### ISSUE TITLE
Example code for Playlist Next/Previous commands wrong

### ISSUE THREAD

**Issue by rockfather** [spotify/web-api#500]
Issue found on April 22nd  2017.

#### Endpoint(s):
* POST https://api.spotify.com/v1/me/player/next
* POST https://api.spotify.com/v1/me/player/previous

#### Actual behaviour:
Example code (using curl) shows use of HTTP PUT, rather than HTTP POST

**Comment by arirawr** [comment]
This has been fixed so I'm going to close the issue. Thanks for reporting!
