### ISSUE TITLE
"v1/me/player/play" won't resume playback

### ISSUE THREAD

**Issue by martinobonfiglioli** [spotify/web-api#501]
Issue found on April 24th 2017.

#### Endpoint(s):
* `PUT v1/me/player/play`

#### Scope(s):
* Some including `user-modify-playback-state`

#### Steps to reproduce:
1. Call first `v1/me/player/pause` in `PUT` with empty body `{}`
2. Then call `v1/me/player/play` in `PUT` with empty body `{}`

#### Expected behaviour:
With the first call the playback goes to pause, with the second call my playback resume to play state

#### Actual behaviour:
With the first call the playback goes to pause as expected, with the second call my now playing track disappear and also cause losing the play queue.

**Comment by dreszczyk** [comment]
I figured out what's wrong - docs. You need to _put empty body_, this means no body at all, not empty stringified object.
Source: I just checked ;)

**Comment by martinobonfiglioli** [comment]
@dreszczyk I wasn't able to make this API works, even with no body at all :(

I want also let you know that:
on the [API console](https://developer.spotify.com/web-api/console/put-play/) with PUT body empty the webpage show an error, with PUT body `{}` makes you lose your playlist.

**Comment by martinobonfiglioli** [comment]
@seahorsepip @dreszczyk could you please make me some example of _put empty body_ or help me to understand the difference between _put empty body_ and _empty stringified object_

Thanks in advance 🙏

**Comment by hughrawlinson** [comment]
@martinobonfiglioli the difference in `cURL` would be

_put empty body_
```
curl -X PUT "https://api.spotify.com/v1/me/player/play" \
     -H "Accept: application" \
     -H "Authorization: Bearer $ACCESS_TOKEN" \
     -H "Content-Type: application/json" \
     --data ""
```

_empty stringified object_
```

curl -X PUT "https://api.spotify.com/v1/me/player/play" \
     -H "Accept: application" \
     -H "Authorization: Bearer $ACCESS_TOKEN" \
     -H "Content-Type: application/json" \
     --data "{}"
```

Hope that helps!

We'll update the docs ASAP!

**Comment by seahorsepip** [comment]
@martinobonfiglioli 
Here's an example when using the Retrofit 2 library (Java):

```
// Service.java
@PUT("me/player/play")
Call<Void> play(@Query("device_id") String deviceId, @Body Play play);

@PUT("me/player/play")
Call<Void> resume(@Query("device_id") String deviceId);

//Some activity.java
public void play() {
    Call<Void> call = service.play(<deviceId>, <playObject>);
}

public void resume() {
    // DONT
    Call<Void> call = service.play(<deviceId>, null);
   
    // DO
    Call<Void> call = service.resume(<deviceId>);
    /*
    It might look like both calls are the same but giving the Body parameter
    a value of null results in Retrofit sending "{}" instead of "" as Body value.
    So instead make a separate Retrofit method that has no Body parameter at all.
    */
}
```

**Comment by hughrawlinson** [comment]
@seahorsepip we're looking into that too :)

**Comment by hughrawlinson** [comment]
Hi! The API should now handle empty bodies as well as empty JSON objects in the body. I'll close this issue now :)
