### ISSUE TITLE
Malformed json request when calling play a user's playback

### ISSUE THREAD

**Issue by chan135** [spotify/web-api#502]
Issue found on February 19th 2015.

#### Endpoint(s):
PUT https://api.spotify.com/v1/me/player/play

#### Scope(s):
user-modify-playback-state

#### Steps to reproduce:
1. Using postman, copy paste "https://api.spotify.com/v1/me/player/play" into endpoint, as well as make the call PUT
2. Put in authorization, and token
3. Press the body tab, and add context_uri for key, and spotify:album:4PgleR09JVnm3zY1fW3XBA for value
4. Add offset for key, and "position": 0 for value
5. Send request

#### Expected behaviour:
24K Magic, Bruno Mars should play

#### Actual behaviour:
400 Malformed Json

I'm trying to make an application that will create a playlist for a user, add songs to it, then play that playlist without them having to press anything on Spotify. I started trying the play request using an album just to test it first, and for some reason I'm getting a Malformed json

**Comment by arirawr** [comment]
Hi there, 

Try using our API console to help you form your request: https://developer.spotify.com/web-api/console/put-play/

If that still doesn't work, please let me know and post the JSON that you are sending here.

**Comment by chan135** [comment]
Hi so I'm using python so I'm not sure how to fully format the JSON even after looking at the API console. For getting the Spotify userID we do something like this :   req = requests.get("https://api.spotify.com/v1/me", headers={"Authorization":'Bearer ' + token}), but I'm not sure where the context_uri or the offset would go in this python command

**Comment by arirawr** [comment]
No problem - in Python, using requests, to pass the JSON you can use the "data" argument. See here: http://docs.python-requests.org/en/master/user/quickstart/#more-complicated-post-requests.

**Comment by hughrawlinson** [comment]
Hey @chan135 - this endpoint accepts a JSON body rather than `form-data` or `x-www-form-urlencoded`. As @arirawr mentioned, you can use the "data" argument of Python requests to pass in data. The request might look something like this:

```
import json

payload = {
  "context_url": url,
  "offset": {
    "position": 5
  }
}

r = requests.post(url, data=json.dumps(payload), headers={"Content-Type": "application/json")
```

Note that the content type is application/json.

As for Postman, I'd recommend setting the "Content-Type: application/json" header, and writing the JSON into the raw tab of the request body. Hope that helps!

**Comment by chan135** [comment]
Ok got it, thanks for the help!

**Comment by the-sides** [comment]
I understand this is closed, but I had this exact problem for a solid hour and my solution was simply stringify-ing the data passed within my AJAX function. I would just like to help anyone who needs to take this specific approach.
```
    ajax_data = {
        "context_uri": "spotify:album:5ht7ItJgpBH7W6vJ5BqpPr",
        "offset": {
          "position": 5
        },
        "position_ms": 0
      }
    $.ajax({
        method: "PUT",
        url: "https://api.spotify.com/v1/me/player/play",
        headers: {
            'Accept': 'application/json' ,
            'Content-Type': 'application/json',
            'Authorization': 'Bearer '+ window.token
        },
        data: JSON.stringify(ajax_data),
        success: function(res){
            console.log("We think it worked", res)
        },
        error : function(xhr, errmsg, err) { 
            console.log(xhr.status + ': ' + xhr.responseText);   
        }
    })
```
