### ISSUE TITLE
Request for historical song popularity feature from API

### ISSUE THREAD

**Issue by ksub2000** [spotify/web-api#508]
Hi, I was wondering if there would be a way not only to get a song's current popularity when pulled from the API, but it's popularity one, two, or however many weeks or months in the past, perhaps as some sort of array from most recent to the beginning the song's time on Spotify.

My specific use cases are for data analytics of song seasonality/sensitivity to changes based on events, such as:
- how much of a spike in play does Christmas music get post-Thanksgiving?
- how does the popularity curve of a "song of the summer" look week-to-week or month-to-month during the year that it is one of the "songs of the summer"?
- how much do artists plays spike when something happens (death, retirement, band breaks up, etc.) to them?
- how much does one artist's plays change after they either feature on a much more popular artist's song or have a much more popular artist feature on their song?
- how do movie soundtracks fare as sequels come out?

While I can get the current popularity of a song (and could, theoretically, over time, build up to the use cases above for any future events), trying to correlate anything about popularity over time for a track, artist, or album is currently unavailable.

Thank you for your help.

**Comment by asmitter** [comment]
Hi @ksub2000 - thanks for the feature request.
It's an interesting idea, but unfortunately not something we are able to bring to the API.
