### ISSUE TITLE
Search by release date only

### ISSUE THREAD

**Issue by laran** [spotify/web-api#51]
I want to search for all albums released within a date range, including dates into the future. For example:
- albums released in the last month
- albums that will be released in the next two weeks

I don't care who the artist is or any information other than the release date.

Is this currently possible? If not, please consider this a feature request.

**Comment by thelinmichael** [comment]
You can search by year to include only albums between some given years, e.g.
 https://api.spotify.com/v1/search?type=album&q=year:2015-2020

If you'd like to filter the results by month, you'd have to follow up with a request to retrieve metadata about the returned albums, e.g. https://api.spotify.com/v1/albums/26bzHnyTkFBFHUFeRwFDn7 includes 

```json
release_date: "2015-03-16",
release_date_precision: "day",
```

[Search endpoint documentation](https://developer.spotify.com/web-api/search-item/)

**Comment by christiangenco** [comment]
Is it still the case that albums can't be searched by exact release date?

I'm trying to search for popular tracks released 10 years ago today. Right now I think the only way to do that is to look at all songs released in 2007, then look up their album metadata for `release_date` and look for tracks released on the right month and day.

If possible, it'd be way easier to search for `q=year:2007%20month:04%20day:30`.
