### ISSUE TITLE
Not possible to add local tracks to playlist through Web API

### ISSUE THREAD

**Issue by johannes-missbach** [spotify/web-api#510]
Issue found on February 19th 2015.

#### Endpoint(s):
* `POST /v1/users/{user_id}/playlists/{playlist_id}/tracks`

#### Scope(s):
* Authenticated as user_id
* User owns a playlist with playlist_id

#### Steps to reproduce:
1. Open the API Console
2. Call the `post-playlist-tracks` endpoint with your user_id & playlist_id and specify `spotify:local:Artist:Album:Title:180` in the `Track URIs` field

#### Expected behaviour:
The local track should have been added to the specified playlist.

FYI: You can copy and paste this track URI into a playlist in the desktop application (verified 1.0.53.758 @ OSX).

#### Actual behaviour:
400 Bad Request (consistently)
```
{
  "error" : {
    "status" : 400,
    "message" : "Invalid track uri: spotify:local:Artist:Album:Title:180"
  }
}
```

**Comment by arirawr** [comment]
Hi Johannes, the `spotify:local:Artist:Album:Title:180` format is not accepted in the Web API and we do not have any plans to implement this.
