### ISSUE TITLE
Recently played songs no longer showing up 

### ISSUE THREAD

**Issue by rickpern** [spotify/web-api#512]
Issue found on May 1st 2016.

#### Endpoint(s):
* `GET /v1/me/player/recently-played`

#### Scope(s):
* user-read-recently-played

#### Steps to reproduce:
1. Play a song
2. Open the API Console
3. Call the `player/recently-played` endpoint

#### Expected behavior:
Results showing your most recent plays including the song I just played.

#### Actual behaviour:
Plays since last night are not showing up.  I've tried restarting the apps, playing with different devices, etc. to no avail.  I have also confirmed that other people are experiencing the same issue.  Some plays are still getting shared to my Facebook since I'm sharing activity, but not visible via this endpoint.

**Comment by fan1200** [comment]
Same here, last tracks were from April 30th. Everything played yesterday (May 1st) was not visible in the recent tracks endpoint. (Checked on multiple devices and private mode was not on)

**Comment by rickpern** [comment]
That's exactly what I'm seeing @fan1200, last tracked play for me and all of my coworkers was the night of April 30th.  I've tweeted at their support accounts too to no avail so far.

**Comment by arirawr** [comment]
Hi all - we have been able to recreate this issue and are working on it. Thanks for bringing it to our attention!

**Comment by fan1200** [comment]
Hi,

I can confirm that this is working again.

**Comment by arirawr** [comment]
This issue has been resolved. Thank you for your report!

**Comment by rickpern** [comment]
Thanks for the quick turnaround!!
