### ISSUE TITLE
Bad Request: 400 Getting Access Token Using Authorization Code Flow 

### ISSUE THREAD

**Issue by tuyenopp-openpath** [spotify/web-api#514]
I am having the issue when trying to obtain access token using authorization code. I followed the Authorization Code Flow found here https://developer.spotify.com/web-api/authorization-guide/  and everything worked fine up to last week (04-27-17). Now after getting the authorization code, I got  Bad Request: 400  `{"error":"invalid_grant","error_description":"Invalid redirect URI"}` when following the step 4 in the aforementioned  tutorial. Is there a new change in the API the I did't know of? Here is my code to get the access token:

```
$.ajax({
  type:"POST",
  url: 'https://accounts.spotify.com/api/token',
  data: {
    "redirect_uri": encodeURIComponent(REDIRECT_URI),
    "grant_type":'authorization_code',
    "code":authCode,
    "client_id":spotifyID,
    "client_secret":spotifySecret
  }
}).done(function(data) {
  console.log(data)
}).fail(function(error){
  console.log(error)
})
```

Please help.

**Comment by elegos** [comment]
`Invalid redirect URI` seems like you're sending an invalid URI, or an URL not in the "My Applications" app's allowed URLs. BTW why do you encode your redirect URI? Shouldn't be that handled by `$.ajax` itself? (not using it by ages btw)

**Comment by tuyenopp-openpath** [comment]
Hi elegos, 

 Thank you for your prompt response. Using redirect uri without encoding works.
