### ISSUE TITLE
Some requests get a 502 Bad Gateway response

### ISSUE THREAD

**Issue by DuckThom** [spotify/web-api#515]
Issue found on April 28th 2017.

#### Endpoint(s):
* `GET /v1/me/player/currently-playing`

#### Scope(s):
* user-read-playback-state

#### Steps to reproduce:
1. Call the endpoint

#### Expected behaviour:
200 Response

#### Actual behaviour:
Some (I'd say around 1 in a 1000) requests return a 502 Bad Gateway response:

```
[2017-05-02 13:32:14] production.ERROR: GuzzleHttp\Exception\ServerException: Server error: `GET https://api.spotify.com/v1/me/player/currently-playing` resulted in a `502 Bad Gateway` response:
{
  "error" : {
    "status" : 502,
    "message" : "Bad gateway."
  }
}
```

**Comment by arirawr** [comment]
Hello, we took a look into this and haven't found anything abnormal. 502 errors can occur periodically, but are not a cause for concern in these quantities. In most cases, you can re-try the request immediately and get a response.

We actively monitor errors internally and are notified of any spikes.

Thank you for your report!
