### ISSUE TITLE
A track's preview_url inconsistently returned with different access tokens

### ISSUE THREAD

**Issue by rickpern** [spotify/web-api#516]
Issue found on May 3rd 2017.

#### Endpoint:
* `GET /v1/tracks/1ygcoPipW5Dru2lgT1kquj

#### Steps to reproduce:
1. Open the API Console
2. Call the `tracks/1ygcoPipW5Dru2lgT1kquj` endpoint with no access-token
3. Note the `preview_url` attribute
4. Repeat steps 1-3 with a non-Premium user's access token
5. Repeat steps 1-3 with an application's client access token
6. Repeat steps 1-3 with a Premium user's access token

#### Expected behaviour:
I expect the `preview_url` to either be `null` or present for all 4 cases.

#### Actual behaviour:
For all access tokens except my Premium account, the `preview_url` is `null`, but when using my premium account's access token I get `https://p.scdn.co/mp3-preview/3771074a3979339d5cf37f0f0eb1a0673babd3e3?cid=8897482848704f2a8f8d7c79726a70d4`.

This is only happening for select songs, but this song is a good example.  The same result is given when requesting all the tracks for select albums.

Please let me know if you need more info or cannot reproduce.

**Comment by korbor1** [comment]
Got the same error. From

>  "Top 100 tracks currently on Spotify"

`https://api.spotify.com/v1/users/spotify/playlists/4hOKQuZbraPDIfaGbM3lKI/tracks`

I call the api with application's client access token and 32 tracks from 100 got `preview_url: null`

Like week ago, everything was fine

**Comment by orangemooncreative** [comment]
I am having the same issue for top tracks with the client access token returning preview_url: null.

**Comment by bldoron** [comment]
Ever since switching to the application's client access token all major artists ('U2', 'Queen') have preview_url set to null. How can I get them back for my application?


This is a major blocker for me as it renders the Spotify API useless.
Please fix ASAP.

**Comment by shawns582** [comment]
Any resolve here?  I am having this same issue when I use the client access token retrieve a track.  This a major blocker for me to as it also renders the Spotify API unusable.  Desperate for a fix...thanks in advance.

**Comment by tamoyal** [comment]
would love some info on this, nothing in the docs about this - https://developer.spotify.com/web-api/get-artists-top-tracks/

**Comment by hughrawlinson** [comment]
Hi all - [as documented](https://developer.spotify.com/web-api/object-model/#track-object-full), when the track preview is not available, it will be null. Track previews can be unavailable for a wide variety of reasons, so your app should handle the possibility that one isn't available. In some cases, previews may only be available to premium users, for licensing reasons.
