### ISSUE TITLE
Profile Widget links to the wrong profile

### ISSUE THREAD

**Issue by crohrer** [spotify/web-api#518]
Issue found on May 6th 2017.

#### Scope(s):
* None (application is not using authentication)

#### Steps to reproduce:
1. Create widget code with a normal user URI (I used my own spotify:user:119725717) on https://developer.spotify.com/technologies/widgets/spotify-follow-button/#disqus_thread
2. open the generated iframe URL
3. Click on user name or profile picture

#### Expected behaviour:
The User Profile that belogs to the clicked user name should be opened

#### Actual behaviour:
The Artist page of Avicii is opened

**Comment by 72lions** [comment]
Thanks for the bug report! The fix should be live right now. Feel free to verify the fix.

**Comment by 72lions** [comment]
@arirawr feel free to close this one
