### ISSUE TITLE
Deadline of unauthenticated calls Web API

### ISSUE THREAD

**Issue by greencoppercompany** [spotify/web-api#521]
Hi Spotify team!

#### Endpoint(s):
All endpoints still accessible without authentication, but mainly for us: 
* `GET /v1/artists/{artist_id}/top-tracks`
* `GET /v1/tracks/{track_id}`
* `GET /v1/albums/{album_id}`

As stated in [this](https://developer.spotify.com/news-stories/2017/01/27/removing-unauthenticated-calls-to-the-web-api/) blog post, on 29th May 2017 the /search /tracks /albums /artists and /users (and related) endpoints will start requiring an access token.

The information has been shared since a while and the deadline is now in 20 days. We were wondering if based on current traffic on detailed endpoints you still see many unauthenticated calls. We're migrating many apps to support change and would like to know  if you're about to postpone the deadline, which could let us more time to finish everything :)

Thanks for your help,
Loïc

**Comment by arirawr** [comment]
Hi Loïc, 

No, the deadline will not be postponed and all requests need to be authenticated starting on May 29th.

Please see the migration guide here: https://developer.spotify.com/migration-guide-for-unauthenticated-web-api-calls/

Let us know if you have any issues while migrating.

**Comment by greencoppercompany** [comment]
Hi @arirawr !

Thanks for your quick feedback!
Loïc
