### ISSUE TITLE
Initiating play from the API affects the functioning of the Mac Desktop application

### ISSUE THREAD

**Issue by richoakley** [spotify/web-api#524]
**Title: Initiating play from the API affects the functioning of the Desktop application**

Issue found on May 10th 2017.

#### Endpoint(s):
* `PUT https://api.spotify.com/v1/me/player/play`

#### Scope(s):
* user-modify-playback-state

#### Steps to reproduce:
1. Open the Spotify Desktop (Mac) application 
2. Initiate a track playback using the above API endpoint
3. Observe the state of the player

#### Expected behaviour:
The Spotify Desktop application on Mac should continue to function as usual. 

#### Actual behaviour:
* The progress bar no longer updates, or functions as normal
* The play/pause button no longer functions, or changes state when clicked

*PS:* I realize that it's possible that this is a bug relating only to the Desktop application, but as it is only affected by the use of the Web API, I decided to report it here.

**Comment by lrholmes** [comment]
This also affects me. I'm not too bothered because I know that a restart will fix it but I am a little concerned that when I release my app users will get worried that their Spotify is broke. I think it's probably an issue with the desktop client though, have you let twitter.com/spotifycares know about this?

**Comment by asmitter** [comment]
Just wanted to update you both that we've replicated this and are investigating.
Looks like a desktop client thing, but as it manifests when using the Web API we'll keep this open for visibility until it's fixed.

**Comment by asmitter** [comment]
Another update: we've found the issue and a fix will be included in the upcoming version of the desktop client. I'll close this issue when that version has rolled out.

**Comment by asmitter** [comment]
The fix has been released. As usual, the update will happen automatically. You can check by going to "Spotify" > "About Spotify". The version with the fix begins 1.0.56.
Let us know if you see any more issues!

**Comment by richoakley** [comment]
Working perfectly! Thanks for the update
