### ISSUE TITLE
Retrieve Sonos device list and send playlist to be played

### ISSUE THREAD

**Issue by scgough** [spotify/web-api#525]
Hi all,
This is a bit of a feature request I guess. I'm just thinking out loud...

Within the SONOS app you can connect Spotify and play songs/albums/playlists.
Within the Spotify app you can play music via connected SONOS devices.

Could there be a way of retrieving a list of said connected SONOS devices via the Spotify API then choose one to play the playlist through?

**Comment by arirawr** [comment]
Have you tried the Connect endpoints? You should be able to use the "Get a User's Available Devices" (https://developer.spotify.com/web-api/get-a-users-available-devices/) endpoint to get your speaker, then use the other connect endpoints to play music.

https://developer.spotify.com/web-api/web-api-connect-endpoint-reference/

**Comment by scgough** [comment]
@arirawr you might have just made my day! I'll check those Beta endpoints out!

**Comment by hughrawlinson** [comment]
Hey @scgough - as noted in our [working with Connect guide](http://dev.spotify.net/documentation/web-api/guides/working-with-connect/), some devices are not controllable or observable via the connect APIs. Currently we are not able to support control of Sonos devices via the Connect API. As @arirawr mentioned, you can use the 'Get a User's Available Devices' endpoint to list the devices that can be controlled (filtering on the `is_restricted` key as documented).

**Comment by scgough** [comment]
@hughrawlinson I've been crying for the last 16 days since you dashed my hopes of controlling a Sonos device. 
Seriously though, thank you for clarifying

**Comment by hughrawlinson** [comment]
Aww, sorry about that @scgough! Hopefully you can still build something cool, let us know if we can help at all :)

**Comment by scgough** [comment]
No problem. I hope so @hughrawlinson ! It'd be great to get you and the team's input on: https://github.com/spotify/web-api/issues/564

**Comment by titopixelfusion** [comment]
+1 we need this feature, not being able to list SONOS speakers is a bummer, SPOTIFY API never identifies the current playing song :/

**Comment by titopixelfusion** [comment]
To determine the current playing song, I actually end up solving the problem by using the endpoing me/player instead of me/player/currently-playing. We get all the details of the current playing song in the player endpoint. Unfortunately device still isn't listed under /devices, but for my project, it doesn't really matter.

**Comment by sennl** [comment]
Is there anythin ongoing to enable discovering Sonos devices over Spotify API?

**Comment by schmurtzm** [comment]
+1

**Comment by Stugr** [comment]
+1

**Comment by pathob** [comment]
+1

**Comment by jaburges** [comment]
hold on, Spotify works ok (showing my sonos devices) within my network (PC and Mobile apps) 
However, does not work when I use the API or the Spotify WebApp. 

Is there no way to surface my sonos devices to Spotify API through an extra approval/auth model?

**Comment by kubukoz** [comment]
Yep, this is bad. The desktop application can change music playing on Sonos, but developer apps can't.

**Comment by rangler2** [comment]
> To determine the current playing song, I actually end up solving the problem by using the endpoing me/player instead of me/player/currently-playing. We get all the details of the current playing song in the player endpoint. Unfortunately device still isn't listed under /devices, but for my project, it doesn't really matter.

It didn't work for me (returned 204 NO CONTENT same as currently-playing endpoint) however the endpoint https://api.spotify.com/v1/me/player/recently-played did return the tracks recently played on sonos. But not the current track until after it ends!!  Anyone know if it is possible to get current playing track when playing via Sonos?

**Comment by rangler2** [comment]
@titopixelfusion  does /me/player this still work for you to get current playing track on Sonos? as it returns 204 NO CONTENT for me. Thanks.

**Comment by kubukoz** [comment]
@rangler2 I'm using `/me/player`, and unless there's actually nothing playing I don't get 204 but a success. https://github.com/kubukoz/spotify-next/blob/bcb2d4c/src/main/scala/com/kubukoz/next/Spotify.scala#L93

**Comment by rangler2** [comment]
Thanks.. Maybe I need to upgrade Sonos...

**Comment by CobraCalle** [comment]
damn...! Does anyone know if this is a technical or a political / business related problem... or with other word: Is there hope that we will be able to build really useful things with the Spotify-API in the future or, will it never work?

**Comment by abhiti** [comment]
Still no update on this? As was previously mentioned, I see my Sonos device in `/me/player`, but with `is_restricted: true`. I'm mostly disappointed because this feature is clearly available in Spotify's Web Player, so I'm not sure why support is not available publicly?

**Comment by dersam** [comment]
Can we ever expect this to be implemented? It's clearly possible, so it's extremely disappointing that the public API is inferior to whatever secret interface is being used.

**Comment by rmccright-usf** [comment]
Would be great to be able to reopen this.  Seeing as the Sonos shows up on the Web Player I don't see why we cant control this with our customer Apps.
