### ISSUE TITLE
Long polling or push for /me/player

### ISSUE THREAD

**Issue by tkhduracell** [spotify/web-api#526]
Would be super useful to have a mechanism for long polling or subscribing to updates or the player state.

**Comment by dreszczyk** [comment]
Probably duplicate of #492

**Comment by seahorsepip** [comment]
@arirawr 
I'm currently polling the endpoint every 3 seconds, what about rate limits? 
My app user base can probably considerably grow when it's out of the testing phase and published.

**Comment by asmitter** [comment]
Closing as a duplicate of #492 - please add your feedback over there.
