### ISSUE TITLE
Add is_following property to get a playlist endpoint

### ISSUE THREAD

**Issue by drsounds** [spotify/web-api#530]
There should be an property is_following: <true or false> indicating if the current authenticated user that retrieves the playlist are actually following the playlist or not.

**Comment by bih** [comment]
Hello @drsounds,

Thanks for your feature request! We're in the process of cleaning up our GitHub issue tracker (as per our [new developer support process](https://github.com/spotify/web-api)) to better serve you and other developers.

In this particular case, we decided not to prioritize this given the lack of compelling use cases. For that reason I'm going to close this as <kbd>wontfix</kbd> for now.

Though I encourage you and other developers to continue to share use cases and support for this feature - it helps us prioritize features in the future. You should still be able to comment on this issue. We will post updates here if there are any updates relating to this ticket 🙂

Thank you for taking the time to share your feedback, and please continue to do so! We highly appreciate it and of course reach out if you have any other questions!

Cheers 👍
