### ISSUE TITLE
Recently played tracks outdated

### ISSUE THREAD

**Issue by fan1200** [spotify/web-api#531]
Issue found on May 15th 2017.

#### Endpoint(s):
* `GET /v1/me/player/recently-played

#### Scope(s):
* 	user-read-recently-played

#### Steps to reproduce:
1. Open the API Console
2. Call the player/recently-played endpoint

#### Expected behaviour:
Gives back a up-to-date list with the recently played tracks.

#### Actual behaviour:
Tracks played after `2017-05-14T17:45:08.359Z` don't show up. I had this issue on May 1st but it was fixed, now its back.

**Comment by rickpern** [comment]
Seeing same issue as well. Duplicate of what happened with #512

**Comment by arirawr** [comment]
We're looking into this - thanks for the report.

**Comment by fan1200** [comment]
It seems to be working again.
