### ISSUE TITLE
Add "Rank" and "Active Listeners" to Artist Object

### ISSUE THREAD

**Issue by raju1210** [spotify/web-api#532]
Issue found on February 19th 2015.

#### Endpoint(s):
* `GET /v1/users/{user_id}`

#### Scope(s):
* None (application is not using authentication)

#### Steps to reproduce:
1. Open the API Console
2. Call the `get-users-profile` endpoint with `user_id` `%5E`

#### Expected behaviour:
A public user object as described on `https://developer.spotify.com/web-api/object-model/#user-object-public`.

#### Actual behaviour:
500 Server Error (consistently)

**Comment by arirawr** [comment]
Hi there - your issue's title doesn't match the description - could you update the description to better describe your issue or request?

**Comment by raju1210** [comment]
Hi

I would like to get from the spotify api for the following information like
: Artist name, Artist rank, Active listeners, followers, increment today
data. So whenever i run the code i would like to get the information
automatically.

**Comment by arirawr** [comment]
You can use the Get Artist endpoint (documented here: https://developer.spotify.com/web-api/get-artist/) to get the artist Name, Popularity, and Followers (as well as some other things).

If you would like additional data that is not contained in that endpoint, please specify so we can treat it as a feature request.

**Comment by raju1210** [comment]
Here in the above link we have artist name and followers, the Popularity is
different when checked with the rank in the spotify app. So it would be
great if we have rank, active listeners along with followers.

**Comment by bih** [comment]
Hello @raju1210,

As per our [new developer support process](https://github.com/spotify/web-api), any feature requests that have no plans to be considered in the next 6 months will be closed as <kbd>wontfix</kbd>. In this particular case there isn't sufficient interest in adding rank and active listeners to artists so we have decided not to focus on this for now.

We encourage you and other members of the community to continue to share use cases and your support for this feature, as it helps us prioritize features going forward. You should be able to comment on this issue even after it is closed. We will also post updates here relating to this suggestion as and when they happen.

Cheers 👍

**Comment by retnikt** [comment]
I was working on a game like Pointless using Spotify's API to get artists' popularity rank, because the Popularity field on an artist does not provide enough resolution for my game to work properly.
