### ISSUE TITLE
Track progress continues infinitely past the end of the track

### ISSUE THREAD

**Issue by mrmekon** [spotify/web-api#533]
Issue found on May 15th 2017.

#### Endpoint(s):
* `GET /v1/me/player/currently-playing`

#### Scope(s):
* user-read-playback-state
* user-read-private

#### Steps to reproduce:
1. Play a track on Spotify website, play.spotify.com
2. Close tab while track is playing.
3. Wait 5 hours.

#### Expected behaviour:
The currently-playing endpoint reports *is_playing* as false, *progress_ms* at the last played position.

#### Actual behaviour:
*is_playing* is true, *progress_ms* is growing infinitely past the end of the track.
```
  "progress_ms" : 17811662,
  "is_playing" : true,
...
    "duration_ms" : 179122,
```

```
Playback State:
Playing on Spotify Web Player [Volume 100%]
Linkan <spotify:track:4mjROuTzUFwnhOHFLkawWR>
17862.614s / 179.122s (9972.3%)
```

**Comment by sahayapoorva** [comment]
I am trying to get the current song being played in spotify, but the api is returning me a song which I played few hours back. I am using the same end point.
`GET /v1/me/player/currently-playing`

**Comment by bih** [comment]
Hello @mrmekon,

We're in the process of revisiting all of our Web API issues as [per our new developer support process](https://github.com/spotify/web-api).

In this particular case, we're not able to reproduce this issue and have not received any new reports in the past year over this. As I cannot confirm if it is resolved, I will close this as <kbd>inactive</kbd>.

Of course, if you're still having issues related to this, please create a new issue and reference this issue (#533) and we'll be happy to investigate this again!

Cheers 👍
