### ISSUE TITLE
Available Markets for some albums returning doubled results

### ISSUE THREAD

**Issue by stewart-wright** [spotify/web-api#535]
#### Endpoint(s):
* `v1/albums/`

#### Scope(s):
* None (application is not using authentication)

#### Steps to reproduce:
1. Open the API Console
2. Call the `albums` endpoint with `album_id` `64peTvbTLBDeSBu0GsCRE4`

i.e. goto [this page](https://api.spotify.com/v1/albums/64peTvbTLBDeSBu0GsCRE4)

#### Expected behaviour:
An album object with an 'available_markets' field containing a list of unique ISO country codes:

> "available_markets" : [ "AD", "AR", "AT", "BE", "BG", "BO", "BR", "CA", "CH", "CL", "CO", "CR", "CY", "CZ", "DE", "DK", "DO", "EC", "EE", "ES", "FI", "FR", "GB", "GR", "GT", "HK", "HN", "HU", "ID", "IE", "IS", "IT", "JP", "LI", "LT", "LU", "LV", "MC", "MT", "MX", "MY", "NI", "NL", "NO", "PA", "PE", "PH", "PL", "PT", "PY", "SE", "SG", "SK", "SV", "TR", "TW", "US", "UY" ]

#### Actual behaviour:
The above album object, but with the list of country codes duplicated:

> "available_markets" : [ "AD", "AR", "AT", "BE", "BG", "BO", "BR", "CA", "CH", "CL", "CO", "CR", "CY", "CZ", "DE", "DK", "DO", "EC", "EE", "ES", "FI", "FR", "GB", "GR", "GT", "HK", "HN", "HU", "ID", "IE", "IS", "IT", "JP", "LI", "LT", "LU", "LV", "MC", "MT", "MX", "MY", "NI", "NL", "NO", "PA", "PE", "PH", "PL", "PT", "PY", "SE", "SG", "SK", "SV", "TR", "TW", "US", "UY", "AD", "AR", "AT", "BE", "BG", "BO", "BR", "CA", "CH", "CL", "CO", "CR", "CY", "CZ", "DE", "DK", "DO", "EC", "EE", "ES", "FI", "FR", "GB", "GR", "GT", "HK", "HN", "HU", "ID", "IE", "IS", "IT", "JP", "LI", "LT", "LU", "LV", "MC", "MT", "MX", "MY", "NI", "NL", "NO", "PA", "PE", "PH", "PL", "PT", "PY", "SE", "SG", "SK", "SV", "TR", "TW", "US", "UY" ],

I haven't figured out why this happens or noticed a pattern with it, but it happens with more than just this one id. Other examples: 6BfdhquO8h8n74ZGTvYVVU, 0ZDX7TUhxIn3S9PzO069hX, 3PEIsRKWPx5w1RSoOnrOoh

**Comment by asmitter** [comment]
Thanks for the report @stewart-wright - we'll take a look.

**Comment by jstlnd** [comment]
@stewart-wright we've deployed a fix for this.
Please let us know if you have any further issues.
And thanks for you report!
