### ISSUE TITLE
Get Artist / Track Popularity by Region

### ISSUE THREAD

**Issue by alex-billetsca** [spotify/web-api#536]
Using the WebAPI, a query as follows: **/v1/artists/{id}?country={countryCode}** could return artist data pertaining to that country.
Ideally something more specific, like regions within a country.

We want to be able to gauge interest in an artist for our region.

**Comment by hughrawlinson** [comment]
Thanks for the feature request!

**Comment by felixmichel** [comment]
@hughrawlinson any plans on making this feature available?

**Comment by patalanov** [comment]
yep, we're waiting...as a general suggestion, any feature relative to location (artist) would be extremely useful, not to say profitable.

**Comment by bih** [comment]
Hello @alex-billetsca,

Thanks for your feature request! We're in the process of cleaning up our GitHub issue tracker (as per our [new developer support process](https://github.com/spotify/web-api)) to better serve you and other developers.

In this particular case, we discussed this and decided that whilst it is a great feature request, it is something that we don't have any plans to address in the next six months. For that reason I'm going to close this as <kbd>wontfix</kbd>.

Though I encourage you and other developers to continue to share use cases and support for this feature - it helps us prioritize features in the future. You should still be able to comment on this issue. We will post updates here if there are any updates relating to this ticket 🙂

Thank you for taking the time to share your feedback, and please continue to do so! We highly appreciate it and of course reach out if you have any other questions!

Cheers 👍

**Comment by bdyetton** [comment]
Hi, any update on plans for this feature?
Thanks 😊

**Comment by Instrumedley** [comment]
yeah, I'd also be interested in this
