### ISSUE TITLE
How can I get the currently playing with Spotify Connect?

### ISSUE THREAD

**Issue by WoLpH** [spotify/web-api#54]
The new Spotify Connect feature is really awesome, but it would be great if I could make other apps (like Plex for example) aware of what Spotify is currently playing. Is there any way to do that using the web API or do I have to meddle around with native API's?

**Comment by thelinmichael** [comment]
Hi @WoLpH! This isn't possible at the moment, and but this feature is tracked in #12.

**Comment by WoLpH** [comment]
Are you sure that's the same? I'm taking specifically about spotify connect, I want to use the Web API as a remote control l

**Comment by thelinmichael** [comment]
If the feature is to retrieve the currently playing track, potentially also retrieving at what device the track is playing on, then I perceive this issue to be the same as #12. If you disagree, feel free to reopen the issue and elaborate a bit on why it differs. If you want to add a bit more about your use case that would be very interesting to read about as well.

**Comment by WoLpH** [comment]
The story is that many people have a home theatre setup these days, yours truly included. And while most of those do support playing from Spotify it makes controlling it remotely a bit of a hassle.

If it would be possible to control Spotify remotely it would allow for Plex, Kodi, MediaPortal and similar apps to show what's playing and maybe even add some visualization and/or album art to it.

**Comment by thelinmichael** [comment]
I believe this feature is indeed captured in #12 since that'd work in the cases you mentioned. Changing the currently playing context (e.g. play this playlist) is captured in #15.
