### ISSUE TITLE
Search gives Bad gateway on specific queries

### ISSUE THREAD

**Issue by oscarmarcelo** [spotify/web-api#541]
Issue found on March 2017.

#### Endpoint(s):
* `GET /v1/search`

#### Scope(s):
* None

#### Steps to reproduce:
1. Open the API Console
2. Call the `search` endpoint with one of the following queries and `type` set to `track`:
   - `track:Chocolat:+Main+Titles+artist:Rachel+Portman+album:Chocolat+-+Original+Motion+Picture+Soundtrack`
   - `track:Wicked+Game+-+Acoustic+artist:Peter+and+Kerry+album:Benaize`
   - `track:Miss+You+-+HONNE+Remix+artist:James+Hersey+album:Miss+You+(HONNE+Remix)`
   - `track:I'm+Forrest...+Forrest+Gump+artist:Alan+Silvestri+album:Forrest+Gump+-+Original+Motion+Picture+Score`
   - `track:Fathead+-+Remastered+artist:David+Newman+album:Pure+Genius:+The+Complete+Atlantic+Recordings+1952-1959`
   - `track:The+Future+-+Main+Titles+artist:John+Ottman+album:X-Men:+Days+of+Future+Past+(Original+Motion+Picture+Soundtrack)`

#### Expected behaviour:
A list of track objects as described on `https://developer.spotify.com/web-api/search-item/`.

#### Actual behaviour:
502 Bad gateway (consistently on specific queries)

**Comment by crohrer** [comment]
Same Problem for me. 
Example for Bad Gateway:
`curl -X GET "https://api.spotify.com/v1/search?type=track&q=artist:AND+YOU+WILL+TRAIL" -H "Accept: application/json" -H "Authorization: Bearer xxx"`

if I change `AND` in my query to something else (like `ANG`), it works correctly:
`curl -X GET "https://api.spotify.com/v1/search?type=track&q=artist:ANG+YOU+WILL+TRAIL" -H "Accept: application/json" -H "Authorization: Bearer xxx`

**Comment by crohrer** [comment]
This might be identical with #527

**Comment by an-tex** [comment]
there seems to be an issue if the term contains AND or OR at either the beginning or the end.

**Comment by crohrer** [comment]
Correct and also for the term NOT

**Comment by oscarmarcelo** [comment]
@crohrer @an-tex No, this doesn't have anything to do with authentication issues or, in the case of this issue that I created, with operator terms, as you can see in the examples I gave.

**Comment by arirawr** [comment]
This issue should now be resolved. Thanks for your report!

Please feel free to reopen if you continue to see this issue occur.
