### ISSUE TITLE
403 Forbidden when calling /play on an unavailable device

### ISSUE THREAD

**Issue by r1sba93** [spotify/web-api#544]
Issue found on May 23rd 2017.

#### Endpoint(s):
* PUT https://api.spotify.com/v1/me/player/play?device_id=###

#### Scope(s):
playlist-modify-public 
playlist-modify-private 
user-read-playback-state 
user-modify-playback-state 
user-read-recently-played

#### Steps to reproduce:
1. Authenticate user and store access token
2. Make call to Player endpoint to play a track on given device

#### Expected behaviour:
User's playback should change on the given device (if the device is active).

#### Actual behaviour:
Playback does not start and status code = 403. Note this does not happen all the time, but it is happening for the same user with the same access token (the user is Premium). Seems to be somewhat tied to the device although in that case I would expect error 404.

**Comment by imthatcarlos** [comment]
+1 I'm seeing the same issue, although with different scopes. I do have "user-modify-playback-state" scope, though.

**Comment by seahorsepip** [comment]
Can't get it to work either :(

**Comment by Gawen** [comment]
I currently have this issue (I'm premium and I do have the scope `user-modify-playback-state`). **When I perform the example request on the Web console, I also get a 403**. Although everything was fine 1h ago.

**Comment by asmitter** [comment]
@Gawen do you still have the error now?
If so, what device are you targeting and is it active/online?

**Comment by Gawen** [comment]
@asmitter I realized that a 403 is returned when no player is launched (in my case, the Android application) (no arg `device_id` is set). The endpoint works when a player is available.

I checked the documentation, the only mention of the status code 403 is the following:

> If the user making the request is non-premium, a 403 FORBIDDEN response code will be returned.

FWIW I would have preferred an explicit error returned by the endpoint, and not a 403 which leads me to the wrong direction of a API's scope issue.

**Comment by asmitter** [comment]
@Gawen Thanks for the extra info.
I agree that 403 FORBIDDEN being returned under those circumstances is pretty misleading.
I've managed to replicate it and we'll see about returning something more suitable.

**Comment by hughrawlinson** [comment]
Hi! We haven't been able to replicate this issue in a while, so I'll close the ticket. If anyone is still able to replicate it, please feel free to reopen this ticket and ping me to let me know :)

**Comment by dukeblue2017** [comment]
I've replicated this issue. 403 comes back. I specified 'context_uri' and offset by 'uri' or 'position'.

**Comment by seahorsepip** [comment]
@dukeblue2017

Please post the exact request with parameter values that results in a 403.

**Comment by dukeblue2017** [comment]
This usually works, but for some reason wasn't that day, I believe because of the lack of a currently playing device or some related factor.

```
curl -X PUT \
  https://api.spotify.com/v1/me/player/play \
  -H 'Content-Type: application/json' \
  -H 'Postman-Token: <TOKEN> \
  -d '{
	"context_uri" : "<PLAYLIST_URI>",
	"offset": {
		"position": 1
	}
}'
```

**Comment by jscholes** [comment]
When you actually send the request, are you including an Authorization header with a valid access token?  Your example curl command only shows a Postman-Token header.

**Comment by dukeblue2017** [comment]
Yes, I am. Sorry about that. I've edited my prior post to reflect that.

**Comment by zearg** [comment]
Your device has to be in "pause" to be played
