### ISSUE TITLE
'Insufficient client scope' error for only one user of an SDA

### ISSUE THREAD

**Issue by raffjones** [spotify/web-api#546]
I have a strange situation where only one user is having an issue with an SDA.

When trying to add a track to a public playlist that they own, we are seeing the error `Insufficient client scope`. 

However, they authorized the same app as everyone else, and nothing has changed in the scope request. We have always had `['playlist-modify', 'user-read-private']`  - this scope should cover it, right?

Is there any way, using the API, to check the scope granted to a user against an API token?

**Comment by hughrawlinson** [comment]
@raffjones sorry to hear you're having an issue.

> Is there any way, using the API, to check the scope granted to a user against an API token?

Yes, *if* you followed the authorization code flow and have a refresh token. You can refresh the token [as described in our Authorization Guide](https://developer.spotify.com/web-api/authorization-guide/#request-access-token-from-refresh-token), the response will tell you what scopes the token is authorized for.

**Comment by raffjones** [comment]
@hughrawlinson Thanks very much for that steer.

I put some logging in place and got this for the problematic user:

        {
          "result": {
            "access_token":"NOT SHOWN",
            "token_type":"Bearer",
            "expires_in":3600,
            "scope":"playlist-modify user-read-private"
          }
        }

So the scopes are correct. It's not that.

However, the request to add the playlist track still results in the `Insufficient client scope` error.

When I create an open.spotify.com playlist link for the ID throwing the error, I see a valid playlist: https://open.spotify.com/user/mollycullenn/playlist/4jK41FsJvdR18UVJVvOqfx

But when I get the user's playlists back, this ID is not amongst them. Does this just mean it been deleted on Spotify? And if so, is the API access for the user who originally created the playlist revoked once it is deleted?

And finally, if that is the case, why does the open.spotify.com list continue to work, with no indication that the playlist has been deleted? Does Spotify continue to provide links to deleted playlists?

I can't see any option to also include a user's deleted playlists when requesting them.

**Comment by hughrawlinson** [comment]
Hi @raffjones - as mentioned in the [Working with Playlists](https://developer.spotify.com/web-api/working-with-playlists/) guide, playlists don't get deleted, just unfollowed. In this case it looks like the user has 'deleted' the playlist in their Spotify client (or elsewhere) - this means that they've unfollowed their own playlist and now no longer have permission to modify the playlist. In order to edit it, they'd need to follow the playlist again (or you can do this in your app).
