### ISSUE TITLE
Add a queue-button to embedded iframes to be able to instantly queue shared tracks

### ISSUE THREAD

**Issue by hagronnestad** [spotify/web-api#548]
A queue-button on the embedded iframe would be great when sharing music in chat applications. I always listen to music at work and when someone shares a track with me I have to copy the URI, paste it in the search box, and queue it. Pressing the play button cancels my current playlist.

Screenshot from Slack showing the embedded Spotify-player:

![image](https://cloud.githubusercontent.com/assets/1651402/26485623/12a456fc-41f8-11e7-9054-86b94de5720e.png)

**Comment by hughrawlinson** [comment]
Thanks for the feature request @hagronnestad - we'll consider it! This issue tracker is for the Web API though, and this feature request isn't in scope, I'd suggest also filing it on community.spotify.com.

**Comment by hagronnestad** [comment]
Thanks @hughrawlinson. For reference: https://community.spotify.com/t5/Idea-Submissions/Social-Add-a-queue-button-to-embedded-iframes-to-instantly-queue/idi-p/1698174#M49508
