### ISSUE TITLE
Searches with Numbers Not Possible / Unreliable

### ISSUE THREAD

**Issue by jlandrum** [spotify/web-api#55]
If searching for a track, the results are often empty or unrelated:

**AFI - Prelude 12/21**
*Query: artist:afi track:prelude 12/21*
`curl -X GET "https://api.spotify.com/v1/search?q=artist%3A%22afi%22+track%3A%22prelude+12%2F21%22&type=track" -H "Accept: application/json"`
Produces no results.

**Stone Sour - 30/30-150**
*Query: 30/30-150*
`curl -X GET "https://api.spotify.com/v1/search?q=30%2F30-150&type=track" -H "Accept: application/json"`
Produces no results

**Stone Sour - 30/30-150**
*Query: 30/30 150*
`curl -X GET "https://api.spotify.com/v1/search?q=30%2F30+150&type=track" -H "Accept: application/json"`
Produces results, but none of them are for Stone Sour

Some however, do work:
**Smashing Pumpkins - 1979**
*Query: 1979*
`curl -X GET "https://api.spotify.com/v1/search?q=1979&type=track" -H "Accept: application/json"`

Judging by this:
**Gorillaz - 5/4**
*Query: 5/4*
`curl -X GET "https://api.spotify.com/v1/search?q=5%2F4&type=track" -H "Accept: application/json"`

Numbers are getting converted into literals, which prevents songs with digits from being discovered.

**Comment by thelinmichael** [comment]
The Web API doesn't currently respect some characters when searching, e.g. `/`. Since this prevents you from finding certain tracks, I'd definitely consider this a bug. The Web API does return e.g. `Thirty` instead of `30`. This is the same behavior as in the Spotify apps. There's no way to turn this off though.

**Comment by hughrawlinson** [comment]
@jlandrum search now supports `/` and `-` characters! I tried the searches you mentioned in your report, and they're all working 😄 Let us know if you find any issues.
