### ISSUE TITLE
Cannot get featured Playlists for a specific date and time. in the past. Timestamp parameter does not alter the results

### ISSUE THREAD

**Issue by adonnelly** [spotify/web-api#550]
Issue found on May 25th 2017.

#### Endpoint(s):
* `https://api.spotify.com/v1/browse/featured-playlists`

#### Scope(s):
* None (application is using authentication but scope not required)

#### Steps to reproduce:
1. Open the API Console
2. Call the `featured-playlists` endpoint with `country` `GB` and timestamp '2001-10-26T11:00:00' 
(that date is a friday)

#### Expected behaviour:
A list of Featured playlists for that date and time. (note the date predates spotify). According to docs

>  timestamp	Optional. A timestamp in ISO 8601 format: yyyy-MM-ddTHH:mm:ss. Use this parameter to specify the user's local time to get results tailored for that specific date and time in the day. 

#### Actual behaviour:
It returns a list of featured playlists that's equal to the most recent fridays featured playlist at that time. eg

`https://api.spotify.com/v1/browse/featured-playlists?country=GB&timestamp=2001-10-26T11%3A00%3A00&offset=0&limit=20`

results are the same as

`https://api.spotify.com/v1/browse/featured-playlists?country=GB&timestamp=2012-10-26T11%3A00%3A00&offset=0&limit=20`

and
`https://api.spotify.com/v1/browse/featured-playlists?country=GB&timestamp=2017-05-26T11%3A00%3A00&offset=0&limit=20`

**Comment by asmitter** [comment]
I think the issue is you're trying to go back too far into the past. Spotify was founded in 2006, so getting playlists for 2001 is perhaps a little ambitious. :)
(Similarly, I believe the Browse feature was introduced around late 2013, so 2012 likely won't work either)

If you try it out with the example given - 2014-10-23T09:00:00 - you can see that it does indeed give different results: https://developer.spotify.com/web-api/console/get-featured-playlists/?timestamp=2014-10-23T09%3A00%3A00&country=GB

I don't know exactly how far back they go - or how long we intend to keep them around - but I'll make a note to update the docs so it's more clear what happens when data for a date doesn't exist.

**Comment by adonnelly** [comment]
Hi,
Thanks for responding and helping with this issue. I still think there is a bug here. Firstly I realize spotify was founded in 2006, that is why I put in that date to demonstrate that no matter what date I put in, the result will always match a date that is the same day of the week. If I put in your date 23 Oct 2014, a Thursday I get the most recent thursdays playlists, and not as they where on 23-10-2014. Ditto for 22-05-2017, a monday. I get back the play list as they where yesterday 29-05-2017.

I have attached some files showing this. 
## Examples 1:
I have compared your parameters https://developer.spotify.com/web-api/console/get-featured-playlists/?timestamp=2014-10-23T09%3A00%3A00&country=GB
which is thursday 23 Oct 2014. to last thursday 25-10-2017. the results are the exact same. Which means in 3 years you displayed the same featured playlist. My results are attached. 

[2014-10-23.txt](https://github.com/spotify/web-api/files/1038289/2014-10-23.txt)
[2017-05-25.txt](https://github.com/spotify/web-api/files/1038290/2017-05-25.txt)

## Examples 2:
Last week I kept a report of mondays plays lists at 10am in GB (22-05-2017). One week later I got the new plays lists and the results had changed slightly. Great. However I then reran the api call but swapping this mondays date with last mondays date and last mondays play list now matches this weeks version. See results attached
[results.txt](https://github.com/spotify/web-api/files/1038337/results.txt)

So to me the api is parseing the entered timestamp to get a day of week and returns the current day of week plat list. So in your example is returns thursday play from last week and not as it was on the 23-10-2014. I hope this make sense. kind regards Adrian
