### ISSUE TITLE
Question about track popularity when it is from an album and a single

### ISSUE THREAD

**Issue by tlss94** [spotify/web-api#553]
Hi,

I got 2 different results for track popularity when it is from an album and a single.
**SHawn mendes treat you better** 
https://api.spotify.com/v1/tracks/1mSlftOO1dlDRXAyOE0Sbd
this one got 22 as track popularity

https://api.spotify.com/v1/tracks/3QGsuHI8jO1Rx4JWLUh9jd
this one got 76 

...
I would trust the second better as it is a recent track

but how to explain the discrepancy?

SPotify API doesn t give much more explications:
'Duplicate tracks (e.g. the same track from a single and an album) are rated independently. '

but which one to select??

thanks you

**Comment by asmitter** [comment]
There is no "correct" one to select - popularity is calculated on the individual track level, and even though these may be the same song, they are in the Spotify system as unique tracks (hence different ids). This could be for a number of reasons including a change of label, licensor, or regional variations.

As Spotify has them as unique tracks, their popularity is ranked independently. Which one you select is up to you and your use case. In general I recommend selecting the one most region appropriate.
