### ISSUE TITLE
Search API

### ISSUE THREAD

**Issue by amilcar-andrade** [spotify/web-api#554]
Issue found on May 29th, 2015.

#### Endpoint(s):
* `GET v1/search`

#### Scope(s):
* None (application is not using authentication)

#### Steps to reproduce:
1. Open a terminal
2. Use curl to make a request. e.g `curl -X GET "https://api.spotify.com/v1/search?q=tania%20bowra&type=artist"`

#### Expected behaviour:
Get a list of results from my search. By the way, this was working fine last week.

#### Actual behaviour:
401 No token provided(consistently)

According the documentation a token is not required for the `search` API. See attached image.
<img width="899" alt="screen shot 2017-05-29 at 12 18 43 pm" src="https://cloud.githubusercontent.com/assets/802308/26556575/4ae4e234-4469-11e7-949d-36282f56fd46.png">

**Comment by alvgarcia** [comment]
Hi,
the same thing is happening to me. I had an app running perfectly a few hours ago and now I have started receiving this "401 No token provided" error when searching.

**Comment by hughrawlinson** [comment]
Hey,

As [announced on Jan 27th](https://developer.spotify.com/news-stories/2017/01/27/removing-unauthenticated-calls-to-the-web-api/), all endpoints will require an access token as of today. Docs will be updated asap :)

**Comment by amilcar-andrade** [comment]
Thanks mate!
