### ISSUE TITLE
Delete Playlist Endpoint?

### ISSUE THREAD

**Issue by 0xNF** [spotify/web-api#555]
Could we get a delete playlist endpoint?
Might seem dangerous, but given that we can already delete a playlists tracks, doesn't seem like a huge increase in danger.

**Comment by jscholes** [comment]
As covered on the [Working With Playlists page](https://developer.spotify.com/web-api/working-with-playlists/):

> We have no endpoint for deleting a playlist in the Web API; the notion of deleting a playlist is not relevant within the Spotify’s playlist system. Even if you are the playlist’s owner and you choose to manually remove it from your own list of playlists, you are simply unfollowing it. Although this behavior may sound strange, it means that other users who are already following the playlist can keep enjoying it. Manually restoring a deleted playlist through the Spotify Accounts Service is the same thing as following one of your own playlists that you have previously unfollowed.

Presumably then, when you choose to delete a playlist inside one of the official Spotify apps, the system simply unfollows it, and then only shows followed playlists in the playlist list.  I'm not sure how, using the UI of one of Spotify's own apps, you would restore a deleted playlist, but simulating this behaviour in your own app shouldn't be too difficult.  Hope that helps!

**Comment by hughrawlinson** [comment]
@jscholes is correct, as ever! As mentioned in the Working With Playlists page, to "delete" a playlist from a user's account, you simply unfollow it.

**Comment by 0xNF** [comment]
Awesome, thanks for the answer, guys.

I missed it under the Working With Playlists page, but I did try to search for it under some of the doc pages. It's notable that nothing of obvious relevance comes up if you search for "delete playlist on the site either.  (see: [here](https://developer.spotify.com/search/?q=delete+playlist))

**Comment by platelminto** [comment]
Is there no way of knowing if a playlist has been deleted then? When [getting a playlist](https://developer.spotify.com/documentation/web-api/reference/playlists/get-playlist/) that has been 'deleted' through the official app, it still exists, and you still show up as its owner. 

The only change I see is that the deleted playlist is no longer public, but if the playlist was private in the first place, there is no change, and no apparent way of telling that its actually been deleted.

Anyone know a possible workaround to this?

**Comment by chevtek** [comment]
@platelminto As far as I can tell you are correct, we have no way of knowing if they have unfollowed their own playlist. The only idea I've come up with so far is to pull down a list of all their playlists and check if it contains the playlist ID in question.

**Comment by chevtek** [comment]
@platelminto Actually! We just found out we can query a follow endpoint to figure out if a user follows a specific playlist.

`https://api.spotify.com/v1/playlists/{playlist_id}/followers/contains`
