### ISSUE TITLE
'preview_url' field for many tracks is null but held content only a month ago 

### ISSUE THREAD

**Issue by pszujewski** [spotify/web-api#556]
#### Title: preview_url field is null but held content only a month ago for many tracks 

Issue found on May 30th 2017.

#### Endpoint(s):
* `GET /v1/tracks/{id}`

#### Scope(s):
* None (application is not using user authentication)

#### Steps to reproduce:
1. Open the API Console
2. Call the `get-track` endpoint with following `ids` as an example The preview_url fields for these tracks did not hold 'null' only a month ago. I don't understand why these are no longer available (plz note that all these 3 tracks originate from movie soundtracks. Is there a connection?) `1eXDRxMJZ0ZaBk15TILd58`
`2KbglBRS8Ew01sEecfVpSL`
`6t9KVIxj1P4dKDahbcrV0f`

#### Expected behaviour:
The field should not be null but instead contain a link to a valid url for the audio track

#### Actual behaviour:
See above

**Comment by hughrawlinson** [comment]
Hi @pszujewski - as mentioned in [the documentation](https://developer.spotify.com/web-api/get-track/), the `preview_url` can be null if a preview is not available - for a huge variety of reasons, preview availability can vary over time, so any app should account for the possibility of an unavailable preview.

**Comment by shawns582** [comment]
@hughrawlinson Out of curiosity, do you happen to know what might have changed with the policies  in the recent weeks?
