### ISSUE TITLE
Returns tracks also when getting an artists' albums

### ISSUE THREAD

**Issue by 72lions** [spotify/web-api#56]
When you want to render an artist with maybe one album you need to do at least 3 requests. I am arguing that a solution where you get back tracks along with albums but with a more strict limit might give more power to the developer and more flexibility when developing using the API.

**Comment by darkhouse** [comment]
I want this as well. I'd also like to get albums when you select an artist. I'm building something right now where 1 request for an artist ends up becoming well over 100 calls after getting related artists, albums and tracks. Even just a list of ids would help reduce the number of calls.

**Comment by asmitter** [comment]
(Cleaning up old issues)
We've no plans to iterate on the current set of endpoints for getting Artist information.

If you are still interested in reducing the number of API calls when rendering all tracks for an artist's albums I suggest first calling [Get an Artist's Albums](https://developer.spotify.com/web-api/get-artists-albums/) and then passing the ids to [Get Several Albums](https://developer.spotify.com/web-api/get-several-albums/). The latter accepts up to 20 ids at a time, so while this may appear like a lot of overhead for an artist with 1 album, it scales much better when the artist has a lot of releases.
