### ISSUE TITLE
Generate Spotify Code for URI?

### ISSUE THREAD

**Issue by seahorsepip** [spotify/web-api#562]
https://news.spotify.com/us/2017/05/08/say-hello-to-spotify-codes/

A way to generate a Spotify code through this web api would be nice.

Either by getting an image response with an barcode image or by getting a bar code response that consists of an array of bar heights.

I tried to find out how the codes were generated and I did find some similarities between uris and the codes but whenever I tried to calculate a code from an uri it ended up being wrong :P 

Just a resource that explains how a code is calculated instead of an api endpoint would also be nice but might be less ideal since the implementation of this can change resulting in 3rd party apps/services showing codes that are generated with old logic and no longer recognizable.

**Comment by hughrawlinson** [comment]
Thanks for the feature request @seahorsepip, we'll consider it.

**Comment by seahorsepip** [comment]
Seems I made a duplicate request of: https://github.com/spotify/web-api/issues/519
