### ISSUE TITLE
Album Availability app not working

### ISSUE THREAD

**Issue by spotifyer** [spotify/web-api#563]
(Apologies if this is the wrong place to ask, my first post.)

After the latest Web API update few days ago, the 'Album Availability' app stopped working. It was very useful so I wanted to check if it can be updated to work again or it's now permanently defunct. Hopefully something can be done about it. Thanks!

http://developer.spotify.com/showcase/item/album-availability

**Comment by seahorsepip** [comment]
Seems like the https://api.spotify.com/v1/albums/<uri> endpoint requires an authorization code
Send the developer a message to update it.

**Comment by hughrawlinson** [comment]
Hey, I've contacted the developer of the app to let them know it's not working at the moment. Feel free to send them a PR, the project is open source :) I'll close this issue since it's not a problem with the web api.
