### ISSUE TITLE
Cannot retrieve profile for user with user id 1184742927

### ISSUE THREAD

**Issue by TLmaK0** [spotify/web-api#566]
Issue found on June 3th 2017.

#### Endpoint(s):
* `GET /v1/me`

#### Scope(s):
* 'user-modify-playback-state',
         'user-read-playback-state',
          'user-read-private',
          'playlist-modify-private',
          'playlist-modify-public'

#### Steps to reproduce:
1. Get a refresh and access token for user 1184742927 with this scopes
2. Call the `/v1/me` with access token

#### Expected behaviour:
A public user object as described on `https://developer.spotify.com/web-api/get-current-users-profile/`.

#### Actual behaviour:
```
{
  "error": {
    "status": 401,
    "message": "Invalid access token"
  }
}
```

It works with other user but not with user id 1184742927

**Comment by TLmaK0** [comment]
I'm able to reproduce this issue with 3 of 5 users. I have tested it on 2 different environments.

**Comment by TLmaK0** [comment]
Finally I found the problem, the access_token field in my database was limited to 255 chars, some users receive tokens with less length and others no.

**Comment by paulgoetze** [comment]
I just ran into the same problem (mine was of length 266). Why do access_tokens have different lengths?
I figure it must have sth to do with the playlist scopes (at least for me it appeared after adding all of them)? 
@hughrawlinson, @arirawr, could you bring this to light?

**Comment by arirawr** [comment]
@paulgoetze correct, the length of the access token is partially related to the scopes on the token. Generally, more scopes = longer token.
