### ISSUE TITLE
/v1/me/player/play does not log the album context

### ISSUE THREAD

**Issue by seahorsepip** [spotify/web-api#567]
Issue found on June 4th 2017.

#### Endpoint(s):
* `PUT /v1/me/player/play `

#### Scope(s):
* user-modify-playback-state

#### Steps to reproduce:
1. Use /v1/me/player/play to start playback of a track in a user's album
2. Get playback info from currently-playing endpoint

#### Expected behaviour:
A context value other then null.

#### Actual behaviour:
Context is null.

**Comment by seahorsepip** [comment]
Probably related to: https://github.com/spotify/web-api/issues/522

**Comment by asmitter** [comment]
Thanks for the report.
Can you share the parameters you are sending to the `/player/play` endpoint please?

**Comment by richoakley** [comment]
Yeah, same issue as #522

**Comment by arirawr** [comment]
Hey there, thanks for reporting! This is a duplicate of #522, so please follow that issue for updates.
