### ISSUE TITLE
Display Name is null for user with user ID "ludotestaccount"

### ISSUE THREAD

**Issue by tobyonono** [spotify/web-api#569]
Display Name is null for user with user ID "ludotestaccount"

Endpoint(s):
* `GET /v1/users/{user_id}`

Steps to reproduce:
1. Open the API Console
2. Call the `get-users-profile` endpoint with `user_id` 

Expected behaviour:
Give "ludotestaccount" for display_name

Actual behaviour:
![image](https://user-images.githubusercontent.com/10547294/26841154-8b9e7146-4ae0-11e7-8b98-31f20867192c.png)

**Comment by lrholmes** [comment]
`display_name` is not guaranteed. Pretty sure it contains the user's name that is gathered if they sign up with Facebook only. So if you sign up with email, you only have an id.

Solution is to check if `display_name` is empty, and if it is, display the ID instead (if that's how you're using it).

**Comment by ZinoKader** [comment]
@lrholmes That's how I've implemented it, unfortunately it seems like this endpoint is returning null for `display_name` more often that it did before. Furthermore, my own profile as well as family and friends' profiles who are all connected to Facebook and have their Spotify display name visibile everywhere are also returning null. I'm beginning to think that something is wrong on Spotify's end.

**Comment by lrholmes** [comment]
@ZinoKader well if you're sure that `display_name` should be there, then yeah that sounds like a bug. Hopefully one of the dev team will be able to help you out with that!

**Comment by tobyonono** [comment]
Ah, I did sign up with an email for that account. Thanks for clearing it up. I was just a bit confused because the id for an account I have through Facebook is an int and for the email only account is what I expect the display_name to be.

**Comment by cdtinney** [comment]
Still seeing this issue. Very frustrating.
