### ISSUE TITLE
Create playlist endpoint 400 error as of this morning.

### ISSUE THREAD

**Issue by jpiepkow** [spotify/web-api#573]
Title: Create playlist endpoint bad request 400 as of 10am eastern time this morning.

Issue found on February 19th 2015.

#### Endpoint(s):
* `GET /v1/users/{user_id}/playlists`

#### Scope(s):
* playlist-modify-public, playlist-modify-private

#### Steps to reproduce:
1. Open the API Console
2. Call the `create-playlist` endpoint with any userId

I noticed in my application that everything was not working because playlist create endpoint was not working due to 400 error. I went to the api console with my account and tried also getting a 400 with the default scope and payload body on that endpoint. I created a new account to make sure it was not something related to my account and also received a 400 error when trying to create. If someone could get back to me asap this is an important part of my application and something I would LOVE to get to the bottom of because I have not ran into this issue in the last 5 months. Thanks!

#### Expected behaviour:
Playlist created like normal

#### Actual behaviour:
400 bad request

**Comment by jmfortunatojr** [comment]
Having this same issue in our production application as well. The endpoint always returns a 400.

**Comment by sjaq** [comment]
I am experiencing the same issue. Even when using the Spotify web api console.

```bash
curl -X POST "https://api.spotify.com/v1/users/sjaq/playlists" -H "Accept: application/json" -H "Authorization: Bearer [SNIP]" -H "Content-Type: application/json" --data "{\"description\":\"Newplaylistdescription\",\"public\":false,\"name\":\"NewPlaylist\"}"

# Returns
{
  "error" : {
    "status" : 400,
    "message" : "Bad request"
  }
}
```

**Comment by jpiepkow** [comment]
I messaged spotifycares on twitter and am still waiting for a response there also

**Comment by rxdazn** [comment]
This also happens on the Spotify browser client:

<img width="741" alt="screen shot 2017-06-12 at 16 34 47" src="https://user-images.githubusercontent.com/1329626/27045124-e8f3416c-4f97-11e7-8bed-268bc22cc9e8.png">

**Comment by asmitter** [comment]
Thanks everyone for the reports. We had an issue with one of the services, which has now been fixed.
Please let us know if you see any more issues.
