### ISSUE TITLE
Playlist does not continue to play songs added via api

### ISSUE THREAD

**Issue by AJScanlan** [spotify/web-api#574]
Issue found on June 13th 2017.

#### Endpoint(s):
* `PUT /v1/me/player/play`
* `POST /v1/users/{user_id}/playlists/{playlist_id}/tracks`

#### Scope(s):
* user-modify-playback-state
* playlist-modify-public 
* user-read-playback-state

#### Steps to reproduce:
1. Add a song to playlist via api
2. Play the last song in the playlist via api
3. Add another song to the playlist while the first song is still playing

#### Expected behaviour:
The playlist should continue playing the rest of the playlist.

#### Actual behaviour:
The playlist stops after the last song, without playing any of the newly added songs.

#### Lack of queue api:
The lack of any queue endpoints means using a playlist as a sort of pseudo queue, unfortunately the playlist endpoints don't seem to be configured for this. 

Some dedicated queue endpoints would fix this problem as well as simplify any code that's currently using the playlist pseudo queue system.

**Comment by jpiepkow** [comment]
This would be awesome if this issue was fixed. I am like you using the playlists as a pseudo queue and have found that the play queue is updated as long as you have 1 song ahead of the current song your are playing. So my current solution is adding a song 20 seconds before the second to last song ends. It works but is superrr hackish.

**Comment by asmitter** [comment]
Thanks for the report.
The issue you are experiencing is around how the client playing (desktop/mobile etc) is handling the updates, so not something we can impact on the Web API side.
However, I believe the real solution to your use-case would be a queue endpoint so you don't need to rely on a playlist workaround. You can add your voice to that request on #462
