### ISSUE TITLE
500 error on out of bound position when adding track to playlist

### ISSUE THREAD

**Issue by jpiepkow** [spotify/web-api#575]
Title: 500 error on out of bound position when adding track to playlist

Issue found on February 19th 2015.

#### Endpoint(s):
* `POST /v1/users/{user_id}/playlists/{playlist_id}/tracks?position=1000

#### Scope(s):
* playlist-modify-public, playlist-modify-private

#### Steps to reproduce:
1. Open the API Console
2. try adding track to existing playlist in a position that is out of bounds(last position + 5)

#### Expected behaviour:
400 error explaining why the call failed.

#### Actual behaviour:
500 Server Error (consistently)

**Comment by arirawr** [comment]
I've been able to reproduce this and will get the appropriate team to look into it. Thanks for the report!

**Comment by arirawr** [comment]
This issue should now be resolved. Thanks for your report!

Please feel free to reopen if you continue to see this issue occur.
