### ISSUE TITLE
Status page?

### ISSUE THREAD

**Issue by jpiepkow** [spotify/web-api#576]
Is there a spotify api status page because I am receiving a lot of 500 and 502 errors today and have never ran into this issue so wondering if service is flaky today.

Thanks

**Comment by hughrawlinson** [comment]
Hey, we don't have a status page at the moment, but it's on our radar of improvements to make 😄

**Comment by megeek** [comment]
+1 on this...it's really helpful to know if 503s are because the service is having issues or something on our end...

**Comment by blackarcanis** [comment]
+1
Could be helpful to know about some 500 status code.

**Comment by mpash** [comment]
Any movement on this? @hughrawlinson

**Comment by avocade** [comment]
+1

**Comment by slim2k6** [comment]
+1

**Comment by bih** [comment]
Hello folks!

In this particular case, creating a status page for the Spotify Web API is a larger engineering task. This isn't something we plan to address in the next 6 months. And as per our [updated developer support process](https://github.com/spotify/web-api), we will close features that aren't being considered in the next 6 months as <kbd>wontfix</kbd>.

Given the popularity of this suggestion, we still encourage you folks (and others reading!) to continue to share possible use cases and support for this feature. It will help us going forward when we frequently revisit suggestions. We will post updates here relating to this suggestion so you can stay in the loop.

Hope this helps. Cheers 👍
