### ISSUE TITLE
PUT track to "play" endpoint repeats track over and over instead of continuing what was playing before after "next" endpoint

### ISSUE THREAD

**Issue by olejon** [spotify/web-api#578]
Issue found June 2017.

#### Endpoint(s):
* `https://api.spotify.com/v1/me/player/play`

#### Scope(s):
* `user-modify-playback-state`

#### Steps to reproduce:
1. Play a playlist, artist or album
2. PUT a track URI to the endpoint

#### Expected behaviour:
Playlist, artist or album should continue to play afterwards.

This is the same issue that is a bug in the Linux desktop client's MPRIS (D-Bus) implementation via OpenURI() and then Next().

#### Actual behaviour:
Track repeats over and over using `https://api.spotify.com/v1/me/player/next` or MPRIS.

Maybe I am missing how this is possible without using a complicated solution? I guess if one choose to play a track URI from a playlist, artist or album, one can PUT all track URIs and use `offset`, but that seems unnecessary. The standard desktop client's behaviour is to continue the previous playing playlist, artist or album after manually playing a track that is not part of that.

**Comment by asmitter** [comment]
Hi @olejon 
The `/play` endpoint is not a queue endpoint - it will overwrite what is playing with what you send it.
In this case sending a single track will overwrite whatever was previously playing, so that is then the only thing queued up.
There is an open request for queue endpoints over at #462

**Comment by olejon** [comment]
Ok. Queue would be very welcome. But still don't see why it can't just continue afterwards. No one wants the same track over and over.

**Comment by asmitter** [comment]
The key is in the name "`context_uri`"
A context is the list of tracks that is being played. An album is a context, as is a Playlist. A single track can also be a context.
In desktop client terms, when you double-click a playlist or click the big green "Play" button, you're setting a new context. So if you're playing one playlist, then navigate to another and click "Play", you do not return to the previous playlist what that one ends. It's a different context.
If you set a single track as the context, that's the use case that you want to play one track and *not* return to what was happening before. Queue is what you're after, which does not yet exist via the Web APIs.

**Comment by olejon** [comment]
Thanks. I understand​ this, although a track URI can not be passed as context in the API, but I understand what you mean by it being a context anyway.

I've managed to work around this problem by, if a user plays a track in a playlist for example, all the tracks in the playlist is added using the "uris" JSON array, shifting the URI (track) selected to be number 0 in the array and using the "offset" JSON integer to set it to 0, so it plays that track first if shuffle is enabled (otherwise it will play a random URI in the array).

Regarding Queue I have a solution for my app with Linux + dbus-monitor to get a signal from the desktop client when the track changes and then playing URIs in my queue database through the same "uris" JSON array. Only problem is that when the last track in the queue plays it plays over and over again as it's the last in the context, so my queue is like a playlist, but not in Spotify.

Transferring the playback to other devices works great and everything can be controlled. I'm really happy Spotify have such a great API and I didn't really see this coming as well. Looking forward to it coming out of beta, but so far 100 % stable for me. Also better documentation and good connection between the player API and the test web console (same documentation). But it can be understood trying and failing a bit!
