### ISSUE TITLE
player/repeat endpoint cannot be set

### ISSUE THREAD

**Issue by rdbartram** [spotify/web-api#581]
Title: player/repeat endpoint cannot be set "

Issue found on June17th 2017.

#### Endpoint(s):
* `PUT /v1/me/player/repeat?state=context`

#### Scope(s):
* "user-read-private", "user-read-email", "user-read-playback-state", "user-modify-playback-state"

#### Steps to reproduce:
1. Invoke REST endpoint with state=track or context or off

#### Expected behaviour:
Repeat mode should be appropriately set and HTTP 204 should be received

#### Actual behaviour:
VERBOSE: PUT https://api.spotify.com/v1/me/player/repeat?state=off) with 0-byte payload
400 Parameter state must be one of the following: track, context, off

**Comment by olejon** [comment]
It works here so you must to something wrong.

Have you tried it in the Web API Console?

https://developer.spotify.com/web-api/console/put-repeat/

Remember to get the necessary OAuth token there.

If it works, look at the cURL example that appears below and check that your request is equal.

Also of course Spotify Premium is needed.

I just tested with the latest Linux client.

**Comment by arirawr** [comment]
Hi @rdbartram - I'm not able to reproduce this. Please check out the Web API Console as linked in the previous reply. You should get a working curl command like the following:

`curl -X PUT "https://api.spotify.com/v1/me/player/repeat?state=off" -H "Accept: application/json" -H "Authorization: Bearer <your_access_token>"`

**Comment by hughrawlinson** [comment]
Hi @rdbartram - we're not able to reproduce this and we haven't heard back from you, so we'll close this issue - please feel free to reopen it if you're still experiencing it and we'll try and find a good way to reproduce it.
