### ISSUE TITLE
Can not PUT more than 226 tracks with offset key or more than 228 tracks without offset key to /play endpoint

### ISSUE THREAD

**Issue by olejon** [spotify/web-api#582]
Issue found on June 19th 2017.

#### Endpoint(s):
* `https://api.spotify.com/v1/me/player/play`

#### Scope(s):
* user-modify-playback-state

#### Steps to reproduce:
1. Try to add *more* than 226 tracks with the offset key set, or more than *228 tracks* without the offset key 

#### Expected behaviour:
The tracks will play.

#### Actual behaviour:
**500 Server Error (consistently)**

The data is sent minimized without spaces. It seems that there is some limit of HTTP Request Header: `Content-Length` between 9130 (works) and 9170 (does not work).

Any workaround? If not this should be fixed, and at least in the documentation.

Thanks for any workarounds!

**Comment by arirawr** [comment]
Hello!

There is a maximum request size, and you appear to have exceeded that.

To play a large number of tracks, I recommend creating a playlist (which you can also do through [the API](https://developer.spotify.com/web-api/create-playlist/)) and then providing that playlist as the `context_uri` when you call the Play endpoint.

**Comment by olejon** [comment]
Thanks for the confirmation. It should be in the docs though. Creating a Playlist is a bad workaround in my case because I use it so that the user can view a playlist, then play a single track in that Playlist, and continue with the rest of the tracks, so I put them all in an array and PUT them to the API, using the offset key to continue playback from that track if shuffle is off to not start always at the first track in the list when playing next track.

Why is it not possible to provide a context_uri along with a list of URIs? That way, one could put a single track from the playlist to the API and the playlist URI as context_uri so that the Playlist continues to play after the track. That way only two URIs would be needed to send to the API.

ALSO it would effectively make it a Queue API which many want as one could then put singlr tracks to the API, for example all tracks in an album and then a Playlist as context and the playlist would play when the album finishes.
