### ISSUE TITLE
/v1/me/player - "non existing id"

### ISSUE THREAD

**Issue by gLarsVegas** [spotify/web-api#583]
I'm using the [/v1/me/player](https://developer.spotify.com/web-api/get-information-about-the-users-current-playback/) function in my script. Sometimes it just returns "non existing id" for a couple of days. I couldnt find any explaination for this behaviour.

To what "id" is it referring to?

**Comment by hughrawlinson** [comment]
Hey - does this only happen when you're playing local tracks on your device?

**Comment by PaulGreefhorst** [comment]
I did notice the same, and as a maater of fact it happens when I played a local file

**Comment by gLarsVegas** [comment]
Seems to be due to local tracks. Tanks @hughrawlinson
