### ISSUE TITLE
Angular 2/4 / jQuery POST - cannot add Authorization header

### ISSUE THREAD

**Issue by nicraMarcin** [spotify/web-api#586]
When I try to add Authorization header to AJAX request api server refuse connection because of OPTIONS method

```
//General
Request URL:https://accounts.spotify.com/api/token
Request Method:OPTIONS
Status Code:204 No Content
Remote Address:194.132.197.231:443
Referrer Policy:no-referrer-when-downgrade


//Response Header
HTTP/1.1 204 No Content
Server: nginx
Date: Thu, 22 Jun 2017 18:13:54 GMT
Connection: keep-alive
Keep-Alive: timeout=600
X-Content-Type-Options: nosniff
Strict-Transport-Security: max-age=31536000;

//Request Header
OPTIONS /api/token HTTP/1.1
Host: accounts.spotify.com
Connection: keep-alive
Access-Control-Request-Method: POST
Origin: http://localhost:4200
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.86 Safari/537.36
Access-Control-Request-Headers: authorization
Accept: */*
Referer: http://localhost:4200/
Accept-Encoding: gzip, deflate, br
Accept-Language: pl,en;q=0.8,en-US;q=0.6
```

I try to get response this function
```
getToken(){

 let headers = new Headers;
 headers.append('Authorization', 'Basic ' + btoa(Spotify.clientId + ':' + Spotify.clientSecret));
 headers.append('Content-Type', 'application/x-www-form-urlencoded');

 let options = new RequestOptions({ headers: headers });


l et params = new URLSearchParams();
 params.append('grant_type', 'client_credentials');


  this.http.post(Spotify.tokenUrl, params.toString(), options).subscribe()
}

```

Because of xhr, and only xhr, uses Preflight request /api/token should accept OPTIONS method to allow next query with post and Authorization header. 

link to topic in stackoverflow [https://stackoverflow.com/questions/44671112/angular-2-4-how-to-add-multiple-headers-to-http-post](url)

**Comment by hughrawlinson** [comment]
Hi,

You shouldn't make a request to the `/api/token` on the `accounts.spotify.com` service from the browser. For that API to work, regardless of the flow, it requires the client secret, which should at no point be in a browser. If you've already done this, you should regenerate your client secret, which can be done in the My Applications section of developer.spotify.com. Two of our three authentication flows require a request to be made on behalf of your application to that endpoint, supplying the client secret - the Authorization Code flow, and the Client Credentials flow. Both of these flows should be carried out in a secure environment, that doesn't expose the client secret (for example, a server). If you need to use one of these flows, I suggest building a small serverside application to handle authentication, along with storage of sensitive data (like client secret, refresh tokens), and proxy requests to the API via that server to maintain security of the data. Alternatively, you can use the Implicit Grant flow, which does not require a server, and yields short-lived access tokens suitable for many web app use cases. More information can be found in our (Authorization Guide](https://developer.spotify.com/web-api/authorization-guide/).

Best,

Spotify Developer Support

**Comment by nicraMarcin** [comment]
Hi,
Thanks for explanation. I follwed by your advice
```
Request URL:https://accounts.spotify.com/authorize?client_id=21006d1ceecb456fakeKeyd62d&redirect_uri=http://localhost:4200/callback&scope=user-read-private%20user-read-email&response_type=token&state=789935
Request Method:GET
Status Code:200 OK
Remote Address:194.132.197.246:443
Referrer Policy:no-referrer-when-downgrade


//Response
HTTP/1.1 200 OK
Server: nginx
Date: Fri, 23 Jun 2017 07:14:12 GMT
Content-Type: application/json
Transfer-Encoding: chunked
Connection: keep-alive
Keep-Alive: timeout=600
Vary: Accept-Encoding
Vary: Accept
Set-Cookie: csrf_token=AQAlhASeHFDJcnkFqhrAdPeMN5aQurwP9HXf25MIzYmZv0_jvYkCtTugGjHtYkCJFxYAwgJJRQlRl7Q;Version=1;Domain=accounts.spotify.com;Path=/;Secure
X-UA-Compatible: IE=edge
X-Frame-Options: deny
Content-Security-Policy: default-src 'self'; [..];
Cache-Control: no-cache, no-store, must-revalidate
Pragma: no-cache
Content-Encoding: gzip
X-Content-Type-Options: nosniff
Strict-Transport-Security: max-age=31536000;
```
and I get strange answer, no redirect or Code :/
```
{"client":{"name":"ng"},"country":"PL","locales":["pl","en","en_US"],"BON":["0","0",1743222955]}
```

**Comment by stokalakis** [comment]
Hi @nicraMarcin - Correct me if I'm wrong, but this is an issue tracker, not a forum for general coding questions (and to me, this does not look like a bug/feature request). Please go and read the manuals; if this does not help you, use stackoverflow or something similar.

**Comment by nicraMarcin** [comment]
Ok, I'm sorry.

**Comment by hughrawlinson** [comment]
Hey @nicraMarcin, we're happy to help with your issue :) The `accounts.spotify.com/authroize` url presents an oauth dialog to a user - rather than making a request from your code to the URL, you should present it to the user in a popup, iframe, or via a redirect. Once the user has granted or denied permission, they will be redirected to your app and data will be contained in the hash of the redirect url.
