### ISSUE TITLE
Duplicate results in Get an Artist's Albums API endpoint

### ISSUE THREAD

**Issue by ashtianicode** [spotify/web-api#587]
Issue found on January 22th 2017.

#### Endpoint(s):
* `GET /v1/artists/{}/albums?limit=50&market=US`

#### Steps to reproduce:
1. GET the endpoint  artist albums for artist="metallica" and you will find some duplicate albums

#### Expected behaviour:
not to get duplicate results . here is a link to difference between two items in results for 
 artist= "metallica" albums : [https://www.diffchecker.com/ErP8svtH](url)

#### Actual behaviour:
duplicate items in search results.

**Comment by hughrawlinson** [comment]
Hey, thanks for flagging this, we'll look into it and let you know.

**Comment by bih** [comment]
Hello @ashtianicode,

Thanks for your bug report! We're in the process of cleaning up our GitHub issue tracker (as per our [new developer support process](https://github.com/spotify/web-api)) to better serve you and other developers.

In this particular case, our content is usually displayed correctly and in some cases multiple versions of the "same" album may appear. For that reason I'm going to close this as <kbd>wontfix</kbd>.

Hope this makes sense. Reach out if you have any other feedback. Cheers 👍
