### ISSUE TITLE
Content Security Policy Error on authorisation via implicit grant flow

### ISSUE THREAD

**Issue by rensftw** [spotify/web-api#588]
Today I faced an issue similar to #350 
Using implicit grant flow, the user is redirected to Spotify authorization page and after the user selects 'Okay' they are immediately redirected to the **Spotify 404 Page** instead of the specified callback (same happens if 'Cancel' is selected).

However in the Safari developer console, two errors appear:
```
Refused to execute a script because its hash, its nonce, or 'unsafe-inline' does not appear in the script-src directive of the Content Security Policy.

Refused to load https://www.google.com/ads/ga-audiences?v=1&aip=1&t=sr&_r=4&tid=UA-5784146-31&cid=369621097.1498228053&jid=1938432370&_v=j56&z=1154408769 because it does not appear in the img-src directive of the Content Security Policy.
```

EDIT: On Chrome Dev Tools there's only one error, which is more descriptive:
```
Refused to load the image 'https://www.google.com/ads/ga-audiences?v=1&aip=1&t=sr&_r=4&tid=UA-5784146-31&cid=207883536.1498490762&jid=595803203&_v=j56&z=93830505' because it violates the following Content Security Policy directive: "img-src 'self' https://d2d1dxiu3v1f2i.cloudfront.net https://i.imgur.com https://d2mv8tnci56s9d.cloudfront.net https://aci.scdn.co https://graph.facebook.com https://fbcdn-profile-a.akamaihd.net https://scontent.xx.fbcdn.net https://www.google-analytics.com https://stats.g.doubleclick.net data: d2d1dxiu3v1f2i.cloudfront.net".
```

Additionally, in the Resources tab of Dev Tools I can see:
<img width="404" alt="screen shot 2017-06-23 at 17 44 43" src="https://user-images.githubusercontent.com/22574186/27491815-bc3e50a6-583b-11e7-82c6-f82e286da8c8.png">
The link inside ```accept.json``` has an access token attached (indicating authorisation was successful) and is fully functional - navigating to that link manually starts the app and everything works as it should, so the problem seems to be that the CSP error prevents it from being triggered.

No such errors appeared during local development, they began happening after I deployed on GitHub Pages (any chance it has to do with GitHub's CSP?)
For reproduction purposes:  [https://rensftw.github.io/ngmusify/](https://rensftw.github.io/ngmusify/)

**Comment by hughrawlinson** [comment]
Hey @rensftw - it looks like your redirect URI is malformed. It's `https:%2Frensftw.github.io%2Fngmusify%2Fsearch`, which converts to `https:/rensftw.github.io/ngmusify/search`; note the missing `/` character after the `:/`. Hope that helps - please re-open this ticket if that doesn't fix the issue.

**Comment by rensftw** [comment]
Yep, that was it. It's all working now 😄 thanks for pointing it out!
