### ISSUE TITLE
Can't connect to service(Spotify OAuth service)?

### ISSUE THREAD

**Issue by Englbach** [spotify/web-api#59]
GET https://accounts.spotify.com/authorize/?client_id=5fe01282e44241328a84e7c5cc169165&response_type=code&redirect_uri=https%3A%2F%2Fexample.com%2Fcallback&scope=user-read-private%20user-read-email&state=34fFs29kd09

String SpotifyUrl = "https://accounts.spotify.com/authorize?client_id="+Uri.EscapeDataString("9ac2b............3")
    + "&response_type=code&redirect_uri="
    + Uri.EscapeDataString("http://localhost:8888/callback")
    +"&scope="+Uri.EscapeDataString("user-read-private user-read-email");
Uri StartUri = new Uri(SpotifyUrl);
Uri EndUri = new Uri("http://localhost:8888/callback");

#if WINDOWS_PHONE_APP
    WebAuthenticationBroker.AuthenticateAndContinue(StartUri, EndUri, null, WebAuthenticationOptions.None);
#else
    WebAuthenticationResult WebAuthenticationResult = 
        await WebAuthenticationBroker.AuthenticateAsync(
                    WebAuthenticationOptions.None,
                    StartUri,
                    EndUri);
if (WebAuthenticationResult.ResponseStatus == WebAuthenticationStatus.Success)
{
    OutputToken(WebAuthenticationResult.ResponseData.ToString());
    await GetSpotifyUserNameAsync(WebAuthenticationResult.ResponseData.ToString());
}

The issue is "Can't connect to the service", but I was trying to connect to facebook service then it ok?

![](http://i.stack.imgur.com/o01KB.png)

**Comment by JMPerez** [comment]
@Englbach It would be useful if you could output the URL that is being requested, as well as the response and status code you get back. Try to print out the contents of `WebAuthenticationResult.ResponseData` and `WebAuthenticationResult.ResponseStatus`.

**Comment by Englbach** [comment]
@JMPerez Hi, Debuger run to at here: WebAuthenticationResult WebAuthenticationResult = await WebAuthenticationBroker.AuthenticateAsync(
                                                        WebAuthenticationOptions.None,
                                                        StartUri,
                                                        EndUri);
and stop => navigation to 
  else if (WebAuthenticationResult.ResponseStatus == WebAuthenticationStatus.ErrorHttp)
                {
                    OutputToken("HTTP Error returned by AuthenticateAsync() : " + WebAuthenticationResult.ResponseErrorDetail.ToString());
                }
That meaning is WebAuthenticationResult.ResponseStatus is fails

**Comment by JMPerez** [comment]
@Englbach still, your response doesn't include what the final requested URL looks like, the response data for the request nor the status code is.

I'm trying to understand what `WebAuthenticationBroker` is doing behind the scenes. We can help wtih issues with the Web API itself, but not with questions about how to make a proper request with a specific library/programming language, since the possible combinations are too broad.

If you are still having issues, you can have a look at the wrappers we list on [our developer site](https://developer.spotify.com/web-api/code-examples/#wrappers). The two ones for .NET provide methods for carrying out the authentication flow.

Also, StackOverflow might be a good alternative to find support for your use case.

**Comment by Englbach** [comment]
I had try "cyperghost" to changed IP->IP USA but still not ok

**Comment by JMPerez** [comment]
@Englbach changing the IP isn't going to solve it. I insist that the problem has to do with the request you are making, but as far as we don't know what the request and its response is, we can't solve this.

**Comment by JMPerez** [comment]
@Englbach I'm closing this issue, since there doesn't seem to be a problem with the Web API. I suggest you have a look at those wrappers or ask on StackOverflow for programming questions about the way you are making the request.
