### ISSUE TITLE
sorting playlist search-results

### ISSUE THREAD

**Issue by Psychnix** [spotify/web-api#591]
Topic: sorting playlist search-results

Request on the 29.06.2017

I am only placing this Request here because otherwise noone of importance might pick it up.

Request:
            Right now there is no option to order your search-results by anything at all. Wouldn't it make sense 
            to be able to do the following:  Search for "Fun" in Spotify, select playlists and then be able to sort 
            the results by followers, Abc, time of creation, name of creator,..., etc.

            Right now the user feels somewhat powerless and overwhelmed by mass of unsorted playlists after 
            a search. 
            If this option already exists somewhere it is placed in a very bad spot!

best regards

**Comment by hughrawlinson** [comment]
Hi, it seems like this feature request is for a Spotify client. You can file issues there on [community.spotify.com](community.spotify.com). Please feel free to reopen if I've misunderstood!
