### ISSUE TITLE
"preview_url" field is null even with avaliable markets

### ISSUE THREAD

**Issue by tengfei2015** [spotify/web-api#592]
Issue found on June 5th 2017.

#### Endpoint(s):
* `https://api.spotify.com/v1/albums/{id}/tracks`

#### Scope(s):
* None

#### Steps to reproduce:
1. Open the API Console
2. Call the `Get an Album's Tracks` endpoint with `Spotify Album ID` `6STfVA1VbC6riYmS1tEma5`

#### Expected behaviour:
It should have "preview_url" in each item object.

#### Actual behaviour:
All "preview_url" field is null even with avaliable markets

It works before, don't know why "preview_url" is null now.

**Comment by diazh** [comment]
I have the same problem.
In the JSON i can see 33 available markets, included my market area, but preview_url is null.

![captura de pantalla 2017-07-05 a las 12 48 29 p m](https://user-images.githubusercontent.com/12104685/27882145-4c29a4e8-6180-11e7-8194-778a6d0ef0a5.png)

**Comment by hughrawlinson** [comment]
Yep - as stated in the documentation, preview URL can be null for a variety of reasons (even if you use a market where the track is available)

**Comment by stephaniegonzalez** [comment]
@hughrawlinson Can you please attach the documentation where this is defined? Thanks!

**Comment by stephaniegonzalez** [comment]
Hi @hughrawlinson I understand it could be a number of reasons the preview player is retuning a null value, but do you have a specific reason for this ID?
