### ISSUE TITLE
API seems sometimes returns wrong artist list of albums

### ISSUE THREAD

**Issue by stolendog** [spotify/web-api#593]
I was running script  few times per hour which checks for artist albums list. 

Issue found on June 29th 2017.

#### Endpoint(s):
* `GET /v1/artists/{artist_id}/albums`

#### Scope(s):
* None 

#### Steps to reproduce:
My script runs constantly few times per hour.

1. Open the API Console
2. Call the `Get an Artist's Albums` endpoint with `artist_id` `3WorcXKb2PFutcaYEFjBWq `

#### Expected behaviour:
Script always expect get correct artist's albums list.

#### Actual behaviour:
My script got albums list with wrong album added `Album_id` `53IBDUGBYywaPlVzcDoeUF`. This album was removed and added again to artist's `3WorcXKb2PFutcaYEFjBWq` albums list few times. I can see it from the log of my script. Now it seems album removed from the wrong artist albums list and added to right artist album list `0LFN3fLwkYmQdNc7jfeum4`

**Comment by arirawr** [comment]
Hi @stolendog - as you've mentioned in your comment, this appears to be fixed now. If you encounter any further issues, please let us know!
