### ISSUE TITLE
Can we integrate Spotify API in WPF application, if can than please share a sample code to play full length tracks?

### ISSUE THREAD

**Issue by RAMANJANEYULUDIDDALA** [spotify/web-api#594]
Issue found on February 19th 2015.

#### Endpoint(s):
* `GET /v1/users/{user_id}`

#### Scope(s):
* None (application is not using authentication)

#### Steps to reproduce:
1. Open the API Console
2. Call the `get-users-profile` endpoint with `user_id` `%5E`

#### Expected behaviour:
A public user object as described on `https://developer.spotify.com/web-api/object-model/#user-object-public`.

#### Actual behaviour:
500 Server Error (consistently)

**Comment by jscholes** [comment]
There is currently no way to integrate full-length playback of tracks into a WPF application on desktop or mobile.  Previously you could use libspotify, but it has now been deprecated and no new appkeys are being issued.

**Comment by hughrawlinson** [comment]
Hi, as usual @jscholes is right - there's no way to do full-length track playback at the moment in WPF. You could use the [Spotify Connect endpoints](https://developer.spotify.com/web-api/web-api-connect-endpoint-reference/) to control an existing Spotify player for a Spotify Premium user though.
