### ISSUE TITLE
Seek Endpoint returning '400 "Required parameter position_ms missing"

### ISSUE THREAD

**Issue by tobyonono** [spotify/web-api#595]
Seek Endpoint returning '400 "Required parameter position_ms missing"

Endpoint(s):
PUT https://api.spotify.com/v1/me/player/seek

Scope(s):
* None (application is not using authentication)

Steps to reproduce:
Works in Console and other api calls to player work with this format

This is what I'm doing in the code

`$.ajax({
                                    url: 'https://api.spotify.com/v1/me/player/seek',
                                    contentType: 'application/json',
                                    type: 'PUT',
                                    dataType: 'json',
                                    headers: {
                                      'Authorization': 'Bearer ' + access_token
                                    },
                                    data: JSON.stringify({'position_ms':progress, "device_id":device}),
                                    success: function(response) {
                                    }
                                  });`

Expected behaviour:
Seek to the selected position after I call it

Actual behaviour:

'400 "Required parameter position_ms missing"

**Comment by seahorsepip** [comment]
There's no need to stringify the data supplied in the ajax request in jQuery.

Did you try the following:

```
$.ajax({
	url: 'https://api.spotify.com/v1/me/player/seek',
	contentType: 'application/json', 
	type: 'PUT', 
	dataType: 'json', 
	headers: { 
		'Authorization': 'Bearer ' + access_token
	},
	data: {
		position_ms: progress,
		device_id: device
	}, 
	success: function(response) {
		//Success
	} 
});
```

**Comment by hughrawlinson** [comment]
Looks like @seahorsepip's answer was right, so I'll close this - please feel free to reopen if you have more questions!
