### ISSUE TITLE
400 "error": "invalid_client" Client Credentials Flow 

### ISSUE THREAD

**Issue by vosamoilenko** [spotify/web-api#597]
I tried everything, an application on IOS works fine with the same client id and secret. I have checked before sending a request, they are 100% similar, anyway, I got an error: invalid client.  

   ```
const CLIENT_ID = "yyyyyyyyyyyyyyyyyyy";
const CLIENT_SECRET = "xxxxxxxxxxxxxxxxxxxxxxx";
let url = "https://accounts.spotify.com/api/token";
let oAuthOptions = {
            contentType: 'application/json',
            dataType: 'json',
            headers: {
               Authorization : 'Basic ' + btoa(CLIENT_ID+':'+CLIENT_SECRET)
            },
            grant_type: 'client_credentials',
            json : true
     };
    $.post(url,oAuthOptions, function(data, status){
             console.log('got answer');
        });

```

**Comment by hughrawlinson** [comment]
Hi - you shouldn't use Client Credentials on iOS. It requires the Client Secret, which should be stored securely. iOS binaries shouldn't include them. I'd recommend doing Client Credentials serverside and calling your server from your app 😄. This also has a variety of other benefits, including enabling you to change your client ID or how you're calling Spotify without a whole new release on the App Store. Make sure to regenerate your client secret if you suspect that it has leaked!

**Comment by mattbarker016** [comment]
This is not a solution. Servers aren't just lying around for free.

**Comment by ashishg656** [comment]
Is there any solution to call this api from client side? I dont want to make a server for this request, so can I use this api from my client side application??? @hughrawlinson @mattbarker016 @vosamoilenko

**Comment by mattbarker016** [comment]
@ashishg656 There really doesn't seem to be a way; I ended up making a quick heroku instance. I tried everything: using the pod, making HTTP requests in the app.
