### ISSUE TITLE
Start/Resume a User's Playback not playing context_uri

### ISSUE THREAD

**Issue by EnyxRB** [spotify/web-api#598]
Hey, I'm using the request module to call from app.js on node.js, I've managed to make it play once the player has been paused, however it won't load the context_uri or from the uris array. I've tried every type of formatting for the json as possible and can't get it to play a chosen track or album. Here's my code:

`request({
		method: 'PUT',  
		uri: 'https://api.spotify.com/v1/me/player/play',  
		headers:{
			Authorization: 'Bearer ' + access_token
		},
		data:{
			"context_uri": "spotify:album:5ht7ItJgpBH7W6vJ5BqpPr"
		}
	}, function (error, response, body) {
		console.log(body);
	});		
`

Apologies for the paste having no indentation, not sure how to stop that?

P.s. I get no errors when sending the request, it just doesn't load the chosen context, instead plays the currently chosen song on the player, so it's not reading the context_uri.

**Comment by hughrawlinson** [comment]
Hi @EnyxRB,

Are you sure that the context URI you're using is available in your market? Here are the markets the context is available in:

```
[
  "AD",
  "AR",
  "AT",
  "AU",
  "BE",
  "BG",
  "BO",
  "BR",
  "CH",
  "CL",
  "CO",
  "CR",
  "CY",
  "CZ",
  "DE",
  "DK",
  "DO",
  "EC",
  "EE",
  "ES",
  "FI",
  "FR",
  "GB",
  "GR",
  "GT",
  "HK",
  "HN",
  "HU",
  "ID",
  "IE",
  "IS",
  "IT",
  "JP",
  "LI",
  "LT",
  "LU",
  "LV",
  "MC",
  "MT",
  "MY",
  "NI",
  "NL",
  "NO",
  "NZ",
  "PA",
  "PE",
  "PH",
  "PL",
  "PT",
  "PY",
  "SE",
  "SG",
  "SK",
  "SV",
  "TR",
  "TW",
  "UY"
]
```

Note the exclusion of `CA`, `US`, and `MX`. If this was the issue, you should have a look at [this guide](https://developer.spotify.com/web-api/track-relinking-guide/) that details how content is linked between different markets, and mark this issue as closed. 😄 

By the way, [here](https://help.github.com/articles/creating-and-highlighting-code-blocks/) is how to do multiline indented code blocks in GitHub flavoured Markdown.

**Comment by arirawr** [comment]
As this hasn't been updated in a while, I'm going to go ahead and close this issue. Please reopen if you are still seeing this behaviour.
