### ISSUE TITLE
Add end point for label search

### ISSUE THREAD

**Issue by s0l4r** [spotify/web-api#601]
I can't seem to find any way to search record labels through the Web API. Is it possible to add this? Also I cannot see that labels are attached to the album object, 

https://developer.spotify.com/web-api/object-model/#album-object-full

There is a copyright object, but is this the same as doing search on label:"XXX" in the desktop client?

The current only valid search types in the API are: album, artist, playlist, and track.

This feature would be good if you want to follow new releases on a list of labels you are interested in.

**Comment by arirawr** [comment]
Hi @s0l4r!

There is a `label` field on the full album object, which you can find [here](https://developer.spotify.com/web-api/object-model/#album-object-full) (and check out a full album response with a label [here](https://developer.spotify.com/web-api/console/get-album/?id=4rG0MhkU6UojACJxkMHIXB)).

If you do a search, you can put `label:yourquery` as your query and it will search albums with that label. I've made an example here querying "Mr.305", which is in the label field for the album example above: [https://developer.spotify.com/web-api/console/get-search-item/?q=label%3Amr.305&type=album](https://developer.spotify.com/web-api/console/get-search-item/?q=label%3Amr.305&type=album)

You can verify that the search results for "mr.305" and "label:mr.305" are indeed different.

I hope this helps with your use case!
