### ISSUE TITLE
Inconsistent Encoding on Available Genre Seeds (UTF8 vs utf-8)

### ISSUE THREAD

**Issue by 0xNF** [spotify/web-api#606]
Issue found on July 9th 2017.

#### Endpoint(s):
* `GET https://api.spotify.com/v1/recommendations/available-genre-seeds`

#### Expected behaviour:
Content should be encoded with `charset=utf-8`

#### Actual behaviour:
Content is encoded with `charset=UTF8`
This mislabeled encoding causes .NET JSON parsers to crash.

**Comment by arirawr** [comment]
@0xNF This should now be fixed. Happy hacking!
