### ISSUE TITLE
DELETE /v1/users/{user_id}/playlists/{playlist_id}/tracks does not delete local tracks

### ISSUE THREAD

**Issue by PaulGreefhorst** [spotify/web-api#612]
Issue found on july 16, 2017
#### Endpoint(s):
* DELETE /v1/users/{user_id}/playlists/{playlist_id}/tracks 

#### Scope(s):
* playlist-modify-public playlist-modify-private

#### Steps to reproduce:
1. Open the API Console
DELETE /v1/users/xxxx/playlists/xxxx/tracks HTTP/1.1
Host: api.spotify.com
Content-Length: 74
Accept-Encoding: gzip, deflate, compress
Accept: application/json
User-Agent: Spotify API Console v0.1
Content-Type: application/json
Authorization: Bearer BQBFizTPwuZg7lqJWwT8kSRtiDr56GZLjpP7j9kfY7RFqPvObvhVX7-hC1FjzgdFAKjv12ibEGq1r2CMWiZpMShBygyynHmP2r1-b8gxZOTEoaIoYBNlBZ_WomsTJIATWYP_fTK6gGo9353yNiplaMF-HkICrXbLx1fCOSNPYqcLvbl0hvE2fYxndjUsrc3Si3KM9T-4u0W1F93vzKfY_z02HbZXUaQq1DLNp6Q

{"tracks": [{"uri": "spotify:local:Led Zepplin::Stairway to Heaven:482"}]}

uri is obtained from v1/users/xxx/playlists/xxx/tracks
->items->track->uri

#### Expected behaviour:
Expecting to get a response with a snapshot id

#### Actual behaviour:
I do get the expected result when delete a track with an uri that starts with spotify:track...
but when the uri starts with spotifu:local:... a bad request is returned:

HTTP/1.1 400 Bad Request
Access-Control-Allow-Headers: Accept, Authorization, Origin, Content-Type
Content-Encoding: gzip
Transfer-Encoding: chunked
Access-Control-Allow-Credentials: true
Access-Control-Max-Age: 604800
Keep-Alive: timeout=600
Server: nginx
Connection: keep-alive
Cache-Control: private, max-age=0
Date: Sun, 16 Jul 2017 09:12:24 GMT
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, POST, OPTIONS, PUT, DELETE
Content-Type: application/json; charset=utf-8

{
  "error" : {
    "status" : 400,
    "message" : "JSON body contains an invalid track uri: spotify:local:Led Zepplin::Stairway to Heaven:482"
  }
}

**Comment by seahorsepip** [comment]
I'm assuming this isn't possible by design since you can't add local tracks using the api either:
https://developer.spotify.com/web-api/add-tracks-to-playlist/

```
Note that local tracks can’t be added.
```

**Comment by arirawr** [comment]
Hi @PaulGreefhorst -

Please see our "Local Files in Spotify Playlists" guide here: https://developer.spotify.com/web-api/local-files-spotify-playlists/

Specifically the following section:
> Limitations
>It is not currently possible to add local files to playlists using the Web API, but they can be reordered or removed. The latter should be done by specifying the index and snapshot_id, and NOT the URI of the track.

So, you need to use index and snapshot_id instead of the track URI.

**Comment by nitricware** [comment]
I'm running into a similar problem, @arirawr 
I'm sending a delete request to the endpoint with this body:
```json
{
    "tracks": [
        {
            "uri":"spotify:local:Paul+Simon:Negotiations+and+Love+Songs+1971-1986:50+Ways+To+Leave+Your+Lover:211",
            "positions":["1"]
        },
        {
            "uri":"spotify:local:Tommy+Tutone:Tommy+Tutone+2:867-5309+%2F+Jenny:227",
            "positions":["2"]
        }
        ],
    "snapshot_id":"uy33tAVbyXDKC+thiohlZbD07f3QEDO46TdhG6r5HHXEArRLtLJd\/xo5yuNfiXjq"
}
```
Still, the API throws an error 400. Also, removing the uri as a whole didn't work, using index instead of positions didn't work either.

What must the body look like to be able to delete local files in playlists?

**Comment by sippsolutions** [comment]
I have the same issue.

**Comment by dersimn** [comment]
Same
