### ISSUE TITLE
Get Playlist Returns Hidden Songs

### ISSUE THREAD

**Issue by sclander** [spotify/web-api#614]
Issue found on July 18th 2017.

#### Endpoint(s):
* `GET /v1/users/{user_id}/playlists/{playlist_id}/tracks`

#### Scope(s):
* playlist-modify-public

#### Steps to reproduce:
Hard to reproduce as I don't know exactly what is causing it.

When using the above endpoint, the list of tracks returned includes tracks I don't expect to be there. These are tracks that were once part of the playlist, but have been removed because they are no longer available on Spotify, or have been moved to a different album. These don't show up in my playlist when viewing in the app, but when I use the API they still come up. Because they don't show up in the app, I'm not sure how to delete them

#### Expected behaviour:
The tracks from the API should match the tracks I can see in the app

#### Actual behaviour:
Hidden tracks appear in results

**Comment by arirawr** [comment]
Hi @sclander - could you provide an example of a playlist for which this occurs?

**Comment by sclander** [comment]
Sure, my playlist 'ARC' is one example (playlistId: 71db6NAG2S38K7UR1VQ4Jl) When I originally made the playlist, it contained the songs Monday Paracetamol by Ulrich Schanauss, and Blue Clouds by Vessels (I can get the exact track IDs if those would be useful). Now, when I view my playlist in the app, it does not contain these tracks, but when I grab all of the tracks from the playlist API, both of those show up.

**Comment by sclander** [comment]
Monday Paracetamol ( id: 126wbVI2n3qrwWznyNZx4s)
Blue Clouds (id: 3GjcxKLZACcuw0HypmQH4C)

**Comment by sclander** [comment]
No, I did not realize that was a setting. This fixed the issue. Thanks!

**Comment by arirawr** [comment]
Great - glad I could help! :)
