### ISSUE TITLE
Can '/api.spotify.com/v1/me/player' take an optional deviceId parameter

### ISSUE THREAD

**Issue by mavvari** [spotify/web-api#619]
Issue found on July 19th 2017.

#### Endpoint(s):
* `GET https://api.spotify.com/v1/me/player`

#### Scope(s):
* None (application is not using authentication)

#### Steps to reproduce:
1. Can this API take an optional request parameter deviceId ? That way we get the current playback state for a specific device.

**Comment by arirawr** [comment]
Have you tried the Devices endpoint [here](https://developer.spotify.com/web-api/get-a-users-available-devices/)? That will get you a list of all devices and information about them.

**Comment by hughrawlinson** [comment]
Hi @mavvari - multiple devices for a single account should be sharing the same playback state - users shouldn't be able to play different things on different devices at the same time. I'd recommend looking at the current playback state, which is global, and if you encounter a situation where you find that the playback state differs between devices, please report that as a bug.
