### ISSUE TITLE
Spotify recommendations API returns no tracks if target_duration_ms supplied

### ISSUE THREAD

**Issue by inter8ection** [spotify/web-api#620]
Issue found on February 22nd July 2017.

#### Endpoint(s):
* `GET https://api.spotify.com/v1/recommendations`

#### Scope(s):
* None (only a valid token required)

#### Steps to reproduce:
1. Open the API Console
2. Call the endpoint, example without target_duration_ms, which works:
curl -X GET "https://api.spotify.com/v1/recommendations?market=GB&seed_tracks=4esbnzta4tTotyIif95mfC,1zB9XtOjNXfEitXFMq1irx,2OlDaPUuYqdCLQncM0LtBu&limit=20&target_valence=0.71&target_popularity=69&target_danceability=0.71" -H "Accept: application/json" -H "Authorization: Bearer yourtokenhere"

3. Call the endpoint with target_duration_ms supplied, which doesn't work:
curl -X GET "https://api.spotify.com/v1/recommendations?target_duration_ms=180000&market=GB&seed_tracks=4esbnzta4tTotyIif95mfC,1zB9XtOjNXfEitXFMq1irx,2OlDaPUuYqdCLQncM0LtBu&limit=20&target_valence=0.71&target_popularity=69&target_danceability=0.71" -H "Accept: application/json" -H "Authorization: Bearer yourtokenhere"

#### Expected behaviour:
An array of tracks as described on `https://developer.spotify.com/web-api/get-recommendations/`.

#### Actual behaviour:
An empty tracks arrays, and an afterFilteringSize: 0 which may imply it's incorrectly filtering based on min_/max_ parameters even when only target_ parameters supplied.

**Comment by arirawr** [comment]
I've been able to reproduce this and am looking into it. Thanks for the report!

**Comment by arirawr** [comment]
Hi @inter8ection - I'm happy to say that this issue has been fixed! Thank you for the report, and happy hacking! 🎉

**Comment by inter8ection** [comment]
Much obliged! I'll report anything else I find :)
