### ISSUE TITLE
Local files scanning and importation into playlist

### ISSUE THREAD

**Issue by gman5500** [spotify/web-api#622]
Spotify automatically scans 'Local Files' and added directories for new music. I suggest a tool to automatically import the new offline files to a playlist.
Possible endpoint query: /v1/users/{user_id}/local
Usecase: I listen to a lot of foreign music spotify doesn't have. Its helpful to a broad region of people.

**Comment by jscholes** [comment]
The Spotify team have [stated on previous occasions](https://github.com/spotify/web-api/issues/510#issuecomment-298660528) that support for local files in the Web API is not planned.

**Comment by bih** [comment]
Hi @gman5500,

As mentioned, we have no plans to add local files to the Web API in the foreseeable future. That's not to say it's not something we won't add at some point to be clear.

Hope that helps!

**Comment by jardakotesovec** [comment]
Hi @bih,
I also miss this feature very much - to be able add local track to the playlist. Is there place where I could upvote it to give it higher priority?

Unfortunately not all songs are on spotify and local files support is super handy, really did not expect that api refuse that :-(. Wondering why its excluded.

Thanks for your time.
Jarda

**Comment by schettino** [comment]
As there are many platforms (web, nodejs, react-native) that can make use of the web api, I think this an important feature that may have been left behind. Please, let us know if something change about it!

**Comment by richjhart** [comment]
How do we bump this up? As far as I'm concerned, the API isn't complete until this is supported.

**Comment by ddallen96** [comment]
Would also love a way to do this, every other step can be scripted
