### ISSUE TITLE
Add context to saved tracks object

### ISSUE THREAD

**Issue by sastraxi** [spotify/web-api#625]
This feature request is for adding a per-track `context` object to each saved track returned by [GET /v1/me/tracks](https://developer.spotify.com/web-api/get-users-saved-tracks/).

This [context object](https://developer.spotify.com/web-api/object-model/#context-object) could be the same as that returned per-track by [/v1/me/player/recently-played](https://developer.spotify.com/web-api/web-api-personalization-endpoints/get-recently-played/).

#### Use Case
We'd like to provide our users with regularly-updating personal playlists and track which of songs we've suggested to them they've saved. We can do this by combining the recently-played track listing's context with the liked tracks already, but this has the possibility for false positives.

#### Additional Information
This would also be great for a personal project--I'd like to have a playlist full of all the songs I've ever liked from Discover Weekly. Currently, I save *and* add tracks to this playlist on the Spotify UI, but it would be great to be able to write a quick scheduled lambda to do this automatically, and I think I'd need this API to make sure the list was correct.

**Comment by bih** [comment]
Hi @sastraxi,

Thanks for reaching out. This sounds like a great feature request and we'll take it into consideration 👍

**Comment by hughrawlinson** [comment]
Hi @sastraxi - I'm not sure what you'd want a context object to represent in this response. What would it represent exactly? If you just need to know the artist or album of the track, that's in the response already.

**Comment by sastraxi** [comment]
@hughrawlinson the `context` object would represent the context in which the given track was saved, just like it represents in the `recently-played` endpoint.

For example, if I saved a track that I was listening to in my Discover Weekly playlist, the context for that track in `/v1/me/tracks` would be something like

```
"context": {
  "uri": "spotify:playlist:37i9dQZEVXcNk3YFTlmZim",
  "external_urls": {
    "spotify": "https://open.spotify.com/user/spotify/playlist/37i9dQZEVXcNk3YFTlmZim" 
  },
  "href": "https://api.spotify.com/v1/users/sastraxi/playlists/37i9dQZEVXcNk3YFTlmZim"
  "type": "playlist"
},
```

**Comment by arirawr** [comment]
Hi @sastraxi - thanks for the suggestion. We've reviewed this suggestion, and will not be able to implement it. We don't have data about the context a track was saved from, so we can't expose an API for it.
