### ISSUE TITLE
/v1/me/player/currently-playing returns out-of-date information

### ISSUE THREAD

**Issue by pigi5** [spotify/web-api#626]
Same issue as the closed issue found here: https://github.com/spotify/web-api/issues/499?_pjax=%23js-repo-pjax-container

Issue found on July 27th 2017.

#### Endpoint(s):
* `GET /v1/me/player/currently-playing`
* `GET /v1/me/player`

#### Scope(s):
* `user-read-currently-playing` or `user-read-playback-state` (depending on endpoint)

#### Steps to reproduce:
1. Start playing a track in the Spotify client.
2. Make an authenticated call with the correct scopes to one of the above endpoints (for example, using the API Console)
3. Check the response to see if it matches the song currently playing in the Spotify client.

#### Expected behaviour:
The response contains accurate information about what is currently playing in the Spotify client.

#### Actual behaviour:
The response contains out-of-date information. (Mine is returning information from ~24 hours ago). The information has not changed as long as I've tried it (I tried multiple times, several hours apart). My Spotify user is pigi5.

Update: My computer restarted over night. When Spotify opened, it opened on the song that the API Console was returning as my currently playing song when I had tested it. I think what happened was that I switched playlists, and the last playing song from the previous playlist was stuck as my "currently playing song".

It might be helpful to know that the playlist I switched to (that wasn't being recognized) was a newly created playlist. My requests now work as intended, so it looks like I won't be having the issue anymore, but just know that it still exists.

**Comment by bih** [comment]
Hi @pigi5,

Thanks for submitting your issue. As I'm not able to replicate your issue and I saw you commented on #499, I'm going to close this as it is a duplicate. Let us know if you have any other questions 👍
