### ISSUE TITLE
Interpreting Spotify's definition of what is a streaming SDA.

### ISSUE THREAD

**Issue by omerduv** [spotify/web-api#628]
I'm writing a desktop application (for macOS) that's using the web API to control song playback.
I'm having trouble interpreting Spotify's definition of what is a streaming SDA.

I'm aware that Android and iOS SDKs have true streaming capabilities. The web API however only allows 3rd party developers to control playback through the '**player**' endpoint.

If my application only uses the player endpoint of the web API, does it fall into the category of a streaming SDA?

The chart [here](https://developer.spotify.com/wp-content/uploads/2015/01/answers-to-common-questions-about-our-terms-of-use-for-developer-tools.pdf) asks whether the app itself streams full-length tracks. As I see it, using the player endpoint of the web API isn't like the app itself streaming tracks.

Is that assumption correct? Is my application a non-streaming SDA?

Thanks!

**Comment by jscholes** [comment]
My interpretation is that sending requests to the Web API, whether to control a Spotify player or to provide song preview clips, does not count as "streaming".  An application is only classed as a "Streaming SDA" if it directly handles Spotify full track audio data and plays it independently.

**Comment by seahorsepip** [comment]
I agree that it doesn't sound sound like a streaming SDA since you're simple using a remote and not streaming anything.

**Comment by hughrawlinson** [comment]
As this is a technical forum, we can't comment on legal matters surrounding the use of the platform. Please seek the advice of a legal expert, who will be able to help much more than I.
