### ISSUE TITLE
Get current queue

### ISSUE THREAD

**Issue by dreszczyk** [spotify/web-api#629]
Issue found on 30.07.2017

#### Endpoint(s):
* `none`

#### Steps to reproduce:
1. Open the API Documentation
2. There is no info about how to get current player queue and how to alter it.

![image](https://user-images.githubusercontent.com/5095527/28754008-275f9d40-753d-11e7-9c1c-145e71ca8ea4.png)

**Comment by bih** [comment]
Hey @dreszczyk,

Thanks for your feedback. We don't currently have an endpoint for retrieving the current player queue, and the feature request has already been suggested previously in #462. Feel free to show your support on that issue 🙂

Cheers!
