### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by maxiedaniels** [spotify/web-api#634]
I didn't get this in the past, but recently I'm seeing this pop up a ton...

An example:
Endpoint - https://api.spotify.com/v1/search
Query - 'young'
Item Type - 'playlist'
Limit - '50'
Offset - '10000'

If I set offset to 0, it works and I'm showing 44281 total results. So I should be able to use a 10,000 offset to get 10000-10050..

**Comment by gLarsVegas** [comment]
I have received a lot of those errors in the last days. Im only using recently-played.

**Comment by rmmjohann** [comment]
Same here. An offeet of 10000 and further results in 502 responses

**Comment by hughrawlinson** [comment]
Hi! An offset of >10000 is not supported, [as per documentation](https://beta.developer.spotify.com/documentation/web-api/reference/search/search/).  The API now returns a 404 when `offset` + `limit` >= 10000.
