### ISSUE TITLE
Device Object, is_restricted flag documentation

### ISSUE THREAD

**Issue by apilaszkiewicz** [spotify/web-api#635]
Device Object, is_restricted flag should be better documented

#### Endpoint(s):
* GET https://api.spotify.com/v1/me/player/devices
* POST https://api.spotify.com/v1/me/player/next

#### Steps to reproduce:
1. Get Devices
2. Device to be controlled (Smartphone)
`is_restricted_flag = true`
`POST https://api.spotify.com/v1/me/player/next => 403`
3. close Spotify App, open Spotify App
`POST https://api.spotify.com/v1/me/player/next => 403`
4. update Spotify App
`POST https://api.spotify.com/v1/me/player/next => 403`
5. close Spotify App, open Spotify App
`POST https://api.spotify.com/v1/me/player/next => 403`
6. restart device
`POST https://api.spotify.com/v1/me/player/next => 204`

**Comment by hughrawlinson** [comment]
Hi! We'll take a look at improving the documentation of this flag. The reproduction steps you pointed to seem to indicate a bug, are you still able to reproduce it? If so, please reopen this ticket and we'll take a look
