### ISSUE TITLE
Web API Caching? / Local Web Helper not sending events to server properly

### ISSUE THREAD

**Issue by tance77** [spotify/web-api#636]
Issue found on February 19th 2015.

#### Endpoint(s):
* `GET /v1/me/player`
* `GET /v1/me/player/currently-playing`
* `GET /v1/me/player/play/`
* `GET /v1/me/player/pause/`

#### Scope(s):
* user-read-playback-state
* user-modify-playback-state

#### Steps to reproduce:
1. Make a `GET /v1/me/player` to end point every 10 seconds
2. Make a `GET /v1/me/player/play/` to end point
2. Make a `GET /v1/me/player/pause/` to end point
3. Observe response data from `GET /v1/me/player` response data may not be accurate `is_playing` to be specific.
4. Change songs through the Spotify client.
5. Observe response data from `GET /v1/me/player` response data may not be accurate `duration_ms` may be in accurate. The item itself may be inaccurate or not yet updated.

#### Expected behavior:
An object described [here](https://developer.spotify.com/web-api/get-information-about-the-users-current-playback/) for a successful response with up to date information.

Why is this data sometimes invalid? Is there a caching thing that is happening? If so why is it happening. I should be able to get the current player info at any given moment. 

Please advise.

#### Actual behavior:
A valid response with old data. For example the duration_ms is sometimes wrong or behind the actual player time. It is sometimes ahead of the player time when changing songs. This is very common when the next endpoint is hit. It still thinks its playing the previous song even though the player has moved on to the next track. 

Is the player not firing events to the local web helper??

**Comment by tance77** [comment]
[Screenshot of data being passed bag of the same song.](http://prntscr.com/g4tu0z)

The player has not been touched it was just allowed to to continue playing. I paused it and played it through the API. Then I received the correct time of the progress of the song. The first duration is just nonsense as the song wasn't even near that playback time.

**Comment by tdhooper** [comment]
This might be https://github.com/spotify/web-api/issues/499

**Comment by tance77** [comment]
@tdhooper thx but nobody has acknowledged me on twitter or github

**Comment by hughrawlinson** [comment]
Hey @tance77, thanks for the report. We'll have a look and see if we can diagnose the problem. Is it still occurring for you?

**Comment by tance77** [comment]
@hughrawlinson yes it seems to happen most when I call the next endpoint then get the players status. The song will be the previous song and the time will be the precious time

**Comment by tance77** [comment]
@hughrawlinson here is a video example of what I am describing, to better help you understand the problem. Sorry for poor audio quality I used some cheap free service to record. 

[Video of Problem](https://youtu.be/Q2PdXr1Qe2s)

**Comment by tance77** [comment]
Update after changing my IP address via a VPN I don't seem to have this issue. Is my IP flagged for some reason?

**Comment by tance77** [comment]
@hughrawlinson this issue seems to have gone away. Not sure if you guys did anything.

**Comment by bichotll** [comment]
I actually have a very similar problem to the one you have shown on your videos.
@tance77 any way you have worked around that problem? I don't use any VPN myself.

Even sometimes the time (progress_ms) can just increase for a value higher than the length of the song while Spotify is actually not playing anything.
It would play silence "to the infinity and beyond"...
I have actually experienced this last one before on their web client open.spotify.com

**Comment by tance77** [comment]
My issue seemed to go away. I'm not at all sure why. Sorry @bichotll
