### ISSUE TITLE
Need an api to retrieve current queue and ability to play a track by position

### ISSUE THREAD

**Issue by gahisee** [spotify/web-api#638]
having the ability to play a list of uri's is certainly good but
it would be complete if there was an endpoint to retrieve the current list and
select an offset for play and/or insertion.
similar to Playlist endpoints...

**Comment by hughrawlinson** [comment]
Hi @gahisee - we've received a feature request to provide a queue API, and we'll post any updates in that request: #462. I'll close this request as a duplicate, but please do head over to that issue and add your voice there!
