### ISSUE TITLE
  How to play songs on spotify api?

### ISSUE THREAD

**Issue by Englbach** [spotify/web-api#64]
Now, I just play songs for 30 seconds of songs(this songs is about 3:10) it is not full. I had tried to some ways but it's not success.

How do I play it?

mediaplayer.Source = new Uri("https://api.spotify.com/v1/tracks/4pn0G7yHNfTgRYRWca8gYA",UriKind.RelativeOrAbsolute);
or 
mediaplayer.Source = new Uri(Stream_url.preview_url.ToString(), UriKind.RelativeOrAbsolute);

"href" : "https://api.spotify.com/v1/tracks/4pn0G7yHNfTgRYRWca8gYA",
{
    "href" : "https://api.spotify.com/v1/albums/60mvULtYiNSRmpVvoa3RE4/tracks?offset=0&limit=50",
    "items" : [ {
        "artists" : [ {
            "external_urls" : {
              "spotify" : "https://open.spotify.com/artist/0TnOYISbd1XYRBk9myaseg"
            },
            "href" : "https://api.spotify.com/v1/artists/0TnOYISbd1XYRBk9myaseg",
            "id" : "0TnOYISbd1XYRBk9myaseg",
            "name" : "Pitbull",
            "type" : "artist",
            "uri" : "spotify:artist:0TnOYISbd1XYRBk9myaseg"
        }, {
            "external_urls" : {
                "spotify" : "https://open.spotify.com/artist/2DlGxzQSjYe5N6G9nkYghR"
            },
            "href" : "https://api.spotify.com/v1/artists/2DlGxzQSjYe5N6G9nkYghR",
            "id" : "2DlGxzQSjYe5N6G9nkYghR",
            "name" : "Jennifer Lopez",
            "type" : "artist",
            "uri" : "spotify:artist:2DlGxzQSjYe5N6G9nkYghR"
        }, {
            "external_urls" : {
                "spotify" : "https://open.spotify.com/artist/2OjoIDVPQKT9B7loZbPEfp"
            },
            "href" : "https://api.spotify.com/v1/artists/2OjoIDVPQKT9B7loZbPEfp",
            "id" : "2OjoIDVPQKT9B7loZbPEfp",
            "name" : "Claudia Leitte",
            "type" : "artist",
            "uri" : "spotify:artist:2OjoIDVPQKT9B7loZbPEfp"
        } ],
        "available_markets" : [ "AD", "AR", "AT", "AU", "BG", "BO", "BR", "CA", "CH", "CL", "CO", "CR", "CY", "CZ", "DE", "DK", "DO", "EC", "ES", "FR", "GR", "GT", "HK", "HN", "HU", "IE", "IS", "IT", "LI", "MC", "MT", "MX", "MY", "NI", "NO", "NZ", "PA", "PE", "PH", "PL", "PT", "PY", "RO", "SG", "SI", "SK", "SV", "TR", "TW", "UY" ],
        "disc_number" : 1,
        "duration_ms" : 222466,
        "explicit" : false,
        "external_urls" : {
            "spotify" : "https://open.spotify.com/track/4pn0G7yHNfTgRYRWca8gYA"
        },
        "href" : "https://api.spotify.com/v1/tracks/4pn0G7yHNfTgRYRWca8gYA",
        "id" : "4pn0G7yHNfTgRYRWca8gYA",
        "name" : "We Are One (Ole Ola) [The Official 2014 FIFA World Cup Song]",
        "preview_url" : "https://p.scdn.co/mp3-preview/4e6c03963fa6a6720648540282afc75f4df744c9",
        "track_number" : 1,
        "type" : "track",
        "uri" : "spotify:track:4pn0G7yHNfTgRYRWca8gYA"
    } ],
    "limit" : 50,
    "next" : null,
    "offset" : 0,
    "previous" : null,
    "total" : 1
}

**Comment by JMPerez** [comment]
At the moment you can only play up to 30 seconds using the `preview_url`, and there is no supported way to have access to the full track. Have a look at https://github.com/spotify/web-api/issues/57
