### ISSUE TITLE
timestamp seems to have freezed value

### ISSUE THREAD

**Issue by xabixab** [spotify/web-api#640]
Issue found on August 15th 2017.

#### Endpoint(s):
* `GET /v1/me/player`

#### Scope(s):
* user-read-playback-state

#### Steps to reproduce:
1. Open the API Console
2. Call the `Get Information About The User's Current Playback` endpoint.
3. Call it again a few seconds later.

#### Expected behaviour:
Timestamp value should contain "when data was fetched" as https://developer.spotify.com/web-api/get-information-about-the-users-current-playback/

#### Actual behaviour:
Timestamp value returns a freezed value. It seems to contain the moment when the current song started.

Sorry my bad english level.

**Comment by tance77** [comment]
@xabixab this is related. No solution yet. [636](https://github.com/spotify/web-api/issues/636)

**Comment by sir-dunxalot** [comment]
I am also having this issue. Timestamps from the 'Get Information About The User's Current Playback' endpoint are often 1-3 minutes in the past even though I requested the data within 2 seconds of getting a response.

**Comment by tance77** [comment]
@sir-dunxalot I found the problem went away by itself. It seemed to happen when I accidentally spammed Spotify with a lot of requests. It felt like my IP address got added to a permanent cache list or something.  It went away after I slowed down my requests. Took almost a week.

**Comment by sir-dunxalot** [comment]
@tance77 Alright, thanks for the tip! If you have any info on how much you reduced the requests by (since I'm in development and am not making a ton of requests right now) that would be helpful. Perhaps it's the number of authorization requests that causes this issue to arise?

**Comment by hughrawlinson** [comment]
Hi! Not sure what could've been causing this, I can't reproduce it, but please ping me again if it's still a problem.

**Comment by MiniGod** [comment]
Hi @hughrawlinson. I've had this issue for a month (unknown before that).

`timestamp` appears to be the timestamp of when the state last changed, while `progress_ms` is calculated in the API response from the last known progress (probably at `timestamp`?).

If I pause, play, seek, or skip, the `timestamp` updates. However, the docs state that `timestamp` is a "Unix Millisecond Timestamp when data was fetched". So responding with the `timestamp` of when the state last changed is therefore incorrect.

With the current behaviour, that at least *I* am experiencing, there is no way to accurately tell the exact `progress_ms`.

**Comment by shivpatel** [comment]
@hughrawlinson I'm also experiencing the same situation as @MiniGod. Does not seem to be caching 
 as the timestamp is correct when the next song plays.

Getting things to work in the meantime by setting my own unix timestamp asap when I get the response back from Spotify; works decent so far with 80% accuracy.

**Comment by mileshenrichs** [comment]
@hughrawlinson Jumping in here to add that I'm experiencing the exact same issue described by @MiniGod and @shivpatel.  Since it's behaving the same way for all of us, I'm guessing this is the expected behavior -- the timestamp field reflects the timestamp at which the user last took an action or the song last changed.  If this is the case, it might be worth indicating this with more clarity in the API documentation.
