### ISSUE TITLE
Cannot authorize a user when using Chrome in a frame

### ISSUE THREAD

**Issue by isaacchien** [spotify/web-api#641]
Cannot authorize a user from my Facebook Messenger extension when using Chrome on desktop

NOTE: This issue does not arise when using Safari on desktop nor does it happen when I use Messenger on iOS. 

Issue found on August 14 2017.

#### Endpoint(s):
GET https://accounts.spotify.com/authorize

#### Scope(s):
user-modify-playback-state

#### Steps to reproduce:
Try to authorize Spotify in a Messenger extension or within a frame on Chrome.  

#### Expected behaviour:
Redirect to my redirect_uri.

#### Actual behaviour:
Refused to display 'https://accounts.spotify.com/authorize?...' in a frame because it set 'X-Frame-Options' to 'deny'.

GET https://accounts.spotify.com/authorize?client_id=37... net::ERR_BLOCKED_BY_RESPONSE

**Comment by hughrawlinson** [comment]
Hi @isaacchien - this is currently expected behaviour. Is there a limitation in Facebook Messenger on opening a separate tab?

**Comment by isaacchien** [comment]
Well Facebook Messenger extensions are contained within a frame on facebook.com not a separate tab. I guess I will have to stick with mobile then. Thanks for your help.

**Comment by rifflock** [comment]
Hi @hughrawlinson 
Sorry to jump on asuch an old thread, but I was wondering if there's a specific design choice for having the X-Frame-Options header set to deny. Working with webviews in messenger it's a much better user experience to stay within the messenger ecosystem than to open up a separate tab/window.
I don't suppose there's any possibility of removing that header on this endpoint

**Comment by lcgonsalves** [comment]
Yes, knowing why this choice was made would be helpful, as it is such a jarring UX to have pop-ups going on.
