### ISSUE TITLE
Get Artist Bio

### ISSUE THREAD

**Issue by neundex** [spotify/web-api#643]
Hello is there an option to grab the Artist's about/bio text?

**Comment by hughrawlinson** [comment]
Hi @neundex - artist bio isn't available in the Spotify API. The closest I could find is to use [the musicbio endpoint of the rovi api](http://prod-doc.rovicorp.com/mashery/index.php/Data/name-api/v1.1/name/music-bio). Hope that helps!

**Comment by coloradocolby** [comment]
Also looking for this functionality!

**Comment by Sigularusrex** [comment]
Would also love this

**Comment by surayashivji** [comment]
+1
