### ISSUE TITLE
Getting higher usage rate limits

### ISSUE THREAD

**Issue by gLarsVegas** [spotify/web-api#644]
I built a SDA which offers users to keep track of their spotify playback and additionally scrobble it to last.fm. Due to the high demand for such a service, a lot of users registered. Currently the service has about 400 users. In the last few days the service started hitting the API rate limit. Obviously I have to request the current/recent playback quite often since it can’t be cached for hours or even days like meta data or something similar. I tried to find a reasonable compromise so I request the playback every minute. But due to the climbing amount of users that’s too often for the rate limit.

I was looking for some contact email address when I stumbled upon this issue comment by @thelinmichael https://github.com/spotify/web-api/issues/228#issuecomment-222351118

Can anybody give me more details about how I can apply for such a "special case".

**Comment by jscholes** [comment]
Requesting a users recently played tracks once per minute seems unnecessary for your use case.  A track must be played for at least 30 seconds to be included in the playback history, and you can fetch up to 50 recently played items.  Thus, it follows that you could safely limit your requests to once every 24 minutes per user without missing anything.  With 400 users, this would work out at one request every 3.6 seconds, which I'm sure wouldn't trigger Spotify's rate limiting policy.

Play history objects from the web API include a timestamp which you can pass directly on when scrobbling, so the user's Last.fm profile will reflect accurate listening times.  Of course, you sacrifice a feeling of realtime processing, but when you don't have access to realtime APIs there's not much you can do about it.  Processing data in guaranteed-to-work batch updates is better than an app which stops functioning entirely due to rate limiting, and you can make it clear to your users that updates to their Last.fm profile will not be immediate.

**Comment by gLarsVegas** [comment]
I have already thought about such a solution but 24 minutes are a lot. It would completely remove any "feeling of realtime". That’s why it’s not realy a good solution to me. Spotify offers full lastfm support in the desktop/smartphone clients but not in the connect devices which are used a lot nowadays. I dont see why scrobbling should be either not possible or that poorly supported.

**Comment by andersborgabiro** [comment]
Wouldn't requiring users to log in spread out rate limits equally on users? I'm aware rate limits are lower then, but the total might still be better. Does it make sense?

**Comment by gLarsVegas** [comment]
@andersborgabiro Users do have to login in order to grant the required permissions. That does not change anything about the rate limit / api key.

**Comment by andersborgabiro** [comment]
But don't you get a rate limit per user then, so it scales with amount of users? My app would probably also break if that's not the case.

**Comment by gLarsVegas** [comment]
Im not sure what exactly you mean. My serice only asks for permission once. So I just use the token and refresh it every time I need to make a request.

"Rate limiting is applied on an application basis (based on client id), regardless of how many users are using it."
https://developer.spotify.com/web-api/user-guide/

**Comment by andersborgabiro** [comment]
I probably don't understand your use case.

Anyway, I rewrote my app yesterday to use an absolute minimum of requests, in cases by chunking data to the limit of each request. That also sped up the app significantly. This might not apply in your case.

**Comment by gLarsVegas** [comment]
Your app has an per app limit. It does not matter how many users you have. At least that's what Spotify says.

I cant decrease my requests without making my service less useful and even if I could it wouldnt fix the problem. It would just give me a month and then I would hit the limit again because I get new users every day.

I'll probably just stop working on the project. There is no point in putting effort in a project if it is already doomed to failure. Another service which was doing pretty much the same as mine has already been shut down because of the rate limit. Sorry, but I'm extremely disappointed by Spotify and so are most of the users. If Spotify is not willed to offer simple features, they should at least support developers who do.

**Comment by andersborgabiro** [comment]
In my case it didn't change what the app did, it only decreased the amount of requests, but with many users (and how the rate limit works) I will eventually hit the roof anyway. Registering several apps and switching between them randomly per user might help for a while, but such manual configuration doesn't scale well. Spotify _could_ of course increase this easily, so maybe nagging helps. My app is based on a long-time request from users for a certain feature, so as you say, others are complementing Spotify with features they should already support.

**Comment by gLarsVegas** [comment]
I need to request data for every single user that's why I need so many requests. The only temporary solution would be to request the data only every 10 minutes which would kill the feel of realtime completely. And even that would only fix the problem for a while. Switching app keys is not realy a solution since it's not allowed and it wont work afaik. The limit is bound to your servers ip.

Spotify even says that they are willed to increase the rate limit in "special cases" but there is not even an email address given.

**Comment by andersborgabiro** [comment]
So that means if I make several completely different Spotify server-based apps they would share the same rate limit, unless they would be hosted on different servers. That's bad.

Direct access from a mobile app would use different IP addresses though.

**Comment by gLarsVegas** [comment]
At least afaik. Even if it would work, it would certainly not be allowed.
Mobile apps are not realy a solution in my case since my service has to be online and obviously I dont want to expose my apps key/secret.

**Comment by hughrawlinson** [comment]
Hi! If you have a use case that requires higher rate limits, please get in touch with us via dm on Twitter @SpotifyPlatform. Polling recently played once per minute doesn't strike me as a use case that we're likely to increase rate limits for though to be completely honest. We're aware of feature requests for real time playback notifications, which is likely to be a better solution for you this use case.

**Comment by faustoct** [comment]
@gLarsVegas How did you handle this?

**Comment by aidannnd** [comment]
@gLarsVegas ^ I am interested as well
