### ISSUE TITLE
Spotify redirect doesn't work when accessing a website through the facebook application on an iPhone

### ISSUE THREAD

**Issue by mcpenchel** [spotify/web-api#646]
Issue found on August 21th 2017.

#### Endpoint(s):
* https://accounts.spotify.com/authorize?client_id=

#### Scope(s):
* 'playlist-modify-public', 'playlist-modify-private', 'user-library-modify', 'user-follow-modify', 'user-read-private', 'user-read-birthdate', 'user-read-email'

#### Steps to reproduce:
1. Use an iPhone
2. Go to https://www.facebook.com/NatirutsOficial/posts/1655850931093718 but through the facebook app
3. Click on http://bit.ly/Natiruts360
4. Log in with spotify

#### Expected behaviour:
To work normally, just as it works with android, desktop and normal browsers in iphone (safari, google chrome). It ONLY doesn't work on iphones if you use the facebook app to click in any website that contains the spotify login button.

#### Actual behaviour:
Redirects to a blank page after login.

**Comment by hughrawlinson** [comment]
Hey @mcpenchel - it seems like this issue is the same as #287, so I'll close it as a duplicate and post any updates there. If you feel like I've missed something, please feel free to reopen!
