### ISSUE TITLE
Null Preview URL when one should exist

### ISSUE THREAD

**Issue by bilva-sanaba** [spotify/web-api#647]
Issue found on August 25th 2017.

#### Endpoint(s):
* `GET https://api.spotify.com/v1/tracks/[id]

#### Scope(s):
* None (application is not using authentication)

#### Steps to reproduce:
1. With JavaScript and jQuery:
```
    $.ajax({
        url: "https://api.spotify.com/v1/tracks/4xkOaSrkexMciUUogZKVTS?market=US",
        headers: {
          'Authorization': 'Bearer ' + param.Token,
          'Accept': 'application/json'
        },
        success: function(response) {
          console.log(response);
          console.log(param.Token)
        }
      });
```
2. Do the same in the Web API console for Get Track using:

ID: 4xkOaSrkexMciUUogZKVTS
Market: US
OAuth: same token from console.log(param.Token)

#### Expected behaviour:
Both the Web API console and the Javascript ajax request should return a JSON object with the same preview_url. 

#### Actual behaviour:
Web API preview_url : "https://p.scdn.co/mp3-preview/55cc8b3138a053364de050e06855de76b1189102?cid=f46a5b9d4e114fa8ac0aedbc4fd9f2b8"
ajax preview_url: null

(All other fields are the same between both)

Why does the Web API Console return the correct preview_url while doing the same using ajax does not?

**Comment by tance77** [comment]
I can't reproduce this error. 

[Code Screenshot and JSON Response](http://prntscr.com/gctpxj)
