### ISSUE TITLE
List of Scopes documentation is missing scope user-read-recently-played

### ISSUE THREAD

**Issue by finchmeister** [spotify/web-api#649]
The [documentation for scopes](https://developer.spotify.com/web-api/using-scopes) is missing the scope `user-read-recently-played`. I found it on the endpoint docs <https://developer.spotify.com/web-api/web-api-personalization-endpoints/get-recently-played/> but it would be good to include it in the main list.

**Comment by arirawr** [comment]
Thanks for reporting @finchmeister - this has been updated in the documentation.
