### ISSUE TITLE
Cannot retrieve an artist's top tracks

### ISSUE THREAD

**Issue by greencoppercompany** [spotify/web-api#650]
Issue found on August 28th 2017.

#### Endpoint(s):
* `GET /v1/artists/{id}/top-tracks`

#### Steps to reproduce:
1. Open the API Console: https://developer.spotify.com/web-api/console/get-artist-top-tracks/#complete
2. Try it out with any artist's ID (sample, ...)

#### Expected behaviour:
Tracks array with tracks in it.

#### Actual behaviour:
Empty array.

**Comment by greencoppercompany** [comment]
The issue doesn't occur when we precise 'CA' for the country instead of 'US'

**Comment by ehrmann** [comment]
As a workaround, if you're making this request from the backend, you can use the access token from the [client credentials flow](https://developer.spotify.com/web-api/authorization-guide/#client-credentials-flow) to request an artist's top tracks for any market.

When using a user access token, top tracks are only returned when the country parameter matches the user's country.

**Comment by hughrawlinson** [comment]
Thanks for reporting this issue @greencoppercompany - we've found the issue and we're working on resolving it!

**Comment by arirawr** [comment]
This should be resolved. Please reopen if you see this happening again!
