### ISSUE TITLE
Get User's Top Artists and Tracks API Response doesn't update for several days

### ISSUE THREAD

**Issue by bepbrasil** [spotify/web-api#651]
Issue found on August 27th 2017.

#### Endpoint(s):
* `GET /v1/me/top/artists`

#### Scope(s):
* user-top-read
--

#### Steps to reproduce:
1. Open the API Console
2. Call the 'get users top artists and tracks' endpoint with time range "short_term" limit "50" and token
3. The response is being return, but it's the same response for several days.

#### Expected behavior:
The response should update at least once a day as the user is constantly listing different artists. 

#### Actual behaviour:
The response is not updating for days.

**Comment by BloodShura** [comment]
I think the data is only updated ~term days~ after it was calculated. So, for example, *short term* means *4 weeks*, then this data will only be updated 28 days after it was last updated.

Can't help but say that, unfortunately, I think this is intentional.

**Comment by hughrawlinson** [comment]
Hey, it looks like this data is having a few issues at the moment - the data is _typically_ updated once a day, so it should definitely have updated by now. We're looking into it, and we'll update this ticket once we know more.

**Comment by Andreilys** [comment]
Any updates on this? I've been getting the same tracks/artists returned for the past couple of days just wondering what the refresh rate is (I'm currently pulling artists/tracks from the short term)

**Comment by hughrawlinson** [comment]
This should be fixed now. If you're still seeing the issue, please feel free to reopen! :)
