### ISSUE TITLE
Custom Playlist image height and width show null

### ISSUE THREAD

**Issue by alex011235** [spotify/web-api#652]
Issue found on 30 August 2017

#### Endpoint(s):
* `/v1/users/{user_id}/playlists/{playlist_id}

#### Steps to reproduce:
1. Create a Playlist
2. Change the Playlist image to a custom image.
3. The API returns a playlist image with null height and width
```
...
 "images" : [ {
    "height" : null,
    "url" : "https://pl.scdn.co/ima.........
    "width" : null
  } ],
...
```

#### Expected behaviour:
An image with valid height and width.

#### Actual behaviour:
Not being able to download custom image.

**Comment by hughrawlinson** [comment]
Hi @alex011235 - it seems you may have encountered an image transcoding error. Have you got an image as base64 you could share to help us reproduce the issue?

**Comment by alex011235** [comment]
Do you mean an image like this?
https://pl.scdn.co/images/pl/default/a705ea088c587f03f309b71e8216ba6367646cea

Why are some images (especially custom images) stored on"https://pl." ? Regular images are stored on "https://i..." or "https://mosaic...". 
Do you know if images on pl will be moved? I found out that images stored on pl are not trusted by our servers. We can close this issue if a change is not going to happen.

**Comment by hughrawlinson** [comment]
Hi @alex011235 - I think I may have misunderstood - in step 2, do you change the image using a Spotify client, or using the [image upload api](https://github.com/spotify/web-api/issues/157)?

As for which cdn the images are stored on - you shouldn't rely on the images being on any specific host, they could be in any location (for the forseeable future they'll be on some subdomain of scdn.co).

When you say the images on pl.scdn.co aren't trusted by your servers, do you mean you're seeing an SSL error?

**Comment by alex011235** [comment]
@hughrawlinson, we only scale the downloaded image, no uploads.

When I analyze the data traffic in Fiddler I get an "Access denied", but that is because of our servers. We wouldn't get the error if the images were stored on e.g. "https://i.scdn". I can't see an SSL error. 

To solve the problem, the url could be whitelisted in our servers. That is a very complicated procedure, not technically but bureaucratically. To me it seems like all custom images are stored on "https://pl.scdn". Can they be moved to "https://i.scdn"?

The best would if we could download images from all locations of course.

**Comment by hughrawlinson** [comment]
Hey @alex011235 - I'm afraid we can't guarantee the host of the cdn in advance. This is so that we're able to make changes and fixes whenever they need to be made without breaking assumptions about the APIs. All we can say is that the URL of the image in the API response should contain the correct image for the album.
