### ISSUE TITLE
Invalid `strict-transport-security` header

### ISSUE THREAD

**Issue by kubukoz** [spotify/web-api#655]
Issue found on September 4th 2017.

#### Endpoint(s):
* `GET /v1/player/me`

--

#### Scope(s):
* user-read-playback-state

--

#### Steps to reproduce:
1. Open the API Console
2. Call the `get-user-player` endpoint with any user

#### Expected behaviour:
Irrelevant

#### Actual behaviour:
Returns a response with a `strict-transport-security: max-age=31536000;` header, which is invalid, as brought to my attention by akka-http:

```
Illegal header: Illegal 'strict-transport-security' header: Invalid input 'EOI', expected OWS, 'i' or token0 (line 1, column 18): max-age=31536000;
```

So, if I get the specs right, the semicolon after max-age's value violates the RFC (https://tools.ietf.org/html/rfc6797). Samples on https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security indeed show a similar header without a semicolon:

```
Strict-Transport-Security: max-age=<expire-time>
```

The header's value being out of spec causes warnings in akka-http. It's nothing urgent, but would be nice to have fixed :)

**Comment by bih** [comment]
Hey! This is something I have raised with our Web API team. I agree that it is not urgent, but it's something that we should fix this in order to meet the RFC. We'll keep you updated when we have updates/a fix 👍  Thanks!

**Comment by bih** [comment]
Exciting news, @kubukoz! 🎉

We have now fixed the issue. I'm going to close this issue, but feel free to comment or reach to us directly if you have any questions.

P.S. Merry Christmas! 🎄 🙂

**Comment by kubukoz** [comment]
Cool stuff! Merry Christmas @bih and the rest of the team :)
