### ISSUE TITLE
OAuth-related integration tests 

### ISSUE THREAD

**Issue by RobinVivant** [spotify/web-api#658]
Hi folks,

I'm a backend engineer, working on integrating our iOS app with this API. For this purpose we are implementing this workflow: https://developer.spotify.com/technologies/spotify-ios-sdk/token-swap-refresh/

All is great and working. But then we want to setup server-side integration tests.

I have a single question: is there a reasonable way to have automated tests generating an OAuth `code` that could be sent to the `/swap` endpoint?

Btw, test API credentials would be nice to have too.

Best regards

**Comment by hughrawlinson** [comment]
Hi @RobinVivant - there's no supported mechanism for writing tests against our APIs. I'd suggest that you mock them in your integration test environment.
