### ISSUE TITLE
Getting Audio Features for Track with ID 7y7zF5PJTUxiSpqxOWrntI (Among others) return 404

### ISSUE THREAD

**Issue by inmanenz** [spotify/web-api#659]
Issue found on September 13th 2017.

#### Endpoint(s):
* `GET https://api.spotify.com/v1/audio-features/{id

#### Scope(s):
* None (application is not using authentication)

#### Steps to reproduce:
1. Open the API Console
2. Call the `audio-features` endpoint with `id` `7y7zF5PJTUxiSpqxOWrntI`

#### Expected behaviour:
A audio features object as described on https://developer.spotify.com/web-api/get-audio-features/`.

#### Actual behaviour:
404 Error for this track and multiple others

**Comment by arirawr** [comment]
Hi @inmanenz, we're aware of an issue affecting this endpoint and are looking into it. I'll let you know when we have an update.

**Comment by arirawr** [comment]
This issue has been resolved. Please let us know if you encounter it again. Thanks for reporting!
