### ISSUE TITLE
Followers object does not have full details

### ISSUE THREAD

**Issue by tylerjdurden** [spotify/web-api#665]
Request date: Sept 18, 2017

I'd like to request an enhancement.

#### Endpoint(s):
* `GET /v1/users/{user_id}/playlists/{playlist_id}`

The above endpoint is used to get a playlist given its `playlist_id` and its creator's `user_id`. It returns a [followers object](https://developer.spotify.com/web-api/object-model/#followers-object), which has two fields: `href` and `total`. 

`total` represents the number of followers, and `href` is _supposed_ to be a link to the full follower details. However, as of today, the documentation for this field states that `href` is:

> A link to the Web API endpoint providing full details of the followers; null if not available. Please note that this will always be set to null, as the Web API does not support it at the moment.

Are there any current plans to implement this? I am working on a project for which I think full follower details could be valuable. Even just `user_id`s for each of them would prove very useful.

Thanks!

**Comment by bih** [comment]
Hey! We definitely still have plans on adding a `/v1/users/{user_id}/playlists/{playlist_id}/followers` API endpoint at some point in the future. There isn't much I can say right now other than we don't have much to announce right now, but I will be sure to chase up and see where we are with this.

**Comment by jeppiebarroga** [comment]
Hi @tylerjdurden, til now the feature hasn't been addressed. May I know what work around did you do to carry on with your project? I'm also working on something that needs information about the current user's followers. Thank you!

**Comment by arirawr** [comment]
Hey all,

As per our [new developer support process](https://github.com/spotify/web-api#creating-an-issue), any feature requests that have no plans to be considered in the next 6 months will be closed as wontfix.

We do not have any plans to implement this in the next 6 months and thus will close as wontfix.

We encourage you and other members of the community to continue to share use cases and your support for this feature, as it helps us prioritize features going forward. You will be able to comment on this issue even after it is closed. We will also post any updates here relating to this suggestion when they happen.

**Comment by eballeste** [comment]
I've always wondered why this particularly useful feature has always been postponed as a nice to have, probably never happening thing.
