### ISSUE TITLE
I'd like to leave one or two specific genres in the search field.

### ISSUE THREAD

**Issue by nickjhonatam** [spotify/web-api#669]
I'd like to leave one or two specific genres in the search field.

the part that I have to change is this:

interface SearchInterface {

     / **
      * Search database using given params.
      *
      * @param string $ q
      * @param int $ limit
      * @param string $ type
      *
      * @return array
      * /
     public function search ($ q, $ limit = 10);
}

Can someone help me with this?

**Comment by jscholes** [comment]
I'm not sure what you're asking.  If you want to search for tracks or artists of a specific genre, you can use the genre field filter e.g.:

    genre:folk

This should be included in the search query itself ($q in your code above).  You can [read more about field filters here](https://developer.spotify.com/web-api/search-item/).

**Comment by arirawr** [comment]
@jscholes is correct - you need to include the genre filter within the query, which is the string `q`.

You can only filter by one genre at a time via this endpoint.
