### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by edwindayot** [spotify/web-api#67]
Cannot retrieve related artists of artist "3hv9jJF3adDNsBSIQDqcjp"

Issue found on June 9th 2015.

Endpoint(s): /artists/{id}/related-artists Scope(s): Credentials Authentication

Steps to reproduce: Use the API Console, https://developer.spotify.com/web-api/console/get-artist-related-artists/ with the ID "3hv9jJF3adDNsBSIQDqcjp" (Mark Ronson)

Expected behaviour: A related artists object as described on https://developer.spotify.com/web-api/get-related-artists/.

Actual behaviour: 502 Bad Gateway

**Comment by thelinmichael** [comment]
Thanks for the very swift report @edwindayot. We ran into some serious networking issues, but it's been resolved now.
