### ISSUE TITLE
Occasional 502 Response for player endpoint

### ISSUE THREAD

**Issue by tance77** [spotify/web-api#670]
Issue found on February 19th 2015.

#### Endpoint(s):
* `GET /v1/me/player`

#### Steps to reproduce:
1. Make a JS request using Axios
2. Call the above endpoint

#### Expected behaviour:
200 Response

#### Actual behaviour:
502 Server Error (rarely)

**Comment by arirawr** [comment]
Hey there, thanks for the report! We monitor all errors and strive to minimise them. However, sometimes the unexpected happens and you may see 500 errors temporarily. In that case, you can try your request again. Please let us know if you start to see this happen more frequently.
