### ISSUE TITLE
Cannot retrieve spotify devices with /v1/me/player/devices

### ISSUE THREAD

**Issue by QNimbus** [spotify/web-api#671]
Issue found on February 22nd September 2017.

#### Endpoint(s):
* `GET /v1/me/player/devices`

#### Scope(s):
* None (application is not using authentication)

#### Steps to reproduce:
1. Open the API Console
2. Call the `Get a User's Available Devices` endpoint

#### Expected behaviour:
A list of all my Spotify connect devices (several Sonos speakers, mobile clients, et cetera)

#### Actual behaviour:
Everytime I query the endpoint I only see my web player (Chrome tab) device, none of my other devices that I can see using the official Spotify App on my phone, or the devices I can see using the web player.

{
  "devices" : [ {
    "id" : "13b1cxxxxxxx7e1c1920cxxxxxxxxf685316c313",
    "is_active" : false,
    "is_restricted" : false,
    "name" : "Web Player (Chrome)",
    "type" : "Computer",
    "volume_percent" : 100
  } ]
}

**Comment by jscholes** [comment]
Certain devices, particularly third party speakers and Sonos units, are not currently controllable through the Web API Connect endpoints.  The /v1/me/player/devices endpoint will only return information for devices which are both active and controllable.  You can read more in the [Working With Web API Connect document](https://developer.spotify.com/web-api/working-with-connect/#observing-devices).

**Comment by DoCode** [comment]
Ok. Please add support for other devices.

**Comment by mar-schmidt** [comment]
Requesting support for devices like Sonos.

**Comment by hughrawlinson** [comment]
Hi! We will continue to add support for as many devices as possible as we're able to. In some cases, devices are not accessible from our servers and therefore are not shown in the response because they have become inactive.

**Comment by joshhodgson** [comment]
@timdonovanuk Chromecasts aren't Spotify Connect devices until they get woken up, they aren't in constant communication with Spotify like a "real" Connect device would be (eg Amazon Echo). Your phone uses the Chromecast API to detect and then wake up the Chromecasts.. there's no reason you couldn't do the same.

**Comment by CosmicMac** [comment]
`devices` endpoint does not find my Sonos One pair, even during playback.
`player` endpoint does, though with a null id:
```
"device": {
    "id": null,
    "is_active": true,
    "is_restricted": true,
    "name": "Sonos Véranda",
    "type": "Speaker",
    "volume_percent": 0
  }
```
Not very consistent.

**Comment by stuart-purr** [comment]
> `devices` endpoint does not find my Sonos One pair, even during playback.
> `player` endpoint does, though with a null id:
> 
> ```
> "device": {
>     "id": null,
>     "is_active": true,
>     "is_restricted": true,
>     "name": "Sonos Véranda",
>     "type": "Speaker",
>     "volume_percent": 0
>   }
> ```
> Not very consistent.

I am also experiencing this, is there a reason behind this?

**Comment by Royal2000H** [comment]
+1
Why are we able to connect to Sonos devices through the Spotify app but not through the API?

**Comment by maurotrentini** [comment]
I have a Windows 10 PC with Spotify desktop installed.

I currently have my Spotify desktop app open and I am logged in with my account. When I retrieve the available devices via the API, it returns an empty list. If I start playback on Spotify desktop and call the same API endpoint, it returns my device successfully.

Shouldn't it return my device even when playback is paused?

**Comment by DracoBlue** [comment]
Any updates on this? This seemed to work for a while, but stopped working some months ago.
