### ISSUE TITLE
Getting 401 when starting premium user playback

### ISSUE THREAD

**Issue by mlnor27** [spotify/web-api#672]
Issue found on September 22th 2017.

#### Endpoint(s):
* `PUT /v1/me/player/play

#### Scope(s):
* None (application is not using authentication)

#### Steps to reproduce:
1. Open the API Console
2. Call the `Start/Resume a User’s Playback` endpoint with a premium oauth token and his active device id

#### Expected behaviour:
204 NO CONTENT on `https://developer.spotify.com/web-api/start-a-users-playback/`.

#### Actual behaviour:
Error: Request failed with status code 401

**Comment by jscholes** [comment]
It's possible that either the access token has expired or it wasn't issued with the appropriate scope.  The body of the response should contain more information about the specific error, for example:

    {
      "error": {
        "status": 401,
        "message": "The access token expired"
      }
    }

Or alternatively:

    {
  "    error" : {
       "status" : 401,
       "message" : "Permissions missing"
     }
    }

Could you clear the token and generate a new one, ensuring that you tick the user-modify-playback-state scope check box, and then confirm whether or not the issue still occurs?  If it does, please post the error response here.

**Comment by mlnor27** [comment]
Hi, thanks for your response,

I actually encountered this error not on the API console but on my js code using Axios put requests. When making a PUT request using Curl or the api console, everything's fine. It seems like axios is having trouble making PUT requests using the start/resume users's playback endpoint. I solved my issue by using jquery. 
Thanks again

**Comment by arirawr** [comment]
Hey @mlnor27, I'm glad you found a fix. I'm going to go ahead and close this issue - happy hacking!
