### ISSUE TITLE
New Releases Endpoint Not Updated Since Sept 8th, 2017

### ISSUE THREAD

**Issue by nknauer** [spotify/web-api#673]
Has anyone tried accessing the new releases endpoint? I have tried accessing the new releases the past two weeks and it hasn't updated since the first Friday of September 2017. It still has only the new releases from the following artists: 

https://api.spotify.com/v1/browse/new-releases

Sam Smith
The National
ODESZA
Alvvays
Jack Johnson
The Black Seeds
etc.

Thanks!

**Comment by KnutZuidema** [comment]
It's updated for me.
I get these:
GEMINI by Macklemore
Wonderful Wonderful (Deluxe) by The Killers
Awake by Illenium
By Any Means 2 by Kevin Gates
Trip by Jhene Aiko
Spent the Day in Bed by Morrissey
Side A by Jillian Jacqueline
All In by Matthew West
Again by Noah Cyrus
Young Martha by Young Thug
Run It Up by Dame D.O.L.L.A
All Things Work Together by Lecrae
Love Yourself 承 'Her' by BTS
A Different Way (Feat. Lauv) by DJ Snake
Week Without You by Miley Cyrus
Laila’s Wisdom by Rapsody
On The Rocks by Midland
One Foot by WALK THE MOON
Moments Passed by Dermot Kennedy
Haiku From Zero by Cut Copy

**Comment by nknauer** [comment]
Thanks. It updated Friday afternoon. There was a two week time span where it wasn't updating which is why I posted this. Fyi GEMINI is a great album! 

I guess to close out this question, is there a set time that this API endpoint will update every Friday? I've seen it updated as early at 9:00AM EST, as late as 4:00PM EST, and sometimes not update at all that week.

**Comment by arirawr** [comment]
Hi there! New Releases are manually curated and published by our editors, so we have no guarantees for exactly when they will be updated. Usually, though, new items are added on Friday mornings. Hope that helps!
