### ISSUE TITLE
Rate limits hit on authorization flow

### ISSUE THREAD

**Issue by squared99** [spotify/web-api#674]
Hi There,

Understandably there are rate limits and best practices suggested when making API call but we seem to hit this issue during authorization flows. For example once the user has authorized and we make a /me API request to retrieve their user information to store identifiers for future login, or to create a local user in a CRM.

Unlike other API calls where you may be able to queue and stagger requests, retrieving user data after authorization needs to happen at the time the user is logging in and so is less controllable. 

Is there anything that can be done to avoid 429 errors during authorization?

Many Thanks

**Comment by hughrawlinson** [comment]
Hi - if you make your requests from your backend, you could put them in a queue that handles rate limits, even implementing your own priority logic if you wanted. That way you can entirely control your rate of requests, and store the credentials for future use.
