### ISSUE TITLE
Can only play albums or playlists, not songs

### ISSUE THREAD

**Issue by Nickedude** [spotify/web-api#675]
Title: Can only play albums or playlists, not songs

Issue found on September 23rd 2017.

#### Comment:
This is more of a question than a bug report. I've tried calling the API in order to change the song currently playing. It works fine when i provide a playlist, artist or an album as a Spotify URI but when i provide a track i get the response below. Is this the inteded behaviour? If so, will song URI's be supported in the future? Thanks a lot! 😃 

#### Endpoint(s):
* `PUT v1/me/player/play`

#### Scope(s):
* user-modify-playback-state

#### Steps to reproduce:
1. Open the API Console
2. Call the `v1/me/player/play` endpoint with a valid OAuth token and the Spotify URI for a track.

#### Expected behaviour:
The track should start playing on the current player.

#### Actual behaviour:
400 "Non supported context uri" received for several songs (tried around 15 songs).

**Comment by jscholes** [comment]
The only valid contexts supported by the Web API Connect endpoints are albums, artists and playlists.  A single track doesn't constitute a context.  If you want to play one or more track URIs independent of any particular context, pass an array of URIs, like this:

    {
      "uris": ["spotify:track:561F1zqRwGPCTMRsLsXVtL", "spotify:track:51ueZKM83MTRv9rgiDfI6Y"]
    }

Or as a curl command:

    curl -X PUT "https://api.spotify.com/v1/me/player/play" -H "Accept: application/json" -H "Authorization: Bearer <access_token>" -H "Content-Type: application/json" --data "{\"uris\":[\"spotify:track:561F1zqRwGPCTMRsLsXVtL\", \"spotify:track:51ueZKM83MTRv9rgiDfI6Y\"]}"

**Comment by Nickedude** [comment]
Ah i see, my bad! 😀
