### ISSUE TITLE
Invalid authorization code on token endpoint

### ISSUE THREAD

**Issue by rvbiljouw** [spotify/web-api#676]
Issue found on 23th of September 2017

#### Endpoint(s):
* `POST https://accounts.spotify.com/api/token`

#### Steps to reproduce:
1. Redirect user to login flow (https://accounts.spotify.com/authorize?response_type=code&client_id=10a4963dcc5c472b8d5c52004d08cb43&redirect_uri=http://localhost:8080/login/callback)
2. Receive callback on http://localhost:8080/login/callback with "code" in query parameter.
3. Make POST request to https://accounts.spotify.com/api/token with code from callback.

The steps above result in API returning 400 Bad Request w/ message "Invalid authorization code."

The POST body I'm sending to the token endpoint looks like this:
```
grant_type=authorization_code
code=AQBD4CLvpVZFpMzoUwv1RX8EMZqtZ3xQb0CN6wdt4ZMYUx1ZJyYTn-NsdY0Z85HjlNTWXB4Xp9kA8B2Gh6Jh4pw5Y0xKp1-Elr067pAwHXcXAtQGqe1DBUCTXz400aDiWFjqaQHcr2sIRqBY6ttK8u9Gdp7D2EkL3kPqsSB8v6yJnmscy5sBVV3F2xpF6FJQY_TzwqAEWdOJ-Gakog5FTUsjDOXP9WyAOr893FcKlUHpX4355hh4koJBLn7WidJifw8AyFAyg1puDsXc42HyIeCfURVWY2tC8L7em-r5Az7Ybn1pN4UZvNf2hn6HBNRul_LA0RcUaSHyMSJowdo9Ix4Cw6YH55o16w-Zr0_JnvbXTKrq3Onvp52KVg2JldOb2tY5PSyPPOef4SyAN1a3_yD-fC5a
redirect_uri=http://localhost:8080/login/callback
client_secret=<redacted>
client_id=10a4963dcc5c472b8d5c52004d08cb43
```

What's interesting is if I wait long enough the endpoint starts returning messages indicating that the authorization code expired. This seems contradictory, because how can the code expire if it's "invalid" (assuming that invalid means it doesn't exist).

**Comment by ddxtanx** [comment]
Was this issue fixed? If so, how?

**Comment by kaiferrall** [comment]
I am having this issue as well using the code from the query parameter and it still says invalid auth code. Can anyone help. Thanks!

**Comment by Sai-Vamshi** [comment]
That happens when sending the request using the same auth code more than once.
