### ISSUE TITLE
Requests that doesn't required Access Token don't work without it.

### ISSUE THREAD

**Issue by ifomex** [spotify/web-api#679]
Requests that doesn't required Access Token don't work without it.

Issue found on September 27th 2017.

#### Endpoint(s):
* `GET /v1/albums/{id}
* `GET /v1/artists/{id}/top-tracks

#### Scope(s):
* None (application is not using authentication)

#### Steps to reproduce:
1. Open the API Console
2. Call the endpoints above

#### Expected behaviour:
return list of tracks.

#### Actual behaviour:
return
{
  "error": {
    "status": 401,
    "message": "No token provided"
  }
}

**Comment by jscholes** [comment]
As of earlier this year, all Web API endpoints require authorisation, regardless of whether they read, modify or otherwise use user data.

**Comment by arirawr** [comment]
As @jscholes has pointed out, all Web API endpoints require an access token. You can read more about that here: https://developer.spotify.com/news-stories/2017/01/27/removing-unauthenticated-calls-to-the-web-api/

You can use one of the methods described in our [Authorization Guide](https://developer.spotify.com/web-api/authorization-guide/) to get an access token.
