### ISSUE TITLE
User Profile stats regarding songs/playlist/albums listened

### ISSUE THREAD

**Issue by dinoparavandis** [spotify/web-api#68]
It would be great if you have API calls for that info regarding my personal account.  In more detail, what was my most listened playlist last month? or song or album.  

Thanks
Dino

**Comment by thelinmichael** [comment]
Thanks for your feedback @dinoparavandis! There's an existing feature request very similar to this one - #20 "Play History Management - User's recently played tracks". It does have a smaller scope though, in that it only covers what **tracks** a user has listened to recently. I'm going to widen the scope of that issue to include other entity types as well, and close this one. I'd be very interested in hearing about what entity types are the most important for you.
