### ISSUE TITLE
Setting a device to -> “is_active" : true

### ISSUE THREAD

**Issue by kwindo** [spotify/web-api#680]
I am experimenting with the new “player” Web API endpoints. Before I can start playing music in my app I need to launch the Spotify client and click on the play button. Otherwise calling “/v1/me/player/play” will return a “403 Forbidden”.

When calling for Available Devices, the launched Spotify client will return but with ‘“is_active" : false’. Clicking de play button in the client will turn this to ‘“is_active" : true’ which makes the play call work.

Having to launch the Spotify app I can live with but I think it’s a bit strange to have to ask my users to quickly play and pause before the controls from my app will work. 

Is there a way to activate a device remotely? Or am I overlooking something else?

**Comment by jscholes** [comment]
> Is there a way to activate a device remotely?

Have you tried [transferring playback](https://developer.spotify.com/web-api/transfer-a-users-playback/) to the desired device to see if that causes the device to become active?

**Comment by kwindo** [comment]
Thanks for your reply James. 

No, not yet but that might be the solution. If I have two devices (desktop and iPhone) and transfer to the not active device it will start playing. 

Need some time to test it when only one device is available and have the call send automatically.

**Comment by kwindo** [comment]
Strangely, now when I launch the Spotify client it comes up as active automatically in my web app. As if someone changes something in the API right after I posted this issue.

**Comment by kwindo** [comment]
Indeed, transfer a User’s Playback seems to do the trick.

**Comment by kwindo** [comment]
Sorry I had to re-open this issue. The above solution works sometimes but not overtime.

It appears that when I've been listening to Spotify on my iPhone for a while, then open up my web-app on my desktop (with no devices active) and launch the Spotify client on my desktop, connection between my app and the Spotify client completely vanishes after calling /v1/me/player.

The only way to get the connection back is to select an other song on the Spotify client and click play.

I noticed before that sending out the correct device information is sometimes an issue.

**Comment by hughrawlinson** [comment]
Hi @kwindo - transferring playback is the correct way to do this. There are some cases in which it's impossible to transfer playback to a device without user interaction, including iOS, where the app has to be active to receive incoming requests for transfer. You can use the `is_restricted` field in the Get A Users Devices endpoint to know in advance whether or not it's possible to transfer to a device. Hope that helps!
