### ISSUE TITLE
Search query field filters only match whole words

### ISSUE THREAD

**Issue by moyerr** [spotify/web-api#681]
Issue found on September 28th 2017.

#### Endpoint(s):
* `GET /v1/search`

#### Scope(s):
* None

#### Description:
When using field filters in a search query, partial word matches seem to be completely ignored and only whole word matches are returned. 

For example, consider a search for "Slow Hands" by Interpol (`uri: spotify:track:0mF7YNgURDkBQaxa9YRc47`). The following queries should return our expected track with the results:
* ✅ `q=artist:interpol%20track:slow%20hands&type=track`
* ✅ `q=artist:interpol%20track:slow&type=track`
* ⛔️ `q=artist:inter%20track:slow%20hands&type=track`
* ⛔️ `q=artist:interpol%20track:slow%20hand&type=track`

However, the second two queries return an empty set because they contain partial word matches (*inter* and *hand*, respectively).

#### Steps to reproduce:
1. Open the API Console
2. Call the `search` endpoint with `q=artist:interpol%20track:slow%20hand&type=track`

#### Expected behaviour:
The API returns a list of results, including "Slow Hands" by Interpol (`uri: spotify:track:0mF7YNgURDkBQaxa9YRc47`).

#### Actual behaviour:
The API returns an empty set of results.

**Comment by hughrawlinson** [comment]
Hi! Thanks for the report. We'll look into it.

**Comment by hughrawlinson** [comment]
Hi @moyerr - to match against partial words, please append '*' to the words. For example, `interp*`.
