### ISSUE TITLE
Why is there two "New Music Friday" playlist?

### ISSUE THREAD

**Issue by lohriialo** [spotify/web-api#683]
I see there are two playlist with the same name "New Music Friday" both of which are updated recently(4 days ago)

```
spotify:user:spotify:playlist:37i9dQZF1DX4JAvHpjipBk
spotify:user:spotify:playlist:37i9dQZF1DWXJfnUiYjUKT
```
Playlist description doesn't tell how this two are different or the logic of how the two playlist is curated? Please share some light, i'm confused to which playlistID to call in my app

**Comment by arirawr** [comment]
Hi @lohriialo !

There are different New Music Friday playlists for different regions. It looks like you've found 2 of them!

If you want to get the correct New Music Friday for a user's region, try using the `browse/featured-playlists` endpoint. If you set the timestamp to a Friday and the country to the user's country, you should get the New Music Friday playlist for their region. You could then save the URI for the playlist. Here's an example for Sweden, using tomorrow's date as a timestamp: https://developer.spotify.com/web-api/console/get-featured-playlists/?timestamp=2017-10-06T09%3A00%3A00&country=SE

Hope that helps! 

PS. If you're into new music, check out our [New Releases endpoint](https://developer.spotify.com/web-api/get-list-new-releases/)!
