### ISSUE TITLE
sending a HTTP “POST” request to the Spotify API for the access token using C#.Net(asp.Net)

### ISSUE THREAD

**Issue by israelquiroz93** [spotify/web-api#684]
Ok so I am currently trying to do the HTTP "POST" request as the Spotify API requires to obtain the access token which then allows me to access other data in the Spotify library. I do not need to have the user login as i am not getting user data, i am trying to just show some data of some albums. This is what I have so far and I am getting a (400) Bad Request error at the line "HttpWebResponse resp = (HttpWebResponse)webRequest.GetResponse();" and cant seem to figure out what is the problem. I know Spotify returns JSON objects, so my string JSON will need to be turned into JSON. I also believe i have encoded the header correctly to Base 64 encoded string as the API says i need to do and have also set the request body to "grant_type=client_credentials". I have been following the instructions that are on the "developer.spotify.com/web-api/authorization-guide/#authorization-code-flow". I am really stuck and dont have much experience doing this so i imagine im doing some rookie mistake, if anyone that has done this and can help me out i would really appreciate it :)

     `string url5 = "https://accounts.spotify.com/api/token"

     byte[] client_byte = Encoding.UTF8.GetBytes(client_id);
     var clientid_mod = Convert.ToBase64String(client_byte); //clientid is modded to Base 64 encoded     string

     byte[] clientsecret_byte = Encoding.UTF8.GetBytes(client_secret);
     var clientsecret_mod = Convert.ToBase64String(clientsecret_byte);//clientsecret is modded to Base 64 encoded string

     //request to get the access token

        HttpWebRequest webRequest = (HttpWebRequest)WebRequest.Create(url5);

        webRequest.Method = "POST";
        webRequest.ContentType = "application/x-www-form-urlencoded";
        webRequest.Accept = "application/json";
        webRequest.Headers.Add("Authorization: Basic" + clientid_mod + ":" + clientsecret_mod);
        var request = ("grant_type=client_credentials");
        byte[] req_bytes = Encoding.ASCII.GetBytes(request);
        webRequest.ContentLength = req_bytes.Length;

        Stream strm = webRequest.GetRequestStream();
        strm.Write(req_bytes, 0, req_bytes.Length);
        strm.Close();

        HttpWebResponse resp = (HttpWebResponse)webRequest.GetResponse();

        String json = "";
        using (Stream respStr = resp.GetResponseStream())
        {
            using (StreamReader rdr = new StreamReader(respStr, Encoding.UTF8))
            {
                //should get back a string i can then turn to json and parse for accesstoken
                json = rdr.ReadToEnd();
                rdr.Close();
            }
        }`

**Comment by jscholes** [comment]
You need to base64 encode the client ID and secret together, in the format client_id:client_secret.  At the moment you're encoding them separately, then joining the two base64 strings together with a colon.

**Comment by israelquiroz93** [comment]
@jscholes thank you so much!!!! Much love man that got it done!

**Comment by MahendraPrasad** [comment]
israelquiroz93, can you share me the full correct code?

**Comment by MahendraPrasad** [comment]
How do i pass the parameter['code', 'grant-type', 'client-id', 'client-secret', 'redirect_uri']  usimg "POST" method

**Comment by eagarsatya** [comment]
> How do i pass the parameter['code', 'grant-type', 'client-id', 'client-secret', 'redirect_uri'] usimg "POST" method

Have u solved this one? I am new to this API things :(
