### ISSUE TITLE
Please add album release dates to artist album info

### ISSUE THREAD

**Issue by andersborgabiro** [spotify/web-api#686]
Addition of release date (and precision) to /v1/artists/{id}/albums would save on API calls, that as you know is both a rate limit and performance issue.

As the order of the albums is not guaranteed to be release date descending, this is an important way of optimising API use and user experience (user-perceived performance) when the albums need to be sorted.

I'm currently using /v1/albums, that has a limit of 20 albums (instead of 50), so chunking is needed, adding API calls, but of course not as much as individual requests for /v1/albums/{id}.

**Comment by arirawr** [comment]
Hi @andersborgabiro, thanks for the request. We'll be sure to update you if there are any developments on this.

**Comment by paulo-raca** [comment]
I'm also interested in this feature

**Comment by arirawr** [comment]
I'm happy to let you know that this is now supported in the API. Thanks for your suggestion!

You can see the endpoint in action using our [Web Console](https://developer.spotify.com/console/get-artist-albums/).

**Comment by andersborgabiro** [comment]
Nice, thanks.

**Comment by paulo-raca** [comment]
Thank you!
