### ISSUE TITLE
Lots of 502 errors today

### ISSUE THREAD

**Issue by roblesterjr04** [spotify/web-api#689]
Issue found on October 10th 2017.

#### Endpoint(s):
* current track
* pause
* play

#### Scope(s):
```
'scope' => [
		            'user-read-email',
		            'user-read-private',
		            'streaming',
		            'playlist-read-private',
		            'playlist-read-collaborative',
		            'playlist-modify-public',
		            'playlist-modify-private',
		            'user-library-read',
		            'user-top-read',
		            'user-read-playback-state'
		        ],
```

#### Steps to reproduce:
May not be able to reproduce. Intermittent 502 bad gateway errors.

#### Expected behaviour:
API results

#### Actual behaviour:
502 Server Error (intermittently)
500 error at least once today.

**Comment by arirawr** [comment]
Hey there, thanks for the report! We monitor all errors and strive to minimise them. However, sometimes the unexpected happens and you may see 500 errors temporarily. In that case, you can try your request again. Please let us know if you start to see this happen more frequently.
