### ISSUE TITLE
"Save Album for Current User"

### ISSUE THREAD

**Issue by pateretou** [spotify/web-api#69]
Hi

I'm working on a script to migrate all my deezer album to spotify.

The problem I have is there is no way to add an entire album to the current user.
You can add each track album but in this case the filter "full albums only" doesn't work.

Could you please add in the "user library" the "Save Album for Current User" ?

If i'm trying to add an album with "/v1/me/tracks" I have a "Payload contains a non-existing ID"

Thanks a lot

**Comment by thelinmichael** [comment]
Hi @pateretou, thanks for your feedback. This is in our backlog but can't promise that it'll be available in the short-term. We'll update this issue when it's available.

Although I'm very happy to hear that you're moving your collection to Spotify, be sure to not break Deezer's Terms of Service with your application.

**Comment by peeinears** [comment]
Bump. Would realllllly love this as well. Trying to migrate my collection from Rdio (as I suspect many others will be doing given the news) but running into the same problem as above: I can add all the tracks, but then nothing shows up with the "Saved Albums Only" filter.

**Comment by peeinears** [comment]
FWIW, I'm finding that this functionality currently exists, it's just undocumented...

**Comment by metric152** [comment]
@peeinears what's the api you're hitting for that?

**Comment by JohnnyCrazy** [comment]
@peeinears is indeed right, there is an endpoint at `https://api.spotify.com/v1/me/albums` which is basically the same as `/me/tracks` just for albums. `PUT`/`GET`/`DELETE` and `/contains` are working as expected

Any specific reason why this is not documented @thelinmichael ?

**Comment by zvonicek** [comment]
@peeinears Would be great if you could share your migration script from Rdio with us ;-) I'm about to write something similar.

**Comment by peeinears** [comment]
@zvonicek Will do if I get it cleaned up a bit. I know @metric152 is working on one that's pretty far along: https://github.com/metric152/move_to_spotify

**Comment by thelinmichael** [comment]
As luck would have it we'd just made these endpoints available to you guys, and we're looking forward to seeing the cool stuff that you'll use them for!

The documentation is now published as well, see:
- [Save Album for User](https://developer.spotify.com/web-api/save-albums-user/)
- [Get User's Saved Albums](https://developer.spotify.com/web-api/get-users-saved-albums/)
- [Remove Album for User](https://developer.spotify.com/web-api/remove-albums-user/)
- [Check User's Saved Albums](https://developer.spotify.com/web-api/check-users-saved-albums/)

Feedback is appreciated. Also, well spotted @peeinears! :star2:

**Comment by peeinears** [comment]
Right on, thanks!

@thelinmichael IIRC, the `GET me/albums` endpoint returns both albums you've saved as well as albums whose tracks you've saved. Is there a way to effectively use "Saved Albums Only" filter via the API? Or at least is there a way to know which albums are fully "saved" and which aren't?

**Comment by thelinmichael** [comment]
@peeinears, we'll try to clarify this in the documentation, but the current behaviour is that saving an album will also save all tracks in that album. Our aim is that the behaviour in the Web API should be similar to the one in the Spotify App, so if the behaviour changes in the app, it'll change in the Web API as well.

**Comment by thelinmichael** [comment]
@peeinears, I misunderstood your previous point. Your observation was correct, the returned albums included albums that simply contained saved tracks. This has been fixed and the `/me/albums` endpoint should now only return albums that have been explicitly saved.

Closing this ticket since this feature has been implemented but feel free to drop feedback, it's greatly appreciated.

**Comment by peeinears** [comment]
@thelinmichael Fantastic, thanks!

**Comment by gabriel-roth** [comment]
> @peeinears, we'll try to clarify this in the documentation, but the current behaviour is that saving an album will also save all tracks in that album. Our aim is that the behaviour in the Web API should be similar to the one in the Spotify App, so if the behaviour changes in the app, it'll change in the Web API as well.

This behavior has changed in the app but not in the API.
