### ISSUE TITLE
Artist top-tracks returning 0 popularity for some tracks

### ISSUE THREAD

**Issue by srveale** [spotify/web-api#690]
Issue found on October 11th 2017.

#### Endpoint(s):
* `GET /v1/artists/{id}/top-tracks`

#### Steps to reproduce:
1. Open the API Console
2. Call the `v1/artists/{id}/top-tracks` endpoint with `id` `0QJIPDAEDILuo8AIq3pMuU`, with country code 'CA' (or 'US') 

#### Expected behaviour:
Receive an array of tracks, each of which has non-zero popularity (assuming they aren't actually unpopular).

#### Actual behaviour:
Several tracks have a popularity of zero. This happens with many artists, but not all. Some artists have one zero-popularity track, some artists have several. I think it's a safe assumption that these tracks actually have higher-than-zero popularity, and in past requests - as recently as yesterday - I've received high popularity values for tracks that now show zero.

**Comment by hughrawlinson** [comment]
Hi @srveale - at the moment all of the top tracks for that artist have non-zero popularities for me. I imagine this was a one-off issue so I'll close this issue, but if you can still reproduce it, feel free to reopen.
