### ISSUE TITLE
Undocumented `restrictions` field on track

### ISSUE THREAD

**Issue by brodin** [spotify/web-api#691]
Issue found on October 13th 2017.

#### Endpoint(s):
* `GET v1/tracks/{id}`

#### Scope(s):
* None (application is not using authentication)

#### Steps to reproduce:
1. Open the API Console
2. Call the `get-track` endpoint with `id` `093sDefkMjV3HG3QbfM8Zz` and `market` `US`

#### Expected behaviour:
A track object as described on `https://developer.spotify.com/web-api/object-model/#track-object-full`.

#### Actual behaviour:
A track object with 
```json
  "restrictions" : {
    "reason" : "market"
  },
```
What is this? :)

**Comment by brodin** [comment]
> If the is_playable property is false, the original track is not available in the given market, and Spotify did not have any tracks to relink it with. The track response will still contain metadata for the original track, and a restrictions object containing the reason why the track is not available: "restrictions" : {"reason" : "market"}.
https://developer.spotify.com/web-api/track-relinking-guide/

However it would be great if the same info was accessible at https://developer.spotify.com/web-api/object-model/#track-object-full

**Comment by arirawr** [comment]
Great catch! I've updated the documentation so that the track object model now includes the restrictions object.
