### ISSUE TITLE
Create playlist from audio recorded by user

### ISSUE THREAD

**Issue by philsheppard100** [spotify/web-api#692]
Hi - I often know what music I want to listen to in terms of rhythm, instruments and perhaps tune, and I can hum or sing something along those lines, often improvised - but there isn't a way I can input that to Spotify.  The apps which enable you to create a playlist based on an existing track don't quite do it.

**Comment by hughrawlinson** [comment]
Hi! Thanks for your request. This isn't a feature that we can prioritize developing in the foreseeable future due to its scope.
