### ISSUE TITLE
Cannot add local tracks using Add Tracks to a Playlist

### ISSUE THREAD

**Issue by mkmoisen** [spotify/web-api#693]
Issue found on October 15th 2017.

#### Endpoint(s):
* `POST /v1/users/{user_id}/playlists/{playlist_id}/tracks`
#### Scope(s):
* playlist-modify-public
* playlist-modify-private

#### Steps to reproduce:
1. Open the API Console
2. Call the `post-playlist-tracks` endpoint containing a uri with a local track, like `spotify:local:...`.

#### Expected behaviour:
The local track is added to the playlist

#### Actual behaviour:
400 User Error (consistently)
{u'error': {u'status': 400, u'message': u'Invalid track uri: spotify:local:...'}}

#### Notes
I realize that local tracks by definition are not on Spotify's cloud, so it would take additional effort to find the local track and add it to the playlist. It would make sense if the API was able to inspect the user's local tracks to see if it exists, and then add it to the playlist. Otherwise if it cannot find the local track on the user's local track listing, raise a 404.

My use case here is to create a new, shuffled playlist from the combination of other input playlists, on a given user's account. As a workaround I'm removing any tracks from the input playlists whose uri's start with `spotify:local` and notifying the user that they need to add them manually, but that isn't ideal.

Thanks!

**Comment by hughrawlinson** [comment]
Hi! Local tracks are not supported by the Web API at all, and at this point, we have no plans to start supporting it. Your current workaround seems like the best solution in this case.
