### ISSUE TITLE
Feature Request: Get Audio Analysis for Several Tracks

### ISSUE THREAD

**Issue by mkmoisen** [spotify/web-api#694]
Currently, it looks like the API only supports getting audio analysis for a single track. Due to this, I have to loop over N tracks and hit the get audio analysis for a single track API each time.

**Comment by hughrawlinson** [comment]
Hi @mkmoisen - the response size for audio analysis is already pretty large, so adding multiple together probably isn't feasible. Besides, looping over tracks allows you to parallelize your requests, speeding up your overall download time :)

I'm always very interested in uses of our audio analysis endpoint - are you working on something cool?

**Comment by mkmoisen** [comment]
Hi @hughrawlinson - Thanks for the response. I am attempting to split my giant playlist into smaller playlists based on various metrics, for example on BPM. Moreover I have a different playlist that is a smaller subset of the bigger playlist, which I prefer more. I want to compare the metrics in the smaller playlist against the bigger playlist to see if there are any statistical patterns as to why I prefer it.

**Comment by hughrawlinson** [comment]
That sounds like an awesome use of the tech! Have you already tried Audio Features and decided you need more detail?
