### ISSUE TITLE
Device ID inconsistent

### ISSUE THREAD

**Issue by rlingineni** [spotify/web-api#696]
Issue found on February 19th 2015.

#### Endpoint(s):
* `GET /v1/me/player/devices`

#### Scope(s):
* Necessary Ones

#### Expected behavior:
Device ID not consistent.

#### Actual behaviour:
Device ID returned is different every time although the device is the same. When a client device disconnects and reconnects, is a new device ID expected behavior?

**Comment by rlingineni** [comment]
When a Connected Device is disconnected, how often does it take to get removed from the API Endpoint?

**Comment by arirawr** [comment]
Yes, this is expected behaviour. You can call the ‘available devices’ endpoint before you do a playback transfer to confirm the current device id of a device. Hope that helps! Let us know if you have any further questions 😄
