### ISSUE TITLE
Documentation should clarify that timestamp is returned as Milliseconds

### ISSUE THREAD

**Issue by bichotll** [spotify/web-api#698]
Issue found on October 20th 2017.

#### Scope(s):
https://developer.spotify.com/web-api/get-information-about-the-users-current-playback/
and similar pages.

`timestamp` is described as normal timestamp. It can be a bit confusing as it's actually a Unix milliseconds timestamp.
A rectification/clarification will avoid any future confusion.
In my case I'm working in a precision based player, and that confused me as normally timestamps are shown as just seconds (which is the standard).
It may sound silly, but this really confused me and took me a bit of time to find out what it was going on.

I presume that what you are returning is what in javascript would be a .getTime() of a Date object, which, again, is not an actual Unix timestamp.

#### Expected behaviour:
Description field should clarify that the timestamp is returned in Milliseconds.
![image](https://user-images.githubusercontent.com/643359/31816700-33cc73f0-b589-11e7-9a02-4d3f10b293e7.png)

#### Actual behaviour:
The timestamp field claims it's a timestamp.
![image](https://user-images.githubusercontent.com/643359/31816667-159cb3ea-b589-11e7-91d9-ee97492a93d0.png)

**Comment by tinyioda** [comment]
While I don't disagree that the documentation could use an upgrade... this is in the user guide (https://developer.spotify.com/web-api/user-guide)

Timestamps
Timestamps are returned in ISO 8601 format as Coordinated Universal Time (UTC) with zero offset: YYYY-MM-DDTHH:MM:SSZ. If the time is imprecise (for example, the date/time of an album release), an additional field will show the precision; see for example, release_date in an album object.

**Comment by mmontag** [comment]
Good feedback! Timestamp docs should always include a unit. @hughrawlinson

**Comment by arirawr** [comment]
Thanks for the feedback! We've updated this in the documentation.
