### ISSUE TITLE
Conditional requests not working due to missing "Last-Modified" headers

### ISSUE THREAD

**Issue by triplef** [spotify/web-api#7]
We’re trying to use conditional requests for the Web API as [documented on your website](https://developer.spotify.com/web-api/user-guide/#conditional-requests). However it seems that the "Last-Modified" header is never set in API responses, and using the "If-Modified-Since" header in requests does not seem to have any effect either.

**Comment by thelinmichael** [comment]
Thanks @triplef. We'll have a look into this.

**Comment by JMPerez** [comment]
Hi @triplef . We have just rewritten the [Condition Requests section in the User Guide](https://developer.spotify.com/web-api/user-guide/#conditional-requests) to describe our current approach to response headers. We are currently working on fine tuning them, but in general they will be either cached using cache-control for some time, or conditionally cached using ETags.
