### ISSUE TITLE
Question: Rate limit for /me/player/currently-playing

### ISSUE THREAD

**Issue by terhuerne** [spotify/web-api#701]
Hi there,

I was wondering if there is an actual rate limit for the currently playing endpoint. My usecase is to build an application that displays the currently playing track on a panel. Is it suitable to check for the currently playing track every 5 or so seconds or will I hit the rate limit sooner or later with such heavy pulling? These short intervals are needed if a user changes the song. I want to have an immediate notification about this change to update my UI.

Thanks,
Johannes

**Comment by jscholes** [comment]
Related: #644, #492.

**Comment by hughrawlinson** [comment]
Hi - Thanks for getting in touch! All our endpoints are behind a rate limit. You should use the rate limit headers to manage your requests so that you don't hit the limits. We're aware that real time playback notifications is a widely requested feature, and will update on #492 if we have any news.
