### ISSUE TITLE
Get a playlist does not respect "fields" query param 

### ISSUE THREAD

**Issue by goldensunliu** [spotify/web-api#703]
**Get a playlist does not respect "fields" query param**   

Issue found on 10/25/2017.

* `GET /v1/users/{user_id}/playlists/{playlist_id}`

#### Steps to reproduce:
1. Open the API Console
2. Call the `get-playlist` endpoint with `user_id`=`spotify`, `playlist_id`=`37i9dQZF1DWXnexX7CktaI` and `fields`=`fields=description,uri`
![image](https://user-images.githubusercontent.com/1348993/32055649-66e20e98-ba30-11e7-8648-1e1707b34856.png)

#### Expected behaviour:
The response should be just the playlist's description and URI: according to https://developer.spotify.com/web-api/get-playlist/

#### Actual behaviour:
The response always return the full playlist object.

#### Important note
Based on the API spec posted here https://github.com/spotify/web-api/blob/master/specifications/raml/api.raml#L478
It also does not include the "fields" query param.

**Comment by jscholes** [comment]
You're including the parameter name and equals sign in the value of the fields parameter.  To fetch just the playlist description and URI, the fields parameter should be set to "description,uri", not "fields=description,uri".

    $ curl -X GET "https://api.spotify.com/v1/users/spotify/playlists/37i9dQZF1DWXnexX7CktaI?fields=description,uri" -H "Accept: application/json" -H "Authorization: Bearer <token>"
    {
      "description" : "Jams from the past and present. Cover photo: Bruno Mars",
      "uri" : "spotify:user:spotify:playlist:37i9dQZF1DWXnexX7CktaI"
    }

**Comment by jscholes** [comment]
Here's an [Example Web API Console request](https://developer.spotify.com/web-api/console/get-playlist/?fields=description%2Curi&user_id=spotify&playlist_id=37i9dQZF1DWXnexX7CktaI).

**Comment by goldensunliu** [comment]
@jscholes +++. thanks! The doc might be a little confusing.

**Comment by nordwars** [comment]
Confusion arises from the documentation page: https://developer.spotify.com/documentation/web-api/reference/playlists/get-playlist/

This page has a button "Example (get selected fields of a playlist)", which links to the API console/tester with pre-filled values. The URI link it provides is:

`https://developer.spotify.com/console/get-playlist/?playlist_id=59ZbFPES4DQwEjBpWHzrtC&user_id=spotify&fields=fields%3Dhref%2Cname%2Cowner%28%21href%2Cexternal_urls%29%2Ctracks.items%28added_by.id%2Ctrack%28name%2Chref%2Calbum%28name%2Chref%29%29%29`

This contains a pre-filled value for "fields": 
`fields=href,name,owner(!href,external_urls),tracks.items(added_by.id,track(name,href,album(name,href)))`

This pre-filled value is incorrect, as it results in fields=fields%3D<field list>, which doesn't work (fields mentioned twice). This is not obvious to all but the most observant users.

The "Example (get selected fields of a playlist)" link on documentation page https://developer.spotify.com/documentation/web-api/reference/playlists/get-playlist/ should be fixed, something like this:

`https://developer.spotify.com/console/get-playlist/?playlist_id=59ZbFPES4DQwEjBpWHzrtC&user_id=spotify&fields=href%2Cname%2Cowner%28%21href%2Cexternal_urls%29%2Ctracks.items%28added_by.id%2Ctrack%28name%2Chref%2Calbum%28name%2Chref%29%29%29`
