### ISSUE TITLE
Thanks for Sharing is shown when cancelling Facebook song share

### ISSUE THREAD

**Issue by bstolarz** [spotify/web-api#704]
Issue found on October 28th, 2017. Mac OS El Capitan. Chrome Browser 

#### Scope(s):
* Share song to Facebook

#### Steps to reproduce:
1. Open the Mac OS Spotify app
2. Go to any song, click on the "..." options
3. Select Share->  to facebook
4. Once in the browser (such as Chrome), click on the "X" or in Cancel button

#### Expected behaviour:
Window should be closed or some Spotify page should be shown.

#### Actual behaviour:
"Gracias por compartir " (Spanish of Thanks for sharing) page is shown. Evidence-> [https://imgur.com/wZ2tb5d]

**Comment by hughrawlinson** [comment]
Hi! It seems like this is a bug report for one of the Spotify clients. Thanks! I’ll pass it on to the engineers who work on it, but this forum is for feature requests and bug reports on our Spotify Web API, and as this issue is out of scope for the forum, I’ll close it.
