### ISSUE TITLE
Random 500 errors when some songs are played using the playback API

### ISSUE THREAD

**Issue by andywong418** [spotify/web-api#706]
Title: Random 500 errors when some songs are played using the playback API

Issue found on October 28th 2017.

We created our own queuing system to play songs added dynamically to a playlist, but 10% of the time the songs don't play and we get a 500 internal server error.

Endpoint(s):
* `PUT /v1/me/player/play`

Scope(s):

user-modify-playback-state
playlist-modify-public
user-read-playback-state

Expected behaviour:
A user adds a song to a created playlist, our queueing system places it on the queue and each song plays when next song is called via web sockets.

Actual behaviour:
As mentioned most of the songs do play but occasionally when we go to the play endpoint the songs don't play and we get an internal 500 error.

**Comment by hughrawlinson** [comment]
Hi @andywong418 - I'd recommend implementing retries with exponential backoff for this one. We'll continue to fix bugs as we find them, but as this API relies on communication with a third device, it's definitely a good idea to cover some failure cases.
