### ISSUE TITLE
Please add Currently Playing Track for public Playlist

### ISSUE THREAD

**Issue by ayinmursalin** [spotify/web-api#707]
is there is a way to get currently playing track on a user playlist

from https://developer.spotify.com/web-api/console/get-playlist-tracks/

it endpoints are : `v1/users/{user_id}/playlists/{playlist_id}/tracks`

and i get the track list on my public Playlist

```

```

i see this : https://developer.spotify.com/web-api/console/get-users-currently-playing-track/

but endpoints are` v1/me/player/currently-playing`

it says `/me/`, so i can't get what currently playing on my public Playlist
```

```
i wish there is endpoints like `v1/users/{user_id}/player/currently-playing`

```

```

why i need it ? because my App(let's say Music Cafe) have a public Playlist to let any user add a track on it, and know what is track currently playing on that Playlist

**Comment by jscholes** [comment]
If I understand you correctly, you're asking for an endpoint which allows you to determine what other users are currently listening to.  This has all sorts of privacy and security implications and, while I don't represent Spotify in any capacity, I can't see this happening any time soon if ever.  After all, the Web API still doesn't even support collaborative playlists.

If you want this functionality, you'll have to build it yourself by allowing users to authorise inside your app, and then pulling down their currently playing information.  Please make it clear to everyone though that this is what you're intending to do, and ignore any currently playing information if the context doesn't correspond to your playlist.

**Comment by arirawr** [comment]
Hi @ayinmursalin -

The concept of "currently playing" only applies to *users*, not to playlists. Several users could be playing the same playlist at the same time and have entirely different currently playing tracks.

For your use case, it seems you would just need to get the currently playing track for the user that is logged in and actually controlling playback in the app. You need to authenticate that user, and then use the `/me/player/currently-playing` endpoint.

As @jscholes mentioned, if you want to get currently playing information for users, you need to authenticate those users through your app using one of our [authorization flows](https://developer.spotify.com/web-api/authorization-guide/).

**Comment by ayinmursalin** [comment]
i mean.

let says i have an Account for Public Playlist (e.q. Music Cafe)
and i used this playlist to be plays in my Cafe

i wanna build an app that user can login with his account, but can add a track on my Playlist, and they now what song is currently play.

**Comment by jscholes** [comment]
I understand what functionality you're trying to create - you want a jukebox-style system so people can choose their own music.  However, the implementation you describe is currently not possible.  You would need to create an application which would:

1. Authorise with the Spotify Web API as you;
2. Provide a user interface for people to perform searches and add their chosen songs to your playlist.

This sort of functionality has already been requested previously, for example in issue #462.  You wouldn't be able to allow people to do this from the Spotify applications on their smartphones (although I think such a system would be open to abuse anyway).

One final note: This is not to be taken as legal advice, and you should seek out your own legal counsel.  However, publically playing back Spotify content on business premises may violate Spotify's personal account terms and conditions.

**Comment by jpiepkow** [comment]
@ayinmursalin  random I came across this but I built https://spin.social for exactly your example usecase.. although a tad hacky and I have not touched it in 6 months it should still work.
