### ISSUE TITLE
docs: currently playing returns a 204

### ISSUE THREAD

**Issue by zmb3** [spotify/web-api#708]
#### Endpoint(s):
* `GET https://api.spotify.com/v1/me/player/currently-playing`

#### Expected behaviour:
The [docs](https://developer.spotify.com/web-api/get-the-users-currently-playing-track/) for the currently playing endpoint mention only 200 or 202 as valid response codes.  If there is not an error I would expect either a 200 or 202.

#### Actual behaviour:
When nothing is playing, the API actually returns a 204 (which is totally reasonable).

Should the docs be updated?  It seems like we need to s/200 OK/204 No Content/ here:
> When no available devices are found, the request will return a `200 OK` response but with no data populated.

**Comment by arirawr** [comment]
Hey @zmb3 - thanks for the report! We've updated the documentation to be more clear on this.
