### ISSUE TITLE
Audio Analysis API output is truncated for some IDs

### ISSUE THREAD

**Issue by franciscoaraposo** [spotify/web-api#709]
Hi,

I've been using the Spotify audio analysis API. However, for some IDs, the output is truncated, i.e., I can't retrieve all of the information that I need.

The ID list is the following:

55JBawJRzYIsYMLBxi2AGC
5Nb6txEq65b9UfeplVF2a8
5ou59ERA2f7ffyAxAcZyVz
73Mfgc0HTZeNCoNrDI46sJ
4BWtaaeVIRsR5HgLfuJAB9
6T38YYdc9GkLO07TRI3li2

I hope you can fix this bug soon.

Thanks in advance,
Francisco

**Comment by franciscoaraposo** [comment]
Update: I was able to find different IDs for 5 of those 7 in the list. However, 2 of them are unique in Spotify's database and, therefore, I'm still missing the data:

5Nb6txEq65b9UfeplVF2a8
6T38YYdc9GkLO07TRI3li2

**Comment by arirawr** [comment]
We've been able to reproduce this and are looking into it. Thanks for the report!

**Comment by arirawr** [comment]
Hi again, 

We’ve resolved the truncation for the tracks that you listed and we’re working on a broader fix for any other tracks with malformed analysis. We should have the issue fully resolved in the coming weeks.

Thank you for your report - you help us make the Spotify Platform even better! 🎉
