### ISSUE TITLE
502 Bad gateway on /search

### ISSUE THREAD

**Issue by Jleagle** [spotify/web-api#711]
I was trying to find a way to retrieve a random track, so i was searching for "a OR e OR i OR o OR u", but kept getting timeouts, presumably because it has to scan through nearly every track on Spotify. It seems to work fine if i use a different type value (not track). Other searches seem to have similar results such as `"*a*"`.

#### Date
Issue found on November 1st 2017.

#### Endpoint(s):
/v1/search

#### Scope(s):
No extra scopes, just regular auth

#### Steps to reproduce:
1. curl -X GET "https://api.spotify.com/v1/search?q=a+OR+e+OR+i+OR+o+OR+u&type=track&limit=1&offset=0"

2. curl -X GET "https://api.spotify.com/v1/search?q=*a*&type=track&limit=2&offset=0"

#### Expected behaviour:
Return the results

#### Actual behaviour:
502 Error (consistently)

**Comment by jscholes** [comment]
As per the [docs for the search endpoint](https://developer.spotify.com/web-api/search-item/):

> Only one OR operator can be used in a query.

The Web API should probably return a 400 Bad Request response in this case rather than a 502, but this search still wouldn't work.

**Comment by Jleagle** [comment]
Thanks, i didnt realise as using two for me actually does work, tested using "a OR b OR c"

**Comment by arirawr** [comment]
Hi @Jleagle - the Search endpoint is not designed for those kind of queries and will time out. 

For your use case (which is similar to this one: #216), you could try "randomising" the letter you search on your app's side, then randomise the offset you ask for, ie. `curl -X GET "https://api.spotify.com/v1/search?q=yourRandomLetter&type=track&offset=yourRandomOffset"`
