### ISSUE TITLE
Retrieve number of times the current user has played a track

### ISSUE THREAD

**Issue by yohanboniface** [spotify/web-api#712]
Hi!

I think this is different from #70.
Is there a way to know how many times I've played a given track?

Context: to discover new music, I put a lot of tracks/albums in a "holdall" playlist. I'd like to automatically (with a script I mean) remove from that playlist the tracks I've already listened x times.

Thanks :)

**Comment by hughrawlinson** [comment]
Hi! Thanks for the feature request. We'll consider it.

**Comment by tonydrake** [comment]
This is the feature I'm looking for too.  I'm just interested in how many time the 'logged in' user has played a song... so perhaps an API on the ../me/tracksplayed etc.... listing all the tracks I've played, and a sub-list /me/tracksplayed/trackplayhistory showing each play event and device.

**Comment by alexing10** [comment]
I'd love this feature too!

**Comment by arirawr** [comment]
Hey all,

As per our [new developer support process](https://github.com/spotify/web-api#creating-an-issue), any feature requests that have no plans to be considered in the next 6 months will be closed as wontfix.

We do not have any plans to implement this in the next 6 months and thus will close as wontfix.

We encourage you and other members of the community to continue to share use cases and your support for this feature, as it helps us prioritize features going forward. You will be able to comment on this issue even after it is closed. We will also post any updates here relating to this suggestion when they happen.
