### ISSUE TITLE
Preview URL are null when authenticated with Client Credentials Flow

### ISSUE THREAD

**Issue by greencoppercompany** [spotify/web-api#713]
Issue found on November 7th 2017.

#### Endpoint(s):
* `GET /v1/artists/{id}/top-tracks`

#### Steps to reproduce:
1. Implements '[Client Credentials Flow](https://developer.spotify.com/web-api/authorization-guide/)'
2. Compute the request for the artist id: 4MAvEYtgY8yNljGP697n4F and country 'US' (Think about the header to add as explained in the documentation Client Credentials Flow)
3. Check the JSON received

#### Expected behavior:
Preview_urls should be accessible this way.
Sample:
`...
"name" : "Frei zu sein",
"popularity" : 26,
"preview_url" : "https://p.scdn.co/mp3-preview/5cd93e1ebfbf58b62e65cfc92f6a542d723f00dd?cid=7e91af2342ad4d619950799f466cde20",
...`

#### Actual behaviour:
Preview_urls are null.
Sample:
`...
"name" : "Frei zu sein",
"popularity" : 26,
"preview_url" : null,
...`

**Comment by arirawr** [comment]
As documented, the preview URL can be null. This can happen for a variety of reasons related to licensing restrictions or technology. Your app should handle the possibility that a clip is not available.
