### ISSUE TITLE
Search only returns a result when a specific market is given (in some cases)

### ISSUE THREAD

**Issue by mschwebler-tgm** [spotify/web-api#714]
Issue found on February 19th 2015.
I encountered the issue with some tracks. Described example is 'Kraftklub - Hand in Hand'

#### Endpoint(s):
* `GET /v1/search`

#### Scope(s):
* None (application is not using authentication)

#### Steps to reproduce:
1. Create GET request
2. Call the `search` endpoint with `query=artist:Kraftklub+track:Hand+in+Hand&type=track&limit=1`
3. Result has no items (`[]`)
4. Append `&market=AT` to your request
5. et voilà, you got your requested track

#### Expected behaviour:
As I didnt find any documentation about default markets I would assume that the track is found if it is in the database - no matter in which country it is available or not. However the result is empty.

#### Actual behaviour:
Request returns empty list of tracks

**Comment by hughrawlinson** [comment]
Hi @mschwebler-tgm - all apps require authentication now, so if the request is responding with an HTTP status of 200, you must be including an access token. By default, the search API endpoint uses the market associated with your access token. You can, of course, change market with the `market` parameter as you found. I'm not sure which market your token is associated with, but it's likely that track isn't available in the default market, and isn't showing up until you set the `market` parameter to a market in which the track is available.
