### ISSUE TITLE
add enpoint to get albums by record label

### ISSUE THREAD

**Issue by goeddea** [spotify/web-api#716]
I'm a bit of a maniac when it comes to browsing music, and wanted to develop a tool which helps me better stay current about new releases. This would run on node.js and be open source.

This would monitor new releases using your Web API and create playlists from these, e.g. create a folder "releases_2017_week_20", with all relevant new releases as individual playlists within this.

Relevance would be determined by two lists:
		○ artists I find interesting
		○ record labels I find interesting

Looking at the Web API endpoint reference (https://developer.spotify.com/web-api/endpoint-reference/) I do not see an endpoint which would give me the albums/releases for a record label.

The meta-data for label is there - and I can search for "label" using the Spotify client. (In fact, this is why I switched from Deezer, where this is not possible.)

Could you please add an endpoint to request albums by label?

**Comment by hughrawlinson** [comment]
Hi! You can do this using the search API using a parameter like `q=label:Sony`. Hope that helps!

**Comment by goeddea** [comment]
Thanks! Will give that a try.

**Comment by mecanographik** [comment]
Hi,
Did you manage to build something to get Label’s album release? I would need to test it on my webApp 🤟🏻Thanks
