### ISSUE TITLE
'/v1/me/player' occasionally returns empty string

### ISSUE THREAD

**Issue by tinyioda** [spotify/web-api#717]
Hi Everyone,

Occasionally the endpoint '/v1/me/player' returns an empty string rather than an error or valid response. 

It happened a few minutes ago. All day I had been listening to music in my car on a long drive; tonight when I booted the personal (UWP) client I'm working on and I started receiving an empty string causing an exception in my app (I get that the exception is my own fault, I was only looking for error codes or valid responses not an empty string). I tried generating a new token by logging in again and still an empty string. I knew exactly how to fix it - I used the real client and played just a second or two of a song, tried my client again and it started returning a valid response from the endpoint. 

I know that's not a lot to go on, but I have definitely seen it more than once as I knew exactly what to do to resolve the issue.

Issue found on November 11th 2017 

#### Endpoint(s):
* `GET /v1/me/player`

#### Scope(s):
* user-read-playback-state

#### Steps to reproduce:
Unable to easily reproduce but I've definitely seen the issue more than once.

#### Expected behaviour:
A public user object as described on `https://developer.spotify.com/web-api/get-information-about-the-users-current-playback/`.

#### Actual behaviour:
Empty string returned from endpoint

**Comment by hughrawlinson** [comment]
Hi! As [documented](https://beta.developer.spotify.com/documentation/web-api/reference/player/get-information-about-the-users-current-playback/),

> When no available devices are found, the request will return a `200 OK` response but with no data populated.

Your code should take an empty response to `GET /v1/me/player` to mean that no active devices were found.

Hope that helps!
