### ISSUE TITLE
Check if mobile device will use native Spotify app for authentication?

### ISSUE THREAD

**Issue by lrholmes** [spotify/web-api#718]
Had a user email me earlier stating they couldn't log into my web app on mobile. The issue turned out to be a new feature (new to me, anyway) that causes Safari on iOS to redirect to the native Spotify app for authentication. This is actually pretty cool, however it totally broke the popup auth flow that I had implemented (I think the popup window gets closed during the process and then a new one opened after? Either way, communication with the callback page is lost).

Would it be feasible to check somehow what authentication route the browser will use? Or maybe a query parameter we could add to the login url to prevent the in-app authentication in the meantime? At the moment it seems like to fix this issue I'm going to have to broadly check for a mobile sized viewport and then use a simpler method of handling the login flow (a detriment to any mobile user without the Spotify in-app auth option).

Thanks!

**Comment by lrholmes** [comment]
Just came up with a workaround that retains the same flow as before and works with the new app-based authentication. Instead of posting messages to the popup, I'm checking for changes to localStorage where the token is stored. This seems to work well, and in the same way as before, will close the issue.

**Comment by dvidal49** [comment]
Hello,
I have the same issue as you.
Can you explain in detail how you went around the problem because I do not understand your explanation?
Thanks to you.

**Comment by lrholmes** [comment]
Sure. So the way that I was doing authentication was to open a popup that went to Spotify's auth, which then redirected to my callback url with the code. At the same time my root page, the page that the user clicked to log in, was polling that popup by sending a message. When the user is redirected back to my app at the callback url, the callback view listens for one of these messages, and responds to it with the code. The root page then has the auth code and can close the popup window, and exchange the code for an access token.

That was working until the change outlined in this issue. As a workaround, I added a timeout on the callback page that basically waits a second or so (longer than the time it takes to receive the message from root window, indicating that the communication with that page is lost), and then instead exchanges the code for an access token in the popup, saves it to localStorage, then the popup closes itself.

Now in the root page it both sends a message to the popup and checks for a token in localStorage every second. If there is a response from the popup, it'll continue as normal, and if it detects a token in localStorage, we're already logged in so I update the state to reflect that.

Hope this helps. I should say that I don't think this is the most ideal method of handling it, but my app was broken so went with the first solution that worked. I'll probably go back and optimise it slightly, but I can say that this does work. The reason is that localStorage is shared across any instance of your page in the browser, and updates dynamically, so you can make use of that in place of communicating with the popup directly.

Any q's, let me know.

Additionally let me know if you think I should reopen the issue - I closed it because I came up with a workaround but it isn't ideal.

**Comment by lrholmes** [comment]
Ah, I didn't realise that was an issue as I've not tested with Chrome on iOS. Thanks for pointing that out.

And yes, your other point about in-app browsers is absolutely true, my auth method relies on a multi-tab browser so will fail there. I should rethink how I handle it in those cases.

I'll reopen the issue as you suggested, as it would be nice to get some clarification on how this works / if there is any way for us to disable the behaviour. Chrome -> Spotify -> Safari seems like a definite bug.

**Comment by hughrawlinson** [comment]
Hi! This is an ongoing issue with Chrome on iOS. We're looking into a solution at the moment, and we'll keep you updated on this issue.

**Comment by dvidal49** [comment]
Thank you Hugh!
For info, there is the same issue if you are on an app on the internal browser of the Facebook application on iOS = redirect to Safari

**Comment by Momics** [comment]
4 of my iOS users are experiencing a similar issue. Seems to be the same issue for Chrome and Safari... It could also be my app. I have a MeteorJS application with a OAuth "login with spotify" flow. This is the (faulty) flow my users are experiencing:

- User navigates to my webapp
- User presses my "login with spotify" button
- The native app opens and shows a checkmark
- The native app redirects to a new safari tab without being logged in

Not sure if this is a faulty implementation of Oauth for my app or a bug in the spotify native app. But all other users (that do not get redirected to the native app) aren't experiencing any issues.

**Comment by Momics** [comment]
Hi all, this seems to be fixed in the latest Spotify iOS app update. Thanks and good job!

**Comment by hughrawlinson** [comment]
Hi - as @Momics mentioned, this issue is now resolved :)

**Comment by enkota** [comment]
@lrholmes is this still working for you? When testing with [this example](http://jsfiddle.net/JMPerez/j1sqq4g0/), it will only open in the safari browser and not authenticate via the mobile app.
