### ISSUE TITLE
Receiving 400 error when making recommendations request using diverse set of seeds

### ISSUE THREAD

**Issue by getmicah** [spotify/web-api#719]
Issue found on November 14th 2017.

#### Endpoint(s):
* `GET /v1/recommendations`

#### Scope(s):
* playlist-modify-public (using auth code flow)

#### Steps to reproduce:
1. User selects some (n < 5) artist and track seeds that are quite different (usually time period)
2. GET /v1/recommendations (400 Bad Request)
3. Remove some of the seeds
4. GET /v1/recommendations (200 OK)
5. Remove all seeds
5.  Add some more seeds that previously produced the 400 error
6. GET /v1/recommendations (200 OK)

#### Expected behaviour:
A more helpful error message to see what exactly the problem is.
The only message I get from the web-api is "400 Bad Request".
I'm thinking it's because the api can't get any recommendations based on the given seeds.

#### Actual behaviour:
400 Server Error (sometime)

**Comment by hughrawlinson** [comment]
Hi @getmicah - can you please list the seed combination that caused the 400 error so that we can reproduce the issue?

**Comment by arirawr** [comment]
Closing this issue as we haven't been able to reproduce the behaviour. Feel free to reopen with reproduction steps if you are still seeing the issue!
