### ISSUE TITLE
"Player" endpoints give 400 error when playing a locally downloaded song

### ISSUE THREAD

**Issue by charredgrass** [spotify/web-api#721]
Issue found on November 16th 2017.

#### Endpoint(s):
* `GET /v1/me/player`

#### Scope(s):
* "user-read-playback-state"
* "user-read-currently-playing"

#### Steps to reproduce:
1. Play a song that has been imported to Spotify using a file stored on the computer.
2. Using the valid authorization code for the account that is playing the song, call `GET /v1/me/player` or `GET /v1/me/player/currently-playing`.

#### Expected behaviour:
A response code of 200, 204, or 202

#### Actual behaviour:
A response of:

``` json
{
  "error" : {
    "status" : 400,
    "message" : "invalid id"
  }
}
```

It should be noted that I can call `GET /v1/me/player` and get a *valid* response with the exact same call if I am playing another song, but switching to a song I've imported through a local file and calling this endpoint will give me a 400 error.

**Comment by hughrawlinson** [comment]
Hi! The connect Web APIs cannot return information about local tracks as the metadata is stored only in the client. Very open to feedback on how you'd expect the API response to look in this case 😄

**Comment by charredgrass** [comment]
I was under the impression that a 400 error would be returned only for bad requests, regardless . I think that calling `/v1/me/player/currently-playing` should return a 200 response that states in the body that the track data is unavailable.  In my opinion, a 400 error is not appropriate here because it doesn't really communicate the problem.

However, it doesn't really matter for me, since I know that the 400 response will likely be because of a local track, it was just confusing for me at first. Thank you for responding to my issue.

**Comment by BloodShura** [comment]
The documentation says:

> When **no track is currently playing**, the request will return a **204 NO CONTENT** response with no payload. A **202 ACCEPTED** response with no payload can be returned **if no information about the currently playing track is available**.

So, I think it's actually an error that this endpoints returns a **400 Bad Request** if the user is playing a local file, because this HTTP error code is generally used for when the request is malformed/with missing required fields/etc, and not for representing a specific state of the system.

If this behavior won't be changed, then at least the docs should be updated with information about it.

**Comment by xzion** [comment]
BloodShura is spot on, it would be nice to see the endpoint behaviour accurately follow the documentation, or otherwise have the documentation updated to reflect the current behaviour. 

@hughrawlinson please consider re-opening this issue.
