### ISSUE TITLE
The recently played endpoint is not reporting new plays

### ISSUE THREAD

**Issue by mattruzicka** [spotify/web-api#724]
Issue found on November 22nd 2017

#### Endpoint(s):
* `GET https://api.spotify.com/v1/me/player/recently-played`

#### Steps to reproduce:
1. Listen to a track on Spotify
2. Make a request to the recently played endpoint

#### Expected behaviour:
The song will be in the list of recently played tracks

#### Actual behaviour:
I only see my recently played tracks from yesterday

****

**Comment by mattruzicka** [comment]
It's working again. Thanks.

**Comment by mattruzicka** [comment]
I'm seeing this issue again. Looks like the ```https://api.spotify.com/v1/me/player/recently-played``` endpoint is down

**Comment by hughrawlinson** [comment]
Hi @mattruzicka - we'll have a look into it. Thanks for reporting it!

**Comment by hughrawlinson** [comment]
Hi @mattruzicka - it looks like there was a problem with one of our systems that is resolved now. Please ping me if you see this behavior again!

**Comment by xavierliancw** [comment]
This endpoint is 404'ing. I'm looking at beta.developer.spotify.com and it seems that this endpoint's reference is missing from the documentation. Did you guys remove it?

**Comment by arirawr** [comment]
@xavierliancw Here is the reference for this endpoint on the beta site: https://beta.developer.spotify.com/documentation/web-api/reference/player/get-recently-played/

**Comment by mattruzicka** [comment]
I'm seeing this issue again @hughrawlinson

**Comment by mattruzicka** [comment]
Okay, it's working again.

**Comment by mattruzicka** [comment]
I'm seeing this issue again @hughrawlinson

**Comment by asarendt** [comment]
Hi I'm seeing the above issue again today.]

**Comment by asarendt** [comment]
Hey all, I am seeing this issue again this morning. My last reported play was 15 hours ago.
