### ISSUE TITLE
Playlist search for AC/DC gives 502 - Bad Gateway

### ISSUE THREAD

**Issue by michaelherger** [spotify/web-api#725]
Issue found on November 23th 2017.

#### Endpoint(s):
* `GET /v1/search`

#### Steps to reproduce:
1. Open the API Console
2. Call the `search` endpoint with query set to `AC/DC`, type `playlist`

#### Expected behaviour:
Instead of playlists for this artist I'd get an error 502.

#### Actual behaviour:
502 Bad Gateway (consistently)

```
curl -X GET "https://api.spotify.com/v1/search?limit=5&market=US&q=ac%2Fdc&type=playlist" -H "Accept: application/json" -H "Authorization: Bearer-xxx"
{
  "error" : {
    "status" : 502,
    "message" : "Bad gateway."
  }
}
```

**Comment by hughrawlinson** [comment]
Hi! We'll look into it, thanks for reporting!

**Comment by arirawr** [comment]
Thanks again for the report! I'm going to close this in favour of #140 - which covers a broad range of special character searches.
