### ISSUE TITLE
player/play plays the currently paused track instead of playing the specified uri 

### ISSUE THREAD

**Issue by jacobfrank96** [spotify/web-api#726]
Issue found on November 24th 2017.

#### Endpoint(s):
* `PUT /v1/me/player/play`

#### Scope(s):
* user-modify-playback-state

#### Steps to reproduce:
When I click "try it" on the spotify web api website it works and my spotify desktop player plays the specified song. Here is the cURL request the website provides:

`curl -X "PUT" "https://api.spotify.com/v1/me/player/play" --data "{\n  \"context_uri\": \"spotify:album:5ht7ItJgpBH7W6vJ5BqpPr\",\n  \"offset\": {\n    \"position\": 5\n  }\n}" -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: Bearer BQA6bdbPmdIvhAUykMfnOf8ByURH7mECcd1NvnYPPavh85SOUwochbWj_fibxfULhsPQPhA44CvgbBTRpjeKb7N1AqM-P1kVmsi867cmDyLvw70I0w2Nytu-5HVdC9m91zgFZI7kjQGLLDcTMeExaQz4LSKdM5zWl1VKK7eg_kS_01gIbIZTgdinTP1vhfQr-ax2y7USCJIBn2HRuK1xyh3riyl_8668g3u_Bkw8SDK-o1dXFdoJfGEk-Ja8aMeoKun4WA1RyCX7sQQ2oQ"
`

However, when I try to implement it on my website it just resumes play on whatever was currently paused on my desktop but does not play the song specified in the uri. I'm not sure if my ajax request is incorrect or not but it is returning with a success. 

here is my javascript code:

app.playTracks = () => $.ajax({
    url:  'https://api.spotify.com/v1/me/player/play',
    headers: { 'Authorization': 'Bearer ' + access_token },
    method: 'PUT',
    dataType: 'json',
    body: {
        "context_uri": "spotify:album:5ht7ItJgpBH7W6vJ5BqpPr",
        "offset": {"position": 5}
      },
    success: function(result) {
      console.log("success");
      console.log(result);
    }
}
);

#### Expected behaviour:
I expect it to play the Cry, by Carly Rae Jepsen, like the "try it" example does.

#### Actual behaviour:
It doesn't play Cry, by Carly Rae Jepsen, but resumes play from whatever song I currently have paused on my Spotify desktop.

**Comment by jacobfrank96** [comment]
Also, when something if something is already playing on my desktop I get a 500 (Internal Server Error). This does not happen, however, when I do it through the "try it" button

**Comment by jscholes** [comment]
In your code:

    body: {
    "context_uri": "spotify:album:5ht7ItJgpBH7W6vJ5BqpPr",
    "offset": {"position": 5}
    },

Are you 100% sure this is being sent as valid JSON?  I'm not a JavaScript developer and have no experience with the ajax function you're using, but the API response is consistent with what happens when you haven't provided any new content to be played (i.e. the player resumes if paused and throws an error if already playing).

Perhaps have a look at [this answer on StackOverFlow](https://stackoverflow.com/questions/4159701/jquery-posting-valid-json-in-request-body).  If the requests work via curl and the Web API Console, then the error is in your code.

**Comment by seahorsepip** [comment]
Your body content should be just a JS object:
```
app.playTracks = () => $.put({
	url: 'https://api.spotify.com/v1/me/player/play',
	headers: { 'Authorization': 'Bearer ' + access_token },
	method: 'PUT',
	dataType: 'application/json',
	body: {
		context_uri: 'spotify:album:5ht7ItJgpBH7W6vJ5BqpPr',
		offset: {
			position: 5
		}
	},
	success: result => {
		console.log(result);
	}
});
```

**Comment by dukeblue2017** [comment]
I'm experiencing the same problem. Trying to play a song seems to resume playback of the paused song. Also, as mentioned above, when a song is playing, a 500 error is returned. Perhaps this is to be expected, because the user's playback status can be checked before attempting to start/resume if necessary.

**Comment by jscholes** [comment]
Hi @dukeblue2017, please post your code to demonstrate how you're making the request.  Does the endpoint work correctly if you use the Web API Console or the curl command lines it can generate?

**Comment by dukeblue2017** [comment]
I'm using Postman, but here's the cURL output it gives (stripped down a bit):

curl -X PUT \
  https://api.spotify.com/v1/me/player/play \
  -H 'authorization: Bearer <INSERT_ACCESS_CODE>' \
  -H 'content-type: application/json' \
  -d '{
	"context_uri" : "spotify:user:<USER_ID>:playlist:<PLAYLIST_ID>"
}'

**Comment by jacobfrank96** [comment]
I fixed my problem by wrapping the content in the body with jsonify()

**Comment by hughrawlinson** [comment]
Hi - looks like this issue is resolved. If I've misread, please feel free to reopen this ticket or to ping me!

**Comment by hughrawlinson** [comment]
Also, I absolutely approve of the example track ID. We're massive fans of Carly Rae Jepsen in the Spotify Platform team. 👩🏻‍🎤
