### ISSUE TITLE
Feature request. Plz add visualization... like winamp?

### ISSUE THREAD

**Issue by Dudemx** [spotify/web-api#727]
In the old internet days winamp had plug ins that added visualization to the music, heck, even the xbox had visualization. I'm using spotify on my ps4 and in parties or just alone staring at a picture of the song-album can be a little dull... just a suggestion.

Thanks foe reading this

**Comment by jscholes** [comment]
Hi @Dudemx, this issue tracker pertains to Spotify's Web API, used by developers.  If you want to make a feature request relating to a Spotify client or app, you can [do that here](https://community.spotify.com/t5/Idea-Submissions/idb-p/ideas_submissions).

**Comment by Dudemx** [comment]
Ok ty

**Comment by arirawr** [comment]
@jscholes is correct - please submit the request to the [Spotify Community Ideas](https://community.spotify.com/t5/Idea-Submissions/idb-p/ideas_submissions) :)
