### ISSUE TITLE
Invalid Client credentials in JSON

### ISSUE THREAD

**Issue by AL3X1** [spotify/web-api#728]
Issue found on February 19th 2015.

#### Endpoint(s):
* `/api/token`

Hello, i have the problem. I want use Spotify Web API for C++ wrapper, and i implement all authentication methods.

When i'm use Authorization Code Flow, i receive this json:
`{"error":"invalid_client"}`

My request looks like this:
 `https://accounts.spotify.com/api/token?grant_type=authorization_code&code=-1UZWpCwDeqV6AS9j7jQDg&redirect_uri=https%3A%2F%2Fgoogle.com%2F`

I send header: 
 `Authorization: Base MmZlYWFlMFdM3NTVlNDg2ZTljYjc3ZjM5NzNmNTQ4Y2Q=:NmYwMTcyYzNlMWNhNDgxNDhiMTczMzI4ZjkwNWU4NsD= `

And, when i try Client Credentials Flow, i receive this code: 
 <body>
  <div class="head">
    <a class="spotify-logo" href="/" tabindex="-1" title="Spotify"></a>
  </div>

    <div class="container-fluid error">
      <div class="content">
        <h1 class="h1">Error</h1>
        <p>
          Oops! Something went wrong, please try again or check out our <a href="https://www.spotify.com/help">help area</a>.
        </p>
      </div>
    </div>
    <script async defer src="https://d2d1dxiu3v1f2i.cloudfront.net/496c5b7/js/error.js" sp-error=''></script>
  </body>

*Yes, it's HTML code, in browser or console, not web page *

Also, i have `400 Bad Request` HTTP Code.

But Implicit Grant Flow *works fine*.

**I read other threads with similiar problem, but this doesn't help me.**
Where is my mistake?

**Comment by jscholes** [comment]
First things first, your Authorization header is in the wrong format.  You need to prefix it with "Basic" rather than "Base".  You then need to base64 encode both the client ID and client secret together, separated with a colon, rather than encoding each and separating the base64 strings with a colon as you're doing here.  Your redirect URI then needs to exactly match whatever you have set on your Spotify Developer account.

As an aside, you shouldn't post your client ID, client secret and OAuth codes here as this is a public forum.  Even if you base64 encode them someone else can easily reverse the process.  If the values you posted above are valid credentials, I would regenerate them on the Spotify Developer site.

Try my suggestions above and let us know how you get on.

**Comment by AL3X1** [comment]
@jscholes 
Nice it works, but i have `{"error":"invalid_grant","error_description":"Invalid authorization code"}` error :(

P.S. About Client ID and secret - it's invalid, it's ok.

**Comment by jscholes** [comment]
Which authorization flow are you intending to use?  In your first comment you mention the client credentials flow, but for that you dont' need an authorization code.

Additionally, you've written your request URL in a format which looks like a GET request, with query parameters.  The request to https://accounts.spotify.com/api/token should be a POST request, with the relevant parameters sent in the body.

**Comment by AL3X1** [comment]
@jscholes 
I send a POST request, i just show parameters.

**Comment by jscholes** [comment]
Okay.  It might be best to post your code so we can see exactly what you're doing.

**Comment by AL3X1** [comment]
@jscholes 

<?php

$url = "https://accounts.spotify.com/api/token?";

$curl = curl_init($url);
$params = [
    "grant_type" => "authorization_code",
    "code" => "mHIZWo_sAsuU6ATl-JvwBw",
    "redirect_uri" => "https://google.com/"
];

$id = "client_id:client_secret";

$header = [
    "Authorization: Basic " . base64_encode($id)
];

curl_setopt($curl, CURLOPT_HEADER, true);
curl_setopt($curl, CURLOPT_POST, true);
curl_setopt($curl, CURLOPT_POSTFIELDS, http_build_query($params));
curl_setopt($curl, CURLOPT_HTTPHEADER, $header);
curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);

$res = curl_exec($curl);
print_r($res);

Here is my php code, because i'm testing requests.

**Comment by hughrawlinson** [comment]
Hi @AL3X1 - it sounds to me like you're using an access token to refresh. You'll need to use a refresh token, as obtained in the authorization code flow. Here's an [example implementation of the Authorization Code flow](https://glitch.com/~spotify-authorization-code) in Javascript. Please let me know if you need further help with this!

**Comment by 2022karanbhasin** [comment]
Im legit going crazy... I tried to use the code you shared through glitch @hughrawlinson - but it's not working :(.     response.redirect(`/#access_token=${data.body['access_token']}&refresh_token=${data.body['refresh_token']}`) This is the only line I changed. It used to be response.send('thesamelink'), but I need them to be able to get redirected etc. What do I do?!?!?
