### ISSUE TITLE
Preview URL missing with Client Credential Flow

### ISSUE THREAD

**Issue by alecpm** [spotify/web-api#729]
Issue found on November 30th 2017.

For some tracks/artists, when I make a track request with the API console I see a non `null` `preview_url` for but when using a Client Credential Flow from a server I get a `null` `preview_url` for the same query.

#### Endpoint(s):
* `GET /v1/tracks/3GxLaG1FCsY9QXacAGgwsh?market=US`

#### Scope(s):
* Client Credentials Flow

#### Steps to reproduce:
1. Open the API Console
2. Call the `tracks` endpoint with `track_id` `3GxLaG1FCsY9QXacAGgwsh`
3. Note the `preview_url`
4. Make the same request using a Client Credential Flow
5. Note the `preview_url` is now `null`

#### Expected behaviour:
The results for the two different authentication flows should be consistent.

#### Actual behaviour:
The `preview_url` value varies depending on authorization flow for some tracks.

#### Other example tracks affected:
* `2BOUrjXoRIo2YHVAyZyXVX`
* `43Vb1wOGyRfk7fsZ5ZLRH8`
* `0TCC2Kwusv749hTFrO7d9Q`

The application client id I'm seeing this issue with is `bac193759fd24ca189fc99d6083f4107`. This issue relates to #148 and specifically the comment on that issue by @feedm3.

**Comment by hughrawlinson** [comment]
Hi @alecpm - for a variety of reasons, preview URL may be null as documented. In some cases, due to licensing reasons, the preview url may only be available to logged in premium users.
