### ISSUE TITLE
500 Server Error response from Get Several Albums endpoint

### ISSUE THREAD

**Issue by thelinmichael** [spotify/web-api#73]
Specific album IDs cannot be retrieved at the same time for some specific markets. (Not affecting retrieving albums in general.)

Issue found on June 18th 2015.

Endpoint(s): /v1/albums?ids={id1},{id2}.. 
Scope(s): None (application is not using authentication)

Steps to reproduce: [Make a GET request to this URL](https://api.spotify.com/v1/albums/?ids=2xcenvf9M6ImredOcVqns1,0MdnHtSUpnSJkZ6tzpov2p,6tXeoAbvpZCYNZPMCex4MQ,79A4V4gi26YuYFD5tU7ZEJ,2kUlMcRh1vOtYjDQAHotdy,7Dh9uAr5Pv3RVs65jyRrDy,3KnJzJIjhNYr7G1VErTLH3,6DB7ORIE7kutUuoDl5S2tz,0ghFsyZKCJOpC0CtXbfS9D,14cUCy4aMykhZbIFTw7dtW,1S543Bgkd1pzNtqHrDp5bq,4QyE2i0y4nyxHsiwm6VK9V,3eWoVPAUtBO8JpwOkWpvnw,11DmTQm7WPeSXih1FPuaXL,4sgNyq4LbcoRnNhte25GPs,31Sx9uz9KqlvmX07Pvp0wN,1WPsWyV7wvMY6kHEuC1P8t,19ZjUG7r4X1T0rduCQQmOF,3ukz1aqOnagO6feYOwjUYP,1btyMKUprgzUxLeowgQ2UZ&market=NO)

Expected behaviour: Return metadata about the given albums.

Actual behaviour: 500 Server Error (consistently)

**Comment by jsimonsson** [comment]
A fix has been deployed.
