### ISSUE TITLE
404, code:-1 error when callign artist endpoint

### ISSUE THREAD

**Issue by lohriialo** [spotify/web-api#730]
Issue found on February 30th Nov, 2017.

#### Endpoint(s):
* `GET /v1/artist/64KEffDW9EtZ1y2vBYgq8T`

#### Scope(s):
* None (application is not using authentication)

#### Steps to reproduce:
1. Call https://api.spotify.com/v1/artists/4nDoRrQiYLoBzwC5BhVJzF

#### Expected behaviour: 
Should return artist data because I know artist exist at https://open.spotify.com/artist/64KEffDW9EtZ1y2vBYgq8T

#### Actual behaviour:
http status: 404, code:-1

#### Note:
Error is random, if I make the same call again, I get the data sometime and at times I don't. My script has been working just fine for the last 5-6 months, suddenly this random error on 30th Nov, no luck so far

I get random error like this:
![image](https://user-images.githubusercontent.com/4565035/33471512-c30f280c-d693-11e7-94c9-1d5af49c4f94.png)

**Comment by loonpwn** [comment]
I am also experiencing this. Running the following at the moment gives me a ~50% hit rate of the API, seems random. It's either a 404 or it gives me what I actually want.

`curl -X GET "https://api.spotify.com/v1/search?q=tania%20bowra&type=artist" -H "Authorization: Bearer {token}"`

**Comment by hughrawlinson** [comment]
Hi! It looks like we were experiencing an issue with our API that was causing some artists to 404. We think we've resolved this now. If you encounter this issue again, please feel free to reopen it or to ping me :)
