### ISSUE TITLE
On Chrome Mobile iOS, Spotify connect launch Spotify Application, then redirect to Safari ?!

### ISSUE THREAD

**Issue by dvidal49** [spotify/web-api#732]
Hi!
On my web application on mobile (using Spotify Web API), when I'm on Chrome IOS and I launch the Spotify Connect, the Spotify application is launched to authenticate and then redirect to the default browser of my mobile : Safari. Or before I stayed on Chrome. Do you have this problem and did you find a solution to stay on the starting browser: Chrome ?
Thank you for your help.

Issue found on November 2017.

#### Endpoint(s):
* https://accounts.spotify.com/authorize?client_id=' + CLIENT_ID +
              '&redirect_uri=' + REDIRECT_URI +
              '&scope=' + scope + &response_type=code

#### Scope(s):
* user-read-private user-read-email user-read-birthdate playlist-modify-public playlist-modify-private user-library-modify user-library-read user-follow-read user-follow-modify user-top-read

#### Expected behaviour:
After "Authorize", i need stay on my start browser : on Chrome.

#### Actual behaviour:
On iOS, it open Spotify Application, then it open Safari. But the Spotify Login Button was on Chrome ?

**Chrome iOS > click on Spotify Connect Button (web api) > it open me Spotify Application > and it redirect me to my Safari Browser**

**Comment by hughrawlinson** [comment]
Hi! This is an ongoing issue that we're tracking in #718. Please follow that issue for updates related to this.
