### ISSUE TITLE
404 errors on some endpoints in NZ/AU; US and EU work fine

### ISSUE THREAD

**Issue by jaedb** [spotify/web-api#733]
Issue found on December 1st, 2017.

#### Endpoint(s):
* `GET /v1/me`
* `GET /v1/browse/categories`
* `GET /v1/browse/categories/{category_id}`
* `GET /v1/browse/categories/{category_id}/playlists`
* `GET /v1/browse/featured-playlists`
* `GET /v1/browse/new-releases`

#### Scope(s):
* None (application is not using authentication)

#### Steps to reproduce:
1. Open the API Console
2. Call the `get-new-releases` endpoint from a NZ/AU based IP address (for failure)
3. Repeat as above from a EU/US based IP address (for success)

#### Expected behaviour:
[Cursor-based paging object](https://developer.spotify.com/web-api/object-model/#cursor-based-paging-object)
```
{
  "albums" : {
    "href" : "https://api.spotify.com/v1/browse/new-releases?offset=0&limit=20",
    "items" : [...],
    "limit" : 20,
    "next" : "https://api.spotify.com/v1/browse/new-releases?offset=20&limit=20",
    "offset" : 0,
    "previous" : null,
    "total" : 500
  }
}
```

#### Actual behaviour:
404 Not Found (inconsistently). Repeatedly resending the request eventually returns successfully (HTTP 200). Continuing to resend then reverts to the 404 Not Found error.
Video capture of the issue in action, using Postman HTTP client: https://youtu.be/ul44jDOqs3Q

**Comment by victorpre** [comment]
Some endpoints are not available as well for Brazilian region:

- `GET /v1/me/player`
- `GET /v1/me/player/currently-playing`
- `GET /v1/me/player/devices`

**Comment by hughrawlinson** [comment]
Hi! It looks like we were having an issue with our API calling some endpoints to 404. We think we've resolved this now. Please ping me or reopen this issue if you encounter it again.

**Comment by jaedb** [comment]
@hughrawlinson I can confirm that everything is working as expected now, thanks!
