### ISSUE TITLE
Is it possible to get the index of a particular track on a playlist?

### ISSUE THREAD

**Issue by dukeblue2017** [spotify/web-api#734]
I am trying to trigger a certain track to play for a user within the context of a playlist. Currently, the /v1/me/player/play endpoint only supports offsetting playback position by index, not by track ID (the actual behavior with the otherwise correct syntax is that the playlist begins playing at the first track no matter the ID passed in as offset).

Is there a way to get the index of a particular track on a playlist other than iterating over the array returned by the `/v1/users/{user_id}/playlists/{playlist_id}` endpoint?

#### Endpoint(s):
* `/v1/users/{user_id}/playlists/{playlist_id}`
* `/v1/me/player/play`

#### Scope(s):
* `user-modify-playback-state`

**Comment by tpict** [comment]
I don't believe so, I've resorted to iterating over `/v1/users/{user_id}/playlists/{playlist_id}/tracks` results until the `next` URL is null

**Comment by hughrawlinson** [comment]
Hi! It's not possible, as a track may appear in a playlist multiple times. The correct way is to paginate through a playlists tracks until you find the track uri.
