### ISSUE TITLE
Artist name in JSON is empty.

### ISSUE THREAD

**Issue by ConstantKostya** [spotify/web-api#735]
Issue found on December 6th 2017.

#### Endpoint(s):
* `GET /v1/tracks/{id}`

#### Steps to reproduce:
1. Open the API Console
2. Call the `get-tracks` endpoint with `id` `6Br5mChPdgQNmLF0G0gjPH`
(Track name: I Dont Want to Live Forever)

#### Expected behaviour:
The JSON should return 
`"https://api.spotify.com/v1/artists/6IrDpI3xcuzTUiEc3fnc9H",
"id": "6IrDpI3xcuzTUiEc3fnc9H",
        "name": "Amy Kaylee",
        "type": "artist"`

#### Actual behaviour:
But is returning:
`"https://api.spotify.com/v1/artists/6IrDpI3xcuzTUiEc3fnc9H",
"id": "6IrDpI3xcuzTUiEc3fnc9H",
        "name": "",
        "type": "artist"`

**Comment by jscholes** [comment]
When I load spotify:track:6Br5mChPdgQNmLF0G0gjPH into the Spotify desktop app on Windows, I don't see any metadata for it or the album it belongs to there either.

**Comment by ConstantKostya** [comment]
True, And 'https://open.spotify.com/artist/6IrDpI3xcuzTUiEc3fnc9H' returns "Amy Kaylee", The artists is known IMO

**Comment by arirawr** [comment]
I've been able to reproduce this and we're looking into it. Thanks for the report!

**Comment by arirawr** [comment]
Hi @ConstantKostya - we took a look into this, and it turns out this content is no longer on Spotify so you will not be able to access the track/album or the associated metadata.
