### ISSUE TITLE
Play embed widget doesn't play on click if Spotify app is not open

### ISSUE THREAD

**Issue by drazamilo** [spotify/web-api#737]
Issue found on February 19th 2015.

#### Endpoint(s):
* They're not really endpoints, they're the embeds.

#### Scope(s):
* None (application is not using authentication)

#### Steps to reproduce:
1. Press Log in with Spotify here: https://www.realtor.com/holiday-playlist/
2. Press the play button on any of the embeds

#### Expected behaviour:
If Spotify is not open yet, it should open Spotify and play the song immediately. If Spotify is already open, it should just immediately start playing the song.

#### Actual behaviour:
If Spotify is not open yet, it opens Spotify but does not play the song until a second click on the play button. If Spotify is already open, it does nothing.

**Comment by bih** [comment]
Thanks for reaching out!

There is a known issue with play widgets where, if a track URI is relinked, the embed widget doesn't automatically play. We're working on fixing that issue in the near future. Try using a different URI and it should automatically start playing.

If you're not sure what Track Relinking is, we have [a handy guide](https://beta.developer.spotify.com/documentation/general/guides/track-relinking-guide/) for you.

I'll close this issue, but feel absolutely free to re-open if this does not solve your problem or if there's a different issue relating to the widgets you're having 👍
