### ISSUE TITLE
Volume is decremented by 1 when reading playback state

### ISSUE THREAD

**Issue by joshuathompson** [spotify/web-api#738]
Issue found on December 7th 2017.

#### Endpoint(s):
* `PUT /v1/me/player/volume`
* `GET /v1/me/player/devices`

#### Scope(s):
* `user-read-playback-state`
* `user-modify-playback-state`

#### Steps to reproduce:
1. Open the API Console
2. `PUT` the number `54` in the `Set Volume For User's Playback` endpoint page
3.  `GET` the current playback information from the `Get Information About The User's Current Playback` endpoint page.

#### Expected behaviour:
I would expect the JSON object to show a volume_percent of 54 which was just set.

#### Actual behaviour:
The volume is decremented by one, showing 53.

**Comment by bih** [comment]
Hey! I can confirm that I can replicate this bug and we're investigating. Thanks for reporting!

**Comment by bih** [comment]
We've gone ahead and fixed this issue. Try it again when you have a chance 👍 

As it's fixed from our end, I'll close the ticket, but feel free to re-open if this issue persists.
