### ISSUE TITLE
OAuth Error 502

### ISSUE THREAD

**Issue by annadnl** [spotify/web-api#739]
Issue found on December 8th 2018.

#### Endpoint(s):
* any

#### Scope(s):
* any

#### Steps to reproduce:
1. Open the API Console
2. Call the "Get OAuth Token" Button

#### Expected behaviour:
User should be authenticated

#### Actual behaviour:
502 Server Error (not consistently - sometimes it does authenticate)

Same behaviour if calling the authentication via web api.

**Comment by hughrawlinson** [comment]
Hi @annadnl! This issue started this morning, but appears to be resolved now. Please ping me if you're still experiencing it.
