### ISSUE TITLE
All Platforms - "Google Home" device times out from Spotify Connect

### ISSUE THREAD

**Issue by thordavid** [spotify/web-api#741]
Issue found on December 11 2017.

#### Endpoint(s):
* `GET https://api.spotify.com/v1/me/player/devices`

#### Scope(s):
* Premium User
#### Steps to reproduce:
1. play something from spotify on google home device with voice
2. Let some time go by: Call the `GET https://api.spotify.com/v1/me/player/devices
` endpoint`
3. Always connected google home device is not returned as it is with amazon echo/alexa
4.  works well with alexa device but not with google home device
5. ask google home to play spotify and device now appears when endpoint is called.
6. seems like it times out

#### Expected behaviour:
device type type to always be connected`.

#### Actual behaviour:
device times out and is not longer reported as available via the endpoint (consistently)

**Comment by bih** [comment]
Sounds like there's a bug with our integration on Google Home. Thank you for sharing this bug report - we'll look into it and get back to you!

**Comment by Jean-PhilippeD** [comment]
Hello,

I think I have the same behaviour here but with all my devices. (sonos, raspotify, android app and linux app).

After a few hours without using any devices, the endpoint returns me an empty array. Once I play music on a given device through an app (linux or android), this device is showing up through API endpoint.
