### ISSUE TITLE
502 when sending POST to refresh token

### ISSUE THREAD

**Issue by annadnl** [spotify/web-api#742]
Issue found on December 13th 2017.

#### Endpoint(s):
* `POST https://accounts.spotify.com/api/token`

#### Scope(s):
* none

#### Steps to reproduce:
1. post several refresh requests for tokens

#### Expected behaviour:
existing user token refreshes

#### Actual behaviour:
502 Bad Gateway (inconsistently, occurs after a random number of POST requests)

**Comment by bih** [comment]
Hey @annadnl! Thanks for reporting this issue. Are you still getting 502's when calling for a refresh token?

**Comment by annadnl** [comment]
hello, bih,
inconsistently, and this morning lots and lots of 503 on put requests.

**Comment by mahdiamolimoghadam** [comment]
42318175

**Comment by arirawr** [comment]
Closing this as we haven't been able to replicate. Please re-open with replication steps if you continue to see this issue :)
