### ISSUE TITLE
get users top artists does not return real total / nexttoken

### ISSUE THREAD

**Issue by yonahforst** [spotify/web-api#743]
Issue found on December 13th 2017.

#### Endpoint(s):
* `GET /v1/me/top/{type}`

#### Scope(s):
* user-top-read

#### Steps to reproduce:
1. Open the API Console
2. Call the `Get User's Top Artists and Tracks` endpoint

#### Expected behaviour:
A paging object where the total is the total number of objects available and a next token

#### Actual behaviour:
A paging object where the max total is always the limit and never a next token. You can confirm this by playing with the limit param; setting it lower and higher

**Comment by arirawr** [comment]
I've been able to reproduce this and we're looking into it. Thanks for the report!

**Comment by arirawr** [comment]
Hi @yonahforst - thanks again for the report! We tracked down the bug - this should be working as expected now. 🎉
