### ISSUE TITLE
Number of streams for albums

### ISSUE THREAD

**Issue by mza97** [spotify/web-api#744]
Is it possible to add them? It could be interesting for anomaly detection.

**Comment by arirawr** [comment]
Thanks for the feature request! We don't have any plans for this in the short term, but we'll post here if there are any updates.

**Comment by arirawr** [comment]
Hey all,

As per our [new developer support process](https://github.com/spotify/web-api#creating-an-issue), any feature requests that have no plans to be considered in the next 6 months will be closed as wontfix.

We do not have any plans to implement this in the next 6 months and thus will close as wontfix.

We encourage you and other members of the community to continue to share use cases and your support for this feature, as it helps us prioritize features going forward. You will be able to comment on this issue even after it is closed. We will also post any updates here relating to this suggestion when they happen.
