### ISSUE TITLE
Get Artist ID associated with a User ID

### ISSUE THREAD

**Issue by sukezane** [spotify/web-api#745]
Does all Artist account always have Spotify User ID?
If so, I would like to retrieve artist's Spotify User ID (beginning spotify:user:) and integrate with an artist ID(beginning spotify:artist: )

Some artist account disclosed artist’s user account ID at Spotify Desktop App. For example, AmPm(spotify:artist:5Xcbv83o11Ez2XPHa1n8Pf) disclosed their user account because AmPm created playlist from user account(spotify:user:ampm_tokyo) and the playlist published at the artist page which display artist tracks and albums.

**Comment by arirawr** [comment]
Thanks for the feature request! We'll post here if there are any updates, but we don't have any plans for this in the short term.

**Comment by arirawr** [comment]
Actually, this looks like a duplicate of #10. I'm going to close this, and you can follow that issue for updates!
