### ISSUE TITLE
Username with special chars not working in POST/PUT requests

### ISSUE THREAD

**Issue by jwilsson** [spotify/web-api#746]
Issue found on December 20th 2017.

#### Endpoint(s):
* `POST /v1/users/#username/playlists`

#### Scope(s):
* `playlist-modify-public`

#### Steps to reproduce:
1. Open the API Console.
2. Call the `post-playlists` endpoint with `user_id` `#jwilsson`

#### Expected behaviour:
A new playlist to be created as described on `https://developer.spotify.com/web-api/create-playlist/`.

#### Actual behaviour:
`403 Forbidden` with message `You cannot create a playlist for another user`.

This originally stemmed from https://github.com/jwilsson/spotify-web-api-php/issues/111 where POST/PUT requests without a URL encoded username containing special chars such as "#" would yield a 404. However, since the API Console URL encodes the username I ran into the above issue where it's returning `403`s instead.

URL encoding the username may very well be the expected behaviour and I'm just bad at finding it in the docs, but that still wouldn't explain the `403` errors. So I guess this is both a question and a bug report. 

* Do we need to URL encode usernames in POST/PUT requests?
* But URL encoded username return `403 Forbidden`.

Thanks,
Jonathan

**Comment by sevi-l** [comment]
try: Replace the hash with %23 in the url

**Comment by arirawr** [comment]
I've been able to reproduce this and we're looking into it. Thanks for the report!

**Comment by BloodShura** [comment]
@arirawr any updates?

**Comment by arirawr** [comment]
No updates yet. I'll post here when we have updates :)

**Comment by arirawr** [comment]
This issue should now be resolved. Thanks for your report!

Please feel free to reopen if you continue to see this issue occur.
