### ISSUE TITLE
Can't sign up to Spotify developer program

### ISSUE THREAD

**Issue by typistX** [spotify/web-api#749]
I'd rather add this as an issue for "general web api" but could find no link or email address which offered more general assistance.

I'm using Chrome on MacOS Sierra. When I submit the signup form, the animation just spins and spins and nothing happens. After a while I'll get a notification that the CAPTCHA has expired.

Is the developer program closed or something?

**Comment by arirawr** [comment]
Hi there - that's not good! Could you please let us know exactly what flow you're going through (the URL of the firm you are trying from, which buttons you're clicking, etc) so we can try to reproduce the issue?

**Comment by typistX** [comment]
Hi,

> the URL of the firm you are trying from

I've tried this multiple times from multiple locations. 

This is how I'm attempting:

1. Open Google Chrome / Safari on MacOS
2. First result leads you here: https://developer.spotify.com/
3. Click on the upper stripe offering to join the beta program
4. Click on the link with the anchor "Sign up for a free Spotify account here."
5. Sign up for Spotify
6. Fill details
7. wait forever, or until you get an error that the CAPTCHA has expired

**Comment by typistX** [comment]
I think I've figured out what the problem is, but I'm not sure what the solution is, if any: Spotify isn't available in my country. 

But I'm not looking to use Spotify's consumer-facing service. I'm looking to integrate and utilize its API for my own end-users. Shouldn't **that** be possible, even though listening to Spotify isn't something I can do in my country?

**Comment by hughrawlinson** [comment]
Hi @typistX - in order to sign up for the Spotify Developer Program, you must have a Spotify account, and in order to have a Spotify account, you must live in a country in which Spotify is available. Therefore, you're ineligible for signing up for Spotify for Developers. Sorry! Hope Spotify comes to your country soon.

**Comment by typistX** [comment]
Appreciate your response but respectfully disagree with this policy. What if I’m a “non-Spotify” country but my service is US-facing one?
