### ISSUE TITLE
Sortable playlists

### ISSUE THREAD

**Issue by jaedb** [spotify/web-api#75]
When fetching a user's playlist, there is no way to request a sort order. The only way to achieve such things is to send multiple requests to get all playlists (because of the limit of 200 playlists per request), and then locally compile a sorted list that way. This is a hacky approach, and requires extra requests to the Spotify API.

I propose an additional parameter to be parsed when requesting a user's playlist, that provides sorting by Title, Date Created, LastUpdated and OwnerID. This sorted list will then be split by the pagination object as is currently the case.

**Comment by thelinmichael** [comment]
Thanks for the feedback @jaedb, some users have a lot of playlists and sorting on our side would indeed be a nice feature.

**Comment by paulcarvill** [comment]
Any update on whether sort parameters are going to be added for playlists or saved albums? "Title" and "Date Created" would be most useful.

**Comment by bih** [comment]
Hello @jaedb,

As per our [new developer support process](https://github.com/spotify/web-api), any feature requests that have no plans to be considered in the next 6 months will be closed as <kbd>wontfix</kbd>.

In this particular case, it is currently possible to sort through playlists. I do agree that it would be more efficient (both for you and Spotify's servers) to be specify a `sort`-esque parameter for your convenience. However, this is something we expect to consider in the next 6 months and thus will close as <kbd>wontfix</kbd>.

We encourage you and other members of the community to continue to share use cases and your support for this feature, as it helps us prioritize features going forward. You should be able to comment on this issue even after it is closed. We will also post updates here relating to this suggestion as and when they happen.

Cheers 👍

**Comment by shillshocked** [comment]
Please add this. I have no current workaround.
