### ISSUE TITLE
Cannot check playlist's followers

### ISSUE THREAD

**Issue by blubecks** [spotify/web-api#751]
Issue found on December 28th 2017.

#### Endpoint(s):
* `GET /users/{owner_id}/playlists/{playlist_id}/followers/contains`

#### Scope(s):
* All possible scopes

#### Steps to reproduce:
1. Open the API Console
2. Call the `Check if Users Follow a Playlist` endpoint with all the mandatory params (playlist id, playlist_owner, my id)

#### Expected behaviour:
I expect a `true` as a result.

#### Actual behaviour:
It returns `false`

**Comment by arirawr** [comment]
Hi @blubecks - thanks for the report! I'm not able to reproduce this - could you let me know the exact parameters you're using?

**Comment by arirawr** [comment]
Going to close this as I can't reproduce the behaviour - please reopen with reproduction steps if you're still seeing the issue 🙂

**Comment by blubecks** [comment]
I'm sorry for my late reply, actually now works fine! Thank you for your support!! :)
