### ISSUE TITLE
Tracks missing from PlayHistory on 2017-12-27

### ISSUE THREAD

**Issue by Kaprow** [spotify/web-api#752]
Issue found on February 19th 2015.

#### Endpoint(s):
* `GET /me/player/recently-played`

#### Scope(s):
user-read-recently-played 
playlist-read-private 
playlist-modify-private 
playlist-modify-public

#### Steps to reproduce:
Call the API with limit 50

#### Expected behaviour:
The last 50 tracks played by the user are returned

#### Actual behaviour:
Play History for 2017-12-27 is incomplete. Many songs played to completion are missing.

**Comment by arirawr** [comment]
We're looking into this - thanks for the report.

**Comment by arirawr** [comment]
Confirmed that there was an issue with the data around this time. It has been resolved.
