### ISSUE TITLE
Alphabetic Sorting in Documentation

### ISSUE THREAD

**Issue by Dargmuesli** [spotify/web-api#753]
Lists in the API's documentation like "topics" on https://developer.spotify.com/web-api/object-model/ are often not completely sorted alphabetically. Currently `context object` is the last element in the list. Also e.g. on https://beta.developer.spotify.com/documentation/web-api/reference/ `Library` is sorted in between `Tracks` and `User's Profile`, ... . That makes it sometimes irritating to find a feature. Why is that? Can it be fixed?

**Comment by arirawr** [comment]
Hi @Dargmuesli - we've fixed this up for you on the [object model](https://beta.developer.spotify.com/documentation/web-api/reference/object-model/) and [reference documentation](https://beta.developer.spotify.com/documentation/web-api/reference/) 🔡 

Happy hacking! 💻

**Comment by Dargmuesli** [comment]
Thanks a ton!

**Comment by Dargmuesli** [comment]
Just in case you want to hear some other ideas on improvement in the documentation @arirawr:

- The Library endpoint documentation names speak in two album related titles of "Current User" and in their track counterparts of "a User's".
- Do you want me to add more things when I find them?

If you're wondering: my question is related to my work on [thelinmichael/spotify-web-api-java#105](https://github.com/thelinmichael/spotify-web-api-java/issues/105). I use your naming scheme as ours over in the Java wrapper.

**Comment by arirawr** [comment]
So they do, good catch. Will take a look.

We have a feedback form at the bottom of the [website's homepage](https://beta.developer.spotify.com/) - that's probably the best place to report documentation or website errors.

PS - thanks for contributing to the wrappers and helping make the developer experience awesome!
