### ISSUE TITLE
Internal server Error when trying to transfer the playback

### ISSUE THREAD

**Issue by eykjs** [spotify/web-api#755]
Issue found on January 3rd 2018.

#### Endpoint:
* `PUT https://api.spotify.com/v1/me/player`

#### Scope(s):
* streaming
* user-read-birthdate
* user-read-email
* user-read-private
* user-read-playback-state
* user-modify-playback-state

#### Steps to reproduce:
1. Make a XHR Request to the https://api.spotify.com/v1/me/player endpoint with a valid device_Id 

#### Expected behaviour:
Retrieving no error and because of that I expect the new device to be selected as active device

#### Actual behaviour:
500 Internal Server Error

**Comment by arirawr** [comment]
Hi @eykjs - thanks for the report. This looks like a duplicate of issue #747 - please follow that issue for updates!
