### ISSUE TITLE
No mobile device with /v1/me/player/devices

### ISSUE THREAD

**Issue by Nicolai8** [spotify/web-api#756]
#### Endpoint(s):
* `GET /v1/me/player/devices

#### Scope(s):
* user-read-playback-state

Hello,
I'm trying to get available devices but getting only Web Player and my mobile device is missing. What looks strange is that in official Spotify web app I see both Web Player and mobile device.

I also tried here: [https://beta.developer.spotify.com/console/get-users-available-devices/](https://beta.developer.spotify.com/console/get-users-available-devices/) but with no success.

Do I miss something? Any help will be appreciated.

UPDATE:

`https://api.spotify.com/v1/me/player` returns:
```
"context": null,
  "device": {
    "id": null,
    "is_active": true,
    "is_restricted": true,
    "name": "SM-G935F",
    "type": "Smartphone",
    "volume_percent": null
  },
```

**Comment by arirawr** [comment]
Hi @Nicolai8 - thanks for the report!

Connect Web API relies on local network connections to discover and interact with some devices.

For example, when:
- A new device is added to the network
- A device is in “sleep” mode
- A device on the local network is currently tied to another user account, or
- Other reasons specific to the device

As a result, some devices that appear in the Connect picker within the Spotify application may not always be visible or available on the Connect Web API Endpoints.

You can read more in the guide [Using the Spotify Connect Web API](https://beta.developer.spotify.com/documentation/web-api/guides/using-connect-web-api/).
