### ISSUE TITLE
HTML Widget Play Button broken - Too many redirects

### ISSUE THREAD

**Issue by an-tex** [spotify/web-api#757]
You can see the error in the documentation it self:

https://developer.spotify.com/technologies/widgets/examples/

There's a redirect loop, e.g.:
https://open.spotify.com/embed?uri=spotify%3Atrack%3A33Q6ldVXuJyQmqs8BmAa0k
redirects to itself. 

Seems this breaks all players that are out there...

**Comment by bih** [comment]
Hey! Thanks for reporting this bug. It has now been fixed. Feel free to re-open if you are continuing to have issues 👍
