### ISSUE TITLE
500 Error Attempting To Authenticate User

### ISSUE THREAD

**Issue by avoinicu** [spotify/web-api#758]
Issue found on January 11th 2018.

#### Endpoint(s):
* `GET https://accounts.spotify.com/en/authorize?`

#### Scope(s):
* 'user-read-private user-read-email'

#### Steps to reproduce:
Make the initial client side request to the authorize endpoint and click accept or cancel

#### Expected behaviour:
When the user clicks accept or cancel, instead of redirecting to my applications callback with authorization code, or an error, the server responds with a 500 internal server error consistently.

#### Actual behaviour:
500 Server Error (consistently)

**Comment by RafaelMagalhaesN** [comment]
Same problem :'(

**Comment by bih** [comment]
Sorry to hear you're having issues. Have you checked to see your Redirect URIs are exactly the same, including the trailing slashes?

**Comment by avoinicu** [comment]
Yes, the Redirect URIs are exactly the same.

**Comment by bih** [comment]
OK, sorry to hear that! Could you share your complete authorization URL with us? We're investigating and will get back to you here when we have more information.

**Comment by avoinicu** [comment]
This is the authorization URL I'm redirected to:

https://accounts.spotify.com/en/authorize?response_type=code&client_id=2092c53fdcce427b8a0ff9c4c6e02756&scope=user-read-private%20user-read-email&redirect_uri=http:%2F%2Flocalhost:8888%2Fcallback%2F&state=fQDHOvPzmf3KNSCZ

and it's generated by the authorization_code example.

**Comment by fqueiruga** [comment]
@avoinicu  For me, the problem was solved registering the callback URL on the developer's console (I forgot to do it)

**Comment by avoinicu** [comment]
@fqueiruga I have the callback URL registered in the developers console.

**Comment by arirawr** [comment]
Hey @avoinicu - took a look at your app.

It seems the only redirect URI you have registered to your app is https://example.com/callback, but the uri you're using in that authorize url is http://localhost:8888/callback/. If you register the URI `http://localhost:8888/callback/` on the dashboard (and make sure you save!), this will fix your issue. You can edit redirect URIs in the "Edit Settings" menu:

![screen shot 2018-01-12 at 12 07 35](https://user-images.githubusercontent.com/6777313/34872478-38b47f62-f791-11e7-8fe4-96372c6449a2.png)


I'm going to go ahead and close this issue :)

**Comment by hambb** [comment]
@bih @arirawr  I have same issue.
redirected url : 
https://accounts.spotify.com/en/authorize?client_id=1877951149964f46adf5a46f1180fc96&response_type=code&redirect_uri=★&scope=&state=ueFia6qv8j6obBh1
★ is my service url and already registered `Redirect URIs` url.

**Comment by avoinicu** [comment]
@arirawr I'm quite sure the redirect URI was in there (just checked before answering your first question).

Anyways, it seems it's working now, so thank you for your help!

**Comment by arirawr** [comment]
@hambb Took a look at your app, it seems you're authenticating an iOS app. Make sure your redirect URI follows the requirements here: https://beta.developer.spotify.com/documentation/general/guides/app-settings/#to-enter-uri-for-an-app-on-ios

**Comment by hambb** [comment]
@arirawr okay... I'll check it out once more and if find issue, I will create new issue.
thanks!
