### ISSUE TITLE
Not working sign up with email

### ISSUE THREAD

**Issue by hambb** [spotify/web-api#759]
Issue found on January 11th 2018.

#### Endpoint(s):
*  `GET https://www.spotify.com/us/signup/`

#### Scope(s):
* None (application is not using authentication)

#### Steps to reproduce:
first, I called up the API `GET https://accounts.spotify.com/en/authorize`
I have spotify account, but is not working.
: same issue https://github.com/spotify/web-api/issues/758

So, I tried sign-up with email, cannot sign-up.
I found ERROR, chrome browser console is:
```
spweb-site-ad03e0c37d.min.js:3 Uncaught TypeError: Cannot read property 'type' of undefined
    at t.validator.highlight (spweb-site-ad03e0c37d.min.js:3)
    at t.validator.defaultShowErrors (spweb-site-ad03e0c37d.min.js:3)
    at t.validator.showErrors (spweb-site-ad03e0c37d.min.js:3)
    at c (signup-660fa65035.js:1)
    at Object.<anonymous> (signup-660fa65035.js:1)
    at Object.dispatch (jquery-2-0680c441b5.1.3.min.js:2)
    at Object.v.handle (jquery-2-0680c441b5.1.3.min.js:2)
    at Object.trigger (jquery-2-0680c441b5.1.3.min.js:2)
    at Object.e.event.trigger (jquery-2-0680c441b5.1.3.min.js:3)
    at Object.<anonymous> (jquery-2-0680c441b5.1.3.min.js:2)
```

#### Expected behaviour:
1.success sign-up with email
2. redirecting to my applications callback with authorization code

#### Actual behaviour:
javascript console error

**Comment by bih** [comment]
Thanks for reporting this issue! We're investigating and will get back to you 👍

**Comment by bih** [comment]
@hambb Do you have more information on what browser/version/OS you're using?

**Comment by hambb** [comment]
@bih 
I using browser : Chrome , version : 63.0.3239.132(32bit). and OS is WIN7

**Comment by arirawr** [comment]
Hi @hambb - are you still seeing this error?

**Comment by zeorin** [comment]
@arirawr I'm not OP, but I'm also affected by this error, cannot sign up as a result.
The error is still active.

**Comment by arirawr** [comment]
@zeorin do you have a live link to your authorize page so I can try to reproduce? 😄

**Comment by zeorin** [comment]
@arirawr Just visiting https://www.spotify.com/us/signup/ in any web browser will display the error in the console. I myself am not trying to use the API.

As far as I can tell, for at least a month now, nobody would have been able to sign up to Spotify without using Facebook connect (not sure if that's working or broken, because I don't have a Facebook account).

**Comment by arirawr** [comment]
@zeorin Unfortunately I can't help with customer support - you should contact @SpotifyCares on Twitter or go to https://support.spotify.com/us/. They should be able to help you with sign up issues 🙂

**Comment by zeorin** [comment]
@hambb FWIW I couldn't sign up because the country I'm in isn't supported, see https://twitter.com/SpotifyCares/status/955432500419022848.

FYI signing up whilst using an IP address from a supported country works. All services after that seem to work without needing IP shenanigans.
