### ISSUE TITLE
Add ability to play full tracks for logged in users

### ISSUE THREAD

**Issue by jonknyc** [spotify/web-api#76]
I am building a web app to play music, and would love to build it on the Spotify web API.  Anyone listening to music on my app would have to have a Spotify account and be signed in via OAuth, but much to my surprise, the web API does not let you play full tracks.

Is there a reason you don't support playing full tracks?  (I tried Googling around, and didn't find any great explanations anywhere)

**Comment by thelinmichael** [comment]
Hi @jonknyc! There's no web implementation yet, so it's only available for the Android and iOS SDKs. I just reopened the initial issue mentioning this, see #57.
