### ISSUE TITLE
Server responds 500 internal error while trying to get access token using implicit grant authentication

### ISSUE THREAD

**Issue by hansonlee2017** [spotify/web-api#761]
Issue found on Jan, 12, 2018.

#### Endpoint(s):
* `https://accounts.spotify.com/en/authorize?client_id={client_id}&response_type=token&scope=playlist-modify-public&redirect_uri=http:%2F%2Flocalhost:3000`

#### Scope(s):
* playlist-modify-public

#### Steps to reproduce:
1. open above url in a browser
2. pressing OK causes internal error after post

[Error page image](https://imgur.com/6u5knyW)

#### Expected behaviour:
Redirect to redirect_uri (http://localhost:3000)

#### Actual behaviour:
500 Server Error (consistently)

**Comment by hansonlee2017** [comment]
client_id is: d09fde2a4c2c442dbc24ea0a32edfe19

**Comment by damianciancio** [comment]
I have the same issue

**Comment by arirawr** [comment]
Hey @hansonlee2017 - I took a look at your app. It looks like you have your redirect URI saved in the developer dashboard as `http://localhost:3000/` (with the trailing slash), whereas you're passing the accounts service `http://localhost:3000` (without the trailing slash). Your redirect URIs need to be **the exact same**, right down to the trailing slash.

You can either add a trailing slash to the URI you're sending to the accounts service, or add `http://localhost:3000` to your app on the [developer dashboard](https://beta.developer.spotify.com).

We're aware of the poor error handling for invalid redirect URI errors and are working on a fix.
