### ISSUE TITLE
Get-Curren- User’s-Saved-Albums only returns 19

### ISSUE THREAD

**Issue by gahisee** [spotify/web-api#762]
Issue found on February 19th 2015.

#### Endpoint(s):
GET https://api.spotify.com/v1/me/albums

#### Scope(s):
user-library-read

#### Steps to reproduce:
1. Open the API Console
2. Call the `Get Current User's Saved Albums' with Limit=20 and Offset=0

#### Expected behaviour:
I have 34 saved albums, so this first call should return 20.
#### Actual behaviour:
Only 19 albums are returned.
this is the last part of the response:
 "limit" : 20,
  "next" : null,
  "offset" : 0,
  "previous" : null,
  "total" : 19

**Comment by arirawr** [comment]
Hi @gahisee - are you getting the 34 saved albums from the Desktop app? 

The Desktop app, by default, shows saved albums **and albums that contain saved tracks**. The Web API only returns saved albums.

In the Desktop app, on your Albums view, you can click the "Saved Albums Only" option (see below), which will give you the same results as the Web API.

<img width="910" alt="screen shot 2018-01-22 at 10 19 46" src="https://user-images.githubusercontent.com/6777313/35213565-5cb5b06e-ff5e-11e7-9353-1a6f1a930380.png">

**Comment by gahisee** [comment]
my report clearly had to do with Web API.
not the desktop which in fact is my reference.  it shows 34 "Saved Albums Only".
still the web api call https://api.spotify.com/v1/me/albums?limit=50&offset=0
only returns 20 (as of this morning) and the response shows "Next" as null.
if i request the next page anyway with https://api.spotify.com/v1/me/albums?limit=50&offset=50
i get 0 items back.

**Comment by arirawr** [comment]
Sounds like it may be a duplicate of #754 then. We're already looking into it and will comment on that issue when we have updates! 🙂

**Comment by manzt** [comment]
I am having a similar issue. I have more than 50 albums saved to my Spotify, and when I use the web api call https://api.spotify.com/v1/me/albums?limit=50&offset=0, it returns 50 albums. However, if I make the web api call https://api.spotify.com/v1/me/albums?limit=50&offset=1, it returns 49. If I make the call https://api.spotify.com/v1/me/albums?limit=50&offset=49, it returns 1 album. If I try to make a request for the next page, https://api.spotify.com/v1/me/albums?limit=50&offset=50, it returns 0 items. 

It seems that the offset and limit do not work to actually page. It just shortens the length of the returned original 50.
