### ISSUE TITLE
Not saving redirect URL 

### ISSUE THREAD

**Issue by jram0421** [spotify/web-api#763]
The web console is not saving my redirect URL

**Comment by arirawr** [comment]
Hi @jram0421 - have you made sure to press "Save" at the bottom of the form after you add the URI?

**Comment by arirawr** [comment]
I'm happy to share that we've updated the dashboard so your URIs are saved as soon as you click "Add" - no need to scroll down to save the whole form. I'm going to close this issue - feel free to reopen if you continue to see issues.
