### ISSUE TITLE
Information about https://api.spotify.com/v1/me/player/recently-played

### ISSUE THREAD

**Issue by asolu** [spotify/web-api#764]
The endpoint in the title returns only the last 50 played song?
Seems that the after and before parameters are  in influent.
How much song can i discover back in time?

**Comment by hughrawlinson** [comment]
Yep, that's correct, you can get up to 50 most recently played songs. There's no way to get further back in time. Hope that clarifies things!

**Comment by asolu** [comment]
Ok thanks for your answer! In future will be possible?
