### ISSUE TITLE
Mobile app dosnt show on device call

### ISSUE THREAD

**Issue by Nagge** [spotify/web-api#765]
When using "https://api.spotify.com/v1/me/player/devices" you can see desktop and mobile devices if they are open using a desktop for request. But you cannot see mobile if you use the same phone to do request and open app. Mobile only shows when using your phone on request if you play a song in your app and then do request.

**Comment by arirawr** [comment]
Hi @Nagge - I haven't been able to reproduce the behaviour you describe here. I'm going to close the issue, but feel free to reopen with reproduction steps if you are able to consistently reproduce the issue.

As documented [here](https://beta.developer.spotify.com/documentation/web-api/guides/using-connect-web-api/#devices-not-appearing-on-device-list), the Connect API relies on local network connections to discover and interact with some devices. Some devices that appear in the Connect picker within the Spotify application may not always be visible or available on the Connect Web API Endpoints.
