### ISSUE TITLE
Last play date for tracks

### ISSUE THREAD

**Issue by Reygok** [spotify/web-api#768]
Hello, I was a bit disappointed to see that tracks don't have theis last play date associated with them. I listen to music with this in mind, however. I wrote an app for iOS which sorts all my songs after their last play date, so I listen to the songs which I havent heard in a long time first. 
Now that I've been trying out spotify, I miss this feature, and having the simple info added to a track in the api would allow me to create custom playlists with this principle.

Thanks in advance!
Reygok

**Comment by arirawr** [comment]
Thanks for the feature request! We'll post here if there are any updates.

**Comment by arirawr** [comment]
As per our [new developer support process](https://github.com/spotify/web-api#creating-an-issue), any feature requests that have no plans to be considered in the next 6 months will be closed as wontfix.

We do not have any plans to implement this in the next 6 months and thus will close as wontfix.

We encourage you and other members of the community to continue to share use cases and your support for this feature, as it helps us prioritize features going forward. You will be able to comment on this issue even after it is closed. We will also post any updates here relating to this suggestion when they happen.
