### ISSUE TITLE
Album Art not showing in "Now Playing" widget of macOS Notification Center

### ISSUE THREAD

**Issue by fabi94music** [spotify/web-api#769]
#### Expected behaviour:
Album cover is shown on the Notification Center widget

#### Actual behaviour:
Now album cover

**Comment by arirawr** [comment]
Hi @fabi94music! This sounds like an issue with the MacOS app. You should reach out to customer service at [twitter.com/SpotifyCares](https://twitter.com/SpotifyCares) or https://support.spotify.com
