### ISSUE TITLE
Read metadata for track currently playing on a different device

### ISSUE THREAD

**Issue by SkylerLutz** [spotify/web-api#77]
I would like to be able to read the metadata for a track currently playing on another device. For example, if I am playing a track on my iPad, I would be able to write an iPhone app that is able to display the track playing from the iPad. Thanks

**Comment by colm2** [comment]
Hey, did you find any solution to this?

**Comment by thelinmichael** [comment]
@colm2, a feature that'd support this use case is tracked in #12.

**Comment by colm2** [comment]
Thanks, I subscribed over there. :)

**Comment by mprinc** [comment]
1+

**Comment by nqvst** [comment]
+1
