### ISSUE TITLE
Start/Resume a user's playback results in duplicate first track

### ISSUE THREAD

**Issue by gahisee** [spotify/web-api#770]
#### Endpoint(s):
https://api.spotify.com/v1/me/player/play

#### Scope(s):
user-modify-playback-state

#### Steps to reproduce:
1. Open the API Console
2. Call the `Start/Resume a User's Playback` and specify a user's playlist in the context_uri
no offset was specified 

#### Expected behaviour:
First track in the playlist begins to play. However, the same track is repeated in the Next-up list.

#### Actual behaviour:
First track of the playlist appears twice the queue.

**Comment by arirawr** [comment]
Hi @gahisee - I can't seem to reproduce this behaviour. Are you seeing this happen consistently?

**Comment by hughrawlinson** [comment]
Hi! Haven't heard from you in a while, so I'm going to close this issue. Please ping me if you're still experiencing it!
