### ISSUE TITLE
Feature request: Retrieve average active listeners on a playlist

### ISSUE THREAD

**Issue by jasongrishkoff** [spotify/web-api#774]
Hi there,

There's a growing trend of fake Spotify playlists in the music industry, with a number of those "curators" selling their playlists to unsuspecting artists who see 100,000 followers on a playlist and assume it translates to lots of plays.

Some of them don't necessarily have fake followers -- but have instead relied heavily on "download gates" to build their numbers.  Their followers are real, but the engagement is nonexistent. 

I've written an article about it here: https://www.indieshuffle.com/news/the-rise-of-fake-spotify-playlists/

I think the solution is simple: to be able to see how many active listeners a playlist has (perhaps a monthly, weekly or even daily breakdown).  Is this something that can be included in the playlists endpoint?

**Comment by jasongrishkoff** [comment]
I think it'd be just as reasonable to get a metric for average monthly listens if the number of listeners isn't available. Bottom line is that there are a growing number of playlisters selling their following to eager artists and the majority of them are unable to deliver anything close to what their numbers imply.  Unfortunately right now there's no way to know *what* those numbers are though.

**Comment by bih** [comment]
Hey @jasongrishkoff,

Thanks for reaching out. Given the nature of this, it seems like a feature request that should be directed towards [Spotify Community](https://community.spotify.com) as this relates to a product feature, rather than as a developer platform feature.

With that being said, if you can provide more use cases that will be clearly applicable to third-party developers, I'm happy to re-open this as a feature request for the Web API.

**Comment by jasongrishkoff** [comment]
Hi @bih, as a 3rd party developer, I can give the specific example of my website www.submithub.com -- a platform for sending songs to music bloggers and playlisters.

We currently use the Spotify API to pull metrics around how many followers each playlist has.  However, this metric does not translate to how engaged a playlist is -- one might have 500,000 followers but only generate 5,000 plays a month, where another might have 10,000 followers and generate 500,000 plays a month.

Being able to see a monthly active listeners (or listens) count with each playlist API response would give a much better indicator of how engaged that audience is.

Another website -- chartmetric.io -- collects data on Spotify playlisters, and similarly tries to produce metrics that convey how active and influential said playlister. They too are looking for a solution to this problem at scale.

Both of us are now exploring the Artist Insights dashboard but there doesn't seem to be an open API.   Are there plans to address #485 ?  Until then, we're going to need to request those artists to send us CSV exports on a case-by-case basis.

**Comment by kcrandall** [comment]
I agree with Jason metrics on how many listens a playlist gets as well as how many listens each song gets so that one can see how placement further down in the queue affects how much it gets played.

**Comment by livetodaylovetmrw** [comment]
Hi @jasongrishkoff and @kcrandall ,

I'm an artist and looking exactly for this metric when evaluating playlists. I know this exists on Submithub now, but do you guys have a found a way to measure this for playlists not listed on Submithub?

Kind regards

Chris

**Comment by jasongrishkoff** [comment]
Hi @livetodaylovetmrw -- the data we're displaying on SubmitHub is based on manual observation of data displayed in the "Discovered On" section.  To date that's the only way to capture the information you're after.

**Comment by vincentjr** [comment]
+1 on this.

@jasongrishkoff you mentioned CSV exports, where does that live on the Fan Insights portal on Spotify?

**Comment by jasongrishkoff** [comment]
@vincentjr Music --> Playlists --> top right there's a download icon of last 72 hours, 28 days, or all-time (since 2015).  Possibly only visible on desktop browser.

**Comment by vincentjr** [comment]
Oh wow, I always thought that down button was part of the dropdown selector lol. I'm actually looking to get the Top Cities information but the only CSV available on the Audience tab looks like Listeners/Followers timeline? @jasongrishkoff

**Comment by jasongrishkoff** [comment]
All I've been looking at are the plays from playlists -- not sure what other data is available.

**Comment by vincentjr** [comment]
Got it, also love what you did with your service (we used it a couple times :D). Good luck on this ticket.
