### ISSUE TITLE
No data on body of response from /v1/me/player

### ISSUE THREAD

**Issue by spike886** [spotify/web-api#775]
Issue found on February 1th 2018.

#### Endpoint(s):
* `GET /v1/me/player`

#### Steps to reproduce:
1. Open the API Console
2. Call the the endpoint for getting information about current player

#### Expected behavior:
Response 200, with data on the body

#### Actual behaviour:
Response 202, with empty body

**Comment by bih** [comment]
Hey @spike886!

You need to request the [`user-read-playback-state`](https://beta.developer.spotify.com/documentation/web-api/reference/player/get-information-about-the-users-current-playback/) scope when you authorize the user. Alternatively, in the Console you should make sure said scope is selected as demonstrated below:

![screen shot 2018-02-02 at 14 56 19](https://user-images.githubusercontent.com/918552/35736710-51a99e6e-0829-11e8-9189-42f8ef8c1d34.png)

I'm going to close this issue as I cannot replicate this issue. Feel free to re-open if you continue to have issues 👍

**Comment by spike886** [comment]
I have already set all Scopes. And I still have the same issue.
![image](https://user-images.githubusercontent.com/5800938/35749613-ea1c6b84-0830-11e8-99bd-266c1fb1d4a7.png)
