### ISSUE TITLE
Legacy Spotify Connect for older Speakers.

### ISSUE THREAD

**Issue by zGrav** [spotify/web-api#777]
So, a lot of people, myself included, have been Spotify Premium members and even got some Spotify Connect enabled devices to suddenly, a few days ago, not being able to use them and basically being turned into paperweights (very heavy ones, I might add.).

This apparently was an internal decision by Spotify and no warning came. At least, not to me. And the solution? Buy a new device. Yeah, no, thanks, not all of us can shell out $ for premium brands unfortunately.

I'd really still like to keep my fully functioning speaker and to get it back and running with Connect w/o BS.

Can we get some insight on why this happened? What were the critical changes? What is stopping the support on older devices?

Is a "legacy" module in the plans?

Regards.

**Comment by hughrawlinson** [comment]
Hi @zGrav,

This is an issue tracker for the Spotify Web API, we don't manage speakers. You can contact [our customer service team](https://support.spotify.com/us/), who may be able to address your questions.

Best,

Hugh
Spotify Developer Support

**Comment by zGrav** [comment]
Hugh, I get this is the Web API issue tracker, but do you have a endpoint for devices, which my speaker is now gone from...

I'll pursue the customer service team once more.

Thanks.

**Comment by hughrawlinson** [comment]
Ah - from that perspective, if Spotify Connect support for a device has been sunset, it will stop appearing in the Available Devices endpoint responses. I'll see if we can clarify that in our documentation.
