### ISSUE TITLE
Lookup returning 502 [Bug]

### ISSUE THREAD

**Issue by DarkN3ss61** [spotify/web-api#78]
when trying to access http://ws.spotify.com/lookup/1/?uri=spotify:track:3aGYAW4jJUNzqNdYpY1N0T
it has been returning 502 502 Bad Gateway

A few days ago it was fine. Can you either fix this or give me a workaround?

**Comment by thelinmichael** [comment]
Thanks a lot for reporting this issue @DarkN3ss61! It was resolved a couple of hours ago.
