### ISSUE TITLE
Start/Resume a User's Playback curl command has wrong formatting 

### ISSUE THREAD

**Issue by wborland** [spotify/web-api#781]
Issue found on February 19th 2015.

Endpoint(s):
https://beta.developer.spotify.com/console/put-play/

Steps to reproduce:
1. Go to url above
2. Copy the curl command
3. Execute curl command

Expected behavior:
A users playback status starts.

Actual behaviour:
400 Malformed son (constantly)

Solution:
Need to get rid of '\n' in curl command

**Comment by arirawr** [comment]
Nice catch! We'll get that fixed up.

**Comment by arirawr** [comment]
This issue should now be resolved. Thanks for your report!

Please feel free to reopen if you continue to see this issue occur.
