### ISSUE TITLE
Get Artist's Albums and songs by date

### ISSUE THREAD

**Issue by danbo2468** [spotify/web-api#782]
Hello, I was trying to get all the albums and songs an artist has released after a given date. I haven't found a way to achieve this. Can anybody tell me if this really isn't possible or give me some advice?

**Comment by hughrawlinson** [comment]
Hey @danbo2468 - I'd recommend using the 'Get an Artists Albums' endpoint, you can check out docs [here](https://beta.developer.spotify.com/console/get-artist-albums/). You can then paginate through the albums until you reach the given date. There's no `released_after` filter in the Spotify Web API.
