### ISSUE TITLE
https://api.spotify.com/v1/me/player/play play the specific context_uri

### ISSUE THREAD

**Issue by imminna** [spotify/web-api#784]
Issue found on February 8th 2018.

#### Endpoint(s):
* `PUT https://api.spotify.com/v1/me/player/play`

#### Scope(s):
* user-modify-playback-state

#### Steps to reproduce:
1.lauch spotify app first
2.Open the API Console
3.Call the me/player/play endpoint and uris body field as:
 { "context_uri": "spotify:user:11153497290:playlist:1SdgH3natY1rHmI4hNLnrt",
 "offset": {"position":0 }
 }

#### Expected behaviour:
A successful request will return a 204 NO CONTENT response code.

#### Actual behaviour:
I get 202 response code

However , if the spotify app is playing, using this api will return a 204 succeed
 How could I solve the problem ?

**Comment by arirawr** [comment]
Hi @imminna!

You will see a 202 response the first time a user connects to the Spotify Connect API or when the device is temporarily unavailable. Please see our full guide on working with the Connect API here: https://beta.developer.spotify.com/documentation/web-api/guides/using-connect-web-api/#enabling-the-initial-request

On receiving a 202 response, your application should retry the request after 5 seconds, but no more than at most 5 retries.

Hope that helps!
