### ISSUE TITLE
502 Bad Gateway with a certain recommendations endpoint

### ISSUE THREAD

**Issue by gtodd876** [spotify/web-api#785]
#### Endpoint(s):
* `GET https://api.spotify.com/v1/recommendations/?limit=10&market=US&seed_genres=electronic&target_tempo=120`

#### Scope(s):
* user-read-private user-read-email

#### Steps to reproduce:
1. Open Postman
2. Add my Authorization Bearer token
3. GET route

#### Expected behaviour:
A public user object as described on `https://beta.developer.spotify.com/documentation/web-api/reference/browse/get-recommendations/`.

#### Actual behaviour:
502 Bad Gateway Server Error (consistently)

**Comment by Gawen** [comment]
I have the exact same issue. Reproduced on the Spotify Console API, genre only field `genres` to `blues`.

**Comment by arirawr** [comment]
We're aware of the problem and are looking into it. I'll post here when we have updates :)

**Comment by gtodd876** [comment]
As a heads up, the recommendation endpoint has been working great again for me today!

**Comment by arirawr** [comment]
Yes, sorry for not updating! This was fixed :)
