### ISSUE TITLE
Controlling volume using Web Playback SDK & Connect

### ISSUE THREAD

**Issue by lrholmes** [spotify/web-api#788]
First of all, the Web Playback SDK is really awesome, and I'm super excited to use it my projects. However, I'm having a little trouble at the moment handling volume changes with the SDK/Connect API.

Currently changing the volume of the Web Playback player is causing an odd desynchronisation bug. You can reproduce this by changing the volume of the WP player via the native Spotify App. For me at least, after changing the volume in the native app, GET `/player` endpoint starts returning `is_playing: false` and this issue seems to show on the native player too, as the album artwork disappears and 'play' is unclickable (pics attached).

<img width="801" alt="Before volume change" src="https://user-images.githubusercontent.com/6804978/36064581-0ba45c30-0e85-11e8-8b80-63ab67c1ee60.png">
<img width="799" alt="After volume change" src="https://user-images.githubusercontent.com/6804978/36064584-0d56e94e-0e85-11e8-985b-4444dc3c9755.png">

I'm pretty sure it's some issue with the volume, because changing playback position works okay via the Connect API/native Spotify app.

I have more thoughts about the way that the volume is managed between Connect/Web Playback, but I think they're not relevant to this issue so will post separately later.

Let me know if there's anything I can do to help with the issue, I'm very keen to get the Web Playback SDK working at its best!

**Comment by bih** [comment]
Hey @lrholmes!

Thanks for your kind words. We're excited to see what you do with the SDK, too!

This looks interesting. Oddly it seems I can't reproduce the bug if my device is the Web Playback SDK and I update the volume through the native client. Maybe I have the steps to reproduce wrong? Could you outline the exact steps you took to replicate the bug? Then we can take a better look 👍

**Comment by lrholmes** [comment]
Hey @bih! Thanks for your response. I can't reproduce it anymore either... it seems to work really well! To celebrate I deployed the app - check it out at https://songstack.co if you want!

Will keep an eye on its performance and update if anything goes wrong 👍
