### ISSUE TITLE
Get progress_ms from the currently playing track?

### ISSUE THREAD

**Issue by ajboss98** [spotify/web-api#789]
Issue found on February 19th 2015.

#### Endpoint(s):
* `GET /v1/users/{user_id}`

#### Scope(s):
* None (application is not using authentication)

#### Steps to reproduce:
1. Open the API Console
2. Call the `get-users-profile` endpoint with `user_id` `%5E`

#### Expected behaviour:
A public user object as described on `https://developer.spotify.com/web-api/object-model/#user-object-public`.

#### Actual behaviour:
500 Server Error (consistently)

**Comment by jscholes** [comment]
Please edit your issue so that it actually reflects the problem you're experiencing, rather than the default issue template.

**Comment by bih** [comment]
Hey @ajboss98 👋

I'll interpret this as a request to learn about how to collect the `progress_ms` (or, where in a track you are in milliseconds). This is possible from the [`GET /v1/me/player` endpoint](https://beta.developer.spotify.com/documentation/web-api/reference/player/get-information-about-the-users-current-playback/).

I'll go ahead and close the issue. If I have misunderstood your question, feel free to re-open and I'll be more than happy to answer your question.
