### ISSUE TITLE
Birthday visible through multiple user-read scopes

### ISSUE THREAD

**Issue by morgzz** [spotify/web-api#792]
Issue found on February 15th 2018.

#### Endpoint(s):
* `GET /v1/users/{user_id}`

#### Scope(s):
* user-read-email
* user-read-private
* user-read-birthday

#### Steps to reproduce:
1. Open the [API Console](https://beta.developer.spotify.com/console/get-current-user/)
2. Call the `get-users-profile` endpoint with `user_id` `%5E`
3. Test each scope individually. 

#### Expected behaviour:
Per documentation below:
https://beta.developer.spotify.com/documentation/web-api/reference/users-profile/get-current-users-profile/

##### Birthday
> The user’s date-of-birth. This field is **only available** when the current user has granted access to the 
> `user-read-birthdate` scope.

#### Actual behaviour:
But the birthday is visible on all 3 scopes

------------------------------
I'm not sure this is a bug or not, it may be that the documentation needs updating.

**Comment by arirawr** [comment]
Hi @morgzz - thanks for the report! I'm not able to replicate this. 

I suspect this has to do with the way the Web API Console works. If you request the `user-read-birthdate` token using the "Get Token" button, it grants the Console access to the scope for your user. If you then click "Get Token" again and request the `user-read-email` scope and uncheck the `user-read-birthdate` scope, the access token you receive will still have the scope as you have already granted access (until it expires in one hour).

Going to go ahead and close this issue :)
