### ISSUE TITLE
Spelling Error in Polish Translation of Auth login screen

### ISSUE THREAD

**Issue by SMECRMdev** [spotify/web-api#797]
Issue found on February 19th 2015.

#### Expected behaviour:

Spelling error found in Polish translation of the button in attached image.
There is wrong spelling in second button – it should be POTWIERDŹ (“D” is missing right now).

#### Actual behaviour:
![2018-02-21 09_25_46-2018-02-21 09_25_20-fw_ wrong translation - message html](https://user-images.githubusercontent.com/36702459/36485175-81058a78-16e9-11e8-8d0b-68be597af698.jpg)

**Comment by arirawr** [comment]
Nice catch! We've reported the translation issue.

**Comment by BillFleischerSonymusic** [comment]
Hi Arielle @arirawr
Just following up on this item to see if it happened to have been addressed.  Thanks in advance.
Bill Fleischer
Sony Music Entertainment

**Comment by arirawr** [comment]
Hi Bill, I've followed up on the translation error (unfortunately it's not something I can directly change myself). I'll close this issue once it's addressed 😄

**Comment by BillFleischerSonymusic** [comment]
Hi just following up on this translation error to see if it's possible to fix... 
Thanks
Bill

**Comment by BillFleischerSonymusic** [comment]
@arirawr Hi, just following up to see if this translation/typo issue for the Polish Spotify authentication screen can be corrected.  Or, if it's not possible, let me know and I can set our Polish affiliate's expectations.... i.e. that Spotify is simply unable to correct the typo and they probably just need to live with it, or disable their Spotify application.

Thanks,
Bill

**Comment by BillFleischerSonymusic** [comment]
@hughrawlinson Hi, just following up to see if this translation/typo issue for the Polish Spotify authentication screen can be corrected. Thanks!

**Comment by arirawr** [comment]
Hi, it has been reported. We'll let you know here when it's fixed.

**Comment by arirawr** [comment]
Hey @BillFleischerSonymusic, happy to report that this has been resolved.

**Comment by BillFleischerSonymusic** [comment]
Ok, great! Will follow up with our Poland affiliate
