### ISSUE TITLE
502 bad gateway

### ISSUE THREAD

**Issue by VilleKoivukangas** [spotify/web-api#799]
I keep getting 502 Bad Gateway (from https://api.spotify.com/v1/me/player/play) and i am using exactly same codes as couple days ago and then it worked like charm.

I found this #340 closed issue and seems like similar problem

**Comment by arirawr** [comment]
Hi @VilleKoivukangas - we're aware of the problem and are working on a fix. I'll update when it's back to normal!

**Comment by arirawr** [comment]
This has been resolved 🙂
