### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by toberk** [spotify/web-api#8]
Hi there,

- Is it possible to make the shuffle mode more random?
- Is there (or will be) a way to run spotify under ARM like CubieTruck or RasberryPi?
- The newest version doesn´t show the count of new added Tracks to a playlist (beside the playlist) - PLEASE, PLEASE go back to this - now Spotify is not half as comfortable as it was before...and if the blue points in front of the new tracks came back into the playlists - would be nice too :)

Thanks in advanced and with great respct for the developer team!

Regards from germany

Tobias

**Comment by thelinmichael** [comment]
Hi @toberk!

Thanks for getting in touch, but this repository only handles bug reports and feature requests for [Spotify's Web API](https://developer.spotify.com/web-api). I believe your concerns would be appreciated in the [Spotify Community forums](https://community.spotify.com/).
