### ISSUE TITLE
Release date for playable full tracks?

### ISSUE THREAD

**Issue by GabeJacobs** [spotify/web-api#80]
Hey!

I was wondering if there was a general release date for a full-track playable web api? I know there is no way to play tracks except for using the iFrame widget (and therefore no way to play/pause programmatically), but I also heard that this is something you are working on. 

It would be very nice if you could tell us an estimated release (or even a beta release) of this new API.

Thanks so much!

- Gabe

**Comment by thelinmichael** [comment]
Hey @GabeJacobs! We haven't yet given an estimated date for playing full tracks, but we're working on it. I'd really like to ballpark it, but let's just say that it isn't happening in the short-term.
