### ISSUE TITLE
Accept the latest Developer Terms of Use to complete the set-up of your account.

### ISSUE THREAD

**Issue by XavierVicente** [spotify/web-api#800]
I can't accept the terms of Service
![image](https://user-images.githubusercontent.com/25264879/36609561-8fff076c-18cd-11e8-8b7e-cc88d20ca6d2.png)

![image](https://user-images.githubusercontent.com/25264879/36609417-0a22eaf0-18cd-11e8-8cff-59c1f41b8770.png)

some help?

**Comment by mattsteffey** [comment]
Having the same problem.

**Comment by bih** [comment]
Hey there!

We were having issues with the dashboard on Friday night. That was resolved on Friday (and sorry for the late reply, we typically only check these during weekdays). For that reason, I'll go ahead and close the ticket. If you're still having issues, feel free to re-open the issue and we'll take a look 🙂
