### ISSUE TITLE
Does the Web API and Spotify CDN support HTTP/2?

### ISSUE THREAD

**Issue by NeoLegends** [spotify/web-api#803]
#### Endpoint(s):
* All, including the image CDN

#### Scope(s):
* None (application is not using authentication)

Our application displays a potentially long list of tracks including their cover images. This means that the users' browsers will make lots of requests to i.scdn.com. Having HTTP/2-support for the Web API and the image CDN will be beneficial for performance.

I'm not sure how easy this feature request is. I can imagine that upgrading an entire CDN for HTTP/2 support might be out of scope for a simple feature request and is more of a long term goal. So I'm posting this rather as food for thought than an actual feature request 😄.

**Comment by hughrawlinson** [comment]
Thanks for the feature request @NeoLegends - we're looking into how we can best leverage HTTP/2 to improve performance for end users, so we'll update you here if there's any changes we make.

**Comment by bih** [comment]
Hey @NeoLegends,

Thanks for reaching out. I confirmed with the Web API team that HTTP/2 is supported and it is only supported on a handful of properties hosted on our CDN - for example, with [developer.spotify.com].

I'll close this issue as it is supported in Web API. If there any updates to HTTP/2 support on our CDN, I'll post them here. Hope this helps!
