### ISSUE TITLE
How do I increase my rate limits for the Web API?

### ISSUE THREAD

**Issue by imminna** [spotify/web-api#804]
We’re developing an app to control your Spotify app, to providing user listening music
Our APP is a GLOBAL APP with lots of users daily utilisation and lot of more during some periods.

How could we do for increase this limit ?
Can we contact your personnaly for explain that ?  Or have a contact at Spotify parternship ?

**Comment by bih** [comment]
Hey @imminna,

Thanks for reaching out. If you'd like to reach out about a Spotify partnership, you can go to the "Create an App" flow in the new [Spotify for Developers Dashboard](https://beta.developer.spotify.com/dashboard/). From there, you can select to apply for a commercial integration and once approved, they can walk you through the API Rate Limits for Partners.

Hope this helps! Feel free to re-open if you have any additional questions regarding rate limiting for partnerships 🙂
