### ISSUE TITLE
Unsupported Web API?

### ISSUE THREAD

**Issue by HwanChoi** [spotify/web-api#810]
I would support some functions for my Spotify Application with Android SDK and Web API Wrapper provided by official Web Site.

Please let me know under my questions.

1. GET | /v1/search | Search for an Item
how to get profile? Web APIs only support Album, Artist, Track, Playlist.

2. GET | /v1/me/following | Get Followed Artists
how can I get User Information except Artist. It mean I can not get friend (Followed User) music list even if I followed him. there is no way to  listen my friend Playlists.

3.  functions (Discover, Genres&Moods, Top result, Appears On)
upper functions are being supported by your official Spotify Android Application.
I would want to support these functions on my developing application.
so how can I support?

Thank you!

**Comment by arirawr** [comment]
Hi @HwanChoi - thanks for reaching out!

1. Search does not support searching for User Profiles. You can get a user profile using the [Get a User's Profile endpoint](https://beta.developer.spotify.com/documentation/web-api/reference/users-profile/get-users-profile/), but you will need the `user_id` of the user you want. You can also get the [Current User](https://beta.developer.spotify.com/documentation/web-api/reference/users-profile/get-current-users-profile/).

2. Correct, that is not supported in the Web API. If you want to retrieve another user's music, you would need to have that user authorize your application to access that data by requesting the appropriate scopes.

3. Check out [the endpoints under Browse](https://beta.developer.spotify.com/documentation/web-api/reference/browse/), which give access to things like new releases, genres and moods, and other categories you'd find in the Browse tab of the Spotify application. Top Result and Appears On are not available at this time.

Hope that helps - let us know if you have any more questions!
