### ISSUE TITLE
Feature Request: retrieve geo data of where top fans are

### ISSUE THREAD

**Issue by eyoon7** [spotify/web-api#812]
Use Case:
1. Be able to find where an artists top listeners are

**Comment by hughrawlinson** [comment]
Hi @eyoon7 - could you clarify your use case? Once you've found where an artist is most popular, what would you use that data for?

**Comment by eyoon7** [comment]
We are doing a little school project where we want to do analysis on how
emerging artists popularity may change as they gain more followers/fans.
For example, if an emerging artist is from Austin, Texas, does popularity
spread outward from Texas? or does the spread of popularity not depend on
proximity to the artists hometown.

**Comment by hughrawlinson** [comment]
Thanks for the clarification @eyoon7 :) I'll keep this issue open as a feature request :)

**Comment by arirawr** [comment]
Hey there - I'm closing this as a duplicate of #188. Please see the comment on that issue.
