### ISSUE TITLE
Missing track search results when using client credentials flow when market not specified

### ISSUE THREAD

**Issue by OliverColeman** [spotify/web-api#813]
Issue found on March 8th 2018.

#### Endpoint(s):
* `GET/v1/search`

#### Scope(s):
* None (client credentials auth flow)

#### Steps to reproduce:
0. Retrieve a token via client credentials auth flow.
1. Do request with market set to AU: `curl -X GET "https://api.spotify.com/v1/search?q=artist%3A%22jack+johnson%22+album%3A%22brushfire+fairytales%22+track%3A%22drink+the+water%22&type=track&market=AU" -H "Accept: application/json" -H "Authorization: Bearer <TOKEN>"`
2. Do request with no market set: `curl -X GET "https://api.spotify.com/v1/search?q=artist%3A%22jack+johnson%22+album%3A%22brushfire+fairytales%22+track%3A%22drink+the+water%22&type=track" -H "Accept: application/json" -H "Authorization: Bearer <TOKEN>"`

#### Expected behaviour:
The second request (no market set) should return at least as many results as the first (market set to AU).

#### Actual behaviour:
The second request (no market set) returns only a single track. The first (market set to AU) returns 3 tracks.

**Comment by hughrawlinson** [comment]
Thanks for the report. This is happening because when `market` is not specified, it defaults to the `US` market, as there is no "marketless" search. This is poorly documented, so I'll make sure to clarify in our docs. Thanks!

Best,

Spotify for Developers
