### ISSUE TITLE
Recently Played Album Reporting Incorrectly for UK listeners

### ISSUE THREAD

**Issue by mattruzicka** [spotify/web-api#818]
Issue found on March 12th 2018

Endpoint(s):
GET https://api.spotify.com/v1/me/player/recently-played

We are seeing an issue with recent plays for UK listeners who are listening to the album "Ultimate" by Bryan Adams - https://open.spotify.com/album/3AUHDaXUhZimlDLFh4sTDV

Recent plays for 9 of the 21 tracks from the album are reporting the incorrect album. For example, when UK listeners listen to the first song, "Go Down Rockin'", it says they are playing the track from the album "Get Up" which is not correct.

Any clarification on what is happening here would be much appreciated. Is this a bug or expected behavior?

**Comment by hughrawlinson** [comment]
Hi @mattruzicka - sorry it took so long to get to this. It seems to be working as expected with my UK account now. I would suspect that it was a short term metadata issue that's been resolved. Please comment if this is still an issue for you :)
