### ISSUE TITLE
Notifications API 401 on player notifications

### ISSUE THREAD

**Issue by craftbyte** [spotify/web-api#819]
Issue found on March 14th 2018.

#### Endpoint(s):
* `-`

#### Scope(s):
* -

#### Steps to reproduce:
-

#### Expected behaviour:
Subscribe to Player notifications

#### Actual behaviour:
401 Unauthorized (consistently)

**Comment by hughrawlinson** [comment]
Hi @craftbyte - thanks for the request!

Real-time events via websockets are a highly-requested feature - you can check out issue #492, where we'll post any updates.

I edited your post to remove details about a private Spotify API. The public APIs we provide are fully documented on [Spotify for Developers](beta.developer.spotify.com), and the use of any undocumented APIs is against our Developer Terms of Service. We're glad to see you're enthusiastic about the platform, but the more time we spend on making sure people aren’t _"investigating"_ non-public APIs that they’re not authorised to access, the less time we can spend on making these APIs ready to be available to the public.
