### ISSUE TITLE
Retrieve larger artist header image size than 640px 

### ISSUE THREAD

**Issue by enkota** [spotify/web-api#822]
Hi,

Is it possible to retrieve a larger header image size of a particular artist? I am outputting the image onto the header of the page as full width so 640 is quite pixelated. On the actual Spotify page the image can be much higher quality.

Thanks!

**Comment by hughrawlinson** [comment]
Hi @enkota - thanks for the request. It's not possible now, but we're tracking the issue in #617 and will post any updates there.
