### ISSUE TITLE
Cannot retrieve artist genres

### ISSUE THREAD

**Issue by vgalaktionov** [spotify/web-api#823]
Issue found on March 18th 2018.

#### Endpoint(s):
* `GET /v1/artists/{artist_id}`

#### Scope(s):
* None (application is not using authentication)

#### Steps to reproduce:
1. Open the API Console
2. Call the `Get an Artist` endpoint with `id` `2GHclqNVjqGuiE5mA7BEoc` or any other Artist ID

#### Expected behaviour:
genres is an array of genre strings

#### Actual behaviour:
genres is an empty array

**Comment by lewtur** [comment]
I'm also having this issue on the `https://api.spotify.com/v1/me/top/artists/` endpoint.

**Comment by hughrawlinson** [comment]
Hi! We're looking into this, and will post any updates here.

**Comment by arirawr** [comment]
This has been resolved 🙂
