### ISSUE TITLE
GET /users/{user}/playlists returning invalid/nonexistent playlists

### ISSUE THREAD

**Issue by BloodShura** [spotify/web-api#828]
Issue found on March 24th 2018, **although** has been happening for at least 4 months.

Some playlists being retrieved are nonexistent (if you try to access their URL, they do not exist); they don't have any tracks, nor they do have a *name* entry.

Example:

```
{
    "collaborative": false,
    "external_urls": {
        "spotify": "https://open.spotify.com/user/spotify/playlist/37i9dQZF1DWTs4di2L4PuA"
    },
    "href": "https://api.spotify.com/v1/users/spotify/playlists/37i9dQZF1DWTs4di2L4PuA",
    "id": "37i9dQZF1DWTs4di2L4PuA",
    "images": [],
    "owner": {
        "display_name": "Spotify",
        "external_urls": {
            "spotify": "https://open.spotify.com/user/spotify"
        },
        "href": "https://api.spotify.com/v1/users/spotify",
        "id": "spotify",
        "type": "user",
        "uri": "spotify:user:spotify"
    },
    "public": true,
    "tracks": {
        "href": "https://api.spotify.com/v1/users/spotify/playlists/37i9dQZF1DWTs4di2L4PuA/tracks",
        "total": 0
    },
    "type": "playlist",
    "uri": "spotify:user:spotify:playlist:37i9dQZF1DWTs4di2L4PuA"
}
```

#### Endpoint(s):
* `GET /v1/users/{user_id}/playlists`

#### Steps to reproduce:
1. Request the playlists for an user, for example, *spotify*
2. At +/- 300th item (by gradually requesting the endpoint with offsets), some "ghost" playlists are returned in the *items* array response

#### Expected behaviour:
A response with... uhm... only valid playlists?

#### Actual behaviour:
A response with valid playlists, but some "ghost" ones too.

**Comment by hughrawlinson** [comment]
Hey @BloodShura - sorry it took so long to get to this issue. Thanks for the report. I've been able to reproduce it. On the `spotify` user, I found `37i9dQZF1DWVPLGy8vd7P0`, which is a ghost playlist. I'll report it to the team. In the mean time, as I'm sure you've done, you should filter these playlists on the client side.

**Comment by arirawr** [comment]
This issue should now be resolved. Thanks for your report!

Please feel free to reopen if you continue to see this issue occur.
