### ISSUE TITLE
How can I obtain the "Get a category" file json? Thank you very much

### ISSUE THREAD

**Issue by JessicaMartini212887** [spotify/web-api#829]
I can't find a function for this: https://beta.developer.spotify.com/documentation/web-api/reference/browse/get-category/. If I'd want to save a category object in a .json file, how can I do?
Sorry for my ignorance, I'm a beginner!

**Comment by hughrawlinson** [comment]
Hi! If you wanted to save the results of the 'get a category' call, you could use our [Web Console](https://beta.developer.spotify.com/console/get-browse-category/). The web console lets you fill in parameters to the call, and make the call right from your web browser. You can then paste the results into a json file. Hope that helps! Let me know if you have any more questions.
