### ISSUE TITLE
The SingUp page in the new Developer site gives a 404

### ISSUE THREAD

**Issue by avinashlahel** [spotify/web-api#830]
Issue found on March 27th 2018.

#### Endpoint(s):
* https://www.spotify.com/int/in/signup/

#### Scope(s):
* None (application is not using authentication)

#### Steps to reproduce:
1. https://www.spotify.com/int/in/signup/

#### Expected behaviour:
Signup page

#### Actual behaviour:
404  (consistently)

**Comment by arirawr** [comment]
Hi @avinashlahel , what URL is giving the 404?

**Comment by avinashlahel** [comment]
Thanks for the prompt reply

Broken URL : https://www.spotify.com/us/in/signup/

I am trying to signUp to get the Bearer token for my App, but  I am unable
to signup

**Comment by arirawr** [comment]
Thanks for the extra info. I see you're using a `in` country code, are you trying to sign up from India? Spotify is not yet available in India so you will not be able to create a Spotify account. We require a valid Spotify account to be able to log into Spotify for Developers and create Client IDs. You can sign up to receive updates on when new countries launch here: https://www.spotify.com/us/why-not-available/
