### ISSUE TITLE
Web Playback SDK: playback fails on Chrome 66

### ISSUE THREAD

**Issue by lrholmes** [spotify/web-api#831]
I've just noticed that playback has stopped working on my app, receiving this error in the console:
```
Uncaught (in promise) DOMException: play() failed because the user didn't interact with the document first. https://goo.gl/xX8pDD
```
I initially thought this was an error of my cause, but following the [link in the error](https://developers.google.com/web/updates/2017/09/autoplay-policy-changes), it seems that this is caused by Chrome's new 'prevent autoplay' feature not working nicely with the way that playback is provided by the WP SDK through an iframe. There is no 'interaction' in this iframe, so Chrome detects it as an autoplay and prevents it.

They do have a section for 'iframe delegation', which is exactly the solution and is as simple as adding `allow="autoplay"` as an attribute to the injected iframe, so it would probably be a good idea to add this to sdk script, however this part of the feature is sitting behind a flag for now, so I guess there's not much that can be done in the time being?

**Comment by arirawr** [comment]
We've just made a fix to this, it should be deployed in the next few days. Thanks for the report! 🎉

**Comment by zashu24** [comment]
@arirawr  I am using  chrome 66 and I am still having the issue. Sometimes it gives below error and sometimes it does not but html5 video is not auto playing.  Is there any other solution which I can use?
 Uncaught (in promise) DOMException: play() failed because the user didn't interact with the document first. https://goo.gl/xX8pDD

**Comment by christophgomez** [comment]
@zashu24  @lrholmes This doesn't seem to a bug with the SDK but instead a default behavior implemented by Google on Chrome. It has to do with `<video>` and `<iframe>` and `<audio>` tags in the document. It's to stop websites from creating random noise on the user's tabs. One solution is to add the property `muted=muted` to the iframe tag, which in our case is not possible and not really a desired behavior. The other solution is to

- Open `chrome://flags/#autoplay-policy`
- Set No user gesture is required
- Relaunch Chrome

This seems to get everything working the way intended.
