### ISSUE TITLE
Change order of playlists

### ISSUE THREAD

**Issue by rudiedirkx** [spotify/web-api#833]
Is there a way to save the playlists order? I see `v1/users/{user_id}/playlists/{playlist_id}/tracks` to order tracks in a playlist, but not playlists themselves. The desktop app does it, so it's a thing. Is it not an API thing?

**Comment by hughrawlinson** [comment]
Hi! This isn't available over our APIs. Our clients sort playlists by most recently edited, and allow users to drag and drop order. I can keep this issue open as a feature request, but it's not planned at the moment.

**Comment by rudiedirkx** [comment]
Yes, it's a feature request. Sounds like `PUT /v1/users/{user_id}/playlists`.

**Comment by bih** [comment]
Hello @rudiedirkx,

We're in the process of revisiting all our Web API issues, and as this particular request has no plans to be prioritised in the next 6 months (as per [our updated support process](https://github.com/spotify/web-api)) we will be closing it.

Of course, should there be updates related to sorting playlists via the API, we'll post them here for your convenience! Cheers 👍
