### ISSUE TITLE
[Chromecast] Cannot retrieve full list of user devices

### ISSUE THREAD

**Issue by plasma16** [spotify/web-api#834]
[Chromecast] Cannot retrieve full list of user devices 
Issue found on February 19th 2015.

#### Endpoint(s):
'GET /v1/me/player/devices

#### Scope(s):
Web API with authorisation token 
This affects Home-Assistant integration. 

#### Steps to reproduce:
1. Open the API Console
2. Call the `get users available devices` endpoint with `user_id` `%5E`
https://api.spotify.com/v1/me/player/devices

#### Expected behaviour:
Following devices are consistently available on the Sptofy Android App. 
Bedroom : Spotify Connect
Web Player (Chrome) : Spotify Connect
Living Room : Google Cast
Dining : Google Cast
Home : Google Cast (Group)
Party : Google Cast (Group)
![screenshot_20180401-101314](https://user-images.githubusercontent.com/1083093/38169169-6fff72aa-3595-11e8-8efa-87a7e7412c30.png)

#### Actual behaviour:
{
  "devices": [
    {
      "id": "4c969bd041fe49e9911eea7fbb831498",
      "is_active": true,
      "is_restricted": false,
      "name": "Living Room",
      "type": "CastAudio",
      "volume_percent": null
    },
    {
      "id": "9e68148388c9d666fd02d5eee69bb343585e0c64",
      "is_active": false,
      "is_restricted": false,
      "name": "Web Player (Chrome)",
      "type": "Computer",
      "volume_percent": 100
    },
    {
      "id": "3debf0a7487a215a7c2a8149c3a8d042b86bb9ff",
      "is_active": false,
      "is_restricted": false,
      "name": "Bedroom",
      "type": "Speaker",
      "volume_percent": 40
    }
  ]
}

**Comment by joshhodgson** [comment]
See #787

**Comment by arirawr** [comment]
Hey @plasma16 - thanks for the report.

As documented [here](https://beta.developer.spotify.com/documentation/web-api/guides/using-connect-web-api/#devices-not-appearing-on-device-list), some Spotify Connect devices that show in the mobile app may not appear in the Web API. The Spotify mobile app can detect Google Cast devices on your WiFi network, but the Web API does not return these devices.

Looks like a couple of folks on #787 found some clever workarounds that may be helpful for you.

**Comment by timdonovanuk** [comment]
Sorry, this is so dumb. The whole point of an API is to surface end points that work together. You are providing an end point that is "show Spotify Connect devices" but is actually broken. If the mobile and desktop app can show all Connect devices, why can't this API?

**Comment by timdonovanuk** [comment]
@joshhodgson this isn't just Chromecast devices this affects. Sonos devices exhibit the same behaviour. Even if they are playing Spotify, and are listed as Spotify Connect devices in the mobile/desktop app (so you'd agree they are thus Spotify Connect Devices!)...you cannot see them via the api that's supposed to list Spotify Connect devices. 

Apparently Spotify clients uses a secret API that we're not allowed to use?
