### ISSUE TITLE
Add the possibility to include an offset to the me/following endpoint

### ISSUE THREAD

**Issue by oskarssd** [spotify/web-api#837]
#### Endpoint(s):
* `GET /v1/me/following`

The endpoints `/v1/me/tracks` and `/v1/me/albums` takes an optional query parameter called _offset_. It would be great if `/v1/me/following` could do the same.

Then it would be possible to load only a part of the list of the followed artists. I guess it's also a good thing to allow similar behaviour for similar endpoints.

**Comment by hughrawlinson** [comment]
Thanks for the feedback @oskarssd, we'll look into it. The `/v1/me/following` endpoint uses cursor based pagination for an underlying technical reason, but it would be good to consolidate.

For clarity, it's still possible to load the entire list of followed artists by using cursor based pagination.

I'll keep this issue open as a feature request :)

**Comment by arirawr** [comment]
Hey @oskarssd,

As per our [new developer support process](https://github.com/spotify/web-api#creating-an-issue), any feature requests that have no plans to be considered in the next 6 months will be closed as wontfix.

We do not have any plans to implement this in the next 6 months and thus will close as wontfix.

We encourage you and other members of the community to continue to share use cases and your support for this feature, as it helps us prioritize features going forward. You will be able to comment on this issue even after it is closed. We will also post any updates here relating to this suggestion when they happen.
