### ISSUE TITLE
Top tracks by year

### ISSUE THREAD

**Issue by yonahforst** [spotify/web-api#838]
Is there a way to retrieve the playlist_ids for a users top track by year (e.g. https://open.spotify.com/view/2017-page or https://open.spotify.com/view/2016-page)

**Comment by arirawr** [comment]
Yes, for 2017. You can use the Get A Category's Playlists endpoint, with a category ID of `2017`. Check it out in the console here: https://beta.developer.spotify.com/console/get-category-playlists/?category_id=2017

Hope that helps!

**Comment by yonahforst** [comment]
😱 thats awesome!! will 'Your top tracks 2017' always be the first result?

**Comment by arirawr** [comment]
I'm not sure on that one so you shouldn't rely on that in your code 🙂
