### ISSUE TITLE
I cannot get my dedicated server to work with Spotify Api

### ISSUE THREAD

**Issue by CoZmicShReddeR** [spotify/web-api#839]
Issue found on April 4th 2018.

#### Endpoint(s):

Domain: cozworld.com

#### Scope(s):
Cannot connect to spotify from my dedicated server my domain is cozworld.com

#### Steps to reproduce:
Attempted these tree 
Command Prompt: curl https://api.spotify.com/v1/albums
Ping api.spotify.com
Ping 194.68.30.86
I added to my host file: 194.68.30.86    api.spotify.com 

I also tried everything with and without Firewall 

#### Expected behaviour:
A public user object as described on `https://developer.spotify.com/web-api/object-model/#user-object-public`.

#### Actual behaviour:

Command Prompt:

Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\Users\Administrator>curl https://api.spotify.com/v1/albums
curl: (7) Failed to connect to api.spotify.com port 443: Timed out

**Comment by CoZmicShReddeR** [comment]
The Addon I am using is for Xenforo https://xenforo.com/community/resources/th-spotify.6326/

**Comment by arirawr** [comment]
Hi @CoZmicShReddeR -
It doesn't look like you're using a valid `curl` command. Could you try using our Web API Console and copy the `curl` command to run on your machine? https://beta.developer.spotify.com/console/get-album/

**Comment by CoZmicShReddeR** [comment]
I used 

curl -X "GET" "https://api.spotify.com/v1/albums/4aawyAB9vmqN3uQ7FjRGTy?market=ES" -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: Bearer BQAxJV_rJXF2gw8-b5pabtzTuZagL5mFuxiH18E2zC4O3yEP33vsLIdmlNfgy_NvVHFGi1gSrFPbOfqJc7Bai6JH1fHf3S6TpRIpgZ0HXTGnPVJtTxJQpYZXSDl_SpeG14iFxcduRMHnfRqYEeNOiOaGMHMDmDhNGrcFQw"

It Timed Out

I cannot even log into the Developer Api site from my server so I believe it's being blocked somehow

![issues-spotify](https://user-images.githubusercontent.com/563611/38388939-c8f8da60-38ea-11e8-9300-da70ea297248.png)
![issues-spotify2](https://user-images.githubusercontent.com/563611/38388940-c90a36de-38ea-11e8-8cdd-f30c5b1140a7.png)

**Comment by arirawr** [comment]
Could you check what `api.spotify.com` resolves to on your server by running `dig api.spotify.com`?
Also, we had some small problems yesterday with some systems which may have contributed to this, are you still seeing the issue today?

**Comment by CoZmicShReddeR** [comment]
I still cannot log into the Developer site with my server. I can log into with my desktop but something is blocking my server from logging into the website! I am using Chrome and tried it with the Edge browser nothing works...

I tried dig api.spotify.com it was labeled an unrecognized command

###################
Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\Users\Administrator.WIN-9SQRCA2QBAF>dig api.spotify.com
'dig' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Administrator.WIN-9SQRCA2QBAF>
#######################

**Comment by CoZmicShReddeR** [comment]
Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\Users\Administrator.WIN-9SQRCA2QBAF>nslookup api.spotify.com
Server:  rdns01.us-midwest-1.nexcess.net
Address:  208.69.120.23

Non-authoritative answer:
Name:    weblb-wg.dual-gslb.spotify.com
Address:  104.154.127.47
Aliases:  api.spotify.com


C:\Users\Administrator.WIN-9SQRCA2QBAF>

**Comment by hughrawlinson** [comment]
Hi @CoZmicShReddeR - we've made a change recently that may have inadvertently fixed this issue - can you check if it's working for you now?

**Comment by arirawr** [comment]
Hey @CoZmicShReddeR, as we haven't heard from you in a while, I'll assume that means everything has been resolved! If not, feel free to reopen so we can help you out.
