### ISSUE TITLE
createPlaylist Error 404: invalid username

### ISSUE THREAD

**Issue by syan0127** [spotify/web-api#840]
```
private void createPlaylist() {
    Map<String, Object> options = new HashMap<>();
    options.put("public", false);
    options.put("name",  "playlist");
//  final PlaylistSimple playlist = getIntent().getParcelableExtra("playlist");

    spotify.createPlaylist(userId, options, new SpotifyCallback<Playlist>() {
        @Override
        public void failure(SpotifyError spotifyError) {
            Log.e("create playlist error", spotifyError.getMessage() + " :(");
        }

        @Override
        public void success(Playlist playlist, Response response) {
            Log.e("create playlist success", "success :)");
        }
    });
}
```

This is the code I have to create a playlist in the currently logged in user. However, I get error: 404 Invalid Username. I have the correct scope for "playlist-modify-private".

**Comment by arirawr** [comment]
Hi @syan0127 - how are you retrieving the `userId` that you pass to the `createPlaylist` function?

**Comment by hughrawlinson** [comment]
Hi @syan0127 - I'm going to close this issue as stale, but if you'd like help with it please feel free to ping us :)

**Comment by samryan18** [comment]
@hughrawlinson @arirawr 
I am having the exact same issue. I am able to call functions to overwrite tracks and make other changes to playlists using the same username but when I try to create a playlist I get a 404 - Invalid username. 

I also have the correct scope.

**Comment by jenxguo** [comment]
Hi @samryan18 , did you ever solve your issue? Experiencing the exact same thing here.
