### ISSUE TITLE
Many albums returning "Sorry couldn't find that" on embed

### ISSUE THREAD

**Issue by jtbayly** [spotify/web-api#844]
Issue found on April 18th 2018.

#### Endpoint(s):
Play Button embeds

#### Scope(s):
* None (application is not using authentication)

#### Steps to reproduce:
visit https://artists.spotify.com/guide/spotify-for-artists
Scroll down and see the following. Happens with a lot of bands right now.
<img width="387" alt="screen shot 2018-04-18 at 11 47 22 am" src="https://user-images.githubusercontent.com/210024/38943000-52d391f4-42fe-11e8-83a7-0bfbedcc34b0.png">

#### Expected behaviour:
a functioning embedded web player

#### Actual behaviour:
See screenshot above

**Comment by hughrawlinson** [comment]
Hi @jtbayly - we're looking into it. Just want to check that your Spotify account is registered in the US? (I guessed based on your location in your GitHub profile).

**Comment by jtbayly** [comment]
Yes. US account.

**Comment by arirawr** [comment]
Hi @jtbayly - are you still seeing this behaviour? If so, in which browser and version?

**Comment by jtbayly** [comment]
No. It's fixed, as far as I can tell.

Joseph Bayly
Pastor, *Christ Church* <https://www.christchurchcincy.com>
Editor, *Warhorn Media* <https://warhornmedia.com>
m: 812-360-5909

**Comment by arirawr** [comment]
Great, I'll close this issue then. Please reopen if you see it happening again 😃
