### ISSUE TITLE
Implicit grant flow: redirect uri gets truncated if using HashRouter in React

### ISSUE THREAD

**Issue by agatheblues** [spotify/web-api#845]
## Redirect URIs does not work as expected when using React HashRouter

Issue found on April 18th 2018.

#### Endpoint(s):
* `GET /v1/authorize`

#### Scope(s):
'user-read-private user-read-email user-library-read'

#### Steps to reproduce:
1. Whitelist http://localhost:8888/#/callback as a redirect Uri in your app
2. Call the `authorize` endpoint with the given client_id, scope, redirect_uri by following the implicit grant flow authentication
3. Check callback url in browser

Note: make sure you have React HashRouter in place

#### Expected behaviour:
Redirect uri is
`http://localhost:8888/#/callback#access_token=BQD...SB2D&token_type=Bearer&expires_in=3600&state=Xg...`

#### Actual behaviour:
Redirect uri is `http://localhost:8888/#/access_token=BQD...SB2D&token_type=Bearer&expires_in=3600&state=Xg...`

**Comment by hughrawlinson** [comment]
Hi! This is correct behaviour. As per [RFC 6749](https://tools.ietf.org/html/rfc6749#section-3.1.2):

> The [redirection] endpoint URI MUST NOT include a fragment component.

Perhaps you could use react router instead? https://github.com/ReactTraining/react-router

Or, you could redirect to a separate page that saves the access token to localstorage and redirects to your react app, which could then read the token from storage.

Hope that helps!

**Comment by agatheblues** [comment]
I figured it has been designed like this on purpose. For those we the same issue, I solved it as you said by saving the token in the localStorage, and passing the path (the route to redirect to after the callback) in the state (saved in localStorage as well). 

Thanks !
