### ISSUE TITLE
Web Playback SDK - AudioContext

### ISSUE THREAD

**Issue by leroy** [spotify/web-api#846]
Hi,

I would like to use the Web Audio API to visualize the audio data of the song that's currently playing. I have noticed that this is currently not supported. Any thoughts on this?

Thank you for this amazing platform!

**Comment by mental32** [comment]
I have not used the web playback SDK as much but i believe you can implement this yourself, there is an endpoint for [audio analysis](https://beta.developer.spotify.com/documentation/web-api/reference/tracks/get-audio-analysis/) as long as you have access to the track id of the current song playing

**Comment by hughrawlinson** [comment]
Hi! As @mental32 noted, the audio analysis and audio features endpoints are the best way of getting detailed information about the audio of a track. The Web Playback SDK doesn't hook in to Web Audio. Additionally, the issue tracker for the Web Playback SDK is [here](https://github.com/spotify/web-playback-sdk). Hope that helps!
