### ISSUE TITLE
Issue in Spotipy's method search()

### ISSUE THREAD

**Issue by JulianFM** [spotify/web-api#847]
We have had a problem with Spotipy's search() method for a few hours now. It continually returns a 404 error even though it previously returned correct results. 

Thanks

**Comment by NaturalFigurehead** [comment]
Same results for the search endpoint in my .NET app as well. Checked a couple other websites that use Spotify API and nothing can be searched on them either.

**Comment by hughrawlinson** [comment]
Hi! Are you using the Client Credentials authorization flow to get your tokens?

**Comment by NaturalFigurehead** [comment]
@hughrawlinson yes

**Comment by hughrawlinson** [comment]
We discovered the issue and deployed a fix. Can you check if it's working for you now?

**Comment by JulianFM** [comment]
@hughrawlinson yes, this problem begin this morning (in Spain), aprox. 4 or 5 hours ago. I think is not problem about my code...

![abc](https://user-images.githubusercontent.com/24258356/39185272-f365b710-47c6-11e8-82e7-83a898622ab1.png)

**Comment by JulianFM** [comment]
@hughrawlinson yes, it works! thanks

**Comment by hughrawlinson** [comment]
Great! :)
