### ISSUE TITLE
Preview url fine seek/scrubbing

### ISSUE THREAD

**Issue by ridhwaans** [spotify/web-api#850]
I'm sorry if this isnt the correct place, but how does the API serve the preview_url so that clicking time on a track player or html5 audio will fast forward or rewind it?  

example preview url  
`preview_url`: `https://p.scdn.co/mp3-preview/bb0a310830636ebf8e5f6a1fa03d129a9724f7ec?cid=774b29d4f13844c495f206cafdad9c86`  

I have a readstream for a music file in the back like so but I am unable to reproduce the same behaviour  

````
function(req, res) {  
  const path = <path_to_track_file>
  const stat = fs.statSync(path)
  const head = {
      'Content-Type': 'audio/mpeg',
      'Content-Length': stat.size
  }
  res.writeHead(200, head);
  fs.createReadStream(path).pipe(res);
});
```

**Comment by hughrawlinson** [comment]
Hi @ridhwaans - you should be able to put the preview url into a html5 audio element with controls enabled and scrub to a certain position (or use the DOM element API to scrub).

`<audio src="{your preview url}" controls/>`

Hope that helps!
