### ISSUE TITLE
Block Spotify APP through a Web security service solution from Symantec

### ISSUE THREAD

**Issue by JuanPerezSymantec** [spotify/web-api#851]
Hello after contacting the support@spotify.com they redirected me here.
First of all my name is Juan Perez and I work for Symantec. I work in the support area of a Web security filter that our customers use.
Right now one particular has come to me wanting to block the Spotify application through our product.

Initial I was able to block the URLs "spotify.com" and "support.spotify.com" the thing is that the application keeps running. What I would like to know if there is any way that you can provide me with the different URLs that the application reaches out to in order to play the music.

Our product basically is a Web security filter that scans traffic on port 80 and 443 and the user is able to create specific rules for that traffic to allow/block it as they see needed.

If you require any further information please let me know as I most interested in a way to get the application blocked for them.

Best regards

Juan M Perez

**Comment by jscholes** [comment]
This is the issue tracker for Spotify's Web API for third party developers, so the support team weren't correct in directing you here.  Additionally I don't think you're going to have much luck asking Spotify to help you do your job when, as in this case, if you do your job correctly it means less service usage for them.  My suggestion is to crack open your nearest packet sniffing tool.

**Comment by wolkenschieber** [comment]
This is the most pathetic issue, I can imagine.

**Comment by JuanPerezSymantec** [comment]
jscholes thanks for your reply. I guess they pointed me here from that email address and they were wrong.No worries I will keep looking to see if we are able to find the right URL as most of the ones that come from TCPview and Wireshark don't seem to be working.
Thanks

**Comment by jscholes** [comment]
Additionally, if you log into Spotify and then open up %localappdata%\spotify\Browser\Local Storage (on Windows), you'll see a whole list of URLs for which the browser inside the Spotify application has created local storage databases.  Blocking all of those, I'm sure, would go a long way in making the company's employees happier and more productive /S
