### ISSUE TITLE
Getting additional Artist's Info and Images (as shown in the "About" section)

### ISSUE THREAD

**Issue by RafaPolit** [spotify/web-api#852]
Get additional Artist's Info and Images through the API

#### Endpoint(s):
* `GET /v1/artists/{id}`

#### Scope(s):
* None (application is not using authentication)

#### Expected behaviour:
The 'about' info and all the different images related to the artist should be retrieved.   If you go to an Artists profile / about in the Spotify app, there are usually several pictures from one artist, as well as a nice bio.

This should be accessible through the API.  If I am developing a different or simplified front for the music info, this is interesting data, and should be part of the public accessible info.

#### Actual behaviour:
Only the main image is retrieved in several sizes, no bio available.

**Comment by hughrawlinson** [comment]
Thanks for the request @RafaPolit. #207 and #617 seem to already request this, so I'll close this issue as a duplicate - you should follow those issues for any updates. Thanks!
