### ISSUE TITLE
The iOS SDK is explicitly prohibited from use for broadcast aka “listen together” apps

### ISSUE THREAD

**Issue by markusvtjohansson** [spotify/web-api#854]
Spotify has updated their iOS SDK page and added the sentence "The iOS SDK is explicitly prohibited from use for in-car apps, alarm clock apps, ring-tone apps, voice-assistants, broadcast aka “listen together” apps, and to create offline experiences for wearable or other devices." In my opinion, this is quite vague, especially the "broadcast aka listen together apps" part. My app, which is currently on the App Store, lets users listen together using the tracks' ID's and the users positions in the tracks, meaning that they basically listen to the same song as their friends at the same time. Does this fall into the "broadcast" or "listen together" apps, or is this way of doing it permitted? I mean, it isn't really "broadcasting" considering that the users just listen to music normally, only difference being that their position, and the song playing, are the same as their friends'. 

If this would mean the end of my app I would be absolutely devastated, considering that I have been working on it for over a year. I refuse to believe that is true, but I would like it if someone could explain more precisely what apps falls into "broadcast aka listen together apps" so I understand how things actually look. Thanks.

**Comment by arirawr** [comment]
Hi @markusvtjohansson, 

All use of the Spotify Platform falls under the [Developer Terms of Service](https://beta.developer.spotify.com/terms). I'm not able to interpret those terms for you, and I recommend consulting a lawyer to determine whether your usage falls under those restrictions.

If you are developing a commercial (monetized) application, I recommend submitting an application for commercial approval (you can do this by clicking "Create a Client ID" on your Spotify for Developers Dashboard and selecting "Yes" when asked about commercial integrations. A member of the partnerships team will then be able to follow up about your integration.

As this is the issue tracker for our Web API, I'm going to go ahead and close this issue.

(PS - have you checked out the [new iOS App Remote SDK](https://beta.developer.spotify.com/documentation/ios-app-remote)?)
