### ISSUE TITLE
Unable to retrieve my spotify profile data from api.spotify.com/v1/me

### ISSUE THREAD

**Issue by kapilbahadur** [spotify/web-api#855]
Issue found on April 28th 2018.
Sat, 28 Apr 2018 10:37:04 GMT

#### Endpoint(s):
* `GET api.spotify.com/v1/me

#### Scope(s):
* None (application is not using authentication)
* 

#### Steps to reproduce:
1. Open the API Console
2. Copied my Credentials, and secret
3. grant_type = 'client_credentials'
4. scope="user-read-private"
5. Submit a GET request on /v1/me
6. Got a 403 error with Empty Body

After Remove grant_type
1. Got a 400 error with body "Only valid bearer authentication supported" even though my authorisation is "Bearer <TOKEN>"

**Comment by arirawr** [comment]
Hi @kapilbahadur - for getting user data, like /me, you cannot use access tokens from the Client Credentials Flow. You will need to use either the Implicit Grant Flow (if you have a static site / front end only) or the Authorization Code Flow (if you have a server). Access tokens from either flow will work as expected :)

Read up on the differences between the flows here: https://beta.developer.spotify.com/documentation/general/guides/authorization-guide/
Code sample for implicit grant flow: https://glitch.com/edit/#!/spotify-implicit-grant
Code sample for authorization code flow: https://glitch.com/edit/#!/spotify-authorization-code
