### ISSUE TITLE
/me endpoint no product field for some users

### ISSUE THREAD

**Issue by bmachlin** [spotify/web-api#856]
Issue found on April 29th 2018.

#### Endpoint(s):
* `GET /v1/me`

#### Scope(s):
* user-read-private

#### Steps to reproduce:
1. Open the API Console
2. Call the `me` endpoint for a user that's part of a family plan

#### Expected behaviour:
Normal endpoint JSON results, including the 'product' field

#### Actual behaviour:
It seems for some users, there is no 'product' field returned.

I've only seen it for one user that I'm test with. But they're part of a family plan and when I get user info from the /me endpoint with their account logged in, there is no product info (e.g. premium, free, open). It might also be relevant that they log in through Facebook.

**Comment by hughrawlinson** [comment]
Thanks for the report @bmachlin. I'll look into it.

**Comment by bih** [comment]
Hello @bmachlin,

We're in the process of revisiting all of our Web API issues as [per our new developer support process](https://github.com/spotify/web-api).

In this particular case, I have not been able to reproduce your bug and it might have been resolved in the meantime. I will close it as <kbd>inactive</kbd> as I cannot confirm it has been resolved, and we haven't received further reports regarding the `product` column not returning in the `GET /v1/me` endpoint.

Of course, if you're continuing to have bugs related to this, feel free to create a new issue and reference this (#856) - we'll be happy to investigate!

Cheers 👍
