### ISSUE TITLE
Wrong endpoint listed in docs for /previous.

### ISSUE THREAD

**Issue by kschultee** [spotify/web-api#861]
#### Endpoint(s):
* `POST /v1/me/player/previous`

#### Doc(s):
* Listed as 'POST /v1/me/player/seek'

Wrong endpoint listed for player usage 'Skip User’s Playback To Previous Track'.

**Comment by arirawr** [comment]
Nice catch @kschultee ! I've gone ahead and fixed that up. Let me know if you see any more issues 😄
