### ISSUE TITLE
create-new-playlist not working

### ISSUE THREAD

**Issue by lchaggard** [spotify/web-api#864]
For a final project, I'm trying to play with Spotify's various APIs through Python to create, analyze and save a summery playlist by generating recommendation songs, creating a playlist, and adding songs to it. I got the recommended ones to work, but I'm stuck with the one where you create a new playlist and add songs to it. For awhile it wasn't throwing any errors at all or giving any results, and now it's giving a 403 error.

Issue found on May 3rd, 2018.

#### Endpoint(s):
* `POST https://api.spotify.com/v1/users/{user_id}/playlists`

#### Scope(s):
* playlist-modify-private

#### Expected behaviour:
A new empty playlist is made in the user's library.

#### Actual behaviour:
403 error - insufficient client scope.

This is what my code looks like so far. I know there's something I'm not understanding about the parameters, and I'm also unclear how to plug in my username.

```
newtoken = "a token that's retrieved from the webpage"

newheaders = {'Authorization': "Bearer {}".format(newtoken),
              "Content-type": "application/json"}

newdata = {"name": "my summer playlist",
              "description": "the best playlist for summer!",
              "public" : "false"}

newplaylist = rq.post("https://api.spotify.com/v1/users/{user_id}/playlists", 
                        headers=newheaders, params=newparams, data=newdata).json()
```

I realize this is super hacky and totally not how it would properly work in an app. I'm just using Python and Jupyter notebook.

**edit: formatting of code**

**Comment by hughrawlinson** [comment]
Hi @lchaggard - that sounds like an awesome hack project! Could you confirm which Authorization Flow you're using to generate your access token?

**Comment by arirawr** [comment]
Hi @lchaggard - I'm going to close this as we haven't heard from you in a while! Please feel free to reopen if you're still having trouble.

**Comment by mmmichl** [comment]
A note to fellow developer, who might run in the same issue.

By default the playlists are _public_, not private. Therefore you need the scope `playlist-modify-public`, the request won't work with only `playlist-modify-private` applying to a public playlist.

This is in a way confusing, as all the reading works and you assume you have the right scope. But I guess it works, because they playlist is public by default.
