### ISSUE TITLE
Add Tracks to a Playlist not working

### ISSUE THREAD

**Issue by justinkb88** [spotify/web-api#867]
I can no longer add a track to a playlist. I have used this API for over a year now on a web app and I noticed it stopped working on May 4, 2018.

Issue found on May 4, 2018.

#### Endpoint(s):
* POST https://api.spotify.com/v1/users/{user_id}/playlists/{playlist_id}/tracks

#### Scope(s):
* playlist-modify-public
* playlist-modify-private

#### Steps to reproduce:
Execute cURL via PHP using format documented on https://beta.developer.spotify.com/console/post-playlist-tracks/

#### Expected behaviour:
Track specified in cURL call should be added to given position in playlist specified

#### Actual behaviour:
No errors given but no track is added. 

Additional notes:
1. I can still remove a track documented on https://beta.developer.spotify.com/console/delete-playlist-tracks/ from the same server without issue.
2. When using the "Try It" function on https://beta.developer.spotify.com/console/post-playlist-tracks/, the track is added successfully. Executing the same curl call from my server fails however.

**Comment by jscholes** [comment]
The fact that it works in the console but not in your code suggests that the problem is with the latter.  Could you post the code you're using?  Additionally, can you get it to work using the curl command generated by the console when using curl directly, rather than via PHP?

**Comment by justinkb88** [comment]
`curl -X "POST" "https://api.spotify.com/v1/users/team3stone/playlists/5oGhnClMLEBoACesKLKXWz/tracks?position=3&uris=spotify%3Atrack%3A0gD6lWJhbXHWNVwQziSVvl" -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: Bearer BQBbl22vLDUovgZvCZODH18wzwGCnHTYjTQEtfb7GfUWhM8dXZcqabEbiqe9mWpXO5b-BVuJZc9A6ujZ5eTld5dwjZ6k86JF2VxB2rXvxH5giho6hc3Z0oClplwtth0R3_k00XRSfjprCS9En9-CBnewHH42MKq99DkcJHySGkl4R71UJ9UqdRDJvBewxvUHVXkpMtAByR34"`

Above is the code I just generated from the console. It correctly adds the track to the playlist when I use the "Try It" button. Copying this code and running directly from my Windows machine results in the following. Again, as a control, the cURL code to remove a track works correctly on my Windows machine.

```
<!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 411 (Length Required)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>411.</b> <ins>ThatΓÇÖs an error.</ins>
  <p>POST requests require a <code>Content-length</code> header.  <ins>ThatΓÇÖs all we know.</ins>

```

**Comment by jscholes** [comment]
The request will work if you include a Content-Length header, set to 0.  I thought most libraries would include this by default, but I guess curl doesn't.

The main problems here seem to be:

1. As with the Content-Type header, the Web API should ignore the lack of a Content-Length header if the URIs and positions are sent in the query string rather than the request body;
2. Alternatively, the API console and documentation should make it clear that the Content-Length header is always required if this is a recent change.

**Comment by jscholes** [comment]
As an aside, the access token you posted above has now expired, but as a rule you shouldn't post valid tokens here.  Within the window when that token is valid, the token is publically available on the Internet and can be used to access your account.

**Comment by justinkb88** [comment]
@jscholes Thank you!!! That did the trick. I'm curious now as to where to request the API console and documentation be updated to reflect this change...
