### ISSUE TITLE
/v1/me/player no longer returning progress_ms value?

### ISSUE THREAD

**Issue by michaelherger** [spotify/web-api#870]
Issue found on May 9 2018.

#### Endpoint(s):
* `GET /v1/me/player`

#### Steps to reproduce:
1. call the `player`endpoint aus authorized user
2. get player status back, incl. playing track information etc.
3. `progress_ms` is always zero

#### Expected behaviour:
`progress_ms` is supposed to return the current position within the track

**Comment by AndyMardell** [comment]
+1

Started happening yesterday (8th May) and it was definitely working before this. 

Progress returns 0 for my Amazon Echo _and_ my Dot.
Progress returns correctly for my desktop app and phone.

**Comment by gahisee** [comment]
yes, starting sometime yesterday, my app is seeing "progress_ms" of 0.
tried it with Console, same problem.
come on, Spotify, you are a big public boy now;  test before deploying....

**Comment by hughrawlinson** [comment]
Hi! I've repro'd the error, and reported it. Will update here when there's news.

@gahisee let's keep it respectful on the tracker :)

**Comment by michaelherger** [comment]
Thanks @hughrawlinson!

Could there be a bigger caching issue on your end, as I sometimes wouldn't get new track information either. It would always report the same old track as being playing.

**Comment by hughrawlinson** [comment]
@michaelherger I'm not sure that issue is related. Could you provide repro steps, including which devices/clients you're using to do the playback?

**Comment by michaelherger** [comment]
@hughrawlinson - it's a librespot based implementation... But I think the reason I don't get updated track information is that librespot crashes. Not "your" problem, but likely caused by the changes on your end?

**Comment by hughrawlinson** [comment]
@michaelherger @AndyMardell @gahisee we've pushed a fix, and this bug is fixed! 🎉

@michaelherger librespot is not an approved part of Spotify's offering. It could stop working at any moment, we don't support it.

I'll close this issue because it's fixed 😄

**Comment by michaelherger** [comment]
Thanks @hughrawlinson. And understood about librespot - that's why I said "not your problem" ;-). (BTW. it's not librespot either, but my own code...)
