### ISSUE TITLE
need to use ios, android api of spotify

### ISSUE THREAD

**Issue by nishantsethibrv** [spotify/web-api#871]
Issue found on February 19th 2015.

#### Endpoint(s):
* `GET /v1/users/{user_id}`

#### Scope(s):
* None (application is not using authentication)

#### Steps to reproduce:
1. Open the API Console
2. Call the `get-users-profile` endpoint with `user_id` `%5E`

#### Expected behaviour:
A public user object as described on `https://developer.spotify.com/web-api/object-model/#user-object-public`.

#### Actual behaviour:
500 Server Error (consistently)

**Comment by hughrawlinson** [comment]
Hi @nishantsethibrv - can you please describe the issue? The Android & iOS SDKs are available for use, and documented [on our website](https://beta.developer.spotify.com/documentation/ios-sdk/)
