### ISSUE TITLE
Downloading music for ringtones

### ISSUE THREAD

**Issue by MadManda1972** [spotify/web-api#872]
Would love to use my downloaded music, as personally set ringtones in my contacts.
But as my phone is a Samsung Galaxy S8+. Only downloaded tunes available from the samsung app store. Sadly that store is not necessarily a safe cyber attack free zone. 
Any suggestions?

**Comment by hughrawlinson** [comment]
Hi @MadManda1972! As per the [Developer Terms of Use](https://beta.developer.spotify.com/terms/), you shouldn't use the Spotify Platform for acquiring ringtones.
