### ISSUE TITLE
Search for artist/track beginning with string

### ISSUE THREAD

**Issue by markusvtjohansson** [spotify/web-api#874]
In Spotify's own applications, if you for instance search for "rih", the artists showing upp will be Rihanna, Rich the Kid, etc. However, when I use the Spotify API search endpoint I receive results exactly matching, or containing, the search string, which in this example would return nothing since there is no artist called "rih". Is it possible to achieve the same behavior as in Spotify's own application using the API, that is searching with a partial string and retrieving results that begin with it?

**Comment by markusvtjohansson** [comment]
Wow thank you so much, it works perfectly!

**Comment by jsimonsson** [comment]
👍
