### ISSUE TITLE
Useage Question

### ISSUE THREAD

**Issue by joecaraccio** [spotify/web-api#875]
Hi Everyone,

I know this isn't a technically question, but I have been having a hard time getting a response for this question.

I noticed on the Android SDK: https://beta.developer.spotify.com/documentation/android-sdk/
There is a note that says: 
**_"The Android SDK is explicitly prohibited from use for in-car apps, alarm clock apps, ring-tone apps, voice-assistants, broadcast aka “listen together” apps, and to create offline experiences for wearable or other devices."_**

So does an app like this exist: http://flomusic.com/ with some sort of special partnership with spotify? As someone that wants to implement similar features I am curious if I can legally, or if I need special permission.

Any help would be huge!

**Comment by hughrawlinson** [comment]
Hi @joecaraccio - we're unable to interpret our [Developer Terms of Use](http://beta.developer.spotify.com/terms) for you. All integrations must comply with our terms. If you're interested in applying for extra licenses, please register a commercial client id in [our dashboard](https://beta.developer.spotify.com/dashboard/applications) to send your request to our commercial partnerships team.

**Comment by joecaraccio** [comment]
@hughrawlinson Okay I guess that kinda answers my question. Its clear they had extra licenses right though?

**Comment by joecaraccio** [comment]
I can't find a contract for the commercial partnerships team..

**Comment by hughrawlinson** [comment]
@joecaraccio I can't comment on another company. By clicking 'Create a Client ID' and indicating that your Spotify integration is commercial, you'll be presented with a form that will go to our commercial partnerships team 😄
