### ISSUE TITLE
/me/top/{type} endpoint returning 403

### ISSUE THREAD

**Issue by andrew-schultz** [spotify/web-api#877]
Title: `/me/top/{type}` endpoint returning 403 for requests made from authorized app
Issue found on February 19th 2015.

#### Endpoint(s):
* `GET /v1/me/top/{type}`

#### Scope(s):
* streaming, user-top-read, user-read-birthdate, user-read-email, user-read-private

#### Steps to reproduce:
( test site link: https://bandbrowser.herokuapp.com/ )
1. App requests valid token using Client ID and Client Secret
2. User 'logs in' / goes through authorization flow to get a valid access_token for use in queries
3. User clicks within the circle displayed on screen
4. Request to `GET /v1/me/top/{type}` endpoint is made

#### Expected behaviour:
A users top artists / tracks object is returned as described in  `https://beta.developer.spotify.com/documentation/web-api/reference/personalization/get-users-top-artists-and-tracks/`.

#### Actual behaviour:
403 Error

***NOTE: using the console and sending CURL's through the command line / making requests through postman using the same token thats requested through the authorization flow returns the expected response from the api. The issue seems to only occur when requests are made to the endpoint from the app itself. 

request code for reference:

```
var getTopList = function() {
  return new Promise( ( resolve, reject ) => {
    var xmlHttp = new XMLHttpRequest();
    xmlHttp.open( 'GET', 'https://api.spotify.com/v1/me/top/artists', true );
    xmlHttp.setRequestHeader( 'Accept', 'application/json' );
    xmlHttp.setRequestHeader( 'Content-Type', 'application/json' );
    xmlHttp.setRequestHeader( 'Authorization', "Bearer " + token )
    xmlHttp.onreadystatechange = function() {
      if ( xmlHttp.readyState == 4 && xmlHttp.status == 200 ) {
        var results = JSON.parse( xmlHttp.response );
        resolve( results );
      }
      else if ( xmlHttp.readyState == 4 && xmlHttp.status != 200 ) {
        console.log( 'error' );
      }
    };

    xmlHttp.send( );
  } );
};
```

**Comment by hughrawlinson** [comment]
Hey @andrew-schultz - looks like you're not using the same token in your request that you receive from the Authorization Code flow. Could you check how you're getting the token there?
