### ISSUE TITLE
player_state_changed event fires multiple times

### ISSUE THREAD

**Issue by cbreezier** [spotify/web-api#878]
Issue found on May 13th 2018.

#### Endpoint(s):
* `PUT v1/me/player/play?device_id={device_id}` https://beta.developer.spotify.com/documentation/web-api/reference/player/start-a-users-playback/

#### Scope(s):
* user-modify-playback-state

#### Steps to reproduce:
1. Play a song using the above endpoint
2. Print out the contents of the `player_state_changed` event (ie `  player.addListener('player_state_changed', state => { console.log(state); });
`)

#### Expected behaviour:
A single event is fired with the correct track duration as per `https://beta.developer.spotify.com/documentation/web-playback-sdk/reference/#event-player-state-changed`.

#### Actual behaviour:
Two state change events are fired. Both are exactly identical (position = 0, paused = false, track_window shows the same current_track) except the first event has a different song duration (24ms shorter - seems like a constant number) and the timestamps of the events are different.

**Comment by bih** [comment]
Hello @cbreezier,

As this issue only relates to the [Web Playback SDK](https://github.com/spotify/web-playback-sdk/issues) and not to the Web API, I'm going to close this as <kbd>offtopic</kbd>. Please open it in that particular issue tracker.

Cheers!
