### ISSUE TITLE
preview_url returns null depending on context

### ISSUE THREAD

**Issue by kaliseo** [spotify/web-api#879]
preview_url unavailable depending context

Issue found on May 15th 2018.

#### Endpoint(s):
* `GET /v1/search`
* `GET /v1/users/{user_id}/playlists/{playlist_id}`

#### Scope(s):
* Oauth

#### Steps to reproduce:
1. Call search API
2. Call playlist API

preview_url is available for some tracks in search, but not in playlist or in playlist, but not in search

#### Expected behaviour:
sample track : spotify:track:32SkyVfs7k7tTsxoUjUEDa
preview_url:"https://p.scdn.co/mp3-preview/b5f28aeffc451a40f7acc5ad94e77ac74db320f6?cid=..."
_Available in search, but not in playlist_

#### Actual behaviour:
sample track : spotify:track:32SkyVfs7k7tTsxoUjUEDa
preview_url:null
_Available in search, but not in playlist_

**Comment by bih** [comment]
Hello @kaliseo,

I'll close this as this is expected behaviour. We mention throughout the Web API as follows:
> A link to a 30 second preview (MP3 format) of the track. Can be `null`

There was an error where it did not mention the `Can be null` in the [Web API Object Model](https://developer.spotify.com/documentation/web-api/reference/object-model/) and that is now fixed. Your application should support to check if the `preview_url` is not `null`. Hope this helps!

**Comment by kaliseo** [comment]
Hi there,

I understand that, but.. it did not answer to the question : Why is it null
depending on wich API is called ? In playlist API it's available for
specific ID, but not in search. Weird.

Best regards,

Thierry

Thierry @ Gmail


Le lun. 6 août 2018 à 14:08, Bilawal Hameed <notifications@github.com> a
écrit :

**Comment by bih** [comment]
Hello @kaliseo,

There could be numerous reasons why it may return `null`. In those cases, our API honours those reasons and thus will return `null. By documenting it, hopefully yourself and other developers are able to build experiences around this particular edge case.

Hope this clears things up!
