### ISSUE TITLE
Remove track from playlist not working properly for certain tracks

### ISSUE THREAD

**Issue by Integritus** [spotify/web-api#88]
Cannot remove some track from a playlist.

Issue found on July 20th 2015.

Endpoint(s):DELETE https://api.spotify.com/v1/users/{user_id}/playlists/{playlist_id}/tracks

Scope(s): playlist-read-private playlist-modify-public playlist-modify-private

Steps to reproduce: Use the API Console
with cURL:
curl -X DELETE "https://api.spotify.com/v1/users/1243337728/playlists/10c82cBoljlRUe5bCAiPnf/tracks" -H "Accept: application/json" -H "Authorization: Bearer BQAS68btxnZgv8WYuJt9bOtqrysiqlOcOIyGdSdI5GAbRMJNCQ7wtrWFuBwEz3r7r37xAWYm-fY60D3_HZOwnSRnyX3HFP_a9G5IlNMWczAKI39KOxuwWkweCjvwRyVfPzhxvuN0b6i8fTUui7H7OLR5IxkWLc8KhtGFBkUidjiH0mkUINsxpD21OXic2R3xOZrjrAaAdPEkwEpFIoJaMCEcLT5qv7ACtaTaZSg3KPJSzJD72XxexO4" -H "Content-Type: application/json" --data "{\"tracks\":[{\"uri\":\"spotify:track:3aN2V18W3EiW7eg5tHALpF\"}]}"

Request:
DELETE /v1/users/1243337728/playlists/10c82cBoljlRUe5bCAiPnf/tracks HTTP/1.1
Host: api.spotify.com
Content-Length: 61
Accept-Encoding: gzip, deflate, compress
Accept: application/json
User-Agent: Spotify API Console v0.1
Content-Type: application/json
Authorization: Bearer BQAS68btxnZgv8WYuJt9bOtqrysiqlOcOIyGdSdI5GAbRMJNCQ7wtrWFuBwEz3r7r37xAWYm-fY60D3_HZOwnSRnyX3HFP_a9G5IlNMWczAKI39KOxuwWkweCjvwRyVfPzhxvuN0b6i8fTUui7H7OLR5IxkWLc8KhtGFBkUidjiH0mkUINsxpD21OXic2R3xOZrjrAaAdPEkwEpFIoJaMCEcLT5qv7ACtaTaZSg3KPJSzJD72XxexO4

Response:
HTTP/1.1 200 OK
Access-Control-Allow-Headers: Accept, Authorization, Origin, Content-Type
Access-Control-Max-Age: 604800
X-Content-Type-Options: nosniff
Content-Encoding: gzip
Transfer-Encoding: chunked
Access-Control-Allow-Credentials: true
Strict-Transport-Security: max-age=31536000;
Keep-Alive: timeout=600
Server: nginx
Connection: keep-alive
Cache-Control: private, max-age=0
Date: Tue, 21 Jul 2015 03:41:57 GMT
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, POST, OPTIONS, PUT, DELETE
Content-Type: application/json

{
  "snapshot_id" : "LxPC4bLMt6z9Z3Y78pxjkFnU5A+jG2eA3Sd2nl6MLb6sSzFixr0qlbdX/hf1mX5x"
}

Expected behaviour: All instances from that track should have been deleted from the playlist

Actual behaviour: 200 OK, It says it was completed but the track are still in the playlist.

**Comment by asmitter** [comment]
If you do a request to read the tracks from that playlist, you can see that it doesn't include any instances of `spotify:track:3aN2V18W3EiW7eg5tHALpF`.
The URI you are passing resolves to "We're in this Together" by "Nine Inch Nails", which *does* exist in the playlist but under the URI `spotify:track:5wrGBHi7aaUkgCbInkta8T`. This is a symptom of [track relinking](https://developer.spotify.com/web-api/track-relinking-guide/) where what appears to be a single song can exist under several URIs.

To solve, make sure that you are attempting to remove the original URI, which can be found when reading the playlist object.

It's also important to ensure that if the track item has a "linked_from" object, you should use the URI in there. More details are in that guide linked above.

**Comment by Integritus** [comment]
I had used spotify:track:5wrGBHi7aaUkgCbInkta8T too which was provided by the playlist endpoint, but that had the same result, but after reading the link you sent I tried the uri from "linked_from" and that did the trick. Thanks
