### ISSUE TITLE
Spotify playlist embedding without Google Analytics

### ISSUE THREAD

**Issue by galileomc** [spotify/web-api#882]
Hallo

we have an embedded spotify playlist on our website and I just realized that Google Analytics is loaded into the iframe of the spotify playlist. Due to the new privacy rules of the EU I want to get rid off Google analytics on our website and my question is if this is possbile? Or do I better remove the Spotify playlist completely?

Thanks for your answer

Daniel

**Comment by bih** [comment]
Hi @galileomc,

Our embeds are GDPR compliant and respect the user's privacy. If you prefer to show the tracks in your playlist without using an embed, you can use the [Get a Playlist's Tracks](https://developer.spotify.com/documentation/web-api/reference/playlists/get-playlists-tracks/) Web API.

Hope this helps. I'm going to close this as this isn't an issue, but feel free to re-open if there's anything else related to this matter 👍
