### ISSUE TITLE
Currently-Playing returns 500 error when playing podcasts

### ISSUE THREAD

**Issue by sauercrowd** [spotify/web-api#887]
Issue found on February 19th 2015.

#### Endpoint(s):
* GET /v1/me/player/currently-playing

#### Scope(s):
* user-read-currently-playing

#### Steps to reproduce:
1. Start playing a podcast episode (e.g. Software Engineering Daily - ContainerSecurity)
2. Make an authenticated call with the correct scopes to /v1/me/player/currently-playing
3. Check the response

#### Expected behaviour:
The response contains body contains a JSON describing the currently played podcast episode

#### Actual behaviour:
500 Server Error (consistently)
```
{
  "error": {
    "status": 502,
    "message": "Backend respond with 500"
  }
}
````

**Comment by arirawr** [comment]
Hey @sauercrowd - we don't support podcasts in the Web API currently. I'm going to close this specific bug as wontfix for now - you can follow issue #551 for updates on podcast support in general.
