### ISSUE TITLE
Authorization 

### ISSUE THREAD

**Issue by imminna** [spotify/web-api#889]
Issue found on May 22th 2018.

#### Expected behaviour:
LINK: https://accounts.spotify.com/authorize/?client_id=fde7df28eb524228a814e716d195bfd0&response_type=code&redirect_uri=http://open.spotify.com/browse/featured&scope=playlist-read-private%20playlist-read-collaborative%20playlist-modify-public%20playlist-modify-private%20streaming%20ugc-image-upload%20user-follow-modify%20user-follow-read%20user-library-read%20user-library-modify%20user-read-private%20user-read-birthdate%20user-read-email%20user-top-read%20user-read-playback-state%20user-modify-playback-state%20user-read-currently-playing%20user-read-recently-played

when I put LINK in my own embedded browser(C#), then the browser is no response,
howerver it still work last week, I didn't revise my program.

**Comment by arirawr** [comment]
Hi @imminna! Looks like you have an invalid redirect URI. You have it set in the URL as `http://open.spotify.com/browse/featured`. This URI needs to have been entered in the Redirect URI whitelist, which you can edit by clicking "Edit Settings" on the application from [your Dashboard](https://beta.developer.spotify.com/dashboard). The values must exactly match, including upper or lowercase, terminating slashes, and such.

**Comment by imminna** [comment]
hi @arirawr , 
It seems that it is not the reason for the redirect URI.

This link works fine in Chrome browser
When I open the link via my own embedded browser(C#), it happend nothing, howerver it still work last week.

It seems to be a problem with javascript compatibility

**Comment by imminna** [comment]
@arirawr 
BTW, I change the link as below,
https://accounts.spotify.com/authorize/?client_id=984c5ee4db4e43a9a565ae309378af34&response_type=code&redirect_uri=http://open.spotify.com/browse/featured&scope=playlist-read-private%20playlist-read-collaborative%20playlist-modify-public%20playlist-modify-private%20streaming%20ugc-image-upload%20user-follow-modify%20user-follow-read%20user-library-read%20user-library-modify%20user-read-private%20user-read-birthdate%20user-read-email%20user-top-read%20user-read-playback-state%20user-modify-playback-state%20user-read-currently-playing%20user-read-recently-played

There is still the same issue
