### ISSUE TITLE
Terms Of Service on the Developer page | Error 502

### ISSUE THREAD

**Issue by misomarcell** [spotify/web-api#890]
I can't accept the Terms Of Service on the Developer page.

#### Endpoint(s):
* https://beta.developer.spotify.com/dashboard/tos-accept

#### Steps to reproduce:
1. Open https://beta.developer.spotify.com/dashboard/tos-accept
2. Check the checkbox
3. Click on Accept the terms

#### Expected behaviour:
Let me continue

#### Actual behaviour:
502
`{
  "error" : {
    "result_code" : 502,
    "message" : "Failed to store new user in database"
  }
}`

**Comment by vatogonzalez** [comment]
I've got the same issue as @misomarcell has. After the above mentioned steps on /dashboard/tos-accept page shows a red bar with "There was an error sending the data. Try again." This bug has been reported earlier this year and was supposedly solved according to the Spotify team. 

**Tried & failed workarounds:**

1. Logging out of Spotify, restarting (Safari), logging in; failed
2. Logging in with another browser (Chrome); failed.
3. Logging in with another computer and browser (Firefox); failed
4. Combinations of the above mentioned over different IP's; failed.

**Comment by vatogonzalez** [comment]
**Update: Succes!**

After logging out -> restart app-> login with different browsers (Chrome and Safari), I gave Firefox a go. This time the error did not show up. The only thing in common with Chrome and Safari is the AdBlock Plus extension that's loaded on both. On Firefox I had no extensions installed. Perhaps that had something to do with it.

**Comment by misomarcell** [comment]
Yes, it seems fixed for me as well.
