### ISSUE TITLE
Add AspNet.Security.OAuth to list of available OAuth2 integrations

### ISSUE THREAD

**Issue by 0xNF** [spotify/web-api#894]
The OAuth2 Integration section of the [Web API Library page](https://beta.developer.spotify.com/documentation/web-api/libraries/#libraries) should have the [AspNet.Security.OAuth.Spotify](https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/tree/dev/src/AspNet.Security.OAuth.Spotify) library appended to it. It's available for ASP.NET Core 1.0 and 2.0

**Comment by arirawr** [comment]
Thanks for the link! I've added this to the section you mentioned. 🎉
