### ISSUE TITLE
/v1/me/player sometimes has an empty body even when music is playing

### ISSUE THREAD

**Issue by BenBanerjeeRichards** [spotify/web-api#895]
Issue found on May 28th 2018.

#### Endpoint(s):
* `GET /v1/me/player`

#### Scope(s):
* user-read-playback-state

#### Steps to reproduce:
1. Start listening to music (the endpoint will correctly have no body is no spotify device is active).
2. The easiest way to recreate is to go to [https://beta.developer.spotify.com/console/get-user-player](https://beta.developer.spotify.com/console/get-user-player), get a token and hit "Try".  

#### Expected behaviour:
A body with information about the current player state (as specified in docs) when music is being listened to.

#### Actual behaviour:
*Sometimes* the body of the response is empty even when I am listening to music. Below are the screenshots from the request made by the developer console at [https://beta.developer.spotify.com/console/get-user-player](https://beta.developer.spotify.com/console/get-user-player):

The empty response body:
![image](https://user-images.githubusercontent.com/5972559/40610373-068205c0-626a-11e8-8a16-3646b56051e5.png)

The request and response headers:
![image](https://user-images.githubusercontent.com/5972559/40610475-675077d8-626a-11e8-88ff-6c9a0e775b1d.png)

There is a final way to verify the issue: go to [https://www.skiley.net/](https://www.skiley.net/) - the front page shows which song you are listening using the spotify api. If the endpoint is returning an empty body you will see 
![image](https://user-images.githubusercontent.com/5972559/40610557-c71b066a-626a-11e8-9472-02cc658d0f10.png)
even when you are listening to music. This shows the issue with different API credentials.

The issue starts occurring when I make the request after a long period (12 hours for example) of not listening to music. Then at some point it will start working and returning the correct response. 

When I sat down to write this report, I started playing music on my phone and noticed the endpoint wasn't working. However, just as I finished that previous sentence ~20 minutes later, the endpoint suddenly started working. In that period I haven't touched Spotify - still playing the same playlist on the same device.   

Similar to #775

**Comment by egobiah** [comment]
Here the same problem but i have maybe more information on the issues ;

The problem apears when the Windows XP spotify client is listening playlist. After aproximately 10 hours of utilisation /v1/me/player give me nothing.

To "resfresh" it i must open spotify on play.spotify.com with google chrome and i get about 10 hours again.

**Comment by BenBanerjeeRichards** [comment]
I haven't noticed this issue occurring in a while so it looks like it has been fixed
