### ISSUE TITLE
All Playlist.Owner Objects are returning NULL

### ISSUE THREAD

**Issue by JasonTBA** [spotify/web-api#896]
Issue found on Monday 28th 2018.

#### Endpoint(s):
* `GET https://api.spotify.com/v1/me/playlists`

#### Scope(s):
* playlist-read-private

#### Steps to reproduce:
1. Open the API Console
2. Try the example here: https://beta.developer.spotify.com/console/get-current-user-playlists/?limit=10&offset=0
3. Notice that owner object looks like: 

"owner": {
        "display_name": null,
        "external_urls": {
          "spotify": null
        },
        "href": null,
        "id": null,
        "type": "user",
        "uri": null
}

#### Expected behaviour:
An Owner object as described in your documentation.

#### Actual behaviour:
Owner object filled with NULL values.

This is pretty critical to our application and I assume others as well since multiple playlists can have the same name but were made by different people. Without the owner there is no way to differentiate. Please advice on timing for getting this resolved on your end if possible. Thank you.

Also, here's a screenshot for posterity:

<img width="751" alt="screen shot 2018-05-28 at 11 19 04 am" src="https://user-images.githubusercontent.com/39202926/40621161-a3d9f612-6269-11e8-912f-cda9d9df1070.png">

**Comment by arirawr** [comment]
Hi @JasonTBA - this should now be resolved. Please reopen if you continue seeing this behaviour!

**Comment by alexsdesign** [comment]
I am having this issue as of around 2 to 3 hours ago.
The display_name value is consistently blank or returning a NULL value.

This also appears to be affecting your web player too when loading a list of playlists.
