### ISSUE TITLE
Playlist description links

### ISSUE THREAD

**Issue by lrholmes** [spotify/web-api#897]
It is my understanding that currently only verified users & artists may add links to a playlist description. If that is the case, is it currently possible to add links to a description through the API, if using an access token from a verified user?

If not, then that would definitely be a handy feature!

Of course, it would be even better if we could add links to any playlist for any user, but I don't know if you have plans to enable that functionality for regular users.

Thanks!

**Comment by bih** [comment]
Hello @lrholmes,

As per our [new developer support process], any feature requests that have no plans to be considered in the next 6 months will be closed as <kbd>wontfix</kbd>.

In this particular case, this doesn't prevent applications where verified users may login and have their playlist descriptions modified with links they did not consent to. Those playlists would also tend to have more followers. That being said, there is value in having this - but it would require more engineering work and thought - and it hasn't received many use cases or +1's from the community to justify it right now.

We still encourage you and other members of the community to continue to share use cases and your support for this feature, as it helps us prioritize features going forward. You should be able to comment on this issue even after it is closed. We will also post updates here relating to this suggestion as and when they happen.

Cheers 👍
