### ISSUE TITLE
Response Object for Create a Playlist has NULL name and description

### ISSUE THREAD

**Issue by ToddBerliner** [spotify/web-api#898]
Issue found on February 19th 2015.

#### Endpoint(s):
* `POST https://api.spotify.com/v1/users/{user_id}/playlists`

#### Scope(s):
* playlist-modify-private

#### Steps to reproduce:
1. Open the API Console to Playlists > Create a Playlist
2. Fill in the required fields
3. Click TRY IT

#### Expected behaviour:
The response object should include the name and description specified in the Request Body.

#### Actual behaviour:
The response object has NULL for the name and description (consistently).

**Comment by scgough** [comment]
I too have this issue!

**Comment by hughrawlinson** [comment]
Hi! We pushed a fix for this issue. Please let me know if you're still able to reproduce it, and I'll reopen the ticket. Thanks for reporting!

**Comment by ToddBerliner** [comment]
Looks good, I can no longer reproduce the issue. Thank you.

**Comment by scgough** [comment]
Thanks @hughrawlinson - this was a seemingly small thing with big repercussions. Glad you got it sorted for us!
