### ISSUE TITLE
Allow 'Cache-Control' to be in API request headers

### ISSUE THREAD

**Issue by newyankeecodeshop** [spotify/web-api#9]
Endpoint: /me (although probably applies to all of them)
Scope: "user-read-private user-read-email"
Steps to Reproduce: I modified the "authorization_code" web-api example for the GET request to "/api.spotify.com/v1/me" by adding a "Cache-Control: max-age=360". (Line 107 in /authorization_code/public/index.html). 
Expected behaviour: The user profile object is returned
Actual behaviour: Firefox issues an OPTIONS request and reports:

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.spotify.com/v1/me. This can be fixed by moving the resource to the same domain or enabling CORS.
```

My goal is to make it so my application will not request the user profile data more than once in an hour. By setting the "max-age" in a cache control request header, I tell the browser cache not to fetch the data if it is less than one hour old. The HTTP spec allows the client to use the Cache-Control header in a request to override the default behavior of the HTTP cache.
I believe the problem is caused by "Cache-Control" not being in the list of headers in the "Access-Control-Allow-Headers" response. If the API is changed to allow Cache-Control, it would give browser apps greater flexibility in controlling the caching of responses. I don't believe this affects iOS or Android since their networking stack does not enforce CORS.

**Comment by JMPerez** [comment]
Since the response from the server comes with the `Cache-Control: private, max-age=0` header, the user-agent (in this case your browser) won't cache the response. When you set `Cache-Control: max-age=360` in the request, no valid cached content will be found and the request will hit Spotify.

A possible enhancement would be to vary the caching depending on the provided header, so if a different user logs in, a different `Authorization` header would be supplied and the content will be requested again.

But at the moment, you can only cache it at an application level, which after all shouldn't be a big deal.

**Comment by newyankeecodeshop** [comment]
My understanding of the HTTP spec (Section 14.9.1) is that the response is cache-able because it does not include "no-cache" or "no-store". The max-age=0 instructs the client to re-validate future requests, but that behavior can be overridden by a request with a different max-age (or a max-stale). Plus, there are other resources in your API that have larger ages, such as a search results or artist metadata. That means that a web application cannot force a refresh by setting "Cache-Control: no-cache" in the request to bypass the max-age from the server. The only way would be to use a "cache-buster" query string, but that breaks all caching of the resource which is not helpful for performance.

**Comment by bih** [comment]
Hey @newyankeecodeshop,

Can you confirm this is still an issue? I see that we now return the `Cache-Control` header and it is now `public, max-age=7200` instead of `private, max-age=0`.

**Comment by bih** [comment]
I'm closing this issue as inactive. It doesn't seem resolved as per the suggestion, but we've introduced a `Cache-Control` header as mentioned in my last comment.

Feel free to open a new issue and reference this (#9) if you'd like to raise this again. Cheers!
