### ISSUE TITLE
Spotify Web API + auth flow for Meteor

### ISSUE THREAD

**Issue by xinranxiao** [spotify/web-api#90]
Hi,

I created a few packages for using Spotify on Meteor.js a month or two back. I think it would be helpful to put links to these on the Spotify code examples page for those who wish to get started with Spotify on Meteor.

Here's the two relevant libraries:
https://github.com/xinranxiao/meteor-spotify-web-api/ (atmosphere link: https://atmospherejs.com/xinranxiao/spotify-web-api)
https://github.com/xinranxiao/meteor-accounts-spotify/ (atmosphere link: https://atmospherejs.com/xinranxiao/accounts-spotify)

Here's the page I'm referring to
https://developer.spotify.com/web-api/code-examples/#libraries

**Comment by JMPerez** [comment]
We have just added them! Thanks for letting us know.
