### ISSUE TITLE
Cannot play a playlist context and start at a specific offset

### ISSUE THREAD

**Issue by markstuartwalker** [spotify/web-api#901]
Issue found on February 31st 2018.

#### Endpoint(s):
* https://api.spotify.com/v1/me/player/play

#### Scope(s):
* user-read-playback-state user-modify-playback-state

#### Steps to reproduce:
1. GET https://api.spotify.com/v1/me/player/play with json
{"offset":{position:13},"context_uri":spotify:user:spotify:playlist:37i9dQZF1DWTot4nTod8BO}

#### Expected behaviour:
The playlist plays from the 13th track

#### Actual behaviour:
No error, no no playing

Note that omitting the offset causes the playlist to start from the first track
{"context_uri":"spotify:user:spotify:playlist:37i9dQZF1DWSOkubnsDCSS"}

**Comment by arirawr** [comment]
Hi @markstuartwalker 

You can check out a working example of this endpoint in our Web Console here: https://developer.spotify.com/console/put-play/?device_id=&body=%7B%22context_uri%22%3A%22spotify%3Auser%3Aspotify%3Aplaylist%3A37i9dQZF1DX67YC0MmS612%22%2C%22offset%22%3A%7B%22position%22%3A5%7D%7D

In your code sample, it looks like you just need some double quotes around the position, so it would look like `"offset": { "position": 13 }`

Hope that helps!

**Comment by markstuartwalker** [comment]
It did help but it was not the full story. Yes, the "position" needed quotes but quotes needed to be around the "spotify ..... GHtyFFF" value. This is odd because I have not needed this in any other parts of the API.
