### ISSUE TITLE
Return HTTP204 when there is no content

### ISSUE THREAD

**Issue by Riley1994** [spotify/web-api#902]
Return HTTP204 when there is no content

Some endpoints like /v1/me/player can correctly reply with an empty body and `Content-Length: 0`. In this scenario the API should return HTTP status code `204 No Content` instead of `200 Ok`, which is provided for in the [RFC](https://tools.ietf.org/html/rfc2616#section-10.2.5).

#### Endpoint(s):
* `GET /v1/me/player`
* probably more but I haven't had a chance to go find them all

#### New behaviour:
When API returns a body with `Content-Length: 0` the status code is `204 No Content`

#### Actual behaviour:
The status code is `200 OK`

**Comment by arirawr** [comment]
Hi @Riley1994 - could you provide reproduction steps or specific scenarios where that endpoint returns 204? I'm not able to reproduce this behaviour.

**Comment by arirawr** [comment]
Hey @Riley1994, as I haven't heard back from you, I'm going to assume that this is resolved. Please reopen with reproduction steps if you're still seeing the issue.

**Comment by Riley1994** [comment]
Hi @arirawr, sorry about not getting back to you, the notification must have slipped through.

According to the docs `/v1/me/player` will return no content when no available devices are found. In this scenario the HTTP code should be `204 No Content` to differentiate it from a successful request with content (ie: `200 Ok`).

Hopefully that clears up what I mean, let me know if you need any more info though.

**Comment by Guptacos** [comment]
Not sure if this was ever resolved. I've found that `GET https://api.spotify.com/v1/me/player/` returns a 204 if there is no active device.

However, the [documentation for the endpoint](https://developer.spotify.com/documentation/web-api/reference/player/get-information-about-the-users-current-playback/) says it should return a 200 and have no populated data.

In addition, the [documentation for player](https://developer.spotify.com/documentation/web-api/reference/object-model/#player-error-reasons) says that no active device should return 404

Is this a mistake in the documentation or the endpoint?
