### ISSUE TITLE
Playlist object full in Create playlist response contains "name": null

### ISSUE THREAD

**Issue by nicolausYes** [spotify/web-api#904]
Issue found on June 05th 2018.

#### Endpoint(s):
* `POST /v1/users/{user_id}/playlists`

#### Scope(s):
* playlist-modify-public
* playlist-modify-private

#### Steps to reproduce:
1. Open Try it page https://developer.spotify.com/console/post-playlists/
2. Get Token for a user with neccessary scopes.
3. Input user id to user_id field.
4. Press Try it

#### Expected behaviour:
API should return Playlist object full with proper playlist name.
https://developer.spotify.com/documentation/web-api/reference/object-model/#playlist-object-full

#### Actual behaviour:
API returns Playlist object full with 'null' as a name.

```
{
  "collaborative": false,
  "description": null,
  "external_urls": {
    "spotify": "https://open.spotify.com/user/xehiyoux/playlist/6xIj3uZ0oSzEQtxXjFfUyx"
  },
  "followers": {
    "href": null,
    "total": 0
  },
  "href": "https://api.spotify.com/v1/users/xehiyoux/playlists/6xIj3uZ0oSzEQtxXjFfUyx",
  "id": "6xIj3uZ0oSzEQtxXjFfUyx",
  "images": [],
  "name": null,
  "owner": {
    "display_name": null,
    "external_urls": {
      "spotify": "https://open.spotify.com/user/xehiyoux"
    },
    "href": "https://api.spotify.com/v1/users/xehiyoux",
    "id": "xehiyoux",
    "type": "user",
    "uri": "spotify:user:xehiyoux"
  },
  "primary_color": null,
  "public": true,
  "snapshot_id": "k6f7rxg7as1qE3NLvXle0iCI2y+2GGswxMbQmMdJEgAdlNtK38SwJgeMM7ymNbOA",
  "tracks": {
    "href": "https://api.spotify.com/v1/users/xehiyoux/playlists/6xIj3uZ0oSzEQtxXjFfUyx/tracks",
    "items": [],
    "limit": 100,
    "next": null,
    "offset": 0,
    "previous": null,
    "total": 0
  },
  "type": "playlist",
  "uri": "spotify:user:xehiyoux:playlist:6xIj3uZ0oSzEQtxXjFfUyx"
}
```

After creating a playlist the endpoint /v1/users/{user_id}/playlists/{playlist_id} returns a playlist with a correct name.

The same situation while creating playlist from the web player. It is creating but with an empty title http://prntscr.com/jr0ugz/direct

**Comment by scgough** [comment]
+1 I have also started getting this error

**Comment by haversnail** [comment]
+1, also getting this same response. And what's this "primary_color" thing about? +1 for new features??

**Comment by hughrawlinson** [comment]
Hi! We pushed a fix for this issue. Please let me know if you're still able to reproduce it, and I'll reopen the ticket. Thanks for reporting!
