### ISSUE TITLE
It seems that "seed_genres"-parameter for the "recommendations"-endpoint only use the first genre, even if I specify more 

### ISSUE THREAD

**Issue by MalteToenjes** [spotify/web-api#908]
Hi,
I'm wondering about the "recommendations"-endpoint. To be more specific I'm wondering about the seed_genres parameter. After the documentation I can set an array with multiple genres, so I expect that the spotify-system is searching for tracks including all of them. But after running a few tests it turns out only the first genre of my array is included. So is there a reason why its like this?

**Comment by arirawr** [comment]
Hi @MalteToenjes - the recommendations returned by this endpoint may fall into any one of the genres you provide, not necessarily all of them. For example, if you give seed genres of "pop" and "funk", you will get some pop tracks and some funk tracks, not tracks that fall under both.

Hope that helps!
