### ISSUE TITLE
Invalid Cache-Control Response Header  @ /api/token

### ISSUE THREAD

**Issue by wobu** [spotify/web-api#91]
i just queried following endpoint 

     https://accounts.spotify.com/api/token

with simple Client Credentials for receiving a non refreshable token.

The framework (akka http) i am using is claiming that one header in the response is invalid

     cache-control: : no-cache, no-store, must-revalidate

if this is the case, it is truly invalid. 

Note the additional:

     :

Other endpoints are working correctly.

**Comment by thelinmichael** [comment]
Thanks for the report @wobu.

**Comment by thelinmichael** [comment]
And a fix is deployed!
