### ISSUE TITLE
Trouble playing a song with SDK

### ISSUE THREAD

**Issue by noobiept** [spotify/web-api#914]
So I'm trying to play a song from Spotify and I'm having trouble making it work. I can do the login just fine but then don't know the next step.

I'm following this: https://developer.spotify.com/documentation/web-playback-sdk/quick-start/

Here's what I'm doing.

```
window.onSpotifyWebPlaybackSDKReady = () => {
// ...
// Connect to the player!
player.connect();
playSong('spotify:album:1Je1IMUlBXcx1Fz0WE7oPT', token);
}

function playSong(uri, token) {
    fetch("https://api.spotify.com/v1/me/player/play", {
        method: "PUT",
        headers: {
            "Accept": "application/json",
            "Content-Type": "application/json",
            Authorization: "Bearer " + token,
        },
        body: JSON.stringify({
            context_uri: uri,
        }),
    });
}
```

#### Endpoint(s):
* `/v1/me/player/play`

#### Scope(s):
* streaming user-modify-playback-state user-read-birthdate user-read-email user-read-private

#### Actual behaviour:
401 Error (consistently)

I get a 401 error from that.
On the 'player' object, there's some methods like 'togglePlay()' / 'nextTrack()' but when I call that I get a `Cannot perform operation; no list was loaded.`.

So, how do you play a song?

**Comment by arirawr** [comment]
Hi @noobiept - are you trying to stream from a Free account or Premium account?

**Comment by noobiept** [comment]
I'm testing on a premium account.

**Comment by noobiept** [comment]
Is the code correct? Is this a potential account issue?

**Comment by arirawr** [comment]
I can't see all your code, so it's hard to tell. One issue may be with the `getOAuthToken` function not properly getting a token. Another is that you need to wait for the player's "ready" event ie. `player.on('ready', data => { //something } );`

Check out this full working example here: https://glitch.com/edit/#!/spotify-web-playback?path=script.js:36:0

**Comment by noobiept** [comment]
I was able to make it work thanks to your example, thanks man!
