### ISSUE TITLE
Spotify Search returns not found for results > 10,000

### ISSUE THREAD

**Issue by MikeNGarrett** [spotify/web-api#917]
Issue found on June 15, 2018.

#### Endpoint(s):
* `GET /v1/search`
* parameter `tag:new`, `album`, `limit=50`, `offset=10000`

#### Steps to reproduce:
Use the API to search with a large result and try to offset > 10,000.

#### Expected behaviour:
Results.

#### Actual behaviour:
Not found.

**Comment by MikeNGarrett** [comment]
@happy-machine Can you point me to the ticket with this report so I can follow it? I wasn't able to find it on my initial search before posting this ticket.

**Comment by MikeNGarrett** [comment]
I just realized @happy-machine is not a contributor here, so I'm reopening.

**Comment by hughrawlinson** [comment]
Hi @MikeNGarrett - this isn't a bug, this is [documented behaviour](https://developer.spotify.com/documentation/web-api/reference/search/search/).

> Maximum offset (including limit): 10,000.

Hope that clarifies things!

**Comment by MikeNGarrett** [comment]
@hughrawlinson Documentation and reality are definitely different. I understand now that I "got away with this" until the limit was enforced. Thanks for clarifying.

**Comment by shillshocked** [comment]
This isn't enough to do some simple tasks.
