### ISSUE TITLE
Cannot refresh my access token with the Accounts API

### ISSUE THREAD

**Issue by paufabregat** [spotify/web-api#919]
Issue found on June 18th 2015.

#### Endpoint(s):
* `POST accounts.spotify.com/api/token`

#### Scope(s):
* user-read-private 
* user-read-email 
* playlist-read-private 
* playlist-read-collaborative 
* user-library-read 
* user-library-modify 
* user-top-read 
* user-read-currently-playing 
* user-read-playback-state

#### Steps to reproduce:
Follow the [authorization code](https://developer.spotify.com/documentation/general/guides/authorization-guide/#authorization-code-flow) flow. 

Client id and client secret are base64 encoded on the header using:
`echo -n client_id:client_secret | base64 -` 

and making the post request as described on the guide: 
~~~
curl -H "Authorization: Basic ZjM4Zj...Y0MzE=" -d grant_type=refresh_token -d refresh_token=NgAagA...NUm_SHo https://accounts.spotify.com/api/token
~~~

#### Expected behaviour:
On step **4. Requesting a refreshed access token; Spotify returns a new access token to your app** of the authorization code flow get the object described in the example with a new access token. I should get something similar to this:
~~~
{
   "access_token": "NgA6ZcYI...ixn8bUQ",
   "token_type": "Bearer",
   "scope": "user-read-private user-read-email",
   "expires_in": 3600
}
~~~

#### Actual behaviour:
400 Bad Request 
`{"error":"invalid_client","error_description":"Invalid client"}`

#### Things already checked:
* Create a new app and try with a new pair client id, client secret
* [Be sure the spotify app](https://github.com/snipsco/spotify-auth/blob/master/authorization_code/app.js#L58) is returning the right things after authorization
* [Use refresh_token endpoint](https://github.com/snipsco/spotify-auth/blob/master/authorization_code/app.js#L120) from the previous app to see if the problem persists (it does)

**Comment by paufabregat** [comment]
@arirawr @bih @hughrawlinson I know similar issues have been opened in the `web-api` repo in the past and I have been through them already trying to find out what I may be doing wrong. I have been also checking carefully the auth flow documentation to make sure there is no silly mistake on my side. 
At this point, I am really clueless on how to move forward and I would really appreciate your support whenever you get the chance. Thank you in advance! :)

**Comment by bih** [comment]
Have you tried sending `client_id` and `client_secret` to the `POST https://accounts.spotify.com/api/token` endpoint? You can use that instead of the `Authorization: Bearer ...` header. That might solve your problem!

**Comment by paufabregat** [comment]
@bih Thank you for the fast reply! I just did it:
~~~
curl -d grant_type=refresh_token -d refresh_token=MY_REFRESH_TOKEN -d client_id=MY_CLIENT_ID -d client_secret=MY_CLIENT_SECRET https://accounts.spotify.com/api/token
~~~
I am getting back the same error `{"error":"invalid_client","error_description":"Invalid client"}`

**Comment by bih** [comment]
In that command you didn't define a HTTP method. Try this.

```
curl -X POST \
     -d grant_type=refresh_token \
     -d refresh_token=MY_REFRESH_TOKEN \
     -d client_id=MY_CLIENT_ID \
     -d client_secret=MY_CLIENT_SECRET \
     https://accounts.spotify.com/api/token
```

I ran the command above with my credentials and worked fine. Let me know if you continue to have issues. It seems like the credentials you're using might have a typo.

**Comment by paufabregat** [comment]
Resolved! Silly mistake on my end but it has really driven me crazy for some days. On my client app, I was not using the same client credentials used in the server auth app that was giving back the refresh token.
