### ISSUE TITLE
EchoNest 12 dimensional vector of timbre - meaning of each element?

### ISSUE THREAD

**Issue by koren88i** [spotify/web-api#920]
The EchoNest Analyzer Documentation states the following regarding timbre:

The Echo Nest Analyzer’s timbre feature is a vector that includes 12 unbounded values roughly centered around 0.

Those values are high level abstractions of the spectral surface, ordered by degree of importance.

For completeness however, **the first dimension represents the average loudness of the segment; second emphasizes brightness; third is more closely correlated to the flatness of a sound; fourth to sounds with a stronger attack; etc**

I am looking for the **rest of the list**.. what is the high level meaning of each dimension.

Have not found it anywhere, and can not think of a way to check the meaning myself (using other music analysis or ml clustring).

**Comment by giang12** [comment]
https://github.com/orgs/echonest/people maybe a better place to start bugging ..

**Comment by 0xNF** [comment]
> https://github.com/orgs/echonest/people maybe a better place to start bugging ..

I don't necessarily disagree because who knows if they still pay attention over there, but it's worth remembering that the Echo Nest was acquired and shut down by Spotify, and everything on that page has been in active since at least 2016.

**Comment by arirawr** [comment]
Hi @koren88i! Thanks for the request. I'm going to close this in favour of #947. Please follow that issue for updates about audio features documentation.
