### ISSUE TITLE
Invalid authorization code

### ISSUE THREAD

**Issue by kaiferrall** [spotify/web-api#925]
Cannot get the access token from /api/token using the authorization code. 

Issue found  on June 26, 2018.

#### Endpoint(s):
* `POST /api/token

#### Scope(s):
* Access token, using the code from the /authorize route the post to /api/token responds with "invalid grant", and "invalid authorization token"

#### Expected behaviour:
Using the the query parameter from /authorize called code I still get a 400 status that says invalid authorization code. Since I am using the code that is sent back from /authorize I am expecting to get back the access token back from my post.

#### Actual behaviour:
400 status code. "error" invalid grant, "error description" invalid authorization code. 

My code: 
request.post(
        "https://accounts.spotify.com/api/token",
        {
          form: {
            grant_type: "authorization_code",
            redirect_uri: "http://localhost:3000/test",
            code: `${req.query.code}`,
            client_id: `${keys.spotify.client_id}`,
            client_secret: `${keys.spotify.client_secret}`
          }
        },
        (err, response, body) => {
          res.send(response);
        }
      );

**Comment by colemahatmccreary** [comment]
do you remember how you sorted this out?

**Comment by kaiferrall** [comment]
Hey sorry what issue are talking about?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by colemahatmccreary** [comment]
the 'invalid authorization code' error on spotify web api auth flow

**Comment by kaiferrall** [comment]
Can u send a link to the stackoverlfow, I’m guessing that’s where ur refering to?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by colemahatmccreary** [comment]
I'm commenting on your github issue - [https://github.com/spotify/web-api/issues/925]

**Comment by kaiferrall** [comment]
Oh okay I will checkout it out one sec

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by kaiferrall** [comment]
Hey cole I will get back to you in the morning a little busy atm. Send me a personal email if u Want.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by colemahatmccreary** [comment]
ok thanks

**Comment by colemahatmccreary** [comment]
hey for you or anyone else who finds themselves here looking for a solution:

I'm using nextjs/react for this project and when a user returned to my callback URI from authorizing on Spotify, I called the /api/token endpoint (to exchange auth token for refresh token) from inside componentWillMount. 

Only after moving that last API call to componentDidMount does it return a refresh token and not the 'invalid grant, invalid authorization code' error I had been seeing. Hope this helps.

**Comment by Kruszylo** [comment]
I have same issue when I try to recieve refresh_token with `curl`. First I get access_token  and then I do 
```
curl -H "Authorization: Basic MzBhNTlhZTc5NWJ...5ZWIyZWQ=" -d grant_type=authorization_code -d code=BQCzw01muZZDZSdf...912opS -d redirect_uri=http%3A%2F%2Flocalhost%3A8100%2Fmain https://accounts.spotify.com/api/token
```
And I recieve `{"error":"invalid_grant","error_description":"Invalid authorization code"}`. How to fix this?
