### ISSUE TITLE
Track relinking for markets and popularity values

### ISSUE THREAD

**Issue by onelifeliveit** [spotify/web-api#928]
Hi there team,

I have a question I can't seem to find the answer to. How do you factor in the market value for getting the "best" popularity value of tracks?

By example, if I have track ID ABC with popularity 0 BUT track ABC is also linked to track XYZ and track XYZ has popularity value 80. How do I access the XYZ popularity value.

Example, if you don't define a market, you get the popularity of the exact track ID you submit BUT what I actually need is the "highest" popularity of that tracks possible re linked tracks.

So say for example, market=ALL perhaps? Maybe a way to get the highest popularity of relinked tracks?

The business use for this is NOT to actually then stream the song so in "real world" the market value is not required for removing or allowing possible tracks. This is purely a tool to get popularity values that could be linked to a track that at the moment has no value in Spotify.

For example, in market ZA a track has not yet reached popularity 80 BUT the "same" track by track relinking in market US has reached 80 - Hence the tool to predict what is going to become popular needs to look at the highest popularity value and NOT a specific market.

I hope I'm explaining this in a way someone can help :)

Many Thanks

**Comment by bih** [comment]
Hello @onelifeliveit,

Do you have an example of a track ID that has a lower `popularity` in one market and a higher `popularity` in another market? I'm not sure I follow.

Just so I understand, the use case here is to detect tracks that could be popular in a particular market based on how it is performing in other markets?

**Comment by arirawr** [comment]
Hey @onelifeliveit, as we haven't heard back from you with more information on this issue, we're going to close this issue as inactive. Please feel free to reopen and comment with the requested info so we can help you 🙂
