### ISSUE TITLE
Audio Features not working for certain Spotify tracks

### ISSUE THREAD

**Issue by tomjaimz** [spotify/web-api#929]
Hi, I would like to request that https://github.com/spotify/web-api/issues/923 be re-opened.

I have a playlist that is automatically updated daily, and uses audio features for sorting.  It's been working fine for over a year, however since June 18th it has been failing due to a significant increase in the volume of tracks that lack an audio feature profile.

I see that 923 was opened recently, and a recent comment indicates at least one other person encountering this problem.

I would say I have added over 2,000 tracks to my playlist in the last year or so, and of those perhaps only 2 or 3 failed to get audio feature objects.  Since June 18th, 21 new tracks have failed to return audio feature objects.

The solution to 923 seems to indicate that audio feature objects were created for the tracks that the reporter had encountered, but it seems to be the issue is systemic.

Issue found on June 18th, 2018.

My description below highlights the 21 tracks released since June 18th that do not have audio-feature objects:

#### Endpoint(s):
* `GET /v1/audio-features?ids=4VPMoAVfD2UCacipd11PJw%2C3ne6hRkl1MgLf0WwRhZXU3%2C7dRJLvM0RMByeJNnbthm6E%2C4xowQvAlaQlAfXHYtcBxe2%2C2prRXBrhnd3BSIP63Ld59L%2C2IOwkPAkDDGvkLzlnUdcQ2%2C2kGqcecDUhi7e3wvm5cUjY%2C14CX3nEihqZK9lR9XrcNYJ%2C0kxojsWbN5U4krbk8yYWpd%2C4jkYCDN1arnPQ5HcWChhKG%2C0T8C8LTnhPcpRwTiUWGzBQ%2C7t0MNDhyv0ggclROXkmJuO%2C1iRlHOS7o2YYZtUlUZhHtl%2C3IBOf42ijoA4EzB5CIcfog%2C5BOHxzYSDYY5jHoqDY7YWT%2C4vBgr4V2GOuBi896Thvgsg%2C3sxYw4AzSqS193y7B31n2t%2C2iGvIF4GcWHop2XOoYkdpd%2C1uZwnxyUTiuVl7U8I2f5E1%2C5sn7f3na9nvZmgfXdi33Ts%2C07wtxHqUa3UHKBwM2a48hf`

#### Scope(s):
* None (but OAuth requred)

#### Steps to reproduce:
1. Open the API Console
2. Call the `audio-features` endpoint with `ids` `4VPMoAVfD2UCacipd11PJw,3ne6hRkl1MgLf0WwRhZXU3,7dRJLvM0RMByeJNnbthm6E,4xowQvAlaQlAfXHYtcBxe2,2prRXBrhnd3BSIP63Ld59L,2IOwkPAkDDGvkLzlnUdcQ2,2kGqcecDUhi7e3wvm5cUjY,14CX3nEihqZK9lR9XrcNYJ,0kxojsWbN5U4krbk8yYWpd,4jkYCDN1arnPQ5HcWChhKG,0T8C8LTnhPcpRwTiUWGzBQ,7t0MNDhyv0ggclROXkmJuO,1iRlHOS7o2YYZtUlUZhHtl,3IBOf42ijoA4EzB5CIcfog,5BOHxzYSDYY5jHoqDY7YWT,4vBgr4V2GOuBi896Thvgsg,3sxYw4AzSqS193y7B31n2t,2iGvIF4GcWHop2XOoYkdpd,1uZwnxyUTiuVl7U8I2f5E1,5sn7f3na9nvZmgfXdi33Ts,07wtxHqUa3UHKBwM2a48hf`

#### Expected behaviour:
Array of audio feature objects t as described on `https://developer.spotify.com/documentation/web-api/reference/tracks/get-several-audio-features/`.

#### Actual behaviour:
Array of nulls.

**Comment by bih** [comment]
Hi @tomjaimz!

Were you not able to re-open the issue? I'll go ahead and close this as a duplicate and re-open #923.

**Comment by tomjaimz** [comment]
@bih Nah, plebeians like me cannot re-open bugs. :-)
