### ISSUE TITLE
Get a Playlist endpoint returns NULL on description when get a Spotify playlists.

### ISSUE THREAD

**Issue by sukezane** [spotify/web-api#930]
Issue found on February 19th 2015.

#### Endpoint(s):
* `GET /v1/users/{user_id}/playlists/{playlist_id}`

#### Scope(s):
* None

#### Steps to reproduce:
1. Open the API Console
2. Call the Get a Playlist endpoint with `user_id`(spotify) and `playlist_id`(37i9dQZF1DX8FwnYE6PRvL)

#### Expected behaviour:
`description` returns "Rock into 2018 with the ultimate rock party playlist!"

#### Actual behaviour:
`description` returns NULL

**Comment by arirawr** [comment]
I've been able to reproduce this and we're looking into it. Thanks for the report!

**Comment by arirawr** [comment]
@sukezane This should now be resolved! Thanks for the report.
