### ISSUE TITLE
Undocumented /playlists endpoints?

### ISSUE THREAD

**Issue by c24w** [spotify/web-api#931]
#### Endpoint(s):
* `GET /v1/playlists/{playlist_id}`

#### Scope(s):
* playlist-read-private
* playlist-read-collaborative

#### Steps to reproduce:
`curl https://api.spotify.com/v1/playlists/{playlist_id} -H 'Authorization:Bearer {token}'`

I thought it seems odd that the `/users/{user_id}/playlists/{playlist_id}` endpoints require a `user_id`, assuming a `playlist_id` is unique.  Also, I can pass random text as the `user_id` and the playlist will still be returned.  This made me think I should be able to drop the user portion of the path, which turned out to work!  What's the point in passing the user?  I can't find any mention of these `/playlists` endpoints; should they be used?

**Comment by PouleR** [comment]
See this blogpost by Spotify: https://developer.spotify.com/community/news/2018/06/12/changes-to-playlist-uris/

**Comment by c24w** [comment]
Great!  Thank you for that.  I don't know how [my search](https://www.google.co.uk/search?q="api.spotify.com%2Fv1%2Fplaylists") missed that post.
