### ISSUE TITLE
Sleep mode function

### ISSUE THREAD

**Issue by osmarpinheiro** [spotify/web-api#932]
Hello there.

I wish the Spotfy application had a sleep mode function where we could set a timer to stop playing.
Is it the best place to make this suggestion?

Best regards,
Osmar.

**Comment by jscholes** [comment]
> Is it the best place to make this suggestion?

No, this issue tracker is related to Spotify's offerings for third party developers.  You can [go here to submit a feature request](https://community.spotify.com/t5/Idea-Submissions/idb-p/ideas_submissions) for the official Spotify clients, websites or apps.

**Comment by arirawr** [comment]
As @jscholes mentioned, please visit the [Spotify community](https://community.spotify.com/t5/Idea-Submissions/idb-p/ideas_submissions) to submit ideas for our mobile apps.
