### ISSUE TITLE
Inconsistent behavior of the `market` query param

### ISSUE THREAD

**Issue by stefanprobst** [spotify/web-api#933]
(1) If I am reading the docs correctly, specifying a `market` query parameter should result in `available_markets` being replaced by `is_playable`. While this is true for endpoints like `/albums`, it is *not* true for `/search?type=album`.
(2) The docs for the `/search` endpoint mention a special `from_token` value for `market` that seems to work for other endpoints, but is not documented there.
(3) And a wish: if the `from_token` value for `market` is indeed intended to work for all endpoints, something similar would be great for `country` as well.

**Comment by arirawr** [comment]
Thanks for your suggestion! We made some updates to improve how market/from_token works and have updated the documentation. Let us know what you think!
