### ISSUE TITLE
Cannot add tracks to playlists, 500 error

### ISSUE THREAD

**Issue by JessicaMartini212887** [spotify/web-api#934]
Cannot add tracks to playlists for user account 212887@studenti.unimore.it.

Issue found on June 30th 2018.

Endpoint(s): /users/kingwig/playlists
Scope(s): playlist-read-private, playlist-modify-private, playlist-modify-public

I use spotipy library and the actual behaviour is 500 Server Error (consistently).
Can you check this?

**Comment by arirawr** [comment]
Hi @JessicaMartini212887 - could you please include some steps for reproducing this error, and maybe a code snippet of the call you're making?

**Comment by arirawr** [comment]
Hey @JessicaMartini212887, as we haven't heard back from you with more information on this issue, we're going to close this issue as inactive. Please feel free to reopen and comment with the requested info so we can help you 🙂
