### ISSUE TITLE
Some iframe playlist embed gets error

### ISSUE THREAD

**Issue by sukezane** [spotify/web-api#935]
Issue found on July 2nd 2018.

#### Steps to reproduce:
1. Get iframe playlist embed code from Spotify desktop app. 
https://open.spotify.com/user/spinninrecordsofficial/playlist/4173ENNA5eMzHrz9pipvxI?si=hKao-N4cTCeh-aHVQw_HOw

2. Paste embed code to html file. 
```
<iframe src="https://open.spotify.com/embed/user/spinninrecordsofficial/playlist/4173ENNA5eMzHrz9pipvxI" width="300" height="380" frameborder="0" allowtransparency="true" allow="encrypted-media"></iframe>
```
3. Open html file.

#### Expected behaviour:
Playlist embed player will displayed on html file.

#### Actual behaviour:
Iframe returns error.
```
embed.2018-06-29_e14f24a3.js:1 Uncaught TypeError: Cannot read property 'uri' of null
    at e.tracks.items.map (embed.2018-06-29_e14f24a3.js:1)
    at Array.map (<anonymous>)
    at embed.2018-06-29_e14f24a3.js:1
    at embed.2018-06-29_e14f24a3.js:1
    at embed.2018-06-29_e14f24a3.js:1
    at embed.2018-06-29_e14f24a3.js:1
    at embed.2018-06-29_e14f24a3.js:1
    at t.a.e (embed.2018-06-29_e14f24a3.js:1)
    at Object.<anonymous> (embed.2018-06-29_e14f24a3.js:1)
    at n (embed.2018-06-29_e14f24a3.js:1)
```

**Comment by bih** [comment]
Hi sukezane!

Thanks for reaching out! I can confirm that we can reproduce this issue and are investigating into a fix. We'll post updates here! 🙂

**Comment by bih** [comment]
Hey @sukezane,

I can confirm this has now been resolved. Feel free to create a new issue and reference this issue (#935) if you're continuing to have problems with the Play Button.

Cheers!
