### ISSUE TITLE
Add GET /v1/me/playlists endpoint 

### ISSUE THREAD

**Issue by jwilsson** [spotify/web-api#937]
#### Endpoint(s):
* `GET /v1/playlists`

#### Use cases
This is just a feature request for API consistency. Given that `POST /v1/me/playlists` is now available (per https://developer.spotify.com/community/news/2018/06/12/changes-to-playlist-uris/) I think it would make sense to get a list of a user's playlists but being able to omit the user ID.

**Comment by arirawr** [comment]
Hey! This is already available here: https://developer.spotify.com/documentation/web-api/reference/playlists/get-a-list-of-current-users-playlists/
Check it out in the console here: https://developer.spotify.com/console/get-current-user-playlists/
