### ISSUE TITLE
How to Play my Spotify Playlist across two devices in my home simultaneously; Premium Account

### ISSUE THREAD

**Issue by shutterbug35** [spotify/web-api#939]
I am hoping someone can help with what does not seem to be a difficult task, but it is turning into one... I am having a party tomorrow and would like to play a Spotify playlist I created on both my TV (surround sound) and my Alexa/Echo outside - simultaneously of course.  Can I even do that and if so, how?  I have searched high and low in the Spotify community and help section and nothing goes into the details of exactly how to do this.  This is my last hope.

CS

Issue found on February 19th 2015.

#### Endpoint(s):
* `GET /v1/users/{user_id}`

#### Scope(s):
* None (application is not using authentication)

#### Steps to reproduce:
1. Open the API Console
2. Call the `get-users-profile` endpoint with `user_id` `%5E`

#### Expected behaviour:
A public user object as described on `https://developer.spotify.com/web-api/object-model/#user-object-public`.

#### Actual behaviour:
500 Server Error (consistently)

**Comment by jscholes** [comment]
Spotify only allows you to play music on one device or app at once.  If you want to stream it to the whole house, you'll have to stream it from one central point and then broadcast it out somehow.

**Comment by arirawr** [comment]
Hi @shutterbug35 - as @jscholes mentioned, you can only play on one device at a time from your Spotify account. You can contact customer support for more help with using Spotify on your devices [here](https://support.spotify.com/us/contact-spotify-support/).
