### ISSUE TITLE
403 error on preview_url

### ISSUE THREAD

**Issue by jpouillard** [spotify/web-api#94]
Hello,

I recently had few 403 errors when i called the `preview_url`... But it works normally on some preview...
There is a restriction or another thing ?

<pre>
GET https://p.scdn.co/mp3-preview/36cec7cf0a1e7e17c198d6bd5263e9f56757f791 403 (Forbidden)
</pre>

<pre>
  Error 
    Code AccessDenied/Code 
    Message Access Denied/Message 
    RequestId BCB8EB624D46E536/RequestId 
    HostId 
      lhFLgBowq5RAHv89Js2w2oyBLTxyk676hEN+emB19x7Rr5KtPcnMn0S1o3e5IfqUDFwgmH2wFKE=
    /HostId 
  /Error
</pre>

**Comment by asmitter** [comment]
This was likely due to a temporary condition. Can you retry that track URI to see if you get an updated preview_url?

**Comment by jpouillard** [comment]
Problems solved apparently. Thanks !
