### ISSUE TITLE
v1/me/player/play does not consistently play the given uris array in the proper order

### ISSUE THREAD

**Issue by TomerAberbach** [spotify/web-api#940]
`v1/me/player/play` does not consistently play the given uris array in the proper order.

Issue found on February 19th 2015.

#### Endpoint(s):
* `PUT /v1/me/player/play`

#### Scope(s):
* `user-modify-playback-state`

#### Steps to reproduce:
1. Open the API Console
2. Call the `put-play` endpoint with `uris`:
```
[ 
  "spotify:track:2RlgNHKcydI9sayD2Df2xp",
  "spotify:track:7CxLQRkNmMKjFlNSITV3q7",
  "spotify:track:5hkdfA87RZvNaxl6XiveOA",
  "spotify:track:3goSVuTt3fDYDP6kRnFwuL",
  "spotify:track:4cbrkSmA6bHPqu7xuQ2YHI",
  "spotify:track:0ZGD86ANZoQT2tU57Y4gCE"
]
```

#### Expected behaviour:
The tracks passed in an array should play in the order in which they were passed.

#### Actual behaviour:
The tracks passed in an array play in a seemingly random order.

**Comment by Belgiumese** [comment]
Does this happen even with shuffle disabled on the Spotify player? I found that if shuffle was previously enabled, it would immediately play in a random order.

**Comment by TomerADev** [comment]
I just tested it and it appears you are right.
I checked the [documentation](https://developer.spotify.com/documentation/web-api/reference/player/start-a-users-playback/) and there isn't any mention of this behavior.
Maybe it should be documented?
