### ISSUE TITLE
advanced search on the Spotify client

### ISSUE THREAD

**Issue by thomasdallan** [spotify/web-api#941]
not properly regarding the APIs, but it's a technical issue about the desktop client (i have reached this page asking the Spotify Customer Support by chat: they redirected me here). I was often using the "spotify advanced search" (i.e. upc:XXXXXXXXXX or label:LABELNAME ) in the spotify search field directly. This kind of search seems not working anymore. Working for a record label company this is something i would frequently use. Is there a way to have it back? Or is there a special request that my company can make to have it back (i guess something for professionals only)?
Thank you for your reply

**Comment by arirawr** [comment]
Hey @thomasdallan - This issue tracker is for the Web API and we aren't able to help with issues in the desktop client.

If you want to use the APIs for this type of search, you can check out the documentation for how to form queries here: https://developer.spotify.com/documentation/web-api/reference/search/search/#writing-a-query---guidelines

It seems that you may have done this already, but you can ask Spotify customer support about the desktop app here: https://support.spotify.com/us/contact-spotify-support/

**Comment by thomasdallan** [comment]
funny that the Spotify Support redirects the people here and you redirect the people back there again... very professional!
