### ISSUE TITLE
Getting auth_token using Python

### ISSUE THREAD

**Issue by shiftsayan** [spotify/web-api#944]
Issue found on February 19th 2015.

#### Endpoint(s):
* ` GET https://accounts.spotify.com/authorize/`

#### Scope(s):
* `user-read-private` 
* `user-read-email`

#### Steps to reproduce:
1. I set up my app in the dashboard using the `redirect_uri` http://localhost:8000 after reading that this was possible in several places and guides.

2. I ran a SimpleHTTPServer using Python in the background.

2. Then I used the following GET request to get my `auth_token` and proceed with other queries.

```
params = (
    ('client_id', MY_CLIENT_ID),
    ('response_type', 'code'),
    ('redirect_uri', "http://localhost:8000"),
    ('scope', 'user-read-private user-read-email'),
)

response = requests.get('https://accounts.spotify.com/authorize/', params=params)
```

#### Expected behaviour:
Based on what I have read, I should be redirected to a URL with the `auth_token` or get it in the response object, but I am not a 100% sure.

#### Actual behaviour:
The GET request works and I get the response object <Response [200]>. However, when I try to get the contents of the object, I get an HTML document, which renders as:
![screen shot 2018-07-11 at 12 17 12 pm](https://user-images.githubusercontent.com/8451336/42555798-1302be60-8507-11e8-9474-aec33b3dcd71.jpg)

I think there is something wrong with my `redirect_uri` but I don't know.

**Comment by jscholes** [comment]
You need to open the /authorize URL in your browser, along with the same params you're generating here.  This is so you can agree to the required scopes and then be redirected to your callback URL.  You cannot complete this authorization flow in headless or server-side code.

**Comment by 0xNF** [comment]
>  You cannot complete this authorization flow in headless or server-side code.

As someone for whom Spotify's auth flows were my first introduction to OAuth, this was a sticking point of confusion for several hours. OAuth is complicated, man.
