### ISSUE TITLE
Web player not working.

### ISSUE THREAD

**Issue by roccomuso** [spotify/web-api#945]
I'm not sure if this is the right place to report it. But I'm having a issue playing any song on the web player. I'm on Ubuntu 16.04, Chrome.

The exception in console:

```
Uncaught in Promise
r {code: "HARMONY_OPERATION_FORBIDDEN", message: "Skipping not allowed.", status: -1, debug: {…}}
```

**Comment by arirawr** [comment]
Hi there,
You can get support for the Spotify app from customer support [here](https://support.spotify.com/us/contact-spotify-support/) or on Twitter @SpotifyCares.

**Comment by roccomuso** [comment]
One year passed already. Same issue.
