### ISSUE TITLE
Cannot Follow Any Artists on Web Player or Mac App

### ISSUE THREAD

**Issue by Jbonez87** [spotify/web-api#946]
I can no longer follow artists on the spotify app for Mac. My operating system is OSX High Sierra and I'm a free tier user. Here's what I've tried: 
1. Logging out and logging back in 
2. Using the web player 
3. Quitting the app completely and restarting it 
4. Checking the chrome console for any errors. Here's what did come up: 
Failed to load resource: the server responded with a status of 400 () spclient.wg.spotify.com/ads/v1/ads/leaderboard?payload=e30=:1 

Failed to load resource: the server responded with a status of 502 () blank:59 
Uncaught SyntaxError: Invalid or unexpected token blank:59 
Uncaught SyntaxError: Invalid or unexpected token at blank:6 

I'm using Chrome Version 67.0.3396.99 (Official Build) (64-bit) 

5. Check the network tab for any XHR errors: No errors on this endpoint (https://api.spotify.com/v1/me). However I did notice that in the JSON response object I have a followers object with href and total key-value pairs but I don't seem to have a following object. Is this by design or are my followers stored at a different endpoint? 

6. Check the application tab to see if there are any clues in localStorage or sessionStorage (possibly null following values is what I was looking for): Just a stringified array with my playback history. Has this feature been deactivated for free tier members or is this a bug?

**Comment by arirawr** [comment]
Hi @Jbonez87! Thanks for the report! This issue tracker is for the Web API. Please report this issue to Spotify customer support here: https://support.spotify.com/us/contact-spotify-support/
