### ISSUE TITLE
Documentation on audio features and audio analysis

### ISSUE THREAD

**Issue by mateusrangel** [spotify/web-api#947]
Mark Koh @markkohdev told me to create this issue, so he can build the requested documentation, because there isn't currently external documentation on exactly how these features are calculated.

In the actual documentation of audio features (https://developer.spotify.com/documentation/web-api/reference/tracks/get-several-audio-features/), we dont know how the audio features are calculated, only what they represent.

**Comment by mateusrangel** [comment]
wassup @markkohdev

**Comment by DijonLee** [comment]
I would love Docs on this as well!  There was a topic on researchgate on this but did not provide much information about actual documentation but this might be interesting to you

https://www.researchgate.net/post/Is_there_any_documentation_about_Spotifys_audio_features

**Comment by mateusrangel** [comment]
Any news @arirawr ?

**Comment by arirawr** [comment]
Hey @mateusrangel! No updates to share right now. Rest assured, we'll post here when we have more info to share with you.

**Comment by arirawr** [comment]
I'm very happy to let you know that this documentation has been updated! Check it out here: https://developer.spotify.com/documentation/web-api/reference/tracks/get-audio-analysis/

**Comment by mateusrangel** [comment]
> I'm very happy to let you know that this documentation has been updated! Check it out here: https://developer.spotify.com/documentation/web-api/reference/tracks/get-audio-analysis/

thanks!!!!!!!!

**Comment by Isetnt2** [comment]
Thanks!

**Comment by goldensunliu** [comment]
@arirawr 
https://github.com/spotify/web-api/issues/920#issue-333653911
I am pretty sure we are still missing the complete documentation around timbre. We still have no idea how to make sure of these unbounded values.

**Comment by whistlebug23** [comment]
I've been studying this video, but Mark Koh says the same things as the documentation. He shares some great already-made analyses.

`https://www.youtube.com/watch?v=goUzHd7cTuA`

**Comment by ericauv** [comment]
> @arirawr
> [#920 (comment)](https://github.com/spotify/web-api/issues/920#issue-333653911)
> I am pretty sure we are still missing the complete documentation around timbre. We still have no idea how to make sure of these unbounded values.
> ![image](https://user-images.githubusercontent.com/1348993/53313543-d19d5400-3887-11e9-90f9-9b2286dc1b14.png)

Still missing documentation regarding what the other 8 dimensions correspond to.

**Comment by markkohdev** [comment]
Hey @goldensunliu @whistlebug23 @ericauv -- sorry about the super delayed response to this - I didn't realize I was tagged here 🤦‍♂ 

The "displayed below" is just a typo and should be "displayed above" -- I'll fix that later this week.

Hopefully this clarifies things a bit regarding how these values are generated:
These basis functions were generated using a [PCA](https://en.wikipedia.org/wiki/Principal_component_analysis) over the segment's spectrogram.  The description of the first four dimensions is simply a human _interpretation_ of the basis functions.  While interpreting the other dimensions requires [knowledge/intuition of spectrograms](https://www.izotope.com/en/learn/understanding-spectrograms.html), you can get a sense of what each basis function evaluates by trying to imagine what the sound of the spectrogram representation would be.

Generally, we don't suggest that you attempt to actually directly use these interpretations of the `timbre` field in your code.  The field is best used for things like comparison of segments (using euclidian distance or some other distance measure) to determine repetitive parts of a track, or perhaps to compare the "sounds" of two songs by clustering their segments' timbre vectors and calculating the distance between the cluster centroids of the two tracks. These are just a couple examples but they hopefully give a bit of insight into how these are useful.
