### ISSUE TITLE
Add Profile Type for Search API Endpoint

### ISSUE THREAD

**Issue by alfg** [spotify/web-api#95]
Hello, 

Are there any plans to add the `profile` type to the search API endpoint? It currently supports `album`, `artist`, `playlist`, and `track`. I see the Spotify client has this functionality, but I don't see it on the Web API:

https://developer.spotify.com/web-api/search-item/

I would like to get a user's list of public playlists by their username. However, in some cases, the `user_id` on the [User's Playlist API](https://developer.spotify.com/web-api/get-list-users-playlists/) may not be their username if they registered via Facebook. So adding the `profile` type to the search API would help find the `user_id` in this case.

Example:
`spotify:user:alfarf` - Profile's user_id as username.
`spotify:user:1247175885` - Another profile's user_id, probably registered from Facebook.

Thanks!
-Alf

**Comment by thelinmichael** [comment]
Hey @alfg! There are no short-terms on adding usernames to the API's search functionality unfortunately. Since this is the first feature request mentioning this, this Github issue will be a good place to update if/when changes occur, as well as enabling other users discuss and show support for this feature.

**Comment by alfg** [comment]
Thanks, @thelinmichael! I'll keep an eye on this thread. :)

**Comment by nikhilbedi** [comment]
+1

**Comment by kkoser** [comment]
+1

**Comment by surayashivji** [comment]
+1

**Comment by TheAtomicGoose** [comment]
+1

**Comment by adamazad** [comment]
+1

**Comment by dimitris-athanasiou** [comment]
+1

**Comment by KramerLewis** [comment]
+1

**Comment by arirawr** [comment]
Hey all,

As per our [new developer support process](https://github.com/spotify/web-api#creating-an-issue), any feature requests that have no plans to be considered in the next 6 months will be closed as wontfix.

We do not have any plans to implement this in the next 6 months and thus will close as wontfix.

We encourage you and other members of the community to continue to share use cases and your support for this feature, as it helps us prioritize features going forward. You will be able to comment on this issue even after it is closed. We will also post any updates here relating to this suggestion when they happen.
