### ISSUE TITLE
Consistently getting 502s for some users when saving albums/tracks

### ISSUE THREAD

**Issue by ehamberg** [spotify/web-api#950]
Issue found on 6 July 2018.

I have seen 502s for album and track saves for some access tokens for a little over a week now. Happy to provide specific tokens over a private channel if that will help you resolve this.

Thanks!

#### Endpoint(s):
* `PUT /v1/me/albums?ids={albumid}`
* `PUT /v1/me/tracks?ids={trackid}`

#### Scope(s):
* user-follow-modify
* user-library-modify
* playlist-modify-public
* user-read-email

#### Steps to reproduce:
Attempt to save an album to a user's account, with a valid access token:

```
PUT /v1/me/albums?ids=1dPGTztQgIPp0uEuq2773X HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Authorization: Bearer [hidden]
Connection: keep-alive
Content-Length: 0
Host: api.spotify.com
```

#### Expected behaviour:
A `200 OK` response.

#### Actual behaviour:
`502 Bad Gateway` error (consistently for some tokens)

```
HTTP/1.1 502 Bad Gateway
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: Accept, Authorization, Origin, Content-Type, Retry-After
Access-Control-Allow-Methods: GET, POST, OPTIONS, PUT, DELETE, PATCH
Access-Control-Allow-Origin: *
Access-Control-Max-Age: 604800
Alt-Svc: clear
Cache-Control: private, max-age=0
Content-Encoding: gzip
Content-Type: application/json; charset=utf-8
Date: Fri, 13 Jul 2018 06:38:06 GMT
Transfer-Encoding: chunked
Via: 1.1 google

{
    "error": {
        "message": "Something went wrong",
        "status": 502
    }
}
```

**Comment by bih** [comment]
Hello @ehamberg,

Thanks for reporting this issue. Sorry to hear you're having problems - we'll investigate with the Web API team and let you know about updates here!

**Comment by ehamberg** [comment]
Thanks, @bih. Just wanted to say that these issues persist. I have seen quite a few `502`s again today (e.g. at `2018-07-27 00:37:16.223`).

**Comment by bih** [comment]
@ehamberg That isn't good, sorry to hear! It's still on our list of task for investigating, hopefully we'll have some updates soon 🙂

**Comment by arirawr** [comment]
Closing this issue as we haven't been able to reproduce the behaviour. Feel free to reopen with detailed reproduction steps if you are still seeing the issue!

**Comment by ehamberg** [comment]
I won't be able to post the requests here as they contain user tokens, but I'd be happy to provide you with requests that get 502s over a different channel.
