### ISSUE TITLE
Cannot create playlist with new endpoint

### ISSUE THREAD

**Issue by blackarcanis** [spotify/web-api#951]
About this news:
[Changes to Playlist URIs coming to our APIs](https://developer.spotify.com/community/news/2018/06/12/changes-to-playlist-uris/)

#### Endpoint(s):
* `POST /v1/playlists`

#### Steps to reproduce:
1. Make a request on this endpoint

#### Expected behaviour:
Having a response with the playlist created returned.

#### Actual behaviour:
No response, no error, nothing.

**Comment by arirawr** [comment]
Hey @blackarcanis,
This issue is now resolved. The correct endpoint for creating a playlist was incorrectly labelled as `POST /v1/playlists` when it was actually `POST /v1/me/playlists`. We have fixed the issue and updated it in the original blog post.
