### ISSUE TITLE
Track JSON shape changed without notice: preview_url is now preview_urls

### ISSUE THREAD

**Issue by 0xNF** [spotify/web-api#952]
Returned track objects no longer contain `preview_url` field and instead contain a `preview_urls` field. Additionally, the format of the returned field has changed to include an additional `cid` query parameter. For example:  
https://p.scdn.co/mp3-preview/97cdc2d73f6ad2d49ee1dbd6e2c8d54faad0f5dc?cid=94197ced7ac64ef085002296d6674ea6  

Is there documentation for this change and what should I be aware of when working with this changed field?   

For reference, the current docs, [available here](https://developer.spotify.com/documentation/web-api/reference/object-model/#track-object-full), still say that tracks contain the old preview_url field.

**Comment by arirawr** [comment]
Hi @0xNF - I'm still seeing the `preview_url` field being returned. Could you provide an example of a call that returns `preview_urls` instead?

**Comment by 0xNF** [comment]
This was on the `get-current-user-saved-tracks` endpoint on of Friday July 13th, around 9:36pm UTC but it seems it's been reverted back.  

This is what the returned json looked like:

```json
```

**Comment by 0xNF** [comment]
It was on the 'https://api.spotify.com/v1/me/tracks` endpoint around Friday July13th around 9:36pm UTC.  

It seems to have reverted back now, and the endpoint is now returning the expected `preview_url` field.  

Here's what the returned json for a sample track looked like at that time.  
Note the `preview_urls` field:
```json
{
  "artists": [
    {
      "external_urls": {
        "spotify": "\"spotify\": \"https://open.spotify.com/artist/1z4g3DjTBBZKhvAroFlhOM\""
      },
      "href": "https://api.spotify.com/v1/artists/1z4g3DjTBBZKhvAroFlhOM",
      "id": "1z4g3DjTBBZKhvAroFlhOM",
      "name": "Red Velvet",
      "type": "artist",
      "uri": "spotify:artist:1z4g3DjTBBZKhvAroFlhOM"
    }
  ],
  "available_markets": [
        "...edited for brevity...."
  ],
  "disc_number": 1,
  "duration_ms": 194800,
  "explicit": false,
  "external_urls": {
    "spotify": "\"spotify\": \"https://open.spotify.com/track/2uUof8u18LCJwFLMwFm0zC\""
  },
  "href": "https://api.spotify.com/v1/tracks/2uUof8u18LCJwFLMwFm0zC",
  "id": "2uUof8u18LCJwFLMwFm0zC",
  "name": "Aitai-tai",
  "preview_urls": "https://p.scdn.co/mp3-preview/6f00b5c63ab7354889794b1f36a52372d835ca37?cid=94197ced7ac64ef085002296d6674ea6",
  "track_number": 2,
  "type": "track",
  "uri": "spotify:track:2uUof8u18LCJwFLMwFm0zC"
}
```

**Comment by arirawr** [comment]
Alright, good to hear it seems to have resolved itself! Feel free to reopen if you see the behaviour again.
