### ISSUE TITLE
Docs on start/resume a users playback are incorrect

### ISSUE THREAD

**Issue by idanlo** [spotify/web-api#955]
on [this](https://developer.spotify.com/documentation/web-api/reference/player/start-a-users-playback/) page of the docs there is an endpoint for resuming or stopping a users playback. There are options to change the playback to a different track or playlist. in the body parameters section it says in the uris parameter "A JSON array of the Spotify...." but on the context_uri it simply says a Spotify URI which is incorrect. If i send a request without with a parameter like this:
`{ context_uri: "spotify:album:1Je1IMUlBXcx1Fz0WE7oPT }` it won't work. but doing it like this will work:
` { "context_uri": "spotify:album:1Je1IMUlBXcx1Fz0WE7oPT" } `. i don't know why but this is how it is for me

**Comment by davidhernandeze** [comment]
You didnt close the string in the first one

**Comment by idanlo** [comment]
I'm sorry I didn't copy it right, I am sending it as a string so there are quotes on both sides

**Comment by idanlo** [comment]
I'm sorry I didn't copy it right, I am sending it as a string so there are quotes on both sides
