### ISSUE TITLE
invalid_client when authenticate

### ISSUE THREAD

**Issue by khamaileon** [spotify/web-api#96]
Please see: https://github.com/omab/python-social-auth/issues/703

**Comment by JMPerez** [comment]
@khamaileon Is there any way you can provide the resulting request (url being requested, HTTP verb, authentication header...)? We've seen developers having problems with this before and they used to be related to how the authentication header was composed.

See [Spotify Web API Bad Request Error “invalid_client” when refreshing token](http://stackoverflow.com/questions/25596936/spotify-web-api-bad-request-error-invalid-client-when-refreshing-token) and [Spotify WebAPI authorization - client credentials flow error invalid_client](http://stackoverflow.com/questions/26044062/spotify-webapi-authorization-client-credentials-flow-error-invalid-client).

**Comment by khamaileon** [comment]
method = 'POST'
url = 'https://accounts.spotify.com/api/token'
data = {
    'client_id': '611da437f92f45f69b2d22xxxxxxxxxx',
    'client_secret': '7382921a3e1d4decae2390xxxxxxxxxx',
    'code': 'AQCh_8yytEOGzGyDl2-4Yv_vRKprxFBzi0VKZqiVNmSo09V51fz9onkUzB-CRwmLuh645siaP_EcVmip-BHM20UYzm2vUkGwOqDtm91CDmT308dIfTIiDAKYcvjBg5VuxFl6QsO9KdIK3R3tGWqVtciVw6HCBDYo3i34vDqfh2NyTNQ0eJskwJONS0-bxxJqHPtKmFxxxxxxxxxx',
    'grant_type': 'authorization_code',
    'redirect_uri': 'http://ac.local:8000/complete/spotify/
'},
headers: {'Authorization': "Basic b'NjExZGE0MzdmOTJmNDVmNjliMmQyMmQ0NzI2YzAxN2Y6NzM4MjkyMWEzZTFkNGRlY2FlMjM5MGZhNxxxxxxxxxx='"}

**Comment by khamaileon** [comment]
It's was a bad authorization header format.
I submitted a fix : https://github.com/omab/python-social-auth/pull/704

**Comment by JMPerez** [comment]
@khamaileon great!
