### ISSUE TITLE
Get albums ever released from that artist, even hidden ones.

### ISSUE THREAD

**Issue by papin97** [spotify/web-api#960]
#### Endpoint(s):
* `/v1/artists/{id}/albums`

#### Scope(s):
* All scopes

#### Steps to reproduce:
1. Open the API Console
2. Call the `albums` endpoint with `id` field filled and `market` field empty (or make it XX).

#### Expected behaviour:
Get all albums ever released from the artist, including hidden one (for example: when I search with artist id `50l3hdnSiYODINDYhyP0QA`, it should return album `0cc0EF1hJ0TIictMprdsTu`, because it doesn't have market availability (market field is empty)).

#### Actual behaviour:
Only albums that has market availability filled will be shown in result.

**Comment by arirawr** [comment]
Hey @papin97,

This is expected behaviour for this endpoint, and we do not have any plans to change this in the next 6 months. I'm going to close this as wontfix.
