### ISSUE TITLE
New Features - user charts for sharing and share album

### ISSUE THREAD

**Issue by ashersquire** [spotify/web-api#962]
Hello,

I have a feature request that would differentiate your product from other streaming services: Individual user charts. 

Use case: User would be able to create and maintain a top 10 chart of their favorite current music. This would be able to be shared with friends. Friends could also search for a user and look that user chart if configured. My friends and I are always sending each other our favorite songs through messages but would be much better in your app through a chart so users can be proactive. 

Also the ability to share an album through Whatsapp and text message would be nice as you can only currently share songs. 

Let me know if you want further clarification or more information. 

Thanks for your interest in the Spotify Web API!
If you're submitting a bug, please use the following template.
If your issue is a feature request, please include your use-case so that we have all the necessary info.

-->

Issue found on February 19th 2015.

#### Endpoint(s):
* `GET /v1/users/{user_id}`

#### Scope(s):
* None (application is not using authentication)

#### Steps to reproduce:
1. Open the API Console
2. Call the `get-users-profile` endpoint with `user_id` `%5E`

#### Expected behaviour:
A public user object as described on `https://developer.spotify.com/web-api/object-model/#user-object-public`.

#### Actual behaviour:
500 Server Error (consistently)

**Comment by arirawr** [comment]
Hey @ashersquire! I'm happy to let you know that the API already has this kind of functionality in the form of [Get User's Top Artists and Tracks](https://developer.spotify.com/documentation/web-api/reference/personalization/get-users-top-artists-and-tracks/). You can get up to 50 of the user's top artists or tracks over three time periods, short term, medium term, and long term.

This issue tracker only deals with the Web API, but if this is something you'd like to see in our official apps, you can submit an idea over at https://community.spotify.com

Try it out in the console here: https://developer.spotify.com/console/get-current-user-top-artists-and-tracks/
