### ISSUE TITLE
F2 to rename playlists.

### ISSUE THREAD

**Issue by sigz321** [spotify/web-api#97]
Simple as topic. Just an enchancement idea from me as a well-versed Windows user. F2 renames files and folders in Windows. 

Thank you for adding "CTRL+F = search within playlists" function again <3

**Comment by asmitter** [comment]
Hi - this is an issue tracker for developers using the Spotify Web API.
Feedback and ideas for the clients can be posted over at the [Spotify Community](https://community.spotify.com/).
