### ISSUE TITLE
Desktop plugin dev using audio

### ISSUE THREAD

**Issue by datenstrudel** [spotify/web-api#972]
Hi, 

as `https://developer.spotify.com/support/` redirects me to the github board I am placing this non web api related question here.

I realize there are Desktop Plugins (like Equalify.me) that must have some sort of access to the actual audio stream in order to work.
My **question is where can I find documentation in order to implement a plugin that requires analysis of the audio stream**? 

It seems all options provided at https://developer.spotify.com are more or less related to either app or web development. Giving direction is apprecieated.

Best
ds

**Comment by 0xNF** [comment]
I don't think there's anything official published on this topic.  
Are you sure Equalify isn't just hooking the win32 process?

**Comment by datenstrudel** [comment]
Haven't thought about it, but sounds reasonable.

Sad anyway there doesn't seem to be an "official way". (?)

**Comment by arirawr** [comment]
Hey @datenstrudel!

We don't offer any direct access to the audio stream. We do, however, have audio analysis, which may help for your use case. It's available here: https://developer.spotify.com/documentation/web-api/reference/tracks/get-audio-analysis/

Hope that helps!
