### ISSUE TITLE
how to get a new refresh_token?

### ISSUE THREAD

**Issue by iagolaguna** [spotify/web-api#975]
Hello everyone, I'm following your Authorization guide and I'm confusing some things, if you can clarify some things for me. I will be glad.

Into second step of https://developer.spotify.com/documentation/general/guides/authorization-guide/#authorization-code-flow , you are saying:

![image](https://user-images.githubusercontent.com/17499030/43688098-0ccb2d78-98b9-11e8-9cad-b6b5c972f028.png)

Presuming this, code is equal a authorization code.
Into the same step, you are saying:
![image](https://user-images.githubusercontent.com/17499030/43688139-d70c34e2-98b9-11e8-943a-2aaf2e014846.png)
Presuming this, i understand that if i replace the `code` to the `refresh_token`  that has giving to me  and trigger a new request for `/api/token`, i will receive a new `refresh_token`, but this isn't true i'm receiving this follow message : 
![image](https://user-images.githubusercontent.com/17499030/43688179-a65d10ae-98ba-11e8-8b3f-7a44a5589364.png)

Into fourth step of https://developer.spotify.com/documentation/general/guides/authorization-guide/#authorization-code-flow , you are saying how i can refresh my token, and it's ok, but what i not understand is: 
 * don't i need a new `refresh_token`?
 * the `refresh_token` doesn't expire?
 * the api don't need send me a new `refresh_token` when  i refresh the `access_token`?

**Comment by jscholes** [comment]
When you use a refresh token to refresh an access token, you may or may not get back a new refresh token.  If you do, you should use it.  But refresh tokens are not documented as ever expiring unless your application is de-authorized by the user.

In other words: your refresh token can last forever.

**Comment by iagolaguna** [comment]
Wow thanks for answer me to fast.
Well if refresh token can last forever it's great! 
Thank you again.

**Comment by arirawr** [comment]
Seems like this is resolved. Thanks for the great answer @jscholes! Let me know if you have any other questions @iagolaguna :)
