### ISSUE TITLE
Account is closed and Spotify continues to take money of my card.

### ISSUE THREAD

**Issue by Michaelrodgerss** [spotify/web-api#977]
Issue found on February 19th 2015.

#### Endpoint(s):
* `GET /v1/users/{user_id}`

#### Scope(s):
* None (application is not using authentication)

#### Steps to reproduce:
1. Open the API Console
2. Call the `get-users-profile` endpoint with `user_id` `%5E`

#### Expected behaviour:
A public user object as described on `https://developer.spotify.com/web-api/object-model/#user-object-public`.

#### Actual behaviour:
500 Server Error (consistently)

**Comment by Michaelrodgerss** [comment]
Please closed my accounts for rodgersmichael82

**Comment by arirawr** [comment]
Hi @Michaelrodgerss - this forum is for support with the Spotify Web API and we are not able to help with your account. Please contact customer support here: https://support.spotify.com/us/
