### ISSUE TITLE
Functional issues with spotify widget 

### ISSUE THREAD

**Issue by meenal29oct** [spotify/web-api#978]
1)Spotify not functional on devices intermittently
2)Partner Article | Spotify frame hidden on firefox
3)Click on Forward/backward arrow hides the spotify frame

**Comment by arirawr** [comment]
Hi @meenal29oct! Could you please provide some reproduction steps or a link to where you see this behaviour?

**Comment by arirawr** [comment]
Hey there, as we haven't heard back from you with more information on this issue, we're going to close this issue as inactive. Please feel free to reopen and comment with the requested info so we can help you 🙂
