### ISSUE TITLE
New follow playlist endpoints?

### ISSUE THREAD

**Issue by PouleR** [spotify/web-api#979]
Since the introduction of the new playlist endpoints (and changes to the playlist URIs) I haven't found anything about changes to the playlist follow/unfollow endpoints.

Are they going to change as expected below?

#### Current endpoint(s):
* `PUT /v1/users/{user_id}/playlists/{playlist_id}/followers`
* `DELETE /v1/users/{user_id}/playlists/{playlist_id}/followers`

#### Expected endpoints:
* `PUT /v1/playlists/{playlist_id}/followers`
* `DELETE /v1/playlists/{playlist_id}/followers`

**Comment by bih** [comment]
Hello @PouleR,

I'm sure if you saw, but [we temporarily reverted those changes](https://developer.spotify.com/community/news/2018/06/12/changes-to-playlist-uris/):

> Update: Due to technical issues, we have rolled back the change originally scheduled for 11th September 2018. We will communicate a new date for the change as soon as we have one.

For that reason, I'll close this ticket. It has been raised with the Web API team. Once we re-introduce those changes feel free to open a new ticket if this is still an issue.
