### ISSUE TITLE
I need some personal help from a Spotify dev please - I am lost 

### ISSUE THREAD

**Issue by wskproductions** [spotify/web-api#983]
Issue found on February 19th 2015.

#### Endpoint(s):
* `GET /v1/users/{user_id}`

#### Scope(s):
* None (application is not using authentication)

#### Steps to reproduce:
1. Open the API Console
2. Call the `get-users-profile` endpoint with `user_id` `%5E`

#### Expected behaviour:
A public user object as described on `https://developer.spotify.com/web-api/object-model/#user-object-public`.

#### Actual behaviour:
500 Server Error (consistently)

**Comment by jscholes** [comment]
This is a public issue tracker.  Please edit your title and description to explain the issue(s) that you're experiencing so someone can help you.

**Comment by arirawr** [comment]
Hi @wskproductions - we'll need a little more info in order to help you out. Could you please edit your question to follow the issue template we provide?

**Comment by arirawr** [comment]
Hey there, as we haven't heard back from you with more information on this issue, we're going to close this issue as inactive. Please feel free to reopen and comment with the requested info so we can help you 🙂
