### ISSUE TITLE
Save response of web api allowed?

### ISSUE THREAD

**Issue by mapimagdich** [spotify/web-api#986]
Reading the Terms of Service for the Spotify Web API, developers are not allowed to aggregate data from the API.

I want to save the popularity values from the song (its a value from 1-100) once a day, so that the user can retrace the popularity values of a certain song in the past - unfortunately this is not possible with the current API, so I want to save this in a database:

What I want to save is:

    StreamX has popularity value 52 on 14.08.18

    StreamX has popularity value 58 on 15.08.18

    StreamX has popularity value 64 on 16.08.18

    ....

Is this allowed under the current terms of service of the WEB API?

**Comment by bih** [comment]
Hello @mapimagdich!

Unfortunately I'm not allowed to interpret the terms for legal reasons. There is one section (as of 15th August 2018) that mentions storing metadata:

> Do not improperly access, alter or store the Spotify Service or Spotify Content, including (i) using any robot, spider, site search/retrieval application, or other tool to retrieve, duplicate, or index any portion of the Spotify Service or Spotify Content (which includes playlist data) or collect information about Spotify users for any unauthorized purpose; (ii) making excessive service calls that are not strictly required for the proper functioning of your SDA via the Spotify Platform; (iii) **storing metadata** or cover art or aggregating metadata, cover art, audio, or other Spotify Content to create databases or any other compilation **other than as strictly necessary** to offer and operate your SDA; (iv) requesting, collecting, soliciting or otherwise obtaining access to user names, passwords, or other authentication credentials for the Spotify Service, other than through the means specifically provided for by the Spotify Platform and as strictly necessary to offer and operate your SDA or as expressly authorized by a Spotify user.

I do however encourage you to look through [our full Developer Terms of Service](https://developer.spotify.com/terms/) to check if your application is compliant. If in doubt, I encourage you to contact your legal representative.

Hope this helps!
