### ISSUE TITLE
Playlist arranging - improvement suggestion

### ISSUE THREAD

**Issue by meikonen** [spotify/web-api#987]
Hi I'm a heavy Spotify user and a starting playlist creator,

1. Would it be possible to add playlists, to combine so basically that I could drag a playlist and add the tracks from that playlist to another. this could come up with a question "are you sure?".
Or is there a way I dont know?

2. it would be nice if I could download a folder of different playlists at once to be listened offline.
is this someway possible?

Many thanks in advance

Elias

Issue found on February 19th 2015.

#### Endpoint(s):
* `GET /v1/users/{user_id}`

#### Scope(s):
* None (application is not using authentication)

#### Steps to reproduce:
1. Open the API Console
2. Call the `get-users-profile` endpoint with `user_id` `%5E`

#### Expected behaviour:
A public user object as described on `https://developer.spotify.com/web-api/object-model/#user-object-public`.

#### Actual behaviour:
500 Server Error (consistently)

**Comment by arirawr** [comment]
Hey @meikonen - thanks for the suggestion!

This issue tracker only deals with requests for our Web API. Suggestions for the official Spotify apps should be posted over at https://community.spotify.com/.
