### ISSUE TITLE
Get an artist id given user id (or vice versa)

### ISSUE THREAD

**Issue by patmanh** [spotify/web-api#99]
When artists authenticate with our application, we can get their user id (ie Alesso's is ``alessoofficial``). However, to get more info on Alesso (as an artist), we need to query the artist APIs with his artist id (``4AVFqumd2ogHFlRbKIjp1t``). I'm failing to see how I can figure out this mapping (or the reverse).

Is there any endpoint I can hit which will allow me to get the mapping between user ids and artist ids? Or anywhere else I can get/infer this data?

**Comment by thelinmichael** [comment]
Hi @patmanh! The mapping between artists and users is not exposed at the moment, but a similar issue has been raised in #10. I think it makes sense to merge these two issues, but please let me know if you think differently.

**Comment by patmanh** [comment]
Sounds good @thelinmichael - will follow that issue.
