### ISSUE TITLE
Player: Connected device returns "device.id: null"

### ISSUE THREAD

**Issue by simonfyi** [spotify/web-api#991]
Issue found on August 19th 2018.

#### Endpoint(s):
* `GET /v1/me/player`

#### Scope(s):
* `user-read-playback-state`

#### Steps to reproduce:
1. Open Spotify
2. Play any song
3. Select any device but your current under `Connect to a device`.
4. Open the API Console
5. Call the `get-user-player` endpoint with valid token

#### Expected behaviour:
Returns a (remote) `device object` with valid `device.id`.

#### Actual behaviour:
It returns a `device object` with null as `id`.
Example response:
```
"device": {
    "id": null,
    "is_active": true,
    "is_private_session": false,
    "is_restricted": true,
    "name": "Office",
    "type": "Speaker",
    "volume_percent": 10
  },
```

This results in not being able to control the player, for we don't have any valid active device.

**Comment by arirawr** [comment]
Hi @simonfyi, thanks for the report.

Some devices are not able to be controlled through the Spotify Connect Web API, as documented [here](https://developer.spotify.com/documentation/web-api/guides/using-connect-web-api/#devices-not-appearing-on-device-list). These uncontrollable devices will return a null ID. You can see all controllable devices by calling the `/v1/me/player/devices` endpoint (documentation [here](https://developer.spotify.com/documentation/web-api/guides/using-connect-web-api/#viewing-device-list)).

**Comment by simonfyi** [comment]
Thanks for the info, I see the `is_restricted` prop which I can use.
