### ISSUE TITLE
Change a Playlist's Details Broken in Web Console.

### ISSUE THREAD

**Issue by viking2917** [spotify/web-api#993]
Issue found on August 19th 2018.

The web console seems unable to change a playlist's public status from true to false. 

(note also that I am myself unable to change a playlist's public status from true to false via the api - but that is another bug report. (it's fine from the spotify client, just not via the api).

#### Endpoint(s):
* `PUT /v1/users/{user_id}/playlists/{playlist_id}`

#### Scope(s):
* (web console will list the required scopes, playlist-modify-public and playlist-modify-private, in the steps below, use Get Token to get the appropriate scopes.).

#### Steps to reproduce:
1. Open the API Console
2. Create a public playlist.
3. Go to the 'Change a Playlist's Details' page (https://developer.spotify.com/console/put-playlist/)
4. Fill in relevant details, hit "Try It". (Use Get Token to set the required scopes.
5. No response is listed in the page.
6. Open the console. Note that javascript has thrown an error about invalid JSON.

(the javascript error is: "Uncaught (in promise) SyntaxError: Unexpected end of JSON input
    at console.bundle.js:20799")

#### Expected behaviour:
The playlist's public status should change from true to false and the http response shown in the API web console.
#### Actual behaviour:
Nothing happens; the status is not changed and no output is shown.

See attached screenshots with details. 
![playlistcreated](https://user-images.githubusercontent.com/7691349/44318730-8d5e6200-a3d3-11e8-9eda-8e862155c659.png)
![modifydetails](https://user-images.githubusercontent.com/7691349/44318732-8fc0bc00-a3d3-11e8-9de6-99d6829e983c.png)
![consoleerror](https://user-images.githubusercontent.com/7691349/44318734-92231600-a3d3-11e8-82b5-ba513caab545.png)

**Comment by blackarcanis** [comment]
I can confirm, same issue on this endpoint:
PUT https://api.spotify.com/v1/playlists/{playlist_id}

Nothing is returned and nothing is changed on the playlist details.

**Comment by bih** [comment]
Hello @viking2917,

I just tested this and it works fine (updating both `name` and `public`). I'm not sure if we fixed it outside of this bug report itself, but it seems like it's resolved so I'll close the ticket. Feel free to re-open if you're continuing to have issues 🙂
