### ISSUE TITLE
Discover Weekly Playlist not found

### ISSUE THREAD

**Issue by andreatoso** [spotify/web-api#996]
I'm trying to fetch the "Discover Weekly Playlist" through web-api using this end-point: 
`GET v1/users/spotify/playlists` and with my clientId, clientSecret and accessToken
The response gives me a list of 1527 playlists (Today's Top Hits, RapCaviar, etc.) but the "Discover Weekly Playlist" is not in this list. How can I solve this issue?

**Comment by grantbrewster** [comment]
Did you solve this? What is the correct endpoint? I am trying to access the Discover Weekly playlists of authenticated individuals that do not have the Discover Weekly playlist saved. Thanks!

**Comment by andreatoso** [comment]
@grantbrewster I didn't solve this, and apparently there's no solution.

**Comment by vastus** [comment]
You can get the "Discover Weekly" playlist from the playlists endpoint [`/v1/me/playlists`](https://developer.spotify.com/documentation/web-api/reference/playlists/get-a-list-of-current-users-playlists/). Make sure to request the [`playlist-read-private`](https://developer.spotify.com/documentation/general/guides/scopes/#playlist-read-private) scope.

Try it out in the [console](https://developer.spotify.com/console/get-current-user-playlists/).

**Comment by grantbrewster** [comment]
@vastus Thanks for the input, unfortunately it looks like this only works if the individual user has clicked "follow" on the Discover weekly playlist. Is it possible maybe using https://developer.spotify.com/console/get-category-playlists/ to get a categories playlist and somehow get the category "Made For You"? Do you have any idea if this is possible?

**Comment by vastus** [comment]
> unfortunately it looks like this only works if the individual user has clicked "follow" on the Discover weekly playlist

I'm not sure how it works but this is what I found from the docs:

> New to Spotify? 
>
> We need to get to know you and the music you like, so expect to receive your Discover Weekly playlist after a few weeks of listening. 
> https://support.spotify.com/uk/using_spotify/playlists/discover-weekly/

**Comment by esolitos** [comment]
Just want to add to this that it seem that if a user "Follows" multiple "Discover Weekly", there's no way to know which one is theirs and which is not from the API. :(
